### ISSUE TITLE
pybind, virtual overrides: Improve error messages for return-value-cast-errors

### ISSUE THREAD

**Issue by EricCousineau-TRI** [RobotLocomotion/drake#10016]
Not clear if this is due to our fork or not, but @sherm1 ran into an issue where implementing overrides gave mysterious errors:
```
    simulator.StepTo(args.duration)
TypeError: StepTo(): incompatible function arguments. The following argument types are supported:
    1. (self: pydrake.systems.analysis.Simulator_[float], arg0: float) -> pydrake.systems.analysis.StepToResult

Invoked with: <pydrake.systems.analysis.Simulator_[float] object at 0x7f60d4fd21f0>, 0.1
```

The issue was the the method should return a status object, but instead returned `None`; most likely, the `py::cast_error` was somehow caught as a argument casting error, rather than a return value casting error.

Depending on the outcome of #9292, the priority of this may change.

**Comment by jwnimmer-tri** [comment]
For status-returning bindings, typically we should allow `std::optional<Result>` so that the Python code can return None.  Then, the binding and decide what to say about that (either choose a default value, or throw a nice error message).
