### ISSUE TITLE
MAKE TEST: LC singleton fail: java.net.SocketException: Can't assign requested address

### ISSUE THREAD

**Issue by tarquasso** [RobotLocomotion/drake#1006]
Running the following tests within Matlab were unsuccessful:
- StateMachineControl.run() in the examples/PlanarMonopodHopper directory ended with a warning.
- runLQR in the examples/Quadrotor directory caused the Matlab 2014b instance to crash.
 
Ran 
$make test 
in the drake-distro folder, it was running for 2.5 hours. 
A few of the tests either failed or timed out.

84% tests passed, 58 tests failed out of 373

Total Test time (real) = 10219.84 sec

The following tests FAILED:
	  5 - solvers/+drakeFunction/+euclidean/+test/normSquaredTest (Failed)
	  6 - solvers/+drakeFunction/+euclidean/+test/signedDistanceToHyperplaneTest (Failed)
	  7 - solvers/+drakeFunction/+euclidean/+test/smoothNormTest (Failed)
	 18 - solvers/test/rrt_piano_mover (Failed)
	 19 - solvers/test/rrt_piano_mover_rotation (Failed)
	 20 - solvers/test/rrt_piano_mover_translation (Failed)
	 27 - solvers/test/testTaskSpaceRRT (Failed)
	 33 - systems/plants/constraint/test/AllBodiesClosestDistanceConstraintTest (Failed)
	 34 - systems/plants/constraint/test/RelativeGazeTargetConstraintTest (Failed)
	 35 - systems/plants/constraint/test/RelativePositionConstraintTest (Failed)
	 36 - systems/plants/constraint/test/RelativeQuatConstraintTest (Failed)
	 37 - systems/plants/constraint/test/WorldPositionInFrameConstraintTest (Failed)
	 38 - systems/plants/constraint/test/testKinCnst (Timeout)
	 48 - systems/plants/test/bullet_collision_closest_distance_jac_test (Failed)
	 51 - systems/plants/test/collisionDetectBoxTest (Failed)
	 52 - systems/plants/test/collisionDetectCHullTest (Failed)
	 53 - systems/plants/test/collisionDetectCapsuleTest (Failed)
	 56 - systems/plants/test/collisionDetectSphereTest (Failed)
	 65 - systems/plants/test/momentumTest (Failed)
	 93 - systems/plants/test/testIK (Timeout)
	111 - systems/plants/test/testRigidBodyBluffBody (Failed)
	112 - systems/plants/test/testRigidBodyInertialMeasurementUnit (Failed)
	115 - systems/plants/test/testRigidBodyWingChangingParams (Failed)
	116 - systems/plants/test/testRigidBodyWingWithControlSurface (Failed)
	117 - systems/plants/test/testRigidBodyWingWithControlSurfaceOnlyControlSurface (Failed)
	125 - systems/plants/test/testURDFmex (Failed)
	139 - systems/test/runPendulum (Failed)
	140 - systems/test/testLCMVisualizer (Failed)
	161 - util/test/taylorTest (Failed)
	195 - util/test/trigPolyTest (Failed)
	250 - examples/Atlas/test/testIndividualCentersOfPressure (Failed)
	254 - examples/Atlas/test/testRunningPlanner (Timeout)
	258 - examples/CartPole/CartPoleEnergyShaping.run (Failed)
	290 - examples/Pendulum/PendulumEnergyControl.run (Failed)
	291 - examples/Pendulum/runDLQR (Failed)
	292 - examples/Pendulum/runLQR (Failed)
	293 - examples/Pendulum/runLQRtest (Failed)
	294 - examples/Pendulum/runPassive (Failed)
	296 - examples/Pendulum/runSwingUp (Failed)
	297 - examples/Pendulum/runTrajectorySwingUpAndBalance (Failed)
	298 - examples/Pendulum/runTrigLQR (Failed)
	299 - examples/Pendulum/runValueIteration (Failed)
	302 - examples/Pendulum/test/polyFeedback (Failed)
	303 - examples/Pendulum/test/runPendLCMControl (Failed)
	304 - examples/Pendulum/test/testFeedback (Failed)
	306 - examples/Pendulum/test/testLCMPlant (Failed)
	307 - examples/Pendulum/test/trigPolyTest (Failed)
	308 - examples/Pendulum/test/tvlqrRestartTest (Failed)
	309 - examples/Pendulum/test/tvlqrTest (Failed)
	310 - examples/Pendulum/test/urdfDynamicsTest (Failed)
	316 - examples/Quadrotor/Quadrotor.runOpenLoop (Failed)
	318 - examples/Quadrotor/runDircolWObs (Failed)
	321 - examples/Quadrotor/test/buildOcTree (Failed)
	331 - examples/RimlessWheel/runPassiveLCP (Failed)
	332 - examples/RimlessWheel/test/testContactGradients (Failed)
	333 - examples/RimlessWheel/test/testLCPgradients (Failed)
	335 - examples/SimpleDoublePendulum/runEndPointJac (Failed)
	340 - examples/SimpleFourBar/runLQR (Failed)
Performing coverage
 Cannot find any coverage files. Ignoring Coverage request.
Submit files (using http)
   Using HTTP submit method
   Drop site:http://kobol.csail.mit.edu/cd/submit.php?project=Drake
   Uploaded: /Users/rkk/softrobotics-git/drake-distro/drake/pod-build/Testing/20150418-1323/Build.xml
   Uploaded: /Users/rkk/softrobotics-git/drake-distro/drake/pod-build/Testing/20150418-1323/Configure.xml
   Uploaded: /Users/rkk/softrobotics-git/drake-distro/drake/pod-build/Testing/20150418-1323/Test.xml
   Submission successful
Errors while running CTest

The problems seem to have at least partially to do with one of these errors:

a) STARTUP ISSUE:
This indicates a potentially serious problem in your MATLAB setup, which should be resolved as soon as possible.  Error detected was:
MATLAB:run:FileNotFound
../../softrobotics-git/drake-distro/addpath_pods not found. 
> In matlabrc at 228 
To reproduce this test use rng(968673823,'twister’)

My matlab startup folder is:
/Users/rkk/Documents/Matlab
It contains a 'startup.m’ file with this content:
run('../../softrobotics-git/drake-distro/addpath_pods’)
the drake distro sits here:
/Users/rkk/softrobotics-git/drake-distro/
Is that startup.m file content wrong?

b) ALL NETWORK TRAFFIC BROADCAST TO NETWORK:
> In addpath_drake at 74
  In addpath_drake at 4 
 Added the lcm jar to your javaclasspath (found via cmake)
Warning: Currently all of your LCM traffic will be broadcast to the network, because:
  Route to multicast channel does not run through the loopback interface.
  Consider running: sudo /Users/rkk/softrobotics-git/drake-distro/drake/util/setup_loopback_multicast.sh

Shall I just run:  sudo /Users/rkk/softrobotics-git/drake-distro/drake/util/setup_loopback_multicast.sh ?

c) CAN’T ASSIGN ADDRESS:
> In checkDependency at 62
  In checkDependency at 73
  In collisionDetectTest at 19
  In collisionDetectSphereTest at 2
  In fevalPackageSafe at 21 
 Added the lcmgl jar to your javaclasspath (found via cmake)
LCM: Disabling IPV6 support
LCM: TTL set to zero, traffic will not leave localhost.
LC singleton fail: java.net.SocketException: Can't assign requested address

Is that because I am on a hotel wifi, that does not allow LCM to broadcast? Or something else?

**Comment by RussTedrake** [comment]
#2 - yes.  Follow the instructions displayed on the screen.

#3 - as i said, search for yosemite on the drake github issues, you should find an easy fix.

#1 is probably #3.

**Comment by tarquasso** [comment]
Thanks a lot, so this fixed it:
a) STARTUP ISSUE by changing 'startup.m' content to:
warning('off','Drake:DisablingSimulinkAutosave')
run('<fullpathto>/drake-distro/addpath_pods')

b) ALL NETWORK TRAFFIC BROADCAST TO NETWORK: $sudo <pathto>/drake-distro/drake/util/setup_loopback_multicast.sh

-c) CAN’T ASSIGN ADDRESS by following #558
