### ISSUE TITLE
add keyboard 'gaming' support to python teleop guis.

### ISSUE THREAD

**Issue by RussTedrake** [RobotLocomotion/drake#10060]
@rcory got feedback that it might be a much more user-friendly way to pilot the robot.

pygame can definitely do it.  not sure yet if there is a recommended way to do it with tkinter (which is a lighter dependency).  will take a look.

**Comment by EricCousineau-TRI** [comment]
We are still using `pygame` for some automotive demos, so if it's easier, perhaps we could start with that?

**Comment by RussTedrake** [comment]
yup.  was thinking that if tkinter could do it, we could drop the relatively more heavy pygame dependency (because this is basically the only thing we are using pygame for).  but using pygame is probably the lowest friction solution.

**Comment by rcory** [comment]
@RussTedrake I think we're just about ready to need this feature, so thought I'd bubble this back up. Thanks.

**Comment by RussTedrake** [comment]
Thanks!
