### ISSUE TITLE
Port attic/manipulation/dev/quasistatic to multibody/

### ISSUE THREAD

**Issue by RussTedrake** [RobotLocomotion/drake#10079]
Requires cleaning / test coverage in addition to porting from RBP => MBP/SceneGraph.

I would also like to think about improving the performance of the solver, by considering stronger MI formulations and warm-starting.  cc @TobiaMarcucci , @pangtao22 

My motivation for this is that the current models of the iiwa has state variables related to the integral terms in the PID controller, and implementing this sort of soft prescribed motion (e.g. obtains the closest motion to the commanded motion that does not violate constraints) feels like a fundamentally better model.  Strictly speaking i don't need to also add the quasi-static constraints also, but this has the nice benefit of further reducing the state space, and (likely) being reasonable for most of our simulations.

**Comment by jwnimmer-tri** [comment]
In #12283 we are considering marking the attic copy for deprecation, to be removed from master in three months.  Would that substantially interfere with this porting, or any other ongoing uses of the quasistatic system code?  For porting at least, grabbing the file from git history should be easy.  Not sure if there are other concerns.
