### ISSUE TITLE
Logic upstream of `LeafSystem::DeclareVectorOutputPort` is brittle for 0-sized vectors

### ISSUE THREAD

**Issue by EricCousineau-TRI** [RobotLocomotion/drake#10105]
From https://github.com/RobotLocomotion/drake-external-examples/issues/120:

> With drake @ 4c9dc10, `LeafSystem::CreateCachedLeafOutputPort` determines if it's vector-valued or abstract-valued based on the following snippet of code:
> ```
> fixed_size == 0 ? kAbstractValued : kVectorValued
> ```
> Using `-DRUN_X11_TESTS=ON` for `drake_cmake_installed`, the test fails as:
> ```
> DiagramBuilder::Connect: Cannot mix vector-valued and abstract-valued ports while connecting output port y0 of System drake/systems/RigidBodyPlant@00007fb8f880e600 to input port rgbd_camera_u0 of System drake/systems/sensors/RgbdCameraDiscrete@00007fb8f85b5390
> ```
> 
> If there is a tree that has all fixed elements, this will fail. Workaround is to just add something floating; fix is to make this less brittle.
> 

Code that is failing looks like this:
https://github.com/RobotLocomotion/drake-external-examples/blob/c9d182f5f001a67502aedc8f8186fcb07cf513c7/drake_cmake_installed/src/pcl/drake_camera_example.cc#L61-L64

@sherm1 Is it OK if I assign this to you for now?

\cc @jamiesnape

**Comment by sherm1** [comment]
Yup, zero was a bad choice to mean "abstract"!

**Comment by EricCousineau-TRI** [comment]
This is dududududududuplicate of #10864.
