### ISSUE TITLE
MultibodyPlant MapVelocityToQDot() and MapQDotToVelocity() return NaNs...

### ISSUE THREAD

**Issue by edrumwri** [RobotLocomotion/drake#10135]
...when MBP is constructed using a strictly positive time step argument.

Apparently related to #9171.

**Comment by amcastro-tri** [comment]
do you have an example code to reproduce this failure @edrumwri? 
I am surprised because this method gets called (with time step positive) all the time [here](https://github.com/RobotLocomotion/drake/blob/master/multibody/multibody_tree/multibody_plant/multibody_plant.cc#L1362).

**Comment by edrumwri** [comment]
If you want to reproduce this, change "timestep = 0.0" to "timestep = 0.1" (or the like) in multibody_tree_test.py, Line 632. The upshot is that MBP::DoMapVelocityToQDot(.) silently returns (multibody_plant.cc:1398) if the system is discrete, so you never know that the mapping failed.

My BasicVector was initialized to NaNs (feature rather than bug, I expect), which means that the NaNs that were "returned" were just never set.

**Comment by amcastro-tri** [comment]
ah! yeah, that does seem like a bug. I can see how someone might want to call this method as you did.
