### ISSUE TITLE
Drake GSG should have Drake favicon, not Google

### ISSUE THREAD

**Issue by jwnimmer-tri** [RobotLocomotion/drake#10162]
See https://drake.mit.edu/styleguide/cppguide.html; we should have the Dragon, not the G.

**Comment by soonho-tri** [comment]
https://github.com/RobotLocomotion/styleguide/pull/15

**Comment by soonho-tri** [comment]
<img width="507" alt="screen shot 2018-12-07 at 3 02 33 pm" src="https://user-images.githubusercontent.com/20779767/49670009-2d96d000-fa31-11e8-8e00-782cf389441b.png">
