### ISSUE TITLE
mbp: Make plan to improve maintainability

### ISSUE THREAD

**Issue by EricCousineau-TRI** [RobotLocomotion/drake#10194]
Once #9366 is resolved, MBP will be massive interface. Per @sammy-tri's [comment](https://reviewable.io/reviews/robotlocomotion/drake/10128#-LTTllk_Eu19yzwkdhDr), we should make a plan to improve the maintainability.

**Comment by EricCousineau-TRI** [comment]
Per f2f with @amcastro-tri about #9963, we could potentially see public API for element-based computations as a way to make the MBP interface more maintainable (#10194); if the indirection becomes `Element.Calc(context) -> Tree.Calc(context, element)` vs. the present `Plant.Calc(context, element) -> Tree.Calc(context, element)`, then it could be possible for us to remove the relevant public `Plant.Calc(...)` methods to component-ize these computations and reduce the number of methods shoved into `MultibodyPlant`.

@sammy-tri @sherm1 Can I ask what y'all think about this? Does this have an OK smell to it?

**Comment by sherm1** [comment]
I enthusiastically support this idea! Asking a body for its location is _so_ much nicer than asking MBPlant to find the body and do it for you.

**Comment by amcastro-tri** [comment]
API implemented in #10206 if you are curious.

**Comment by EricCousineau-TRI** [comment]
In f2f with @avalenzu, prompted by #10215, both he and I agree that it will be nice to start removing `*InWorld(...)` overloads, and rather promote the usage of explicit frame usage. Things like the expressed-in frame could be optional, and just default to the measured-in frame. (We didn't agree on whether the measured-in frame should default to `world`, though.)

While I understand that we want to have sugar methods for usability, we should try to minimize the number of overloads (like what we've done with `JacobianWrtVariable`).

@amcastro-tri @sherm1 Would it be OK if we start tending toward this direction?

**Comment by sherm1** [comment]
I like reducing the number of APIs _in theory_ but the InWorld sugar can be much easier to use and in many cases are all that anyone needs. The general methods require a deeper understanding of frames than many people are comfortable with. So my first thought is that I'd rather we keep these around, especially if they are useful in pedagogical examples.

**Comment by amcastro-tri** [comment]
Both APIs are now available in master. Maybe you guys can take them for a spin and see if you like/dislike them?

**Comment by EricCousineau-TRI** [comment]
To me, the better step would be to say "Can we live with the more explicit overloads", where we don't have the sugar, but yeah, it's what we got, so will see if I can tend towards those myself.
---
@mitiguy Following up from #9971: Dumb question, but is `CalcFrameJacobianWrtVExpressedInWorld` effectively a sugar for `CalcJacobianSpatialVelocity`?
If so, I'd like to elect that we do less work and leave out the explicit spelling to minimize number of overloads for maintainability.

**Comment by EricCousineau-TRI** [comment]
Er, then I'm not sure if I understand the reason for renaming `CalcFrameJacobianWrtVExpressedInWorld`.
If we want `CalcJacobianSpatialVelocity`, we should really just deprecate the former, and point to the new hotness, and not add a new-and-soon-to-be-removed name - less work?

**Comment by sherm1** [comment]
(@mitiguy is out tomorrow so I'm responding)
@EricCousineau-TRI your last comment is what Paul and I discussed and I think what he meant above. His laptop is too feeble for a decent all-Drake build and his Puget has a cable on order, so he's using CI to see whether he's breaking anything but has several revisions to go. The plan is to chop down the number of methods by switching them all to using the JacobianWrtV/QDot enum, and nuking the "FrameJacobian" "Geometric" "Analytic" and other disfavored terms all to match the new simpler names. The "InWorld" sugar is likely to survive though due to its ubiquitous utility and reduced complexity.

**Comment by amcastro-tri** [comment]
My preference is to strictly stick to what we all [agreed in this design document](https://docs.google.com/document/d/1MZRIKs4OOyQy2qGSzJsqkuVLGSeHUUGJ5AVA4mGC5js/edit). According to that document the steps are:
1. Deprecate `CalcPointsGeometricJacobianExpressedInWorld()` and `CalcPointsAnalyticalJacobianExpressedInWorld()`. Refactor to single method `CalcJacobianTranslationalVelocityExpressedInWorld()` (maintain the useful, though refactored, overload for when points are already expressed in the world frame, as [here](https://github.com/RobotLocomotion/drake/blob/master/multibody/plant/multibody_plant.h#L1436)).
2. `CalcBiasForPointsGeometricJacobianExpressedInWorld()` --> `CalcBiasForJacobianTranslationalVelocityExpressedInWorld()`
3. `CalcFrameGeometricJacobianExpressedInWorld()` --> `CalcJacobianSpatialVelocityExpressedInWorld()`.
4. `CalcBiasForFrameGeometricJacobianExpressedInWorld()` --> `CalcBiasForJacobianSpatialVelocityExpressedInWorld()`.
5. `CalcRelativeFrameGeometricJacobian()` --> `CalcJacobianSpatialVelocity()`

Probably to put all this under a common `@name` section describing common terminology (such as the use of `Jv` or `Jqdot` and frames conventions). @avalenzu wrote a nice piece of documentation following these guidelines [here](https://github.com/RobotLocomotion/drake/blob/master/multibody/plant/multibody_plant.h#L1705).

**Comment by sherm1** [comment]
I believe that matches what @mitiguy and I discussed yesterday. The existing PR created some confusion but is "do not review" and not intended as the final stop. I'll review the actual version against the above plan when it's ready.

**Comment by mitiguy** [comment]
I agree with all your comments and apologize for the confusion.
As Sherm mentioned, I sometimes use CI to do my builds (e.g., for multibody plant or tree) and labeled the PR as "do not review" -- but I should have added a comment directly to this thread to avoid problems on this "Jacobian Epic" hot topic.  So to summarize:
1.  Much more to do before any of this will be reviewed.
2.  Looking forward to my new build machine.
3.  Will be taking some family vacation time -- back on Tuesday January 8th.
     I may not be easily reachable except by cell phone 650-346-9595  (voice-only, no text).
     Feel free to call as the spirit moves you :)
4.  Happy Holidays to you -- I greatly appreciate all we do !

**Comment by mitiguy** [comment]
Responding to your question - these names are temporary place holders.  I am using CI to do my builds so labelled this temporary work in my PR as "Do not review".  Please ignore my temporary work.  Good news is that I have a new build machine -- and will soon not need CI to do my time-consuming builds.

**Comment by jwnimmer-tri** [comment]
If there is still work we plan to do, we can open a specific issue about it.  This issue is not sufficiently crisp to keep open for 6 years in this state.
