### ISSUE TITLE
Calling symbolic::Polynomial::decision_variables() is very slow

### ISSUE THREAD

**Issue by hongkai-dai** [RobotLocomotion/drake#10229]
I just found when I call `Polynomial::AddProduct` https://github.com/RobotLocomotion/drake/blob/07cd8f081b52b06547c852edf001a133c951a899/common/symbolic_polynomial.cc#L642-L646, 99.46% of time is spent on `CheckInvariant`. And inside `CheckInvariant`, 90% of time is spent on calling `decision_variables()` in https://github.com/RobotLocomotion/drake/blob/07cd8f081b52b06547c852edf001a133c951a899/common/symbolic_polynomial.cc#L666-L667

Here is the callgrind output of my test.
[callgrind.out.28429.zip](https://github.com/RobotLocomotion/drake/files/2680953/callgrind.out.28429.zip)
together with a screenshot visualized in kCachegrind
![screenshot from 2018-12-14 08-26-37](https://user-images.githubusercontent.com/6314000/50014891-0e8cc680-ff7a-11e8-8a30-287c6de35aad.png)

I would like to propose two improvements
1. We call `CheckInvariant` only in the debug mode.
2. `Polynomial` stores `decision_variables_` and `indeterminates_`. It also updates `decision_variables_` and `indeterminates_` inside any of its non-cost methods that changes to `indeterminates_` and `decision_variables_`.

@soonho-tri what do you think?

**Comment by soonho-tri** [comment]
From f2f,

For 1), we can first change `AddProduct` and check the performance. The goal is to keep the invariant checks for the user-facing APIs.

For 2), I think it's the right direction, but we agree that it might actually slows things down as we need to update the fileds. I'll first experiment the idea and check the performance.
