### ISSUE TITLE
MultibodyPlant::GetFrameByName segfaults when invalid frame name matches model instance name

### ISSUE THREAD

**Issue by rcory** [RobotLocomotion/drake#10243]
Take the following example, where a new model is added to the `MultibodyPlant` and subsequently queried with an _invalid frame name_ (which happens to match the name of the newly added model instance):

```
const multibody::ModelInstanceIndex new_model = 
    parser.AddModelFromFile(sdf_path, "foo");
const auto& child_frame = plant_->GetFrameByName("foo", new_model);
```
This code produces a segfault. Given that the provided name is invalid, this should instead produce a run-time error alerting the user that the provided frame name is invalid.

**Comment by tarquasso** [comment]
👍

**Comment by amcastro-tri** [comment]
I just tried this. I do however get an exception with the message: 
> "There is no frame named 'foo' in model instance 'foo'."

Could you provide a code snippet and SDF file to reproduce this?
or even better @rcory and @tarquasso, maybe one of you could get a back-trace and locate the origin? gdb is great at that.

**Comment by jwnimmer-tri** [comment]
Closing for lack of repro.
