### ISSUE TITLE
ComputeSignedDistancePairwiseClosestPoints should compute sphere-to-sphere distance in the closed form

### ISSUE THREAD

**Issue by hongkai-dai** [RobotLocomotion/drake#10270]
Currently when we compute the signed distance between spherical objects in `ComputeSignedDistancePairwiseClosestPoints()` https://github.com/RobotLocomotion/drake/blob/master/geometry/query_object.h#L184~L185, the code resorts to FCL's GJK/EPA implementation. It approximates the spheres as polytopes, and computes the signed distance using an iterative algorithm. This is both inefficient and inaccurate. Instead we should be able to compute the signed distance between spheres in the closed form.

There are two solutions to this problem
1. Inside `ComputeSignedDistancePairwiseClosestPoints()`, it first detects if the objects are spheres. If yes, it calls a special routine to compute the distance in the closed form.
2. Fix the problem in FCL's upstream. In the signed distance query in FCL, it should have a special routine to compute the signed distance between spheres.

Solution 1 is probably a quicker fix.

**Comment by SeanCurtis-TRI** [comment]
I've got a live FCL commit that will allow specific primitive tests for the *signed* distance queries. I'll submit it to FCL in the next little bit (right after I dig out of my holiday hole).

**Comment by DamrongGuoy** [comment]
Thank you, @SeanCurtis-TRI.  Please keep us updated on FCL.  I update that a quick fix in Drake by PR #10281 will be ready for review when PR #10148 landed.  Happy New Year!

**Comment by DamrongGuoy** [comment]
Fixed by #10281.
