### ISSUE TITLE
Python PATH is Broken on Mac High Sierra

### ISSUE THREAD

**Issue by liangfok** [RobotLocomotion/drake#10304]
See the errors here:

https://drake-jenkins.csail.mit.edu/view/Nightly%20Production/job/mac-high-sierra-unprovisioned-clang-bazel-nightly-release/35/

```
env: python2: No such file or directory
...
//:py/install_test                                                       FAILED in 0.9s
```

This is likely due to a Bazel update. An RC file likely needs the following to be added:

```
--action_env=PATH=/usr/local/bin:/usr/bin:/bin
```

**Comment by jamiesnape** [comment]
Relates https://github.com/bazelbuild/bazel/issues/6648.

**Comment by EricCousineau-TRI** [comment]
Would adding this to `install_prereqs_user_environment` for Mac make it work?

**Comment by jamiesnape** [comment]
It would, though technically this is not a Mac issue.

**Comment by jamiesnape** [comment]
I imagine the analog for Linux would be `--action_env=PATH=/usr/local/bin:/usr/bin`.

**Comment by jamiesnape** [comment]
I think this also makes our own version of the `bzl` `which()` function redundant, but that is not going to break anything.

**Comment by jwnimmer-tri** [comment]
> I think this also makes our own version of the bzl which() function redundant, but that is not going to break anything.

Not quite.

(1) When our `//tools/workspace` rules are used from a `bazel_drake_external`, we don't know what the action `$PATH` will be.  I think its still good to ignore whatever the user configured, at least by default.

(2) I'm not sure that `build --action_env` affects, e.g., `bazel fetch //...`.
