### ISSUE TITLE
Additional unit tests for `ComputeSignedDistanceToPoint` for `Box`.

### ISSUE THREAD

**Issue by DamrongGuoy** [RobotLocomotion/drake#10335]
Follow up to #10148.  We would like to set up additional unit tests for `ComputeSignedDistanceToPoint` for `Box`.  We should consider:
1. Query points outside the box nearest to one of the 6 faces, the 12 edges, and the 8 vertices of the `Box`.
2. Query points on the boundary of the box exactly on one of the 6 faces, the 12 edges, and the 8 vertices of the `Box`.
3. Non-symmetric box dimensions, for example, 20x30x10 in addition to the current symmetric dimensions 20x10x10.

**Comment by SeanCurtis-TRI** [comment]
As for the non-symmetric dimensions, I'd suggest that they be in place of the current symmetric. I don't see that the symmetric values give you any additional testing that the non-symmetric would provide. Although, if you do see one, you can ignore this.

**Comment by DamrongGuoy** [comment]
Fixed by #10481.
