### ISSUE TITLE
jenkins: Colored output obscures console and plain text views

### ISSUE THREAD

**Issue by EricCousineau-TRI** [RobotLocomotion/drake#10334]
Related #10333; however, in this case, the colored output in Jenkins `Console Output` still has some bits obscured:

> ![image](https://user-images.githubusercontent.com/26719449/50619656-732ba900-0ec8-11e9-98d8-eef2e2efeeea.png)

Additionally, the plain text is also difficult to read:

> ![image](https://user-images.githubusercontent.com/26719449/50619668-9a827600-0ec8-11e9-993a-95aec905999e.png)

It'd be nice to have the `Console Output` show up correctly.
Additionally, if there is an easy way to scrub color escape sequences from text, it'd be nice to have some sort of purely plain text view available.

**Comment by jamiesnape** [comment]
Relates jenkinsci/ansicolor-plugin#145 ?

**Comment by jamiesnape** [comment]
I will try to downgrade the plugin, but it requires a restart of Jenkins so it won't happen particularly soon.

**Comment by EricCousineau-TRI** [comment]
Resolved by downgrading the plugin.
