### ISSUE TITLE
py lint: Warn when `assert(...)` is used instead of `assert ...`

### ISSUE THREAD

**Issue by EricCousineau-TRI** [RobotLocomotion/drake#10372]
Came up here: https://reviewable.io/reviews/robotlocomotion/drake/10368#-LVkUP2r8K7uFIz1xV1d

Rationale: Rationale: https://stackoverflow.com/a/3112178/7829525
(Not using parentheses will help avoid the snafu of accidentally making an always-true assertion.)

**Comment by jwnimmer-tri** [comment]
See https://peps.python.org/pep-0679/ for recent discussions, where they might fix Python to DWIM.

Also as of Python 3.8, we have a SyntaxWarning for this kind of mis-use.  For me, that all seem good enough to close this as not requiring any linter changes on Drake's part.

Feel fee to comment/reopen if anyone disagrees.
