### ISSUE TITLE
atlas mimoCascade commands generate a ridiculous number of warnings about unconnected inputs

### ISSUE THREAD

**Issue by RussTedrake** [RobotLocomotion/drake#1038]

**Comment by RussTedrake** [comment]
couldn't reproduce this today (not sure why i saw them before).

**Comment by rdeits** [comment]
Were you possibly running a test with the old controller? The new one doesn't use any mimoCascades at all

**Comment by RussTedrake** [comment]
Ah.  Could have been.  In that case, i'm still happy calling it (at least temporarily) resolved.
