### ISSUE TITLE
py symbolic: DeprecationWarning not raised by `e_xv == e_yv`?

### ISSUE THREAD

**Issue by EricCousineau-TRI** [RobotLocomotion/drake#10411]
Example failure: https://drake-cdash.csail.mit.edu/testDetails.php?test=25813237&build=1103482
Snippet:
```
FAIL: test_relational_operators_nonzero (symbolic_test.TestSymbolicExpression)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./bindings/pydrake/test/symbolic_test.py", line 528, in test_relational_operators_nonzero
    value = (e_xv == e_yv)
AssertionError: DeprecationWarning not raised
```

My guess is that this machine has a later version of NumPy in which the warning message has changed from what we're filtering for:
https://github.com/RobotLocomotion/drake/blob/14f5b3960/bindings/pydrake/common/deprecation.py#L175-L179

**Comment by SeanCurtis-TRI** [comment]
The test in question is using Numpy 1.16.0. A sampling of half-a-dozen other mac tests indicate that they all ran against 1.15.4_2.

**Comment by EricCousineau-TRI** [comment]
Seeing if I can repro with `virtualenv` on Bionic.
