### ISSUE TITLE
[geometry] GeometryState::X_WG_proximity_ never shrinks.

### ISSUE THREAD

**Issue by avalenzu** [RobotLocomotion/drake#10436]
I can't quite wrap my head around the index juggling that's being done here to know what the solution is, but this definitely seems wrong to me:

- `X_WG_proximity_` is only ever modified by the `push_back()` call here https://github.com/RobotLocomotion/drake/blob/8e466eb24ff85da51154463d955dd00ef289983d/geometry/geometry_state.cc#L615
- As soon as it's passed into `ProximityEngine::UpdateWorldPoses()`, it's size is checked against that of `X_WG_`, which does shrink.

**Comment by SeanCurtis-TRI** [comment]
I'm assuming this became manifest from a sequence of adding, removing, and then adding geometry?

**Comment by avalenzu** [comment]
Yes. Although only the adding and removing steps are required to make it manifest.
