### ISSUE TITLE
Error using a transmogrified SceneGraph<ADS>

### ISSUE THREAD

**Issue by hongkai-dai** [RobotLocomotion/drake#10453]
I have encountered an error when I transmogrified a `Diagram<double>` (containing an `MBP<double>` and a `SceneGraph<double>`) to a `Diagram<ADS>`. After the transmogrification, when I call the function to compute the signed distance in SceneGraph, it throws me an error. 

As a comparison, I also tried to construct that `Diagram<ADS>` directly without transmogrification, and then call the same signed distance function, it runs fine.

I created a [test](https://github.com/hongkai-dai/drake/blob/transmogrify_diagram_proximity_engine_bug/multibody/inverse_kinematics/test/transmogrify_bug_demo.cc) to show the error. To reproduce the problem, you could run
```
$ bazel build //multibody/inverse_kinematics/transmogrify_bug_demo
$ ./bazel-bin/multibody/inverse_kinematics/transmogrify_bug_demo
```

The error I got when running the transmogrified `Diagram<ADS>` is
```
abort: Failure at geometry/proximity_engine.cc:1065 in UpdateWorldPoses(): condition 'indices.size() == dynamic_objects_.size()' failed.
```
@SeanCurtis-TRI @sherm1

**Comment by SeanCurtis-TRI** [comment]
Thanks for the test, @hongkai-dai. Makes my job so much easier.
