### ISSUE TITLE
Performance loss with EigenPtr

### ISSUE THREAD

**Issue by amcastro-tri** [RobotLocomotion/drake#10468]
I observed performance losses of up to 30% in our inverse dynamics due to the use of EigenPtr. The bottleneck showed up in [this line](https://github.com/RobotLocomotion/drake/blob/660f2dfb1ea4aa4ad1f006dd183a451a1dee8308/multibody/tree/body_node.h#L751) where the argument to `get_mutable_generalized_forces_from_array()` (usually inlined so it won't show up in your profiler though you'll see the new/delete's cost) is an `EigenPtr` and gets called in a loop of critical performance.

The problem turned out to be that `EigenPtr` uses a heap variable allocated [here](https://github.com/RobotLocomotion/drake/blob/660f2dfb1ea4aa4ad1f006dd183a451a1dee8308/common/eigen_types.h#L388). There is a corresponding TODO [here](https://github.com/RobotLocomotion/drake/blob/21df93f66444af0800c123e0baf5105782778838/common/eigen_types.h#L379).

**Comment by sherm1** [comment]
Ouch!
