### ISSUE TITLE
MultibodyPlant::GetVelocitiesFromArray(.) is bound to the wrong method.

### ISSUE THREAD

**Issue by edrumwri** [RobotLocomotion/drake#10474]
From multibody_tree_py.cc, line 602 at 09b6460, offending code is:

       .def("GetVelocitiesFromArray", &Class::GetPositionsFromArray,
            py::arg("model_instance"), py::arg("q"),
doc.MultibodyPlant.GetPositionsFromArray.doc)

Looks like a bad case of copypasta :)

**Comment by EricCousineau-TRI** [comment]
D'oh! Thanks for catching that!
