### ISSUE TITLE
update runAtlasRunning for v5 model

### ISSUE THREAD

**Issue by RussTedrake** [RobotLocomotion/drake#1047]
running it right now is hysterical.  i'd recommend it if you need a quick laugh.

**Comment by RussTedrake** [comment]
@hongkai-dai -- could you or @avalenzu please resolve this or move it to the dev subdirectory?

**Comment by hongkai-dai** [comment]
will take a look tomorrow.

**Comment by avalenzu** [comment]
@hongkai-dai, @RussTedrake, I'd like to take this one, if it's alright. I think I have the strongest interest in getting this working at the moment :)

**Comment by RussTedrake** [comment]
yeah!

**Comment by jwnimmer-tri** [comment]
Closing as won't-fix, because #6369 will be removing the relevant software.

If I'm confused and this should in fact stay open, please re-open an clarify the remaining unsolved problem(s) in a new comment here.
