### ISSUE TITLE
pydrake: Long-running C++ code is hard to kill with Ctrl+C

### ISSUE THREAD

**Issue by EricCousineau-TRI** [RobotLocomotion/drake#10497]
@rcory ran into an issue ran he ran `simulator.RunTo(a_large_amount_of_time)`, and noticed that it was really hard to kill the simulation with Ctrl+C.

Perhaps it's some GIL stuff, but it did not seem to be remedied by trying to release the GIL (using `py::gil_scoped_release`).

Perhaps there's a way to make a more robust `sigint` handler?

EDIT: The workaround, in this case, is what Evan posted below.

**Comment by edrumwri** [comment]
This workaround is much more compact:

    while simulator.get_context().get_time() < t_final:
        simulator.StepTo(simulator.get_context().get_time() + dt)

**Comment by EricCousineau-TRI** [comment]
I think Evan's workaround has addressed the issue, as I've seen it being used in user's code (e.g. from the Underactuated course).
Closing for now.

**Comment by EricCousineau-TRI** [comment]
Came up in discussion today; per @jwnimmer-tri, one possibility, beyond `while` loop, is to use `set_monitor` to possibly let Python interpreter intercept SIGINT or whatever.

For things using an OpenAI `gym` style interface:

> If you have an external step governor, then presumably the right thing to do is to set the simulator's max step large, and then just step to exactly where the governor asked you to.

\cc @hongkai-dai

**Comment by jwnimmer-tri** [comment]
>    simulator.StepTo(simulator.get_context().get_time() + dt) 

Note one hazard of this in particular: if `dt` is congruent with a periodic update from one of your systems, you might end up with some worthless steps (h ~ 1e-17) as the running floating point sum (dt + dt + dt + dt + ...) diverges from the `CalcNextUpdateTime` (k * period).
