### ISSUE TITLE
MbP needs templated versions of get_joint and get_mutable_joint 

### ISSUE THREAD

**Issue by RussTedrake** [RobotLocomotion/drake#10493]
that match the templates on `GetJointByName`, e.g.
```
  template <template <typename> class JointType = Joint>
  const JointType<T>& get_joint(JointIndex joint_index) const {
```
I'm finding myself down-casting downstream, which isn't the end of the world but is inconsistent with the `GetJointByName` workflow.

**Comment by amcastro-tri** [comment]
@EricCousineau-TRI, do you like these templated methods? I remember that you probably didn't quite like them? do I do see the value of having this sugar.

**Comment by EricCousineau-TRI** [comment]
I definitely see value in C++ land when dynamic polymorphism + downcasting is involved.

The thing I don't like is the only implementation being so tightly coupled to the templated method that it's hard to figure out what's sub-type specific, and what is generic to the base type.

In this case, I would suggest something like:
```c++
// Put the real code here.
const Base& GetSomething(Index);

// Pure sugar.
template <typename Type>
const Type& GetSomething(Index) const {
  return dynamic_cast<const Type&>(GetSomething(index));
}
```

... if it doesn't cause ambiguity issues.

**Comment by jwnimmer-tri** [comment]
Consider `GetSomething(index)` and `GetSomethingAs<Subtype>(index)` to disambiguate the base vs downcast type.

**Comment by amcastro-tri** [comment]
Thank you for the input guys, greatly appreciated.

**Comment by jwnimmer-tri** [comment]
Closing as not planned.  Python is the way and the light, and this is C++-only sugar.
