### ISSUE TITLE
Contact force direction appears to be incorrect

### ISSUE THREAD

**Issue by pangtao22** [RobotLocomotion/drake#10529]
Documentation on `PointPairContactInfo` says that the contact force returned by `contact_force()` is on bodyB: https://drake.mit.edu/doxygen_cxx/classdrake_1_1multibody_1_1_point_pair_contact_info.html#adf061bdb3efd7aafdc886a705994dfb3 

However, it appears that the force is on bodyA. For example, in this test (https://github.com/pangtao22/drake/blob/fbc88062122a788b0503d1d2aac52372cc499119/bindings/pydrake/systems/test/meshcat_visualizer_test.py#L86 ), the bodyB in `contact_results.contact_info(0)` is the table, but `contact_results.contact_info(0).contact_force()` has a positive z component, which should have been negative. 

@sherm1

**Comment by sherm1** [comment]
Per Slack conversation, assuming the code & doc are really different _probably_ better to change the code to match the doc (the assumption that forces are on body B seems spread around in the code).
