### ISSUE TITLE
should std::uniform_real_distribution<symbolic::Expression> and friends support operator() with no arguments?

### ISSUE THREAD

**Issue by RussTedrake** [RobotLocomotion/drake#10548]
When showing this code:
https://github.com/RobotLocomotion/drake/blob/master/examples/manipulation_station/manipulation_station.cc#L486-L490

I found myself explaining that the RandomGenerator instance here does absolutely nothing (ever); it's only there for compatibility with the std::uniform_real_distribution<double>::operator() syntax.  But we could easily support operator() with no arguments, which would clean up this code.  Is there any reason not to?

Alternatively, we could offer an entirely differently named method that returns the symbolic::Expression for the distribution without requiring a generator argument.

**Comment by soonho-tri** [comment]
I'll add `operator()` with no arguments. I will justify it in its doc.

**Comment by soonho-tri** [comment]
@RussTedrake , in #10549, you commented:

>  (though would be great to add the python binding, too?)

FYI, we do not expose `std::*_distribution`s to pydrake. We only provide 1) random symbolic variables (such as `RANDOM_UNIFORM` and `RANDOM_GAUSSIAN`), 2) random generators, and 3) `Expression::Evaluate(Generator)`.

**Comment by RussTedrake** [comment]
ah.  then no action requested for now.  (will be playing with random symbolic expressions in python soon enough and will have better understanding then)

**Comment by soonho-tri** [comment]
SGTM. Please open an issue if you have a feature-request!
