### ISSUE TITLE
Don't use /opt in drake_cmake_installed README docs

### ISSUE THREAD

**Issue by RussTedrake** [RobotLocomotion/drake#10550]
When I run the instructions here:
https://drake.mit.edu/python_bindings.html#binary-installation-for-python
on my mac, it fails to create /opt/drake and its subdirectories.  Running as root was the easy fix, but it would be good to acknowledge that (and recommend this, or a better alternative) right in the doc.

**Comment by RussTedrake** [comment]
I also think that https://drake.mit.edu/python_bindings.html#building-the-python-bindings should come later in the document.  Probably just before https://drake.mit.edu/python_bindings.html#debugging-with-the-python-bindings

cc @EricCousineau-TRI

**Comment by jwnimmer-tri** [comment]
I think `/opt` in those docs was inspired by https://github.com/RobotLocomotion/drake-shambhala/blob/master/drake_cmake_installed/README.md (which does have the `sudo`).  However, I don't know _why_ we're using `/opt` -- that seems dumb.  Probably our instructions should always just use `$HOME`?

**Comment by jamiesnape** [comment]
> However, I don't know why we're using /opt -- that seems dumb. Probably our instructions should always just use $HOME?

RPATH issues. Not dumb at all.

**Comment by jwnimmer-tri** [comment]
A quick skim of an Ubuntu binary image shows that rpath and runpaths are all `$ORIGIN`-relative (or system `/usr/libx86_64/.```) stuff.  Is there an open issue, that we should have Drake's binary release be usable from any directory you unpack it into?  If not, we should create one.

**Comment by jamiesnape** [comment]
This is configuration: mac.

**Comment by jwnimmer-tri** [comment]
Fair enough.  But then we have another issue that the _Ubuntu instructions_ also say to use `/opt`, without sudo (so it _also_ doesn't work), and in any case on Ubuntu we should _not_ recommend `/opt`.

**Comment by jamiesnape** [comment]
Our usage matches https://www.tldp.org/LDP/Linux-Filesystem-Hierarchy/html/opt.html in my opinion. People can install why they like however, but recommending `/opt` is not unusual.

**Comment by jwnimmer-tri** [comment]
I agree that using `/opt/drake` is consistent with FHS (and Debian's additions to FHS).  My position is that it's bad UX for us to suggest doing so.  Putting files in `$HOME` is going to be a substantially better workflow, for Ubuntu users at least.  (Or for python, virtualenv + pip is actually what we should be shooting for once we have time.)

In any case, I'm okay with deferring that debate to a in a different issue / future work.  But the fact remains that for `/opt`, the read-only problem also exists on Ubuntu, so this "read-only" bug isn't exclusively `configuration: mac`.

**Comment by jwnimmer-tri** [comment]
\CC @tri-ltyyu This is a documentation issue we hit last week.

**Comment by jwnimmer-tri** [comment]
As best I can tell, as of #15953 none of our https://drake.mit.edu documentation tells the user to do things into `/opt` anymore.

The only place that does suggest `/opt` is https://github.com/RobotLocomotion/drake-external-examples/tree/main/drake_cmake_installed#instructions, so I guess fixing that documentation as well would be the last part of this issue.

**Comment by RussTedrake** [comment]
Perhaps I just need a clarification, but I see a lot of `/opt` in e.g. https://drake.mit.edu/apt.html#stable-releases

**Comment by jwnimmer-tri** [comment]
Yes, that's where our `apt` packages put Drake.  However, since that's `apt` (or really, `dpkg`) placing the files there, it works as intended, without the user need any special permissions or instructions, beyond what any other use of `apt install` would demand.

**Comment by jwnimmer-tri** [comment]
This one is pretty easy.  The call to action is to change these instructions ...

https://github.com/RobotLocomotion/drake-external-examples/tree/main/drake_cmake_installed#instructions

... to unpack somewhere in the user's home directory, rather than `/opt`.  We should also run the new instructions by hand to make sure they work OK.
