### ISSUE TITLE
Automatically mirror files downloaded by repository rules to S3

### ISSUE THREAD

**Issue by jamiesnape** [RobotLocomotion/drake#10556]
Relates #8595. WIP https://github.com/jamiesnape/drake/tree/mirror-to-s3.

**Comment by EricCousineau-TRI** [comment]
Per f2f: Remaining actions are:
* Decide where the scripts are going to live (`drake` vs `drake-ci` vs. something else?).
* Deploy the job. Use Jeremy's magical repository scraping script. Determine job cadence.

**Comment by tri-ltyyu** [comment]
Have script running locally to do this. Should be quick issue.

**Comment by EricCousineau-TRI** [comment]
Per f2f, delayed due to "firefighting"; will pick up most likely next week.

**Comment by EricCousineau-TRI** [comment]
Scripted landed via #11548. Needs to have configuration + jobs land.

**Comment by jamiesnape** [comment]
I need to do some refactoring of the CI scripts since the mirroring scripts internally shell out to bazel without the CI-specific flags. Not a huge deal, though.

**Comment by EricCousineau-TRI** [comment]
Per f2f, plan is to have a set of particular CI jobs; refactoring mentioned is to put CI-specific Bazel flags to be put as a `bazelrc` file, maybe.

**Comment by jamiesnape** [comment]
https://drake-jenkins.csail.mit.edu/job/linux-bionic-gcc-bazel-continuous-python3-mirror-to-s3/
