### ISSUE TITLE
Create nightly docker images containing latest binary install and prerequisites

### ISSUE THREAD

**Issue by jamiesnape** [RobotLocomotion/drake#10554]

**Comment by EricCousineau-TRI** [comment]
Xref: [Slack convo](https://drakedevelopers.slack.com/archives/C2PMBJVAN/p1548949781021800)

**Comment by jwnimmer-tri** [comment]
... the upshot being "so that new users can take Drake for a spin with as little friction as possible".

**Comment by jamiesnape** [comment]
If someone other than me can assign a priority, it would be useful.

**Comment by EricCousineau-TRI** [comment]
@RussTedrake Is `priority: med` sufficient, or is this `priority: high` given No. of requests?

**Comment by RussTedrake** [comment]
I am going to point people to http://manipulation.csail.mit.edu/install_drake_docker.html for the time being, and see how that works out.  Assuming that goes well, my proposal would be that we have a slightly cleaner version of this available as the first recommendation under our sphinx "installation and quickstart" documentation.

**Comment by EricCousineau-TRI** [comment]
Mentioned in #7654.

**Comment by EricCousineau-TRI** [comment]
For consumption in `underactuated` via the Dockerfile, Jamie mentioned that he could possibly use the same versioning mechanism (though not sure how it'd work for experiment PRs); though we need to check on restrictions from DockerHub.

**Comment by EricCousineau-TRI** [comment]
In service of #11962, targeting this for before end-of-month (Sept. 27), just downloading the binary.

**Comment by EricCousineau-TRI** [comment]
Just need to PR docs for Docker Hub: https://hub.docker.com/r/robotlocomotion/drake/tags
