### ISSUE TITLE
Remove MultibodyTreeContext

### ISSUE THREAD

**Issue by sherm1** [RobotLocomotion/drake#10572]
The internal MultibodyTree initially required a custom Context called MultibodyTreeContext. That is no longer needed and requires dynamic_casts for almost all operations, which can be very expensive. It also makes MBTree unnecessarily complicated.

The only remaining functionality provided by MBTreeContext is knowledge of whether the kinematic state variables are continuous or discrete. That is construction-time information that can be provided directly by MBTree. A few utility methods need to move to MBTree also.

**Comment by sherm1** [comment]
`MultibodyTreeContext`, RIP :ghost:

**Comment by SeanCurtis-TRI** [comment]
Alas poor `MultibodyTreeContext`, I knew him well. :skull:

    Hamlet, Act 5 Scene 1
