### ISSUE TITLE
sdf: Improvements to MultibodyPlant parser

### ISSUE THREAD

**Issue by EricCousineau-TRI** [RobotLocomotion/drake#10590]
We've started working with OSRC to start to delve a bit deeper into SDF as a format specification. I'd like this to be our public tracker for the overall project to tie separate issues together.

Some things that we are planning to work on:
- [x] Better define edge cases of SDF
- [x] Get better defined semantics for frames `<pose frame='...'/>` ([bitbucket issue](https://bitbucket.org/osrf/sdformat/issues/200)) - successor to #9350
- [x] Enable better encapsulation (beyond gluing stuff with Xacro, or defining a custom format extension)
  - See: http://sdformat.org/tutorials?tut=composition_proposal

\cc @sherm1 @scpeters

**Comment by jwnimmer-tri** [comment]
@EricCousineau-TRI reading over this issue, I'm not sure about what any remaining call-to-action is supposed to be?  Could you clarify?

**Comment by EricCousineau-TRI** [comment]
Remaining action is to polish out composition (use Drake's URDF parsing for composition #15950, then plumbing it through #15948).

Closing this - thanks for the reminder!
