### ISSUE TITLE
python: Include bindings in valgrind anaylsis

### ISSUE THREAD

**Issue by EricCousineau-TRI** [RobotLocomotion/drake#10608]
Example using re-compiled Python:
https://gist.github.com/EricCousineau-TRI/ce79d3265bb72934267e24ddc8c623bc

This would have to use `pip` or something else to "recreate" the packages, which would be painful.

(Moving from Kitware notes to GitHub issue.)

**Comment by EricCousineau-TRI** [comment]
Was this already done via the `helgrind` mods?

**Comment by jamiesnape** [comment]
Only partially (not for memcheck: https://github.com/RobotLocomotion/drake/blob/7a03e312cea8bfb1ea2177c1ab49312d577d9c7a/tools/dynamic_analysis/bazel.rc#L215).

I can't imagine us ever recompiling python, so the task is more finishing the suppressions to be able to use `python3-dbg`.

**Comment by jwnimmer-tri** [comment]
Closing as "nice to have, but unlikely to ever float to the top of the priority list".
