### ISSUE TITLE
multibody doxygen gives people the impression that MBP does not support collision

### ISSUE THREAD

**Issue by RussTedrake** [RobotLocomotion/drake#10615]
I've had a few people look at this page:
https://drake.mit.edu/doxygen_cxx/group__multibody.html

and say "so MBP doesn't support collision yet?" (because the only section on collision says "RBP only").  That's not the message we want to send!

**Comment by sherm1** [comment]
@SeanCurtis-TRI I think this doc is yours -- time for an update?

**Comment by SeanCurtis-TRI** [comment]
I'm on it.

**Comment by SeanCurtis-TRI** [comment]
I'd recommend splitting this:

- the "Collision Filter Concepts" belong to me.
- the "Compliant Contact in Drake" belongs to @amcastro-tri (as the time-stepping contact in MBP is no longer what is documented in the doxygen.)

**Comment by sherm1** [comment]
The immediate need is to avoid the misleading impression that MBP doesn't support contact. A larger reworking could be deferred if necessary.

**Comment by SeanCurtis-TRI** [comment]
The problem is that much that is there is not correct for MBP/SG. So, the simplest fix is to delete the module entirely and then fill it in after the fact.

All in favor?

**Comment by SeanCurtis-TRI** [comment]
This would also resolve #9467.

**Comment by sherm1** [comment]
Aye! (Should still say _something_ about MBP and contact -- maybe just a link to some Doxygen or example?)
