### ISSUE TITLE
cdash: Recover dynamic analysis summaries

### ISSUE THREAD

**Issue by EricCousineau-TRI** [RobotLocomotion/drake#10611]
(From Kitware notes.)

Dynamic analysis summaries disappeared from CMake to Bazel, could get them back in. (Info is there, just need to parse.)

(This involves ongoing work.)

**Comment by jamiesnape** [comment]
Switching to "low priority" since it is technically in progress.

**Comment by BetsyMcPhail** [comment]
[CDash issue](https://github.com/Kitware/CDash/issues/795)

**Comment by tri-ltyyu** [comment]
This can be backlogged because the impact isn't felt right now. Please comment if you're affected.

**Comment by jwnimmer-tri** [comment]
Could I see an example of these summaries (maybe for a different project)?  Is it like statement coverage?  The dynamic analysis facts we care about are hard-fail tests in both pre-merge and post-merge, so I don't immediately see what beyond that we'd want?

**Comment by jwnimmer-tri** [comment]
Given that there doesn't seem to be anything still missing (kcov works well), I'll close this sufficiently done.
