### ISSUE TITLE
Pre-merge builds experiencing remote caching slow-downs

### ISSUE THREAD

**Issue by EricCousineau-TRI** [RobotLocomotion/drake#10619]
_Edit: Original title was **ci: leak-san required builds can be slow (~2hrs)**_

See Slack convo: https://drakedevelopers.slack.com/archives/C270MN28G/p1549493207082300

Difference between failed download and a very slow download.
May be resolved once this makes it into a release (and we use it):
https://github.com/bazelbuild/bazel/issues/5440

Possible solutions:
* Switch off remote caching for leak-san
* Something else?

**Comment by jwnimmer-tri** [comment]
Now that S3 guarantees strong consistency, using S3 directly for our remote cache is probably going to be more performant than our current EC2 solution.

We should investigate that as a solution.  We could even roll it out for Ubuntu builds only, in case its untenable to immediately switch the macOS build farm to using it.

**Comment by jwnimmer-tri** [comment]
Another option: split the cache into even more, different servers (e.g., a dedicated LSan-only one).

**Comment by jwnimmer-tri** [comment]
I'm not sure if there is still more to do here.  The builds have seemed pretty healthy to me lately, I haven't seen any pre-merge stalls on any PR's I've been tracking, since many months ago.

Maybe @svenevs can keep an eye on this as we update our caching infra, and then close it out.
