### ISSUE TITLE
models: Consider XML validation, model guidelines, etc.

### ISSUE THREAD

**Issue by EricCousineau-TRI** [RobotLocomotion/drake#10610]
~At present, there's no XML validation.~ (Validation tracked by #8271).
Additionally, I'm looking into ways to try and enforce better model documentation guidelines (e.g. labeling axes, origin, etc.), possibly via lint or something else.

(Porting from Kitware notes.)

**Comment by jamiesnape** [comment]
Relates in part #8271.

**Comment by EricCousineau-TRI** [comment]
Closing in lieu of #17061
