### ISSUE TITLE
ci: Code coverage is trending down

### ISSUE THREAD

**Issue by EricCousineau-TRI** [RobotLocomotion/drake#10618]
Code coverage is trending down, from >90% to ~85%
- Possibly due to artificial duplication with attric?

**Comment by jwnimmer-tri** [comment]
I'm going to posit that project-wide it is difficult to monitor and work on this trend.  If subsystem maintainers want to look within their folders for trends, that's a-ok but doesn't need this issue.

\CC @sherm1 @hongkai-dai @EricCousineau-TRI @SeanCurtis-TRI
