### ISSUE TITLE
ci: CDash slow to parse submissions

### ISSUE THREAD

**Issue by zackgalbreath** [RobotLocomotion/drake#10620]
**Background**:
CDash asynchronously parses its submissions. When a build client (typically jenkins) submits results to CDash, they go on an Amazon SQS queue. We use a third party message queue (MQ) abstraction library called [bernard](https://github.com/bernardphp/bernard) to interact with SQS.

**Description**:
On the afternoon of 2019/02/05 and the morning of 2019/02/06, we noticed that CDash had fallen roughly one hour behind in parsing its submissions. We tracked this down to Bernard calling the Amazon SQS client library function [receiveMessage](https://docs.aws.amazon.com/aws-sdk-php/v3/api/api-sqs-2012-11-05.html#receivemessage), which returned no results. In other words, Amazon SQS was reporting no messages on the queue even though many were actually waiting. This was nondeterministic however. Occasionally there was a spurt of activity followed by another lull.

One thing we did to attempt to mitigate this problem was increase the `WaitTimeSeconds` value from 5 seconds to 30 seconds.

We're tracking this issue here in case the problem reemerges.

**Comment by jwnimmer-tri** [comment]
With over a year with no new complaints, I think we can close this one for now.  If we see problems happening again, we can reopen it.
