### ISSUE TITLE
Upgrade to latest Doxygen

### ISSUE THREAD

**Issue by jwnimmer-tri** [RobotLocomotion/drake#10631]
The latest Doxygen (1.8.15) has a few bugfixes that end up being very nice (in particular, using-declarations for class methods).

Homebrew [already has 1.8.15](https://formulae.brew.sh/formula/doxygen), and in general seems like it will track the latest releases like it usually does.

Ubuntu is [stuck on 1.8.13](https://packages.ubuntu.com/bionic/doxygen) (even in > 18.04).  We should provide a binary image for latest on Ubuntu, so that we can have nice things.

See also in-progress [Debian upgrade to 1.8.15](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=919413).

**Comment by jwnimmer-tri** [comment]
I can't remember if SourceForge still adds malware to its downloads, but they do have builds up at https://sourceforge.net/projects/doxygen/files/rel-1.8.15/ that we could mirror for ourselves.  Upstream also provides a binary release, but it's unsigned and _very_ slow to download.  We could also build our own release tarball or deb from source.

**Comment by jwnimmer-tri** [comment]
@jamiesnape Do you have any suggestions on how we should obtain (and refresh) a binary release of Doxygen for Ubuntu?  Just running CMake seems to work fine for me -- we could write a short docker script to make a binary, maybe?  Or use one of the prebuilts mentioned above.  Or...?

\CC @EricCousineau-TRI

**Comment by jamiesnape** [comment]
Does http://doxygen.nl/files/doxygen-1.8.15.linux.bin.tar.gz work on 18.04? If not, I guess I can build binaries and host them in S3 like VTK.

**Comment by jwnimmer-tri** [comment]
I will try to check today.  When I tried to fetch it last night, the download was going to take hours.

**Comment by jamiesnape** [comment]
I will start a download here and upload to S3, but I guess I could probably build it quicker than the download takes.

**Comment by jamiesnape** [comment]
Do we need clang-assisted parsing? The Homebrew versions don't support it by default.

**Comment by jwnimmer-tri** [comment]
Nope.  It's currently set to OFF in our Doxyfile, and in my local testing it seems fine to keep it that way.

**Comment by jamiesnape** [comment]
Try these:

* https://drake-packages.csail.mit.edu/doxygen/doxygen-1.8.15-bionic-x86_64.tar.gz
* https://drake-packages.csail.mit.edu/doxygen/doxygen-1.8.15-xenial-x86_64.tar.gz

I will PR the build scripts if/when we use them.

**Comment by jamiesnape** [comment]
I probably should add a license file to archive, so the SHA's may change when I fix that.
