### ISSUE TITLE
RungeKutta3 integrator is using a too-conservative error estimate

### ISSUE THREAD

**Issue by sherm1** [RobotLocomotion/drake#10633]
While reworking the integrators for cache-friendliness per #10621 I noticed that the RK3 integrator is using a first-order estimator (giving an O(h²) error estimate) but the Butcher table for it calls for a second-order estimator (giving an O(h³) estimate). h² is a poor estimate, but errs almost always by being way too conservative, forcing the integrator to take smaller step sizes than necessary.

[This](https://github.com/RobotLocomotion/drake/blob/master/systems/analysis/runge_kutta3_integrator-inl.h#L103) is the offending line:
```c++
xcdot0.ScaleAndAddToVector(-dt, err_est_vec_);
```
That `xcdot0` should be `xcdot1`.

Changing to the 2nd order estimate is easy, but figuring out how to modify the unit tests is not. Also, the sinusoid accuracy unit test appears to show the actual error varying as h⁴ when it should be varying as h³. I'm confused.

**Comment by edrumwri** [comment]
Fixed with #10901
