### ISSUE TITLE
Caching performance overhead.

### ISSUE THREAD

**Issue by amcastro-tri** [RobotLocomotion/drake#10644]
I am in the process of adding new cache entries to speed up the computation of the mass matrix. Lo and behold, I do get a nice performance boost as expected. However, the performance of our inverse dynamics gets affected! That is, caching has measurable overhead. I was careful not to do `EvalFoo()` within performance critical loops but instead to `Eval()` outside loops and pass the updated cache entries deep into the MBT code. Even being that careful, the performance hit was measurable, 10% to be more specific.

I did the following test; within `MultibodyTreeSystem` I swapped all the  `CacheEntry::Eval<FooCacheType>()` by `CacheEntry::UnsafeEval<FooCacheType>()`, where the latter is a hacky implementation without checks like so:
```c++
  template <typename ValueType>
  const ValueType& UnsafeEval(const ContextBase& context) const {
    const CacheEntryValue& cache_value = get_cache_entry_value(context);
    if (cache_value.needs_recomputation()) {
      UpdateValue(context);
    }
    const AbstractValue& abstract_value = cache_value.get_abstract_value();
    return static_cast<const Value<ValueType>*>(&abstract_value)->get_value();
  }
```
that is, `MaybeGetValue()` seems to be more expensive that what we'd like to believe. That was only responsible for about 7% of that cost. I couldn't tell where the other 3% is going.

I dug deep inside `UpdateValue()` but its extra checks were not measurable.

**Comment by sherm1** [comment]
Oh, you probably won't be surprised to see MaybeGetValue()'s first line:
```
    const Value<T>* value = dynamic_cast<const Value<T>*>(this);
```

Switching that to `unchecked_dynamic_cast` should make that very cheap (in Release builds).

**Comment by jwnimmer-tri** [comment]
@amcastro-tri Could you check what difference #10649 makes to your numbers?

**Comment by amcastro-tri** [comment]
Thanks @jwnimmer-tri, I'll rerun the tests.

**Comment by sherm1** [comment]
I believe this is fixed now -- can we close it @amcastro-tri ?

**Comment by amcastro-tri** [comment]
Definitely #10649 was an improvement, I haven't observed this overhead in any of my recent profiles.
