### ISSUE TITLE
Error in building drake from source via Cmake in Ubuntu 18.04 Bionic Beaver

### ISSUE THREAD

**Issue by enriquetrucios** [RobotLocomotion/drake#10676]
### Description
I have installed all packages by running:
`./setup/ubuntu/install_prereqs.sh`
and execute `cmake -DWITH_MATLAB=ON ../drake` && `make`
The procedure was interrupted by an error:
`ERROR: /home/luistru/drake/bindings/pydrake/systems/BUILD.bazel:58:1: C++ compilation of rule '//bindings/pydrake/systems:framework.so' failed (Exit 4) cc failed: error executing command /usr/bin/cc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections ... (remaining 419 argument(s) skipped)`
```
INFO: Elapsed time: 4834.958s, Critical Path: 315.35s
INFO: 1200 processes: 1192 linux-sandbox, 8 worker.
FAILED: Build did NOT complete successfully
CMakeFiles/drake_cxx_python.dir/build.make:110: recipe for target 'drake_cxx_python-prefix/src/drake_cxx_python-stamp/drake_cxx_python-build' failed
make[2]: *** [drake_cxx_python-prefix/src/drake_cxx_python-stamp/drake_cxx_python-build] Error 1
CMakeFiles/Makefile2:968: recipe for target 'CMakeFiles/drake_cxx_python.dir/all' failed
make[1]: *** [CMakeFiles/drake_cxx_python.dir/all] Error 2
Makefile:162: recipe for target 'all' failed
make: *** [all] Error 2
```

### Reproduction

> Before you post:

> * Have you reviewed the documentation on
I reviewed [(https://drake.mit.edu/matlab_bindings.html)]
> * What operating system are you running Drake on?
Ubuntu 18.04: Bionic-Beaver
> * Have you rerun `install_prereqs.sh` on your current commit of `drake`?
-- The C compiler identification is GNU 7.3.0
-- The CXX compiler identification is GNU 7.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Bazel: /usr/bin/bazel (found suitable version "0.21.0", minimum required is "0.19.2") 
-- Found PythonInterp: /usr/bin/python2 (found suitable exact version "2.7.15") 
-- Found Git: /usr/bin/git (found version "2.20.1") 
-- Configuring done
-- Generating done

> If you have encountered a bug (installation, segfaults, etc.), please try to
post reproduction steps and as much relevant output as possible. Consider
posting long snippets as a [Gist](https://gist.github.com/).

**Comment by jwnimmer-tri** [comment]
Were there any other parts of the error output that were interesting?

My best guess at the moment is that kernel killed the compiler due to memory pressure, or that the computer ran out of disk space.  How many cores and how much RAM does this computer have?

To reduce memory pressure, you can reduce the number of jobs the build tries to run at once -- create the file `$HOME/.bazelrc` and with the line `build --jobs=2` (or some other number).  (Unfortunately `make -j2` doesn't percolate through to the underlying Bazel build system -- by default, it tries to use almost all memory and processors, and sometimes it is too aggressive.)

**Comment by enriquetrucios** [comment]
Effectively, the kernel had killed the compiler.
The procedure increased by 2 hours but It didn't make any mistakes.
Thanks a lot.
