### ISSUE TITLE
CI should send emails if git retries fails after retries are exhausted

### ISSUE THREAD

**Issue by jamiesnape** [RobotLocomotion/drake#10686]
For example in https://drake-jenkins.csail.mit.edu/view/Production/job/linux-xenial-gcc-cmake-nightly-everything-release/87.

**Comment by jamiesnape** [comment]
Also looks like failure emails were not sent in that instance.

**Comment by jamiesnape** [comment]
FTR https://issues.jenkins-ci.org/browse/JENKINS-34376 actually makes robustly sending the failure emails unnecessarily difficult.

**Comment by EricCousineau-TRI** [comment]
Per f2f, has paused work, but can resume later (w/in ~1 month?).

**Comment by tri-ltyyu** [comment]
This failure isn't happening often enough that re-trying should suffice. Closing for now
