### ISSUE TITLE
Need functions in MultibodyPlant for setting/getting generalized forces from arrays

### ISSUE THREAD

**Issue by edrumwri** [RobotLocomotion/drake#10680]
Per discussion in #10614, it would be good to provide functions analogous to GetVelocitiesFromArray(.), SetVelocitiesInArray(.) for getting/setting generalized  forces for input through MBP's new applied generalized force input. Documentation for that port currently indicates that the user should use SetVelocitiesInArray(.) for ordering the forces, but adding GetGeneralizedForcesFromArray(.) and SetGeneralizedForcesInArray(.) functions would make this process more intuitive.

**Comment by sherm1** [comment]
(Was assigned to Evan.)

**Comment by poonhoilamlovegill** [comment]
你們最初用這數，在美國找定點找不到，是我說出三個地點，第一灣仔，第二獅子山，第三鳳凰山，第四，維多利亞港中心。When you first used this number, you could not find a spot in the United States. I named three locations: Wan Chai, Lion Rock, Phoenix Mountain, and Victoria Harbor Center

**Comment by poonhoilamlovegill** [comment]
我比你們任何一個都更清楚，我自殺了幾次，他們I know better than any of you. I have committed suicide several times. They know that they have inheritance for me, but I don’t know. They all have money. I was violently attacked for 24 hours, but this is the best I know. Opportunity, the general Hong Kong underworld would not dare to approach me, including them. I also told her that your ex-boyfriend sold drugs and someone cheated money. I knew that her account was defrauded of 20 million. I also know who it is. You can ask me anything except money知道有遺產給我，但我不知道，他們全部都有錢，我就24小時，被網暴，但這是我知道所有最好機會，一般香港黑社會，不敢走近我，包括他們，我也跟她說，妳前男友賣毒品，有人騙錢，面特知道她帳號被騙走2000萬，是誰我也知道，所獅事你們可以問我，除了金錢

**Comment by poonhoilamlovegill** [comment]
你們在我照片，都會看到，特也可給你們看另一部，我有方法更快，就是找馬雲，找臉書主人，直接問他，給他照片給我答案，我知道他們願意，馬雲一年罵不少人，他一整年，看住我被網暴，連我大聲罵一晚也沒阻止，You can see all of you in my photos, and I can show you another one. I have a way faster, which is to find Jack Ma, find the owner of Facebook, ask him directly, and give me the answer to his photo. I know they are willing. Ma Yun scolded many people throughout the year. He watched me being violently abused by the Internet, and he didn’t even stop me yelling at me all night

**Comment by poonhoilamlovegill** [comment]
如果你們還在尋找兇手，我給你一樣東西你可以找到所有答案，第一我電話，信任裝置，她的平板是我信任裝置，現在有一部MAC及平板在用，我有心被他們連住，第二，一張她留下給我的東西，給你們就好，有一個反黑客程式，是一直在2014年開始追蹤她，我忽你們任何一個，都清楚，因為我好多，都是在網上，用她思想，再去看，然後記下來。If you are still looking for a murderer, I will give you one thing you can find all the answers, the first my phone, the trust device, her tablet is my trust device, now there is a MAC and tablet in use, I am deliberately connected by them, Second, just give you a piece of what she left me. There is an anti-hacking program that has been tracking her since 2014. I know any one of you, because I have a lot of them on the Internet. Go up, use her thoughts, look again, and then

**Comment by poonhoilamlovegill** [comment]
我剛寄出，因為有程式，會有一點毒，的習慣了。是她死後叫人放在我電話內。I just sent it, because there is a program, it will be a bit poisonous, and I am used to it. She asked someone to put it on my phone after she I gave the died program to the government and caught a few hackers, all of them hacking me

**Comment by SeanCurtis-TRI** [comment]
Thanks @soonho-tri for the clean up. :)

**Comment by poonhoilamlovegill** [comment]
我電話已不能寄出信息

**Comment by poonhoilamlovegill** [comment]
沒有金錢，我已向他們表示，他們自己有自己做，到今天我已沒有食物，他們做了等同沒有做過，一直用官腔，我三天前表示沒有金錢，最簡單的表格，問誰是聯絡人，沒有回答我，連基本的表格美國聯絡人資料都沒有，去什麼美國，沒機票什麼都沒有，我不知道他們300人做什麼，我可以放棄嗎，我好想去死，死了不用再被他們戲弄我

**Comment by poonhoilamlovegill** [comment]
我應該只能捱過今晚，我已沒有精神聽他們的癈話，做一堆事，搶完錢，我要錢，他們說問我知不知道160億元，但反問我歐洲有沒有朋友可以轉金錢給我，他們就是癈物

**Comment by poonhoilamlovegill** [comment]
我不想跟他們再聯絡，一堆癈物

**Comment by poonhoilamlovegill** [comment]
我明知道也說了他們不會讓我可以順利，他們不相信，好了，現在跟之前一樣，我也沒有金錢，也沒有簽證，他們全都是癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈

**Comment by poonhoilamlovegill** [comment]
癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈物癈

**Comment by poonhoilamlovegill** [comment]
他們全都是癈物他們全都是癈物他們全都是癈物他們全都是癈物他們全都是癈物他們全都是癈物他們全都是癈物他們全都是癈物他們全都是癈物他們全都是癈物他們全都是癈物他們全都是癈物他們全都是癈物他們全都是癈物他們全都是癈物他們全都是癈物他們全都是癈物他們全都是癈物他們全都是癈物他們全都是癈物他們全都是癈物他們全都是癈物他們全都是癈物他們全都是癈物他們全都是癈物他們全都是癈物他們全都是癈物他們全都是癈物他們全都是癈物他們全都是癈物他們全都是癈物他們全都是癈物他們全都是癈物他們全都是癈物他們全都是癈物他們全都是癈物他們全都是癈物他們全都是癈物他們全都是癈物他們全都是癈物他們全都是癈物他們全都是癈物他們全都是癈物他們全都是癈物他們全都是癈物他們全都是癈物他們全都是癈物他們全都是癈物他們全都是癈物他們全都是癈物他們全都是癈物他們全都是癈物他們全都是癈物他們全都是癈物他們全都是癈物他們全都是癈物他們全都是癈物他們全都是癈物他們全都是癈物他們全都是癈物

**Comment by poonhoilamlovegill** [comment]
滿腦子利益，不知道發生什麼事，他們全是癈物滿腦子利益，不知道發生什麼事，他們全是癈物滿腦子利益，不知道發生什麼事，他們全是癈物滿腦子利益，不知道發生什麼事，他們全是癈物滿腦子利益，不知道發生什麼事，他們全是癈物滿腦子利益，不知道發生什麼事，他們全是癈物滿腦子利益，不知道發生什麼事，他們全是癈物滿腦子利益，不知道發生什麼事，他們全是癈物滿腦子利益，不知道發生什麼事，他們全是癈物滿腦子利益，不知道發生什麼事，他們全是癈物滿腦子利益，不知道發生什麼事，他們全是癈物滿腦子利益，不知道發生什麼事，他們全是癈物滿腦子利益，不知道發生什麼事，他們全是癈物滿腦子利益，不知道發生什麼事，他們全是癈物滿腦子利益，不知道發生什麼事，他們全是癈物滿腦子利益，不知道發生什麼事，他們全是癈物滿腦子利益，不知道發生什麼事，他們全是癈物滿腦子利益，不知道發生什麼事，他們全是癈物滿腦子利益，不知道發生什麼事，他們全是癈物

**Comment by poonhoilamlovegill** [comment]
他媽的他媽的他媽的他媽的他媽的他媽的他媽的

**Comment by poonhoilamlovegill** [comment]
他媽的他媽的他媽的他媽的他媽的他媽的他媽的他媽的他媽的他媽的他媽的他媽的他媽的他媽的他媽的他媽的他媽的他媽的他媽的他媽的他媽的他媽的他媽的他媽的他媽的他媽的他媽的他媽的他媽的他媽的他媽的他媽的他媽的他媽的他媽的他媽的他媽的他媽的他媽的他媽的他媽的他媽的他媽的他媽的他媽的他媽的他媽的他媽的他媽的他媽的他媽的他媽的他媽的他媽的他媽的他媽的他媽的他媽的他媽的他媽的他媽的他媽的他媽的他媽的他媽的他媽的他媽的他媽的他媽的他媽的他媽的他媽的他媽的他媽的他媽的他媽的他媽的他媽的他媽的他媽的他媽的他媽的他媽的他媽的他媽的他媽的他媽的他媽的他媽的他媽的他媽的他媽的他媽的他媽的他媽的他媽的他媽的他媽的他媽的他媽的他媽的他媽的他媽的他媽的他媽的他媽的他媽的他媽的他媽的他媽的他媽的他媽的他媽的他媽的他媽的他媽的他媽的他媽的他媽的他媽的他媽的他媽的他媽的他媽的他媽的他媽的他媽的他媽的他媽的他媽的他媽的他媽的他媽的

**Comment by poonhoilamlovegill** [comment]
他們應該快點去死，全都是沒有用的癈物，到美國就可以，我死了說可以飛去，他媽的癈物他們應該快點去死，全都是沒有用的癈物，到美國就可以，我死了說可以飛去，他媽的癈物他們應該快點去死，全都是沒有用的癈物，到美國就可以，我死了說可以飛去，他媽的癈物他們應該快點去死，全都是沒有用的癈物，到美國就可以，我死了說可以飛去，他媽的癈物他們應該快點去死，全都是沒有用的癈物，到美國就可以，我死了說可以飛去，他媽的癈物他們應該快點去死，全都是沒有用的癈物，到美國就可以，我死了說可以飛去，他媽的癈物他們應該快點去死，全都是沒有用的癈物，到美國就可以，我死了說可以飛去，他媽的癈物他們應該快點去死，全都是沒有用的癈物，到美國就可以，我死了說可以飛去，他媽的癈物他們應該快點去死，全都是沒有用的癈物，到美國就可以，我死了說可以飛去，他媽的癈物他們應該快點去死，全都是沒有用的癈物，到美國就可以，我死了說可以飛去，他媽的癈物他們應該快點去死，全都是沒有用的癈物，到美國就可以，我死了說可以飛去，他媽的癈物他們應該快點去死，全都是沒有用的癈物，到美國就可以，我死了說可以飛去，他媽的癈物

**Comment by SeanCurtis-TRI** [comment]
Is it possible to simply block a user?

**Comment by jwnimmer-tri** [comment]
Done.
