### ISSUE TITLE
Massless, position-controlled control surfaces

### ISSUE THREAD

**Issue by blandry** [RobotLocomotion/drake#107]
A position-controlled control surface that is massless could be supported in the URDF the same way we do wings with a _force_element_. Instead of a _wing_ inner tag, the _force_element_ would have a _control_surface_ inner tag. The _control_surface_ would have the same attribute as the _wing_ (_chord_,_nominal_speed_,_profile_,_span_, _stall_angle_). The main difference is that the parent link of the _force_element_ would not be the link corresponding to the control surface itself, but of its actual parent (for example the parent of an aileron would be the wing link).

Then in the parser, instead of creating a RigidBodyWing, we create a RigidBodyControlSurface which is a child class of RigidBodyWing. RigidBodyControlSurface inherits all of the methods of RigidBodyWing and only needs to override computeSpatialForce. computeSpatialForce does the following:

-Forward kinematics of the RBM (which doesn't include any control surface)
-Forward kinematics of the control surface only
-Compute aerodynamic force on the control surface
-Returns the force as an external force

Now the problem with this approach is in computing the forward kinematic of the control surface. This depends on the input, which we don't have access to from inside computeSpatialForce (we only have access to the state). Any suggestions?

**Comment by RussTedrake** [comment]
this is being addressed in the new c++ rigid body system design.

**Comment by RussTedrake** [comment]
may revisit in the future, but not immediately relevant in the c++ code.
