### ISSUE TITLE
ycb: Update inertias to use constant-density estimations from meshes

### ISSUE THREAD

**Issue by EricCousineau-TRI** [RobotLocomotion/drake#10704]
Follow-up from: #10702

We should update the models to use an estimation from the mesh (if possible).

This may involve:
* Simplifying / separating the inertial estimation from the current `//manipulation/util:meshlab_to_sdf` binary (e.g. just give it an OBJ, and it'll give you an `<inertial/>` with no frame adjustment)
* Ensuring that the center of mass is accurate given the inertial adjustments.

\cc @kmuhlrad @allisonh-tri

**Comment by jwnimmer-tri** [comment]
These files live in a different repo now, so I'll move this issue to https://github.com/RobotLocomotion/models/issues/38 instead.
