### ISSUE TITLE
make does not respect -j (jobs) flag with a number

### ISSUE THREAD

**Issue by rdeits** [RobotLocomotion/drake#1070]
In drake, doing `make -j8` results in the following:

```
make[1]: warning: jobserver unavailable: using -j1.  Add `+' to parent make rule.
```

`make -j` (which allows unlimited jobs) does work, but can result in a total lockup of the host machine when too many jobs are spawned. 

We should support `make -jN` so users can get parallel builds without thrashing.

**Comment by tkoolen** [comment]
I don't get the warning message in OSX using -j8.

**Comment by RussTedrake** [comment]
is this still an issue?  the new superbuild certainly changed it, is it resolved?

**Comment by psiorx** [comment]
Superbuild fixed this for me.

**Comment by liangfok** [comment]
I just noticed this error on my machine, which is Ubuntu 14.04 64-bit.  I was wondering why compiling was taking so long...

**Comment by liangfok** [comment]
@jwnimmer-tri's computer also has the same problem. Thus, I'm going to reopen this issue.

**Comment by jwnimmer-tri** [comment]
Also @rpoyner-tri reports this occurring also.

**Comment by rpoyner-tri** [comment]
As before, when this was the case, '$ make -C pod-build -j8' works as expected.

**Comment by rpoyner-tri** [comment]
Here's a (possibly wrong or hasty) patch derived from the drake-dist makefile: 
```
diff --git a/drake/Makefile b/drake/Makefile
index 3a07863..326595f 100644
--- a/drake/Makefile
+++ b/drake/Makefile
@@ -13,7 +13,11 @@ CMAKE_CONFIG=--config $(BUILD_TYPE)
 
 .PHONY: all
 all: configure
+ifeq ($(OS),Windows_NT)
        cmake --build pod-build $(CMAKE_CONFIG) --target install
+else
+       $(MAKE) -C pod-build
+endif
 
 pod-build:
        cmake -E make_directory pod-build

```

**Comment by rpoyner-tri** [comment]
formulated a PR at #1945 .

**Comment by RussTedrake** [comment]
i believe this is now resolved.
