### ISSUE TITLE
gallery: Incoporate `drake-pytorch`

### ISSUE THREAD

**Issue by EricCousineau-TRI** [RobotLocomotion/drake#10719]
See: https://github.com/robert-verkuil/drake-pytorch

Suggested steps:
- [ ] Do some cleanup passes on the repo (e.g. clear out unused / prototype code, etc.)
- [ ] Consider refining Python code for use in `underactuated` - either putting code in `underactuated` for ease of use, or consuming from `drake-pytorch`
- [ ] Make Drake PR to put in Gallery

\cc @robert-verkuil @pvarin @RussTedrake

**Comment by jwnimmer-tri** [comment]
Given the age of the repository, it doesn't seems like a good candidate for the gallery in 2024.
