### ISSUE TITLE
Port GlobalInverseKinematics to use MultibodyPlant

### ISSUE THREAD

**Issue by jwnimmer-tri** [RobotLocomotion/drake#10724]
As discussed in #10681, @hongkai-dai writes:

> I think we should port `GlobalInverseKinematics` to use MBP and also change to use the const Solve method. I will do it in the 3 months window in a separate PR.

The current deprecation marker puts its removal on 2019-06-01 as this deadline.

**Comment by jwnimmer-tri** [comment]
FYI The porting to const-Solve method is done, but I believe this code is still RBP-only and needs a port to MBP.

**Comment by jwnimmer-tri** [comment]
@hongkai-dai I think that #13921 resolved this?

**Comment by hongkai-dai** [comment]
Yes, this is resolved.
