### ISSUE TITLE
pydrake unit tests for deprecation are too boilerplatey

### ISSUE THREAD

**Issue by jwnimmer-tri** [RobotLocomotion/drake#10728]
We currently have many stanzas that look like this:
```python
with warnings.catch_warnings(record=True) as w:
    warnings.simplefilter('always', DrakeDeprecationWarning)
    // stuff
    self.assertEqual(len(w), 2)
```

That's a lot of boilerplate.  We should condense it somehow, maybe:
```python
with ExpectDrakeDeprecation(2):
    // stuff
```

Noted in #10681 code review.

**Comment by EricCousineau-TRI** [comment]
My request is that this expose the warnings `w` still, and not try to encode too much about what's to be expected, e.g.
```
with catch_drake_warnings(record=True) as w:
   // stuff
  self.assertEqual(len(w), 2)
```

Could be done relatively easily with a `contextmanager`:
https://docs.python.org/3/library/contextlib.html#contextlib.contextmanager

**Comment by jwnimmer-tri** [comment]
That turns 3 lines of boilerplate into 2.  I suspect @ggould-tri would still object (as would I).

What about this?
```python
with catch_drake_warnings(action='always', expected_count=2) as w:
    pass  # stuff
```

... where the kwargs to the context are optional (defaulting to 'always', None), and so you can still do `self.assertEqual(len(w), 2)` or whatever to cover irregular conditions might occur?

**Comment by EricCousineau-TRI** [comment]
Sounds good to me!
