### ISSUE TITLE
MultibodyPlant does not properly calculate the output from the generalized contact forces port

### ISSUE THREAD

**Issue by edrumwri** [RobotLocomotion/drake#10741]
The output port is only returning the last results from the contact solve in DoCalcDiscreteVariableUpdates(.) which means that if you have not called that method, you inexplicably get zero contact forces. There's a TODO regarding this problem in the output port calculation method, but it only says that the method should be cached (this method should have been doing the full computation in the meantime).

**Comment by jwnimmer-tri** [comment]
I believe that due to the revert in #10875, this issue is again unfixed.
