### ISSUE TITLE
Add tests for JacobianWrtVariable::kV in multibody_plant_jacobians_test.cc

### ISSUE THREAD

**Issue by mitiguy** [RobotLocomotion/drake#10744]
Currently, the test KukaIiwaModelTests in file multibody_plant_jacobians_test.cc only tests for JacobianWrtVariables::kQDot.  This test was overlooked with more than one developer in previous PRs.

One possible solution involves adding a method that leverages MapVelocityToQDot() in file multibody_tree.h to form the "N" matrix that relates qDot to v and use this method inAdd a method in conjunction with the analytical calculations that are already performed for kQDot.

**Comment by mitiguy** [comment]
In file multibody_plant_jacobians_test.cc.
In test functions such as:  TEST_F(KukaIiwaModelTests, CalcJacobianTranslationalVelocityNonUnitQuaternion)

Add methods to test
CalcJacobianSpatialVelocity(*context, JacobianWrtVariable::kV, frame_E,  p_EoEp, frame_W, frame_W, &Jv_V_WEp_W);

CalcJacobianTranslationalVelocity(*context, JacobianWrtVariable::kV, frame_E,  p_EoEp_E, frame_W, frame_W, &Jq_v_WEp_W);

**Comment by jwnimmer-tri** [comment]
If we haven't missed the tests in the past 4 years, chances are we don't care.  Closing as not planned.
