### ISSUE TITLE
offer LeafSystem::DeclareVectorInput(name, size, random_type)

### ISSUE THREAD

**Issue by RussTedrake** [RobotLocomotion/drake#10751]
We have `System::DeclareInputPort(name, PortDataType::kVectorValued, int)` and `LeafSystem::DeclareVectorInput(name, BasicVector(size), random_type)`.  In both cases, the unfortunate user has to understand something about the systems framework that they should not absolutely need (`PortDataType` or `BasicVector`).  It would be trivial to offer the default `BasicVector` option, and I think it would be popular!  (in my python code, it would mean that the file doesn't need to import `PortDataType` nor `BasicVector` at the top, which always confuses people.)

Ditto for output ports.

**Comment by jwnimmer-tri** [comment]
As I've been visiting many call sites as part of #15179, I'm also sad that we have to say `BasicVector` when declaring vector ports.  A _string name_ and _int size_ would help in very many places.
