### ISSUE TITLE
s1dot not being set in QPLocomotionPlan

### ISSUE THREAD

**Issue by tkoolen** [RobotLocomotion/drake#1079]
Just found that s1dot is only being set (to zeros) in QPInputConstantHeight. QPLocomotionPlan does set s1, but it doesn't set s1dot. @rdeits, is this bad or are we not using s1dot anyway?

**Comment by rdeits** [comment]
It appears that s1dot is never used inside the old or new controller, so I
think this is ok. @kuindersma is that right?

**Comment by kuindersma** [comment]
Correct, we only need s1dot if we're computing Vdot (e.g., for fall classification), which we're not.
