### ISSUE TITLE
RigidTransform * Matrix3Xd returns Vector3d

### ISSUE THREAD

**Issue by hongkai-dai** [RobotLocomotion/drake#10816]
There is something incorrect in using operator* with RigidTransform. I tried `X_AB * p_BV`, where `X_AB` is a RigidTransform, and `p_BV` is Eigen::Matrix3Xd with 4 columns. It returns me a Vector3d, only the result of `X_AB * p_BV.col(0)`. I think we should either throw a compilation error or returns a Matrix3Xd. I prefer to returning a Matrix3Xd

**Comment by sherm1** [comment]
I marked this high priority -- multiplication is supposed to work right! (attn @mitiguy to investigate please)

**Comment by EricCousineau-TRI** [comment]
BTW Does it throw an error in debug mode? I'd assume that it would.

**Comment by mitiguy** [comment]
This is being addressed in PR #11308

**Comment by tri-ltyyu** [comment]
This issue can close?

**Comment by mitiguy** [comment]
This was fixed with PR #11308
