### ISSUE TITLE
ipython kernel crashes (with no diagnostics) when input port is not connected

### ISSUE THREAD

**Issue by RussTedrake** [RobotLocomotion/drake#10818]
running this trivial example in a notebook brings down the kernel:
```
from pydrake.examples.pendulum import PendulumPlant

plant = PendulumPlant()
context = plant.CreateDefaultContext()
#context.FixInputPort(0, [0])
derivs = plant.AllocateTimeDerivatives()
plant.CalcTimeDerivatives(context, derivs)
```
uncommenting the FixInputPort line fixes it, of course.

this particular example requires #10817

**Comment by EricCousineau-TRI** [comment]
First step will be to see if this happens in C++ too; if so, may pass the buck along :)

**Comment by EricCousineau-TRI** [comment]
Can repro in pure C++: https://github.com/EricCousineau-TRI/drake/commit/9c6ea46f52c2048232962357af1b3364db7b17fd
Probably just a port-checking thing.

**Comment by jwnimmer-tri** [comment]
Yup.  `this->EvalVectorInput(context, 0)->GetAtIndex(0);` is the old, bad Eval.  If the code used the new port.Eval, this would produce a proper diagnostic.

**Comment by EricCousineau-TRI** [comment]
Yup, doing so now.

**Comment by akshitj1** [comment]
Hi @EricCousineau-TRI , still all other examples(acrobot, quadrotor) uses the former  ( `this->EvalVectorInput(context, 0)->GetAtIndex(0);`).  I ran into same issue after making my own plant using those egs. as reference. I was running DirectCollocation on it. Should I send a PR with necessary changes in others too, if trivial?

**Comment by EricCousineau-TRI** [comment]
Yup, that would be awesome if you could - thanks!
