### ISSUE TITLE
bind symbolic::Evaluate in python please?

### ISSUE THREAD

**Issue by RussTedrake** [RobotLocomotion/drake#10824]
@sadraddini started using pydrake.symbolic (converting from sympy) and said it's MUCH faster for most things.  But we don't offer the matrix version of `Evaluate` yet.  

https://drake.mit.edu/doxygen_cxx/namespacedrake_1_1symbolic.html#a189f3085c95a362da3dafdc788be3302

Perhaps other `MatrixBase<symbolic::Expression>` bindings are missing, too?

**Comment by jwnimmer-tri** [comment]
@soonho-tri Could you post back here and/or edit the issue to reflect what work still remains?

**Comment by soonho-tri** [comment]
Close by #10835
