### ISSUE TITLE
Implement contact-implicit direct transcription using MultibodyPlant<AutoDiff>

### ISSUE THREAD

**Issue by rcory** [RobotLocomotion/drake#10840]
and use it in a simple contact planning example (planar manipulation). The approach is outlined in:

Posa, M., Cantu, C., Tedrake, R.: A direct method for trajectory optimization of rigid
bodies through contact. International Journal of Robotics Research 33(1), 69–81 (2014)

**Comment by drewhamiltonasdf** [comment]
> and use it in a simple contact planning example (planar manipulation). The approach is outlined in:
> 
> Posa, M., Cantu, C., Tedrake, R.: A direct method for trajectory optimization of rigid bodies through contact. International Journal of Robotics Research 33(1), 69–81 (2014)

If you do it, I will mow your lawn. I will water your houseplants. I will feed your cat when you are on vacation. Whatever you like.
