### ISSUE TITLE
pydrake.symbolic.Evaluate: Having an Array as Env

### ISSUE THREAD

**Issue by sadraddini** [RobotLocomotion/drake#10846]
Related to #10824 and #10835 and as @RussTedrake suggested. 

Now we have the python bindings for Evaluate function for a matrix. It works as 
`
pydrake.symbolic.Evaluate(X,E)
`
where `X` is a numpy array of `pydrake.symbolic.Expression` objects as entries, and `E` is the environment in the form of a dictionary `{pydrake.symbolic.Variable:float}`. This allows for fast evaluation of large matrices around a single environment. 

What can be even more useful for strengthening symbolic module is an equivalent to [Lambdify](https://docs.sympy.org/1.2/modules/utilities/lambdify.html) in Sympy. An easy option is having `E` as `{pydrake.symbolic.Variable:N*1 numpy array of floats}`, so one can evaluate `X` for multiple environments without writing a for loop in python. 

This comes handy in evaluating arrays of nonlinear functions for a number of query points.

**Comment by soonho-tri** [comment]
@sadraddini , thanks for the suggestion. I'll work on it.
