### ISSUE TITLE
git: Ensure PRs don't add big files

### ISSUE THREAD

**Issue by EricCousineau-TRI** [RobotLocomotion/drake#10847]
Can do it as a git hook, or a nag bot, or a Jenkins script.

Can use Kitware's GitHub App (pre-check) for doing Git linting.

**Comment by zackgalbreath** [comment]
We might be able to re-use or re-purpose a GitHub app we wrote for this purpose for another project.

https://github.com/apps/pppl-bot

**Comment by jwnimmer-tri** [comment]
So far we've managed to skate by without this, and between #15774 and/or `--filter=blob:none` it's probable that we either start committing model textures to other repositories more regularly, or else we commit them directly into Drake.  Either way, we can punt on this issue for now, and re-open if/when we find a specific need.
