### ISSUE TITLE
pack the mex related function into a separate library

### ISSUE THREAD

**Issue by hongkai-dai** [RobotLocomotion/drake#1087]
drakeUtil.h contains a lot of functions that are mex related, such that we cannot construct a standalone C++ test if we want to include drakeUtil.h. Same as QPCommon.h.

**Comment by hongkai-dai** [comment]
@RussTedrake , could you assign this to me?

**Comment by psiorx** [comment]
This is a duplicate of #1071

**Comment by RussTedrake** [comment]
resolved.  we now have drakeMexUtil
