### ISSUE TITLE
MultibodyPlant gives a mysterious error if an sdf suddenly gains collision geometry

### ISSUE THREAD

**Issue by RussTedrake** [RobotLocomotion/drake#10874]
Problem:
https://stackoverflow.com/questions/55075161/how-to-debug-inputporteval-required-inputport0-is-not-connected

Proposed solutions:
- update all multibody examples in drake to use the `AddMultibodyPlantSceneGraph` sugar.  
- if possible, provide a better error message for this case.  (not sure if there is a convenient single point of entry for this call, though...)

**Comment by sherm1** [comment]
Updating the examples to best practices seems like the right answer.

**Comment by jwnimmer-tri** [comment]
I'm resolving this as a duplicate of #11448.
