### ISSUE TITLE
Feature request: Warn when LcmSubscriberSystem has a DrakeLcm object with no receive thread.

### ISSUE THREAD

**Issue by pvarin** [RobotLocomotion/drake#10894]
I've run into this bug a couple of times:
1. Setup a system with an LcmSubscriberSystem
2. Forget to call lcm.StartReceiveThread()
3. Wonder why messages contain all zeros

It would probably save a lot of debugging time for consumers of the LcmSubscriberSystem if it checked that the DrakeLcm object had a valid receive thread when the simulation is run and printed a useful warning message.

**Comment by jwnimmer-tri** [comment]
Duplicate of #10895.
