### ISSUE TITLE
ci: Turn off `xenial-valgrind-memcheck-weekly`

### ISSUE THREAD

**Issue by EricCousineau-TRI** [RobotLocomotion/drake#10890]
See Slack convo:
https://drakedevelopers.slack.com/archives/C270MN28G/p1552336898014300?thread_ts=1552312717.012700&cid=C270MN28G

Summary: It's difficult to reproduce in Bionic, and not providing too much value as the Enabling team has moved primary development / usage to Bionic.

\cc @jwnimmer-tri

**Comment by jamiesnape** [comment]
They are manually disabled for now. It will take me slightly longer to update the scripts that are used to provision the Jenkins jobs.

**Comment by jamiesnape** [comment]
Removed.
