### ISSUE TITLE
Maliput should support lane directivity.  

### ISSUE THREAD

**Issue by andrewbest-tri** [RobotLocomotion/drake#10917]
This issue tracks the implementation of Maliput's DirectionUsageRule.

__Outline__
DirectionUsageRule should contain at-least the following information:
* ID
* LaneSRange
* severity? {Advisory, Strict}
* Direction {WithS, AgainstS, Undirected}

We will add these rules to the RoadRuleBook. This also involves

PR 1
1. Adding the DirectionUsageRule class
1. Adding Comparison methods
1. Adding tests
PR 2
1. Adding getter methods to the RoadRulebook
1. Adding DirectionUsageRule to QueryResults.
1. Updating SimpleRulebook
1. Adding tests
-- 
PR 3
1. Updating Yaml loader to support DirectionUsageRule

__Questions:__
1. Do we need With, Against, Undirected, and Both, or just 3 of the 4
1. Do we need severity? Probably can get by without at first.

**Comment by andrewbest-tri** [comment]
@liangfok mind taking a look at this plan and giving feedback?

**Comment by liangfok** [comment]
Maliput's design doc includes the following direction usage rules:
 * bidirectional (e.g., non-striped single-lane residential street)
 * unidirectional, s increasing
 * unidirectional, s decreasing
 * bidirectional, turning-only
 * no-traffic (e.g., median strip)
 * parking-lane

What is your reason for simplifying this down to just three?
 * WithS
 * AgainstS
 * Undirected

**Comment by EricCousineau-TRI** [comment]
Per discussion in #10930, this design is captured in the maliput org-mode doc here:
https://github.com/RobotLocomotion/drake/blob/c40a01fb7/automotive/maliput/doc/maliput-design.org#L1225

**Comment by liangfok** [comment]
@andrewbest-tri can this ticket be closed now that #10951 is merged?

**Comment by andrewbest-tri** [comment]
I would like to leave it open until the YAML loader supports DirectionUsageRules.
