### ISSUE TITLE
doc: Discoverability of mutlibody notation is... suboptimal

### ISSUE THREAD

**Issue by EricCousineau-TRI** [RobotLocomotion/drake#10921]
I love the multibody notation that we have; however, I always struggle hardcore to sift through Doxygen's esoteric arrangement to remember where they actually lie.

At present (edd1bac6f), it's here:
> ![image](https://user-images.githubusercontent.com/26719449/54371510-e0d61d00-464f-11e9-90a6-3866798013d1.png)

The fact that these notes are in a section that's next to something else called `Modeling Dynamical Systems` makes some sense, but still makes it hard to find the right bin to go to.

Is there some way that we can make this easier to find and refer to when sifting through that nav bar?

(@mitiguy assigning you for now, as I'm not sure who should own this.)

\cc @sherm1

**Comment by sherm1** [comment]
I have trouble finding it too and I wrote most of it!
