### ISSUE TITLE
Refactor CI packaging scripts to support multiple configurations per platform

### ISSUE THREAD

**Issue by jamiesnape** [RobotLocomotion/drake#10948]
At the moment, the scripts assume a configuration that enables only the F2C version of SNOPT of all the commercial solvers. As it looks like we moving toward offering binary packages in multiple configurations (e.g., #10542 and #10804), the CI scripts need to support that.

**Comment by jwnimmer-tri** [comment]
At least as of #10542, we will not have multiple builds of SNOPT.  Perhaps this issue is no longer relevant.

**Comment by jamiesnape** [comment]
If #10804 ever happens (seems remote that it would), it would be necessary, but I don't think we need a separate issue.
