### ISSUE TITLE
pkg_config: Make Homebrew paths only be applied on Mac

### ISSUE THREAD

**Issue by EricCousineau-TRI** [RobotLocomotion/drake#10953]
See: https://github.com/robotlocomotion/drake/pull/10941#pullrequestreview-215918248

**Comment by jwnimmer-tri** [comment]
Absent this causing some problem, how about we decide not to care and just close the issue?  This doesn't seem worth spending even a single minute on, until it's causing a problem.

**Comment by jamiesnape** [comment]
Yes, I don't think it will ever, ever cause a problem.

**Comment by EricCousineau-TRI** [comment]
Yeah, SGTM.
