### ISSUE TITLE
Maliput duplicates predicates in rules comparisons

### ISSUE THREAD

**Issue by andrewbest-tri** [RobotLocomotion/drake#10950]
In Maliput's rules_*_comparisons.h, a specific predicate is given for each rule type and sub-comparison. Originally, @maddog-tri suggested replacing these with a generic predicate. See

[rules_speed_limit_compare.h](https://github.com/RobotLocomotion/drake/blob/c727021dee2b398a366e8b4be8f322354618b885/automotive/maliput/api/test_utilities/rules_speed_limit_compare.h#L15)
and [rules_right_of_way_compare.h](https://github.com/RobotLocomotion/drake/blob/c727021dee2b398a366e8b4be8f322354618b885/automotive/maliput/api/test_utilities/rules_right_of_way_compare.h#L16)

PR 10930 adds another instance of this TODO.

**Comment by liangfok** [comment]
I moved this ticket into Maliput's new repository.
