### ISSUE TITLE
port.FixValue() should accept an initializer list as a value

### ISSUE THREAD

**Issue by sherm1** [RobotLocomotion/drake#10978]
Per discussion in #10964, it would be nice to be able to write
```c++
input_port.FixValue(&context, {1., 2., 3.});
```
with identical results (for a vector-valued port) to:
```c++
input_port.FixValue(&context, Vector3d{1., 2., 3.});
```

This would require updates to the VectorPolicy (to accept and convert an `initializer_list<T>`) and the AbstractPolicy (to reject such a list). These policies are enforced by
`internal::ValueToVectorValue` and `internal::ValueToAbstractValue` classes.

Eager SFINAE wizard solicited for implementation!

**Comment by jwnimmer-tri** [comment]
I proposed this in #10964.  I no longer think it's worthwhile.
