### ISSUE TITLE
py mbp: Change bindings to use `RigidTransform`

### ISSUE THREAD

**Issue by EricCousineau-TRI** [RobotLocomotion/drake#10982]
Per this conversation:
https://github.com/robotlocomotion/drake/pull/10959#issuecomment-474850174

~May depend on viability of turning of implicit casts.~ It'll be easy.

Steps:
- [x] #11061 Fix implicit conversions
- [ ] Switching bindings to use `RigidTransform`
- [ ] Deprecate implicit conversions (following C++)

\cc @amcastro-tri

**Comment by EricCousineau-TRI** [comment]
Hm... I updated the checkboxes for what would maximize backwards compatibility. However, given that we've already broken it (as some Anzu code is broken by the current Drake `master`), should we just keep it as-is? I can forward-fix the Anzu code.

@jwnimmer-tri @amcastro-tri Can I ask y'all's opinion?

**Comment by jwnimmer-tri** [comment]
If doing the same thing in pydrake as we did in C++ is easy enough (and it looks like that's what your checkbox list implies), then that seems worthwhile.

**Comment by jwnimmer-tri** [comment]
@EricCousineau-TRI I think this work might already be finished?  If not, could you clarify what remains?

**Comment by EricCousineau-TRI** [comment]
Ah, nope - it seems to be all done!
