### ISSUE TITLE
[geometry] Add coarse "pose-update" cache entry to SceneGraph

### ISSUE THREAD

**Issue by SeanCurtis-TRI** [RobotLocomotion/drake#10988]
The full tear-down of `SceneGraph` to make it cache friendly and reduce its foot print in the abstract state of a diagram is a large undertaking. However, we can improve performance and make `SceneGraph` compatible with the upcoming "frozen" context by doing something small.

The solution will be a coarse approximation of what `SceneGraph` will look like down the road when we make it cache-compliant. Essentially, we create a cache entry for "black boxes updated". `Calc`'ing that cache entry has the side effect of pulling poses and updating all the black boxes (in the future we'll have finer granularity). This will have two effects:

1. It will play nicely with the frozen context -- even to the extent that if you forget to evaluate a query *prior* to freezing, you'll get feedback.
2. It will also improve performance w.r.t. the current single-point query. The first query on dirty inputs will update the black box, but subsequent queries will not.

**Comment by calderpg-tri** [comment]
Since this is the performance bottleneck for our demo right now, this should be high priority.
