### ISSUE TITLE
num_xx_state accessors are all over the place

### ISSUE THREAD

**Issue by RussTedrake** [RobotLocomotion/drake#10993]
we have 
`System::get_num_continuous_states()`
`System::get_num_total_inputs()`
`System::get_num_total_outputs()`

but then
`Context::get_num_abstract_states()`
`Context::get_num_discrete_state_groups()`
`Context::get_num_total_states()`

any many don't have python bindings.

**Comment by sherm1** [comment]
@RussTedrake these are better now as of #10995. System and Context both have:
- num_continuous_states(), num_discrete_state_groups(), num_abstract_states()
- num_numeric_parameter_groups(), num_abstract_parameters()
- num_input_ports(), num_output_ports()

Context also has:
- num_total_states()

System also has:
- num_constraints(), num_constraint_equations()

Note the lack of an initial `get_` on these methods. We had a mix of with-get and without-get "count" methods; at least in the System framework we're standardizing on the without-get form.

Python bindings for _most_ of these are available, using the same names. It's possible that there are still some missing bindings.

Out of an abundance of optimism, I'm closing this issue. Please continue to file specific inconsistencies or missing methods if you encounter them.
