### ISSUE TITLE
Furniture API needs to be implemented in Maliput.

### ISSUE THREAD

**Issue by andrewbest-tri** [RobotLocomotion/drake#11008]
Maliput Design doc specifies queries for fetching "furniture" of the road. This includes objects on the road as well as road-markings, traffic lights, signs, etc. So far, the API has implemented traffic lights as part of phasing, but the rest of the furniture API should be implemented.

We propose initially to implement Furniture as a new member of the road network.

Furniture encompasses the following things: 
1. Linear Features
    * Lane striping
1. Areal Features
    * Crosswalks
    * Restricted medians
    * Do not block zones 
1. Signage
    * Stop lights, stop signs
    * turn restrictions, etc
1. Volumetric furniture
    * Benches
    * mailboxes
    * traffic cones
    * debris

We expect FurnitureRecord to be either an abstract class subclasses by each type or a record similar to QueryResult, i.e. a container that contains at most one of the different types. 

Some common queries we expect to need are 
* Get all markings filtered by lane (with an additional SRange subquery)
* **more to come**

See the maliput design doc for more context.

**Comment by liangfok** [comment]
I moved this ticket into Maliput's new repository.
