### ISSUE TITLE
Password about Jupyter notebook with Docker

### ISSUE THREAD

**Issue by ddliugit** [RobotLocomotion/drake#11017]
I found that  password for Jupiter notebook with Docker is needed. Is this only for MIT student?

**Comment by jwnimmer-tri** [comment]
I am not aware of any Drake software or instructions that require a password, but I also don't really understand the question.  Can you post a link to instructions you were following that ended up asking for a password?

As background, please take a look at https://www.chiark.greenend.org.uk/~sgtatham/bugs.html for some advice about how to inform bug reports in a way that enables useful replies.
