### ISSUE TITLE
Support resource deprecation

### ISSUE THREAD

**Issue by EricCousineau-TRI** [RobotLocomotion/drake#11012]
Motivated by #11009: It'd be nice to actively warn users if a model is deprecated, because I want to delete confusingly redundant files.

*NEW Resource-general*: See Jeremy's first comment.

*OLD Parsing-specific*: For now, we could add a text-file scanning heuristic that will scan for a `DEPRECATED` comment and provide the message. Later, we can consider adding a `<drake:deprecated/>` tag for SDF (and maybe URDF).

**Comment by jwnimmer-tri** [comment]
I'd say make it work for any resource, not just models.

We could install them to `share/drake/deprecated` instead (or whatever) once they become deprecated, and FindResourceOrThrow can be taught to look there and warn (but succeed).  No need to pollute the parsers or otherwise with an installation-related concern.

**Comment by EricCousineau-TRI** [comment]
SGTM. Updated title; would be nice to ensure it works in concert with `package://` discovery (#10531), at least for Drake's package path file resolution.

**Comment by EricCousineau-TRI** [comment]
Hm... If we do it purely in a resource-based fashion, how might we add a message for deprecation timeline and what to use instead? I guess we could do something like:
```
${install}/share/drake/.deprecated/
   examples/acrobot/
     Acrobot.sdf
     .Acrobot.sdf.deprecation_message.txt
```

That way it spews a message on access to that resource?

**Comment by jwnimmer-tri** [comment]
Sure, or even a single YAML/JSON file or whatever, where we can list files + messages (sharing a message with multiple files is probably common).  Doing that might even mean that we can keep the files in their original path, but still have FindResource warn?  Less shuffling is probably better.

**Comment by jwnimmer-tri** [comment]
@EricCousineau-TRI Now that we have monthly release notes, I wonder if mentioning pending resource removals there is a sufficient solution?

**Comment by EricCousineau-TRI** [comment]
Yeah, I'd be fine with that!

**Comment by jwnimmer-tri** [comment]
=> #10605 for process note, but nothing left to do here.
