### ISSUE TITLE
python tests shouldn't have to argparse just to avoid showing windows

### ISSUE THREAD

**Issue by RussTedrake** [RobotLocomotion/drake#11029]
Writing this:
https://github.com/RobotLocomotion/drake/blob/master/bindings/pydrake/systems/drawing_graphviz_example.py#L48
actually requires a lot of lines
https://github.com/RobotLocomotion/drake/blob/master/bindings/pydrake/systems/drawing_graphviz_example.py#L14-L20
and detracts from the simplicity of our "simple" examples.

can't we just add the line to the bazel test rule for python binaries/libraries to disable matplotlib?  it's been working well for me: https://github.com/RussTedrake/underactuated/blob/master/src/CMakeLists.txt#L25

**Comment by jwnimmer-tri** [comment]
We could do set the environment `MPLBACKEND=Template` in test_env, similar to https://github.com/RobotLocomotion/drake/blob/a7ad789c2827e85fd4d4bee8b6db57ce263e339f/tools/bazel.rc#L37-L42.  That seems like a fine change to me.
