### ISSUE TITLE
Parse collision filter from SDF files

### ISSUE THREAD

**Issue by SeanCurtis-TRI** [RobotLocomotion/drake#11087]
PR #8232 had allowed collision filter groups to be defined in an sdf file. This functionality was supported by the RBT implementation. As we've moved to MPB/SG, this feature has not yet made the transition.

Rather than blindly aping that specification, we should examine it and determine if it needs tweaking before we implement. This issue will serve as the basis to clearly define the feature we want.

**Comment by SeanCurtis-TRI** [comment]
cc @calderpg-tri @EricCousineau-TRI

**Comment by EricCousineau-TRI** [comment]
Marginally relates (but may not require) #9754

**Comment by huihuaTRI** [comment]
Can I bump up the priority of this issue since the FLT uses the collision filter tag heavily? It seems now we have a clear user request.

**Comment by SeanCurtis-TRI** [comment]
#12495 is a direct translation of the original RBT functionality. We'll consider that it closes this PR and if "rethinking" is truly required, we'll open a new PR.

**Comment by huihuaTRI** [comment]
Would this issue needs a separate PR other than [#12495](https://github.com/RobotLocomotion/drake/pull/12495) since that one is only for URDFs?

**Comment by SeanCurtis-TRI** [comment]
That's a good point. We should leave this open, noting that the implementation is only half in place.

**Comment by SeanCurtis-TRI** [comment]
Or should #12495 also add it to SDF at the same time?  :D

**Comment by huihuaTRI** [comment]
I am actually looking into that already. I will report back about the plan.

**Comment by huihuaTRI** [comment]
Talked to Sean f2f, the plan is to push PR #12495 first and then work on the SDF part. The main thought pushes this decision is to remove the blocker on the FL stack which only uses URDFs.
