### ISSUE TITLE
Remove AddForceElement specialization from MBP/MBT

### ISSUE THREAD

**Issue by amcastro-tri** [RobotLocomotion/drake#11080]
MBP/MBT have `AddForceElement()` specializations for adding `UniformGravityField` force elements. [MBP specialization here](https://github.com/RobotLocomotion/drake/blob/56dab59ff6d80566f2f8de917112cece56ccdd9e/multibody/plant/multibody_plant.h#L903) and [MBT specialization here](https://github.com/RobotLocomotion/drake/blob/56dab59ff6d80566f2f8de917112cece56ccdd9e/multibody/tree/multibody_tree.h#L421).

These specializations create two layers that don't agree between MBP and MBT, leading to difficult to diagnose bugs, see #11051.

It is bad practice and they should be removed for a better solution.

**Comment by sammy-tri** [comment]
This should be taken care of once the deprecation period introduced in #11401 elapses.
