### ISSUE TITLE
pydrake MathematicalProgram::SetInitialGuess permits wrong sizes

### ISSUE THREAD

**Issue by RussTedrake** [RobotLocomotion/drake#11097]
Not sure what's happening with the memory here, but the following program should assert but does not:
```
from pydrake.all import MathematicalProgram
prog = MathematicalProgram()
x = prog.NewContinuousVariables(1, 2)
prog.SetInitialGuess(x, np.zeros(42))
```

**Comment by hongkai-dai** [comment]
`MathematicalProgram::SetInitialGuess` calls `DRAKE_ASSERT` instead of `DRAKE_DEMAND`. I can change it to `DRAKE_DEMAND`
https://github.com/RobotLocomotion/drake/blob/bd00a8c9889019f779fe993d31817c9b708b8c4e/solvers/mathematical_program.h#L2203-L2207

**Comment by RussTedrake** [comment]
I think that would be good.  Thanks
