### ISSUE TITLE
QuadPlantPenn.m, computation for rpy_ddot, overkill?

### ISSUE THREAD

**Issue by hjjayakrishnan** [RobotLocomotion/drake#1110]
Are the computations done actually required? It seems too complicated. VIjay Kumar's paper also doesn't mention any of them.

**Comment by RussTedrake** [comment]
Tagged @peteflorence in case he wants to respond, too, but I could imagine a few differences.  We're using an RPY coordinate system here, for simplicity, but Vijay's group emphasizes singularity free control in SE(3).  We could have done that here, but haven't yet.  Also, Vijay's paper is about planning, not simulation.  For simulation you need to somehow compute the  derivatives of your angular velocity representation.
