### ISSUE TITLE
Figure out a better way to do sensed support logic in drake atlas simulation 

### ISSUE THREAD

**Issue by rdeits** [RobotLocomotion/drake#1111]
https://github.com/mitdrc/drake/pull/118 broke some of the atlas balancing tests b/c they involve starting the robot off the ground and using the kinematic_or_sensed support logic. That doesn't play nice with the hack in AtlasPlanEvalAndControlSystem when there's no contact force sensors.

**Comment by rdeits** [comment]
@RussTedrake you can assign this to me and I'll take care of it post-DRC

**Comment by rdeits** [comment]
I've also temporarily fixed those unit tests by starting them with the feet on the ground

**Comment by RussTedrake** [comment]
related to #6381.  with that link established, I will close this one.
