### ISSUE TITLE
Standardize naming for "count" methods to start with num_ rather than get_num_

### ISSUE THREAD

**Issue by sherm1** [RobotLocomotion/drake#11110]
Drake APIs have been inconsistent in naming simple "count" methods like `num_input_ports()` vs. `get_num_input_ports()`. PR #11078 make the System Framework consistently use `num_` for all such methods. Per discussion in that PR, we should consider adopting that standard Drake-wide, deprecating the old `get_` methods, and updating the style guide to reflect that convention.

**Comment by jwnimmer-tri** [comment]
I am happy for the framework to be consistent, since the System and Context deal so frequently in terms of "how many foo's do I have".  I am not sure it's worth bothering with the rest of the tree.  I'd like to suggest closing this until it's a problem.

**Comment by EricCousineau-TRI** [comment]
Er, just to follow-up: I'd be OK to close this as long as this rule is encoded somewhere for the Systems Framework (in a header file or something).

I guess I'd be OK if we chalk up to general consistency without an explicit policy, but it seems like explicit would be nice here?

**Comment by jwnimmer-tri** [comment]
I'm content with either of those options.

**Comment by jwnimmer-tri** [comment]
Over the past year, no re-occurrences of `get_num_foo` have regressed within the systems framework.  To me, that says the cargo-cult / implicit policy for spelling here is sufficiently robust.

@EricCousineau-TRI (or anyone) if you'd like to find somewhere in framework Doxygen to stash this advice then I have no objection, but in the meantime I don't think we need an issue reminding us.

Also, there seems to be no great pull (and I also personally disfavor) any broader project-wide (cppguide) naming rule.

Given all of that status, I'd rather focus on more useful issues instead, so I'm closing this.
