### ISSUE TITLE
doxygen: Do not emit for `*.cc` files, also ignore `internal` namespace when appropriate

### ISSUE THREAD

**Issue by EricCousineau-TRI** [RobotLocomotion/drake#11130]
At present, doxygen shows cruft for things like `GTEST_TEST` and `PYBIND11_MODULE`. Ideally, those shouldn't be there.

**Comment by EricCousineau-TRI** [comment]
Revamped to encompass stuff encountered in #12036.

**Comment by jwnimmer-tri** [comment]
After #12796 merges, we should see if any cruft encompassed by the above complaints still remains.
