### ISSUE TITLE
[hydroelastic] Add tetrahedral data structure

### ISSUE THREAD

**Issue by tri-ltyyu** [RobotLocomotion/drake#11152]
This is a placeholder issue for adding tetrahedral data structure which is needed as Spiral I of Hydroelastic force model implementation

**Comment by DamrongGuoy** [comment]
We have the data structure to represent a tetrahedral mesh now.  It's called VolumeMesh and VolumeMeshField.

However, we don't have code to generate volume meshes for all kinds of primitives.  We only have a code to generate a tetrahedral mesh of a sphere that Alejandro wrote.
