### ISSUE TITLE
Function to evaluate traction at any point

### ISSUE THREAD

**Issue by tri-ltyyu** [RobotLocomotion/drake#11155]
This is a placeholder issue for evaluating traction which is needed as Spiral I of Hydroelastic force model implementation

**Comment by edrumwri** [comment]
Prototyping this week.

**Comment by edrumwri** [comment]
No progress due to on site- still planning to prototype this week.

**Comment by edrumwri** [comment]
PR #11485 is undergoing significant rework to address an efficiency issue pointed out by @amcastro-tri

**Comment by edrumwri** [comment]
Resolved.
