### ISSUE TITLE
[hydroelastic] Contact surface data structure

### ISSUE THREAD

**Issue by tri-ltyyu** [RobotLocomotion/drake#11153]
This is a placeholder issue for adding contact surface data structure which is needed as Spiral I of Hydroelastic force model implementation

**Comment by DamrongGuoy** [comment]
Both this issue #11153 and issue #11214 will be solved by PR #11034.

**Comment by DamrongGuoy** [comment]
Expect to land PR #11034 this week and then close this issue.

**Comment by DamrongGuoy** [comment]
#11034 has landed now.  I close this issue.
