### ISSUE TITLE
Latest drake distro binary with LCM for windows 64

### ISSUE THREAD

**Issue by hjjayakrishnan** [RobotLocomotion/drake#1115]
Could someone tell where I can find the Latest drake distro binary with LCM for windows 64bit ?

**Comment by RussTedrake** [comment]
I have not posted it yet (but did actually get lcm compiling nicely on windows just recently).  We're competing in the darpa robotics challenge this weekend; but i'll post it sometime next week.

**Comment by hjjayakrishnan** [comment]
Thanks a lot, Russ. Eagerly waiting for it.

And good luck to Atlas!

**Comment by RussTedrake** [comment]
it's posted.
