### ISSUE TITLE
Unable to Install

### ISSUE THREAD

**Issue by AeroGauti** [RobotLocomotion/drake#1118]
Hi, i tried to follow the instructions and do accordingly, but i find very difficult with building the collection and testing installation. Any guidance would be a great help. As i am a beginner, finding it very difficult. :(

**Comment by sheim** [comment]
The basic guide is [here](https://github.com/RobotLocomotion/drake/wiki/Installation-and-Quickstart).
If you're new, you should probably first try out the binary version, which is pre-compiled and the easiest way to start.

If you need more help, you should post the specific problems you're having, as well as your OS.
Also, see #1113 if any of your questions are already answered there. Cheers!

**Comment by AeroGauti** [comment]
Hi, thanks for your reply. Installed cmake, and others too, compiled few examples, its running but lot of warnings and errors... Will be back with specific problems.. Cheers!!!!!!

**Comment by sheim** [comment]
Some warnings, like 'zero-crossing detected', are completely normal.
Also, many of the examples require additional libraries like SNOPT
which are not open-source and not included by default. In these cases,
drake will give you an error.

Bu it seems that the installation is working fine now? In which case,
you can close the issue (and for new problems, open a new issue).

Sent from my iPhone

**Comment by AeroGauti** [comment]
How do i close a issue?
