### ISSUE TITLE
Default input-output feedthrough should use prerequisites_of_calc

### ISSUE THREAD

**Issue by jwnimmer-tri** [RobotLocomotion/drake#11194]
When a LeafSystem declares that an OutputPort `calc` function does not use some inputs, the author should not _also_ have to override `DoHasDirectFeedthrough` to tell the framework that same thing again.  The LeafSystem should know the answer already and reply accordingly.

**Comment by sherm1** [comment]
Ideally yes! The default for the prerequisites is very conservative though (as are those for HasDirectFeedthrough) so it's not clear this will be less misleading. Lots of false positives at the moment.

**Comment by jwnimmer-tri** [comment]
Indeed, the immediate effect would be small.  However, it seems _much better_ instruct users to add a prereqs argument to their Declare when they have feedthrough problems, than to override DoGetHasVerbNounThingForAllPortsIntMap or whatever it's called.  Doing it at declare-time is more cohesive, and it will also make caching (much?) more effective.
