### ISSUE TITLE
Compute numerical gradient

### ISSUE THREAD

**Issue by hongkai-dai** [RobotLocomotion/drake#11267]
## Problem
We spend a lot of time making sure that the gradient in `Eval(AutoDiffXd& x, AutoDiffXd* y)` is correct. It would be better if can check the gradient automatically.

## Proposal
Add a method
```C++
void ComputeNumericalGradient(std::function<void (const Eigen::Ref<const Eigen::VectorXd>&, Eigen::VectorXd*)> calc_fun, const GradientOption& option);
```
we can choose to compute the gradient numerically through finite difference, and then compare that gradient against autodiff gradient.

cc @RussTedrake @avalenzu @EricCousineau-TRI

**Comment by EricCousineau-TRI** [comment]
FTR I believe `geval` and `gradTest` were mentioned in our meeting:
https://github.com/RobotLocomotion/drake/blob/last_sha_with_original_matlab/drake/matlab/util/gradTest.m
https://github.com/RobotLocomotion/drake/blob/last_sha_with_original_matlab/drake/matlab/util/geval.m
