### ISSUE TITLE
SceneGraph reports distance result for a specific pair of geometries

### ISSUE THREAD

**Issue by hongkai-dai** [RobotLocomotion/drake#11260]
Currently SceneGraph reports the distance results for every pair of geometries. If I just need the result between a specific pair (with given geometry ID), then SceneGraph does a lot of redundant computation.

**Comment by SeanCurtis-TRI** [comment]
Related to #10990.

**Comment by SeanCurtis-TRI** [comment]
It's not currently in Q4 OKRs. How much is it's absence affecting you?

**Comment by hongkai-dai** [comment]
It's a performance improvement. So if you don't plan to work on it in Q4, that is fine. Do you think it will take a lot of time to add this feature?

**Comment by SeanCurtis-TRI** [comment]
Well, as a one-off, I could probably knock this out quickly. As the original issue suggests, it relates to a more elaborate discussion in #10990 and I'd like to convince myself that doing a quick patch here doesn't conflict in any way with the bigger solution.

**Comment by SeanCurtis-TRI** [comment]
How heavy is the performance hit? Do you have any sense of the size?

**Comment by hongkai-dai** [comment]
I have a system with 10 geometries, so there are 55 different pairs. In many cases I only need 1 or 2 out of these 55 pairs.

**Comment by SeanCurtis-TRI** [comment]
Right...and since this is *distance*, you're getting all pairs (i.e., no culling). So, what's a factor of 25X between friends?

**Comment by DamrongGuoy** [comment]
@hongkai-dai , @SeanCurtis-TRI  I think we can close this issue now, right?

**Comment by SeanCurtis-TRI** [comment]
Correct. This was closed by #12379.
