### ISSUE TITLE
Port SG to use RigidTransform

### ISSUE THREAD

**Issue by tri-ltyyu** [RobotLocomotion/drake#11277]
Per discussion in #9865, upon completion of replacing Isometry with RigidBodyTransform class, there's there's a need to port SG to RigidTransform. Creating this for prioritization and tracking.

**Comment by mitiguy** [comment]
Closed/consolidated this issue (Port SG to use RigidTransform #11277) in favor of
issue #11549 (Update SceneGraph call sites to use RigidTransform instead of Isometry).
