### ISSUE TITLE
Python Simulator(Diagram&) doesn't keep the Diagram alive

### ISSUE THREAD

**Issue by gizatt** [RobotLocomotion/drake#11285]
I ran into an issue (in Python) where a Simulator object that outlives the Diagram it was constructed from leads to a segfault when it's used (for simulation) down the road. I'm pretty sure this is because of the Diagram being freed once it goes out of scope -- global-scoping the Diagram resolves the segfault.

This originally arose using the Simulator-factory architecture used in the MonteCarlo python example PR'd in #11256, but I suspect it's unrelated to the MonteCarlo stuff. The example PR'd is fine, as the Diagram lives in high enough scope, but [this modification, which constructs the Diagram from scratch inside of the Simulator-factory method](https://pastebin.com/rZfR7JVg) segfaults for me.

On the C++ side, there's a `unique_ptr<Diagram>` interface to Simulator that _transfers_ ownership, which is not Python bound -- only the reference version is bound. But there's still a keep_alive that I would hope would increment the reference counter on the Python-owned Diagram and keep it from being cleared till the Simulator dies. 

Have discussed a tiny bit with @EricCousineau-TRI. Workarounds are pretty easy for now, but it's a nasty hole to fall.

**Comment by rpoyner-tri** [comment]
I'll provisionally claim this was fixed by #14356, with the side effect that diagrams became immortal. Requires a bit more investigation to be sure.
