### ISSUE TITLE
PortSwitch primitive system

### ISSUE THREAD

**Issue by RussTedrake** [RobotLocomotion/drake#11287]
As discussed with a few of you, I've got the "PortSwitch" system mostly coded up now, and will PR it this weekend.  It's a simple system that offers many ports on the input, but passes-through only one of them to the output (with one additional input for the port_selector).  I imagine this being useful for combining many low-level controller primitives (e.g. DifferentialIK, PlanEval, hybrid control, etc) with all of them wired up, but only one of them getting called thanks to this switch.

cc @kmuhlrad @pangtao22

**Comment by avalenzu** [comment]
This is the [Multiport Switch](https://www.mathworks.com/help/simulink/slref/multiportswitch.html) block in Simulink, in case you're interested in naming precedents (not that we need to be though).

**Comment by pangtao22** [comment]
Thanks! Are the inputs to the PortSwitch system vector or abstract-valued?

**Comment by RussTedrake** [comment]
It supports either.  Will PR soon.
