### ISSUE TITLE
"Undefined control sequence \Sum" in LMPC documentation

### ISSUE THREAD

**Issue by rcywongaa** [RobotLocomotion/drake#11286]
As seen [here](https://drake.mit.edu/doxygen_cxx/classdrake_1_1systems_1_1controllers_1_1_linear_model_predictive_controller.html#details), there seems to be an error in parsing the equation

**Comment by jwnimmer-tri** [comment]
Over to @EricCousineau-TRI for triage.

**Comment by EricCousineau-TRI** [comment]
Thanks! Filed a PR since it was simple enough to fix: #11314
