### ISSUE TITLE
Velocity frame coordinate names corresponding to quaternion floating joint are wrong

### ISSUE THREAD

**Issue by tkoolen** [RobotLocomotion/drake#1129]
@avalenzu mentioned that in the velocity frame for an RBM, the coordinates for a quaternion floating joint are currently named
[xdot; ydot; zdot; wx; wy; wz]
while the velocity parameterization for a quaternion floating joint is actually twist in body coordinates, so a better set of names would perhaps be
[wx; wy; wz; vx; vy; vz]

**Comment by RussTedrake** [comment]
agreed.  i've pushed the simple change.  let's see if any unit tests were depending on the old name.

**Comment by tkoolen** [comment]
Thanks. Didn't mean to push this on your stack, sorry; I meant to just keep a record of it as I was in the middle of something else.
