### ISSUE TITLE
install: Do not install Bazel-generated python scripts

### ISSUE THREAD

**Issue by EricCousineau-TRI** [RobotLocomotion/drake#11303]
Installing these scripts is worse than useless, it's harmful.

Lost time to this here: https://github.com/robotlocomotion/drake/pull/11261#issuecomment-485510181

**Comment by jamiesnape** [comment]
They didn't used to be; we create different launchers, where necessary. Did something change?

**Comment by EricCousineau-TRI** [comment]
Yeah, just that I had decided to install scripts under `pydrake.examples`, and didn't think to scrub the Bazel-generated stuff. #11304 seems simple enough to fix that mistake

**Comment by jwnimmer-tri** [comment]
For the record, these appear to be the installed stubs, as of Drake v0.17.0.
```
drake/lib/python3.6/site-packages/pydrake/examples/multibody/pendulum_lqr_monte_carlo_analysis
drake/lib/python3.6/site-packages/pydrake/examples/multibody/cart_pole_passive_simulation
drake/lib/python3.6/site-packages/pydrake/examples/multibody/run_planar_scenegraph_visualizer
```

**Comment by EricCousineau-TRI** [comment]
Just curious, can post your recipe used to generate that list?

**Comment by jwnimmer-tri** [comment]
I grepped the v0.17.0 binary release for 'env python$'.

**Comment by jwnimmer-tri** [comment]
The new grep is for `'env python3$'`.  As of v0.39.0, the list of problematic files remains only the same three as above.
