### ISSUE TITLE
pydrake doc: Clarify consistent order of binding (namely for large interfaces)

### ISSUE THREAD

**Issue by EricCousineau-TRI** [RobotLocomotion/drake#11301]
General follow-up to: #11293

See linked PR for an acute pain point on inconsistent binding order.

**Comment by jwnimmer-tri** [comment]
For typical classes that only have ~10 methods, the current status quo is okay by me.  It's monsters like MBP with 100+ definitions where we need to use a pattern that authors and reviewers can follow easily.
