### ISSUE TITLE
Doxygen link to "@ref tangent_force" is dead

### ISSUE THREAD

**Issue by amcastro-tri** [RobotLocomotion/drake#11319]
A user just found out that [this link](https://github.com/RobotLocomotion/drake/blob/9c40c8c0d10cf2a784b39f2eeb98478bb00a5cf8/multibody/plant/multibody_plant.h#L2879) is dead and we'd like to bring back the nice description we had about the Stribeck model (including a great schematic!).

cc'ing @SeanCurtis-TRI who is the original author of those nice docs.

**Comment by SeanCurtis-TRI** [comment]
It was removed in #10622. It probably makes sense to resurrect the parts that are actually still relevant to the MBP model in the MBP documentation.

**Comment by amcastro-tri** [comment]
I bumped the priority of this because just in the last month I had several requests for this, including external people from other companies.

**Comment by SeanCurtis-TRI** [comment]
Currently under review.
