### ISSUE TITLE
mkdoc: Deprecated overloads lose their `_Xargs` specifier?

### ISSUE THREAD

**Issue by EricCousineau-TRI** [RobotLocomotion/drake#11324]
See: https://github.com/RobotLocomotion/drake/pull/11323#pullrequestreview-230393515

Looking at our christmas-tree test, I don't see any `doc_deprecated_Xargs` generated stuff, so mayhaps it wasn't tested?
https://github.com/RobotLocomotion/drake/blob/9c40c8c0d10cf2a784b39f2eeb98478bb00a5cf8/tools/workspace/pybind11/test/sample_header_documentation.expected.h

@jwnimmer-tri I've assigned you to start; feel free to reassign, though.

**Comment by jwnimmer-tri** [comment]
To summarize: there are two methods, each with a full API doc and marked DRAKE_DEPRECATED:
```c++
const systems::OutputPort<T>& get_continuous_state_output_port() const;
const systems::OutputPort<T>& get_continuous_state_output_port(ModelInstanceIndex model_instance) const;
```
But there apparently is only a single `.doc_deprecated` constant.  Presumably, one of the two docstrings is lost / misfiled / unavailable.  The intended behavior is that both constants are available.
