### ISSUE TITLE
Update MultibodyPlant to always use q and v as kinematic variables

### ISSUE THREAD

**Issue by sherm1** [RobotLocomotion/drake#11347]
After #9171 is resolved, it will be possible to declare kinematic variables q and v independently of whether they are ultimately simulated using integration or discrete time stepping. MBP provides both methods but currently is forced to use generic discrete variables when in time stepping mode. We lose the information that the variables affect configuration and velocity, creating problems in properly declaring cache dependencies.

Update MBP to make use of the new state variable abstractions to declare q and v, while still permitting user selection of the simulation update method, and external analysis as a continuous or discrete system.

(This can't be done until #9171 is resolved.)

**Comment by jwnimmer-tri** [comment]
Surely whenever #9171 eventually happens, we will revisit all of Drake's first-party leaf systems to rework them to use the API.  We don't need a second issue reminding us.
