### ISSUE TITLE
Obtain Python runtime from a toolchain rather than flag

### ISSUE THREAD

**Issue by jamiesnape** [RobotLocomotion/drake#11380]
Advance warning that bazelbuild/bazel#7899 will break Drake badly. WIP at https://github.com/RobotLocomotion/drake/compare/master...jamiesnape:incompatible-use-python-toolchains (last commit only, needs Bazel 0.25). FYI @EricCousineau-TRI.

**Comment by jamiesnape** [comment]
(Maybe we can stop having to define `DRAKE_PYTHON_BIN_PATH` too.)

**Comment by EricCousineau-TRI** [comment]
Ooh, yes, removing that env var would be awesome!

**Comment by EricCousineau-TRI** [comment]
Per f2f, seems that this got reverted in 0.26 'cause it broke too many things.
Will come in later versions (probably 0.27 rather).

**Comment by jamiesnape** [comment]
> Per f2f, seems that this got reverted in 0.26 'cause it broke too many things.
Will come in later versions (probably 0.27 rather).

Not reverted, strictly speaking, the flip of the incompatible flag was delayed indefinitely.

**Comment by jamiesnape** [comment]
I am leaning toward trying to ride out have to support selectable Python 2 and 3 support with `--incompatible` flags. Building Python 2 and 3 simultaneously would actually be easier, but we don't support Python 3 on Xenial. Supporting just Python 2 on Xenial and just Python 3 on Bionic and Mac seems easy enough, so waiting for Xenial to disappear is not an issue.

**Comment by EricCousineau-TRI** [comment]
We should target to have this done by Dec. (ideally), in preparation for Bazel 2.0.
