### ISSUE TITLE
Incomplete debug information for ASan

### ISSUE THREAD

**Issue by m-chaturvedi** [RobotLocomotion/drake#11392]
There's a lack of line numbers in the stack for ASan on some Linux (clang) and Mac builds:

[`linux-bionic-clang-bazel-nightly-address-sanitizer`](https://drake-jenkins.csail.mit.edu/view/Nightly%20Production/job/linux-bionic-clang-bazel-nightly-address-sanitizer/148/consoleText)
 [`mac-mojave-clang-bazel-experimental-address-sanitizer`](https://drake-jenkins.csail.mit.edu/view/Mac%20Mojave/job/mac-mojave-clang-bazel-experimental-address-sanitizer/2/)

**Comment by jamiesnape** [comment]
#11489 is at least one example of this slowing down an important feature, so I think medium is probably a fairer priority, especially given the fix is probably quicker than the time it would add next time someone has to chase around the source code for a memory issue.

**Comment by EricCousineau-TRI** [comment]
Resolved by #11730
