### ISSUE TITLE
Missing call to AddAppliedExternalSpatialForces() in MultibodyPlant?

### ISSUE THREAD

**Issue by sherm1** [RobotLocomotion/drake#11410]
An external user reported the following:

> Just pulled master and realized I forgot to communicate that after line 1447, in multibody_plant.cc you need: `AddAppliedExternalSpatialForces(context0, &forces0);`

Please check whether this is missing, and fix if so.

**Comment by amcastro-tri** [comment]
Not very often we see an issue that gives the solution :-).
