### ISSUE TITLE
RoadNetwork should be simplied to use foo_book classes.

### ISSUE THREAD

**Issue by andrewbest-tri** [RobotLocomotion/drake#11412]
RoadNetwork does not have an IntersectionBook member and should. This will enable us to link to the loaders provided in the yaml files. In addition, the presence of rule vectors is unnecessary. 

Victory Conditions:
1. vectors of DirectionUsageRule and SpeedLimitRule are removed.
1. vector of intersections is replaced with IntersectionBook.

**Comment by liangfok** [comment]
I'm closing this since this was handled by 3cd076924fb197fad8e0c1803a62fc504e40aa7b.
