### ISSUE TITLE
PhaseRingBookLoader should also populate a ManualPhaseProvider.

### ISSUE THREAD

**Issue by andrewbest-tri** [RobotLocomotion/drake#11437]
ManualPhaseProvider requires the initial_phase which is only available while processing the yaml file. The loader in
```
drake/automotive/maliput/base/phase_ring_book_loader.h
```
should be updated to populate a ManualPhaseProvider as well.

**Comment by liangfok** [comment]
After studying this issue some more, I think the best option is to modify intersection_book_loader.cc to call `ManualPhaseProvider::AddPhaseRing()` when it is lacking a ring.
