### ISSUE TITLE
need better error message for MbP users who (from their perspective) suddenly need SceneGraph

### ISSUE THREAD

**Issue by RussTedrake** [RobotLocomotion/drake#11448]
I'm seeing a lot of questions like this one below.  In almost every case, they have been working with a MultibodyPlant (without contact), and then change the geometry a bit and suddently start getting these errors.  Clearly, the need for SceneGraph after working with MBPs is coming as a surprise to folks.  

> I also keep running into this error and I'm wondering what the correct way to resolve it is. I've taken some guesses, but none have worked:
```
RuntimeError: InputPort::Eval(): required InputPort[0] (geometry_query) of System ::drake/multibody/MultibodyPlant@0000000004171ff0 (MultibodyPlant<drake::AutoDiffXd>) is not connected
```

**Comment by sherm1** [comment]
Relates to #10874

**Comment by joemasterjohn** [comment]
#13558 adds a less vague error message:
>The geometry query input port (see MultibodyPlant::get_geometry_query_input_port()) of this MultibodyPlant is not connected. Please connect the geometry query output port of a SceneGraph object (see SceneGraph::get_query_output_port()) to this plants input port in a Diagram.

Does that suffice?

**Comment by RussTedrake** [comment]
Thanks @joemasterjohn .  It definitely helps them with a resolution, but might there be a little preamble that helps them understand why the sudden requirement?  something as simple as "you've requested an MBP call that requires a geometry query... " then your text?

**Comment by jwnimmer-tri** [comment]
See also https://github.com/RobotLocomotion/drake/issues/10874#issue-419049303 and https://github.com/RobotLocomotion/drake/issues/10874#issuecomment-471225736.  As part of this resolution, we should also consider updating our examples to use the sugar that always creates an MbP and SG as a single unit.

**Comment by jwnimmer-tri** [comment]
After #17580 lands, what work or cleanup still remains open here?

**Comment by SeanCurtis-TRI** [comment]
I believe all of the strategies discussed in this issue have been addressed by the various issues. #17580 didn't officially close this because I wasn't sure about merging order. I'm happy to update that PR so it automatically closes this.

**Comment by SeanCurtis-TRI** [comment]
As the various solutions have been addressed in merged commits, we'll close this issue. If this crops up again, we can re-open it.
