### ISSUE TITLE
graphviz MBP kinematic chain

### ISSUE THREAD

**Issue by RussTedrake** [RobotLocomotion/drake#11441]
Motivation: We are painfully short on tools for introspecting into the structure of an MBP (especially from python).  As a result, I'm getting constant questions from people who think that our sdf parser has a bug -- i think the reality is the problems are almost always missing sdf format documentation and/or bugs in their sdfs.  But admittedly, we offer essentially no tools for debugging.

Specific proposal: why not be able to graphviz the kinematic tree from an MBP?

**Comment by sherm1** [comment]
A neat idea, and goes well with #10068.
cc @amcastro-tri
