### ISSUE TITLE
SetFromVector gives a "cryptic" error message

### ISSUE THREAD

**Issue by RussTedrake** [RobotLocomotion/drake#11452]
Another frustrated student is seeing 

```
Failure at bazel-out/k8-opt/bin/systems/framework/_virtual_includes/vector/drake/systems/framework/vector_base.h:93 in SetFromVector(): condition 'value.rows() == size()' failed.
```
and finally concluded that
> While cryptic, this seems to imply that my controller is sending fewer inputs to the system than n_actuators, as required?

We should improve the error message to at least report which system / port is having the problem.

**Comment by jwnimmer-tri** [comment]
Fixed in #14101.
