### ISSUE TITLE
Need to provide the way for re-usage of the same traffic bulb groups/bulbs

### ISSUE THREAD

**Issue by vladimir-tri** [RobotLocomotion/drake#11467]
Given that traffic  BulbGroups/Bulbs are repeatable ( different traffic lights may be instantiated using the same bulb groups/bulbs ), it would be necessary to  employ this fact of repeatability in TrafficLights/Intersection book structures to reduce amount of data.

**Comment by liangfok** [comment]
I moved this ticket into Maliput's new repository.
