### ISSUE TITLE
beautiful ImplicitStribeckDocumentation is effectively undiscoverable

### ISSUE THREAD

**Issue by RussTedrake** [RobotLocomotion/drake#11470]
I get a lot of questions about drake's contact model / solver implementation.  I finally went looking for the doc.  I had to work really hard to find it!  And it's quite nice:
https://drake.mit.edu/doxygen_cxx/classdrake_1_1multibody_1_1_implicit_stribeck_solver.html

I don't think any novice could have found it.  Can we please make it more prominent?

**Comment by SeanCurtis-TRI** [comment]
Please take a look at #11431 and see if that doesn't resolve the issue.

**Comment by RussTedrake** [comment]
it does indeed.  hoorah!

**Comment by amcastro-tri** [comment]
@RussTedrake, #11431 just merged. There is an entry point to contact modeling in the [multibody_plant.h here](https://github.com/RobotLocomotion/drake/blob/7b71e21463003f02aba31e2d9138ce8633fdec86/multibody/plant/multibody_plant.h#L164)
