### ISSUE TITLE
SceneGraph's QueryObject has a neutered copy contructor

### ISSUE THREAD

**Issue by sherm1** [RobotLocomotion/drake#11482]
**Background:** QueryObject is somewhat of a misfit in the System Framework architecture. It is required to reside in a SceneGraph output port, yet is not actually a _value_, but rather an _interface_ into SG's context that permits a wide variety of "live" queries to be performed. To make it an actual value would require making a copy of the massive GeometryState; past performance problems tell us that doing so is prohibitively expensive and must be avoided (#10149).

Because we decided that QueryObject must be presented at an output port, and output port values  come from type-erased cache entries, it must be possible to put QueryObject in an AbstractValue. That requires it have a copy constructor, even though this object really should not be copied. To make this work the current implementation contains a stub, hidden-from-Doxygen copy constructor that simply returns a default-constructed QueryObject. This caused a problem reported in #11476 because cloning a Context requires copying all the cache entries, including the one holding a QueryObject. The copy was marked up to date but actually didn't contain current data.

**Problem**: While we have a workaround for #11476, we would like to have a real fix. It is not at all clear that making QueryObject copyable is the right fix. In fact it would be a very expensive copy (including the source context's GeometryState) only to be immediately recalculated to produce a "live" QueryObject referencing the new context's GeometryState.

**Possible solutions**: So while `Value<QueryObject>` ought to be copyable, we should either figure out how to make that cheap or make sure we don't actually invoke the copy when cloning a Context. Several possibilities:
- engineer the copying so that the new QueryObject has a live connection to the new GeometryState rather than a stale copy of the old GeometryState
- allow designation of cache entries that "allocate on copy" in the same vein as some of the reset_on_copy members we have elsewhere. The destination cache entry would then have a default-constructed QueryObject that would initially be marked out of date.

A better alternative IMO would be to consider where we made an architectural error that makes it so difficult to deal with this very fundamental operation of issuing geometry queries. Having shoehorned this interface into an output port might be a reasonable place to look first.

**Comment by SeanCurtis-TRI** [comment]
There is definitely a long term question about whether the `QueryObject` is the right way to fit geometric queries into the system framework.

However, the short term solution is to fulfill the long-existing TODO that says finish off the copy semantics. So, we're doing that in #11484 and using that to close this immediate issue.
