### ISSUE TITLE
Add support for running include-what-you-use (locally and on CI)

### ISSUE THREAD

**Issue by jamiesnape** [RobotLocomotion/drake#11503]
Especially useful for ironing out a few `libstdc++` vs. `libc++` issues that are not handled by `cpplint`.

**Comment by jwnimmer-tri** [comment]
Having full-tree IWYU is also fine, but in my opinion a better answer for standard library includes is that we should teach our cpplint fork about more types and their includes (C++14, etc.).  It should be a fairly simple change.

**Comment by jamiesnape** [comment]
> Having full-tree IWYU is also fine, but in my opinion a better answer for standard library includes is that we should teach our cpplint fork about more types and their includes (C++14, etc.). It should be a fairly simple change.

I do not disagree.

**Comment by jamiesnape** [comment]
CC @EricCousineau-TRI since you asked me a few weeks ago for the issue number regarding `std::array`.

**Comment by jwnimmer-tri** [comment]
This is sufficiently far down on the priorities list that we're going to close it as "not planned".
