### ISSUE TITLE
geometry: Isolate LCM dependency

### ISSUE THREAD

**Issue by jwnimmer-tri** [RobotLocomotion/drake#11507]
The `//multibody/plant:multibody_plant_core` depends on `//geometry:geometry_visualization`, and `//geometry:geometry_visualization` depends on `//lcm` -- oops, now MBP depends on LCM.

There is only one tiny function in `geometry_visulization.h` needed by MBP.  We should carve out that function into some other file, either an existing one or a new one.

**Comment by jwnimmer-tri** [comment]
I'll happily do the PR, but the only hard part is choosing the new location (and name?), which I'll defer to @SeanCurtis-TRI.  Choosing the name is the only hard part though, so it probably makes sense for you do to the PR anyway.  But if you'd like me to, just tell me the (file)names to use.

**Comment by SeanCurtis-TRI** [comment]
Thanks. I'll do it first thing in the morning. As you say, it's trivial.
