### ISSUE TITLE
Visualising per-link inertias

### ISSUE THREAD

**Issue by mauricefallon** [RobotLocomotion/drake#1150]
Given a urdf, I want to visualize the inertias and CoM for each link using ellipses. As well as the combined version.

Is there a demo for doing that? I remember @avalenzu doing this for Atlas using maple wood density as the ellipse scaling...

**Comment by RussTedrake** [comment]
Call `enableLCMGLInertiaEllipsoids` on your BotVisualizer object:
https://github.com/RobotLocomotion/drake/blob/master/systems/plants/BotVisualizer.m

- Russ

**Comment by RussTedrake** [comment]
Feel free to re-open if you have problems with this.

**Comment by mauricefallon** [comment]
Thanks Russ, that was perfect.
