### ISSUE TITLE
LaneSRange should have equality operator.

### ISSUE THREAD

**Issue by andrewbest-tri** [RobotLocomotion/drake#11522]
LaneSRange needs an equality operator defined for boost::python vector indexing support.

> Before you post:

> * Have you reviewed the documentation on
[Getting Help](https://drake.mit.edu/getting_help.html)?
> * Have you reviewed existing GitHub issues and StackOverflow posts?
> * Have you rerun `install_prereqs.sh` on your current commit of `drake`?

> If you have encountered a bug (installation, segfaults, etc.), please try to
post reproduction steps and as much relevant output as possible. Consider
posting long snippets as a [Gist](https://gist.github.com/).

**Comment by liangfok** [comment]
I moved this ticket into Maliput's new repository.
