### ISSUE TITLE
simple_ui.py fails to host all the sliders for robot has too many joints

### ISSUE THREAD

**Issue by guzhaoyuan** [RobotLocomotion/drake#11559]
simple_ui is a gui tool for moving the robot joints with sliders.

The gui fails to display all the joints for robot has too many joints. The window can not host all the sliders.

![Screenshot from 2019-05-30 16-52-49](https://user-images.githubusercontent.com/11495993/58672615-a9951500-82fc-11e9-96eb-e1b9d05b51cf.png)

A scroll bar would be best to help reach down to all the sliders.

**Comment by sherm1** [comment]
BTW @guzhaoyuan has fixed this already and will push a PR shortly.
