### ISSUE TITLE
pydrake: Figure out why `default_scalars_pybind.h` triggers warning on `AutoDiffScalar(const AutoDiffScalar&)`

### ISSUE THREAD

**Issue by EricCousineau-TRI** [RobotLocomotion/drake#11566]
See:
https://reviewable.io/reviews/robotlocomotion/drake/11563#-LgSsDtkA_L2A1NVYhmz:-LgSsDtkA_L2A1NVYhn-:b9fks3f

**Comment by EricCousineau-TRI** [comment]
First step would be to centralize the `ifdef` stuff in `default_scalars_pybind`

**Comment by EricCousineau-TRI** [comment]
This was centralized in #11563; for now, gonna place it on backlog.

**Comment by jwnimmer-tri** [comment]
Either #16074 fixes this, or else is isn't worth worrying about with a tracking issue.
