### ISSUE TITLE
SortedPair<GeometryId> is not hashable

### ISSUE THREAD

**Issue by hongkai-dai** [RobotLocomotion/drake#11578]
I tried to use `SortedPair<GeometryId>` as a key for an unordered map as
```C++
std::unordered_map<SortedPair<GeometryId>, int> my_map;
SortedPair<GeometryId> pair;
my_map.emplace(pair, 0);
```
The compiler says `SortedPair<GeometryId>` is not hashable.

On the other hand, `GeometryId` is hashable, as `unordered_map<GeometryId, int>` works, but when we use `SortedPair<GeometryId>`, it is not hashable.

cc @edrumwri @SeanCurtis-TRI

**Comment by jwnimmer-tri** [comment]
You need to specify `drake::DefaultHash` for the `Hash` template argument of the `std::unordered_map`.

**Comment by edrumwri** [comment]
I also had to add this to identifier.h to get it to work:

```
   /// Implements the @ref hash_append concept.
   template <class HashAlgorithm>
   friend void hash_append(HashAlgorithm& hasher, const Identifier& p) noexcept {
      using drake::hash_append;
     hash_append(hasher, p.get_value());
   }

```

**Comment by jwnimmer-tri** [comment]
Ah yes, I see now that `geometry/identifier.h` does not follow Drake's rules as prescribed by https://drake.mit.edu/styleguide/cppguide.html#std_hash.  Perhaps it predated that rule.
