### ISSUE TITLE
testQuat2expmapSequence unit test failure

### ISSUE THREAD

**Issue by RussTedrake** [RobotLocomotion/drake#1158]
http://kobol.csail.mit.edu/cd/testDetails.php?test=2396391&build=13880

Site: DRAKE003
Build Name: precompiled-pull-RussTedrake-rdeits-rd-merge-drc-into-RobotLocomotion-master
Build Server Directory: C:/cygwin64/tmp/drake-precompiled/drake-29100
Pull Request: #1156
CDash: http://kobol.csail.mit.edu/cd/viewTest.php?onlyfailed&buildid=13880

<matlab_test>strcmp(test_name,'util/test/testQuat2expmapSequence') && strcmp(error_id,'Drake:ValueCheck')</matlab_test>

**Comment by david-german-tri** [comment]
This test seems to be clean on CI nowadays, so I'll close this issue.
