### ISSUE TITLE
Make DifferentialIK leaf system available within pydrake

### ISSUE THREAD

**Issue by naveenoid** [RobotLocomotion/drake#11581]
for examples/manipulation_station/differential_ik.py
Either implement in C++ and as the TODO within this file states or find some other way to expose this functionality to downstream consumers. Assigning to @RussTedrake since his names on the TODO.

**Comment by EricCousineau-TRI** [comment]
FTR We have the function here:
https://drake.mit.edu/pydrake/pydrake.manipulation.planner.html#pydrake.manipulation.planner.DoDifferentialInverseKinematics

**Comment by RussTedrake** [comment]
FTR -- goal is to move that system into c++ (and add the bindings)

**Comment by jwnimmer-tri** [comment]
The file `drake/examples/manipulation_station/differential_ik.py` still exists (including its "puppetmaster" copy-pasta in Anzu, which cites this issue).

I am not totally sure from the above, but my impression was that prior to closing this ticket, we were supposed to delete that manipulation_station file and change the teleop tools to use `DifferentialInverseKinematicsIntegrator` instead.

(Re-opening so we don't lose track of this question.)
