### ISSUE TITLE
pydrake: Bind more APIs for RotationMatrix

### ISSUE THREAD

**Issue by kunimatsu-tri** [RobotLocomotion/drake#11585]
The current `pybind` provides a subset of APIs for `RotationMatrix` as you can see [here](https://github.com/RobotLocomotion/drake/blob/master/bindings/pydrake/math_py.cc#L124-L148) ([permalink](https://github.com/RobotLocomotion/drake/blob/8d0815853c73dc65ea729267b03bc532700f22c7/bindings/pydrake/math_py.cc#L124-L148)).

It would be great if all the APIs are fully covered since it has good stuff in C++. In particular, what I want to use so far is `IsValid` and `ProjectToRotationMatrix`.

**Comment by mpetersen94** [comment]
I need a few of these as well so I was going to throw together a quick pr.  Are there any other specific methods you'd like?

**Comment by kunimatsu-tri** [comment]
Just two methods listed above listed are ok to me for now. Thanks!
