### ISSUE TITLE
Reduce the number of Mac builds in CI

### ISSUE THREAD

**Issue by tri-ltyyu** [RobotLocomotion/drake#11587]
To reduce the load on hardware, we want to reduce the # of test run on nightly (back to level of pre-Mojave). Per f2f in weekly meeting, some proposed ideas are:
- Reduce High Sierra to weekly
- Reduce # of tests

**Comment by tri-ltyyu** [comment]
Assigning to Jamie for now, pls re-assign if needed.

**Comment by jamiesnape** [comment]
Done.
