### ISSUE TITLE
Rewrite MosekTest.SolverOptionsTest to not use MSK_DPAR_SEMIDEFINITE_TOL_APPROX

### ISSUE THREAD

**Issue by jamiesnape** [RobotLocomotion/drake#11608]
`MSK_DPAR_SEMIDEFINITE_TOL_APPROX` does not appear to behave as expected in MOSEK 9.0.

Blocks #11595.

**Comment by hongkai-dai** [comment]
The IT department at TRI mentions that they will add the Mosek 9 license this month. I will rewrite that test once the TRI Mosek license is ready.

**Comment by tri-ltyyu** [comment]
Got an update from Pete at IE. Working on it now and should have an update by tomorrow.

**Comment by EricCousineau-TRI** [comment]
Is this one now potentially unblocked by the license upgrade? (checking convos, seems like we've got the upgrade?)

**Comment by hongkai-dai** [comment]
@EricCousineau-TRI I was working on this last night, will send a patch today.

**Comment by hongkai-dai** [comment]
@jamiesnape I cannot send a PR to your branch, so here is a patch for your PR #11595
[diff.txt](https://github.com/RobotLocomotion/drake/files/3335691/diff.txt), could you apply this patch on top of your PR?

**Comment by jamiesnape** [comment]
Sure, thanks.
