### ISSUE TITLE
InverseDynamicsController output confusing

### ISSUE THREAD

**Issue by guzhaoyuan** [RobotLocomotion/drake#11651]
I spent hours trying to use `InverseDynamicsController`. I finally figured out that the output of `InverseDynamicsController` is actually the generalized_force `Bu` and should be directed to `plant.get_applied_generalized_force_input_port()`. There is no warning or error when I connected to the `plant.get_actuation_input_port()` which only accept `u`, and no evidence in the documentation tells the user about the correct port.

There is no issue for fully actuated single branched robot, because `B` is identity matrix. So in the iiwa `InverseDynamicsController` example it is using `plant.get_actuation_input_port()` and totally fine.

The document for `InverseDynamicsController` output port
![image](https://user-images.githubusercontent.com/11495993/59523815-1f65b880-8e87-11e9-8e37-797e0c31d9ca.png)

The document for `plant` input ports
![image](https://user-images.githubusercontent.com/11495993/59524641-4de49300-8e89-11e9-92cc-744200a19f1f.png)

We should detect the connection between wrong port and give error, add clear explanation about how to use `InverseDynamicsController` correctly, add correct examples.

**Comment by SeanCurtis-TRI** [comment]
@edrumwri I'm assigning this to you -- feel free to pass it along if you feel you're the wrong assignee.

**Comment by edrumwri** [comment]
The documentation for this class states that "this class assumes the robot is fully actuated..." and as you noted, "There is no issue for fully actuated ... robot"
