### ISSUE TITLE
pydrake: For core templated value types, ensure `cast[T]`, `ToType(T)`, or something else is exposed

### ISSUE THREAD

**Issue by EricCousineau-TRI** [RobotLocomotion/drake#11668]
Per @mpetersen94's Slack question:
https://drakedevelopers.slack.com/archives/C3YB3EV5W/p1560874172017900

> With `RigidTransform` now supporting Autodiff in python, what do I need to do to multiply a double-typed `RigidTransform` by a Autodiff-typed vector? Right now it seems to say that the `RigidTranform` needs to be the same type as the vector.

Current workaround would be to "explode" the type into its parts, and then do the conversion... but yuck. It should be simple enough to expose `cast[]` or what not.

**Comment by mpetersen94** [comment]
Would binding [this method](https://drake.mit.edu/doxygen_cxx/classdrake_1_1math_1_1_rigid_transform.html#af22020b0567a392bfc275031a868657f) enable this?

**Comment by EricCousineau-TRI** [comment]
Not exactly... All of those methods are templated on `T`, and thus constrains `other` to also be of type `T`.

Generally, in code when this needs to be done, `.cast<T>()` is used:
https://github.com/RobotLocomotion/drake/blob/a14a4cc82ae0572e82bf15033d0b23988ad8a414/geometry/proximity/test/distance_sphere_to_shape_test.cc#L146

**Comment by mpetersen94** [comment]
Does this have an eta? Even a hacky version that isn't ready for drake master but can convert `RigidTranform` and `RotationMatrix` from `double` to `AutoDiffXd` would be helpful.

**Comment by EricCousineau-TRI** [comment]
Took a whack at it in #11851. Lemme know how it looks.
