### ISSUE TITLE
multibody: Deprecate `SceneGraph<T>* scene_graph = nullptr` args from MultibodyPlant API

### ISSUE THREAD

**Issue by EricCousineau-TRI** [RobotLocomotion/drake#11663]
See discussion here:
https://github.com/robotlocomotion/drake/pull/11633#issuecomment-502854554

\cc @sherm1 @SeanCurtis-TRI @jwnimmer-tri

**Comment by jwnimmer-tri** [comment]
If @sherm1 and @SeanCurtis-TRI agree with the idea, I'm happy to make the PR when I have spare cycles.  This has bothered me for a while.

**Comment by SeanCurtis-TRI** [comment]
I'm likewise happy to see it go (but I'm also looking forward to the day when there's even less SG in MBP.)

**Comment by sherm1** [comment]
I'm neutral -- @amcastro-tri any objections?

**Comment by amcastro-tri** [comment]
I agree nowadays it's not necessary anymore. I like the idea of removing the `scene_graph = nullptr`.
