### ISSUE TITLE
OSQP and SCS export extra symbols

### ISSUE THREAD

**Issue by sammy-tri** [RobotLocomotion/drake#11697]
As mentioned in #11682, both OSQP and SCS have symbols for (at least) `SuiteSparse_malloc` (and related functions).  Per @jamiesnape "If they are vendoring libraries, they should be mangling names. That is the bug regardless of build system. The odds are probably we would need to make that fix."

**Comment by EricCousineau-TRI** [comment]
To figure out priority: Is there an acute failure due to this at the moment?
