### ISSUE TITLE
mp: `result.GetSolution(var)` segfaults if `not result.is_sucess()` for certain solvers

### ISSUE THREAD

**Issue by EricCousineau-TRI** [RobotLocomotion/drake#11699]
From @sadraddini's comment here:
https://github.com/RobotLocomotion/drake/issues/9633#issuecomment-497437906

~I can't see this C++ (at least for a given solver), but I can see it in Python (at least for this given formulation):
https://github.com/EricCousineau-TRI/drake/commit/b4249af1e47765c6f0f83cc45a05d5724fc68fb9~

I can reproduce, both in C++ and Python:
https://github.com/EricCousineau-TRI/drake/commit/f7f2cd6ae

```
# Python
bazel run //bindings/pydrake/solvers:py/mathematicalprogram_test -- TestMathematicalProgram.test_module_level_solve_function_and_result_accessors

# C++
bazel run //solvers:mathematical_program_test -- --gtest_filter='*TestNonlinearExpressionConstraints'
```

\cc @hongkai-dai

**Comment by EricCousineau-TRI** [comment]
@hongkai-dai Seems like this is a C++ issue in general (see edit above)

**Comment by EricCousineau-TRI** [comment]
As Hongkai mentioned in upstream thread, it seems like it *might* be dependent on what solver it is.

**Comment by EricCousineau-TRI** [comment]
Checking in debug mode, failure is caught using `DRAKE_ASSERT`:
```
abort: Failure at solvers/mathematical_program_result.cc:52 in GetVariableValue(): condition 'variable_values.rows() == static_cast<int>(variable_index->size())' failed.
```
Should we use `DRAKE_DEMAND` here (not to resolve this, but to make error more clear)?

That being said, my initial guess is that OSQP's code paths do not call `MathematicalProgramResult::set_x_val`, which seems to be confirmed here:
https://github.com/RobotLocomotion/drake/blob/3ee9090108b50e75ce88f259255ca9a8a08d11a1/solvers/osqp_solver.cc#L289-L319

Question is:
Should `x_val_` always be populated correctly, and if so, what should it be? (NaN?)
Or should `GetSolution(...)` fail-fast if it was unsuccessful? (thus avoiding the need for this policy?)

\cc @jwnimmer-tri

**Comment by hongkai-dai** [comment]
I think when I call `MPResult::GetSolution()`, it should check if `x_val_` is empty or not. If `x_val_` is empty, then `MPResult::GetSolution()` should just return some NaNs, to indicate that the problem is not solved successfully.

I will send a quick PR.

**Comment by EricCousineau-TRI** [comment]
Sounds good! Will reassign for now, thanks!
