### ISSUE TITLE
`RollPitchYaw` performs `if` logic on symbolic

### ISSUE THREAD

**Issue by ggould-tri** [RobotLocomotion/drake#11700]
In `roll_pitch_yaw.cc`:185 there is an `if` on comparisons with T type variables (which can be symbolic).  This triggers an Evaluate without a meaningful environment and so blows up in my use case (random distributions over angles).

Those comparisons should use `if_then_else` instead, and this case should be tested.

See https://drakedevelopers.slack.com/conversation/C2WBPQDB7/p1561056705064800 for original conversation.

Thanks!

**Comment by sherm1** [comment]
Looks like a job for you, @mitiguy !

**Comment by sherm1** [comment]
@ggould-tri what's an appropriate priority for this?

**Comment by ggould-tri** [comment]
I was able to work around it in my code by reordering my operations, so it's not a "things are broken" priority.  I think the question is how it relates to dynamics work.

The fix should be trivial; the test coverage I don't know.

**Comment by jwnimmer-tri** [comment]
I believe that #10495 already resolved this.
