### ISSUE TITLE
Add is_expanded to symbolic expression

### ISSUE THREAD

**Issue by hongkai-dai** [RobotLocomotion/drake#11741]
# Problem statement
Currently when we construct a  symbolic polynomial from an expression `e`, the constructor of the symbolic polynomial expands the expression, by recursively expanding the sub-expression in `e`. This approach is not efficient. For example, if we have three expressions `e, f1` and `f2`, and we want to expand `e * f1` and `e * f2`. Then when we expand `e * f1`, we need to expand `e`; but when we expand `e * f2`, we need to expand `e` again.

# Proposed solution
We add a flag `bool is_expanded` to `symbolic::Expression`. When we call `Expression::Expand()` and `is_expanded` flag is true, then `Expand()` function does nothing. Hence when we need to expand `e * f1` and `e * f2`, we first expand `e` to get `e_expanded`, then we expand `e_expanded * f1` and `e_expanded * f2`, and we only need to expand the common expression `e` for once.

@soonho-tri what do you think?

**Comment by soonho-tri** [comment]
I am implementing this proposed solution in my WIP branch. Let's talk about it in the scheduled meeting this afternoon.
