### ISSUE TITLE
[render] Assess IPC render engine implementations

### ISSUE THREAD

**Issue by SeanCurtis-TRI** [RobotLocomotion/drake#11748]
## Problem statement

There are mature renderers (in both render engines and authoring packages) which provide APIs such that we could create a Drake `RenderEngine` that invokes a renderer vis inter-process communication. This could provide a path to exercising mature technologies without trying to embed them into Drake directly.

Two possibilities:
  - Game engine: e.g., Unity or UnrealEngine.
  - @gizatt had done a [prototype with Blender](https://github.com/gizatt/blender_server) discussed in [this slack thread](https://drakedevelopers.slack.com/archives/D5DTBD2G5/p1552278586002200).

This approach has all sorts of inherent challenges. As the investigation begins, this statement will be extended to offer a more complete discussion of the unique challenges.

**Comment by EricCousineau-TRI** [comment]
Thanks! And just to check, do you mean Blender, not Bullet?

**Comment by sherm1** [comment]
Oops, yes -- fixed.

**Comment by jwnimmer-tri** [comment]
I wonder if this issue should be closed in lieu of #15915, which I believe is the same feature request, but the one actually being worked / tracked?

**Comment by SeanCurtis-TRI** [comment]
This is actively being pursued and doesn't need to be tracked here.
