### ISSUE TITLE
[render] Assess viability of filament as PBR real-time RenderEngine implementation

### ISSUE THREAD

**Issue by SeanCurtis-TRI** [RobotLocomotion/drake#11745]
[Google filament](https://github.com/google/filament) is an open-source, cross-platform physically-based render engine (PBR). Images such as [this](https://google.github.io/filament/webgl/parquet.html) are highly suggestive that the render *quality* is what we're looking for. However, there are a number of issues that need to be considered:

1. Integration
    - Are there issues with exercising it Drake?
    - Can it support the `RenderEngine` API? E.g., can we get label, depth, and color images from it?
2. Mac-compatible
    - Although billed a cross-platform compatible, this needs to be confirmed for Drake.
3. Authoring 
    - What will it take to author content? 
    - What will it take to load content?
 
(Edit this as more issues become interesting.)

## Deliverable

This should come in *two* parts:

1. A survey of our current usage and expected usage of a PBR engine. What features do we rely on? Which do we wish we could rely on?
2. Sufficient code to determine how filament lines up with the initial survey and its usability. This will not be code intended for merging into master but could serve as a starting point if filament is determined to be viable.

Ultimately, the deliverable is a document capturing the two enumerated "parts".

**Comment by SeanCurtis-TRI** [comment]
See @gizatt's initial analysis in the slack channel: https://drakedevelopers.slack.com/archives/C3GG2R4JY/p1543862958012700?thread_ts=1543862958.012700

**Comment by soonho-tri** [comment]
> Mac-compatible

This might be useful: https://github.com/dartsim/homebrew-dart/blob/master/Formula/filament.rb

**Comment by SeanCurtis-TRI** [comment]
Heh...looks like Amazon must be interested in it as well. (Ironic since they have their own game engine.)

**Comment by SeanCurtis-TRI** [comment]
Closing this for now; we can revisit it if filament evolves.
