### ISSUE TITLE
Use OS version of Eigen

### ISSUE THREAD

**Issue by jwnimmer-tri** [RobotLocomotion/drake#11758]
We are using a pinned version of Eigen (3.3.3) because it used to be the case that the OS version of Eigen was too old on most platforms (Trusty and Xenial).  However, in Bionic we have 3.3.4 available.

So once we drop support for Xenial (#10606) there is no more reason to pin and download and install our own version of Eigen.

I'd like to start that transition now, conditioned on an `os != xenial` guard in `repository.bzl`, so that we can both de-risk it and and reap the benefits prior to the Xenial EOL date.

- Use ubuntu Eigen 3.3.4 on Bionic.
- Use homebrew Eigen 3.3.7 on macOS.

**Comment by jwnimmer-tri** [comment]
Thoughts @EricCousineau-TRI and @jamiesnape?

\CC @soonho-tri

**Comment by jamiesnape** [comment]
Good idea.

**Comment by soonho-tri** [comment]
Nice!

**Comment by EricCousineau-TRI** [comment]
Sounds good to me!
