### ISSUE TITLE
Compute center of mass of MultibodyPlant

### ISSUE THREAD

**Issue by guzhaoyuan** [RobotLocomotion/drake#11767]
We need a function to compute center of mass position of `MultibodyPlant`. 
The function could take in options such as set of `ModelInstanceIndex` or set of `BodyIndex` to compute the center of mass of elements specified in the set.

**Comment by huihuaTRI** [comment]
@guzhaoyuan Is this already in master? If yes, we could just close this issue.

**Comment by guzhaoyuan** [comment]
Yes, this function is implemented in MultibodyPlant.
https://github.com/RobotLocomotion/drake/blob/3d388ab19b46a913a4b6a5633744c0f9bcbe5697/multibody/plant/multibody_plant.h#L2013
