### ISSUE TITLE
buildcop: `snopt_solver_test`  has ASan issues

### ISSUE THREAD

**Issue by EricCousineau-TRI** [RobotLocomotion/drake#11781]
Can reproduce failure locally on latest `master` @ 7b257f324:
```
$ ( set -ex; CC=$(which clang); CXX=$(which clang++); bazel test -c dbg --config=snopt_fortran --config=asan --test_tag_filters=snopt //solvers:s
nopt_solver_test ; )
```

Failures:
https://drake-cdash.csail.mit.edu/testDetails.php?test=31002769&build=1193356 (xenial)
https://drake-jenkins.csail.mit.edu/job/linux-bionic-clang-bazel-weekly-snopt-fortran-address-sanitizer/changes | https://drake-cdash.csail.mit.edu/testDetails.php?test=31083270&build=1193482 (bionic)

---
UPDATE:
Succeeds (does not fail) locally on my machine, using old commit (same as more [recent successful build](https://drake-jenkins.csail.mit.edu/job/linux-bionic-clang-bazel-weekly-snopt-fortran-address-sanitizer/4/)): d54213152

Bisecting with:
```sh
$ cat > ~/tmp/drake_issue_11781.sh <<'EOF'
#!/bin/bash
set -eux -o pipefail

CC=$(which clang)
CXX=$(which clang++)
bazel test \
    -c dbg --config=snopt_fortran --config=asan --test_tag_filters=snopt \
    //solvers:snopt_solver_test
EOF
$ chmod +x ~/tmp/drake_issue_11781.sh
$ git bisect start 7b257f3 d542131 --
$ git bisect run ~/tmp/drake_issue_11781.sh
```

Offending commit is 24cda05d3edd2b1097821c304d37afcd337a5bae
```
24cda05d3edd2b1097821c304d37afcd337a5bae is the first bad commit
commit 24cda05d3edd2b1097821c304d37afcd337a5bae
Author: Jamie Snape <jamiesnape@users.noreply.github.com>
Date:   Mon Jul 1 10:38:41 2019 -0400

    Add strip_path_prefix and other sanitizer options (#11750)
```

**Comment by EricCousineau-TRI** [comment]
@jamiesnape Looks like either your commit introduced a check that wasn't running before, or perhaps lost some filtering info...
Do you know which it might be?

\cc @tri-ltyyu

**Comment by jamiesnape** [comment]
It would be the former (our previous config must have been fooling us that we were checking this). There is no filtering to apply. If this is a problem internal to SNOPT, since we cannot currently handle whitelists, I would be inclined to apply a patch to SNOPT/Fortran at build time to add attributes.

**Comment by EricCousineau-TRI** [comment]
Aye. From briefly debugging, it looks like passing the filename is what causes the overrun:
https://github.com/RobotLocomotion/drake/blob/7b257f3247429a3771fb10647919a9b297511210/solvers/snopt_solver.cc#L783

If I disable file logging (indicated by the stack trace), the test fails (of course), but there no longer is a buffer overrun:
```patch
diff --git a/solvers/snopt_solver.cc b/solvers/snopt_solver.cc
index 7bcfdddab..25644653a 100644
--- a/solvers/snopt_solver.cc
+++ b/solvers/snopt_solver.cc
@@ -780,7 +780,8 @@ void SolveWithGivenOptions(
     print_file_name = print_file_it->second;
   }
   Snopt::sninit(
-      print_file_name.c_str(), print_file_name.length(), 0 /* no summary */,
+      // print_file_name.c_str(), print_file_name.length(), 0 /* no summary */,
+      nullptr, 0, 0,
       storage.iw(), storage.leniw(),
       storage.rw(), storage.lenrw());
   auto guard = MakeGuard([&storage]() {
```

**Comment by jamiesnape** [comment]
Or maybe we can do similar to this for now?
https://github.com/RobotLocomotion/drake/blob/b2050ed81bd6e674da93406df8090e888988b12c/solvers/test/snopt_solver_test.cc#L118-L131

**Comment by EricCousineau-TRI** [comment]
Ooh, nice! Yeah, trying that out.

**Comment by jamiesnape** [comment]
Out of interest, can you try setting `strict_string_checks=0`?

**Comment by EricCousineau-TRI** [comment]
Yup, patching `strict_string_checks=0` on current `master` (7b257f324) does suppress the error.
