### ISSUE TITLE
implement TaylorVar in c++

### ISSUE THREAD

**Issue by RussTedrake** [RobotLocomotion/drake#1179]
Again @tkoolen has done a beautiful first pass at this, using Eigen's autodiff scalar
https://www.dropbox.com/s/24lrdb5lgmw7x2e/AutoDiffTest.tar?dl=0

**Comment by tkoolen** [comment]
Can I try using AutoDiffScalar in the manipulatorDynamics function of AcrobotPlant? Or are you already working on this?

**Comment by RussTedrake** [comment]
Haven'f started.  By all means go for it.  Thanks!

**Comment by tkoolen** [comment]
Just got an initial implementation working. See https://github.com/tkoolen/drake/tree/tk-autodiff-scalar.

Still to do:
1. move utility functions to a better place (I just put them in manipulatorDynamics.cpp for now)
2. add support for higher order TaylorVars (non-trivial)

I think I'll skip 2 for now, do 1, and submit a pull request.

**Comment by tkoolen** [comment]
OK, I did 1. I also added a templated function called eigenToMatlabGeneral, with specializations that call eigenToMatlab, eigenToTrigPoly, or eigenToTaylorVar based on the type of the input. This allowed me to clean manipulatorDynamics.cpp up quite a bit. Have a look.

**Comment by tkoolen** [comment]
See https://github.com/RobotLocomotion/drake/pull/1191.

**Comment by RussTedrake** [comment]
excellent!

**Comment by RussTedrake** [comment]
resolving as duplicate of #1199.
