### ISSUE TITLE
MultibodyPlant API needs grouping & reordering for Doxygen clarity

### ISSUE THREAD

**Issue by sherm1** [RobotLocomotion/drake#11807]
MultibodyPlant has a large API. Many of the methods naturally fall into related groups (including overload sets with identical names and related methods with similar names). Some of the methods have been grouped nicely in the [Doxygen documentation](https://drake.mit.edu/doxygen_cxx/classdrake_1_1multibody_1_1_multibody_plant.html) but many (> 100) are ungrouped, making it very difficult for users to find what they need.

While there may be many ways to re-engineer this API, that's out of scope for this issue. Instead, there are some short-term improvements that would make the existing API easier to navigate in Doxygen:
- create new `@name` groups so that all related methods are grouped together
- write some overall documentation for each group to explain the common theme therein
- reorder groups as necessary to put the most commonly-used methods near the top
- collect the many deprecated methods in their own group at the bottom.

For reviewer sanity, code _moving_ should be done in its own PR, where the description promises that _no_ code or existing-documentation changes have been made. That way the vast seas of green in Reviewable can be ignored. Then adding the new `@name` text and any required local method documentation changes can be put in a separate PR that does not do _any_ code moving. That could also be done in a multiple-PR series that does some moving, some updates, some more moving, etc.

Assigning to @mitiguy for consideration, with @amcastro-tri as likely feature reviewer.

**Comment by amcastro-tri** [comment]
This would be a great improvement. Thanks @mitiguy and @sherm1.

**Comment by SeanCurtis-TRI** [comment]
On PR management -- alternatively, you could do it in a 2-commit, single PR where one commit does the moving and the other commit adds content. It's simple to map those first two commits to two Reviewable revisions with subsequent changes adding single revisions. Feel free to ping me if you like this idea -- I've used it in the past with success.

**Comment by amcastro-tri** [comment]
I like @SeanCurtis-TRI's proposal.
