### ISSUE TITLE
Validate a passed Context corresponds to the proper System

### ISSUE THREAD

**Issue by edrumwri** [RobotLocomotion/drake#11801]
I just spoke with a fellow Drake user who has been bit by a bug that I've been bitten by multiple times: one inadvertently passes the wrong Context to a system (usually happens when failing to pass in a subsystem Context).

Often, one will receive a puzzling error message. In this user's case, it was:

`abort: Failure at bazel-out/k8-opt/bin/systems/framework/_virtual_includes/context_base/drake/systems/framework/context_base.h:237 in MaybeGetFixedInputPortValue(): condition '0 <= index && index < num_input_ports()' failed.
`

Since a System creates its Context, it can associate a unique identifier for that System with that Context. Or, if a unique identifier isn't desirable (I could imagine that we would want to be able to pass that Context to two identical systems), a hash might be the answer instead.

There might be an even easier solution but I think letting the user figure this one out on their own is no longer acceptable.

**Comment by sherm1** [comment]
@drum are you able to run this is Debug? In theory you should get a much better message in that case. If that works, we can hopefully find a cheap subset of tests to leave enabled in Release.

**Comment by sherm1** [comment]
Er, @edrumwri that is (see previous comment).

**Comment by edrumwri** [comment]
That _was_ the output in debug mode. When I've experienced this problem in release mode before, I've been gifted with only a "Segmentation Fault" message :(

**Comment by jwnimmer-tri** [comment]
To help inform a solution, please provide an acute example (real code or pseudo-code) that shows the user(s)' call sequence(s) that failed to produce a good diagnostic.

**Comment by edrumwri** [comment]
Here's an example without _any_ warning or diagnostic that should produce one:

```
class FirstLeafSystem : public LeafSystem<double> {};
class SecondLeafSystem : public LeafSystem<double> {};

void ShouldBlow() {
  FirstLeafSystem sys1;
  SecondLeafSystem sys2;
  auto context = sys1.CreateDefaultContext();
  sys2.Publish(*context);
}
```

One possible response could be that an error might be encountered when that Context is used- though it might not be- and I can't think of a good reason for the particular use above not to be caught.

**Comment by sherm1** [comment]
Yup, should have blown up.
