### ISSUE TITLE
Trajectories through walls with office.urdf

### ISSUE THREAD

**Issue by peteflorence** [RobotLocomotion/drake#1184]
@scottviteri @rdeits 

With the current office.urdf from this May 8 commit https://github.com/RobotLocomotion/drake/commit/25ea55e441d63b8d17557be6a720bb6486f6ab53, runMixedIntegerOffice gives me a trajectory that goes through this wall:

<img width="1920" alt="screen shot 2015-07-16 at 8 02 06 am" src="https://cloud.githubusercontent.com/assets/5640360/8722703/3ce4682e-2b95-11e5-98ee-c08fe7559d78.png">

I reverted to the office.urdf version from before that commit https://github.com/RobotLocomotion/drake/blob/67f43ec7d4eb4c83ad1a258ede1724de2de09705/examples/Quadrotor/office.urdf, and it gave me a collision-free trajectory:

<img width="1920" alt="screen shot 2015-07-16 at 8 18 10 am" src="https://cloud.githubusercontent.com/assets/5640360/8722654/c9d467d0-2b94-11e5-8626-6d44fdd820d3.png">

@scottviteri should we not just revert to your older version?

**Comment by scottviteri** [comment]
For right this second you can revert to the old version, but I'll fix the
new version today.

-Scott

**Comment by RussTedrake** [comment]
resolved in  #1187
