### ISSUE TITLE
Possibility of adding a joint group tag in the sdf/urdf of Drake

### ISSUE THREAD

**Issue by huihuaTRI** [RobotLocomotion/drake#11857]
During the Drake developer meeting, we have discussed the possibility to add tags which could put certain joints into a group in the urdf or sdf. The purpose is to easily grab/set state or command for certain joints. For example, the joints for the left arm or just the torso. It turns out that such tags are not available in urdf/sdf. 

The question is that is it possible to add those customized tags in urdf/sdf and get processed by Drake. 

One way to work around this is to just create several leaf systems to do this kind of tasks specifically.

**Comment by sherm1** [comment]
If this isn't already in urdf/sdf this would be a novel Drake feature. Can you explain what it would be used for and why a user couldn't do it already using joint names (for example)?

**Comment by jwnimmer-tri** [comment]
I would argue that in any case, the correct process would be to design and implement and validate this feature in TRI-internal repository (aka Anzu) first to de-risk its requirements, and only if and when we've built up that experience with the solution space to contribute it back to Drake.

**Comment by huihuaTRI** [comment]
To answer Sherm's question, an example case would be wanting to control a particular arm of a mobile base robot with more than one arm, while keeping the rest of the body static. This is a feature in Moveit!, in which you can generate a trajectory plan for arbitrary limbs.

It is good to have, but not a necessary feature.

**Comment by EricCousineau-TRI** [comment]
Can you point to MoveIt! documentation that embeds these tags within URDF? I thought they ultimately used a separate config file for handling joint groupings and all that?

**Comment by huihuaTRI** [comment]
I have limited experience with MoveIt! also. I tend to close this issue for now since I already have some workaround solution for my problem.

**Comment by EricCousineau-TRI** [comment]
Just out of curiosity, can you mention what your workaround was?

**Comment by huihuaTRI** [comment]
It's a very tedious way. I just create controllers for different parts and list the joint names of that part explicitly.
