### ISSUE TITLE
Remove Isometry3 from systems/rendering

### ISSUE THREAD

**Issue by SeanCurtis-TRI** [RobotLocomotion/drake#11888]
The `systems/rendering` folder still has a number of artifacts that all depend on `Isometry3` -- this needs to be scrubbed as well.

When addressing this, search for TODO(#11888) to find related artifacts.

**Comment by SeanCurtis-TRI** [comment]
NOTE: This impacts `geometry/` because `SceneGraph` uses the `PoseBundle` class to communicate with `drake_visualizer`. If we created a single `drake_visualizer` system that connected to `SceneGraph`'s `QueryObject` output port then this output port could simply be eliminated.

**Comment by jwnimmer-tri** [comment]
FWIW it would be super quick to just change PoseBundle to use RigidTransform -- deprecate a getter/setter pair and add new ones.  Probably a 200 LOC PR.

**Comment by SeanCurtis-TRI** [comment]
Thinking deprecate `set/get_pose` and adding `set/get_transform`?

**Comment by jwnimmer-tri** [comment]
Exactly.  (I didn't actually think about the names, but I think that's a good name.)
