### ISSUE TITLE
Upstream scs release vendors stale, incompatible version of qdldl

### ISSUE THREAD

**Issue by jwnimmer-tri** [RobotLocomotion/drake#11883]
Drake master is currently using **[SCS](https://github.com/cvxgrp/scs) v2.0.2** from Nov 30, 2017.  We would like to upgrade to the next (and most recent) release **SCS 2.1.1** from Jul 8, 2019, per our policy of always using the latest upstream releases.  (See https://github.com/cvxgrp/scs/releases page for the list of SCS releases.)

During the past 21 months since the last release, SCS has updated from using `linsys/direct/external/ldl.h` in v2.0.2 to `linsys/direct/external/qdldl/qdldl.h` in 2.1.1.

Separately, Drake also depends on [OSQP](https://github.com/oxfordcontrol/osqp) which itself uses [QDLDL](https://github.com/oxfordcontrol/qdldl/).

The problem is that SCS has vendored a stale, incompatible copy of QDLDL into their externals folder.  Building SCS against the latest QDLDL used by OSQP does not work.  I have not tried building two different copies of QDLDL into Drake at once, but I suspect it would not work.

We should find some way to upgrade to the latest SCS.  I suspect we will have to submit a PR to SCS to vendor and use the latest QDLDL, have them release a new version number of SCS, and then upgrade Drake to that new version, skipping 2.1.1 entirely.

My WIP branch for the SCS upgrade is ~~at https://github.com/jwnimmer-tri/drake/commits/new-release-scs,~~ _below,_ as a starting point for this work.

```patch
diff --git a/tools/workspace/scs/package.BUILD.bazel b/tools/workspace/scs/package.BUILD.bazel
index 6671391..0a731c3 100644
--- a/tools/workspace/scs/package.BUILD.bazel
+++ b/tools/workspace/scs/package.BUILD.bazel
@@ -23,8 +23,8 @@ config_setting(
 
 SCS_HDRS = glob(["include/*.h"]) + ["linsys/amatrix.h"]
 
-# TODO(jamiesnape): Use system AMD and LDL instead of outdated versions in
-# linsys/direct/external. These are licensed under the LGPL so only build a
+# TODO(jamiesnape): Use the system-provided AMD instead of the outdated version
+# in linsys/direct/external.  It is licensed under the LGPL so only build a
 # shared library for :scsdir.
 
 cc_binary(
@@ -32,8 +32,10 @@ cc_binary(
     srcs = SCS_HDRS + glob([
         "linsys/*.c",
         "linsys/common.h",
-        "linsys/direct/**/*.c",
-        "linsys/direct/**/*.h",
+        "linsys/direct/external/amd/*.c",
+        "linsys/direct/external/amd/*.h",
+        "linsys/direct/private.c",
+        "linsys/direct/private.h",
         "src/*.c",
     ]),
     defines = ["USE_LAPACK=1"],
@@ -53,6 +55,7 @@ cc_binary(
     deps = [
         "@blas",
         "@lapack",
+        "@qdldl",
     ],
 )
 
@@ -69,8 +72,7 @@ install(
     targets = [":libdrake_scsdir.so"],
     docs = [
         "LICENSE.txt",
-        "linsys/direct/external/AMD_README.txt",
-        "linsys/direct/external/LDL_README.txt",
+        "linsys/direct/external/amd/LICENSE.txt",
     ],
     doc_strip_prefix = ["linsys/direct/external"],
 )
diff --git a/tools/workspace/scs/private.h.diff b/tools/workspace/scs/private.h.diff
new file mode 100644
index 0000000..eaef719
--- /dev/null
+++ b/tools/workspace/scs/private.h.diff
@@ -0,0 +1,11 @@
+--- linsys/direct/private.h.orig       2019-07-08 15:10:47.000000000 -0400
++++ linsys/direct/private.h            2019-08-01 09:45:48.339703815 -0400
+@@ -7,7 +7,7 @@
+ 
+ #include "common.h"
+ #include "external/amd/amd.h"
+-#include "external/qdldl/qdldl.h"
++#include "qdldl.h"
+ #include "glbopts.h"
+ #include "scs.h"
+ 
diff --git a/tools/workspace/scs/repository.bzl b/tools/workspace/scs/repository.bzl
index 21922a2..1461795 100644
--- a/tools/workspace/scs/repository.bzl
+++ b/tools/workspace/scs/repository.bzl
@@ -8,8 +8,11 @@ def scs_repository(
     github_archive(
         name = name,
         repository = "cvxgrp/scs",
-        commit = "v2.0.2",
-        sha256 = "8725291dfe952a1f117f1f725906843db392fe8d29eebd8feb14b49f25fc669e",  # noqa
+        commit = "2.1.1",
+        sha256 = "0e20b91e8caf744b84aa985ba4e98cc7235ee33612b2bad2bf31ea5ad4e07d93",  # noqa
         build_file = "@drake//tools/workspace/scs:package.BUILD.bazel",
+        patches = [
+            "@drake//tools/workspace/scs:private.h.diff",
+        ],
         mirrors = mirrors,
     )
```

\CC @EricCousineau-TRI FYI

**Comment by jwnimmer-tri** [comment]
@jamiesnape @EricCousineau-TRI Can I nudge this a bit higher on the priority list?  Maybe target having some progress prior to the Oct 1st upgrade cycle?

Note that OSQP has releases 0.6.0 now (Drake is at 0.5.0).  I'm planning on leaving the 0.6.0 upgrade to be resolved concurrently with this issue, in case they end up being intertwined.

**Comment by EricCousineau-TRI** [comment]
We've got a few other things to deprecate / upgrade for Oct 1, as well as some other items (e.g. OSPRay).
I'm hesitant to up this in priority if it's just for cleanliness. Would this be blocking any significant features? (e.g. using a good optimizer that we need upgrades for?)

**Comment by jwnimmer-tri** [comment]
It's just a question of how long we want to live on a stale pin of two solvers.  OSQP is relatively prominent in our choose_best_solver matrix.

I will put this back on my radar to work in a week or two, in case other priorities have taken over Jamie's time.  I agree that the work to cull the OS / Py2 support matrix is more important.

**Comment by EricCousineau-TRI** [comment]
SGTM, thanks!
