### ISSUE TITLE
rgbd_sensor: Rework constructor parameters for consistency / future-proofing

### ISSUE THREAD

**Issue by EricCousineau-TRI** [RobotLocomotion/drake#11895]
Relates #11878 per discussion in #11879:
https://github.com/robotlocomotion/drake/pull/11879#pullrequestreview-269687586

If #11879 lands in its current state, the color and depth properties are separate parameters, but the poses are in a separate struct.

We should converge on something that's consistently, and possibly robust.

One option is to stick some or most ctor parameters into `RgbdSensor::Param` (and have it absorb `RgbdSensor::CameraPoses`). This could then handle optional things either with default constructors, or using `optional<>`. This could also be "future proof" adding new options, like specifying a separate renderer (but *not* separate intrinsics) for the label "camera".

\cc @SeanCurtis-TRI

**Comment by jwnimmer-tri** [comment]
I'm not sure exactly what this was about, but I anticipate that the current `CameraConfig` struct is sufficient.
