### ISSUE TITLE
drake_visualizer: Stop using DRAKE_BAZEL_RUNFILES

### ISSUE THREAD

**Issue by EricCousineau-TRI** [RobotLocomotion/drake#11914]
@jwnimmer-tri has ported most stuff in Anzu to use more proper `Rlocation` resource finding. `drake_visualizer` should follow.

At present in Anzu, if we run `drake_visualizer` directly from an `Rlocation`, it's fine.
However, if we ensure that's under `RUNFILE_DIR`s, our PYTHONPATH hack logic breaks.

**Comment by jwnimmer-tri** [comment]
@EricCousineau-TRI I propose closing this as a"WONTFIX" per #16215. What do you think?

**Comment by EricCousineau-TRI** [comment]
SGTM!
