### ISSUE TITLE
Notation in ContactSurface should match camera ready version of hydroelastics paper

### ISSUE THREAD

**Issue by edrumwri** [RobotLocomotion/drake#11931]
In particular, we now need to rename E, which was the generic field for computing the contact surface, to `pknot` which is effectively the name used in the cited paper.

**Comment by sherm1** [comment]
`pknot`? Did you mean `pnaught` to represent the symbol p₀ from the paper? If so, I would suggest `p0`  instead.

**Comment by sherm1** [comment]
Damrong, I'm not sure if this is still an issue (it was assigned to Evan). Please close if not. Note low priority - not urgent.

**Comment by DamrongGuoy** [comment]
Right now the public API of `ContactSurface` uses `e_MN` including `EvaluateE_MN(face, barycentric)`, `EvaluateE_MN(vertex)`, and `e_MN()`.  

We should change to `EvaluateP0()`, `p0()`.

**Comment by DamrongGuoy** [comment]
We might want to remove the discussion of hₘₙ from the documentation of [ContactSurface](https://drake.mit.edu/doxygen_cxx/classdrake_1_1geometry_1_1_contact_surface.html) since ∇hₘₙ is not in the API anymore.

**Comment by SeanCurtis-TRI** [comment]
Well, it's still worth discussing because we use the surface normals of the contact mesh as a piecewise-linear approximation of ∇hₘₙ.

**Comment by jwnimmer-tri** [comment]
We seem to be OK without this.  If there is a 30 minute fix, anyone is still welcome to submit it, but it seems this work isn't sufficient important to schedule for the past several years.
