### ISSUE TITLE
Improve exception safety with smart pointers

### ISSUE THREAD

**Issue by elfring** [RobotLocomotion/drake#11935]
Would you like to wrap any pointers with the class template “[std::unique_ptr](https://en.wikipedia.org/wiki/Smart_pointer#unique_ptr "Description for the usage of smart pointers")”?

Update candidates:
- [approximateIK()](https://github.com/RobotLocomotion/drake/blob/61193c5d89c4371c1b6e6aad335e894f2e56e861/attic/multibody/approximate_ik.cc#L18)
- [MultipleTimeKinematicConstraint::eval()](https://github.com/RobotLocomotion/drake/blob/06cd20dc1b852baa9c625d558074877a6ab6a3d2/attic/multibody/rigid_body_constraint.cc#L523)

**Comment by sherm1** [comment]
Thanks, @elfring. We follow the Drake [style guide](https://drake.mit.edu/styleguide/cppguide.html#Ownership_and_Smart_Pointers) (mostly just the Google Style Guide) regarding ownership and use unique_ptr (and rarely shared_ptr) to manage that -- we don't permit raw pointers with uncertain ownership. However when passing const or mutable references as arguments where there is no ownership transfer, the style guide requires pointer arguments for mutable access.

The example you pointed to are just argument references and are also in our `attic/` code which is slated for deprecation. So we won't be changing those. Thanks in any case though, and please let us know if you see other problems.
