### ISSUE TITLE
Install lint and library lint fail when pkg-config dependencies are not installed

### ISSUE THREAD

**Issue by jamiesnape** [RobotLocomotion/drake#11952]
This is due to the tests using `genquery` and causes issues in the `NO_IPOPT` (all platforms), `NO_NLOPT` (all platforms), and `NO_DREAL` (Mac). Easiest may be just to not run those tests, but we could also "fix" `pkg_config.bzl` to defer errors.

Relates #11951.

**Comment by jwnimmer-tri** [comment]
I am not sure that this is meaningfully distinct from #11951?  If we decide support those configs, then we need to fix any linter problems that block it.  If we decide not to support those configs, then this is "wontfix".  I would like close this now, if that works for you?

**Comment by jamiesnape** [comment]
Works for me.
