### ISSUE TITLE
Officially support `no_{solver}` configs?

### ISSUE THREAD

**Issue by EricCousineau-TRI** [RobotLocomotion/drake#11951]
@jamiesnape did some work in #11945 to fix various bugs in `no_{solver}` configs, in response to #11942 for `no_dreal`.

Should we slate spinning up CI for this? Perhaps by mid-November?

@RussTedrake @jwnimmer-tri Can I ask y'all's opinion on this?

EDIT: Jamie mentioned that it may be a day's work fix remaining issues and to set up CI.

**Comment by RussTedrake** [comment]
I’ll defer to you all on this one.

**Comment by EricCousineau-TRI** [comment]
Sounds good.
My vote is yes, let's spin up CI by mid-November.

**Comment by jamiesnape** [comment]
Can we remove the question mark in the title here (or close the issue if the answer is no)?

**Comment by jwnimmer-tri** [comment]
I have not heard a reason why we need to officially support any no_{solver} config.  If someone has one, we can reopen this issue (or open a new one, if there's a more specific topic for support).

**Comment by jamiesnape** [comment]
Cool, an issue pruned. Apparently, I have almost 100 assigned to me across GitHub.
