### ISSUE TITLE
jupyter: Need ability to run notebooks online (e.g. Google Colab), fast + robust

### ISSUE THREAD

**Issue by EricCousineau-TRI** [RobotLocomotion/drake#11962]
At present, there are some notebooks on `underactuated` that can be run with Google Colab. However, the provisioning does not have fixed versioning (which in itself is a hard problem), and cannot easily work with experimental versions.

This generally works, but will break if old notebooks try to run when the provisioning downloads the latest prebuilt Drake, or if a newer notebook wants to use functionality not yet on Drake `master`.
I'm setting this at low priority for now, can raise priority once it becomes a pain point.

\cc @RussTedrake @jwnimmer-tri

**Comment by EricCousineau-TRI** [comment]
@RussTedrake Can I ask if you have a desired due date for this? (following up from #12023)

Most feasibly, we could do it by mid-November given other things on the docket.
We can push it up if it'll help service the Manipulation class, but I'm not sure that you'd get more mileage out of Drake-tested-and-hosted notebooks rather than those in `underactuated`.

**Comment by RussTedrake** [comment]
Responded on slack: https://tri-internal.slack.com/archives/C16R6JA0M/p1568130771009200

**Comment by EricCousineau-TRI** [comment]
From Slack convo, ideal would be October 10, latest would be November 1st.

**Comment by EricCousineau-TRI** [comment]
Two options I'm currently aware of:
* [Google Colaboratory](https://colab.research.google.com/): Provisioning is a bit awkward here, though. Would be nice to have the option of having a Dockerfile / pre-provisioned image rather than having users provision them with inline scripts.
* [Binder](https://mybinder.readthedocs.io/en/latest/). Seems promising, may work with free hosting, may need to pay or self-host. Has option for provisioning based on `Dockerfile`s, which could motivate #10554.

**Comment by EricCousineau-TRI** [comment]
Planning to start work on this ~Oct. 1.

**Comment by EricCousineau-TRI** [comment]
Planning to start on this more towards in the beginning of Nov. (Was deferred due to platform turnover work.)

**Comment by EricCousineau-TRI** [comment]
Example notebooks can be seen in the "tutorials" part here:
https://drake.mit.edu/#core-library

(Binder icon at top right)

**Comment by EricCousineau-TRI** [comment]
Per f2f, Binder's docs for where to put the `Dockerfile`.

Also they don't like `:latest` tags, so Jamie may push a `:devel` tag (assuming this doesn't affects updates).

**Comment by EricCousineau-TRI** [comment]
Per f2f, there may be ~24 hours of difference between `master` and the BinderHub-utilized image.

One solution would be to use a branch, like `nightly`, to have a "moving tag", that people can browse with that branch, e.g.:
https://mybinder.org/v2/gh/RobotLocomotion/drake/nightly?filepath=tutorials%2Fmathematical_program.ipynb (note: this will currently be broken)

@jwnimmer-tri You cool with this?

**Comment by jwnimmer-tri** [comment]
I don't think I have an objection in general to transcribing CI outcomes into git, but I also don't understand what mechanics are being proposed nor what problem is being solved by it, so I can't render a concrete opinion yet.

**Comment by EricCousineau-TRI** [comment]
The problem is that the BinderHub notebooks use Drake `master`, but the provisioned images use the binaries from the nightly jobs. If someone adds functionality to `pydrake`, and then uses that functionality in a Jupyter notebook, then the BinderHub notebook may break because the nightly does not yet support that functionality.

The mechanics would be to restrict BinderHub to only view the nightly versions of the notebooks by using the "nightly" branch as a tag. The nightly job that publishes the Docker images that BinderHub uses would also push to the "nightly" branch on Drake, using the commit that it used to produce the binaries + Docker image.

**Comment by jamiesnape** [comment]
Aside: This would also help with the theoretical issue we have with Linux and Mac packaging builds not necessarily building the same SHA (or any nightlies for that matter). If the Linux build updated the nightly branch, Mac (and any other platforms) could then just pull that branch. Also it would be clear to users of the nightly builds what was built/tested. There are others ways to sync, but that would be a nice easy one.

**Comment by jwnimmer-tri** [comment]
Sounds pretty good.  Two things:

(1) I don't like vanilla "nightly" as the name.  There are a lot of things happening every night.  Something like "nightly-latest" to reflect `drake-latest-bionic.tar.gz` intent would be a start, or maybe "nightly-latest-release", or something.  Maybe y'all can come up with a better idea.

(2) Why a branch?  It seems like exactly what tags are for.  If I recall correctly, branch names pollute clones of `upstream` by default, but tags do not?

**Comment by jamiesnape** [comment]
> (1) I don't like vanilla "nightly" as the name.  There are a lot of things happening every night. 

I am not necessarily advocating this, we could actually make everything nightly use that tag. That would be for a different issue (or not at all). Either way, any name is fine.

> (2) Why a branch? It seems like exactly what tags are for. If I recall correctly, branch names pollute clones of upstream by default, but tags do not?

Depends on your philosophy on whether tags should (always) be immutable. I do not mind either way.

**Comment by EricCousineau-TRI** [comment]
I'm also indifferent. "nightly-latest-release" sounds good to me.

As far as branch vs. tag, I'm fine with either, as long as downstream tools don't expect Git tags to be immutable (and then do something like caching BinderHub notebooks or what not).

**Comment by jwnimmer-tri** [comment]
Hmm.  I think there are some subtleties here.

We can't apply tag a nightly-latest-release and then launch the builds and then upload the binaries -- because in that case we'd have newer notebooks + older binaries during the build window, which is exactly the situation we're trying to avoid.  And if the build fails, the situation would persist beyond the build window.

It has to be more like choose a commit sha, build and publish the binaries, and only then move the tag to that commit.  Furthermore, if the tag is to be understood to apply to more than one build variant, then we actually need to rendezvous all of those builds passing before publishing binaries or moving the tag.  Or at least, publish only `YYYYMMDD` binaries, and only sync them to `latest` as of the rendezvous.

So it could be something like:
- choose a commit to use for the nightly builds, tag as "nightly-latest-pending";
- fire off all the nightly builds, publishing packaging / docker results under a "YYYYMMDD" name;
- only if a sufficient set of builds passed, then tag "nightly-latest-success" from "nightly-latest-pending" and label the "YYYYMMDD" artifacts as "latest".

**Comment by jamiesnape** [comment]
Yes, we do need a provisional nightly tag and a final nightly tag. It is one of major defects that we have at present that the packaging happens before nightly builds (mostly applies to Mac builds in practice, as Linux has so many continuous).

**Comment by jamiesnape** [comment]
That final update job would also be good for adding a monthly release version tag (e.g., the person managing the release logs into Jenkins and starts a build with an extra parameter or two).

**Comment by EricCousineau-TRI** [comment]
Per f2f, current Binder image is broken; e.g. https://mybinder.org/v2/gh/RobotLocomotion/drake/master?filepath=tutorials
Some permission issues.

**Comment by EricCousineau-TRI** [comment]
Per f2f, the first step towards Jeremy's solution would be to (a) turn on testing in the Linux nightly release packaging job and (b) then apply the tag. This is about a 95% solution, which is towards Jeremy's 100% solution.

This is local and wouldn't fix the across-build synchronization issue, but would address the acute failure mode of the Binder-consumed Docker image being flawed.

Then the across-build interlocks could be done in end of January (per f2f with Jamie, we'd need some new infrastructure).

**Comment by jamiesnape** [comment]
My guess for the breakage (since it is now vaguely reproducible) is that they have multiple (randomly assigned?) cloud providers and, therefore, potentially multiple versions of Docker, some of which do not have the fix for https://github.com/moby/moby/issues/35018. I will need to copy the files as root and then add a `CMD` layer changing the permissions, unfortunately.

**Comment by EricCousineau-TRI** [comment]
Jamie is currently testing this mechanism.

**Comment by EricCousineau-TRI** [comment]
Target is EOW (Fri).

**Comment by EricCousineau-TRI** [comment]
FYI Here's the `bazelbuild` issue that lists other solutions people are using:
https://github.com/bazelbuild/rules_python/issues/63

One in particular: https://github.com/bazelbuild/rules_python/issues/63#issuecomment-616958737

> Thanks guys for the starting point. A more recent attempt of mine:
> dayfine/xlab#6
> 
> Basically my setup allows me to use Google Colab with the local libraries (proto, etc) I build with Bazel
