### ISSUE TITLE
Refactor VTK-based renderers into common code base

### ISSUE THREAD

**Issue by SeanCurtis-TRI** [RobotLocomotion/drake#11964]
There are two VTK-based `RenderEngine` implementations: RenderEngineVtk and RenderEngineOspray (as of the creation of this issue, it was in review as #11916). Both of these renderers are based on VTK (which suggests that `RenderEngineVTK` should probably be renamed, but I digress).

Because they both use VTK they have a great deal of plumbing in common. These two render engines should be refactored so that their common code is shared.

**Comment by jwnimmer-tri** [comment]
This might have been obsoleted via #14339?  Unless there is some desire to fold `render_engine_vtk_base.h` inside the VTK renderer directly?

**Comment by SeanCurtis-TRI** [comment]
Definitely going to close this. Separation is no longer required.

Merging *may* be required as their is now *some* "refactored" code, but it's so incredibly low priority, that I'm not going to worry about it.
