### ISSUE TITLE
jupyter: Should install example / tutorial notebooks

### ISSUE THREAD

**Issue by EricCousineau-TRI** [RobotLocomotion/drake#11974]
This would be nice for binary distribution, as well as if we have utility code for Juptyer (e.g. slider demos like what we have in Anzu).

Some notes:
* Hoist prereqs from `source_prereqs` to `binary_prereqs`.
* Ensure that the notebooks are somehow tested in `install_test`.

\cc @jamiesnape

**Comment by jwnimmer-tri** [comment]
The proposal in #13683 is to move the tutorials into a separate repository.  What does that imply for this issue?

**Comment by EricCousineau-TRI** [comment]
That would imply this issue could be closed.

However, coming back a year later and seeing the success of deployment on Google Colab, I think we could close this, regardless of moving to a separate issue.
