### ISSUE TITLE
Docuemntation claims GCC 7.3 on Bionic, is actually 7.4

### ISSUE THREAD

**Issue by jwnimmer-tri** [RobotLocomotion/drake#11998]
The table at https://drake.mit.edu/developers.html (as well as the binary release footnote) claim we use GCC 7.3, but in fact (e.g., per https://drake-jenkins.csail.mit.edu/view/Packaging/job/linux-bionic-unprovisioned-gcc-bazel-nightly-snopt-packaging/293/consoleText) we use GCC 7.4.

**Comment by jamiesnape** [comment]
FTR Looks like it changed in Bionic on April 6, 2019.
