### ISSUE TITLE
pydrake.symbolic docs don't contain class overview

### ISSUE THREAD

**Issue by RussTedrake** [RobotLocomotion/drake#11997]
For instance, all of the great documentation under "Detailed Description" here:
https://drake.mit.edu/doxygen_cxx/classdrake_1_1symbolic_1_1_expression.html

Doesn't appear here:
https://drake.mit.edu/pydrake/pydrake.symbolic.html#pydrake.symbolic.Expression

**Comment by jamiesnape** [comment]
Looks like that documentation has been extracted just fine. It is just up to the author of the bindings to actually use it.

**Comment by RussTedrake** [comment]
Perhaps it's only symbolic expression (and friends?) then.  @soonho-tri -- might you take a look?

**Comment by soonho-tri** [comment]
Copy that. I'm working on a PR.
