### ISSUE TITLE
ContactInfo deprecation dates are inconsistent

### ISSUE THREAD

**Issue by jwnimmer-tri** [RobotLocomotion/drake#12002]
The `num_contacts()` deprecation in #11901 variously says `"12-01-2019"` and `"2019-10-01"` throughout the codebase.  I think both should be spelled as `"2019-12-01"` everywhere?

**Comment by edrumwri** [comment]
This issue has become obviated since the deprecated code has been removed in (#12144). Please reopen if I'm mistaken.
