### ISSUE TITLE
PidController python binding seems to have memory corruption

### ISSUE THREAD

**Issue by RussTedrake** [RobotLocomotion/drake#12027]
Add the following line:
```
        self.assertEqual(controller.num_input_ports(), 2)
```
to
https://github.com/RobotLocomotion/drake/blob/master/bindings/pydrake/systems/test/controllers_test.py#L221

results in
```
test_pid_controller
    self.assertEqual(controller.num_input_ports(), 2)
AssertionError: -751256949 != 2
```

**Comment by RussTedrake** [comment]
fyi @mpetersen94

**Comment by RussTedrake** [comment]
blocking #12009

**Comment by EricCousineau-TRI** [comment]
Can reproduce here: https://github.com/RobotLocomotion/drake/commit/378191ec35bd9674bc9e4102819287eec5f300c0
Debugging...

**Comment by EricCousineau-TRI** [comment]
Ah, multiple inheritance... Didn't realize that this interface had that:
https://github.com/RobotLocomotion/drake/blob/838a9155/systems/controllers/pid_controller.h#L46-L47

I'm pretty sure that's the problem. Will see what I can do.
