### ISSUE TITLE
Remove PositionKinematicsCache and VelocityKinematicsCache from ForceElements methods.

### ISSUE THREAD

**Issue by mitiguy** [RobotLocomotion/drake#12035]
In the classes that inherit from ForceElements

Change  CalcPotentialEnergy( Context, PositionKinematicsCache)
to           CalcPotentialEnergy(Context ).

Change  CalcConservativePower( Context, PositionKinematicsCache, VelocityKinematicsCache)
to          CalcConservativePower( Context)

Change  CalcNonConservativePower(Context, PositionKinematicsCache, VelocityKinematicsCache)
to          CalcNonConservativePower( Context)

**Comment by jwnimmer-tri** [comment]
5 years later, I'm assuming this work is "not planned".
