### ISSUE TITLE
director, drake_visualizer: Support Python 3

### ISSUE THREAD

**Issue by EricCousineau-TRI** [RobotLocomotion/drake#12046]
Towards #10606

**Comment by EricCousineau-TRI** [comment]
@patmarion If you have a chance, can I ask if you have a release / non-volatile branch (one that won't get rebased / deleted after merge at least for a while) for Director Python 3?

You had mentioned the following one, but it's unclear what it's lifetime will be:
https://github.com/RobotLocomotion/director/pull/625

**Comment by EricCousineau-TRI** [comment]
@jamiesnape Can I ask how things are going on this front? Is this something that we could start trying out (e.g. in Anzu) before we remove Mac + Python 2 support?

(Or should we separate out the removal of Mac Python 2 support?)

**Comment by jamiesnape** [comment]
Should be ready tomorrow. Everything builds fine, just have not checked if it actually runs.

**Comment by EricCousineau-TRI** [comment]
A user ran into the issue captured in https://github.com/RobotLocomotion/drake/pull/11134:
https://stackoverflow.com/questions/58270730/drake-frame-visualization-attribute-error
This will be resolved by updating Director, at least on modern platforms (Bionic).

Can I ask when we might have this on Drake master?

**Comment by jamiesnape** [comment]
It's in the queue for Mac, for Bionic after that, so probably late this week.

**Comment by felixcra** [comment]
I'm looking forward to see this work :)

**Comment by jwnimmer-tri** [comment]
Sometime next week (or soon after) is our nominal 0.12.0 release tag.  Be in touch with me if you'd like to ensure that this fix specifically does or does not make it into the release.

**Comment by jamiesnape** [comment]
It probably should be in, but I would not say it should be a blocker. That said, the work is pretty much done, but if release can be the later part of the week, it gives more time to review and test (there is a lot of churn with Mac Python 3 versions at the moment, for instance).

**Comment by jamiesnape** [comment]
Draft PR is now up (#12296).
