### ISSUE TITLE
MultibodyPlant simulation crashes when there are no degrees of freedom

### ISSUE THREAD

**Issue by gizatt** [RobotLocomotion/drake#12066]
Running [this simulation of a MultibodyPlant with nothing in it](https://gist.github.com/gizatt/4faa3327f9f30479451b6e26d526c829) fails with error `Failure at multibody/plant/implicit_stribeck_solver.cc:255 in ImplicitStribeckSolver(): condition 'nv > 0' failed.` I get the same error if I add lots of geometry, but it's all welded to the world.

While there's not terribly much to be learned from simulating that plant, it'd be really nice if it still worked, right?

**Comment by sherm1** [comment]
Yes, that should work!

**Comment by amcastro-tri** [comment]
@gizatt, see #12070.

**Comment by gizatt** [comment]
Nice, thanks!
