### ISSUE TITLE
Be able to set the ignore velocity flag in CalcGravityGeneralizedForces

### ISSUE THREAD

**Issue by yangwill** [RobotLocomotion/drake#12064]
When calculating the generalized gravitational forces using UniformGravityFieldElement::CalcGravityGeneralizedForces, the calculated gravitation forces does not match the expected gravitational forces when there are non-zero velocities. 

This was fixed in my local version of drake by moving the version of CalcInverseDynamics with the ignore_velocities flag to be a public member function, and setting that flag to true in CalcGravityGeneralizedForces.

**Comment by amcastro-tri** [comment]
Our performance "fixes" to inverse dynamics broke this. Thanks for finding the bug and reporting.
See #12065
