### ISSUE TITLE
Should switch to require >= C++17

### ISSUE THREAD

**Issue by EricCousineau-TRI** [RobotLocomotion/drake#12077]
We gained official support via #11610, and have been using C++17 in Anzu, and it's been great.
We should eventually require C++17, esp. once we drop Xenial (#10606), 

Strawman date to require >= C++17: ~2019-11-15 ?~ 2019-10-25 (same as timeline issue)

\cc @jwnimmer-tri @jamiesnape

**Comment by jwnimmer-tri** [comment]
Yes, as soon as Xenial and High Sierra are gone, we should make `-std=c++17` our minimum (and our default).

**Comment by jamiesnape** [comment]
So I think you can probably just say that the last day we guarantee that a non-C++17 compiler will work is the day we remove Xenial. We don't need a different date per se.
