### ISSUE TITLE
missing py::arg in python binding for symbolic classes

### ISSUE THREAD

**Issue by soonho-tri** [RobotLocomotion/drake#12076]
I'm working on a PR based on @EricCousineau-TRI 's initial commit.

**Comment by EricCousineau-TRI** [comment]
FTR Slack convo: https://drakedevelopers.slack.com/archives/C3YB3EV5W/p1568643652003600

**Comment by jwnimmer-tri** [comment]
To be clear, the victory condition is that the functions bound in https://github.com/RobotLocomotion/drake/blob/master/bindings/pydrake/symbolic_py.cc use `py::arg("foo")` for any arguments where the name is at all meaningful.  For example, `Jacobian` has `f, vars` but they are not named.  In contrast, a named argument for something like `__add__` is not important.
