### ISSUE TITLE
Dense Articulated Real-Time Tracking

### ISSUE THREAD

**Issue by RussTedrake** [RobotLocomotion/drake#12091]
(aka DART)

https://link.springer.com/article/10.1007/s10514-015-9462-z

The Drake developers at TRI have an implementation of this algorithm in our internal repositories. In principle, we are happy to share it, but making it public takes time and we have not yet prioritized it. Please upvote it by adding a "thumbs up" reaction to this comment if you want us to know that you are keen.

**Comment by yenchenlin** [comment]
Hello @RussTedrake , thanks a lot for mentioning this! Any follow-up?

**Comment by RussTedrake** [comment]
Your interest quite clear (thanks @mariabauza)!  We started talking last week about exactly how to bring it in and are budgeting time for it in our project planning.  It's not going to wink instantly into existence, but do we aim to deliver.
