### ISSUE TITLE
Bus error / abort trap related to Eigen usage under Xcode 11

### ISSUE THREAD

**Issue by jamiesnape** [RobotLocomotion/drake#12107]
Appears to be in release configuration only. One such failure relates to this line: https://github.com/RobotLocomotion/drake/blob/7d672344d45d8badd94b5bc76a47b138532c7bba/math/continuous_algebraic_riccati_equation.cc#L24

```
)$ clang -v
Apple clang version 11.0.0 (clang-1100.0.33.8)
Target: x86_64-apple-darwin18.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

$ bazel test //math:continuous_algebraic_riccati_equation_test

FAIL: //math:continuous_algebraic_riccati_equation_test (see /private/var/tmp/_bazel_user/7c7ad393d9017d670ea6cd4ae3566d69/execroot/drake/bazel-out/darwin-py2-opt/testlogs/math/continuous_algebraic_riccati_equation_test/test.log)
INFO: From Testing //math:continuous_algebraic_riccati_equation_test:
==================== Test output for //math:continuous_algebraic_riccati_equation_test:
Using drake_cc_googletest_main.cc

[==========] Running 2 tests from 1 test case.
[----------] Global test environment set-up.
[----------] 2 tests from CARE
[ RUN      ] CARE.TestCare
external/bazel_tools/tools/test/test-setup.sh: line 310: 12507 Bus error: 10           "${TEST_PATH}" "$@" 2>&1
================================================================================
```

Apparently still an issue using Eigen 3.3.7, but may be fixed in `tip`. CC #11758.

Blocks macOS Catalina support. CC #11692.

**Comment by soonho-tri** [comment]
FYI:
 - I've checked that using '3.3.7' does *not* resolve the issue.
 - However, using the [`3.3` backport branch](https://bitbucket.org/eigen/eigen/branch/3.3) fixes the problem.  There are only four bug fixes between the release of 3.3.7 and the tip of 3.3 branch. It seems that http://eigen.tuxfamily.org/bz/show_bug.cgi?id=1741 is the culprit but I haven't checked it further.

**Comment by jamiesnape** [comment]
Appears to be literally the most recent commit that fixes  `//math:continuous_algebraic_riccati_equation_test`: https://bitbucket.org/eigen/eigen/commits/a5c3d12011a0a8f4b94a44a8b1c5d9139965c812

**Comment by EricCousineau-TRI** [comment]
\cc @scpeters (just in case this is related to Clang bugs encountered with releasing GMP for Homebrew...)

**Comment by jamiesnape** [comment]
I think it is related to optimization flags that we see it now, not a bug in the compiler.

**Comment by jamiesnape** [comment]
(Though I may have a different bug that potentially a libc++ issue. Still triaging that, though.)

**Comment by soonho-tri** [comment]
A small example (triggering segmentation fault):

```c++
// main.cc
#include <iostream>

#include "Eigen/Dense"

int main() {
  Eigen::MatrixXd B(2, 1), R(1, 1);
  B << 0, 1;
  R << 3;
  Eigen::LLT<Eigen::MatrixXd> R_cholesky(R);
  const auto result = R_cholesky.solve(B.transpose())(0, 0);  // Segfault
  return 0;
}
```

```bash
clang++ --std=c++11 -O3 -fstack-check -I <eigen_dir> main.cc
```

```
$ clang++ --version
Apple clang version 11.0.0 (clang-1100.0.33.8)
Target: x86_64-apple-darwin18.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```
