### ISSUE TITLE
Centroid-subdivision of triangles in ContactSurface in ConstructSurfaceMeshFromMeshHalfspaceIntersection and CalcZeroLevelSetInMeshDomain.

### ISSUE THREAD

**Issue by DamrongGuoy** [RobotLocomotion/drake#12113]
Related to PR #12112. The same problem could happen in ConstructSurfaceMeshFromMeshHalfspaceIntersection() (mesh_half_space_intersection.h) and CalcZeroLevelSetInMeshDomain() (contact_surface_from_level_set.h).
![image](https://user-images.githubusercontent.com/42557859/65803840-b30c7d80-e134-11e9-8db8-6a1137017eab.png)
 As the ContactSurface moves, some intersection triangles (triangle intersects halfspace, or levelset intersects tetrahedron) could change to intersection quadrilateral. Currently we subdivide the intersection quadrilateral into four triangles by adding its centroid, but we do not subdivide the intersection triangle.  As a result, we can have one triangle (from intersection triangle) abruptly change to four triangles (from intersection quadrilateral) as the ContactSurface moves.

A simple solution is to always subdivide an intersection n-gon into (n+1) triangles. As ContactSurface moves, we will have three triangles (from one intersection triangle) smoothly change to four triangles (from one intersection quadrilateral).
![image](https://user-images.githubusercontent.com/42557859/65803858-c9b2d480-e134-11e9-8233-8ffe1f350b29.png)

Since this centroid-subdivision of a polygon is common in the three codes for ContactSurface creation, we should factor out this function and make it shared by the three codes.

**Comment by DamrongGuoy** [comment]
CC: @SeanCurtis-TRI @sherm1 @edrumwri @amcastro-tri @ryanelandt 

@ryanelandt I confirm that even though Figure 5 in PFC paper shows 5-gon-to-4-gon transition, the same idea applies to 4-gon-to-3-gon transition too, right?
![image](https://user-images.githubusercontent.com/42557859/65806645-742ff500-e13f-11e9-91e3-aee25c57161a.png)

**Comment by SeanCurtis-TRI** [comment]
Closing this issue.

 - mesh-half space intersection was resolved by #12935
 - I've just created issue #14183 for removing the now unused contact surface from level set functionality.
