### ISSUE TITLE
Improve tetrahedral mesh connectivity for cylinders and boxes.

### ISSUE THREAD

**Issue by DamrongGuoy** [RobotLocomotion/drake#12128]
We should improve mesh connectivity to support Hydroelastic contact model. There are two problems that I found after visualizing the tetrahedral meshes.

1. MakeBoxVolumeMesh() creates a tetrahedral mesh of a box that has some tetrahedra with all vertices on the box boundary. These tetrahedra will define zero extent field in their volume.  This picture shows some of these tetrahedra.
![image](https://user-images.githubusercontent.com/42557859/65997386-23294500-e44e-11e9-8da1-92dadd1d1cf2.png)

2. MakeCylinderMesh() creates a tetrahedral mesh of a cylinder that has some tetrahedra spanning two layers. The picture below shows the problematic tetrahedra when we set the clipping plane through the second layer. All other tetrahedra in the first layer were hidden, but the problematic tetrahedra are shown because they span both the first and the second layer. The problematic tetrahedra come in groups of four tetrahedra forming octahedra. I believe when MakeCylinderMesh() share the same SplitOctahedron() code as  MakeSphereVolumeMesh(), we won't have this problem (this task is scheduled in Q4 CY2019). It is not clear how these problematic tetrahedra would affect the discretized extent field.
![image](https://user-images.githubusercontent.com/42557859/66002658-034b4e80-e459-11e9-8d31-9c11abaaeb3a.png)

CC: @sherm1 @SeanCurtis-TRI @amcastro-tri @joemasterjohn

**Comment by SeanCurtis-TRI** [comment]
Why is the cylinder mesh a problem?

**Comment by amcastro-tri** [comment]
Good question, I don't see a problem with the tetrahedra being highlighted above.
I wonder though if there are tetrahedra on the top/bottom rims that, as with the box, have all their nodes on the rim and thus a penetration extend field that is zero in the entirety of each tetrahedra. That'd definitely be a big problem.

**Comment by SeanCurtis-TRI** [comment]
@amcastro-tri I agree with you -- I likewise assumed that the cylinder corners would/could suffer from the same problem as box corners. Corners being the nuisance.

**Comment by DamrongGuoy** [comment]
PR #14216 is merged now. I'll enable the box mesh in hydroelastics. After that, I'll check the cylinder.
