### ISSUE TITLE
Eigen upgrade needed for DrakeJoint templates

### ISSUE THREAD

**Issue by psiorx** [RobotLocomotion/drake#1213]
The upcoming AutoDiffScalar/TrigPoly template conversion for DrakeJoint requires a bugfix that's in the new version of Eigen (3.2.5) .

https://bitbucket.org/eigen/eigen/commits/2ecad781e8a3/
http://eigen.tuxfamily.org/bz/show_bug.cgi?id=969

To upgrade to this version, the top few lines of the eigen Makefile need to be replaced with:

```
DL_LINK   = http://bitbucket.org/eigen/eigen/get/3.2.5.tar.bz2
DL_NAME   = 3.2.5.tar.bz2
TAR_NAME = 3.2.5.tar
UNZIP_DIR = eigen-eigen-bdd17ee3b1b3
```

**Comment by RussTedrake** [comment]
can you put in a pull request to the eigen pod?

**Comment by psiorx** [comment]
Will do.
