### ISSUE TITLE
Stop relying on incompatible_legacy_whole_archive

### ISSUE THREAD

**Issue by EricCousineau-TRI** [RobotLocomotion/drake#12137]
See PR #12124

Things break for shared libraries (at least our formulation)?

EDIT: Slack convo: https://drakedevelopers.slack.com/archives/C2PMBJVAN/p1569944216009500

\cc @jwnimmer-tri

**Comment by jwnimmer-tri** [comment]
Yes, we need `--incompatible_remove_legacy_whole_archive=false` as a stopgap, and then some `alwayslink = 1` repairs to pydrake later in order to undo that flag.

**Comment by jwnimmer-tri** [comment]
Where is the tracking issue to remove `--incompatible_remove_legacy_whole_archive=false` as a requirement in our rcfiles?  Users who consume us like `bazel_drake_external` currently have a pain point where they need to change _their own project_ in order to consume Drake.

**Comment by jwnimmer-tri** [comment]
@EricCousineau-TRI The other, more important build system transitions seem to be making good progress.  I'd like to see this issue fixed prior to the v0.12 release (so, merged to master in the next week or so).  If that's not possible, please re-assign this issue to me to work on it.

**Comment by EricCousineau-TRI** [comment]
Spoke with @jamiesnape and it'd be feasible, but not in time for 0.12 release. I'll reassign to you for the time being. Thanks!

**Comment by jwnimmer-tri** [comment]
For the record, trying to fix this has uncovered several challenges.  I don't think it will make the v0.12.0 release cycle.
