### ISSUE TITLE
 URDF Reference link on wiki is broken 

### ISSUE THREAD

**Issue by traversaro** [RobotLocomotion/drake#1214]
Clicking on "URDF Reference" link in the wiki points to 
http://drake002.csail.mit.edu/drake/urdf/drakeURDF.html . Trying to access this URL returns a 403 Forbidden error, at least on my network.

**Comment by RussTedrake** [comment]
Thanks for catching that.  I see the problem and will fix it.

**Comment by RussTedrake** [comment]
fixed.
