### ISSUE TITLE
Tests failing with numpy 1.17.1

### ISSUE THREAD

**Issue by BetsyMcPhail** [RobotLocomotion/drake#12151]
The mac unprovisioned builds updated numpy from 1.16.4 to 1.17.1. As a result, a few tests are failing.

Failing builds:
https://drake-cdash.csail.mit.edu/testDetails.php?test=34480669&build=1230814
https://drake-cdash.csail.mit.edu/testDetails.php?test=34480711&build=1230918

 * [test_linear_algebra ](https://github.com/RobotLocomotion/drake/blob/1970a3a31b1e2c4a4fe9f9d564050c0edd9e6045/bindings/pydrake/test/autodiffutils_test.py#L186) verifies that matmul is not supported for dtype=object (https://github.com/numpy/numpy/issues/11332).  As of numpy 17.0.1 , object arrays are supported in matmul (https://github.com/numpy/numpy/pull/13503).

* The other two tests are failing after a call to `ceil` with the error `TypeError: must be real number, not [...]`. Possibly related to [this ](https://numpy.org/devdocs/release/1.17.0-notes.html#floor-ceil-and-trunc-now-respect-builtin-magic-methods) numpy change.

**Comment by BetsyMcPhail** [comment]
\cc @EricCousineau-TRI

**Comment by EricCousineau-TRI** [comment]
Sorry for delayed direct response, but thanks! Filed the PR.
