### ISSUE TITLE
Document 'SimDiagramBuilder<T>::ConnectControllersAndVisualizer'

### ISSUE THREAD

**Issue by felixcra** [RobotLocomotion/drake#12167]
I think the documentation should mention the existence of this function and its purpose. I tried for hours to figure out how the plant gets the input signals given that in the file `kuka_simulation.cc` the output of the controller is not explicitly connected to the input of the plant.

I managed to figure it out by enabling debug flags, installing a SIGSEGV handler and causing a seg fault in `RigidBodyPlant<T>::model_instance_actuator_command_input_port`.

I hope I did not overlook something in the documentation, but I think its hard to anticipate this behaviour.

**Comment by jwnimmer-tri** [comment]
#13169 removed this code.
