### ISSUE TITLE
Questions regarding kuka_simulation, move_iiwa_ee, and kuka_plan_runner files

### ISSUE THREAD

**Issue by yuki95** [RobotLocomotion/drake#12199]
Hello, 

I am currently trying to implement a pure gravity compensation control on the kuka iiwa 7 using drake. I have implemented my own code into 2 files: simulation and controller. My simulation contains my visualizer which takes in commands and sends out status'. My controller takes in status' and outputs commands. To create this, I have looked at your code for kuka_simulation, move_iiwa_ee, and kuka_plan_runner. However, I have some questions regarding these 3 files.

1. In kuka_simulation, since I would like to switch to torque controller mode, I set the variable torque_control to true which replaces InverseDynamicsController with KukaTorqueController. This torque controller has gravity compensation. However, since the whole purpose of the simulation is create a copy of the physical kuka arm, does this mean that a torque controller already exists in the physical kuka arm?

If this is true, sending a torque value of 0 to all the joints should not let the arm fall down and maintain its position. But if the torque controller does not exist in the physical arm, I would have to change my simulation code by removing KukaTorqueController and placing it in my controller code instead.

2. In kuka_plan_runner,  lcm_.publish(kLcmCommandChannel, &iiwa_command); is used to send a command to the simulation. However, when I looked at the source code for iiwa_command, there was a comment saying
 /**
        * The reference joint positions. They should always be sent regardless of
        * whether the arm is in position control mode or torque control mode.
        */
       int32_t    num_joints;
       std::vector< double > joint_position;

Why would we need to send commanded positions of the arm when running on torque control mode? For example, if the arm was at the 0 position and if I were to send a position command of 0 to each joint while sending a torque of 1 to each joint, wouldn't this create contradiction? The arm would try to keep it's current position while trying to apply a torque.

**Comment by sammy-tri** [comment]
Posted a preliminary answer in stackoverflow at:  https://stackoverflow.com/questions/58400750/pure-gravity-compensation

In keeping with https://drake.mit.edu/getting_help.html we should continue the discussion there, since this is more of a general question than a bug or feature request.
