### ISSUE TITLE
procman sheriff: Needs porting to Python 3

### ISSUE THREAD

**Issue by EricCousineau-TRI** [RobotLocomotion/drake#12204]
We use procman sheriff (and its GUI) in Anzu, and we're planning to remove Python 2 support.

Per f2f with Jamie, this tool has Python 2-only libs (with no Python 3 ports), so it would involve more than just 2to3 updates. (Possibly [as is mentioned here](https://askubuntu.com/questions/697397/python3-is-not-supporting-gtk-module).)

\cc @jwnimmer-tri

**Comment by jwnimmer-tri** [comment]
Given that the tool's use of python2 is unrelated to our own source code (no cross-calling), and we use a pre-compiled version of procman, I'm not sure that we should care about this.  We're using 18.04 and it has python2 available.  I guess the question is when we switch Anzu to 20.04 and whether procman still works on that platform.  If it does, I don't see any need to mess with something that's not broken.

**Comment by EricCousineau-TRI** [comment]
Sounds good. We'll still look at the dependencies, estimate how long it'd take; if it's non trivial (more than 2 calendar days), then we punt.

**Comment by BetsyMcPhail** [comment]
First try of updating from GTK2 to GTK3: https://github.com/RobotLocomotion/libbot2/pull/20

**Comment by EricCousineau-TRI** [comment]
Here's an example PMD from the past:
https://github.com/RobotLocomotion/drake/blob/5c7d53403e2d976ac8a46c466ab1a5bb410d2107/examples/kuka_iiwa_arm/dev/box_rotation/iiwa_dual_box_rot.pmd
(Just for an example.)

**Comment by EricCousineau-TRI** [comment]
Will try this out with Anzu when it's ready.

Retrospective: stayed within 2 day's worth of work. Mainly just renaming.

**Comment by EricCousineau-TRI** [comment]
Just need to make the packages.

**Comment by EricCousineau-TRI** [comment]
Last item here is to fix monospace for output console, then should be good to try it out in Anzu.

**Comment by EricCousineau-TRI** [comment]
Sorry for not posting earlier, but I had tried this out on our hardware setup on 2020-02-28. Worked fine!

@jamiesnape Can we move forward on getting these packages up?

**Comment by jamiesnape** [comment]
Version 0.0.1.20200422-1 is available on drake-apt.csail.mit.edu/bionic bionic main.
