### ISSUE TITLE
ci: Support Mac Catalina

### ISSUE THREAD

**Issue by EricCousineau-TRI** [RobotLocomotion/drake#12288]
Remaining item here is to wait for last two formulae to be built + published on Homebrew.

(Part of campaign originally in #10606)

**Comment by EricCousineau-TRI** [comment]
Aiming to have this done within the next 2 weeks (hopefully Homebrew formulae update, if not, then using an alternative tap)

**Comment by EricCousineau-TRI** [comment]
Updated comment from #11692:

> Note that we are waiting on clp, ~diffstat~, doxygen, and ~llvm@6~ dependencies to be built for Catalina for unprovisioned builds to be switched on.

**Comment by jamiesnape** [comment]
Just missing `doxygen` now.

**Comment by EricCousineau-TRI** [comment]
Per f2f, Jamie may try to build it from source, or just download a custom bottle.

**Comment by jamiesnape** [comment]
Done.
