### ISSUE TITLE
pydrake.math.RotationMatrix is missing binding for ToAngleAxis

### ISSUE THREAD

**Issue by RussTedrake** [RobotLocomotion/drake#12307]
Students in the MIT manipulation class just ran into this missing binding...

**Comment by sherm1** [comment]
I don't suppose one of those students would like to contribute to a great open source project? :)

**Comment by mitiguy** [comment]
PR# 12313 was opened to address missing Python binding for ToAngleAxis.

**Comment by mitiguy** [comment]
@RussTedrake 
This issue is closed as PR #12313 has merged.
