### ISSUE TITLE
Problems with install_prereqs.sh

### ISSUE THREAD

**Issue by rdeits** [RobotLocomotion/drake#1230]
I've found a couple of problems with install_prereqs.sh:

1. Since it invokes `apt-get install`, it must be run as root (on ubuntu). But it also calls `make download-all`, which results in all of the external source folders being owned by root (which is bad).
1. Because it calls the Makefile, it invokes cmake and ends up setting up some initial Cmake cache variables. That's a problem because it always sets the BUILD_TYPE to "Release", which makes a debug build impossible.

**Comment by rdeits** [comment]
Here are some options:

1. don't call `make download-all` inside `install_prereqs.sh`, just tell users to do so beforehand. We can also simplify the install_prereqs logic to just look inside the `drake` and `externals` folders. 
2. Change `install_prereqs.sh` to be run as user but to call `sudo apt-get install` when appropriate. But figuring out whether `sudo` is needed for a particular system will be very tricky. 

I've already implemented option 1 in my testing branch.

**Comment by rdeits** [comment]
Option 2 also requires that we correctly pass the build type through every time we use the makefile.

**Comment by RussTedrake** [comment]
I was thinking about this -- it's the reason that the logic is not inside cmake in the first place.  But slipped in calling make download-all.  My bad.  Option 1 seems reasonable.

**Comment by rdeits** [comment]
Ok, sounds good. This will be fixed in #1231
