### ISSUE TITLE
Use vtkCapsuleSource directly from VTK

### ISSUE THREAD

**Issue by tehbelinda** [RobotLocomotion/drake#12325]
Use vtkCapsuleSource once it's been pulled upstream into VTK itself, see https://gitlab.kitware.com/vtk/vtk/issues/17720
Then we can undo the third party changes in #12305 

Relates to #10153

**Comment by sherm1** [comment]
Assigning to @jamiesnape for now.

**Comment by jamiesnape** [comment]
Despite low priority, probably need to do this sooner rather than later to make it into VTK 9 (it is not a difficult or time consuming task, however).

**Comment by EricCousineau-TRI** [comment]
Jamie's aiming to submit PR by EOD tomorrow.

**Comment by EricCousineau-TRI** [comment]
VTK PR ready; Jamie to add link here.

**Comment by jamiesnape** [comment]
https://gitlab.kitware.com/vtk/vtk/merge_requests/6290

**Comment by jamiesnape** [comment]
Merged into VTK `master`: https://gitlab.kitware.com/vtk/vtk/commit/e464aa29a09c68aa17891861e309a4df2a7969cb

**Comment by SeanCurtis-TRI** [comment]
What's the plan/time frame for the binaries Drake depends on to get updated?

**Comment by jamiesnape** [comment]
It's high on my TODO list, so this week.

**Comment by EricCousineau-TRI** [comment]
Just waiting to update Drake. May wait for VTK 9.

**Comment by jamiesnape** [comment]
FYI VTK 9.0 RC1 is out.
