### ISSUE TITLE
[Question] Currently we support ubuntu16.04?

### ISSUE THREAD

**Issue by xdwgood** [RobotLocomotion/drake#12360]
Currently we support ubuntu16.04?
Any answer is greatly appreciated, I am a person who is ready to start learning "drake"

**Comment by sherm1** [comment]
No, just 18.04.

**Comment by jwnimmer-tri** [comment]
See https://drake.mit.edu/developers.html#supported-configurations and https://github.com/RobotLocomotion/drake/releases/tag/v0.12.0 and https://github.com/RobotLocomotion/drake-external-examples/tree/master/drake_cmake_installed for additional information.
