### ISSUE TITLE
Transition to starlark versions of native build rules

### ISSUE THREAD

**Issue by jamiesnape** [RobotLocomotion/drake#12376]
Using https://github.com/bazelbuild/bazel-federation may be the best bet. Transitioning to `rules_python` is the immediate priority since the native build rules are already deprecated.

CC: @EricCousineau-TRI @jwnimmer-tri

**Comment by jamiesnape** [comment]
Probably should fix the `rules_python` in tandem with #11380.

**Comment by jwnimmer-tri** [comment]
We have rules_python already converted.  We still have to do rules_cc and rules_java.

**Comment by jwnimmer-tri** [comment]
The separate starlark rules_cc is far from complete, and is generally a regression from the native ones.  We'll wait to switch until Bazel deprecates the native ones.

For rules_java, we use it so little that there's no real need to switch anything unless Bazel deprecates the built-in ones.
