### ISSUE TITLE
Gurobi license on drake006 expired

### ISSUE THREAD

**Issue by rdeits** [RobotLocomotion/drake#1238]
Attempting to use gurobi on drake006 gives:

```
>> gurobi(struct('A',sparse(1), 'obj', 1', 'rhs', 1, 'sense', '='))
Error using gurobi
Gurobi error 10009: License expired 2015-04-01
Please consult the Gurobi Quick Start Guide for details on setting up a license.
```

But I'm not sure how that's possible unless we've been skipping all tests that use gurobi since April?

**Comment by psiorx** [comment]
Which user are you logged into drake006 as?  It uses a license that corresponds to your gurobi user I believe.

**Comment by rdeits** [comment]
Ohhh. That makes sense. I was logged in as drc. Good catch :)
