### ISSUE TITLE
mac: Ensure that we match clang-format with Ubuntu when Homebrew drops llvm@6?

### ISSUE THREAD

**Issue by EricCousineau-TRI** [RobotLocomotion/drake#12382]
Per f2f with @jamiesnape, we have `clang-format-8` on `bionic-updates`, so we could upgrade both.

**Comment by EricCousineau-TRI** [comment]
May have gotten bitten by this in this job: https://drake-cdash.csail.mit.edu/viewTest.php?onlyfailed&buildid=1257066
For PR #12505

**Comment by jamiesnape** [comment]
No, this issue would be seen an error on a (most likely) unprovisioned build saying that `clang-format` could not be found.

**Comment by soonho-tri** [comment]
I wonder if https://github.com/grailbio/bazel-toolchain can be a solution to this problem.

> The LLVM toolchain also provides several tools like clang-format. You can depend on these tools directly in the bin directory of the toolchain. For example, @llvm_toolchain//:bin/clang-format is a valid and visible target.

**Comment by jwnimmer-tri** [comment]
For Ubuntu 20.04, I'm going to recommend that we upgrade to clang-format-9, so that we have:
- an identical version on both 18.04 and 20.04, and
- a version that does not depend on python2 (clang-format-6.0 depends on python2)

**Comment by jwnimmer-tri** [comment]
We are using clang-format 9 on master now, both on Ubuntu and macOS.  It seems to me like that should suit us for a while.
