### ISSUE TITLE
How to handle the format returned from the optimizer solver, like <Expression "3">?

### ISSUE THREAD

**Issue by vinbo** [RobotLocomotion/drake#12398]
The nonlinear programming solver returned this format:
initial state: [<Expression "-2"> <Expression "0.10000000000000001">
 <Expression "-0.10000000000000001"> <Expression "3">]

although I was expecting float.  Its type is <type 'numpy.ndarray'>, which seems right.
How do I convert this format to float, please? Thanks
---------------------------update line-----------------------------
The code (under jupyter notebook) is pasted below, when I tried to plot the data, it gives the type error
TypeError: float() argument must be a string or a number

`import numpy as np
from pydrake.all import MathematicalProgram, Solve, IpoptSolver, SolverOptions

import matplotlib.animation as animation
from matplotlib.patches import Circle
import matplotlib.pyplot as plt

class OrbitalTransferRocket():
    
    def __init__(self):
        self.G  = 9.8  # gravitational constant
        self.M1 = 0.4  # mass of first planet
        self.M2 = 0.1  # mass of second lanet
        self.world_1_position = np.asarray([-2.5,-0.1])
        self.world_1_color    = "darkgreen"   
        self.world_2_position = np.asarray([2.5,0.1])
        self.world_2_color    = "orangered"   
        
    def rocket_dynamics(self, state, u):

        rocket_position = state[0:2]
        derivs = np.zeros_like(state)
        derivs[0:2] = state[2:4]

        # these local copies of variables make the equations below
        # easier to look at
        G = self.G; M1 = self.M1; M2 = self.M2;
        world_1_position = self.world_1_position; world_2_position = self.world_2_position;

        derivs[2]  = G * M1 * (world_1_position[0] - rocket_position[0]) / self.two_norm(world_1_position - rocket_position)**3
        derivs[2] += G * M2 * (world_2_position[0] - rocket_position[0]) / self.two_norm(world_2_position - rocket_position)**3
        derivs[2] += u[0]
        derivs[3]  = G * M1 * (world_1_position[1] - rocket_position[1]) / self.two_norm(world_1_position - rocket_position)**3
        derivs[3] += G * M2 * (world_2_position[1] - rocket_position[1]) / self.two_norm(world_2_position - rocket_position)**3
        derivs[3] += u[1]
        
        return derivs

    def two_norm(self, x):
        
        slack = .001
        return np.sqrt(((x)**2).sum() + slack)

    def simulate_states_over_time(self, state_initial, time_array, input_trajectory):

        states_over_time = np.asarray([state_initial])
        for i in range(1,len(time_array)):
            time_step = time_array[i] - time_array[i-1]
            state_next = states_over_time[-1,:] + time_step*self.rocket_dynamics(states_over_time[-1,:], input_trajectory[i-1,:])
            states_over_time = np.vstack((states_over_time, state_next))
        return states_over_time
        
    def plot_trajectory(self, trajectory):
        
        input_trajectory = np.zeros((trajectory.shape[0],2))
        self.plot_trajectory_with_boosters(trajectory, input_trajectory)

    def plot_trajectory_with_boosters(self, trajectory, input_trajectory):

        rocket_position_x = trajectory[:,0]
        rocket_position_y = trajectory[:,1]
        fig, axes = plt.subplots(nrows=1,ncols=1)
        axes.plot(rocket_position_x, rocket_position_y)
        circ = Circle(self.world_1_position, radius=0.2, facecolor=self.world_1_color, edgecolor='black', fill=True ,linewidth = 1.0, linestyle='solid')
        axes.add_patch(circ)
        circ = Circle(self.world_2_position, radius=0.1, facecolor=self.world_2_color, edgecolor='black', fill=True ,linewidth = 1.0, linestyle='solid')
        axes.add_patch(circ)
        axes.axis('equal')

        ## if we have an input trajectory, plot it
        if len(input_trajectory.nonzero()[0]):
            # the quiver plot works best with not too many arrows
            max_desired_arrows = 40
            num_time_steps = input_trajectory.shape[0]

            if num_time_steps < max_desired_arrows:
                downsample_rate = 1 
            else: 
                downsample_rate = num_time_steps / max_desired_arrows

            rocket_position_x = rocket_position_x[:-1] # don't need the last state, no control input for it
            rocket_position_y = rocket_position_y[:-1]
            rocket_booster_x = input_trajectory[::downsample_rate,0]
            rocket_booster_y = input_trajectory[::downsample_rate,1]
            Q = plt.quiver(rocket_position_x[::downsample_rate], rocket_position_y[::downsample_rate], \
                rocket_booster_x, rocket_booster_y, units='width', color="red")

        plt.show()
    
    def compute_trajectory_to_other_world(self, state_initial, minimum_time, maximum_time):
        '''
        Your mission is to implement this function.

        A successful implementation of this function will compute a dynamically feasible trajectory
        which satisfies these criteria:
            - Efficiently conserve fuel
            - Reach "orbit" of the far right world
            - Approximately obey the dynamic constraints
            - Begin at the state_initial provided
            - Take no more than maximum_time, no less than minimum_time

        The above are defined more precisely in the provided notebook.

        Please note there are three return args.

        :param: state_initial: :param state_initial: numpy array of length 4, see rocket_dynamics for documentation
        :param: minimum_time: float, minimum time allowed for trajectory
        :param: maximum_time: float, maximum time allowed for trajectory

        :return: three return args separated by commas:

            trajectory, input_trajectory, time_array

            trajectory: a 2d array with N rows, and 4 columns. See simulate_states_over_time for more documentation.
            input_trajectory: a 2d array with N-1 row, and 2 columns. See simulate_states_over_time for more documentation.
            time_array: an array with N rows. 
        '''
        ###################################
        mp = MathematicalProgram()

        N = 50
        time_total=0.5*(minimum_time+maximum_time)
        dt=time_total/N
        
        k = 0
        u = mp.NewContinuousVariables(2, "u_%d" % k) # no need to name each one grammaly, just to lable
        u_over_time = u
        states_over_time = np.asarray([state_initial])
        for k in range(1,N):
            u = mp.NewContinuousVariables(2, "u_%d" % k)
            state =mp.NewContinuousVariables(4,"state_%d" % k)
            u_over_time = np.vstack((u_over_time, u))
            states_over_time = np.vstack((states_over_time,state))
        state =mp.NewContinuousVariables(4)
        states_over_time = np.vstack((states_over_time,state)) # the N+1 th state is need for given plot function
        print "Number of decision vars", mp.num_vars()
        print "shape of states_over_time:",states_over_time.shape
        
        # constraint of dynamics
        for i in range(N): 
            state_next = states_over_time[i,:]  + dt * self.rocket_dynamics(states_over_time[i,:],u_over_time[i,:])
            mp.AddConstraint(states_over_time[i+1,0]==state_next[0])
            mp.AddConstraint(states_over_time[i+1,1]==state_next[1])
            mp.AddConstraint(states_over_time[i+1,2]==state_next[2])
            mp.AddConstraint(states_over_time[i+1,3]==state_next[3])
        # constraint of destination
        for i in range(35,N):
            rocket_position = states_over_time[i,0:2]
            d2=self.two_norm(rocket_position-self.world_2_position)
            mp.AddConstraint(d2>=0.5)
            mp.AddConstraint(d2<=5./3)
        
        mp.AddQuadraticCost(1 * u_over_time[:,0].dot(u_over_time[:,0]))
        mp.AddQuadraticCost(1 * u_over_time[:,1].dot(u_over_time[:,1]))
            
        result = Solve(mp)
        u_over_time = result.GetSolution(u_over_time)
        states_over_time= result.GetSolution(states_over_time)
        ##########################
        trajectory=states_over_time
        input_trajectory=u_over_time
        time_used = time_total
        time_array = np.arange(0.0, time_used, time_used/(N)) # np.arange(0.0, time_used, time_used/(N+1))
        return trajectory, input_trajectory, time_array

%reload_ext autoreload
%autoreload 2
%matplotlib inline

rocket = OrbitalTransferRocket()

x0 = np.array([-2., 0.1, -0.1, 3])
minimum_time = 5.
maximum_time = 15.
traj, u_traj, time_array = rocket.compute_trajectory_to_other_world(x0, minimum_time, maximum_time)
print type(traj),type(u_traj)
print traj.shape, u_traj.shape
print 'initial state=',traj[0,:]
print 'final state=', traj[50,:]
print 'input=',u_traj[0,:]
rocket.plot_trajectory_with_boosters(traj, u_traj)`

**Comment by hongkai-dai** [comment]
Could you paste your code here so that we can reproduce your output?

**Comment by vinbo** [comment]
> 
> 
> Could you paste your code here so that we can reproduce your output?

Thank you. I pasted it in the main post.

**Comment by hongkai-dai** [comment]
I can't run your code, as I only have pydrake compiled in python3. But I think the problem is that `initial_state` is a numpy array of float, it is not a numpy array of symbolic variables or symbolic expressions. So when you call `result.GetSolution(states_over_time)`, it first tries to convert the numpy array of `[-2., 0.1, -0.1, 3]` to a numpy array of symbolic expressions (with constant expressions).

The solution would be to not to call `result.GetSolution(states_over_time)`, but `result.GetSolution(states_over_time[4:])`. You already know the value of initial state as `x0`, so you don't need to get its value from `result`.

**Comment by vinbo** [comment]
> 
> 
> I can't run your code, as I only have pydrake compiled in python3. But I think the problem is that `initial_state` is a numpy array of float, it is not a numpy array of symbolic variables or symbolic expressions. So when you call `result.GetSolution(states_over_time)`, it first tries to convert the numpy array of `[-2., 0.1, -0.1, 3]` to a numpy array of symbolic expressions (with constant expressions).
> 
> The solution would be to not to call `result.GetSolution(states_over_time)`, but `result.GetSolution(states_over_time[4:])`. You already know the value of initial state as `x0`, so you don't need to get its value from `result`.

Thanks. It works. But not result.GetSolution(states_over_time[4:]) , but result.GetSolution(states_over_time[1:]).
And I have a serious suggestion: Why not write the document more concrete and friendly? It is really hard to read. Take this post as example, even you were making mistakes about wether the index should be [4:] or [1:], because the document does not say anything about it. More examples are needed in the documents.

**Comment by hongkai-dai** [comment]
> Why not write the document more concrete and friendly

Could you point out which function needs better documentation?

We do have a very basic tutorial on Mathematical Program https://nbviewer.jupyter.org/github/RobotLocomotion/drake/blob/master/tutorials/mathematical_program.ipynb. We will add more tutorials in the future.

**Comment by vinbo** [comment]
> Could you point out which function needs better documentation?

The tutorial link is good, but the document https://drake.mit.edu/pydrake/pydrake.solvers.mathematicalprogram.html, or all the documents down here are hard to read

**Comment by vinbo** [comment]
>
> Could you point out which function needs better documentation?
> 
here is another example of the document being too concise to read
https://github.com/RobotLocomotion/drake/issues/12410

**Comment by jwnimmer-tri** [comment]
It looks like this has reached a conclusion.  @hongkai-dai If there is something still to do here, please re-open and clarify what is the acute bug report.

**Comment by vinbo** [comment]
another trick to handle the problem is here:
https://stackoverflow.com/questions/59335527/runtimeerror-you-should-not-call-bool-nonzero-on-formula/59433250#59433250
