### ISSUE TITLE
Update Gurobi support to 9.0

### ISSUE THREAD

**Issue by hongkai-dai** [RobotLocomotion/drake#12419]
A newer version of Gurobi 9.0 is recently released https://www.gurobi.com/products/gurobi-optimizer/whats-new-current-release/. It says the speed is improved by 20% for MIQP, which could be important for us.

It also adds support to non-convex quadratic constraints (We could rewrite the global IK paper without having to relax the bilinear term with McCormick envelope trick).

**Comment by jwnimmer-tri** [comment]
Resolved by #13049.
