### ISSUE TITLE
Support shape permutations across scalar types in ComputeSignedDistancePairwiseClosestPoints

### ISSUE THREAD

**Issue by tehbelinda** [RobotLocomotion/drake#12468]
Following up from #10153, there is still more work required for full proximity engine support. Currently only certain shape permutations are supported and only with certain scalars. Even for doubles, there are varying levels of precision when falling back to using FCL. In `distance_to_shape_callback.h`, the current supported configurations are:

|                       | Sphere     | Box                         | Cylinder               | Halfspace              | Capsule              | Ellipsoid              | Convex              | Mesh              |
| ------------------ | ------------- | ------------------------- | ---------------------- |---------------------- |---------------------- |---------------------- |---------------------- |---------------------- |
| **Sphere**    | double<br>Autodiff<br>1e-14 | double<br>Autodiff<br>1e-14 | double<br>1e-14 | double<br>Autodiff<br>1e-14 | double<br>Autodiff<br>1e-14   | double (FCL fallback)   | double (FCL fallback)   | :x:   |
| **Box**         | double<br>1e-14      | double (FCL fallback)       | double (FCL fallback) | :x:                       | double (FCL fallback) | double (FCL fallback)   | double (FCL fallback)   | :x:   |
| **Cylinder**   | double<br>1e-14   | double (FCL fallback)       | double (FCL fallback) | :x:                       | double (FCL fallback) | double (FCL fallback)   | double (FCL fallback)   | :x:   |
| **Halfspace** | double<br>1e-14 | :x:              | :x:        | :x:                       | :x:                       | :x:                    | :x:                       | :x:   |
| **Capsule**   | double<br>Autodiff<br>1e-14  | double (FCL fallback)       | double (FCL fallback) | :x:                       | double (FCL fallback)  | double (FCL fallback)   | double (FCL fallback)   | :x:   |
| **Ellipsoid**   | double (FCL fallback)  | double (FCL fallback)       | double (FCL fallback) | :x:                       | double (FCL fallback)  | double (FCL fallback)   | double (FCL fallback)   | :x:   |
| **Convex**    | double (FCL fallback)  | double (FCL fallback)       | double (FCL fallback) | :x:                       | double (FCL fallback)  | double (FCL fallback)   | double (FCL fallback)   | :x:   |
| **Mesh**        | :x: | :x: | :x: | :x: | :x: | :x: | :x: | :x: |

We should fully support the shapes we care about, i.e. shapes with spheres, by providing our own implementation for sphere-XXX in `distance_to_point_callback.h`. Otherwise we should provide fallbacks and update the documentation to reflect the latest state.

cc @SeanCurtis-TRI @DamrongGuoy

**Comment by SeanCurtis-TRI** [comment]
Ideally, we'd like to take this one step further. Let's include the level of precision actually provided in the table. It should certainly be included when this table ends up in the documentation.

**Comment by DamrongGuoy** [comment]
This issue #12468 is similar to #10907.  May I add the content of this issue into #10907 and close this issue?  Or we prefer to keep them apart and fix one issue at a time?

**Comment by SeanCurtis-TRI** [comment]
I like rolling them in together.  Good catch!

**Comment by DamrongGuoy** [comment]
Thank you.  I close this issue in favor of #10907.
