### ISSUE TITLE
Can't see build output of drake003

### ISSUE THREAD

**Issue by tkoolen** [RobotLocomotion/drake#1248]
When I click on the build 'Details' link for drake003 in a pull request, the build output doesn't show. After a minute or so I get a connection timeout. Tested in Chrome and Firefox on my machine, and also on @psiorx's machine.

See e.g. this pull request:
https://github.com/RobotLocomotion/drake/pull/1191
where the Details button links to here:
http://drake003.csail.mit.edu/drake/pull-tkoolen-tk-autodiff-scalar-into-RobotLocomotion-master
I can ssh into drake003 just fine.

**Comment by rdeits** [comment]
I had the same issue this morning

**Comment by RussTedrake** [comment]
I've rebooted it.  It's back up

**Comment by tkoolen** [comment]
Great, thanks!
