### ISSUE TITLE
URDF parser error message is not actionable

### ISSUE THREAD

**Issue by tehbelinda** [RobotLocomotion/drake#12506]
Current error messages from loading URDFs, e.g. if physically invalid, are not actionable. This makes it difficult for users to figure out what's going on in the .urdf file. For example:

```
terminate called after throwing an instance of 'std::runtime_error'
  what():  The resulting spatial inertia is not physically valid. See SpatialInertia::IsPhysicallyValid()
Aborted (core dumped)
```

I found this error when trying to load the HSR mesh from https://github.com/ToyotaResearchInstitute/hsr_meshes. Here's the example commit acd55c16dbe2c46e2d7e357a19abf9dee20ce965

**Comment by amcastro-tri** [comment]
Relates to #11109.

**Comment by jwnimmer-tri** [comment]
Relates to #16058.

**Comment by rpoyner-tri** [comment]
I am unable to tease out any useful/reachable information from this issue that is not better expressed in #16058. Closing.
