### ISSUE TITLE
duplicate methods: thirdParty/polytope/vert2lcon and util/poly2lincon 

### ISSUE THREAD

**Issue by RussTedrake** [RobotLocomotion/drake#1253]
the polytope version has lcon2vert, but util version for the other direction doesn't seem to exist.  
in general, we badly need to clean up and organize the util directory.

**Comment by rdeits** [comment]
I wrote poly2lincon long before we'd brought in the Polytopes library (and I didn't implement the other direction because it's much more complicated). 

We can probably replace poly2lincon with a call to vert2lincon, but I've found that toolbox in general to be extremely slow.

**Comment by jwnimmer-tri** [comment]
Relates #6369.

**Comment by jamiesnape** [comment]
All these files are gone now so there is no longer any duplication.
