### ISSUE TITLE
Additional checks that framework is compatible with Context, State, Parameters, etc.

### ISSUE THREAD

**Issue by edrumwri** [RobotLocomotion/drake#12560]
As came up in #12551, some work still remains in the systems framework to check that:

1. System functions that take in a State should check to see whether the State came from a Context created by that System. See, for example, System::CalcUnrestrictedUpdate(.)

2. Input and output port evaluation methods need to check that the passed in Context was created by a System that declared the port.

3. Cache entry evaluation methods need to check that the passed in Context was created by a System that declared the cache entry.

**Comment by jwnimmer-tri** [comment]
Also:

4. SystemConstraint calculations.

**Comment by edrumwri** [comment]
6. System::FixInputPortsFrom(.)

**Comment by jwnimmer-tri** [comment]
Step 1 will be to move `geometry::Identifier<Tag>` to `//common` and use it instead of a bare `uint64_t`, so that we can decorate even more Context-related types with it without spreading the magic POD disease further.

**Comment by jwnimmer-tri** [comment]
WIP for this issue will be at https://github.com/jwnimmer-tri/drake/tree/system_id_more

**Comment by jwnimmer-tri** [comment]
Aside (probably for another issue in the future) -- I just made the mistake of passing the diagram context (not plant context) into `MultibodyPlant::SetFreeBodyPoseInWorldFrame`.  Plant methods like that should also add the context-check.

**Comment by jwnimmer-tri** [comment]
\CC @rpoyner-tri FYI this is one of the more important usability defects in Drake.  If there's a triage on the way to try to get usability improvements, anyone is welcome to steal this / co-work this with me.

**Comment by dmcconachie-tri** [comment]
I believe I just stumbled on this in:

7. Frame::CalcPoseInWorld

**Comment by jwnimmer-tri** [comment]
My current checklist to help measure what's done or not:
- [x] All public methods of SystemBase
- [x] All public methods of System, except for:
  - [ ] EvalTimeDerivatives
  - [ ] CheckValidOutput
- [x] All public methods of LeafSystem
- [x] All public methods of Diagram, except for:
  - [ ] DoCalcTimeDerivatives
  - [ ] DoCalcImplicitTimeDerivativesResidual
  - [ ] GetSubsystemDerivatives
  - [ ] GetSubsystemDiscreteValues
  - [ ] GetSubsystemCompositeEventCollection
  - [ ] GetMutableSubsystemCompositeEventCollection
  - [x] GetMutableSubsystemState(Context&)
  - [ ] GetMutableSubsystemState(State&)
  - [ ] GetSubsystemState

**Comment by rpoyner-tri** [comment]
Attempting to grok the rather terse checklist above. If I understand things adequately, it looks like the missing SystemOutput checking would involve adding a system_id to the SystemOutput object and implementing a check on it, similar (or identical) to ValidateChildOfContext(). Is that the ask?

**Comment by jwnimmer-tri** [comment]
Yup -- ideally, it's literally `ValidateChildOfContext` aka `ValidateCreatedForThisSystem`.  At the same time, we should also stop using (and deprecate) the less-stringent validation method `CheckValidOutput` that is currently used.

In other words, we want this patch to compile and pass existing tests:

```patch
--- a/systems/framework/system.cc
+++ b/systems/framework/system.cc
@@ -439,7 +439,7 @@ void System<T>::CalcOutput(const Context<T>& context,
                            SystemOutput<T>* outputs) const {
   DRAKE_DEMAND(outputs != nullptr);
   ValidateContext(context);
-  DRAKE_ASSERT_VOID(CheckValidOutput(outputs));
+  ValidateCreatedForThisSystem(outputs);
   for (OutputPortIndex i(0); i < num_output_ports(); ++i) {
     // TODO(sherm1) Would be better to use Eval() here but we don't have
     // a generic abstract assignment capability that would allow us to
```

**Comment by rpoyner-tri** [comment]
Follow-up question: should CheckValidOutput just go away altogether?

**Comment by rpoyner-tri** [comment]
Fun subproblems in the remaining checklist items:

* SystemConstraint<=>System near-dependency cycle
* The {Discrete,Continuous}State objects appear to have a more interesting life cycle than, say, SystemOutput. Will need to trace things through carefully.

**Comment by jwnimmer-tri** [comment]
> SystemConstraint<=>System near-dependency cycle

Yeah.  Upon first look, the `SystemConstraint` will need its own error-reporting method, since it can't reuse the `SystemBase` one (nor the `System::ValidateCreatedFor...`, etc.).  However, since it has its own `description` anyway, reporting that on its own seems plausibly good enough.

**Comment by rpoyner-tri** [comment]
I updated the checklist above with a few more System methods that are now checkable, thanks to more helper objects having labels.

A few helper types are not yet labeled: `Parameters`, `AbstractValues`, and perhaps some I haven't noticed yet.

**Comment by rpoyner-tri** [comment]
Updated the checklist. Looks pretty done to me.
