### ISSUE TITLE
Documentation needed to describe new restriction on use of Contexts

### ISSUE THREAD

**Issue by edrumwri** [RobotLocomotion/drake#12570]
With the landing of #12551, a Context can only be used with the System that created it. Documentation is necessary to explain this restriction and how to work around it.

**Comment by rpoyner-tri** [comment]
#15098 added a doxygen essay [@system_compatibility](https://github.com/RobotLocomotion/drake/blob/master/systems/framework/system_compatibility_doxygen.h). Is that existing doc adequate to the need?

**Comment by rpoyner-tri** [comment]
Having re-read the doc, I'm satisfied this is done. @edrumwri feel free to re-open if you see an unmet need.
