### ISSUE TITLE
Remove deprecated Jacobian methods 2020-02-01

### ISSUE THREAD

**Issue by mitiguy** [RobotLocomotion/drake#12600]
Remove deprecated method  CalcFrameGeometricJacobianExpressedInWorld()
and instead use CalcJacobianSpatialVelocity().

This issue follows deprecation of other Jacobian methods from issue #12154 and PR#12171.

**Comment by sherm1** [comment]
@mitiguy should this be closed now?

**Comment by mitiguy** [comment]
@sherm1 This issue is now closed.
I searched the code base and it seems that GeometricJacobian and AnalyticalJacobian now only occupy a poor spot in the old deprecated RigidBodyTree attic.
