### ISSUE TITLE
Diagrams don't report state counts correctly

### ISSUE THREAD

**Issue by sherm1** [RobotLocomotion/drake#12616]
When a Diagram is asked size information about its state it should sum up the size information of its constituent Systems recursively. Diagrams do this correctly for `num_continuous_states()`, but fail for the other counts:  
```
num_discrete_state_groups()
num_abstract_states() 
num_numeric_parameter_groups() 
num_abstract_parameters()
```
all of which are implemented in SystemBase and thus report only locally-allocated variables for the Diagram (of which there are none currently).

Also, `num_constraints()` is implemented in System and also looks suspicious.

cc @RussTedrake

**Comment by jwnimmer-tri** [comment]
> ... num_constraints() is implemented in System and also looks suspicious.

`Diagram::Initialize` copies constraints from the subsystems into the `Diagram` itself, so I think it should be fine.

**Comment by RussTedrake** [comment]
N.B., this was initially caught with the following test which fails if placed in diagram_test.cc (around line 1951).  

```
GTEST_TEST(DiscreteStateDiagramTest, NumDiscreteStateGroups) {
  DiagramBuilder<double> builder;
  builder.template AddSystem<SystemWithDiscreteState>(1, 2.);
  const auto diagram = builder.Build();
  const auto context = diagram->CreateDefaultContext();
  EXPECT_EQ(diagram->num_discrete_state_groups(),
      context->num_discrete_state_groups());
}
```

**Comment by RussTedrake** [comment]
Please resolve the TODO(#12616) in system.h when this is resolved.
