### ISSUE TITLE
Overriding `DoCalcNextUpdateTime()` might have no effect.

### ISSUE THREAD

**Issue by amcastro-tri** [RobotLocomotion/drake#12620]
From f2f with @sherm1, if we override `DoCalcNextUpdateTime()` to return a non-infinity value of `next_update_time`, our simulator should guarantee that time goes exactly through `next_update_time` whether new events were scheduled or not by `DoCalcNextUpdateTime()`. It seems that most of our overrides in Drake do schedule an event (see `LcmLogPlaybackSystem`, 
`LcmSubscriberSystem`).

However `Simulator` uses this time value only if something was scheduled, see [here](https://github.com/RobotLocomotion/drake/blob/cdc37f451e2c97e32fb6670f96ebe0daae70a67a/systems/analysis/simulator.h#L1154). That value of time, in `next_timed_event_time_`, gets also passed to the integrators [here](https://github.com/RobotLocomotion/drake/blob/cdc37f451e2c97e32fb6670f96ebe0daae70a67a/systems/analysis/simulator.h#L1163), however [it gets never used](https://github.com/RobotLocomotion/drake/blob/cdc37f451e2c97e32fb6670f96ebe0daae70a67a/systems/analysis/simulator.h#L1452).

As a case where no new events are scheduled, we have `LcmInterfaceSystem::DoCalcNextUpdateTime()`, which might indicate a bug.

**Comment by sherm1** [comment]
This came up in real life recently, see #14644. Bumping priority to high.

**Comment by sherm1** [comment]
FYI @edrumwri for advice

**Comment by sherm1** [comment]
I'm working on a fix. Making a proper unit test is likely to be the hard part.
