### ISSUE TITLE
Stale docs for Drake GitHub issue labels

### ISSUE THREAD

**Issue by jwnimmer-tri** [RobotLocomotion/drake#12638]
@RussTedrake it looks like you (or someone else at MIT) added more `team: ` names to Drake's list of issue labels in GitHub?  That's fine, but then also we need updates to:
- the textual enumeration of teams and owners at https://drake.mit.edu/issues.html, and
- the query filter in https://drake.mit.edu/platform_reviewer_checklist.html hyperlink.

**Comment by jwnimmer-tri** [comment]
(Alternatively, keep only `team: robot locomotion group` and add a different label, e.g., just `6.832` to flag them as related to courses.)

**Comment by RussTedrake** [comment]
Apologies; did not appreciate the dependency.  

I like that last suggestion (only team: robot locomotion group, then extra tags).  Will implement it tonight if nobody beats me to it.

**Comment by RussTedrake** [comment]
Changed `team: MIT 6.881` => `type: MIT 6.881` and `team: MIT 6.832` to `type: MIT 6.832`, and added `team: robot locomotion group` to any issues that would have been left without a `team` assigned.  Will PR the update to the docs now.
