### ISSUE TITLE
broken link to SOS tutorial from mathematical_program.ipynb

### ISSUE THREAD

**Issue by RussTedrake** [RobotLocomotion/drake#12634]
It looks like the SOS tutorial link is pointing to @hongkai-dai 's google drive.  When I click on it from [binder](https://mybinder.org/v2/gh/RobotLocomotion/drake/master?filepath=tutorials/mathematical_program.ipynb)
 -- it's at the very bottom of the page -- it looks to try to open the colab page but renders very very oddly.

I think the right solution is to land the SOS tutorial in `drake/tutorials`.

**Comment by EricCousineau-TRI** [comment]
@hongkai-dai Would you like me to port the colab page to Drake? We can always go back and do a cleanup pass afterwards?

**Comment by hongkai-dai** [comment]
@EricCousineau-TRI , yes that would be great. I will do a clean up pass later after you port the tutorial to Drake.
