### ISSUE TITLE
optimize loading of large meshes into bullet, or at least warn the user

### ISSUE THREAD

**Issue by RussTedrake** [RobotLocomotion/drake#1264]
Right now, if somebody tries to load a urdf with dense meshes as collision elements, drake simply appears to hang (in `constructModelmex`).  

Looking into it quickly, the hangup is in the looping call to `addPoint` in `BulletModel::newBulletMeshShape` (inside `BulletModel.cpp`).

It also appears that in the latest bullet rev, this method has an optional second argument which would disable the Aabb calculation on every point that gets added.  We could presumably then call `recalcLocalAabb` ourselves *after* adding all of the points. Not sure if this will make large meshes suddenly tractable for us, but we might at least make it past the load stage.  

I think we should try upgrading to the latest bullet and using this feature.  If it resolves the issue, great.  If not, we should also somehow add a warning and/or fail more gracefully if someone accidentally passes in a big mesh.

**Comment by psiorx** [comment]
As of 6 days ago, Bullet is now primarily hosted on GitHub.  The old files will only continue to be hosted on Google Code for some temporary grace period.  

We should probably take this opportunity to transition our Bullet build logic away from downloading a tarball and point it to the new repo.  I'd like to use CMake ExternalProject for this, but it might take some tweaking to get it to match the current functionality in the Makefile (there are some special cases for handling different OS's).

Also, can you point me to an example URDF that exhibits this problem for testing purposes?
