### ISSUE TITLE
sytems::Diagram has no API call for allocating anything other than discrete variables

### ISSUE THREAD

**Issue by rcory** [RobotLocomotion/drake#12652]
Since `systems::diagram::AllocateDiscreteVariables()` is already provided by the API, it should also provide `AllocateAbstractVariables()`, `AllocateContinuousVariables()`, etc.

**Comment by sherm1** [comment]
Related: #12616

**Comment by jwnimmer-tri** [comment]
Continuous variables are `AllocateTimeDerivatives` already, available in `System`.

Note that I will be deprecating `LeafSystem::AllocateContinuousState` in #12630 or before.

I suppose for abstract we should have an API -- the workaround in the meantime is `AllocateContext` + `get_abstract_state`?  But what is the use case where you do not want to use `AllocateContext` instead?  Most things deal with the whole context, not just a portion of it.

I do worry about advertising APIs for these though before #9171 is finished.

**Comment by sherm1** [comment]
@rcory in view of @jwnimmer-tri's comment above do you think these are still needed?

**Comment by jwnimmer-tri** [comment]
Closing for lack of response.
