### ISSUE TITLE
Update all macOS CI builders to bazel 2.0

### ISSUE THREAD

**Issue by jwnimmer-tri** [RobotLocomotion/drake#12678]
Some builders are reporting bazel 1.2.1 currently.

**Comment by jwnimmer-tri** [comment]
1.2.1:
https://drake-jenkins.csail.mit.edu/view/Nightly%20Production/job/mac-catalina-clang-bazel-nightly-debug/111/

2.0.0:
https://drake-jenkins.csail.mit.edu/view/Nightly%20Production/job/mac-mojave-clang-bazel-nightly-release/203/

Looks like catalina vs mojave, perhaps.

**Comment by jamiesnape** [comment]
That is very strange. Looking into it now.

**Comment by jwnimmer-tri** [comment]
FWIW If new images are coming, might be worth PRing this as well:
https://github.com/RobotLocomotion/drake/blob/2bfc34f1d24cfbc168ea8d0403c81fb3ce559e69/setup/mac/binary_distribution/install_prereqs.sh#L22-L24

**Comment by jamiesnape** [comment]
The images were there, but for some reason only 3 of 4 were deployed. User error on my part, it seems.

**Comment by jwnimmer-tri** [comment]
Fixed now.
