### ISSUE TITLE
Possibly move various tests (e.g., force element and joint tests) from MbT to MbP

### ISSUE THREAD

**Issue by mitiguy** [RobotLocomotion/drake#12739]
While reviewing PR# 11946, Alejandro Castro commented that linear_bushing_roll_ptich_yaw_test.cc should make calls through MBP=MultibodyPlant (which is the preferred API) rather than MBT=MultibodyTree (which is really for developers).  Since the code for the LinearBushingRollPitchYaw test started with linear_spring_damper_test.cc, it initiated a discussion about which tests belong where.

TBD:  Which (if any) of the tests in multibody/tree/test should route their calls through MBP rather than MBT and if these tests are changed, should their corresponding files be be moved to multibody/plant/test ?

**Comment by sherm1** [comment]
(Assigned to @amcastro-tri first for discussion.)
