### ISSUE TITLE
Should be possible to provide sdf/urdf models as strings

### ISSUE THREAD

**Issue by ggould-tri** [RobotLocomotion/drake#12754]
Currently the only way to add SDF/URDF models to a MultibodyPlant is via `AddModelFromFile`.  However there are cases where a model is more easily provided in the form of a string or a stream.  For example @avalenzu notes that a DRC team had the robot provide its model over the wire, and I am currently working with a robot (WLKATA Mirobot) that emits the link data used in its internal IK via its serial protocol.

It would probably make sense to provide AddModelFromStream and a trivial wrapper around that for AddModelFromString.

**Comment by jwnimmer-tri** [comment]
The libsdformat APIs don't really support streaming, so I just plan to add a string overload directly.

**Comment by SeanCurtis-TRI** [comment]
@jwnimmer-tri I have a branch where I started this as well. Are you actively tackling this? I note you elevated the priority. Depending on how far along you are, I can either finish mine or retire it.

**Comment by SeanCurtis-TRI** [comment]
Never mind; I just noticed the PR.

**Comment by EricCousineau-TRI** [comment]
FWIW Semi-relates #9500 (stuff on the wire, etc)

**Comment by jwnimmer-tri** [comment]
I added `AddModelFromString` but not the plural `AddAllModelsFromString` companion.  I'll reopen the issue (at lower priority) to go back and add that, too.

**Comment by rpoyner-tri** [comment]
Is there a reason this issue is still open? the String APIs have been available for quite some time.
