### ISSUE TITLE
[geometry] QueryObject introduces Eval...() methods (cache query results)

### ISSUE THREAD

**Issue by SeanCurtis-TRI** [RobotLocomotion/drake#12767]
# Problem Statement

`QueryObject` is the main interface through which other entities can make geometric queries. Invoking a query method on that object always leads to calculations. Therefore, if downstream entities have multiple code paths that would depend on the same query, and *care* about performance, they are obliged to cache the results of the query. This is unfortunate. It doesn't scale well and displaces `QueryObject`'s rightful burden.

# Proposed solution

`QueryObject` should provide `Eval()` versions of those queries (or as many as is reasonable) such that downstream callers are free to evaluate the same query over and over and not worry about incurring a cost. Very much in line with the current `Calc()` vs `Eval()` paradigm.

**Comment by SeanCurtis-TRI** [comment]
@amcastro-tri FYI

**Comment by sherm1** [comment]
Seems like a great idea!

**Comment by jwnimmer-tri** [comment]
Closing until we have a motivating benchmark.
