### ISSUE TITLE
Insufficient unit test of function MakeActuatorSelectorMatrix()

### ISSUE THREAD

**Issue by huihuaTRI** [RobotLocomotion/drake#12779]
Function `MakeActuatorSelectorMatrix` is overloaded on both `JointIndex` and `JointActuatorIndex`. The unit test of this function covers the case of `JointIndex`. However, the `JointActuatorIndex` case is only tested for empty input, which could be insufficient.

On the other hand, it would be nice to have some examples to show how to get a `JointActuatorIndex` from some API. I am having problems finding any. This could be linked to issue [12778](https://github.com/RobotLocomotion/drake/issues/12778)

**Comment by amcastro-tri** [comment]
In #12778 I pointed you to `MBP::GetJointActuatorByName()`. I imagine you'll make immediate use of it since you needed it. I'd be thrilled if you push any of your examples/work as a unit test for this API. It'd definitely be a nice addition as you mention.
