### ISSUE TITLE
Need some sugar to test if two polynomial symbolic::Expressions have coefficients that are approximately equal.

### ISSUE THREAD

**Issue by RussTedrake** [RobotLocomotion/drake#12817]
Right now I'm using:
```
  EXPECT_TRUE(Polynomial(V - V_expected)
                  .RemoveTermsWithSmallCoefficients(1e-6)
                  .EqualToAfterExpansion(Polynomial(Expression::Zero())));
```
It's not horrible, but took me a while to figure out a version I liked -- partly because I kept forgetting that `Expression::ToPolynomial()` returns a `Polynomiald` and NOT a `symbolic::Polynomial`.

**Comment by hongkai-dai** [comment]
@soonho-tri , have you worked on this already? I can take this one.

**Comment by soonho-tri** [comment]
@hongkai-dai , I couldn't start working on this yet. It would be great if you can take this. Thank you.

**Comment by hongkai-dai** [comment]
I plan to add a new function to `symbolic_polynomial.h`
```
bool symbolic::Polynomial::AlmostEqual(const symbolic::Polynomial& other, double tolerance);
```
which returns true if the coefficients between two polynomials are all equal up to the tolerance.

**Comment by RussTedrake** [comment]
Thanks!  I think something like `CoefficientsAlmostEqual` is more clear?
