### ISSUE TITLE
wishlist for operator overloads on symbolic::Polynomial

### ISSUE THREAD

**Issue by RussTedrake** [RobotLocomotion/drake#12832]
these would clean up my #12827 significantly.

```
operator-(Polynomial, Variable)
pow(Polynomial, int)
operator/(Polynomial, double)
Evaluate(Matrix<Polynomial>)
Jacobian(Vector<Polynomial>, Vector<Variable>)
```

**Comment by hongkai-dai** [comment]
I see, that is why you use symbolic::Expression instead of symbolic::Polynomial.

**Comment by soonho-tri** [comment]
#12835 is supposed to provide the requested features.

> pow(Polynomial, int)

Note that this one is already available at https://github.com/RobotLocomotion/drake/blob/master/common/symbolic_polynomial.h#L256-L257.

**Comment by soonho-tri** [comment]
Close by #12835
