### ISSUE TITLE
`MathematicalProgram::AddConstraint(Vector<Formula>)` please?

### ISSUE THREAD

**Issue by RussTedrake** [RobotLocomotion/drake#12841]
We have the vector version for [`Expression`](https://drake.mit.edu/doxygen_cxx/classdrake_1_1solvers_1_1_mathematical_program.html#a412ef43fcfe9a34e19b1054d8750836b), but not for `Formula`.  Would be very nice to have!

**Comment by soonho-tri** [comment]
I'll take care of it.
