### ISSUE TITLE
URDF parser doesn't load joint effort limit

### ISSUE THREAD

**Issue by sammy-tri** [RobotLocomotion/drake#12859]
The Multibody SDF parser loads joint effort limits, but the URDF parser lacks this feature.  It may be slightly more complicated in the URDF case because the effort is specified in the `joint` tag but the joint actuator is created when parsing the `transmission` tag.

**Comment by sammy-tri** [comment]
Self-assigning for now.  If someone wants to work on this more urgently feel free to reassign.

**Comment by sherm1** [comment]
Do we have a way to enforce the effort limit in MBP? It comes in with the joint but I guess it has to be applied to the MBP actuator input port?

**Comment by sammy-tri** [comment]
We don't have a way to enforce the limit in MBP.   I opened this issue in response to a discussion with @yangwill on Slack, he confirmed for me that his interest right now is only in being able to query the value (which I believe would be basically equivalent to the parser support for joint velocity, which I don't think is enforced anywhere either).

**Comment by sherm1** [comment]
I see. Getting it read in does seem like a good first step!
