### ISSUE TITLE
Document that the shorthand vector notation [3  5  7]ʙ  is  3 Bx + 5 By + 7 Bz

### ISSUE THREAD

**Issue by mitiguy** [RobotLocomotion/drake#12888]
Per conversations with @amcastro-tri  and @sherm1 while doing PR #11946,
document the shorthand vector notation  [3  5  7]ʙ.
Herein ʙ denotes a frame whose right-handed orthogonal unit vectors are Bx, By, Bz.
So, [3  5  7]ʙ  =  3 Bx + 5 By + 7 Bz.

Consider a short one-liner at:
https://drake.mit.edu/doxygen_cxx/group__multibody__quantities.html

**Comment by jwnimmer-tri** [comment]
If we're going to do this, please feel free to open a PR.  Given the 4 year time gap, it seems like "not planned" is the facts on the ground, though.
