### ISSUE TITLE
Add wget as a prereq on Mac?

### ISSUE THREAD

**Issue by zacinaction** [RobotLocomotion/drake#1289]
I just tried installing Drake from source on my brand new Mac and ran into some issues due to missing wget (which is not included by default on OS X). A quick 'brew install wget' fixed the problem, but I thought it might be good to include this in the "install_prereqs.sh" script.

**Comment by RussTedrake** [comment]
thanks.  can you tell which external was building when you hit this?

**Comment by zacinaction** [comment]
Bullet

**Comment by RussTedrake** [comment]
perfect.  i’ve added it to my upcoming pull request.  thanks for reporting it.

**Comment by zacinaction** [comment]
Great - thanks!
