### ISSUE TITLE
install swig on the build servers

### ISSUE THREAD

**Issue by rdeits** [RobotLocomotion/drake#1293]
Eventually we may want to use the custom swig-matlab build, but for now it would be nice to have swig available on the build servers (IRIS currently needs it). It should just be: `sudo apt-get install swig` and `brew install swig`.

**Comment by RussTedrake** [comment]
done.  (on drake001,2,3,4,5, and 6).  looks like 3.0 on windows, but might have been 2.0 on ubuntu 12.04
