### ISSUE TITLE
Bug with writeMeshOBJ's use of vertex normals

### ISSUE THREAD

**Issue by mposa** [RobotLocomotion/drake#1296]
util/writeMeshOBJ.m seems to generate invalid OBJ files. In particular, the code to generate the normals ("vt x y z") looks wrong.

1) It only generates 2-vectors, not 3-vectors
2) The vectors it generates are unrelated to the actual normal computations

On my branch, I've temporarily fixed this by removing the use of normals. I'm not sure if this code gets used anywhere in mainstream Drake, but it's hard to see it working at all as-is.

**Comment by patmarion** [comment]
"vt" specifies texture coordinates, not vertex normals.  It appears correct, in that case.  It indeed looks like the code computes normals, but never writes them to the .obj file.  To write normals, it would use the "vn" specifier.

**Comment by RussTedrake** [comment]
i think we've decided this is not an issue...

**Comment by mposa** [comment]
Ok. I'll have to keep the fix around on my branch then, since it caused crashes for me.

**Comment by RussTedrake** [comment]
can you tell us how to reproduce the crash?

**Comment by mposa** [comment]
Seems to have been tied to the older visualizer

**Comment by RussTedrake** [comment]
great.
