### ISSUE TITLE
pybind: Mitigate change of internal GC structure in 3.8

### ISSUE THREAD

**Issue by EricCousineau-TRI** [RobotLocomotion/drake#13026]
EDIT: Whoops! Looks like it was already changed here:
https://github.com/python/cpython/commit/5ac9e6eee5ed18172d70d28cf438df0be4e3b83d

So yeah, now I have to spend time mitigating :(

---
# Old Issue
Title: "pybind: Should ask CPython API maintainers to make resurrection for 2+ times be public API"

Per convo with @jamiesnape, seems like Python 3.8 and 3.9 may start having some breakages, not sure if it will be some heavy CPython API breakages.

I should make sure I make this request sooner than later (would have been better to have made it ~2  years ago):
https://github.com/RobotLocomotion/pybind11/blob/cac3edd971c70469aa710c13d59f9c29c7f4651f/include/pybind11/pytypes.h#L1465-L1475

\cc @ToffeeAlbina-TRI

**Comment by EricCousineau-TRI** [comment]
For example, breakage in Cython for this very reason :(
https://bugs.python.org/issue35081#msg330045

**Comment by EricCousineau-TRI** [comment]
Filed: https://bugs.python.org/issue40240

**Comment by EricCousineau-TRI** [comment]
Ask made, so it may be in the works. For now, will close this, but should re-open once the internal API becomes some form of public and is controllable with a version macro.
(I will receive notifications on upstream issue.)

**Comment by jwnimmer-tri** [comment]
FYI relates to the Drake 3.7 -> 3.8 transition from #13087.
