### ISSUE TITLE
ci: Update Ubuntu AMIs

### ISSUE THREAD

**Issue by jwnimmer-tri** [RobotLocomotion/drake#13083]
Per #13032 we have a new Bazel pin; please refresh the AMIs to use the latest commit.

\CC @jamiesnape

**Comment by jwnimmer-tri** [comment]
Hmm, I did the procedure from memory but got it wrong.  I see now that https://drake.mit.edu/jenkins.html#updating-installation-prerequisites says to use a different order of operations.  Sorry!

**Comment by BetsyMcPhail** [comment]
The Bionic AMI has been updated. As always, it will take Jenkins a few cycles to catch up.
