### ISSUE TITLE
Should document (un)supported features for sim/multibody description formats

### ISSUE THREAD

**Issue by EricCousineau-TRI** [RobotLocomotion/drake#13103]
Motivated by:
* @jwnimmer-tri's [Slack post](https://drakedevelopers.slack.com/archives/C2WBPQDB7/p1587402931061500)
* Drake Developers Meeting Agenda, April 13, 2020

Should document:
* (un)Supported features for SDFormat
  * I would like to include a "roadmap" of sorts for things that are under development.
* (un)Supported features for URDF

This info should have indication for collision types as well. (Relates #12230)
Can be summarized as a table, but I also may want another form for drilling into details.

\cc @SeanCurtis-TRI

**Comment by SeanCurtis-TRI** [comment]
This should also include any custom `drake:`-namespaced tags that we parse.

**Comment by EricCousineau-TRI** [comment]
For collision, should also consider pairwise collision constraints as indicated in #10907.

**Comment by jwnimmer-tri** [comment]
I believe that @rpoyner-tri has already accomplished this in documentation:

https://drake.mit.edu/doxygen_cxx/group__multibody__parsing.html

@EricCousineau-TRI can you take a look and let us know what else is missing?

It doesn't have a roadmap, but _shrug_ that doesn't seem terribly important.  We can use the issues database for tracking any requests that are acute enough to merit action.

**Comment by EricCousineau-TRI** [comment]
Looks good to me! In the future, perhaps we can say which portion of SDFormat we do(n't) parse (e.g. we don't parse `//actor`, `//link/enabled_wind`), but if no one's asking atm, we can defer until acute need arises.

Thanks!
