### ISSUE TITLE
Add contact results visualization to tutorials/rendering_multibody_plant.ipynb

### ISSUE THREAD

**Issue by RussTedrake** [RobotLocomotion/drake#13116]
We don't show anybody, yet, how to visualize forces.  It would be easy/nice to add to the tutorial.

So far, when someone asked, I've responded with:

In meshcat, we have:
https://github.com/RobotLocomotion/drake/search?q=MeshcatContactVisualizer&unscoped_q=MeshcatContactVisualizer

For drake-visualizer, we have:
https://github.com/RobotLocomotion/drake/search?q=ConnectContactResultsToDrakeVisualizer&unscoped_q=ConnectContactResultsToDrakeVisualizer

**Comment by jwnimmer-tri** [comment]
The basics of collision display probably do deserve a mention in the rendering tutorial.

We've also talked about adding a dedicated tutorial for collisions / proximity, which should incorporate a comprehensive look at all kinds of collision visualization.

**Comment by jwnimmer-tri** [comment]
Note that #17690 is somewhat related, but has a different focus.

**Comment by jwnimmer-tri** [comment]
Now that we pervasively suggest `AddDefaultVisualization`, this mostly works correctly automatically.  What remains here is perhaps to add more explanatory text, or a deeper dive on understanding what we're showing when we see collisions in the default visualization.
