### ISSUE TITLE
Drake004 Details button broken

### ISSUE THREAD

**Issue by tkoolen** [RobotLocomotion/drake#1314]
See e.g. this pull request: https://github.com/RobotLocomotion/drake/pull/1304.
Clicking the Details button will start a download of unitTests.out, which only contains
```
!<symlink>ˇ˛/tmp/unitTests.out
```

**Comment by RussTedrake** [comment]
Yup.  I know.  I installed the non-cygwin version of apache, so it doesn't understand those symlinks...

**Comment by RussTedrake** [comment]
should be fixed now.
