### ISSUE TITLE
ci: Initial Ubuntu 20.04 (Focal Fossa) support

### ISSUE THREAD

**Issue by jwnimmer-tri** [RobotLocomotion/drake#13147]
Towards #13102.

We'd like these jobs available in CI, as we start to experiment with 20.04 support:

- linux-focal-unprovisioned-gcc-bazel-experimental-release
- linux-focal-unprovisioned-gcc-bazel-continuous-release

**Comment by jamiesnape** [comment]
Experimental is up. Continuous to follow. See https://drake-jenkins.csail.mit.edu/view/Linux%20Focal%20Unprovisioned/.

**Comment by jamiesnape** [comment]
Continuous is also up.
