### ISSUE TITLE
Purge QPController.m (in favor of the c++ implementation)

### ISSUE THREAD

**Issue by rdeits** [RobotLocomotion/drake#1317]
I'd like to get rid of the old QPController implementation since it's no longer used on the robot or in any simulation examples except the running and jumping demos. To do that, I'll need to:
- [ ] extend lcmt_zmp_data to support 3D systems
- [ ] generalize QPLocomotionPlan.cpp to accept non-constant S in the Lyapunov function
- [ ] generalize setupAndSolveQP to variable-size linear systems (for 2D and 3D)

**Comment by RussTedrake** [comment]
@rdeits -- did the push for valkyrie balancing accomplish this?

**Comment by rdeits** [comment]
No, unfortunately. It's an unrelated issue, mostly due to the lack of support for 3D linear systems in the new controller.

**Comment by jwnimmer-tri** [comment]
Even though #6369 is going to remove the MATLAB implementation, my guess is that it makes sense to keep this issue open, as a TODO to work on the C++ implementation.

**Comment by RussTedrake** [comment]
related to #6381.  with that link established, I will close this one.
