### ISSUE TITLE
Error building drake from GitShell

### ISSUE THREAD

**Issue by itsamk** [RobotLocomotion/drake#1319]
It gives me the following error when I try to build drake on my system using GitShell.[See the image] Please help me resolve this. Thank you. I have already spent hours on the installation.
![capture](https://cloud.githubusercontent.com/assets/13022431/9699141/f57af5b0-53f4-11e5-8032-a8119a38c1d3.JPG)

**Comment by RussTedrake** [comment]
I believe this is because your make command has a space in it.  But this should have already been resolved in the master branch of drake.  Can you make sure you are up to date, and show me a git log to be sure?

**Comment by itsamk** [comment]
I am not really aware with what a git-log is. Can you specifically tell me what to do? I have followed all the instructions on the drake installation instructions page.

**Comment by RussTedrake** [comment]
in the shell, cd into drake-distro and type `git log`.

**Comment by itsamk** [comment]
I exported the git log to a text file and that gave me a 3.7 MB sized file that I can't upload here. Any other way?

**Comment by RussTedrake** [comment]
I just need the top 10 lines

**Comment by RussTedrake** [comment]
I'm planning to make a new precompiled distribution in the next few days -- probably even this weekend.  Perhaps it's easier to go the precompiled route?

**Comment by itsamk** [comment]
Here is the head of the text file. See if you can figure out the problem. It will be really great if this could work somehow now. Otherwise, I can wait till you build up a precompiled version. Sooner will be the better. 
------------------------------ 
commit d42493ab9f1753ace73f9d47851ff76ba2f54061
Merge: 9142442 f381eaf
Author: Russ Tedrake <russt@mit.edu>
Date:   Thu Sep 3 05:22:51 2015 -0400

    Merge pull request #1316 from rdeits/rd-controller-cleanup
    
    delete a bunch of unused control files

commit 91424424785c7ec8b95872d58e426871d6a70482
Merge: 178dd45 775f19b
Author: Russ Tedrake <russt@mit.edu>
Date:   Thu Sep 3 04:44:56 2015 -0400

    Merge pull request #1313 from tkoolen/tk-update-cmake-remove-random-target
    
    Update cmake (got rid of random target generation in pods.cmake)
------------------------------------------

**Comment by RussTedrake** [comment]
took a quick look.  the short answer is -- don't use GitShell (it doesn't support batch syntax).  try running make in the cmd.exe window instead.  I've also used Git Bash and or Git CMD.

For my own notes: PowerShell should probably be treated as Cygwin instead of Windows_NT, but it still seems to have handled some of the quotes differently.

**Comment by itsamk** [comment]
Thanks for the suggestion. 'Make' finally executes but gets stuck somewhere in the process.[see the image] 
![hang](https://cloud.githubusercontent.com/assets/13022431/9701413/f6e26a28-5444-11e5-9c82-08093c4bc3ed.JPG)

**Comment by RussTedrake** [comment]
git is asking you for a password.  snopt requires a license.  you’ll have to set WITH_SNOPT to false for now.

**Comment by itsamk** [comment]
Gives me this error now. 
![capture1](https://cloud.githubusercontent.com/assets/13022431/9701481/b8fc5724-5448-11e5-9232-a5f9948888b3.JPG)

**Comment by RussTedrake** [comment]
the actual error is higher up in the screen.  search for the word Error.

**Comment by itsamk** [comment]
![capture12](https://cloud.githubusercontent.com/assets/13022431/9701504/083f0af6-544a-11e5-8f6a-a78f712cafb3.JPG)

Here.

**Comment by RussTedrake** [comment]
no.  i need to know what cmd.exe was called when it failed.

**Comment by itsamk** [comment]
Sorry, I realized that. I updated the previous comment.

**Comment by RussTedrake** [comment]
it looks like drake did not get checked out properly.  perhaps because it was partially checked out during one of your previous failed attempts.  i would do a clean build (and set your option preferences again)
```
cd drake-distro
rd /s build
rd /s pod-build
make options
make
```

**Comment by itsamk** [comment]
![capture12](https://cloud.githubusercontent.com/assets/13022431/9701553/a2b21fae-544c-11e5-976d-11f971c2d078.JPG)

Back to the previous error.

**Comment by RussTedrake** [comment]
what happens if you cd in the drake subdirectory and run make in there?

**Comment by itsamk** [comment]
![capture13](https://cloud.githubusercontent.com/assets/13022431/9701580/1b6cb174-544e-11e5-9a8e-cec137d48ac1.JPG)

gives me this.

**Comment by RussTedrake** [comment]
you haven’t put the pkg config lite program in your path (from the installation instructions)

**Comment by itsamk** [comment]
![capture14](https://cloud.githubusercontent.com/assets/13022431/9701620/4375da28-544f-11e5-9c76-df2a4d7c1675.JPG)

Here, right? I did.

**Comment by RussTedrake** [comment]
can you call pkg-config from your shell?   (you have to restart the shell for environment variable changes to take effect)

**Comment by itsamk** [comment]
No. It says the term is not recognized.

**Comment by RussTedrake** [comment]
you need to resolve that.

**Comment by itsamk** [comment]
I have added it in the path so theoretically it should work right? 
[..]\Downloads\pkg-config-lite-0.28-1_bin-win32\pkg-config-lite-0.28-1\bin;

cmd.exe gives me the same error.
git shell gives me this:
![capture15](https://cloud.githubusercontent.com/assets/13022431/9701660/48eb26d2-5451-11e5-81e9-346947db8e5b.JPG)

**Comment by RussTedrake** [comment]
that’s working.  try make again

**Comment by itsamk** [comment]
The error is still there. I have even set WITH_EIGEN and WITH_SPOTLESS to FALSE.(They gave errors too)
![capture16](https://cloud.githubusercontent.com/assets/13022431/9701716/575b8064-5455-11e5-933b-ca7e176e0044.JPG)

**Comment by RussTedrake** [comment]
You need eigen.  it’s a required dependency.  

I’m sorry — but I think you should use the precompiled distro.

**Comment by itsamk** [comment]
Then, if I turn EIGEN to TRUE it still gives be related errors. I wish there was some resolution to this. I have just started the course "Underactuated Robotics" at edz and I hope the lack of drake for the first week doesn't cause much problems.
Waiting for the precompiled version. Thanks for your time.

**Comment by itsamk** [comment]
I just realized that you're the instructor to the course as well. Thanks a lot for all the great material. Means a lot.

**Comment by itsamk** [comment]
I removed drake and did a fresh start and cloned it again. This time I used gitbash to run make but, somehow make is giving me an error. Please help me through this.
![captur](https://cloud.githubusercontent.com/assets/13022431/9865394/2f2ec78e-5b73-11e5-8539-7b874b8265d1.JPG)

**Comment by RussTedrake** [comment]
did make options work?  did it pull up a gui, and let you configure and generate?

**Comment by itsamk** [comment]
Yes, it did!

**Comment by RussTedrake** [comment]
try running `make -d` instead of just `make` and show us the output?

**Comment by itsamk** [comment]
![captur](https://cloud.githubusercontent.com/assets/13022431/9865948/76701ee8-5b7a-11e5-9d6f-bfc6514f9713.JPG)

**Comment by RussTedrake** [comment]
i see.  i think that cmake did not find your make executable.  to confirm, can you check the file pod-build/CMakeCache.txt for the MAKE_EXECUTABLE line and show us what it says?

and type `which make` at the command line?

**Comment by itsamk** [comment]
I think I see the error. It has the wrong path set. What should be the correct path here?
![captu](https://cloud.githubusercontent.com/assets/13022431/9866385/63d5ba0e-5b7f-11e5-9980-806e35b4165a.JPG)

**Comment by RussTedrake** [comment]
wherever you have make installed.

**Comment by itsamk** [comment]
Changed it to MAKE_EXECUTABLE:FILEPATH= C:/Program Files (x86)/GnuWin32/bin/make.exe
still doesnt work :\

**Comment by RussTedrake** [comment]
make sure there are no extra spaces and put quotes around it?

**Comment by itsamk** [comment]
I double checked that.

**Comment by itsamk** [comment]
Tried quotes too.

**Comment by tkoolen** [comment]
So https://github.com/RobotLocomotion/drake/pull/1353 fixed this right?

**Comment by RussTedrake** [comment]
yes.
