### ISSUE TITLE
AddEqualTimeConstraints()  should return (a vector of) Bindings

### ISSUE THREAD

**Issue by RussTedrake** [RobotLocomotion/drake#13213]
Having proclaimed the usefulness of naming constraints with e.g.
```
AddConstraint(...).evaluator().set_description('equal_time')
```
I got the natural question about naming the equal time constraints.  I believe this one is my fault; and that the method should return those values.

**Comment by ggould-tri** [comment]
Should this also apply to the other MultipleShooting methods that add constraints (eg `AddTimeIntervalBounds`, `AddDurationBounds`)?

**Comment by RussTedrake** [comment]
Absolutely.  I would think all of the `Add` methods should return their bindings.
