### ISSUE TITLE
Adding Valkyrie as external

### ISSUE THREAD

**Issue by mauricefallon** [RobotLocomotion/drake#1323]
@RussTedrake :
> fyi - take a look at #1320 and see if you like that as a possible model for including Valkyrie.  
> (you keep it in your own repo but it still drops in as an example folder in drake).

With that example, its straightforward to pull in the valkyrie repo. A problem is that the urdf is periodically updated from upsteam NASA source with drake- and ddapp-facing tags e.g. collision groups and contact points in a semi-automated fashion. This is about the same approach @avalenzu had for Atlas.

I guess I'll store the output urdf in a branch.
Do you plan to move the examples content (e.g. Atlas) out of the main repo?

**Comment by RussTedrake** [comment]
Primarily because there is no benefit unless we also remove the history (which is not sometime I want to mess with), I’m currently think that the existing examples like Atlas will stay in the main repo.
