### ISSUE TITLE
Remove ruby dependency

### ISSUE THREAD

**Issue by jwnimmer-tri** [RobotLocomotion/drake#13231]
Asking users to install a full ruby interpreter just to build Drake from source seems overly heavyweight.

We only use it for https://github.com/osrf/sdformat/blob/master/sdf/embedSdf.rb, so it should be possible to rewrite that script in a lighter language (either within Drake, or upstream).

See #8976 for where we added ruby.

**Comment by jwnimmer-tri** [comment]
My current plan of attack:
- PR to sdformat refactoring the "embed" codegen logic
  - remove application-layer versioning logic from codegen
    - be a boring dictionary of relative_filename => contents
      - the codegen rb script will be like 10 lines long
  - stop relying on the global initialization and destruction fiasco
- Upgrade sdformat in Drake
- Re-implement the (now boring) codegen script in python

**Comment by EricCousineau-TRI** [comment]
FTR See old BitBucket PR discussion:
https://github.com/osrf/sdformat/blame/9eb6b99c2c8295fcf533589b4e8e6f4fd5fa623a/Changelog.md#L527
https://osrf-migration.github.io/sdformat-gh-pages/#!/osrf/sdformat/pull-requests/434/page/1#comment-65236228

**Comment by jwnimmer-tri** [comment]
We'll see where https://github.com/osrf/sdformat/pull/270 takes us.
