### ISSUE TITLE
LinearModelPredictiveController should be updated or removed

### ISSUE THREAD

**Issue by RussTedrake** [RobotLocomotion/drake#13248]
The documentation promises that it can handle constraints, but I don't see any implementation that does?  In that case, it does not require a QP solver and reduces to the finite horizon LQR (which we now have).

Furthermore, potential users see the name and look at this implementation to see how we might make optimization performant for MPC in drake.  But this class does NOT do that.  It constructs the transcription from scratch on every timestep, instead of using our best practices for e.g. keeping the `MathematicalProgram` and simply using e.g. `Constraint::UpdateLowerBound` and `Constraint::UpdateCoefficients` or `QuadraticCost::UpdateCoefficients`.

@hongkai-dai -- fwiw, I think now that we've lost @siyuanfeng-tri 's QP controller (because it depended on `RigidBodyPlant`), I don't think we actually have any examples of updating the MP in drake master.

@jadecastro -- what do you think?

**Comment by hongkai-dai** [comment]
I can add a tutorial on updating MP.
