### ISSUE TITLE
styleguide: Should support nested namespaces?

### ISSUE THREAD

**Issue by EricCousineau-TRI** [RobotLocomotion/drake#13244]
Came up in:
https://github.com/robotlocomotion/drake/pull/13225#pullrequestreview-406269679

Seems like current upstream styleguide still doesn't acknowledge nested namespaces either:
https://google.github.io/styleguide/cppguide.html#Namespace_Formatting

FTR nested namespaces make:
```cc
namespace drake::pydrake {
...
}  // namespace drake::pydrake
```
equivalent to:
```cc
namespace drake {
namespace pydrake {
...
}  // namespace pydrake
}  // namespace drake
```
https://en.cppreference.com/w/cpp/17

\cc @SeanCurtis-TRI @jwnimmer-tri @sammy-tri @ggould-tri @sherm1 @RussTedrake @IanTheEngineer

**Comment by sherm1** [comment]
We definitely should allow that! Much nicer.

**Comment by avalenzu** [comment]
TIL!

**Comment by jwnimmer-tri** [comment]
I am not a huge fan of "there is more than one way to do it", for all the usual reasons.  If we like the more compact style, then we should plan to update style guide to disprefer multiple lines and reformat all of Drake in the new style.  Having a linter rule would be a bonus.

**Comment by EricCousineau-TRI** [comment]
SGTM. Was thinking there should be a list of different options, with preferences.

**Comment by jamiesnape** [comment]
Is this a question for a feature request?

**Comment by jwnimmer-tri** [comment]
I think it was both, but any case is on Eric's plate to develop the linter if he want to change the style.

**Comment by jwnimmer-tri** [comment]
The idea is a fine one, but we don't need an issue tracking it.
