### ISSUE TITLE
Upgrade to VTK 9

### ISSUE THREAD

**Issue by jamiesnape** [RobotLocomotion/drake#13253]
Released earlier this week: https://gitlab.kitware.com/vtk/vtk/-/tree/v9.0.0

Relates #10729 (this will be a prerequisite), #12325 (included in the release), #13102 (fewer patches). FYI @SeanCurtis-TRI.

**Comment by jwnimmer-tri** [comment]
Food for thought -- on macOS, if we disabled Drake's ospray support (since it's going to go away when we switch to ARM anyway),  could we then use homebrew's own vtk 9 packages, instead of rolling our own?

**Comment by jwnimmer-tri** [comment]
... now filed as #14326, to be worked prior to the VTK 9 transition.
