### ISSUE TITLE
Update CI for new images (+clang-format-9, -ruby)

### ISSUE THREAD

**Issue by jwnimmer-tri** [RobotLocomotion/drake#13264]
PR #13260 and #13262 have changed the setup pre-requistes. Please deploy new CI images for Ubuntu and macOS.

**Comment by jwnimmer-tri** [comment]
To combine effort, it's possible that adding Gurobi 9 (per #13049) to the CI images (in addition to having Gurobi 8 still present) would be smart.

**Comment by jamiesnape** [comment]
Ubuntu is done. It may be Monday before both Mac are done.

**Comment by jamiesnape** [comment]
Mac is updated.
