### ISSUE TITLE
Should we include MixedIntegerBranchAndBound in ChooseBestSolver ?

### ISSUE THREAD

**Issue by RussTedrake** [RobotLocomotion/drake#13299]
I would vote "yes" because we do not support any MIP solvers in our binary releases.  It would be nicer to write code that just formulates a MIP, and dispatches to gurobi, etc, if available but falls back to our own branch and bound.

@hongkai-dai , @TobiaMarcucci -- what do you think>?

**Comment by RussTedrake** [comment]
If we think yes, then conceptually it would be nice to use `ChooseBestSolver` again to pick the solver_id that the branch and bound uses.  If `ProgramAttributesSatisfied` accepted a `ProgramAttributes` instead of a `MathematicalProgram`, then this would be easy... we would just remove the binary variables attribute and call it again.

**Comment by TobiaMarcucci** [comment]
I'd also vote yes. Students were a little confused by the way that Hongkai's B&B is currently called, they thought it was a "different way to solve an optimization problem," and not another solver. This made some confusion when I was telling them that Gurobi actually uses a B&B algorithm.

**Comment by hongkai-dai** [comment]
I will add it to ChooseBestSolver, probably after Jeremy's PR #13279 lands.

**Comment by jwnimmer-tri** [comment]
As far as how to accomplish this, I think the plan should be to add a `class FooSolver : public SolverBase` that calls `ChooseBestSolver` (on the simplified program) then `MixedIntegerBranchAndBound` during `FooSolver::Solve`.  Then `ChooseBestSolver` can know about `FooId` (presumably at the end of the list).

**Comment by RussTedrake** [comment]
Is there a reason that `MixedIntegerBranchAndBound` does not derive from `SolverBase`?

**Comment by jwnimmer-tri** [comment]
As it stands now, `MixedIntegerBranchAndBound` has-a `MathematicalProgram` and provides for the same kind of data as `MathematicalProgramResult`.  While we could refactor it to derive from `SolverBase`, a wrapper seems easiest and in line with how we treat other servers -- we have `FooSolver` for the wrapper and the server is a distinct library unit tested on its own.

**Comment by jwnimmer-tri** [comment]
Update as of #15541: when try to solve a MIP but no solver can do it (e.g., Guribi is missing), now at least the failure message tells users that they can try `MixedIntegerBranchAndBound` by hand.  This is not necessarily as smooth as we desired upthread, but possibly gets some users unstuck on their own.
