### ISSUE TITLE
clang-format: create, host, and use clang-format@9 formula

### ISSUE THREAD

**Issue by jamiesnape** [RobotLocomotion/drake#13310]
Would save > 3 GB on the Mac images.

**Comment by jwnimmer-tri** [comment]
Partial mitigation towards #13284.

**Comment by jamiesnape** [comment]
https://github.com/RobotLocomotion/homebrew-director/commit/8b01ad18235794448d51bd9fc7cd037ac63743f0, though I need to hook it up to Drake before closing this.
