### ISSUE TITLE
Port examples/rod2d to SceneGraph

### ISSUE THREAD

**Issue by jwnimmer-tri** [RobotLocomotion/drake#13316]
Currently, `examples/rod2d` uses the attic-based drake visualizer glue.  We should port it to use `SceneGraph` instead.

Relates #12158.

https://github.com/RobotLocomotion/drake/blob/4ca6218ebff1aed9bf096ea01589899e9804015c/examples/rod2d/rod2d_sim.cc#L88-L91

**Comment by jwnimmer-tri** [comment]
@SeanCurtis-TRI To confirm my understanding, is the best thing to do here to write a new `RodGeometry` utility class, akin to [PendulumGeometry](https://github.com/RobotLocomotion/drake/blob/master/examples/pendulum/pendulum_geometry.h)?

(I'm hoping we can find an interested new developer to work on this as an onramp issue, not you or I.)

**Comment by SeanCurtis-TRI** [comment]
Yes and yes. We happen to be "on boarding" someone at the beginning of June.  :)  @sherm1 are you thinking what I'm thinking?

**Comment by jwnimmer-tri** [comment]
I was going to ask @IanTheEngineer if he wants to look next week.  Might be a good onramp for RViz work.

**Comment by SeanCurtis-TRI** [comment]
I wouldn't say no to that.

**Comment by sherm1** [comment]
Sounds like a good mini-project. I'm not sure whether Rod2d is actually a great intro to modern Drake, but just making it talk to SG would provide some useful Drake know-how.

**Comment by SeanCurtis-TRI** [comment]
The nice thing is that there are numerous examples of the `PendulumGeometry` pattern in Drake. So, without delving into the details of the system implementation too deeply, you can visualize.

**Comment by jwnimmer-tri** [comment]
We need this finished in the next two weeks, or else we'll remove rod2d from master on 2020-09-01.

**Comment by SeanCurtis-TRI** [comment]
I'll see if I can't just fix it this afternoon. Probably faster to change than to discuss.
