### ISSUE TITLE
Add system scalar conversion with new type as a template argument

### ISSUE THREAD

**Issue by jwnimmer-tri** [RobotLocomotion/drake#13313]
In #13131 we discussed a missing feature from `System<U>` -- the ability to scalar convert it into a `System<T>` where `<T>` is a template argument, instead of being part of the method name as currently such as `ToAutoDiffXd`.

> Adding a templated To... converter is fine. Ideally, we'd offer all three flavors (static, maybe, throws) and use analogous spellings to the current `AutoDiffXd` and `Symbolic` methods, for consistency. (Assuming the static one's more-templated still makes sense; I haven't penciled it out.)

This is an issue to request the new API.

See https://github.com/RobotLocomotion/drake/issues/13131#issuecomment-628578100 for a little more background.

**Comment by EricCousineau-TRI** [comment]
Peanut gallery comment:
Here's a (more constrained) analog in Python:
https://github.com/RobotLocomotion/drake/blob/4ca6218ebff1aed9bf096ea01589899e9804015c/bindings/pydrake/multibody/test/plant_test.py#L112-L124

I'm guessing C++ would work the same way - just query the virtual override using `typeid(T)` at runtime?

**Comment by jwnimmer-tri** [comment]
In C++ I would expect `if constexpr (std::is_same<T, AutoDiffXd>)` to be the trick, not `typeid`.

**Comment by hongkai-dai** [comment]
If this feature works, then we can easily get both AutoDiff with constant size, or the Hessian using nested autodiff.

**Comment by jwnimmer-tri** [comment]
This would still be a closed set of support scalar types.  This is just allowing a method call syntax where the one (of three) choices is a template argument, instead of part of the method name (i.e., the ToAutoDiffXd, ToSymbolic, etc. family).

As always, if we want a new scalar in Drake, then we add it to `default_scalars.h` and throughout the code.

**Comment by rpoyner-tri** [comment]
I've begun a sketch of this; the C++ is pretty straightforward. Question:
what conversion pairs must be supported? Obviously:

double --> autodiff
double --> symbolic

Any others that should be supported? self (e.g., double --> double) transitions? * --> double transitions?

**Comment by jwnimmer-tri** [comment]
I think the starting point would be to match the conversions that are available by default in SystemScalarConverter:
https://github.com/RobotLocomotion/drake/blob/v0.29.0/systems/framework/system_scalar_converter.h#L102-L110

**Comment by rpoyner-tri** [comment]
Excellent! The C++ is mostly done. No 'if constexpr's were harmed in the production of this patch.

Onward to pydrake land.
