### ISSUE TITLE
with_all_supported_externals=ON tries to clone repos that are not public

### ISSUE THREAD

**Issue by mprat** [RobotLocomotion/drake#1333]
Default for 'WITH_ALL_SUPPORTED_EXTERNALS' with CMake tries to clone the repo https://github.com/RobotLocomotion/gloptipoly3.git, sedumi, and snopt, which are not public repos. 

SNOPT_PRECOMPILED works. So `make download-all` works if WITH_ALL_SUPPORTED_EXTERNALS is OFF and gloptipoly3, sedumi, snopt, and bertini are all OFF.

**Comment by mprat** [comment]
Also https://github.com/RobotLocomotion/sedumi.git

**Comment by mprat** [comment]
Also SNOPT.

**Comment by RussTedrake** [comment]
absolutely right.  we should definitely make a WITH_ALL_PUBLIC_EXTERNALS option, too.  (WITH_ALL_SUPPORTED_EXTERNALS was originally intended to help the build servers).
