### ISSUE TITLE
it seems not all cmake externals support "make clean"

### ISSUE THREAD

**Issue by RussTedrake** [RobotLocomotion/drake#1338]
maybe, at the very least, I could use http://www.cmake.org/cmake/help/v2.8.8/cmake.html#command%3aset_directory_properties to add the pod-build directory to make clean for subdirs...?

**Comment by patmarion** [comment]
Probably already aware, but just to be clear, "make clean" means different thing in the cmake world vs. the pod world.

cmake's make clean: removes files created during the build (.o, .so, etc).  Does not remove configuration (CMakeCache.txt) and does not remove files created during install.

pods's make clean: rm's files listed in the install_manifest.txt (usually this lists all files that were installed, no guarantees for custom install steps), then rm's the pod-build (configuration data).  This is more like a make uninstall and make confclean.

**Comment by jhoare** [comment]
Once this gets fixed up, I propose that we add a test in continuous integration to test ``make clean``  @jamiesnape

**Comment by jamiesnape** [comment]
Create a ticket if others agree.

**Comment by Lucy-tri** [comment]
I am working on creating a new external, nlopt #1627 , and it would be really handy to be able to reliably "make clean" for externals (and for everything else).
