### ISSUE TITLE
Should decouple Pydrake vector formatting from C++ formatting

### ISSUE THREAD

**Issue by sherm1** [RobotLocomotion/drake#13395]
#### Background
C++ Drake uses Eigen vectors while Pydrake uses Numpy vectors. Eigen and Numpy have different output formatting conventions. Drake also defines composite vector type VectorBase (and BasicVector) which are visible both in Drake and Pydrake. In C++ we would like output formatting for those (using `operator<<()`) to follow Eigen conventions while in Pydrake we'd like them to follow Numpy conventions.

#### The problem
Currently Pydrake's VectorBase formatting depends on `VectorBase::operator<<()` using Numpy formatting. That prevents resolution of issue #12257, which noted that `operator<<()` had the wrong formatting for Eigen compatibility in C++. @avalenzu merged PR #13365 to fix that but it was reverted in #13384 due to Pydrake breaking.

#### Proposed fix
Make Pydrake's vector formatting independent of C++ so that both packages can use the most natural formatting. Then re-merge #13365.

**Comment by EricCousineau-TRI** [comment]
Marginally relates #8586
