### ISSUE TITLE
runAtlasWalkingNarrowStairs errors

### ISSUE THREAD

**Issue by RussTedrake** [RobotLocomotion/drake#1340]
on some of the build machines... ?  is that just because it was timing out on the others?  is there stochasticity in there?

http://drake006.csail.mit.edu/drake/pull-RussTedrake-snopt_alloc_on_heap-into-RobotLocomotion-master_20150913-0625-Continuous

<matlab_test>strcmp(test_name,'examples/Atlas/test/runAtlasWalkingNarrowStairs') && strcmp(error_id,'Drake:runAtlasWalkingStairs:BadCoMTracking')</matlab_test>

**Comment by rdeits** [comment]
Nope, no stochasticity in that test (but that doesn't mean the results are reliable). I'll look at it now.

**Comment by rdeits** [comment]
Have we maybe lost the fix that improved raycast accuracy in bullet? The raycast terrain height maps for that example are pretty gross now: 

![screenshot-2015-09-14_18 16 31](https://cloud.githubusercontent.com/assets/591886/9863354/13a5f142-5b0d-11e5-8155-c9af648297aa.png)

**Comment by psiorx** [comment]
This might have something to do with the recent bullet upgrade.  The patch that fixed the raycast problems was no longer relevant since the changes that it made are now the defaults in bullet.

**Comment by rdeits** [comment]
Ok, good to know. It's not a critical issue, but might be worth remembering in case we have other raycast problems in the future.
