### ISSUE TITLE
Accelerometer and Gyroscope sensors

### ISSUE THREAD

**Issue by mposa** [RobotLocomotion/drake#13457]
Since attic/ is being deprecated, we will need MBP-friendly implementations of IMU sensors. It's on our todo list, unless someone wants to tackle it first.

**Comment by sherm1** [comment]
Do you want just ground truth spatial acceleration results, or a real device simulation?

**Comment by sherm1** [comment]
MBP can already provide SpatialAcceleration for each body via an output port (we could do it by API also but I'm not sure that's wired up yet). If there is a body representing the IMU that would give a ground truth reading. Is that usable?

**Comment by mposa** [comment]
That's definitely the data that's needed (spatial acceleration and angular velocity), though we'll need to wrap it into objects "IMU/Accelerometer/Gryo" that only provides the actual measurements. I think the basic question is whether or not these sensor systems exist in Drake or only in our dairlib ecosystem.

**Comment by sherm1** [comment]
Ah, yes it would be nice to have pre-built IMU sensors living in `drake/systems/sensors` along with rotary encoders, rgbd, etc.

**Comment by mposa** [comment]
Resolved via https://github.com/RobotLocomotion/drake/pull/13501 and https://github.com/RobotLocomotion/drake/pull/13604 and
