### ISSUE TITLE
Can't build a working precompiled drake on osx

### ISSUE THREAD

**Issue by rdeits** [RobotLocomotion/drake#1346]
I've spent several hours on it, but I can't get a working precompiled distro on osx. I fixed some trivial errors in make_drake_package.sh and created an install script to rewrite all the absolute paths in our non-binary files (which fixes the issue with `pods_get_bin_path.m`, etc.). I also added the CMakeCache.txt to the release filelist. All those changes are here: https://github.com/RobotLocomotion/drake-admin/compare/master...rdeits:rd-install?expand=1 But actually trying to run Quadrotor/runDircol gives:

```
>> runDircol
Invalid MEX-file
'/Users/rdeits/locomotion/drake-admin/www/drake-0.9.9-140da13e5358355f455601435ca866891531132e-mac/drake/systems/plants/constructModelmex.mexmaci64':
dlopen(/Users/rdeits/locomotion/drake-admin/www/drake-0.9.9-140da13e5358355f455601435ca866891531132e-mac/drake/systems/plants/constructModelmex.mexmaci64,
6): Library not loaded: @rpath/libdrakeRBM.dylib
  Referenced from:
  /Users/rdeits/locomotion/drake-admin/www/drake-0.9.9-140da13e5358355f455601435ca866891531132e-mac/drake/systems/plants/constructModelmex.mexmaci64
    Reason: image not found
```

I also cannot run the director from the precompiled distro:
```
/ddConsoleApp -m ddapp.drakevisualizer
Fatal Python error: PyThreadState_Get: no current thread
^C[1]    47878 abort      ./ddConsoleApp -m ddapp.drakevisualizer
```

nor the `drake_viewer`:

```
./drake_viewer
dyld: Library not loaded: @rpath/libdrake_lcmtypes.dylib
  Referenced from: /Users/rdeits/locomotion/drake-admin/www/drake-0.9.9-140da13e5358355f455601435ca866891531132e-mac/build/lib/libdrake_urdf_renderer.dylib
  Reason: image not found
[1]    47919 trace trap  ./drake_viewer
```

I'm afraid I have to give up on this for tonight.

**Comment by RussTedrake** [comment]
thanks for resolving this Robin.
