### ISSUE TITLE
py mbp: Should bind `pydrake.multibody.optimization`

### ISSUE THREAD

**Issue by EricCousineau-TRI** [RobotLocomotion/drake#13473]
See:
https://github.com/RobotLocomotion/drake/tree/master/multibody/optimization

@rpoyner-tri Is this something that you might be interested in taking turns at?

Suggested order:
- [ ] (Eric) `StaticEquilibriumConstraint`
- [ ] (Rico) `ManipulatorEquationConstraint`
- [ ] (Eric) `ContactWrenchEvaluator` + `ContactWrench`
- [ ] (Rico) `StaticFrictionConeConstraint`
- [ ] (Eric) `AddSlidingFrictionComplementarityExplicitContactConstraint`, `AddSlidingFrictionComplementarityImplicitContactConstraint`

Personally, ~I don't mind if we don't~ I do not want us to bind the `*Problem` flavors of the classes.

\cc @hongkai-dai

**Comment by EricCousineau-TRI** [comment]
Per VC with @rpoyner-tri, did an initial work split.

**Comment by jwnimmer-tri** [comment]
> Personally,I do not want us to bind the *Problem flavors of the classes.

Isn't that what #14140 did, though (which you approved)?  Is the issue summary above stale, maybe?

**Comment by jwnimmer-tri** [comment]
We invite users to submit bindings for any classes they need that are not yet bound.  For now, this particular request is not planned.
