### ISSUE TITLE
Update Coulomb friction plot label

### ISSUE THREAD

**Issue by amcastro-tri** [RobotLocomotion/drake#13480]
A (late) follow up to #13463. 

I just realized we must update the label of the x axis [here](https://github.com/RobotLocomotion/drake/blob/a58cf34fbcad1c6f7fc43a42289a0b6775bdcaf4/multibody/plant/images/ideal_stiction.py#L22).

Where it says "Pushing Force (N)", it should say "Sliding velocity (m/s)". 

Nit, I'd also advocate for square brackets to place units.

**Comment by EricCousineau-TRI** [comment]
Simple issues should really have one owner, otherwise accountability is super unclear.
Taking myself off for now ;)

Also, I think in the time it took you to write this issue, you could have written the PR + motivation yourself ;)

**Comment by SeanCurtis-TRI** [comment]
And given where the code lives, this really feels like you should be the owner.

**Comment by EricCousineau-TRI** [comment]
Went ahead and did it anywho. It took me 30sec.
@amcastro-tri Would really love it if in the future you made the smaller changes yourself ;)

**Comment by amcastro-tri** [comment]
sry, I was absolute swamped and when I considered it I realized I had no idea what the process to update those png's is, while you guys do. So no, it would've taken me more than 30 secs.

**Comment by amcastro-tri** [comment]
In retrospect, I realized I should've assigned this to self and use it as a reminder to work on it later. Sorry if this caused you a distraction @EricCousineau-TRI, @SeanCurtis-TRI
