### ISSUE TITLE
mkdoc: Should split out Doxygen -> Sphinx (Napoleon) and test separately

### ISSUE THREAD

**Issue by EricCousineau-TRI** [RobotLocomotion/drake#13499]
Currently, we have our mega-function:
https://github.com/RobotLocomotion/drake/blob/76956e194f197f9ce69236d88aab4e996b24c90a/third_party/com_github_pybind_pybind11/mkdoc.py#L227-L654

That is tested Christmas-tree style:
https://github.com/RobotLocomotion/drake/blob/76956e194f197f9ce69236d88aab4e996b24c90a/tools/workspace/pybind11/test/sample_header_documentation.expected.h

Tasks:

- [ ] We should separate out the docstring processing to its own module (since it's relatively modular), and also have focused tests.
- [ ] As part of this, it would be nice to also simplify `sample_header.h`.

\cc @jamiesnape

**Comment by EricCousineau-TRI** [comment]
@BetsyMcPhail Might this be feasible w/in the next 4 weeks? (June 25)

**Comment by BetsyMcPhail** [comment]
> @BetsyMcPhail Might this be feasible w/in the next 4 weeks? (June 25)

Sounds good to me.
