### ISSUE TITLE
ModelInstance might be making a wrong assumption on state ordering.

### ISSUE THREAD

**Issue by amcastro-tri** [RobotLocomotion/drake#13509]
Thanks to @sammy-tri's comment [here](https://drakedevelopers.slack.com/archives/C2WBPQDB7/p1591374332199500?thread_ts=1591232230.163600&cid=C2WBPQDB7) (in a conversation that started off from an unrelated issue to parsing joints), we found out that we might have introduced a bug when mapping dofs on a per model instance basis.

What we do know about MBP's conract:
- Joints do not dictate the internal tree structure (though the idea is that they do inform a "good/convenient"  tree structure). JointIndex has nothing to do with how dofs are ordered.
- The order mobilizers are added, MobilizerIndex, has nothing to do with how dofs are added either. MBT allows to add mobilizers in any order during the construction of the tree model.
- The tree structure of the model is dictated by the inboard/outbard relationship imposed by mobilizers. The for each "body mobilized by a given mobilizer", we create a "BodyNode".
- BodyNode's are the true nodes of the tree and are ordered in BFT order.
- Dofs are then assigned in increasing order starting at BodyNodeIndex(0) all the way to num_body_nodes().

Summarizing; neither JointIndex, nor MobilizerIndex have anything to do with how dofs are ordered.

cc'ing @sammy-tri

**Comment by sammy-tri** [comment]
Upon further review, the implementation isn't as bad as I thought, and I think we can close this out.

The order of the state for an individual model instance depends on the order in which the mobilizers are added to the model instance which happens after the topology is finalized), not the order in which there added to the plant.  And, fortunately, this happens in body node order, which is the same ordering `MultibodyTreeTopology` uses to assign positions in the full plant's state vector.

https://github.com/RobotLocomotion/drake/blob/master/multibody/tree/multibody_tree.cc#L311

(I even wrote a comment about it at the time!  If only I'd remembered.)

So, fortunately, I was wrong, and neither `JointIndex` or `MobilizerIndex` has anything to do with how dofs are ordered.
