### ISSUE TITLE
doc: python_bindings.rst should have installation instructions moved to installation doc pages

### ISSUE THREAD

**Issue by EricCousineau-TRI** [RobotLocomotion/drake#13500]
Currently, we have install docs here:
https://github.com/RobotLocomotion/drake/blob/76956e194f197f9ce69236d88aab4e996b24c90a/doc/python_bindings.rst#installation

Ideally, these should be filtered into:
https://github.com/RobotLocomotion/drake/blob/76956e194f197f9ce69236d88aab4e996b24c90a/doc/installation.rst

\cc @jwnimmer-tri

**Comment by jwnimmer-tri** [comment]
My plan is to rewrite all of the installation docs in July with help from a new technical contact at Kitware.  How about we wait for that?

**Comment by jwnimmer-tri** [comment]
I'll write it up later this week and post back here with the cross-link.

**Comment by jwnimmer-tri** [comment]
Now filed at #13539.

**Comment by ToffeeAlbina-TRI** [comment]
@RussTedrake this is captured under umbrella #13539 which is on deck on the [build system, continuous integration, distribution](https://github.com/RobotLocomotion/drake/projects/2) board, so I'm removing it from the [improve pydrake documentation *user* experience](https://github.com/RobotLocomotion/drake/projects/4) board.
