### ISSUE TITLE
mac/focal yaml serialization differs from bionic's

### ISSUE THREAD

**Issue by ggould-tri** [RobotLocomotion/drake#13541]
For whatever reason, yaml serialization on mac and focal produces vertically formatted lists, while serialization on bionic produces horizontally formatted ones.  This produces errors like

```AssertionError: 'exam[21 chars]rams:\n  - 5.0\n  - 50.0\n  - 5.0\n  - 1000.0\[89 chars]05\n' != 'exam[21 chars]rams: [5.0, 50.0, 5.0, 1000.0]\n  initial_stat[59 chars]05\n'
  example:
+   controller_params: [5.0, 50.0, 5.0, 1000.0]
+   initial_state: [1.2, 0.0, 0.0, 0.0]
-   controller_params:
-   - 5.0
-   - 50.0
-   - 5.0
-   - 1000.0
-   initial_state:
-   - 1.2
-   - 0.0
-   - 0.0
-   - 0.0
    t_final: 30.0
    tape_period: 0.05
```

The relevant test was nerfed in #13538 but should be rewritten to compare the parsed (or post-parse serialized) rather than a raw reference serialized form in its roundtrip tests (ie, to insist on semantic rather than syntactic equality).

**Comment by jwnimmer-tri** [comment]
Ideally, the I/O code could be set to use the flow style during serialization, because it's nicer to read.  We do that for C++ already:
https://github.com/RobotLocomotion/drake/blob/e55b6dd0bdd0bbb8a45a5ba9390407aaa90f2b8e/common/yaml/yaml_write_archive.cc#L29-L37

**Comment by ggould-tri** [comment]
Amen on the nicer-to-read.
I believe we may have ended up on opposite sides of https://github.com/yaml/pyyaml/pull/256 and so must always set `default_flow_style` when we call the dumper.

**Comment by jwnimmer-tri** [comment]
Ooh, a tribool found in the wild.  Get out the documentary cameras.
