### ISSUE TITLE
Prevent false remote cache hits between builds on different operating systems

### ISSUE THREAD

**Issue by jamiesnape** [RobotLocomotion/drake#13552]
Relates #13102.

Per https://github.com/bazelbuild/bazel/issues/4558 and https://github.com/bazelbuild/bazel/issues/3320 seems creating separate caches is the only truly safe solution.

**Comment by jamiesnape** [comment]
A minimal set of tools for a cache key would be:

* `CC` (`clang` or `gcc`)
* `gfortran`
* `java`
* `python3`

Something like

```bash
dpkg-query --showformat='${Version}' --show $(dpkg-query --search $(readlink -f $(command -v ${tool_name})) | cut -d':' -f1)
```

will get the version in a non-tool-specific way on Ubuntu (modulo some double quotes).

**Comment by jwnimmer-tri** [comment]
Is this a blocker for #13434?

**Comment by jamiesnape** [comment]
Pretty much. It is not a difficult task, though.

**Comment by jamiesnape** [comment]
Closed by https://github.com/RobotLocomotion/drake-ci/commit/7a41caeb69722af80d9e069549db1e1184b3f506.
