### ISSUE TITLE
Add caching for MultibodyTree::CalcAllBodyBiasSpatialAccelerationsInWorld()

### ISSUE THREAD

**Issue by mitiguy** [RobotLocomotion/drake#13560]
While improving efficiency on PR #13453, we thought caching may be useful if an end-user is doing a significant number of bias accelerations calculations -- no reason to call MultibodyTree::CalcAllBodyBiasSpatialAccelerationsInWorld() so many times if many different user-defined bias acceleration calculations are needed.

**Comment by amcastro-tri** [comment]
could you specify what quantity exactly you'd cache?

**Comment by mitiguy** [comment]
Current plan is to cache each body's spatial **bias** acceleration measured in world and expressed in world, with respect to speeds v.

Per conversation with @sherm1 and @rpoyner-tri, caching issue #13560 has been changed to high priority - after PR #13453 merges.  Per Sherm, there was an associated heap allocation performance issue raised by Evan Drumwright.

**Comment by mitiguy** [comment]
Per suggestion by @sherm1 in PR #13453, reverted this to high priority.

**Comment by jwnimmer-tri** [comment]
This issue does not explain why it's relevant, nor any benchmark that demonstrates why any speed-up is required.  Closing a "not planned".
