### ISSUE TITLE
Passing InputPortIndex(0) into PortSwitch's input port selector selects the port selector input

### ISSUE THREAD

**Issue by edrumwri** [RobotLocomotion/drake#13576]
PortSwitch system needs some documentation on proper use: it doesn't describe the type to its abstract input port (i.e., `get_port_selector_input_port()`).

Once one has discerned the type, the semantics of the value passed to this input port are counterintuitive: PortSwitch allows selecting the port selector input port! Put another way: if I pass in InputPortIndex(0) into the port selector input port, I have surprisingly selected the port selector input port. That should not be permitted. I need to pass in InputPortIndex(1) to select the first input port I've defined, InputPortIndex(2) to select the second, etc.

**Comment by jwnimmer-tri** [comment]
This is a fine report, but is not scheduled to be worked on.  People who are interested are invited to open a PR with the missing one sentence of documentation.
