### ISSUE TITLE
Broken sphinx on Ubuntu 18.04

### ISSUE THREAD

**Issue by jwnimmer-tri** [RobotLocomotion/drake#13574]
#13551 broke any Ubuntu 18.04 users that have `python-sphinx` installed in addition to `python3-sphinx`.  The file `/usr/bin/sphinx` points to the python2 version when both are installed.

The file `/usr/share/sphinx/scripts/python3/sphinx-build` is the python3 version, which is what we should be using.

**Comment by jamiesnape** [comment]
Technically #13551 exposed a pre-existing bug, but anyway, #13575.
