### ISSUE TITLE
sensors: RgbdSensor.X_WB_output_port() is `PoseVector`, not `Value<RigidTransform>` :(

### ISSUE THREAD

**Issue by EricCousineau-TRI** [RobotLocomotion/drake#13580]
Docs:
https://github.com/RobotLocomotion/drake/blob/5f4d84b44b69c63a90e88b26d0d07a152b518343/systems/sensors/rgbd_sensor.h#L187-L190

Implementation:
https://github.com/RobotLocomotion/drake/blob/5f4d84b44b69c63a90e88b26d0d07a152b518343/systems/sensors/rgbd_sensor.cc#L73-L74

Came across this while playing with visuomotor stuff and plugging in perception stuff. Basically, I tried to do this, and ran into a random "cannot do matmul for dtype=object"-ish error:
```py
X_WB = sensor.X_WB_output_port().Eval(context)
port = sensor.color_image_output_port()
X_WC = X_WB @ sensor.X_BC()  # Nuts!
```

:crying_cat_face: 

@SeanCurtis-TRI I'm thinking I was the one to review this PR, and didn't catch this?
FYI @RussTedrake Not sure if you're using this port directly.

**Comment by EricCousineau-TRI** [comment]
Retrospective: https://github.com/RobotLocomotion/drake/pull/11704#issuecomment-647227616
Dern...

**Comment by EricCousineau-TRI** [comment]
I *though* the workaround would be to change above Python code to:
```py
X_WB = sensor.X_WB_output_port().EvalAbstract(context).get_transform()
X_WC = X_WB @ sensor.X_BC()
```
... but it looks like the value being output is `Value[BasicVector_[float]]`, *not* `Value[PoseVector]`?

Anywho, the workaround will just be:
```py
blarg = X_port.Eval(context)
X_BC = PoseVector(blarg).get_transform()
```

**Comment by EricCousineau-TRI** [comment]
*WRONG*, `PoseVector(ndarray[7])` does not exist. Instead, I have to do:
```py
blarg = sensor.X_WB_output_port().Eval(context)
blarg_2 = PoseVector()
blarg_2.SetFromVector(blarg)
X_WB = blarg_2.get_transform()
```

:(

**Comment by SeanCurtis-TRI** [comment]
In deprecating `PoseBundle` and its associated classes (including `PoseVector`), `RgbdSensor` now has the `body_pose_in_world` output port. It is `RigidTransformd` valued.
