### ISSUE TITLE
//common:py/cpplint_wrapper_test times out on Focal

### ISSUE THREAD

**Issue by BetsyMcPhail** [RobotLocomotion/drake#13585]
For example: https://drake-cdash.csail.mit.edu/viewTest.php?onlyfailed&buildid=1306590

**Comment by rpoyner-tri** [comment]
Adding team label as part of platform-review rounds.

**Comment by jwnimmer-tri** [comment]
Running the cpplint_wrapper locally, it's somewhat broken anyway (complains about valid code, and assumes we still have a top-level "drake" folder).  Given the bazel scheduler for individual linting, I don't think this tools is useful anymore.

@BetsyMcPhail could you open a PR to remove cpplint_wrapper (and its test) from drake?  It is neither installed, nor mentioned in the documentation, so I don't think we need any deprecation period.

**Comment by DamrongGuoy** [comment]
I confirm that `//common:py/cpplint_wrapper` has nothing to do with CLion instruction for "Lint selected file for google style guide": 
[https://drake.mit.edu/clion.html#lint-selected-file-for-google-style-guide](https://drake.mit.edu/clion.html#lint-selected-file-for-google-style-guide)
