### ISSUE TITLE
[geometry] ConnectDrakeVisualizer ignores geometry state in context

### ISSUE THREAD

**Issue by SeanCurtis-TRI** [RobotLocomotion/drake#13597]
Calling `ConnectDrakeVisualizer` adds some systems to the diagram which are responsible for dispatching LCM message to initialize and update the illustrated SceneGraph geometries in `drake_visualizer`. Unfortunately, when the initialization event is processed to generate the "load" message, the system queries [the model inspector for the `SceneGraph` whose pointer has been stored](https://github.com/RobotLocomotion/drake/blob/master/geometry/geometry_visualization.cc#L283-L284) rather than using the world as described in the context. It should be implemented to depend on the context.

relates #13126

The solution for this is multi-part:

 - [x] #14247 Create a new `System` that properly respect Contexts, versions, and doesn't cheat to get the data.
 - [ ] #14282 Change the `ConnectDrakeVisualizer` implementation so that it replaces the Diagram with the new `DrakeVisualizer` `System`.

Resolves #14290

**Comment by EricCousineau-TRI** [comment]
See also: #10482

**Comment by jwnimmer-tri** [comment]
Several places in the code still mention this issue.  Possibly those should be cleaned up.

**Comment by jwnimmer-tri** [comment]
> Several places in the code still mention this issue. Possibly those should be cleaned up.

=> https://github.com/RobotLocomotion/drake/issues/20962
