### ISSUE TITLE
Additional Focal Dependencies for Binary Install

### ISSUE THREAD

**Issue by iperper** [RobotLocomotion/drake#13606]
Recently upgraded from 18.04 to 20.04 via clean install. 

Today installed Drake via binary [https://drake-packages.csail.mit.edu/drake/nightly/drake-latest-mac.tar.gz](https://drake-packages.csail.mit.edu/drake/nightly/drake-latest-mac.tar.gz).

Added drake to python path. 

`import pydrake` => `ImportError: libClp.so.1`.

This was because I forgot to run `sudo .\install_prereqs`.  After running script, first error resolved.

Try again: `import pydrake` => `ImportError: libnlopt.so.0`. Resolved with `sudo apt install libnlopt0`

Try again: `import pydrake` => `ImportError: libOpenGL.so.0`. Resolved with `sudo apt install libopengl0`

Didn't have this issue with 18.04, although likely because these libraries were available on my system from all the other projects over time.  Not sure if `sudo apt install libopengl-dev` is preferred over non-dev version.  I don't think I missed any install steps (running setup script and adding to Python path).

**Comment by jwnimmer-tri** [comment]
Hi @iperper, thanks for your report!

It seems like you're using Ubuntu 20.04.  However ...

> Today installed Drake via binary https://drake-packages.csail.mit.edu/drake/nightly/drake-latest-mac.tar.gz.

... this link doesn't seem correct, for that case.  Could you share which link you were using?

I'll investigate the dependencies, in any case.

**Comment by iperper** [comment]
Oops.  Sorry copied the wrong link.  It was [https://drake-packages.csail.mit.edu/drake/nightly/drake-latest-focal.tar.gz](https://drake-packages.csail.mit.edu/drake/nightly/drake-latest-focal.tar.gz)

**Comment by jamiesnape** [comment]
Looks like we are querying the wrong pkg-config file for nlopt (C++) on focal, so we are linking to `libnlopt0` (C) when we probably do not need to. On Bionic, there was no split between C and C++. For OpenGL, looks like we are probably installing `libGL.so` and not `libOpenGL.so`. Linking to OpenGL.so was intentional, so that is correct.

**Comment by jamiesnape** [comment]
```
$ ldd libdrake.so | grep "not found"
	libnlopt.so.0 => not found
	libOpenGL.so.0 => not found
	libOpenGL.so.0 => not found
$ ldd --unused libdrake.so | grep nlopt     
	libnlopt.so.0
```

(Aside: I should probably fix `ldd --unused libdrake.so` one day. We are over-linking a lot.)

**Comment by jamiesnape** [comment]
I may as well take this.
