### ISSUE TITLE
remove drake-urdf-schema-documentation from drake.mit.edu

### ISSUE THREAD

**Issue by RussTedrake** [RobotLocomotion/drake#13619]
I've been using google to search drake documentation, as recommended in #7559 and it works well.  But it also reveals that we've got some cruft on the web server.

For instance, googling [`urdf site:drake.mit.edu`](https://www.google.com/search?q=urdf+site%3Adrake.mit.edu) finds lots of his in the out-of-date schema documentation.

**Comment by jamiesnape** [comment]
Done, though it will take a while for Google to remove it from their index.
