### ISSUE TITLE
RoA examples are failing with "Problem looks primal infeasible"

### ISSUE THREAD

**Issue by rdeits** [RobotLocomotion/drake#1365]
On my system, I'm getting errors like this: 

```
Error using PolynomialSystem/regionOfAttraction>levelSetMethod (line 334)
Problem looks primal infeasible

Error in PolynomialSystem/regionOfAttraction (line 136)
      V = levelSetMethod(V,f,options);

Error in CartPolePlant/balanceLQR (line 62)
        V=regionOfAttraction(pp,V,options);

Error in runLQR (line 8)
  [c,V] = balanceLQR(d);
```

for the `runLQR` demos in Quadrotor2D and CartPole. I'm also getting this error on some of the textbook examples like `testCubicPolynomialRoa`.

**Comment by psiorx** [comment]
@anirudhamajumdar 
I think these started cropping up after enabling input saturations.  Any idea what could be going wrong?

**Comment by rdeits** [comment]
The issues seems to be only with Mosek. Forcing options.solver to be `@spot_sedumi` fixes it for me

**Comment by rdeits** [comment]
Turns out that's just the error that spotless reports when your mosek license has expired.
