### ISSUE TITLE
"Epic" for AutoDiffXd performance

### ISSUE THREAD

**Issue by EricCousineau-TRI** [RobotLocomotion/drake#13675]
This issue epic is meant to track performance issues related to our current (970faa6a9b) usage of `AutoDiffXd`. Performance could mean memory overhead, runtime allocations, but generally will relate most closely to wallclock time.

### Related issues

- #10322

### Related discussions

- Benchmarking in `dairlib`:
  - https://gist.github.com/mposa/99e17f7b043ad737cf429c6801311da2
  - https://drakedevelopers.slack.com/archives/C3L92BM2Q/p1590255574041300

\cc @sherm1 @mposa

**Comment by jwnimmer-tri** [comment]
This seems like a duplicate of #10991.

**Comment by EricCousineau-TRI** [comment]
Ah, yup! Closing.
