### ISSUE TITLE
parsing, urdf: Should set `SetDefaultFreeBodyPose()` for each link

### ISSUE THREAD

**Issue by EricCousineau-TRI** [RobotLocomotion/drake#13692]
This is a speculative feature to enable the following prototype:
https://github.com/RobotLocomotion/drake/pull/13128#pullrequestreview-449919203
Relates #13691 

\cc @sammy-tri

**Comment by sammy-tri** [comment]
I think this might be difficult to do in practice.  See my comments about the different cases of parent bodies in #13691.

**Comment by jwnimmer-tri** [comment]
@EricCousineau-TRI the issue overview is somewhat terse.  Could you expand upon the feature request to summarize, please?  What specifically is being requested, and why it is relevant/important to make this change?

**Comment by EricCousineau-TRI** [comment]
Upon rereading the references issues / PR, I think this issue is redundant in terms of #13691 - more or less, this is saying "to properly support an initial pose, we should use `SetDefaultFreeBodyPose()` when parsing via URDF, to ensure reposturing when including w/ SDFormat works correctly"

Closing - thanks for the ping!
