### ISSUE TITLE
mkdoc.py code should be moved from third_party

### ISSUE THREAD

**Issue by jamiesnape** [RobotLocomotion/drake#13726]
#13651 split up `third_party/com_github_pybind_pybind11/mkdoc.py`, which is a good thing. Unfortunately, it relocated some of its (third-party) code to `tools/workspace/pybind11/mkdoc_comment.py`, i.e., from the `third_party` directory to a regularly licensed directory. The code has been heavily modified, but it does retain copyright "2016 Wenzel Jakob" for part of it. I guess that this stage, it probably just needs a suitable statement in the file header, but code moving to/from `third_party` probably should be flagged in review in general.

FYI @BetsyMcPhail @EricCousineau-TRI @jwnimmer-tri.

**Comment by jamiesnape** [comment]
Aside: The `third_party` directory is a losing battle. My packaging tools are telling me that there are more third-party files outside of `third_party` than within it.

**Comment by EricCousineau-TRI** [comment]
Putting under `pydrake` for now and on that board. Seems like an easy 5-10min fix? (just for `mkdoc` ofc)
