### ISSUE TITLE
Xcode 7 breaking link to mex on OSX

### ISSUE THREAD

**Issue by peteflorence** [RobotLocomotion/drake#1374]
Already solved, but thought helpful to document as an issue, for others :+1: 

Also know @RussTedrake already worked through this since he commented on the MathWorks page

Error message was:

```
Error using mex
No supported compiler or SDK was found. For options, visit 
http://www.mathworks.com/support/compilers/R2014b/maci64.html.
```

And solution is at: http://www.mathworks.com/matlabcentral/answers/243868-mex-can-t-find-compiler-after-xcode-7-update-r2015b

**Comment by RussTedrake** [comment]
our more complete solution is on the drake faq.  - Russ
