### ISSUE TITLE
terrainInterpTest shows obvious mismatch with the terrain as visualized in the director

### ISSUE THREAD

**Issue by RussTedrake** [RobotLocomotion/drake#1376]
The dynamics are self-consistent and pass all of the matlab-side tests, but the visualization is obviously wrong.  The most likely culprit, I think, it my obj writing code.  @patmarion -- it's low priority, but tagging you in case you have ideas.

The test is drake/systems/plants/test/terrainInterpTest.m 
![screenshot-2015-09-26_17 48 12](https://cloud.githubusercontent.com/assets/6442292/10120016/c918a264-6476-11e5-9daf-f9f74ddc7d71.png)

**Comment by RussTedrake** [comment]
could be related to #1296 ?

**Comment by patmarion** [comment]
I ran it on linux and the terrain mesh looks correct.  I'll try mac.

**Comment by patmarion** [comment]
Looks correct on Mac, too.  So unfortunately I'm not able to reproduce what you've posted in the attached screenshot :(  For me, the .obj file seems to be written correctly on both platforms and displayed correctly.  It is:

v -7.000000 -3.000000 0.000000
v 7.000000 -3.000000 0.000000
v -7.000000 3.000000 0.000000
v 7.000000 3.000000 5.000000
vt 0.000000 0.000000
vt 1.000000 0.000000
vt 0.000000 1.000000
vt 1.000000 1.000000
g mesh
f 1/1 2/2 4/4 3/3
g

**Comment by RussTedrake** [comment]
Thanks for checking Pat.  I’ve only done it on my mac.  

Does it always look ok if you run it a few times?  (the intial conditions are random, and only some land in the “air”)

**Comment by patmarion** [comment]
Yes, I tried running it several times.  From what I can tell in the source code, the terrain geometry is not randomized, only the initial state of the brick.  The coordinates written in the obj file appear to match those defined in the test file:

options.terrain = RigidBodyHeightMapTerrain([-7,7],[-3,3],5*[0 0; 0 1]);

but in your screenshot, the terrain geometry seems to be wrong, so I'm not sure what that could be.  Given that Mike reported #1296, maybe some machines are misreading the obj files as written, and others are not?

**Comment by RussTedrake** [comment]
this is still clearly wrong on my mac.

**Comment by patmarion** [comment]
can you check the .obj file that is written to disk, does it contain the same values I posted in https://github.com/RobotLocomotion/drake/issues/1376#issuecomment-143782730 ?

**Comment by RussTedrake** [comment]
i see 
```
v -7.000000 -3.000000 0.000000
v 7.000000 -3.000000 0.000000
v -7.000000 3.000000 0.000000
v 7.000000 3.000000 5.000000
vt 0.000000 0.000000
vt 1.000000 0.000000
vt 0.000000 1.000000
vt 1.000000 1.000000
g mesh
f 1/1 2/2 4/4 3/3
g
```

**Comment by patmarion** [comment]
Ah, I see what's going on.  The obj file specifies a quadrilateral:

    f 1/1 2/2 4/4 3/3

But the quad vertices are not coplanar.  When the quad is rendered it must be split into triangles, and depending on how it is split, you will get one of the following two shapes:


<img width="568" alt="screen shot 2016-04-30 at 11 31 48 pm" src="https://cloud.githubusercontent.com/assets/90784/14939931/b402e410-0f2b-11e6-83fa-ff8b659edffb.png">

<img width="530" alt="screen shot 2016-04-30 at 11 40 23 pm" src="https://cloud.githubusercontent.com/assets/90784/14939970/22ae8b98-0f2d-11e6-8715-d7ea49638d23.png">


Maybe the obj writer should explicitly write the triangles faces.  These are the two possible triangulations:

    f 1/1 2/2 4/4
    f 1/1 4/4 3/3

or

    f 1/1 3/3 2/2
    f 3/3 4/4 2/2

If you edit your .obj file to use one of these face definitions, you can load it into drake-visualizer by using the "File --> Open Data..." menu to test.

**Comment by RussTedrake** [comment]
I’ve made the change to the matlab obj writer and it does fix this example.  Will send a PR momentarily.
