### ISSUE TITLE
Use libjchart2d-java from apt on Ubuntu

### ISSUE THREAD

**Issue by jamiesnape** [RobotLocomotion/drake#13778]
Seems to be the same version that we currently use:

* https://packages.ubuntu.com/bionic/libjchart2d-java
* https://packages.ubuntu.com/focal/libjchart2d-java

Relates in part #12783.

**Comment by jamiesnape** [comment]
Queuing this up for @BetsyMcPhail. If it starts getting complicated, we will probably put it on hold again, but I feel like it should be an easy win and a strict improvement for the binary packages.

**Comment by BetsyMcPhail** [comment]
@drake-jenkins-bot linux-bionic-unprovisioned-gcc-bazel-experimental-release please
@drake-jenkins-bot linux-focal-unprovisioned-gcc-bazel-experimental-release please
