### ISSUE TITLE
momentumTest doesn't match Adot_times_v

### ISSUE THREAD

**Issue by RussTedrake** [RobotLocomotion/drake#1377]
I've just converted momentumTest over to using quaternion floating base and tried to update the test code.. but don't get things to match.  It's certainly possible that I've made a mistake (but that test is pretty simple).

@tkoolen or @kuindersma -- might you take a look?  it's in #1375 right now, but i'm registering it here as a known issue so that it doesn't block things.

<matlab_test>strcmp(error_id,'Drake:ValueCheck') && strcmp(test_name,'systems/plants/test/momentumTest')</matlab_test>

**Comment by tkoolen** [comment]
I'm working on this.
