### ISSUE TITLE
Formatting issue in MbP "discrete update solver failed to converge" message

### ISSUE THREAD

**Issue by avalenzu** [RobotLocomotion/drake#13775]
Just got a fun error message (emphasis added):

> RuntimeError: MultibodyPlant's discrete update solver failed to converge at simulation time =   0.154 with *discrete update period =   0.000.* This usually means that the plant's discrete update period is too large > to resolve the system's dynamics for the given simulation conditions. This is often the case during abrupt collisions or during complex and fast changing contact configurations. Another common cause is the >use of high gains in the simulation of closed loop systems. These might cause numerical instabilities given our discrete solver uses an explicit treatment of actuation inputs. Possible solutions include:
>  1. reduce the discrete update period set at construction,
>  2. decrease the high gains in your controller whenever possible,
>  3. switch to a continuous model (discrete update period is zero),      though this might affect the simulation run time.

This was with a discrete-time MbP with a time step of 1e-4. As per slack discussion the remedy is probably to replace a `{:7.3f}` with a `{:7.3g}` somewhere.

**Comment by SeanCurtis-TRI** [comment]
Here
https://github.com/RobotLocomotion/drake/blob/master/multibody/plant/multibody_plant.cc#L2060
