### ISSUE TITLE
PR2 test prints "No closest point found" for every collisionDetect call after compile and the first dt

### ISSUE THREAD

**Issue by RussTedrake** [RobotLocomotion/drake#1378]
very suspicious.  perhaps something is not quite right with the new kinematics cache + bullet?

examples/PR2/runPassive

**Comment by avalenzu** [comment]
Is this new behavior?

**Comment by RussTedrake** [comment]
Yes.  Somehow it’s much worse with the quaternion floating base coordinates…

saturday (before merge):
http://kobol.csail.mit.edu/cd/testDetails.php?test=2896251&build=16389 <http://kobol.csail.mit.edu/cd/testDetails.php?test=2896251&build=16389>

saturday (on the pull request):
http://kobol.csail.mit.edu/cd/testDetails.php?test=2892466&build=16375 <http://kobol.csail.mit.edu/cd/testDetails.php?test=2892466&build=16375>

**Comment by tkoolen** [comment]
BulletModel::findClosestPointsBtwElements
(just so people can get here by searching for it.)

**Comment by tkoolen** [comment]
I think this is because we call
```
      [phi,~,~,~,idxA,idxB] = model.collisionDetect(zeros(model.getNumPositions,1));
```
on line 850 of RigidBodyManipulator.m. For quat floating joints, all zeros is not a valid configuration, and you can't even fix it by normalizing the quaternion in this case.

Should we introduce a method named e.g. nominalConfiguration or zeroConfiguration? Preferences as to the name?

**Comment by RussTedrake** [comment]
good call.  that might be it.  
for what it's worth, we do have `getRandomConfiguration()` , which supports quats.  the names should be consistent so I would say `getZeroConfiguration()`.  or decide to change the other method to `randomConfiguration()`.

**Comment by RussTedrake** [comment]
I just realized that this is actually the reason that drake006 has become so much less effective as a build server.  It's (slowly) writing comically enormous log files filled with reams of this error message.  I've marked this as high priority.
