### ISSUE TITLE
Documentation for `EventStatus` and `Simulator::set_monitor` led me astray

### ISSUE THREAD

**Issue by RussTedrake** [RobotLocomotion/drake#13794]
As documented in #13793, doxygen led me to believe that `Publish` events could return an `EventStatus` to terminate the simulation.  They cannot (yet).  

In particular, the documentation for `ReachedTermination` led me to a `set_monitor` example, which says "A monitor() function behaves the same as would a per-step Publish event handler included in the top-level System or Diagram being simulated."  I believe that is incorrect.  Please update it?

Should we have another issue to track the need to actually finish plumbing the `EventStatus`?

**Comment by sherm1** [comment]
I guess #4447 is that issue but it is somewhat buried in the long discussion there. I'll open a clean one.

**Comment by jwnimmer-tri** [comment]
BTW see #20035.  I think it will mostly (or fully?) solve this issue.
