### ISSUE TITLE
Parse MultibodyPlant model inputs from strings instead of only filenames

### ISSUE THREAD

**Issue by jwnimmer-tri** [RobotLocomotion/drake#13812]
The https://github.com/RobotLocomotion/drake/blob/master/multibody/parsing/parser.h only supports parsing from a filename on disk.  To allow for other sources of model data, we should also be able to parse when given the file contents as a string.

**Comment by mpetersen94** [comment]
Isn't this a duplicate of #12754 ?

**Comment by jwnimmer-tri** [comment]
Great point!  I totally meant to search before opening a new one, and totally failed to do it.  I'll close this as duplicate.
