### ISSUE TITLE
High count collision geometry causes segfault

### ISSUE THREAD

**Issue by chenheamazon** [RobotLocomotion/drake#13818]
> Before you post:

> * Have you reviewed the documentation on
[Getting Help](https://drake.mit.edu/getting_help.html)?
Yes
> * Have you reviewed existing GitHub issues and StackOverflow posts?
Yes the existing segfault issues are not related to this current one.
> * Have you rerun `install_prereqs.sh` on your current commit of `drake`?
Yes

> If you have encountered a bug (installation, segfaults, etc.), please try to
post reproduction steps and as much relevant output as possible. Consider
posting long snippets as a [Gist](https://gist.github.com/).

This is on commit 79200833ded29b88f01a28b74afacdd9d0323e87 from June 1, 2020

When I try to run the simple_gripper built in example, and change the number of collision geometry in the example https://github.com/RobotLocomotion/drake/blob/master/examples/simple_gripper/simple_gripper.cc#L67 (this line here) from 8 to 300, it causes a segfault. We have a similar use case where too many registered collision geometry causes a segfault and we suspect that this is the same issue.

**Comment by sherm1** [comment]
Assigning to @SeanCurtis-TRI for initial disposition.

**Comment by SeanCurtis-TRI** [comment]
I suspect that this got resolved with #13676.

**Comment by SeanCurtis-TRI** [comment]
You should see the benefit in the next release (or in master). Based on what the issue says, you should be able to reduce the number of collision geometries to around 100 (to limit the number of contacts to <= 128) and be ok. Once you have access to master (or the next release), you won't have to live with that artificial constraint.

**Comment by jwnimmer-tri** [comment]
FYI #13676 is available as of v0.20.0 (and v0.21.0, etc.) tags.

**Comment by SeanCurtis-TRI** [comment]
I'm surprised; I went looking in the [release notes](https://drake.mit.edu/release_notes/v0.21.0.html) and didn't see it. But I hadn't actually dug in the commit history to confirm it was included.

**Comment by jwnimmer-tri** [comment]
https://drake.mit.edu/release_notes/v0.20.0.html#multibody-dynamics

**Comment by SeanCurtis-TRI** [comment]
Oops...because it's [here](https://drake.mit.edu/release_notes/v0.20.0.html).

**Comment by SeanCurtis-TRI** [comment]
@chenheamazon Did you ever have the chance to confirm that the problem has gone away?

**Comment by SeanCurtis-TRI** [comment]
Closing because there's been no action for 1.5 years.
