### ISSUE TITLE
py geometry: Should permit RenderEngine to be extended in Python

### ISSUE THREAD

**Issue by EricCousineau-TRI** [RobotLocomotion/drake#13834]
This permits prototyping towards #11748 

Per convo with @thduynguyen 

FYI @RussTedrake @SeanCurtis-TRI

**Comment by SeanCurtis-TRI** [comment]
Could you elaborate on what this entails? Presumably, it's simply a case of [fleshing out the bindings beyond the nominal inclusion that currently exists](https://github.com/RobotLocomotion/drake/blob/master/bindings/pydrake/geometry_py.cc#L93-L99), yes? In essence, resolving the TODO?

If it's more than that, then please elaborate.

**Comment by EricCousineau-TRI** [comment]
That, and implementing a trampoline:
https://pybind11.readthedocs.io/en/stable/classes.html#inheritance-and-automatic-downcasting

FWIW Here's the currently generated interface that I'll use to bootstrap my bindings, courtesy of `autopybind11` (FYI @jamiesnape @josephsnyder):
https://github.com/EricCousineau-TRI/repro/commit/aaaefa7501e95986b999395b7487aa22ec61d951

**Comment by SeanCurtis-TRI** [comment]
Thanks, the elaboration is *very* helpful.

"Trampoline" is clearly a term of art. Do you have a link to its definition?

**Comment by jwnimmer-tri** [comment]
From https://en.wikipedia.org/wiki/Trampoline_(computing), this one seems about right to my experience:

> When interfacing pieces of code with incompatible calling conventions, a trampoline is used to convert the caller's convention into the callee's convention.

**Comment by EricCousineau-TRI** [comment]
Also, a little bit nestled away, but:
https://pybind11.readthedocs.io/en/stable/search.html?q=trampoline
https://pybind11.readthedocs.io/en/stable/reference.html?highlight=trampoline#c.PYBIND11_OVERLOAD
