### ISSUE TITLE
jaco urdf does not visualizer properly in meshcat

### ISSUE THREAD

**Issue by RussTedrake** [RobotLocomotion/drake#13846]
![meshcat](https://user-images.githubusercontent.com/6442292/89733414-5a2f9600-da23-11ea-86a7-d66311db1baa.png)

This is true for both `drake/manipulation/models/jaco_description/urdf/j2s7s300_sphere_collision.urdf` and `drake/manipulation/models/jaco_description/urdf/j2s7s300.urdf`.  Presumably there is some scale getting mis-handled somewhere in the pipeline?

@sammy-tri -- might you take a look?

**Comment by RussTedrake** [comment]
I can reproduce it with 
```
./bazel-bin/manipulation/util/geometry_inspector /Users/russt/drake-install/share/drake/manipulation/models/jaco_description/urdf/j2s7s300.urdf --meshcat
```
(this will open meshcat in a different viewer).

Side comments: 
- `show_model` doesn't appear to work well with a meshcat that is opened by the app.  it renders a blank screen.
- It was not clear how to use `show_model` and friends with resources that were fetched from `RobotLocomotion/models`.  When I ran it pointing to the jaco file in the source tree, it complained about missing mesh files.

**Comment by RussTedrake** [comment]
interestingly, it seems that the pyplot visualizer falls over, as well.  
```
./bazel-bin/manipulation/util/geometry_inspector /Users/russt/drake-install/share/drake/manipulation/models/jaco_description/urdf/j2s7s300.urdf --pyplot
```

**Comment by RussTedrake** [comment]
@gizatt -- fyi, if you are willing to take a look.

**Comment by gizatt** [comment]
Problem seems to be the handling of zero-radius spheres (which is the visual geometry given to the base + some other placeholder bodies). Easy fix in both cases -- I'll open a PR.
