### ISSUE TITLE
New name for drake visualizer

### ISSUE THREAD

**Issue by patmarion** [RobotLocomotion/drake#1385]
Currently the visualizer is launched by:  ddConsoleApp -m ddapp.drakevisualizer.
I can install a proper binary so it's launched with something like: drake-visualizer.  Note, the previous viewer is named drake_viewer.  If we can agree on a name, then this is an easy update which will make things cleaner.  The binary can behave as a proper Mac app bundle (and Windows non-console program) so it integrates into the desktop better.

**Comment by RussTedrake** [comment]
drake-visualizer works for me.  thanks!

(i regret naming the original drake_viewer instead of drake-viewer, which would have been more consistent)
