### ISSUE TITLE
jupyter: Need a way to test whether a jupyter notebook is running as a unit test or as a user

### ISSUE THREAD

**Issue by RussTedrake** [RobotLocomotion/drake#13862]
As discussed in https://reviewable.io/reviews/robotlocomotion/drake/13849#-MEKGi7s3mmUEdBP1AnR

In the underactuated and manipulation repos, I was able to use `get_ipython = None` at the test, but it doesn't work in drake.  @EricCousineau-TRI says we have an alternative approach in anzu.  We could even take the approach of setting an environment variable.  I'm not particular, but it's an important feature.

**Comment by jwnimmer-tri** [comment]
The `add_test_rule = True` case already reaches this branch in the launcher by passing `--test` in sys.argv:
https://github.com/RobotLocomotion/drake/blob/29b976c2eef3defc39c1255d8ffd8ce288c46302/tools/jupyter/jupyter_bazel.py#L43

That's probably where we should inject any customizations.

Something like https://github.com/takluyver/nbparameterise could replace top-of-notebook constants (e.g., `simulation_sec = math.inf`) with overrides given in the `BUILD.bazel`, similarly to how we use `test_rule_args` for the non-notebook flavors of `add_test_rule` to specify gflags.

The design is "the build system's test declarations can tune the device-under-test's parameters", not "a python function can ask whether being executed as a unit test".
