### ISSUE TITLE
missing support for specifying required dependencies

### ISSUE THREAD

**Issue by patmarion** [RobotLocomotion/drake#1390]
With make options, you can disable required dependencies which leads to build errors.  For example, this list contains a mix of required and optional dependencies, so the build system is unable to detect the error:

set(drake_dependencies cmake eigen lcm libbot bullet octomap snopt gurobi)

**Comment by RussTedrake** [comment]
discussed in #1523 -- and proposed a solution.  in short, we allowed this because we wanted users to be able to have a system version of, e.g. lcm, installed.  we will use more options to make that explicit.
