### ISSUE TITLE
improve documentation for using Gurobi as an external

### ISSUE THREAD

**Issue by vtjeng** [RobotLocomotion/drake#1392]
During the installation process for Drake, if users choose to [install Gurobi from source](https://github.com/RobotLocomotion/drake/wiki/FromSource) via `make`, they are required to insert their Gurobi.com username. However, as an additional step to get Gurobi working, it seems necessary to get an academic license and then to store the Gurobi license key file associated with the license. If this is indeed the case, then it would be useful to ensure that users do this first.

## Summary
Indicate that Gurobi is enabled by default if you use the WITH_ALL_PUBLIC_EXTERNALS option, and add a section on adding the key, specifically:

    cd drake-distro
    ./externals/gurobi/gurobi604/linux64/bin/grbgetkey [key-number]

**Comment by RussTedrake** [comment]
also discussed in #1523

**Comment by jonathan-owens** [comment]
Closed. See https://github.com/RobotLocomotion/drake/pull/2286
