### ISSUE TITLE
testRotateVectorMatrix segfaults on drake005

### ISSUE THREAD

**Issue by RussTedrake** [RobotLocomotion/drake#1397]
reliably
http://kobol.csail.mit.edu/cd/testSummary.php?project=1&name=solvers/BMI/util/test/testRotateVectorMatrix&date=2015-10-06

**Comment by jwnimmer-tri** [comment]
Closing as won't-fix, because #6369 will be removing the relevant software.

If I'm confused and this should in fact stay open, please re-open an clarify the remaining unsolved problem(s) in a new comment here.
