### ISSUE TITLE
Emitting latex code from symbolic expression / formula

### ISSUE THREAD

**Issue by soonho-tri** [RobotLocomotion/drake#14002]
Motivation: https://github.com/connorferster/handcalcs

Scope: throw an exception when an expression or a formula include `if_then_else` expressions in it.

@jwnimmer-tri 's suggestion: "I guess maybe nice (and simple enough) to have as a member method, though."

**Comment by RussTedrake** [comment]
We now have ToLatex available for Expression/Formula
