### ISSUE TITLE
pydrake: Should write docs to prescribe copy constructor stuff

### ISSUE THREAD

**Issue by EricCousineau-TRI** [RobotLocomotion/drake#14012]
Relates #14010

**Comment by jwnimmer-tri** [comment]
Maybe the answer is that `DefCopyAndDeepCopy` should _also_ bind `__init__(other: Class)` unconditionally?  It seems like something we should de-boilerplate.  Or at least, skipping the binding of the constructor should be opt-out?

**Comment by EricCousineau-TRI** [comment]
Came up again in Slack: https://drakedevelopers.slack.com/archives/C3YB3EV5W/p1604527861050100
