### ISSUE TITLE
Updated CI images for bazel 3.5

### ISSUE THREAD

**Issue by jwnimmer-tri** [RobotLocomotion/drake#14019]
Per #14005 we have a new bazel in the base image.  Please update at least the Ubuntu AMIs to match.  (The macOS unprovisioned are testing 3.5 already.)

**Comment by BetsyMcPhail** [comment]
Ubuntu (focal and bionic) and Mac (catalina and mojave) AMIs have been updated. Jenkins is using the new AMIS
