### ISSUE TITLE
_collect_cc_header_info does not distinguish between headers that appear in hdrs, textual_hdrs, and srcs

### ISSUE THREAD

**Issue by jamiesnape** [RobotLocomotion/drake#14034]
Relates https://github.com/RobotLocomotion/drake/pull/14003#pullrequestreview-484190779. Relevant to `//common:symbolic`.

**Comment by jwnimmer-tri** [comment]
The victory condition here is removing this code wart:

https://github.com/RobotLocomotion/drake/blob/2de3580f2e2e9b29089a8658806607d1dacfad5a/tools/skylark/pybind.bzl#L377-L378

**Comment by jwnimmer-tri** [comment]
Given that in the past few years we've only had this _one_ instance of this problem, I think fixing this wart is not worth our time.  Closing as "won't fix".  The TODO can stay in the code as a reminder of the wart.  If we grow more warts, we can re-open.
