### ISSUE TITLE
Cannot (yet) use RenderEngineVTK on Colab

### ISSUE THREAD

**Issue by RussTedrake** [RobotLocomotion/drake#14056]
My simple test notebook
https://colab.research.google.com/github/RussTedrake/manipulation/blob/master/pose.ipynb
is crashing... seemingly because it is trying to open a window with a bad X server connection? 

![image](https://user-images.githubusercontent.com/6442292/93025659-bb6ff980-f5cd-11ea-9ff1-16751009082a.png)

Note that I *am* passing `show_window=False` into the `RgbdSensor` constructor, and I don't see any windows open when I run this locally.  I believe we've addressed these issues for running headless before.  Is there a magic incantation that I am missing?

**Comment by jwnimmer-tri** [comment]
For reference, both Drake CI and Anzu CI provide a `DISPLAY` variable that works.

Anzu CI uses a real xorg server with GPU hardware.

Drake CI does this:
- https://github.com/RobotLocomotion/drake-ci/blob/f34fb0054aa50edc40fbae3a907c85651d6da8ce/setup/ubuntu/install_prereqs#L78-L87
- https://github.com/RobotLocomotion/drake-ci/blob/f34fb0054aa50edc40fbae3a907c85651d6da8ce/driver/platform.cmake#L59-L61

Some tests require DISPLAY, even though nothing opens a window.

I'm not sure if there is a way to use the renderer without X.  Maybe with mesa something.  You should be able to test locally by unsetting DISPLAY and seeing the same result.

**Comment by RussTedrake** [comment]
This looks promising.  https://colab.research.google.com/github/tensorflow/lucid/blob/master/notebooks/differentiable-parameterizations/appendix/colab_gl.ipynb

**Comment by RussTedrake** [comment]
It looks like I should be able to use xvfb.  https://colab.research.google.com/drive/1flu31ulJlgiRL1dnN2ir8wGh9p7Zij2t .  Am giving that a spin now.

**Comment by RussTedrake** [comment]
Woot!  That's solved it.  Thanks @jwnimmer-tri !

**Comment by mudamuda-can** [comment]
https://www.programmersought.com/article/42158925287/
