### ISSUE TITLE
fishy-looking math in AutoDiffScalar atan()

### ISSUE THREAD

**Issue by rpoyner-tri** [RobotLocomotion/drake#14051]
Questions were raised in the context of #14045 about the details of the math implementing atan() for AutoDiffXd. I couldn't answer without a bit of history, and some way to evaluate the alternatives. This issue is to track that follow-up.

Comments:
https://github.com/RobotLocomotion/drake/pull/14045#pullrequestreview-487016357
and 
https://github.com/RobotLocomotion/drake/pull/14045#pullrequestreview-487052140

**Comment by sherm1** [comment]
Assigned to @mitiguy for a look. Can you tell if the Eigen atan/asin/etc derivatives are correct for all scalar types? The implementations seem inconsistent.

**Comment by jwnimmer-tri** [comment]
The file in that review is only used with `Scalar = double`.  Was the code suspicious in even with doubles?

**Comment by sherm1** [comment]
> The file in that review is only used with Scalar = double. Was the code suspicious when only used with doubles?

No, I think it is just inconsistently implemented in that case.

**Comment by jwnimmer-tri** [comment]
So @rpoyner-tri how about you change `atan` to use `abs2` for consistency, and then call it a day?  Or else decide we don't care and close the issue.  Either way, this is not worth lingering around.

**Comment by sherm1** [comment]
Per discussion in #16075 I believe the implementation with abs2() is incorrect, though the error would only be apparent for complex numbers. Other uses of abs2() there also seem wrong to me. If we want consistency, we should fix the ones that use abs2() to use plain old square instead of absolute square.
