### ISSUE TITLE
__init__.py installed directly into /opt/drake/lib/pythonX.Y/site-packages

### ISSUE THREAD

**Issue by jamiesnape** [RobotLocomotion/drake#14118]
Does not seem right... Contents are `# Empty Python module __init__, required to make this a module.` which narrows the possibilities down to seven files, I think.

FYI @EricCousineau-TRI

**Comment by EricCousineau-TRI** [comment]
Aye. Perhaps an easy debugging step is to teach `install.py.in` to annotate the files somehow.
e.g. "if it ends with `.py`, inject source location", or just "add `{file}.meta.txt` which indicates where it comes from".

**Comment by jamiesnape** [comment]
I would put a fair amount of money on it being `lcmtypes/__init__.py`.

**Comment by jwnimmer-tri** [comment]
Yes, I added a debug print and I see `-- Installing: lcmtypes/__init__.py to /home/jwnimmer/tmp/bung/lib/python3.6/site-packages/__init__.py`.
