### ISSUE TITLE
provide fastqp (especially for solveLCP) even if gurobi is not present

### ISSUE THREAD

**Issue by RussTedrake** [RobotLocomotion/drake#1415]
not everyone has gurobi, and we could pick a more portable fallback.

**Comment by Lucy-tri** [comment]
@ggould-tri should I prioritize this lower than the C++ trajectory optimization work (pendulum, DircolTrajectoryOptimization)?

**Comment by ggould-tri** [comment]
Yes.  Right now non-emergency issues are a lower priority than current
development.  That may change as we staff up, but not before you are likely
to be done with pendulum anyway.

On Tue, Jun 7, 2016 at 10:11 AM, Lucy <notifications@github.com> wrote:

> @ggould-tri <https://github.com/ggould-tri> should I prioritize this
> lower than the C++ trajectory optimization work (pendulum,
> DircolTrajectoryOptimization)?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/RobotLocomotion/drake/issues/1415#issuecomment-224292546>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AQx__dXeKILkiw2Xyb2hxqrpqea3FeTgks5qJXwZgaJpZM4GMjUl>
> .
>



-- 
Grant Gould
Toyota Research Institute

**Comment by amcastro-tri** [comment]
This is great! I just talked to Russ' students this morning just about this. And we even made a little test calling fastQP but of course it failed. It'd be super useful to have that working. Right now Matlab calls fastQP and only if it fails it calls the Gurobi solver.

**Comment by RussTedrake** [comment]
mathematical program has this soundly resolved going forward (would fallback to snopt).  still have to finish porting fastQP, but will close this particular issue.
