### ISSUE TITLE
testIKtraj and testKinCnst can timeout on the build servers

### ISSUE THREAD

**Issue by RussTedrake** [RobotLocomotion/drake#1418]
this could just be a slow test, but it could also be a crash that is reporting badly.  we need to resolve. 

http://drake005.csail.mit.edu/drake/pull-RussTedrake-win32-into-RobotLocomotion-master_20151010-2310-Continuous

<matlab_test>strcmp(error_id,'timeout') && (strcmp(test_name,'systems/plants/test/testIKtraj') || strcmp(test_name,'systems/plants/constraint/test/testKinCnst'))</matlab_test>

**Comment by RussTedrake** [comment]
http://drake004.csail.mit.edu/drake/pull-gizatt-gizatt_signed_dist-into-RobotLocomotion-master_20160122-0338-Continuous

**Comment by RussTedrake** [comment]
tests are still failing:
http://drake005.csail.mit.edu/drake/pull-henryhwu-fix-1652-into-RobotLocomotion-master_20160126-1206-Continuous

**Comment by hongkai-dai** [comment]
But on CDash, `testIKtraj` passes without timing problem. `testBMI` fails with a segmentation fault. http://kobol.csail.mit.edu/cd/viewTest.php?buildid=20322
