### ISSUE TITLE
Use convex hull approximation as default collision geometry for mesh files

### ISSUE THREAD

**Issue by RussTedrake** [RobotLocomotion/drake#14197]
I am following up on the discussion from [stackoverflow](https://stackoverflow.com/questions/64196799/mesh-based-collision-geometry-in-drake).  I believe that the fact that, by default, specifying a mesh file as a collision geometry results in NO collision geometry represents a *major* usability issue.  For newcomers, they immediately get a bad impression of our dynamics engine.  For experts, it’s a serious limitation to have to curate the collision geometry ourselves.

@sherm1 suggested that bullet is likely using the convex hull.  Browsing the bullet source code quickly, this seems likely, (and I’ve heard the same sentiment from a number of people) but I haven’t officially confirmed that.

Is there any reason why we shouldn’t compute the convex hull and use it as the default collision geometry (printing a warning to the log)?

**Comment by avalenzu** [comment]
+1 from me. That's the behavior we used to have when we used Bullet.

**Comment by SeanCurtis-TRI** [comment]
Agreed. W.r.t. bullet, we got the convex hull for free (buried inside the Bullet API). We don't have that anymore. Now we need to compute the hull ourselves in Drake.

Suggestions for libraries with compatible licenses? Qhull?

**Comment by SeanCurtis-TRI** [comment]
Actually, if we're willing to take a performance hit, I believe there's a way in which we *could* move forward without increasing our external dependencies. I'll have to ponder it.

**Comment by sherm1** [comment]
The Bullet license is compatible with Drake's so we could extract the convex hull code from there if that makes sense.

**Comment by SeanCurtis-TRI** [comment]
It may not compute the convex hull directly. It may have an on-the-fly representation of the convex hull based on the set of vertices that are compatible with its GJK representation.

**Comment by avalenzu** [comment]
@SeanCurtis-TRI is correct. We just fed the vertices of the mesh into their GJK API, which gave us signed distances to the convex hull of those points.

**Comment by RussTedrake** [comment]
I'm going to upgrade this to high priority, as I've had about 5 more questions / comments about it from very different user groups since the issue was opening.  It is proving to be a major pain point for users.
