### ISSUE TITLE
cmake build type is needlessly case sensitive

### ISSUE THREAD

**Issue by edrumwri** [RobotLocomotion/drake#14238]
Drake is the only library I have seen do this: if the build type is not "Debug", "Release", "RelWithDebInfo", etc., the build fails, e.g.:

```
drum @ caesar ~/drake/build
└─ $ ▶ cmake .. -DCMAKE_BUILD_TYPE=debug
CMake Warning at CMakeLists.txt:190 (message):
  Configuration debug is NOT supported


-- Configuring done
-- Generating done
-- Build files have been written to: /home/drum/drake/build
```

**Comment by jwnimmer-tri** [comment]
I found https://cmake.org/cmake/help/v3.22/manual/cmake-buildsystem.7.html#build-configurations which explains that sometimes the value will be case-sensitive, and sometimes it will be case-insensitive.  The general idea in that document _seemed_ to be that in the case of Drake, we should be treating our use of this variable as case-insensitive.
