### ISSUE TITLE
Create missing method Multibody::CalcCenterOfMassTranslationalVelocity()

### ISSUE THREAD

**Issue by mitiguy** [RobotLocomotion/drake#14268]
Vector3\<T\> CalcCenterOfMassTranslationalVelocityInWorld(const systems::Context\<T\>& context) const;  and/or
Vector3\<T\> CalcCenterOfMassTranslationalVelocity(const systems::Context\<T\>& context,  
                                                   const Frame\<T\>& frame_A, const Frame\<T\>& frame_E) const;
---------------------------------------------------------------------------------------------
Note: Two related MultibodyPlant methods are:
Vector3\<T\> CalcCenterOfMassPosition(const systems::Context\<T\>& context) const;
Vector3\<T\> CalcCenterOfMassPosition(const systems::Context\<T\>& context,
      const std::vector<ModelInstanceIndex>& model_instances) const;
---------------------------------------------------------------------------------------------
Note:  PR# #12839 added a similar multibodyPlant method with signature:
void CalcJacobianCenterOfMassTranslationalVelocity( const systems::Context\<T\>& context, 
      JacobianWrtVariable with_respect_to,  const Frame\<T\>& frame_A, const Frame\<T\>& frame_E,
      EigenPtr\<Matrix3X\<T\>\> Js_v_ACcm_E) const;

**Comment by mitiguy** [comment]
PR #14297 should resolve issue #14268.

**Comment by mitiguy** [comment]
@amcastro-tri, @sherm1 @joemasterjohn 
It would be helpful to get your input on the API design for CalcCenterOfMassTranslationalVelocity...
The choice for this API will also affect the API for upcoming method CalcCenterOfMassTranslationalAcceleration...

Some possible options for the API:

Vector3\<T\> CalcCenterOfMassTranslationalVelocityInWorld(const systems::Context\<T\>& context) const; 

Vector3\<T\> CalcCenterOfMassTranslationalVelocity(const systems::Context\<T\>& context,  
                                                   const Frame\<T\>& frame_A, const Frame\<T\>& frame_E) const;

OR YOUR SUGGESTION

Reminder of related APIs that are currently in Drake (which can be changed if needed).
Vector3<T> CalcCenterOfMassPosition(const systems::Context<T>& context) const;

void CalcJacobianCenterOfMassTranslationalVelocity( const systems::Context<T>& context,
JacobianWrtVariable with_respect_to, const Frame<T>& frame_A, const Frame<T>& frame_E,
EigenPtr<Matrix3X<T>> Js_v_ACcm_E) const;

**Comment by sherm1** [comment]
My favorite API set:
```c++
Vector3 CalcCenterOfMassPositionInWorld(const systems::Context& context) const;
Vector3 CalcCenterOfMassVelocityInWorld(const systems::Context& context) const;
Vector3 CalcCenterOfMassAccelerationInWorld(const systems::Context& context) const;
```
I don't think we need to provide results in any other frame since (a) hard to imagine why anyone would want that, and (b) if they do we can just point them to the existing shift and re-express methods. Also, the "InWorld" suffix leaves open the possibility of adding more-general methods if needed.

It might also be necessary for performance reasons to provide combined methods like CalcCenterOfMassPositionAndVelocity() since those can be made much faster than calls to separate methods. I would not advocate doing that now, though!

**Comment by amcastro-tri** [comment]
I like @sherm1's proposal. It is very true that most likely no one will want those quantities in any other frame than the world frame. 
The world signatures look concise and clean.

**Comment by joemasterjohn** [comment]
I defer to @sherm1 and @amcastro-tri on the API design. Since the current PR (#14297) is already using:
```
Vector3<T> CalcCenterOfMassTranslationalVelocity(const systems::Context<T>& context,
const Frame<T>& frame_A, const Frame<T>& frame_E) const;
```
an option would be to make that method private (with the option to make it a public API later) and have the public method use it.
Not sure of the usefulness at this point.

**Comment by joemasterjohn** [comment]
Actually sorry my bad, you don't have to make any private member functions on `MultibodyPlant`. Since the plant method is just calling the underlying implementation in `MultibodyTree`, you can just change the public plant API and leave the tree API as is.

**Comment by sherm1** [comment]
Although ... we would then have unused (and potentially untested) extra complexity in MBTree which would then lead either to similar unused complexity for CoMTranslationalAcceleration or an incompatibility between Velocity and Acceleration MBTree APIs. I don't think "sunk cost" is a good reason to keep the extra code around if we don't have any other reason to do so.

**Comment by mitiguy** [comment]
I think the conversation has converged to the following public API.
Let me know if this is incorrect.

Vector3\<T\> CalcCenterOfMassPositionInWorld(const systems::Context& context) const;
Vector3 \<T\> CalcCenterOfMassVelocityInWorld(const systems::Context& context) const;
Vector3\<T\>  CalcCenterOfMassAccelerationInWorld(const systems::Context& context) const;

Vector3\<T\> CalcCenterOfMassPositionInWorld(const systems::Context<T>& context,
const std::vector& model_instances) const;
Vector3\<T\> CalcCenterOfMassVelocityInWorld(const systems::Context<T>& context,
const std::vector& model_instances) const;
Vector3\<T\> CalcCenterOfMassAccelerationInWorld(const systems::Context<T>& context,
const std::vector& model_instances) const;

Note: I assume I/we will eventually deprecate the following:
Vector3\<T\> CalcCenterOfMassPosition(const systems::Context& context) const;
Vector3\<T\> CalcCenterOfMassPosition(const systems::Context<T>& context,
const std::vector& model_instances) const;

**Comment by sherm1** [comment]
Looks great. I would suggest deprecating CalcCenterOfMassPosition() in the same PR in favor of CalcCenterOfMassPositionInWorld() to avoid ever having two names for the same thing.

**Comment by mitiguy** [comment]
Resolved as PR# 14354 merged with methods and test for MultibodyPlant::CalcCenterOfMassTranslationalVelocityInWorld().
Will open a new issue to deal with Sherm's suggestion to deprecate CalcCenterOfMassPosition() in favor of CalcCenterOfMassPositionInWorld() (avoid having two names for the same thing).

**Comment by mitiguy** [comment]
Specifically, created issue #14537 and PR# 14538 to deprecate CalcCenterOfMassPosition() in favor of CalcCenterOfMassPositionInWorld().
