### ISSUE TITLE
URDF files from Solidworks cause trouble like on Gazebo?

### ISSUE THREAD

**Issue by renanmb** [RobotLocomotion/drake#14262]
Exporting URDFs Directly From Solidworks
https://youtu.be/Uz6KPJBfM1s

My question is to know if this does apply to 100% of the cases?
Is there any perspective into working closer to Solidworks so we can import complex designs without having to polish every URDF files one by one?

This is the major draw back trying to increase productivity in ROS.

**Comment by jwnimmer-tri** [comment]
Hi @renanmb.  We use our issues database for bug reports and feature requests.  For assistance and questions, please post your topic to StackOverflow instead [1].  (The Drake new-issue template cites https://drake.mit.edu/getting_help.html#asking-your-question, which has more details.)

[1] https://stackoverflow.com/questions/ask?tags=drake
