### ISSUE TITLE
Remove documentation only prerequisites from provisioned images

### ISSUE THREAD

**Issue by jamiesnape** [RobotLocomotion/drake#14310]
i.e., anything that is only installed when the `--with-doc-only` flag is passed to the prerequisite scripts.

Relates #13832. Depends on #14168.

**Comment by jwnimmer-tri** [comment]
Given some slack discussions last week, I wonder if this already got completed, perhaps?

**Comment by jamiesnape** [comment]
Ideally we would have scratch and re-provisioned without any doc flags, but a band-aid was applied instead and it looks like we got everything meaningful off the image. So while not perfect, it is probably good enough to close this issue.
