### ISSUE TITLE
precompiled on win32 is missing lcm

### ISSUE THREAD

**Issue by RussTedrake** [RobotLocomotion/drake#1431]
@psiorx -- was that intentional?  i think it should all work.

**Comment by psiorx** [comment]
Looks like it's explicitly turned off in the top-level CMakeLists.txt:

```CMAKE
if (WIN32)
   if (CMAKE_SIZEOF_VOID_P EQUAL 8)  # gtk only compiles on win64 right now
	option(WITH_LCM 		"interprocess communications protocol for visualizers, etc" ON)
    ...
```

I'm experimenting with turning it back on.

**Comment by RussTedrake** [comment]
Oh yes - i had forgotten that

**Comment by RussTedrake** [comment]
related to #1715 and #1760

**Comment by RussTedrake** [comment]
closing in anticipation of #1766
