### ISSUE TITLE
Yaml serialization of templated variant types fails (emits invalid yaml)

### ISSUE THREAD

**Issue by ggould-tri** [RobotLocomotion/drake#14322]
`YamlWriteArchive` serialization of `std::optional<DistributionVectorVariantX>`'s `DeterministicVector` arm emits invalid yaml consisting only of the type tag and without the value.

See the following additional test case: [demonstrate_stochastic_optional_fail](https://github.com/RobotLocomotion/drake/compare/master...ggould-tri:demonstrate_stochastic_optional_fail#diff-b2d63c15aa78ba9735ccd7bc49429dac220c82a4bf34361c1f717fdfa5815074R432-R446)

That test emits the failure:
```
common/schema/test/stochastic_test.cc:445: Failure
Expected equality of these values:
  writer.EmitString()
    Which is: "root:\n  optional_dist_vec: !DeterministicVector\n"
  R"""(root:
  optional_dist_vec: !DeterministicVector { value: [ 1.0, 2.0 ] }
)"""
    Which is: "root:\n  optional_dist_vec: !DeterministicVector { value: [ 1.0, 2.0 ] }\n"
With diff:
@@ -1,2 +1,2 @@
 root:
-  optional_dist_vec: !DeterministicVector\n
+  optional_dist_vec: !DeterministicVector { value: [ 1.0, 2.0 ] }\n

[  FAILED  ] StochasticTest.OptionalTest (2 ms)
```
As you can see, the emitted yaml for the variant element is just the string `!DeterministicVector` with no further content.

FYI @jwnimmer-tri

**Comment by ggould-tri** [comment]
From local experimentation, I am finding that if I add another element after the variant it is not serialized at all, leading me to suspect that the writer is taking an early return between emitting the tag and its content rather than simply mis-serializing this structure.

**Comment by ggould-tri** [comment]
Jeremy:  Assigning this to you as the SME; feel free to assign it back to me if you get overloaded.  I'm not blocked on this, although the behaviour is somewhat worrisome.

**Comment by jwnimmer-tri** [comment]
The bug relates to having `DeterministicVector<-1>` as the tag.  When reading YAML, we discard the template argument while comparing types.  While writing, we fail to strip the template argument from the tag.  And, for some reason, writing a `<` in a tag name makes yaml lose its mind.  I'll work up a patch.
