### ISSUE TITLE
Withdrawing macOS Mojave (10.14) support

### ISSUE THREAD

**Issue by jwnimmer-tri** [RobotLocomotion/drake#14328]
We are planning on dropping support for macOS Mojave (10.14) support in future releases.

Our usual policy is to keep N, N-1 versions alive for macOS -- so the most recent Apple release, and the one immediately prior.

With Big Sur on the way (#13648) it's time to drop Mojave to make room for it.

**Comment by jamiesnape** [comment]
No complaints so far here and I just checked that all our system dependencies are happy with Big Sur (`bazel` and `scipy` protested somewhat, but are good now), so I would propose we start disabling the CI jobs for Mojave this afternoon.

**Comment by jwnimmer-tri** [comment]
SGTM.  We should also do a doc/developers.rst update to go along with that.
