### ISSUE TITLE
Refactor code to geometry/proximity:meshing_utilities

### ISSUE THREAD

**Issue by DamrongGuoy** [RobotLocomotion/drake#14332]
I'd like to create a new library `geometry/proximity:meshing_utilities` in the `internal` namespace. It will contain functions that are called by mesh generators in the Make\*Mesh\*() family and their corresponding unit tests. An incomplete list of functions that will be moved into `meshing_utilities` is:

- CountEdges()
- CountFaces()
- ComputeEulerCharacteristic()
- IsTetrahedronRespectingMa()
- SplitToTetrahedra()

This issue is not urgent.  As a first step, I'll create this new library with only one function SplitToTetrahedra().  It is a part of my ongoing development for MakeCylinderVolumeMeshWithMa() that will share this function with the existing MakeBoxVolumeMeshWithMa().

CC: @SeanCurtis-TRI , @amcastro-tri , @joemasterjohn .

**Comment by SeanCurtis-TRI** [comment]
If all of these are related to volume meshes, it might be worth about thinking of a more targeted name. We have a number of mesh-related activities (parsing objs for proximity `Convex` shapes and rendering, generating surface meshes for rendering, etc.) I fear that "meshing" may be too generic.
