### ISSUE TITLE
multibody: GetBodiesWeldedTo doesn't survive scalar conversion

### ISSUE THREAD

**Issue by EricCousineau-TRI** [RobotLocomotion/drake#14346]
In writing #14345, found that `plant_ad.GetBodiesWeldedTo()` fails with something like this:
```
C++ exception with description "Failure at multibody/topology/multibody_graph.cc:240 in FindBodiesWeldedTo(): condition 'body_index.is_valid() && body_index < num_bodies()' failed." thrown in the test body.
```

Prolly just some topology stuff that needs copying?

Assigning @sherm1 for disposition

\cc @amcastro-tri

**Comment by EricCousineau-TRI** [comment]
For now, captured it in a test:
https://github.com/RobotLocomotion/drake/blob/3bcaaf5d733abdfe9329baa2e5c10954626ac4ca/multibody/plant/test/multibody_plant_test.cc#L1387-L1393

**Comment by sherm1** [comment]
Yikes -- that's scary. @joemasterjohn, can you look at this one also -- more stuff not surviving ToAutoDiff()?
