### ISSUE TITLE
Cmake install prefix can get set to /usr/local

### ISSUE THREAD

**Issue by rdeits** [RobotLocomotion/drake#1438]
I'm not sure exactly how this happened, but my `cmake_install_prefix` on Linux has flipped itself to `/usr/local/`. The top-level drake CMakeLists checks `CMAKE_INSTALL_PREFIX_INITIALIZED_TO_DEFAULT`, which appears to be false in my case, even though the install prefix is, in fact, set to the default. 

There appears to be *intentionally* no documentation for that flag: http://cmake.3232098.n2.nabble.com/Documentation-for-CMAKE-INSTALL-PREFIX-INITIALIZED-TO-DEFAULT-missing-td6096818.html

The `pod-build/CMakeCache` does in fact show:

```
CMAKE_INSTALL_PREFIX:PATH=/usr/local
```

but I'm not sure how this could have happened. Deleting that line from `pod-build/CMakeCache.txt` fixed the problem. 

There may not be a resolution, but I wanted to open this issue anyway in case others see this problem too.

**Comment by RussTedrake** [comment]
thanks.  i did see this once when I was updating the logic, but convinced myself it was only a problem with the cache already being set.  Pretty sure a clean make will always do the right thing.
