### ISSUE TITLE
Upgrade Mosek to 9.2

### ISSUE THREAD

**Issue by hongkai-dai** [RobotLocomotion/drake#14386]
Drake currently supports Mosek 9.0. Unfortunately there is a bug in the Mosek 9.0 upstream code, that we exposed in the PR #14383. We should upgrade our supported version to Mosek 9.2 (and also upgrade the TRI mosek license server).

**Comment by jamiesnape** [comment]
I suspect the license that we use on Drake CI is going to be fine for 9.2, but I have not explicitly checked.

**Comment by hongkai-dai** [comment]
Yes Drake CI license is different from TRI Mosek license. I think if we upgrade Drake Mosek now, then none of the TRI user can continue to use Mosek through Drake.

The IE team at TRI is working on upgrading the Mosek license.
