### ISSUE TITLE
pydrake bazel: How to get a stacktrace in debug mode?

### ISSUE THREAD

**Issue by EricCousineau-TRI** [RobotLocomotion/drake#14381]
@sloretz is trying to debug some stuff here:
https://github.com/sloretz/drake_ros2_demos/pull/3

I thought #14356 would've fixed it, but possibly not.

He's trying to debug, but can't easily find the point in Drake C++ / pybind11 code where things go awry.

For now, he's trying out the `@traced` macro from here: 
https://drake.mit.edu/python_bindings.html#debugging-with-the-python-bindings

I am assuming the our `cmake -DCMAKE_BUILD_TYPE=Debug` command isn't doing anything more special than `-c dbg` for Bazel; but we shall see...

**Comment by EricCousineau-TRI** [comment]
See example trying to get a stack trace in #14380 

Commit: b99ff10d6b
Command:
```
cd drake
bazel run -c dbg //:install -- ${PWD}/build
python_path=$(ls -d ~+/build/lib/python*/site-packages)
env -i PYTHONPATH=${python_path} /usr/bin/python3 -c 'import pydrake.common._module_py._testing as m; m.trigger_segfault()'
```

Triggers a segfault. `coredumpctl gdb` doesn't seem to turn up anything useful (says there's no stacktrace).

Running it under GDB also doesn't seem to yield useful symbols:
```
env -i PYTHONPATH=${python_path} gdb --ex run --args /usr/bin/python3 -c 'import pydrake.common._module_py._testing as m; m.trigger_segfault()'
```

**Comment by EricCousineau-TRI** [comment]
Using `python3-dbg` doesn't seem to turn up anything more fruitful in terms of Drake.
(Python, however, shows it all)

**Comment by EricCousineau-TRI** [comment]
Naively trying out CMake per our docs:
```
cd drake
mkdir build_cmake && cd build_cmake
cmake .. -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=${PWD}/install
```

**Comment by EricCousineau-TRI** [comment]
From my comment in Slack:

> The killer combo with debugging is:
> 
> - Use `@traced` (and the no-buffered-output)
> - Use gdb backtrace
> - Also tell Drake to set it's spdlog level: https://drake.mit.edu/pydrake/pydrake.common.html#pydrake.common.set_log_level
> ```from pydrake.common import set_log_level
> set_log_level("trace")```
> Then it should be obvious how things playout

**Comment by EricCousineau-TRI** [comment]
I (or someone else ;) should PR that to Drake docs.

**Comment by EricCousineau-TRI** [comment]
Efff... I was the one who sprinkled that sauce in :facepalm: 
https://github.com/RobotLocomotion/drake/commit/ea1b198a7cf52e737dde20b43ae95bf7d9ed4844 (#10103)

**Comment by pathammer** [comment]
@EricCousineau-TRI  Is there any way to intercept the [Bazel strip option](https://bazel.build/docs/user-manual#strip) which seems a lot more intuitive?

**Comment by EricCousineau-TRI** [comment]
Yup, good idea! Perhaps there's a way to extract that from cc toolchain information.
Unfortunately, though, it's unlikely I will have time to focus on it anytime soon.

Just to check, is this something that impacted your workflow?

**Comment by pathammer** [comment]
I lost a day trying to build libdrake with debug symbols before seeing this `--no_strip` option on the installer 😥.
I can file an improvement ticket?

**Comment by EricCousineau-TRI** [comment]
Ah, sorry to hear that, and yup, that'd be best!

**Comment by richardrl** [comment]
> * set_log_level

traced is indeed awesome. I also built with no_strp and I'm getting a stacktrace now.

set_log_level is no longer present in current drake, what is the equivalent of set_log_level("trace") now?

**Comment by richardrl** [comment]
> From my comment in Slack:
> 
> > The killer combo with debugging is:
> > 
> > * Use `@traced` and `reexecute_if_unbuffered`
> > * Use gdb backtrace
> > * Also tell Drake to set it's spdlog level: https://drake.mit.edu/pydrake/pydrake.common.html#pydrake.common.set_log_level
> > 
> > ```
> > from pydrake.common import set_log_level
> > set_log_level("trace")
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Then it should be obvious how things playout

traced is indeed awesome. I also built with no_strp and I'm getting a stacktrace now.

set_log_level is no longer present in current drake, what is the equivalent of set_log_level("trace") now?
