### ISSUE TITLE
Error running make

### ISSUE THREAD

**Issue by itsamk** [RobotLocomotion/drake#1441]
![capture44](https://cloud.githubusercontent.com/assets/13022431/10710227/f9390932-7a03-11e5-9c74-8746b2217558.JPG)

I am installing drake on a windows machine and I have been trying to install it for a long time now but always get stuck in one problem or the other. I formatted my system and then retried installing it. But, I started getting this problem. I hope someone could help me fix this so, I can continue using drake. (It has literally been months)

**Comment by RussTedrake** [comment]
What happens if you manually run the cmake-gui command from the makefile on your command line?

**Comment by itsamk** [comment]
I get the c-make GUI. What to set as source of the code and destination of binaries?

**Comment by RussTedrake** [comment]
If it is launched correctly, those should be set for you.  Maybe the problem was earlier in the make file for you.  How about running make options but with the debug flags set?

**Comment by itsamk** [comment]
![capture45](https://cloud.githubusercontent.com/assets/13022431/10710939/e8372df4-7a20-11e5-85ab-82da111f0b4d.JPG)


I ran 'make options -d' and this was the output.

**Comment by RussTedrake** [comment]
You didn't run it from the correct directory. 

Have you tried the precompiled versions?

**Comment by itsamk** [comment]
The precompiled version worked like a charm! :) Thanks!
