### ISSUE TITLE
Manipulator.dynamics() should make sure v was passed in

### ISSUE THREAD

**Issue by rdeits** [RobotLocomotion/drake#1442]
From Piazza:

Calling `dynamics()` on a Manipulator with `x = q` (instead of `x = [q; qdot]`) results in an unhelpful error:

```
Unexpected Standard exception from MEX file.
What() is:inverseDynamics requires velocity kinematics, which have not been cached. Please
call doKinematics with a velocity vector.
..

Error in RigidBodyManipulator/manipulatorDynamics (line 44)
    C = inverseDynamicsmex(obj.mex_model_ptr, kinsol.mex_ptr, f_ext);

Error in Manipulator/dynamics (line 78)
        [H,C,B] = manipulatorDynamics(obj,q,v);
```

That's because `dynamics()` just does:

```
v = x(obj.num_positions+1:end);
```

which, rather than failing, just sets v to be an empty vector. That results in weird mex file errors later on.

**Comment by jwnimmer-tri** [comment]
Closing as won't-fix, because #6369 will be removing the relevant software.

If I'm confused and this should in fact stay open, please re-open an clarify the remaining unsolved problem(s) in a new comment here.
