### ISSUE TITLE
franka: Mesh textures don't show up in meshcat?

### ISSUE THREAD

**Issue by EricCousineau-TRI** [RobotLocomotion/drake#14423]
Confirmed per Slack comment here:
https://drakedevelopers.slack.com/archives/CMV686ZD4/p1607385364024400

Results on drake @ d258ef193:
*Note*: Due to #14422, I quickly hacked it to include franka:
```
$ cd drake
$ git diff -U1
diff --git a/manipulation/util/BUILD.bazel b/manipulation/util/BUILD.bazel
index 44e6daac85..fb51b75008 100644
--- a/manipulation/util/BUILD.bazel
+++ b/manipulation/util/BUILD.bazel
@@ -113,2 +113,5 @@
     srcs = ["show_model.py"],
+    data = [
+        "//manipulation/models/franka_description:models",
+    ],
     deps = [
```
Running:
```
cd drake
# Terminal 1
bazel run @meshcat_python//:meshcat-server
# Terminal 2
bazel run //tools:drake_visualizer
# Terminal 3
bazel run //manipulation/util:show_model -- --meshcat=default --find_resource drake/manipulation/models/franka_description/urdf/panda_arm.urdf
```

Meshcat (bad):
![image](https://user-images.githubusercontent.com/26719449/101497042-83f8bb00-3938-11eb-9586-02261ef82cfa.png)

Director (good):
![image](https://user-images.githubusercontent.com/26719449/101497062-8bb85f80-3938-11eb-9648-0e287bedb76b.png)

\cc @sherm1 @blandry

**Comment by sherm1** [comment]
cc @rpoyner-tri in case you want to look prior to return of the Geometry King

**Comment by SeanCurtis-TRI** [comment]
I believe @joemasterjohn has agreed to take oversight of meshcat. (Joe, correct me if my memory is failing me.)

**Comment by joemasterjohn** [comment]
I did make a mention of that, but if @rpoyner-tri wants to take a crack at this I don't mind.

**Comment by RussTedrake** [comment]
FYI -- https://github.com/RobotLocomotion/drake/pull/15788 resolves this issue (for meshcat c++, not for meshcat-visualizer in python).

**Comment by SeanCurtis-TRI** [comment]
Closing this as meshcat-python is an evolutionary dead end.
