### ISSUE TITLE
Multibody and System "there is no" exceptions should list valid values

### ISSUE THREAD

**Issue by ggould-tri** [RobotLocomotion/drake#14426]
All of the MBP by-name accessors have exceptions that say "there is no [thingy] named [mumble] in the model."

That's great and all but the only way for a user faced with this error to find out what you might have gotten wrong is to run a debug build, get a stack trace, find the enclosing call, and log the contents of the model right before the call.

The exception should list the available names to save the user from this hunt.

**Comment by sherm1** [comment]
Is the proposal just to append a list of all possible [thingys] that would not have generated an error message?

**Comment by ggould-tri** [comment]
That seems to me the most obvious ("you asked for 'ikea_dinera_plate_8in' but the valid models were 'ikea_dinera_plate_8in_0', 'world', 'default', ...").  But I'd be delighted with other alternatives too, so long as they don't require rebuilding in debug mode to find the failure point and add printfs.
