### ISSUE TITLE
Explain in source instructions that a bash alias to matlab is *not* ok

### ISSUE THREAD

**Issue by rdeits** [RobotLocomotion/drake#1443]
It's possible for a user to define a bash alias `matlab=/usr/local/MATLAB/R2014b/bin/matlab` in their bashrc, but cmake will not detect this as an executable. That means that none of our mex files will be built, causing weird issues (as seen on Piazza). 

We should mention in <https://github.com/RobotLocomotion/drake/wiki/FromSource> that you must have a symlink to matlab, not an alias.

**Comment by rdeits** [comment]
Consider using FindMATLAB.cmake

**Comment by RussTedrake** [comment]
will close this in favor of switching to findmatlab.cmake (e.g. #1998)
