### ISSUE TITLE
Updated CI images for libspdlog-dev

### ISSUE THREAD

**Issue by jwnimmer-tri** [RobotLocomotion/drake#14434]
Per ##14429, we have a new library in the base image. Please update the Ubuntu 20.04 AMIs to match.  (There are no changes to macOS nor Ubuntu 18.04.)

**Comment by jwnimmer-tri** [comment]
@jamiesnape ping?

**Comment by BetsyMcPhail** [comment]
Sorry for the delay, I will do the update this afternoon.

**Comment by BetsyMcPhail** [comment]
Focal AMI and Jenkins have been updated
