### ISSUE TITLE
drake_py_test rules + pydrake creates a confusing failure

### ISSUE THREAD

**Issue by ggould-tri** [RobotLocomotion/drake#14477]
A unit test which imports pydrake transitively inherits an import of unittest via pydrake's import of numpy (`numpy/testing/__init__.py`:10).  It therefore fails the `allow_import_unittest` check.

Of course the caller can work around this by setting the `allow_import_unittest` override, but that defeats the purpose of the check.

The correct resolution of this problen is to switch to `drake_py_unittest`, but there is not a clear path by which a user is likely to figure this out (in f2f conversation Sammy and I both missed this solution); possibly `drake_py_test` should signpost that `drake_py_unittest` is preferred in some of its error messages with "perhaps you meant..." style guidance.

**Comment by ggould-tri** [comment]
(This issue is to allow me to TODO some otherwise defective code for #13904)

**Comment by EricCousineau-TRI** [comment]
Yeah, that's related to how `drake_py_unittest_main.py` is written - it allows users to not need `if __name__ == "__main__"`, but it does weird implicit things. The `import uniitest` shindig is another factoring of that which I believe is excessively conservative.

I have minor stake in this issue (aligning unittests in Drake to be more explicit, like Anzu, but with linting), but i have no bandwidth to tackle it anytime soon. :shrug: 

FWIW I'd label this as "backlog" as it's not really that big of a pain point? Or just close it?

\cc @jwnimmer-tri

**Comment by ggould-tri** [comment]
Yeah, the context here is porting code from anzu.

Since I just TODO'ed to this issue in #14478 I have an interest in not closing it -- IMO we shouldn't close issues that back TODOs.  I'm definitely okay with backlogging it if I'm the only person who cares, though.

**Comment by jwnimmer-tri** [comment]
As I commented in the PR, unit tests should almost never use `drake_py_test`.  Almost all of them should use `drake_py_unittest`, which does not suffer from this problem.  My vote is that this caveat is so rare as to not even merit a backlog issue.  Steady state, we will only have 1 or 2 uses of `drake_py_test` in the tree at any time.

**Comment by jwnimmer-tri** [comment]
Maybe we should pivot this ticket to be "improve the error message for the 'import unittest' diagnostic", to have it provide a link back to the documentation of `drake_py_test` along with better stardoc on that macro explaining that it's only to be used in the 1% rare cases.

**Comment by ggould-tri** [comment]
This is also the view I have come to.  Updating the headline.

**Comment by jwnimmer-tri** [comment]
I don't know what to say, the suggestion to use `drake_py_unittest` to solve the problem seems as clear as day to me:

https://github.com/RobotLocomotion/drake/blob/master/common/test_utilities/disable_python_unittest/unittest/__init__.py

Maybe next time this comes up, we can try to dig into what was confusing.  For now: "not planned".
