### ISSUE TITLE
Add Drake's stardoc to website

### ISSUE THREAD

**Issue by jwnimmer-tri** [RobotLocomotion/drake#14489]
Using https://github.com/bazelbuild/stardoc we can turn our starlark macro documentation into something (hopefully) more easily browsed.  That would be a nice-to-have for the core team to browse, e.g., to cite during code reviews.

Marking as very low priority for now.

**Comment by jamiesnape** [comment]
Tried to make that work with one of Russ's repos. Broken then, but maybe they have fixed it now, six months or so later.

**Comment by jwnimmer-tri** [comment]
Closing out as "backlog unlikely to reach an actionable state within a reasonable timeframe".
