### ISSUE TITLE
precompiled Ubuntu director doesn't work

### ISSUE THREAD

**Issue by rdeits** [RobotLocomotion/drake#1448]
Trying to launch the director with precompiled drake on ubuntu fails looking for `libQVTK.so.5.8`

**Comment by patmarion** [comment]
I don't think the precompiled Ubuntu package includes dependent libraries.  You are expected to satisfy those dependencies with apt-get:

    sudo apt-get install libvtk5-qt4-dev


Please close this issue if that resolves your problem.  We could open a new issue if we think we'd like to modify the precompiled package to include more libraries.
