### ISSUE TITLE
win32 precompiled build (0.9.11) doesn't have an addpath_spotless

### ISSUE THREAD

**Issue by tkoolen** [RobotLocomotion/drake#1449]
as opposed to e.g. the win64 build.

From 6.832x Piazza. Just adding spotless and its subdirectories to the path also didn't work for the user who reported it, and makes me think that spotless didn't compiled either.

@psiorx, did spotless just not get built for the win32 precompiled build?

**Comment by psiorx** [comment]
> did spotless just not get built for the win32 precompiled build? 

Looking into it.

**Comment by tkoolen** [comment]
In any case, we unfortunately need to do a new release of the 32 bit version because this is causing 6.832x people not to be able to complete their problem set.
