### ISSUE TITLE
Mirror to s3 job fails without Sphinx 

### ISSUE THREAD

**Issue by BetsyMcPhail** [RobotLocomotion/drake#14527]
Failing job: https://drake-jenkins.csail.mit.edu/view/Continuous%20Production/job/linux-bionic-gcc-bazel-continuous-mirror-to-s3/1844/

Sphinx was removed from the provisioned images, see [Slack conversation](https://drakedevelopers.slack.com/archives/C270MN28G/p1610478253294000)

To fix the error immediately, this job needs to move to the unprovisioned images but it should not need the documentation prerequisites.

**Comment by BetsyMcPhail** [comment]
pinging @jwnimmer-tri

**Comment by jamiesnape** [comment]
Moved to unprovisioned. I guess there is an edge case where we might want to cache something needed to build documentation, so passing the `--with-doc-only` flag is not necessarily bad, but we should not really need Sphinx, so something is not quite right.
