### ISSUE TITLE
Can't build drake on Windows if path contains spaces

### ISSUE THREAD

**Issue by rdeits** [RobotLocomotion/drake#1458]
Attempting to build drake from within `C:\Users\username\My Documents\drake-distro` or similar fails at this line in pods.cmake: https://github.com/RobotLocomotion/cmake/blob/master/pods.cmake#L59 with an error about how STRIP requires two arguments. Presumably this is because cmake can't distinguish an empty string from a missing variable :wink:

**Comment by billhoffman** [comment]
This should be fixed by the change to the install path to recognize "program files (x86)".  Should be in here: https://github.com/RobotLocomotion/drake/pull/1740

**Comment by david-german-tri** [comment]
Windows is no longer supported.
