### ISSUE TITLE
SimplePulley demos fail without gurobi

### ISSUE THREAD

**Issue by cyndiac** [RobotLocomotion/drake#1459]
At commit 2e5b3fb on Windows; error message says it can't find snopt even though it was checked in the cmake setup; pulleys in SimplePulley and tension fall down to infinity

**Comment by rdeits** [comment]
We've reproduced this in Ubuntu 14.04 as well, but I'm still not sure what's causing it.

**Comment by rdeits** [comment]
On further inspection, it might not be snopt-related. The example fails on a binary windows install and on a basic ubuntu source install. Possibly a precompiled snopt issue?

**Comment by cyndiac** [comment]
Works after installing Gurobi (only tested on Ubuntu machine)

**Comment by rdeits** [comment]
That makes sense: I wasn't able to reproduce this on any of my machines, but they all have systemwide gurobi installs that I've accumulated over time.

**Comment by RussTedrake** [comment]
won’t fix.  (moving to c++)
