### ISSUE TITLE
kinova arm - the default value for number of joints and number of finger is hardcoded

### ISSUE THREAD

**Issue by mpatalberta** [RobotLocomotion/drake#14617]
> Before you post:
drake/manipulation/kinova_jaco
  jaco_constants.h    

/// proper arguments to the system constructors.
constexpr int kJacoDefaultArmNumJoints = 7;
constexpr int kJacoDefaultArmNumFingers = 3;

This is problem for the case of arm that may only have 6 joints and 2 fingers,
Some of the memory allocations use this number directly..
The urdf files needs to be used and read in early and off of that information.

**Comment by sherm1** [comment]
Assigning to @sammy-tri for disposition.

**Comment by jwnimmer-tri** [comment]
I am closing this for the same reasons as #14586 -- this is a feature request we'll have to decline.  The example serves to illustrate one sample application.  Making it more configurable would only serve to obscure its tutorial value.  The example is not intended to be a generic building block for application developers to invoke directly.
