### ISSUE TITLE
MarkovDecisionProcess.discretizeSystem requires that xbins and ubins is sorted

### ISSUE THREAD

**Issue by vtjeng** [RobotLocomotion/drake#1465]
### Recommendations

  + `MarkovDecisionProcess.discretizeSystem` should document that it requires `xbins` and `ubins` to be sorted.
  + We should modify the following [section of code](https://github.com/RobotLocomotion/drake/blob/b3a6fb9f8b783a94fa69470744750a6f965e153d/drake/systems/MarkovDecisionProcess.m#L103-L104), as outlined below

### In Detail
The following [section of code](https://github.com/RobotLocomotion/drake/blob/b3a6fb9f8b783a94fa69470744750a6f965e153d/drake/systems/MarkovDecisionProcess.m#L103-L104) implicitly assumes that each of the `xbins` has its minimum value as its first element and the maximum value as its final element.

While this can be corrected (and made more readable) by changing the code to determine `xmin` and `xmax`:

      xmin = reshape(cellfun(@(a) min(a),xbins),[],1);
      xmax = reshape(cellfun(@(a) max(a),xbins),[],1);

The code still does not behave sensibly when you pass in an unsorted array as one of the `xbins`. 

For instance, when replacing the first `xbin` in this [line](https://github.com/RobotLocomotion/drake/blob/b3a6fb9f8b783a94fa69470744750a6f965e153d/drake/examples/Pendulum/runValueIteration.m#L9) in `Pendulum/runValueIteration` with its equivalent unsorted counterpart

     % xbins = {linspace(0,2*pi,51),linspace(-10,10,51)};
     xbins = {[linspace(0,pi-3*pi/25,25),[pi, pi-pi/25, pi-2*pi/25], linspace(pi+pi/25,2*pi, 25)], linspace(-10, 10, 51)};

The plots of `u(x)` and `J(x)` are visibly different (and also have incorrect x-limits due to the behaviour of `imagesc`).

Here is a sample of the plotted results of the original bins and original code at convergence.

![mdp_original_bins_original_code](https://cloud.githubusercontent.com/assets/5932817/11350037/90732a42-91fd-11e5-89a1-5cb5b1d177b6.png)

Here is a sample of the plotted results of the unsorted bins and original code close to convergence.

![mdp_unsorted_bins_original_code](https://cloud.githubusercontent.com/assets/5932817/11350235/890412f2-91fe-11e5-949e-346dc17c6908.png)

Here is a sample of the plotted results of the unsorted bins and modified code (with correct determination of `xmin` and `xmax`) close to convergence.

![mdp_unsorted_bins_corrected_code](https://cloud.githubusercontent.com/assets/5932817/11350077/c91ac59e-91fd-11e5-91f7-56b0eae3ff46.png)

**Comment by RussTedrake** [comment]
yes - the barycentric interpolation absolutely assumes that the grid elements are sorted.  i believe it is documented at the barycentric level (?) but i agree it should be also documented at the MDP level.  Please do add the doc and send another pull request.  Thanks.
