### ISSUE TITLE
Add C++20 support

### ISSUE THREAD

**Issue by jwnimmer-tri** [RobotLocomotion/drake#14670]
We should add official support for building drake under `-std=c++20`, for compilers which support it.  (Relates: #14652.)

We would still require that `-std=c++17` continue function as well, at least as long as we support Ubuntu 18.04 with GCC 7.5 still in play.

This might mean that we need an extra CI variant, or maybe we just flip all Clang CI to C++20 and have GCC CI with C++17.  To be determined.

(Adding this a discussion placeholder for now.)

**Comment by jamiesnape** [comment]
I figure, given #1183, we would not want to push the envelope too far. C++20 compilation should certainly work, but perhaps C++17 may want to stick around for a while (which pushes me toward an extra variant, I think).

**Comment by jwnimmer-tri** [comment]
Let's say the specific call to action here will be to add two new builds to Jenkins:
- `linux-focal-clang-bazel-experimental-release-cxx20`
- `linux-focal-clang-bazel-weekly-release-cxx20`

(Using some variation of those names is fine also, in case that makes the scripting easier.)

They should be identical to the current `linux-focal-clang-bazel-continuous-release` except that they will add `--copt=-std=c++20` to the bazel command line (and not be in "continuous", obviously).

**Comment by jwnimmer-tri** [comment]
At this point, perhaps the best option is to actually just wait for Ubuntu 22 ("Jammy") CI builds to appear, and then use C++17 on Focal and C++20 on Jammy, by default.  That way, CI configs and user configs could be just the same.
