### ISSUE TITLE
[tools:drake_visualizer] Separate visualization settings for hyrdoelastic forces and moments

### ISSUE THREAD

**Issue by rcory** [RobotLocomotion/drake#14689]
Related to #14679 and #14680 

The existing hydroelastic visualization settings dialog prompt provides the user a single checkbox to enable/disable visualization of both force and moment vectors. It would be nice to provide the user a way to enable/disable visualization of each of these independently, i.e., forces, moments, or both.

Moreover, since the units of forces and moments differ, having the ability to provide separate scaling factors (rather than a universal scaling factor) for each seems necessary.

**Comment by SeanCurtis-TRI** [comment]
I'm going to close this in favor of #14680. The only thing this provides that is (well, "was" now) from that issue's description is the request to separate forces and moments completely. I've edited it to include this.
