### ISSUE TITLE
Rendering global information to a Visualizer

### ISSUE THREAD

**Issue by eric-wieser** [RobotLocomotion/drake#1472]
Is there scope for adding direct access to xtraj inside the Visualizer.draw method? It would be useful to be able to  plot previous and end states on the same visualization.

Having access to `time_steps` would also be handy

**Comment by RussTedrake** [comment]
Not directly.  While it sounds like an obvious addition, adding additional state to a visualizer can break the idea of calling a visualizer another dynamical system.  
The trajectory optimization methods (and some examples) do it when they add a visualizer.  
For simulation, we also sometimes write directly to lcm.  We have tools like signal_scope which render those signals outside of matlab.
