### ISSUE TITLE
MultibodyPlant::AddJointActuator() documentation should clarify effort limit is unused

### ISSUE THREAD

**Issue by rcory** [RobotLocomotion/drake#14735]
The documentation for `MultibodyPlant::AddJointActuator()` takes in the actuator's `effort_limit` as an argument. From reading the documentation, it is easy for the user to assume that this limit will be enforced by the actuator (e.g., via saturation), when in fact this value is entirely unused in MBP calculations.

Adding clarifying notes in [this](https://github.com/RobotLocomotion/drake/blob/938c400950e00a5ef5633a26febc3ef575aace41/multibody/plant/multibody_plant.h#L1065-L1071) documentation would help avoid confusion.

**Comment by jwnimmer-tri** [comment]
This is documented at https://drake.mit.edu/doxygen_cxx/classdrake_1_1multibody_1_1_multibody_plant.html#mbp_actuation now.
