### ISSUE TITLE
numerical issue in PiecewisePolynomial

### ISSUE THREAD

**Issue by duanyutong** [RobotLocomotion/drake#14744]
There's a numerical issue causing `PiecewisePolynomial` to break down and yield nonsensical results when evaluated within the defined interval. MBE attached. This can happen when input break values are large. (Example use case is when using microseconds as the time unit.)

Same behaviour if all arrays are of dtype `np.float64`, same in C++ (`std::vector<double>` breaks generating `PiecewisePolynomial<double>`).

I haven't noticed any clear pattern of this issue. This particular failing test case goes from 0 to 4.8e6, while I have another test case that goes above 5e6 producing expected output. So it doesn't look like a simple overflow.

[drake_pp_bug.ipynb.zip](https://github.com/RobotLocomotion/drake/files/6097539/drake_pp_bug.ipynb.zip)

![image](https://user-images.githubusercontent.com/865317/110247575-eca50300-7f3a-11eb-9740-525335076c48.png)

**Comment by SeanCurtis-TRI** [comment]
@hongkai-dai I'm putting this in your wheel house (on-call platform review duties). Feel free to delegate.
