### ISSUE TITLE
Use python3-semantic-version package on Ubuntu

### ISSUE THREAD

**Issue by jamiesnape** [RobotLocomotion/drake#14749]
Instead of `@semantic_version`. Not sure why we do not at present.

FYI @jwnimmer-tri.

**Comment by jwnimmer-tri** [comment]
Not sure why either.  Added in #6014 but even then it looks like [semantic-version existed in Xenial](https://packages.ubuntu.com/xenial/python-semantic-version).

**Comment by jamiesnape** [comment]
I guess, because that author always uses Fedora, and I didn't think to check for an apt package in the review.

(Aside: Among other places, `/usr/share/dh-python/dist/cpython3_fallback` stores most `pip`/`import` to apt mappings locally.)
