### ISSUE TITLE
Should support continuous joints from SDFormat

### ISSUE THREAD

**Issue by calderpg-tri** [RobotLocomotion/drake#14747]
SDFormat defines "continuous" as a supported joint type since 1.6; however, our SDF parser does not support this joint type and throws a "Joint type not supported" exception when parsing a SDF file containing such a joint.

**Comment by calderpg-tri** [comment]
I believe I was writing a new model - specifically, using the initial version of the mecanum-chassis model generator - with wheels attached via continuous joints.

**Comment by jwnimmer-tri** [comment]
Does MbP already offer a compatible joint type?  In other words, is this only a parsing issue, or is it also a missing feature issue with the plant itself?

**Comment by calderpg-tri** [comment]
This is just a parsing issue, presuming that continuous joint behavior between URDF and SDFormat should be the same, `continuous` joints are already supported from URDFs.

**Comment by jwnimmer-tri** [comment]
@EricCousineau-TRI any chance to get this onto the OpenRobotics dashboard?  It's a simple Drake parsing fix (+ test case).

Otherwise maybe ping @xuchenhan-tri for MbP hitlist board.

**Comment by EricCousineau-TRI** [comment]
I could put it on the board - is it OK if it gets done w/in next ~3 weeks?

**Comment by jwnimmer-tri** [comment]
Yes, thanks!  I'd be satisfied with any non-zero velocity towards resolving the issue.

**Comment by RussTedrake** [comment]
It's been a lot more than three weeks.  This is a trivial thing to fix, and pretty surprising that we don't support this.  (Our FIRST robotics team just hit it!)

**Comment by xuchenhan-tri** [comment]
I can pick up this ticket if @EricCousineau-TRI has other priorities.

**Comment by EricCousineau-TRI** [comment]
My apologies and most definitely my bad. I had queued it on the SDFormat board, but did not discuss it w/ OSRC team in that following meeting and it feel to the wayside.

Xuchen - if you're handling it, then yes, that'd be great! Apologies you had to pick up my slack.

Otherwise, will bring up in OSRC meeting on Thursday.
Will still discuss assigning priorities for the SDFormat project as well.

**Comment by xuchenhan-tri** [comment]
No worries! Happy to learn more about SDFormat.
