### ISSUE TITLE
Should nuke almost certainly spurious "failure of target" caused by "running under Python 3" warning from Bazel.

### ISSUE THREAD

**Issue by jamiesnape** [RobotLocomotion/drake#14745]
Specifically `"The failure of target ..." may have been caused by the fact that it is running under Python 3 instead of Python 2.` I fixed the issue in `underactuated` and `manipulation`, so I think it is a one-liner somewhere.

Relates https://github.com/RobotLocomotion/drake/issues/14739#issuecomment-792838449.

FYI @jwnimmer-tri @EricCousineau-TRI.

**Comment by jamiesnape** [comment]
Russ's targets always explicitly set `srcs_version = "PY3"` and explicitly set `python_version = "PY3"` where appropriate.

**Comment by jamiesnape** [comment]
* https://github.com/RussTedrake/htmlbook/blob/26cb5cd9184f6cba1ed42b750ad81ed6497a6769/tools/python/defs.bzl#L18
* https://github.com/RussTedrake/htmlbook/blob/26cb5cd9184f6cba1ed42b750ad81ed6497a6769/tools/python/defs.bzl#L29

**Comment by jwnimmer-tri** [comment]
I'm calling this good enough for now.  I only fixed the `drake_py_...` targets.  Any `py_...` targets from externals might still experience this warning, but _shrug_.

**Comment by jwnimmer-tri** [comment]
It turns out that mkdoc frequently spews about this as well, so I've done another PR (above) to fix that as well.
