### ISSUE TITLE
Remove maintainer-only support on macOS

### ISSUE THREAD

**Issue by jamiesnape** [RobotLocomotion/drake#14754]
I hate to do this, since it hurts me a little, but it does not make sense to keep this going for pretty much just me and maybe Soonho. <s>Note we do have a test of the release notes infrastructure and we do not necessarily need to disable that immediately on macOS since it works fine (though I don't care too much if we did), but I would not fix any huge bugs going forward.</s>

FYI @jwnimmer-tri @soonho-tri.

Relates in part #14752.

**Comment by jwnimmer-tri** [comment]
Generally I think this makes sense, but for the record could you enumerate the tools / use cases that would disappear?

**Comment by jamiesnape** [comment]
`//tools/workspace:mirror_to_s3` is already run on JenkinsI. No reason why `//tools/workspace:new_release` could not for informational purposes.
