### ISSUE TITLE
Audit system prerequisites (and especially under what conditions they are installed)

### ISSUE THREAD

**Issue by jamiesnape** [RobotLocomotion/drake#14752]
We have various categories of system prerequisites (binary, source, doc-only, maintainer-only) on three platforms and somehow they have got out of sync. I will fill out the problems shortly (or just PR fixes), but maybe it is also a sign that the scripts have not become very manageable.

Seems like the times when we pull down something from bazel that has a set of one than one prerequisite gets confusing when that dependency becomes relevant for, say, binary instead of source, or test instead of maintainer. Also when code is removed, sometimes the dependency does not move, or part does, or part does on one platform, but not another.

Also, it is probably me that has made the mistakes, so I have made this too difficult for myself even.

Noticed while looking at #1183.

**Comment by jwnimmer-tri** [comment]
I think this observation is accurate, but not particularly actionable.  Once we have some new failure more biting us (possibly Ubuntu 22.04 support?), then we can revisit with a specific plan.
