### ISSUE TITLE
pydrake missing MultibodyPlant.GetForceElement method

### ISSUE THREAD

**Issue by mfogelson** [RobotLocomotion/drake#14874]
I am working to convert the strandbeest example using pydrake. 

I am currently unsure how to add the position constraints for each bushing element (line 198 run_with_motor.cc) because there is not a method GetForceElement in the pydrake bindings.

Was this method intentionally left out of the python bindings?

**Comment by jwnimmer-tri** [comment]
In the C++ demo, the call to `GetForceElement` is on the class `MultibodyPlant`, not `MultibodyTree`:

https://github.com/RobotLocomotion/drake/blob/v0.28.0/examples/multibody/strandbeest/run_with_motor.cc#L115-L116

https://github.com/RobotLocomotion/drake/blob/v0.28.0/examples/multibody/strandbeest/run_with_motor.cc#L203-L204

However, the pydrake bindings for the `MultibodyPlant` class do not offer the `GetForceElement` either.

I've re-titled the issue accordingly, and will re-assign to @sherm1 for delegation.
