### ISSUE TITLE
Probably need to update vtk bottles on mac

### ISSUE THREAD

**Issue by SeanCurtis-TRI** [RobotLocomotion/drake#14893]
We're getting CI failures on unprovisioned mac. Vtk is not succeessfully being found. The recent conversation can be found [on slack](https://drakedevelopers.slack.com/archives/C270MN28G/p1617989775098700) and echoes needs from back at the [beginning of March](https://drakedevelopers.slack.com/archives/C270MN28G/p1614724289018300).

**Comment by jamiesnape** [comment]
Rebuilt.
