### ISSUE TITLE
systems: LimitMalloc + Asan may not play nicely together?

### ISSUE THREAD

**Issue by EricCousineau-TRI** [RobotLocomotion/drake#14901]
See Slack: https://drakedevelopers.slack.com/archives/C270MN28G/p1618400443116900

Failure: https://drake-cdash.csail.mit.edu/test/171454211
```
+ git log -n 1 --oneline --no-decorate
a005c4081e simulator: Add test to track heap hygiene (#14900)
+ export CC=clang-9 CXX=clang++-9
+ bazel run --config=asan //systems/analysis:simulator_test
...
[ RUN      ] SimulatorTest.MonitorFunctionAndStatusReturn
munmap_chunk(): invalid pointer
{runfiles}/drake/tools/dynamic_analysis/asan: line 10: 47562 Aborted                 (core dumped) "$@"
```

Shallow investigation, post #14900, testing on a005c4081e
(1) Commenting out only `LimitMalloc` line allows it to pass.
(2) Commenting out everything in new test *except* for `LimitMalloc` causes the same issue.

Theory: `LimitMalloc` and `asan` checking do not want to play nicely together.

**Comment by soonho-tri** [comment]
To be specific, the failure in MonitorFunctionAndStatusReturn comes from this line:
https://github.com/RobotLocomotion/drake/blob/a005c4081e1830078525177e51be9d7812db57dd/systems/analysis/test/simulator_test.cc#L2320-L2321

**Comment by jamiesnape** [comment]
It won't. It should be a no-op. If it is a no-op with LSan, it needs to be a no-op with ASan.

https://github.com/RobotLocomotion/drake/blob/b09e40db4b1c01232b22f7705fb98aa99ef91f87/common/test_utilities/limit_malloc.h#L23-L26

**Comment by jamiesnape** [comment]
(There is slight variation between different platforms and compilers with regard the differences between ASan and LSan, but typically ASan will catch a superset of LSan issues.)

**Comment by jamiesnape** [comment]
According to our configuration `LSAN_OPTIONS` is defined during ASan builds, so something unexpected is happening.

https://github.com/RobotLocomotion/drake/blob/b09e40db4b1c01232b22f7705fb98aa99ef91f87/common/test_utilities/limit_malloc.cc#L28-L34

https://github.com/RobotLocomotion/drake/blob/a005c4081e1830078525177e51be9d7812db57dd/tools/dynamic_analysis/bazel.rc#L51

**Comment by rpoyner-tri** [comment]
There is some interaction among multiple factors. If I leave the LimitMalloc stuff as-was, and comment out all the EXPECT_THAT clauses that use MatchesRegex, the crashes also go away. IsSupportedConfiguration is returning false in my debugging runs, but the link-time hooks are still in place. I'll see what else I can find out.

**Comment by rpoyner-tri** [comment]
From further investigation, it looks like ASAN provides its own implementation of `strdup` -- whenever we call that and hand the result to (our hooked version of) `free`, we've crossed the heaps and hence come crashing down. The call to strdup() is buried inside the gtest code.

**Comment by jamiesnape** [comment]
https://github.com/llvm/llvm-project/blob/ad294e572bc5c16f9dc420cc994322de6ca3fbfb/compiler-rt/lib/asan/asan_interceptors.cpp#L445-L460

**Comment by rpoyner-tri** [comment]
Indeed, adding an overriding implementation of `strdup` "fixes" the immediate situation. It's worth noting that the problems arise not from any run-time LimitMalloc instrumentation; the problems arise because our link-time hook set is not complete enough to provide consistent heap access.

The follow-up question is this: is there a stable set of hooks we can provide that will allow "interop" with asan, or should we more aggressively bow out or refuse to execute in ASAN situations?

Possible paths:
 * implement more hooks to allow weakened interop (some ASAN errors won't be reported)
   * unsound (may require maintenance revisions), maybe questionable value
 * blow up at run-time if ASAN/LSAN configuration is detected
   * sound and easy to implement; probably annoying for developers (needs bazel tags to avoid explosions)
 * use compile-time detection (ifdefs) to avoid hooking at all under ASAN builds
   * sound; might be fiddly to get right across various compilers

**Comment by jamiesnape** [comment]
I think `__SANITIZE_ADDRESS__` (GCC) and `__has_feature(address_sanitizer)` (Clang/Apple) cover our support configurations.

**Comment by rpoyner-tri** [comment]
Cool. I will attempt to spell a proper patch to not hook in ASAN builds.

**Comment by jamiesnape** [comment]
Since we control the configurations, you could also `--copt=-DDRAKE_SANITIZE_ADDRESS` if that really did not work for some reason (though no reason to think it wouldn't).

**Comment by EricCousineau-TRI** [comment]
Along what Jeremy mentioned in PR, maybe it's worth doing the 2nd, blow up if ASAN/LSAN detected, rather than silently not running?

(Also: Maybe not, if it's self-evident given that you hafta consciously run asan.)

**Comment by rpoyner-tri** [comment]
No-op situations are currently documented; do you think more is required @EricCousineau-TRI ? This is a test-only utility module after all.

https://github.com/RobotLocomotion/drake/blob/master/common/test_utilities/limit_malloc.h#L23-L26

**Comment by EricCousineau-TRI** [comment]
Ah, gotcha; then nah.
