### ISSUE TITLE
ContactImplicitTrajectoryOptimization incorrectly detects number of contacts

### ISSUE THREAD

**Issue by rdeits** [RobotLocomotion/drake#1491]
`ContactImplicitTrajectoryOptimization.setupVariables()` does:

```
obj.nC = obj.plant.getNumContactPairs;
[~,normal,d] = obj.plant.contactConstraints(zeros(obj.plant.getNumPositions,1));
```

But when it actually generates the contact constraints, it uses the active collision options:

(in `addDynamicConstraints()`):

```
[~,~,~,~,~,~,~,mu] = obj.plant.contactConstraints(zeros(nq,1),false,obj.options.active_collision_options);
```

which results in mu being, in general, smaller than `obj.nC`. I believe the fix is to change, in `setupVariables()`:

```
      [~,normal,d] = obj.plant.contactConstraints(zeros(obj.plant.getNumPositions,1), false, obj.options.active_collision_options);
      obj.nC = size(normal, 2);
```

**Comment by rdeits** [comment]
(working on building drake master so I can submit a fix)

**Comment by mposa** [comment]
Looks good to me.
