### ISSUE TITLE
CalcJacobianCenterOfMassTranslationalVelocity() should take in model_instances as an input

### ISSUE THREAD

**Issue by hongkai-dai** [RobotLocomotion/drake#14916]
Currently when we compute the center-of-mass position through `CalcCenterOfMassPositionInWorld` https://github.com/RobotLocomotion/drake/blob/a939b72dfd547f7f2cfb145f400408e4e1423e46/multibody/plant/multibody_plant.h#L2476-L2478, the function takes `model_instances` as an input, so that we can evaluate the CoM position for a subset of plant.

On the other hand, when we compute the CoM Jacobian, we don't take the `model_instances` as the input
https://github.com/RobotLocomotion/drake/blob/a939b72dfd547f7f2cfb145f400408e4e1423e46/multibody/plant/multibody_plant.h#L3122-L3125
I think we should also add `model_instances` as an input to `CalcJacobianCenterOfMassTranslationalVelocity`

**Comment by sherm1** [comment]
--> @mitiguy

**Comment by mitiguy** [comment]
Got it -- yes, I'll work on it today/tomorrow.

**Comment by mitiguy** [comment]
PR #15387 opened to address this issue.

**Comment by mitiguy** [comment]
Closed with PR #15691 and PR #15387.
