### ISSUE TITLE
multibody optimization: request centroidal dynamics constraints

### ISSUE THREAD

**Issue by RussTedrake** [RobotLocomotion/drake#14914]
Per a slack discussion with @hongkai-dai , we are missing some of the core constraints that we used to support @hongkai-dai and @avalenzu 's work on the ComDynamicsFullKinematicsPlanner (#12344)
- [x] `CenterOfMass(q) = com`, where `q` and `com` are both decision variables
- [ ] `lb <= CenterOfMass(q) <= ub`, with `q` decision variables (for this particular planner, I can implement this via the first)
- [x] `CentroidalMomentum(q,v) = H`, where `q`, `v`, and `H` are all decision variables.  

This third one will require autodiff `MultibodyPlant`, I think, since I don't see a Jacobian method corresponding to `CalcSpatialMomentumInWorldAboutPoint`?

Also related to #6381.

**Comment by hongkai-dai** [comment]
I think we can close this issue, as we already have CentroidalMomentumConstraint, ComInPolyhedronConstraint, and in underactuated repo we have an example of using centroidal dynamics planner on little dog https://github.com/RussTedrake/underactuated/blob/master/examples/littledog.ipynb
