### ISSUE TITLE
MultibodyPlant needs a function for getting the total mass of a plant (or model_instance).

### ISSUE THREAD

**Issue by RussTedrake** [RobotLocomotion/drake#14913]
I spent a few minutes looking for it... but couldn't find it.  The documentation references composite_mass as a concept, but I think it only appears insider the center of mass methods:
https://github.com/RobotLocomotion/drake/blob/0ac940e5f37d67a88f5fe19d1fb111f2f92d2197/multibody/tree/multibody_tree.cc#L1305

Of course it's not hard to implement myself... but my goodness this seems like one that we should offer.

**Comment by sherm1** [comment]
@mitiguy I think this one is for you!

**Comment by mitiguy** [comment]
I agree.  I'll work on it this week.

**Comment by mitiguy** [comment]
PR #14957 addresses this issue #14913.

**Comment by mitiguy** [comment]
Resolved by PR #14957
