### ISSUE TITLE
Joint.velocity_start vs Body.floating_velocity_start() inconsistency

### ISSUE THREAD

**Issue by RussTedrake** [RobotLocomotion/drake#14942]
The [Joint version](https://drake.mit.edu/doxygen_cxx/classdrake_1_1multibody_1_1_joint.html#ae24835fcef569246252959b18d0027d6) of this method returns an index into `v`, but the [Body version](https://drake.mit.edu/doxygen_cxx/classdrake_1_1multibody_1_1_body.html#adc1bbbf124d24c628bb23796cfa5c594) returns in index into the full state vector.

It's perhaps annoying to fix.  But it feels like an inconsistency in our API, and it definitely tripped me up just now.

**Comment by amcastro-tri** [comment]
Duplicate of #12757.
