### ISSUE TITLE
OpenCLPointCloudVoxelizer fails on Catalina

### ISSUE THREAD

**Issue by calderpg-tri** [RobotLocomotion/drake#15006]
From #15005, this test no longer passes on macOS [(link)](https://drake-cdash.csail.mit.edu/test/192474043) after a recent Apple upgrade [(link)](https://discussions.apple.com/thread/252710156) [(link)](https://shapeof.com/archives/2021/4/apple_april_2021_security_update_and_acorn.html) and has been disabled.

cc @jwnimmer-tri @jamiesnape

**Comment by calderpg-tri** [comment]
To elaborate, OpenCL device *enumeration* still appears to work on Catalina, but the ability to *compile* OpenCL kernels was broken by Security Update 2021-002, so this test identifies devices on which to run but then fails to run on them.

Note that OpenCL-accelerated pointcloud voxelization continues to work on Big Sur and Ubuntu.

**Comment by calderpg-tri** [comment]
My understanding of the latest [update](https://shapeof.com/archives/2021/4/apple_april_2021_security_update_and_acorn.html) ([Security Update 2021-003](https://support.apple.com/en-us/HT212530)) is that Apple has fixed the bug in Catalina and we can reenable this test.

@jamiesnape How quickly are the mac CI machines updated?

**Comment by jamiesnape** [comment]
I am just (coincidentally) updating them, so later today.
