### ISSUE TITLE
Missing -DHAVE_SPDLOG when used as CMake external

### ISSUE THREAD

**Issue by jwnimmer-tri** [RobotLocomotion/drake#15004]
In the `drake_cmake_installed` or `drake_cmake_external` workflows (per https://github.com/RobotLocomotion/drake-external-examples) on Ubuntu 20.04, we are compiling Drake's shared library with `HAVE_SPDLOG` defined (so that is has logging support), but then in the client project they do a "find_package" for spdlog, which does not define that directive, and so `drake/common/text_logging.h` degrades into no-op mode for any new calls, and does not let the user configure the log destination anymore.

It's probably also an ODR violation for any of our inline functions that can emit log messages.

At build time once we choose a spdlog on/off, we need to sure that same setting propagates into our installed headers, binaries, or cmake config as well.

This is not a problem on 18.04, since we ship our own spdlog.

It's likely a problem on macOS also since we use homebrew spdlog, but I haven't tested that.

**Comment by jamiesnape** [comment]
Probably adding something along the lines of `COMPILE_DEFINITIONS/INTERFACE_COMPILE_DEFINITIONS HAVE_SPDLOG=1`

**Comment by jwnimmer-tri** [comment]
Yup, something like that would be right, presuming we keep the toggle.  I was also thinking of inverting the logic, so that spdlog is opt-out, since `bazel_drake_external` are the only people who can skip it in the first place.

**Comment by jamiesnape** [comment]
> I was also thinking of inverting the logic, so that spdlog is opt-out, since `bazel_drake_external` are the only people who can skip it in the first place.

I think that is reasonable, though I am all for simplification if we can lose the toggle.

**Comment by jwnimmer-tri** [comment]
A fair question.  It's definitely still in use internally at TRI, but I'll also do a sweep to see if we can change that around somehow.  Maybe now that it's part of Focal that's good enough.  Since it's in `//common:essential` its one of the dependencies we need to be most careful about.  I've also been pondering demoting it to `text_logging.cc` and re-implementing the ~7 formatter methods in the header ourselves, so that we can reduce it to a linker dependency instead of interface dependency.
