### ISSUE TITLE
solvers: OSQP requires a Quadratic Cost, but doesn't tell the user that.

### ISSUE THREAD

**Issue by RussTedrake** [RobotLocomotion/drake#15019]
A student was getting the message:
```
ValueError: The capabilities of drake::solvers::OsqpSolver do not meet the requirements of the MathematicalProgram ({ProgramAttributes: LinearConstraint, LinearEqualityConstraint})
```
for a very simple problem, which had only linear constraints and linear equality constraints.  Looking at the code, I found a hidden:
```
prog.required_capabilities().count(ProgramAttribute::kQuadraticCost) > 0;
```
I believe that they needed to add a Quadratic Cost to satisfy the requirements.  Can we make a better error message?

(I can try to come up with a repro after office hours).

**Comment by hongkai-dai** [comment]
Will send a PR to throw a better message.

**Comment by RussTedrake** [comment]
Just for completeness
```
from pydrake.all import MathematicalProgram, OsqpSolver

prog = MathematicalProgram()
x = prog.NewContinuousVariables(1)
prog.AddLinearConstraint(x[0] == 1)

solver = OsqpSolver()
solver.Solve(prog)
```
does, indeed, give the error message above.
