### ISSUE TITLE
urdf parser incorrectly parses non-first child nodes

### ISSUE THREAD

**Issue by mauricefallon** [RobotLocomotion/drake#1501]
In addRobotFromURDF.m,  parseRobot() searches **ALL** child nodes of the xml file at any level for joint, link, frame, transmission etc.
But what it should do is find only the first level child nodes.

The current search is naive as it can find unintended tags enclosed within another first child node.

For example getElementsByTagName('frame')  ... will find all 'frame' tags at any level. 

So in the snippet below, it will return a frame with the name 'sensor' for this tag:

```
<gazebo reference="leftAnkleRoll">
<sensor name="leftFootSixAxis" type="force_torque">
  <pose>0.0215646 0.0 -0.051054 3.14 0.0 -1.047</pose>
  <sensor_number id="FT001SIM"/>
  <node id="/sensors/leftFootSixAxis"/>
  <api name="TurbodriverForceTorqueSensor_v1"/>
  <always_on>true</always_on>
  <update_rate>1000</update_rate>
  <force_torque>
    <frame>sensor</frame>   <-------- finds this when it shouldn't
  </force_torque>
</sensor>
</gazebo>
```

**Comment by david-german-tri** [comment]
@liangfok, You've been working on parsers, so I've reassigned this to you.  Please prioritize however you see fit.

**Comment by jwnimmer-tri** [comment]
I can't tell if this is a matlab-only defect.  If so, we should label it as such and kick it back to RLG.

**Comment by RussTedrake** [comment]
i believe that it was a matlab defect (but could happen in c++, too).  from memory: the failure is doing a "find first child with tag blah" with the xml parser could find a child of a child, which in this case meant something different.  we should be careful not to do that.  

the matlab urdf parser is effectively deprecated at this point.  safe to close as "will not fix".
