### ISSUE TITLE
Hydroelastics calculation leads to NaN when using AutoDiffXd

### ISSUE THREAD

**Issue by amcastro-tri** [RobotLocomotion/drake#15029]
We document here our analyses and findings on the problem first identified by @SeanCurtis-TRI in #14940.
We extract the discussion in #14963 into this new issue in order to have a clean piece of documentation we can refer to in the source.

# The Problem
There are two independent but related problems.

The first has to do with the expression `f(x) = atan(x)/x` (used to by the friction model). Notice that `f(x)` is not even defined at `x = 0`. At least not numerically. Mathematically, the limits from left and the right exist for both `f(x)` and its derivative. We'd like the computation to reproduce these limits, not the singularity at `x = 0`.

The second problem is related to where the value of `x` comes from. It is actually the magnitude of a vector. So, essentially `x = sqrt(x²)`. While this function is well defined at `x = 0`, its derivatives are not. And if the vector (representing relative velocity) ever reaches zero, its derivatives become undefined (introducing NaNs into the derivatives). And it’s *very* likely for relative velocity between two objects to be zero.

# Proposed solution

in #14963 we propose to use a Taylor expansion of `atan(x)/x` near `x = 0` and use the actual functional form `atan(x)/x` away from zero. This has two benefits:

  - First, since the limits of `f(x)` do exist mathematically, its Taylor expansion is a very nicely defined, continuous polynomial near zero.
  - Second, the polynomial is expressed strictly in terms of `x²`. So, when `x` is near (or even at) zero, we never have to take a square root.

We therefore introduce a cutoff value xc and use the Taylor expansion for `x < xc`.

# Analysis of proposed solution

In principle, the piecewise definition is a great solution. But there are some important remaining questions (which arose during the review of #14963):
  1. In the domain where `x < xc`, is the Taylor series superior, inferior, or equivalent to simply evaluating `atan(x)/x`?
  2. Where should the cut off `xc` be defined? The initial implementation used `xc = 1e-4` based on an analysis of the leading terms of the Taylor expansion.  It turns out that how `AutoDiffXd` evaluates this expression has a significant impact on round-off errors (see below).  Can we choose `xc` better in order to minimize round-off errors?
  3. What's the optimum number of terms in the Taylor expansion? The original implementation used three terms based on the analysis of truncation errors. Is that a good choice when we consider round-off errors introduced by `AutoDiffXd`?
  4. With the original cutoff of `xc = 1e-4`, we observed a discontinuity in the derivatives of the `CalcAtanOverXFromXSquared()` function at `xc` (on the order of 1e-12). How do we assess this discontinuity? Is it inevitable? Does `atan(x)/x` exhibit the discontinuity? Etc.
 
We also realized that round-off errors are extremely important. In particular, since `AutodiffXd` applies brute force chain rule (without any algebraic manipulation to achieve an optimal, well-defined expression) it introduces a significant amount of round-off error.

We present the detailed analysis from #14963 below.

## Experiments to evaluate the proposed solution

This is what I (@amcastro-tri ) did:

I instrumented the unit test to write out the values of `f<double>` and `f<AutoDiffXd>` as ascii text (with the highest precision to fully capture the in-memory value).

In Matlab I generated reference values using Variable Precision Arithmetic (VPA) to 36 digits to serve as our "exact" reference values, for both function and its derivative. (36 digits was overkill; 24 should be sufficient, but I played it safe and made it double that of double precision. In practice, there were no observable differences in the results between 24-digit and 36-digit VPA).

I computed the errors between the VPA reference values and results produced by both `atan(x)/x` and `CalcAtanOverXFromXSquared()`, plotting the results.

For the legends:
  - `f<double>` is the absolute error for the value of `atan(x)/x` evaluated with the double scalar.
  - `f<AutoDiffXd>` is the absolute error for the derivative value of `atan(x)/x` evaluated with the `AutoDiffXd` scalar.
  - `Taylor<double>` is the absolute error for the value of the Taylor expansion evaluated with the double scalar.
  - `Taylor<AutoDiffXd>` is the absolute error for the derivative value of the Taylor expansion evaluated with the `AutoDiffXd` scalar.
  - That lil epsilon (ϵ) marks the double precision machine epsilon.

Lines that appear incomplete or broken are fully defined. The error in the missing regions is reported as zero and can’t be drawn in the plot. This happens a great deal for the Taylor expansion of `f(x)` and less so for its derivatives. So, seeing a “broken” curve is a good thing.

## Plotting the behavior for `xc = 1e-4` and using three terms in the Taylor expansion

![image](https://user-images.githubusercontent.com/22159799/118054574-5d9dd800-b33b-11eb-903f-d855a4db3577.png)
__Figure 1__: Observed error for f(x) and `CalcAtanOverXFromXSquared()`

The original implementation used `xc = 1e-4` and *three* terms in the Taylor expansion. My initial analysis was to simply characterize that definition. The plots below show those results. We can observe the following:
  - The lines for `Taylor<d>` and `f<d>` are both essentially zero for all `x < 1e-4`. That means the functions produce indistinguishably valid results. (Note: `atan(x)/x` exhibits some error for `x > 1e-4`, but the error lies below machine precision for doubles).
  - The big difference is shown in the derivatives values. Below 1e-4, the Taylor expansion shows no error in derivative value. The evaluation of `atan(x)/x` produces errors as large as 1e-8!

This graph allows us to answer the first question:

> In the domain where x < xc, is the Taylor series superior, inferior, or equivalent to simply evaluating atan(x)/x?

The answer is clearly superior. The values are equivalent and the derivatives are exhibit less error.

![image](https://user-images.githubusercontent.com/22159799/118054719-a2c20a00-b33b-11eb-8371-d4d280d73cbf.png)
__Figure 2__: The same data as in Figure 1 but zoomed in to the region `x ∈ [10⁻⁴  1]`. The derivatives in `f<AD>` exhibit some irregularity. We imagine that the implementers of `std::atan` are using similar tricks as we are here, only tailored directly to `atan(x)` (rather than `atan(x)/x)`.

## Precision using 9 terms in the Taylor expansion

Why 9 terms? because as we increase the number of terms we do see improvement, but not anymore after 9 terms. Round-off error with `AutoDiffXd` dominates. This answers question three, what’s the optimal number of terms?. We’ve omitted the graphs for other terms and simply assert that 9 terms is optimal.

The next two plots help us answer Q2; yes, we can move the cutoff for better results, in this case from 1e-4 to 1e-1.

![image](https://user-images.githubusercontent.com/22159799/118054855-e9176900-b33b-11eb-8738-145cc87ad6e9.png)
__Figure 3__: Comparison of `f(x)` and `CalcAtanOverXFromXSquared()`. The Taylor expansion uses nine terms with a cut off at `x = 0.12`.

That red dotted peak that intersects the blue dotted line is at about `x = 0.12`. That is, if we choose `xc = 0.12` the error in the derivatives computed by the Taylor expansion is always *below* that of `atan(x)/x`. Furthermore, the deviation between derivatives at the crossing point is minimized, virtually eliminating the issue outlined in question 4.

![image](https://user-images.githubusercontent.com/22159799/118055059-3f84a780-b33c-11eb-974c-d8236693d374.png)
__FIgure 4__: The same data as in Figure 3 but zoomed in to the region `x ∈ [10⁻⁴  1]`.

# Conclusion

Notice that with this method (Taylor below `xc = 0.12` and `std::atan(x)/x` for the rest) we cannot reach machine precision everywhere. The maximum error I observe for three terms is about `5e-14` and with nine terms `5e-16` (though much closer!)

Therefore we decided on using the Taylor expansion with 9 terms below `xc = 0.12`.

# Additional Thoughts

We could even gain additional precision if so needed by making a specialization of `atan(x)/x` for the case `AutoDiffXd`. While this would work, we are afraid that the large amount of round-off errors we observed in this one lil expression will actually show up in other places. Therefore we are not sure at this stage if getting rid of round-off errors here would result in a final expression with no round-off errors. This was a big surprise. We trust `AutoDiffXd` for getting easy, machine-precision derivatives. It turns out that all we can get is "easy".

# Matlab script to generate reference values

The snippet below can be copy/pasted and run as is within Matlab to generate the reference values used for the unit test in #14963.

```Matlab
% Function atan(x)/x:
f = @(x) atan(x)./x;
% And it's derivative:
df = @(x) (x ./ (x.*x + 1) - atan(x)) ./ (x.*x);

% A set of arbitrary values where to evaluate f and df.
v = [1e-6 1e-4 0.119999 0.12 0.120001 1.0];
digits(36);  % Set desired number of digits for symbolic evaluation.

% Symbolic evaluation.
v_sym = sym(v);
f_sym = f(v_sym); 
df_sym = df(v_sym); 

% Truncation to double precision for our "reference" values.
fref = double(vpa(f_sym));
dfref = double(vpa(df_sym));

% Print values with 16 digits so they can be copy/pasted into our unit
% tests.
sprintf('%.16e, ',fref)
sprintf('%.16e, ',dfref)
```

**Comment by xuchenhan-tri** [comment]
Looks like this issue is more of a summary of what has already been implemented in #14963 instead of an actual change request. It should serve its purpose as long as it's linked to the PR and doesn't have to be left open.
