### ISSUE TITLE
Using `Point` in `dynamics`

### ISSUE THREAD

**Issue by eric-wieser** [RobotLocomotion/drake#1506]
Is it bad form for the dynamics function to start with the following?

     x = Point(obj.getStateFrame, x)

Is there a reason that dynamics is not passed a point object directly?

**Comment by RussTedrake** [comment]
Only performance reasons.  In the new C++ code, it will happen automatically.


On December 9, 2015 at 5:57:45 PM, Eric Wieser (notifications@github.com) wrote:

Is it bad form for the dynamics function to start with the following?

 x = Point(obj.getStateFrame, x)

Is there a reason that dynamics is not passed a point object directly?
