### ISSUE TITLE
[geometry] Modifiable collision filters

### ISSUE THREAD

**Issue by SeanCurtis-TRI** [RobotLocomotion/drake#15089]
## The problem

Drake has the concept of "collision filters". In short, a Drake user can declare that a pair of geometries (A, B) can be ignored in various pair-wise proximity queries (e.g., penetration, signed distance, etc.)

Currently, Drake can only *accumulate* collision filters. That is to say, once a pair has been declared as "filtered", it cannot be reversed. Furthermore, there are various practical applications in which *temporary* modifications to collision filtering would be convenient.

## The proposal

The current API consists of a family of methods: `ExcludeCollisions{Within|Between}` which add filtered pairs to the overall filter configuration. This current API and is part of the *persistent* API (see below) We need to add two things:

  - A parallel persistent `AllowCollisions{Within|Between}` which can reverse the effect of `ExcludeCollisions`.
  - A transient API for adding/removing collision filters.

### Transient filter modifications

We will facilitate transient filter modifications (changes that can be applied and then easily undone) using the concept of a `FilterDeclaration` -- a mechanism for declaring what pairs should be filtered and what pairs should not. The effective collision filter configuration is defined by a persistent base state with an arbitrary number of ordered `FilterDeclaration`s applied to it. The current API would modify the persistent base but have no notion of the `FilterDeclaration`.

The `FilterDeclaration` is the basis for the transient filter modification. Each `FilterDeclaration` will have a unique identifier associated with it. `FilterDeclaration`s can be removed from the sequence and the final configuration will be the persistent base state with the *remaining* ordered declarations reapplied (although that is not necessarily how it will be implemented).

There are some further implications of this design:

  - Include an API to take the current configuration and "bake" it into the base persistent state (invalidating all `FilterDeclaration` ids that had previously been generated).
  - We provide introspection queries on `FilterDeclaration` ids: is the given id valid?
  - Modifications to the persistent base cannot be made while there is a "live" declaration sequence.

There are some interesting implications in using this paradigm that must be explicitly called out to users in the documentation (this list is not necessarily complete and I expect it will be edited to include more nuances as they occur to me):

  - When making a filter declaration, the user should *ignore* what the current configuration is and unambiguosly state what result they want. Defining a declaration relative to the configuration at time of declaration can become invalid if a previous declaration in the sequence gets subsequently removed.
  - There is *no* harm in making redundant declarations. When in doubt, declare.

### Issues

The current [collision filter implementation](https://github.com/RobotLocomotion/drake/blob/master/geometry/proximity/collision_filter_legacy.h) was a quick-and-dirty hack. It borrowed from the old implementation and was applied to enable collision filtering quickly. However, the implementation is insufficient to support any of the desired APIs -- even something as simple as "allowing collision between a filtered geometry pair" is rendered painful. So, we'll have to gut the current implementation in favor of one that is more amenable.

## The plan

The full API has been implemented and parceled into PR-sized commits [here](https://github.com/SeanCurtis-TRI/drake/tree/TRAIN_modifiable_collision_filters). The branch will diminish in size as commits work their way into master.

- [x] #15228
- [x] #15297
- [x] #15348
- [x] Anzu 7291 - Update Anzu to use the new API
- [x] #15396
- [x] #15415
- [ ] #15492

The __*old*__ plan kept for reasons of trivia.

- [ ] ~#15115~ ~#15090~ - Add a new API to `SceneGraph` for manipulating collision filters: `CollisionFilterManager` all subsequent churn will happen on *that* class (and its related class `CollisionFilterDeclaration`).
    - The original plan introduced the new API and did the deprecation in one PR. That has been retired in favor of this new approach.
- [ ] ~#15130~ - Add python bindings.
- [ ] - Deprecating the old API.
- [ ] - Replace the underlying "legacy" filter implementation with a new implementation that will admit modifications to the collision filter configuration (both removing collision filters as well as temporarily modifying the state).
- [ ] - Extend the API to *permanently* remove filters.
- [ ] - Extend the API to facilitate *temporary* modifications of collision filters.

**Comment by sherm1** [comment]
SGTM!

**Comment by EricCousineau-TRI** [comment]
FYI I unchecked the box for #15115, given that it was reverted in #15139.
Was confusing when writing release notes (#15207).
