### ISSUE TITLE
Updated provisioned images for Bazel 4.1

### ISSUE THREAD

**Issue by jwnimmer-tri** [RobotLocomotion/drake#15087]
https://github.com/RobotLocomotion/drake/pull/15086 upgraded our Ubuntu-pinned bazel to 4.1.  Homebrew also has 4.1.0 available.  Please upgrade our provisioned images on both Ubuntu and macOS to use bazel 4.1.

**Comment by jamiesnape** [comment]
macOS is updated. +@BetsyMcPhail for Ubuntu.

**Comment by BetsyMcPhail** [comment]
Ubuntu images have been updated
