### ISSUE TITLE
Operations on trajectories neither check nor output frames

### ISSUE THREAD

**Issue by eric-wieser** [RobotLocomotion/drake#1509]
For instance, any two trajectories of the same dimension can be added together, and will produce a result with an output frame matching neither of the inputs. Ie, this currently works:

```
p1 = Some4StatePlant()
p2 = SomeOther4StatePlant()

x1 = simulate(p1, ...)
x2 = simulate(p2, ...)

bad_add = x1 + x2;
```

But this doesn't:

```
x1 = x1 + [1, 0, 0, 0];
assert(x.getOutputFrame == p1.getOutputFrame)
```

A couple of proposals:
- Addition (or in general, elementwise operations in the time axis) should fail if the frames do not match
- To make existing cases work, we should distinguish default frames from deliberate frames
- Addition should succeed if the frames do not match, but output the same frame as both inputs if they do match

Thoughts?

**Comment by RussTedrake** [comment]
It would be interesting to try the first proposal, and see how many test failures we get.  The second bullet would be difficult to enforce.  The third seems like likely the best option for now.  Again, the new C++ classes will revisit this (and clean it up a bit)

**Comment by RussTedrake** [comment]
won’t fix
