### ISSUE TITLE
solvers: `MosekSolver::enabled()` binding appears to be broken

### ISSUE THREAD

**Issue by RussTedrake** [RobotLocomotion/drake#15106]
```
from pydrake.all import MosekSolver
solver = MosekSolver()
solver.enabled()
```
returns 
```
     30 solver = MosekSolver()
---> 31 solver.enabled()
     32 result = solver.Solve(prog)
     33 assert result.is_success()

AttributeError: 'pydrake.solvers.mosek.MosekSolver' object has no attribute 'enabled'
```

Per slack convo, it would also be good to add a note to the docstring for `available` to remind users that they might also need to check `enabled`.  Or better, if it's true that checking `enabled` also confirms `available`, then can we document that?

**Comment by jamiesnape** [comment]
Does not appear to be bound for solvers implemented in C++. You can add `enabled` near here and in an analogous way: https://github.com/RobotLocomotion/drake/blob/a910475068a928e9ddaed1869c981f24a19c450c/bindings/pydrake/solvers/mathematicalprogram_py.cc#L309-L310
