### ISSUE TITLE
Passing the wrong context to OutputPort::Eval crashes the process

### ISSUE THREAD

**Issue by RussTedrake** [RobotLocomotion/drake#15177]
_Edit: Originally titled **python: passing the wrong context to OutputPort::Eval crashes the python interpreter**._

I've seen this time and again (a user's juptyer server / colab notebook crashes because they passed the wrong context).  I just did it to myself, so decided to make a minimal repro.  I've seen it most often when the context is an `MultibodyPlant` or `SceneGraph`, but created an example below using just a `Gain` which supports my thinking that it is a framework issue, not a system-specific issue.

```
from pydrake.all import DiagramBuilder, Gain, ConstantVectorSource

builder = DiagramBuilder()
gain = builder.AddSystem(Gain([1.0]))
source = builder.AddSystem(ConstantVectorSource([1.0]))
builder.Connect(source.get_output_port(), gain.get_input_port())
diagram = builder.Build()

context = diagram.CreateDefaultContext()

ok = gain.get_output_port().Eval(gain.GetMyContextFromRoot(context))

# This causes the python interpreter to crash:
crash = gain.get_output_port().Eval(context)
```

Expected behavior: The last line should throw an exception (probably `AssertionError`).
Current behavior: The python interpreter crashes.

cc @sherm1 as team owner.
@jwnimmer-tri -- hoping you might have a suggestion/solution.

**Comment by jwnimmer-tri** [comment]
\CC @rpoyner-tri because this is supposed to be caught by our #12560 work.

Later today, I'll see what I can find out from a debugger.

**Comment by jwnimmer-tri** [comment]
It segfaults in Release builds but raises a nice exception in Debug builds.

This is the line that's helping us out in Debug builds.  It's guarded by `DRAKE_ASSERT_VOID`.
https://github.com/RobotLocomotion/drake/blob/v0.30.0/systems/framework/output_port.h#L118

Perhaps none of the calls to `ValidateContext` should ever be within `DRAKE_ASSERT_VOID`.  Most of them are not guarded (only 8 are turned off in Release builds).  I'll have to go back and look why we did it that way.
