### ISSUE TITLE
determine documentation standard for citing publications (from code comments)

### ISSUE THREAD

**Issue by RussTedrake** [RobotLocomotion/drake#1524]
Our current strategy is
- Use doxygen for inline documentation in matlab and c++
- XML schema (published on build) for documenting URDF file formats
- Primary documentation for examples and tutorials are in course notes: http://underactuated.csail.mit.edu
- Video tutorials (only one or two so far, but people seem to like them)
- User contributed gallery.html 
- External wiki/discussion forum https://github.com/RobotLocomotion/drake/issues/1175
- [Wiki](https://github.com/RobotLocomotion/drake/wiki) for install instructions / FAQ (+ launching point for all of the above)

Can we simplify this list?  Are there open-source projects that people think are excellent examples of this?  [Point Cloud Library](http://pointclouds.org/documentation/) is one that gets mentioned quite a bit.

**Comment by RussTedrake** [comment]
Recommendation: consider sphinx to replace wiki documentation (breathe plugin will parse from doxygen output; also a plugin for matlab) so that it is versioned with the source.

**Comment by RussTedrake** [comment]
Idea: tutorials in source as iPython notebooks (even with the matlab engine).  can be run as a unit test.

**Comment by RussTedrake** [comment]
Also need to figure out a standard for citing publications.  https://github.com/RobotLocomotion/drake/pull/1519#issuecomment-167558130

**Comment by david-german-tri** [comment]
@naveenoid, @RussTedrake suggested assigning this to you.  I'll do that once you've added yourself to the TRI group in RobotLocomotion.

**Comment by tri-ltyyu** [comment]
@RussTedrake, is this still a concern? if not, please close

**Comment by EricCousineau-TRI** [comment]
This still useful? TBH, prolly ain't that hard to write regex or whatever to fix this.

(ofc, this would be queued w/in next few months)

**Comment by RussTedrake** [comment]
i'm ok closing it.
