### ISSUE TITLE
DeclareVectorInputPort error

### ISSUE THREAD

**Issue by yangL11** [RobotLocomotion/drake#15250]
Hello, together.
i created my own CMake-Project and linked the drake library. However, when I am trying to create my own LeafSystem I receive a segmentation fault from drake when calling DeclareVectorInputPort in the constructor.
  `this->DeclareVectorInputPort("test", drake::systems::BasicVector<T>(1));`
Everything else seems to work fine, for example using predefined LeafSystems or examples such as the Pendulum. Do you know what the problem could be?
Thanks for your help. Greetings!

**Comment by sherm1** [comment]
Please see Drake's [getting help](https://drake.mit.edu/getting_help.html) advice -- it would be better to use Stackoverflow (tag=drake) for this question.
