### ISSUE TITLE
parsing: Joint names should not collide if they are in different scopes

### ISSUE THREAD

**Issue by azeey** [RobotLocomotion/drake#15280]
Given the following SDFormat
```xml
<model name='parent_model'>
  <link name='L1'/>

  <model name='M1'>
    <link name='L2'/>
    <link name='L3'/>

    <joint name='J1' type='fixed'>
      <parent>L2</parent>
      <child>L3</child>
    </joint>
  </model>

  <joint name='J1' type='fixed'>
    <parent>L1</parent>
    <child>M1::L2</child>
  </joint>
</model>
```
Drake throws an exception with the message
```
AddJoint(): Duplicate joint name 'J1'.
```
This is because it's trying to add joint `J1` to the model instance, `M1`, of the child link `M1::L2`, but `M1::J1` already exists. A simple solution would be to keep the joint in the model instance it's defined, but that could be a breaking change.

/cc @EricCousineau-TRI

**Comment by EricCousineau-TRI** [comment]
Closing for now, given that it's on record.
