### ISSUE TITLE
Concatenating two systems

### ISSUE THREAD

**Issue by eric-wieser** [RobotLocomotion/drake#1534]
If I want the output of one system to go to the input of the next, ie `y = f(u), z = g(y)`, I can use `cascade` to get `z = h(u)`

What function can I use to turn `y = f(u), z = g(v)` into a single plant `[y;z] = h([u;v])`, such that I can pass it into trajectory optimization?

**Comment by RussTedrake** [comment]
That would be a “parallel combination”.  We don’t use it much, but hopefully it will work:  http://drake002.csail.mit.edu/drake/doxygen_matlab/class_dynamical_system.html#acb165e6d663ef0266acb61e50d30f6ee
