### ISSUE TITLE
Python Binding for TrajectoryLinearSystem

### ISSUE THREAD

**Issue by vyas-shubham** [RobotLocomotion/drake#15343]
Feature request to have python bindings for the `TrajectoryLinearSystem` class. This is useful for creating trajectory systems with custom linearizations.

**Comment by jwnimmer-tri** [comment]
@rpoyner-tri are you still evaluating the bindings autogeneration tool?  This class might be a nice test case.

**Comment by jwnimmer-tri** [comment]
For the record, we do have [TrajectoryAffineSystem](https://drake.mit.edu/pydrake/pydrake.systems.primitives.html#pydrake.systems.primitives.TrajectoryAffineSystem) available in pydrake.  If I'm reading it correctly, it could be a possible work-around.
