### ISSUE TITLE
Use pkg-config to find yaml-cpp

### ISSUE THREAD

**Issue by mwoehlke-kitware** [RobotLocomotion/drake#15356]
Several externals are found using `pkg-config`. Unfortunately, yaml-cpp is not among them; the location is hard-coded.

This makes it impossible to use a yaml-cpp from any source other than `apt`, which is needed for #1183.

**Comment by jwnimmer-tri** [comment]
> Use pkg-config to find yaml-cpp

Issue #13335 and #13309 contain some related background information.  As of last year, pkg-config for yaml-cpp was broken on Focal.  I haven't checked whether or not it's still broken.

> This makes it impossible to use a yaml-cpp from any source other than apt, which is needed for #1183.

My current premise for #1183 is that we will use a different `WORKSPACE` file when compiling for pip / manylinux.  Jamie and I thought it would be implausible to incrementally tweak our current `WORKSPACE` to the point where it was satisfactory.  The new `WORKSPACE` would certainly opt back in to the repository rules for _many_ of the existing externals, but would definitely need to replace some of them outright, at least for now.

Perhaps in the longer term, we could work to fold them back into a single, more general `WORKSPACE` that met both needs, but using for a forked `WORKSPACE` seemed like the smartest path to reach the manylinux goal effectively.

**Comment by mwoehlke-kitware** [comment]
> My current premise for #1183 is that we will use a different WORKSPACE file

@jwnimmer-tri, how does one do that?

**Comment by jwnimmer-tri** [comment]
For starters, the I'll bet the boring thing would work: have a `workspace-pip.bzl` committed somewhere within Drake (probably at the root?), and then when running in pip-building mode we do `cp workspace-pip.bzl WORKSPACE` before we begin.

**Comment by mwoehlke-kitware** [comment]
Okay, given that the current approach (n.b. #15636) seems to be hammering a different hard-coded location, is this still relevant?

**Comment by jwnimmer-tri** [comment]
Yes, in any case I think a pip-specific customization will end up as the answer here.  I'm OK if you want to close this issue.
