### ISSUE TITLE
MosekSolver doesn't respect CommonSolverOptions

### ISSUE THREAD

**Issue by RussTedrake** [RobotLocomotion/drake#15359]
Related to #15342.

Turning on printing for mosek requires a different path than the one advertised, and requires a special `MosekSolver` object and a call to `set_stream_logging()`.  

@hongkai-dai -- I'm assigning these issues to you as I consider you the owner of this component.  But we need to find ways for you to recruit help.  You shouldn't have to address everything yourself!

**Comment by hongkai-dai** [comment]
> @hongkai-dai -- I'm assigning these issues to you as I consider you the owner of this component. But we need to find ways for you to recruit help. You shouldn't have to address everything yourself!

I agree. I realize I can't resolve all issues in MathematicalProgram even I work really hard. Besides I need to spend time on the Anzu project, and my research on trajectory optimization or Lyapunov stable control design.
