### ISSUE TITLE
Switch our travis builds to 14.04?

### ISSUE THREAD

**Issue by rdeits** [RobotLocomotion/drake#1536]
Ubuntu 14.04 support was enabled in Travis this fall. Do we want to switch? I'm inclined to say yes, since none of us are running 12.04 anymore.

**Comment by rdeits** [comment]
We're going to keep 12.04 on Travis for now. I'll see if it's possible to run both.

**Comment by rdeits** [comment]
Things that are too old in the Ubuntu 12.04 package repositories (and that we build from source instead):

* swig (stuck at 2.0)
* python-numpy
* python-scipy
* python-matplotlib

**Comment by RussTedrake** [comment]
I see a theme here.  is python going to be the thing that sets our minimum OS?


On December 22, 2015 at 3:00:47 AM, Robin Deits (notifications@github.com) wrote:

Things that are too old in the Ubuntu 12.04 package repositories (and that we build from source instead):

swig (stuck at 2.0)
python-numpy
python-scipy
python-matplotlib

**Comment by jhoare** [comment]
Regarding python, you could consider the conda distribution for older OS's. We use it for older systems where we need a newer python interpreter (e.g. RHEL5/6)

https://www.continuum.io/why-anaconda

**Comment by rdeits** [comment]
That's a good point; I hadn't thought about Conda. And no, not yet--building those packages from source is easy, so there's no need to require 14.04
