### ISSUE TITLE
Support L2-Norm costs in MathematicalProgram

### ISSUE THREAD

**Issue by RussTedrake** [RobotLocomotion/drake#15366]
Proposed roadmap:
- [x] Introduce `class L2NormCost : public Cost` which implements the generic constraint. 
- [x] Add `MathematicalProgram::AddL2NormCost(A,b,vars)` after [the old (incorrectly-named) version](https://github.com/RobotLocomotion/drake/blob/master/solvers/mathematical_program.h#L1084) clears deprecation.
- [x] Teach convex solvers to handle this cost by either:
   - Each solver could opt-in to supporting the `L2NormCost` object, much as they do a `QuadraticCost` object.  (this requires adding another list of `L2NormCost`s to `MathematicalProgram`), or
   - Pass an option to `MathematicalProgram::AddL2NormCost(A,b,vars,use_slack_and_conic_constraint)` that would push the power (burden?) to the user to spell this cost in the convex way that is only better for some optimizers.

For bonus points:
- [ ] Add sugar in `ParseCost(Expression)` to detect the simple form of `sqrt(quadratic)` and create the constraint.
- [ ] Add `MathematicalProgram::AddL2NormCost(expression)`

cc @hongkai-dai

**Comment by jwnimmer-tri** [comment]
> Add MathematicalProgram::AddL2NormCost(A,b,vars) after the old version clears deprecation.

As of #15701, this prerequisite is complete.

**Comment by RussTedrake** [comment]
@hongkai-dai -- might you be willing to add this to your (admittedly also long) list?
