### ISSUE TITLE
Binding_LinearConstraint cannot be cast as Binding_Constraint in pydrake

### ISSUE THREAD

**Issue by hongkai-dai** [RobotLocomotion/drake#15405]
Reported in #15272 , for example, I have to add the overload of `RemoveCost` for each derived cost type in https://github.com/RobotLocomotion/drake/blob/3d71fac70bad294f93c9e5adb5b5ac155219b536/bindings/pydrake/solvers/mathematicalprogram_py.cc#L1379-L1392, same for `RemoveConstraint`. If I don't have these overload, I receive the following error
```
TypeError: RemoveConstraint(): incompatible function arguments. The following argument types are supported:
    1. (self: pydrake.solvers.mathematicalprogram.MathematicalProgram, arg0: drake::solvers::Binding<drake::solvers::Constraint>) -> int

Invoked with: <pydrake.solvers.mathematicalprogram.MathematicalProgram object at 0x7f0cd70b1030>; kwargs: constraint=<pydrake.solvers.mathematicalprogram.Binding_LinearConstraint object at 0x7f0cd420d130>
```

**Comment by EricCousineau-TRI** [comment]
I think this'd be easy to fix in line with what Russ did in #15353. Filing PR now (as part of platform duties).
