### ISSUE TITLE
ProgramAttribute should differentiate between convex and nonconvex quadratic cost/constraints

### ISSUE THREAD

**Issue by hongkai-dai** [RobotLocomotion/drake#15435]
Currently ProgramAttribute has kQuadraticCost and kQuadraticConstraint. We should replace them with kConvexQuadraticCost, kNonconvexQuadraticCost, kConvexQuadraticConstraint and kNonconvexQuadraticConstraint.

**Comment by jwnimmer-tri** [comment]
I can broadly understand why we might want the additional level of detail.  But was there a specific motivation for this feature you had in mind when you filed this?  Would certain solver back-ends deal with the two separately?

**Comment by hongkai-dai** [comment]
I think we can close this now.

In QuadraticCost we have `is_convex()` method.
