### ISSUE TITLE
build libdrakeIK when snopt is present, but gurobi is not;  consider adding libdrakeIK to the snopt precompiled zip

### ISSUE THREAD

**Issue by rdeits** [RobotLocomotion/drake#1545]
We still build libdrakeIK when gurobi and snopt are not found, but it results in a library that's totally useless (it only has symbols for a few IKoptions-related functions). 

Should we just disable building that library if snopt and gurobi are missing?

**Comment by rdeits** [comment]
(this came up because I spent a few hours trying to figure out why I had linker errors on Travis: it turned out that `libdrakeIK` existed, but just had no symbols in it since I had disabled snopt).

**Comment by RussTedrake** [comment]
how hard would it be to enable a useful piece when people have snopt but not gurobi?
maybe we can add it to the snopt precompiled module?

**Comment by tkoolen** [comment]
> Should we just disable building that library if snopt and gurobi are missing?
I actually did just that in https://github.com/RobotLocomotion/drake/pull/1514

**Comment by RussTedrake** [comment]
ok.  renaming this and making it a feature request

**Comment by RussTedrake** [comment]
this is almost resolved with the re-implementation of IK using the new optimization interface.  closing this issue.
