### ISSUE TITLE
How to show custom Multibody::Frame in Drake::Visulizer??

### ISSUE THREAD

**Issue by huihuishen** [RobotLocomotion/drake#15454]
> Before you post:
Hello, Is it possible to display custom frame to see if the position of the frame  is correct?

> * Have you reviewed the documentation on
[Getting Help](https://drake.mit.edu/getting_help.html)?
> * Have you reviewed existing GitHub issues and StackOverflow posts?
> * Have you rerun `install_prereqs.sh` on your current commit of `drake`?

> If you have encountered a bug (installation, segfaults, etc.), please try to
post reproduction steps and as much relevant output as possible. Consider
posting long snippets as a [Gist](https://gist.github.com/).

**Comment by jwnimmer-tri** [comment]
The https://drake.mit.edu/getting_help.html page linked from our issue template says "If you are seeking assistance ... please post a question on StackOverflow with the drake tag."  Therefore, this question belongs on StackOverflow please, not as a GitHub issue.  We like to reserve GitHub issues for bugs and feature requests only.

**Comment by huihuishen** [comment]
> The https://drake.mit.edu/getting_help.html page linked from our issue template says "If you are seeking assistance ... please post a question on StackOverflow with the drake tag." Therefore, this question belongs on StackOverflow please, not as a GitHub issue. We like to reserve GitHub issues for bugs and feature requests only.

ok,thank you very much!
