### ISSUE TITLE
Any tutorial or example for nonlinear model predictive control?

### ISSUE THREAD

**Issue by KeranYe** [RobotLocomotion/drake#15460]
Hi, 

I am currently learning the usage of the Drake library and would like to formulate a nonlinear model predictive control problem. The pydrake examples in the `/tutorial` show the methods to add costs and constraints. However, I am not sure **_how to integrate nonlinear (and maybe even switching) system dynamics into the optimization problem_**. Any examples or hints regarding such usage would be much appreciated.

Thanks,
Keran

**Comment by SeanCurtis-TRI** [comment]
The guidance for [getting help](https://drake.mit.edu/getting_help.html) for Drake recommends:

>  if you are seeking assistance (e.g. tutorials or a brief example), please post a question on StackOverflow with the drake tag.

As such, we'll be closing this issue in favor of the stackoverflow conversation.
