### ISSUE TITLE
GetActuationFromArray(.), GetPositions(ModelInstanceIndex), etc. should provide non-heap allocating versions

### ISSUE THREAD

**Issue by edrumwri** [RobotLocomotion/drake#15461]
We desire to access parts of vectors/state using already allocated Eigen vectors. It's presently very, very cumbersome to access subvectors of actuation vectors corresponding to model instances without allocating heap.

I suggest adding functions having the signature `GetActuationFromArray(ModelInstanceIndex, const Eigen::Ref<const VectorX<T>>&, EigenPtr<VectorX<T>>*)`, etc. to the API.

**Comment by jwnimmer-tri** [comment]
@edrumwri I believe many of these are resolved by #15900.

Do you still want `GetActuationFromArray`, or others that do not yet exist?

**Comment by xuchenhan-tri** [comment]
Following up on this issue -- @edrumwriare there still acute needs for more sugars for more getters?

**Comment by sherm1** [comment]
cc @edrumwri

**Comment by edrumwri** [comment]
This issue has been resolved for us.
