### ISSUE TITLE
TestLQR.TestException tests an uncontrollable system

### ISSUE THREAD

**Issue by hongkai-dai** [RobotLocomotion/drake#15481]
As @jwnimmer-tri mentioned in https://github.com/RobotLocomotion/drake/issues/15449#issuecomment-884554119, this test fails with Eigen 3.4.

I checked the test, but I am not sure if it's the problem of Eigen. Here we have `A = 0` and `B=0` in https://github.com/RobotLocomotion/drake/blob/66c9919c3809ee0ffd7be791486408112c119e98/systems/controllers/test/linear_quadratic_regulator_test.cc#L15-L23, hence the system is uncontrollable. I would think synthesizing an LQR for an uncontrollable system is problematic? Namely the code should fail in these two lines https://github.com/RobotLocomotion/drake/blob/66c9919c3809ee0ffd7be791486408112c119e98/systems/controllers/test/linear_quadratic_regulator_test.cc#L22-L23

@RussTedrake did I miss anything? That for an uncontrollable system we can still synthesize an LQR controller?

**Comment by RussTedrake** [comment]
I agree with you.  That's a bad test.  (I even confirmed that Matlab's LQR refuses to solve that case).  If you look at the history, I think it was a bad test that got more explicitly bad.  I'd recommend making A, B into the double integrator matrices.
