### ISSUE TITLE
Constraint id?

### ISSUE THREAD

**Issue by aespielberg** [RobotLocomotion/drake#1550]
Hi,

I'm trying to delete a BoundingBox constraint from a TrajectoryOptimization class.  There is a function I found:

deleteBoundingBoxConstraint: http://drake002.csail.mit.edu/drake/doxygen/class_nonlinear_program.html#ad22445f2609071fa5263146c792163e2

This function takes in an id.  However, I cannot find how to access the "id" of my bounding box constraint in the .bbcon field.  How do I access that?

**Comment by hongkai-dai** [comment]
Hi Andy,

The cnstr_id is returned as the second argument in `addBoundingBoxConstraint`, or `addConstraint`

**Comment by aespielberg** [comment]
Oh, I see, it returns two values.  Thanks!!
