### ISSUE TITLE
ubuntu 14.04 build on travis hangs at user prompt on installing prereqs

### ISSUE THREAD

**Issue by RussTedrake** [RobotLocomotion/drake#1553]
see discussion at #1549

**Comment by rdeits** [comment]
This is a known bug in the Travis trusty images: https://github.com/travis-ci/travis-ci/issues/4996

This will be fixed whenever they close that issue, or when we implement the prereq system we discussed (in which drake owns the list of prereqs for each option).

**Comment by david-german-tri** [comment]
Closing this as moot since we no longer use Travis.
