### ISSUE TITLE
cpp_template_pybind: AddTemplateFunction should support overloads

### ISSUE THREAD

**Issue by EricCousineau-TRI** [RobotLocomotion/drake#15570]
At present, it doesn't.

From @rpoyner-tri:
https://drakedevelopers.slack.com/archives/C3YB3EV5W/p1628173385005300?thread_ts=1628172481.004400&cid=C3YB3EV5W

> [...] `AddTemplateFunction("foo")` throws test/runtime errors if issued more than once with the same function name. `ImportError: ImportError: RuntimeError: Parameter instantiation already registered: (<class 'float'>,)` 

\cc @jwnimmer-tri

**Comment by jwnimmer-tri** [comment]
Not planned.  Generally we would try really hard to avoid binding templated functions in the first place.  Something like a `type=` kwarg, or inferring the template from the other kwargs types, is superior in most cases.
