### ISSUE TITLE
Deprecate schunk_buttons.py

### ISSUE THREAD

**Issue by jwnimmer-tri** [RobotLocomotion/drake#15583]
`drake/manipulation/schunk_wsg/schunk_buttons.py` is a helper script that isn't part of the build, isn't linted, isn't installed, and most probably totally unused.

Maybe we should deprecate and remove it?

Or if we keep it, it should probably move next to the other drake-visualizer scripts, and get linting & etc.

**Comment by RussTedrake** [comment]
Agreed.  I no longer need / use it.  Thanks!

**Comment by sammy-tri** [comment]
Go ahead and kill it.  Based on when it was written, I'd guess I probably last used that with the iiwa pick and place demo and the RBT enabled version of director.  Trivial to recreate or resurrect if needed.
