### ISSUE TITLE
pip install: Create wheel for Python 3.7

### ISSUE THREAD

**Issue by BetsyMcPhail** [RobotLocomotion/drake#15630]
Need to build a wheel on Ubuntu for a different version of Python (e.g. 3.7)

The goal, in theory, is to use Bionic (3.6) to build wheels that can target Focal (3.8) or Fedora (3.7)

Can use the https://github.com/RobotLocomotion/drake-python3.7 repo as a guide to what may need to be changed to specify the Python version.

Working towards #1183

**Comment by BetsyMcPhail** [comment]
@BetsyMcPhail will review https://github.com/RobotLocomotion/pip-drake/pull/15 and then we can call this complete

**Comment by jwnimmer-tri** [comment]
> @BetsyMcPhail will review RobotLocomotion/pip-drake#15 and then we can call this complete

This has been merged.
