### ISSUE TITLE
Builder::AddSystem should return System& (not System*)

### ISSUE THREAD

**Issue by RussTedrake** [RobotLocomotion/drake#15669]
`DiagramBuilder::AddSystem` returns a `System*`, but `AddMultibodyPlantSceneGraph` and `DrakeVisualizer::AddToBuilder` and others return `System&`.

The consensus on slack is that all of these should return `System&`, and that the Builder::AddSystem is simply a difficult-to-deprecate hold-over.  We also agree that it causes friction for users.  (Speaking for myself, it's been a long time since I wrote C++ code to construct a diagram, and have gotten all of the pointer vs references right without help from the compiler).

We should decide on a deprecation strategy and resolve it.

**Comment by jwnimmer-tri** [comment]
Just to drop in a related note -- this signature change might be a nice time to re-consider whether Drake's ownership-stealing classes that take in arguments by-unique-ptr (Diagram and Simulator) could switch to shared_ptr instead (#13058).  The fact that the framework steals and owns your graph makes it more difficult to change later, and makes pydrake reference counting extraordinarily difficult.  I would hate to add a new function here that returns a reference (and ask everyone to use it instead), only to switch to returning a `shared_ptr` a few months later.

**Comment by jwnimmer-tri** [comment]
> I'd vote against making this change.

Agreed.  The amount of disruption is not merited by the compliant.
