### ISSUE TITLE
meshcat: Trying to upgrade to latest commit, but some primitives can no longer be visualized?

### ISSUE THREAD

**Issue by EricCousineau-TRI** [RobotLocomotion/drake#15681]
Trying to upgrade to https://github.com/rdeits/meshcat/pull/97 (in order to address https://github.com/rdeits/meshcat/issues/93), but seems like something broke, at least on MeshCat C++.

Boxes and the flat face of the cylinder aren't rendering. FWIW, I see the 2 errors with the following message on Firefox console:
```
THREE.BufferGeometry.computeBoundingSphere(): Computed radius is NaN. The "position" attribute is likely to have NaN values. 
Object { uuid: "c58960d9-4cac-4036-ad2e-1aef26946dae", name: "", type: "BoxGeometry", index: {…}, attributes: {…}, morphAttributes: {}, morphTargetsRelative: false, groups: (6) […], boundingBox: null, boundingSphere: {…}, … }
main.min.js:2:219650
```

Command to test:
```
$ bazel run //geometry:meshcat_manual_test
# Open URL
```

Before, on master, bd762ab5e3
> ![image](https://user-images.githubusercontent.com/26719449/131256070-4e185e6a-6169-47a4-80fc-8bf916ac88d0.png)

After, on branch, 04a4a1ed4d:
RobotLocomotion/drake@master...EricCousineau-TRI:issue-meshcat-93
> ![image](https://user-images.githubusercontent.com/26719449/131255982-9394082a-9724-483c-b385-704cc3d65d02.png)

FYI @RussTedrake

**Comment by RussTedrake** [comment]
I've already got the upgrade and the fix waiting to be PR'd.  It is only blocked by #15679.
