### ISSUE TITLE
Update setup.py to not hard-code the Drake version

### ISSUE THREAD

**Issue by mwoehlke-kitware** [RobotLocomotion/drake#15695]
Currently, `setup.py` hard-codes the Drake version. Given that this is already out of date, and a presumably-unnecessary maintenance burden, we should add logic to obtain the version number from the Drake build instead.

(At least for now, however, we should also have a nice way to tack on an alpha/beta build number; e.g. as of writing, this would be `'a4'`.)

**Comment by jwnimmer-tri** [comment]
Related to #14509.

**Comment by mwoehlke-kitware** [comment]
This was (mostly) addressed by #16139. Although that requires passing the *complete* version when building the wheels, it is unclear if we have any intention of ever extracting partial version information from the repository, so perhaps this should be closed.

**Comment by jwnimmer-tri** [comment]
Yes, this is good enough for now.  The version number is not hard-coded anymore.
