### ISSUE TITLE
potentialCollisions returns a comical number of points for a capsule interacting with a flat terrain

### ISSUE THREAD

**Issue by RussTedrake** [RobotLocomotion/drake#1569]
the bullet implementation for multiple_contact support via potentialCollisions works well for e.g. box on box collisions (I think), but seems devastatingly inefficient for more complex geometries.  As an example, simulating a capsule falling into the (very large) box representing flat terrain generates as many points as there are permutations in the potentialCollisions method.  This seems likely to be true for most interesting collision geometries.  
It feels like I cannot turn this on by default.
The question is: is there a better way?  Or is this really the way that people do multi-contact resolution?

**Comment by avalenzu** [comment]
> . . . generates as many points as there are permutations in the potentialCollisions method.

So it generates eight contact points? Or am I reading the code wrong?

**Comment by RussTedrake** [comment]
I guess that’s probably right.  I thought I remembered seeing many more but am getting 4 contact points in my cylinder simulation now.  (perhaps I saw more when I had more serious penetration issues during my initial debugging).

**Comment by RussTedrake** [comment]
i talked to Erwin briefly today, and he says that he does not use this method in the main dynamics pipeline of bullet anymore.  He does some sort of surface clipping algorithm to calculate the polyhedral features.

**Comment by RussTedrake** [comment]
also had a great chat w/ Evan Drumright, who has some collision detection code which enumerates all potential collision cases to return the multi-points.  Sounds like it will be super useful to incorporate.

**Comment by avalenzu** [comment]
Sounds cool!
