### ISSUE TITLE
Archive RobotLocomotion/pip-drake-dependencies

### ISSUE THREAD

**Issue by jwnimmer-tri** [RobotLocomotion/drake#15721]
I believe that https://github.com/RobotLocomotion/pip-drake-dependencies is no longer used / no longer archive.  That means we should "archive" it, in GitHub, I believe?  Is that correct?

(If you agree but don't have the bits to archive it, let me know and I'll click the button.)

Towards #1183.

**Comment by mwoehlke-kitware** [comment]
I assume I have the bits, but since I'm not familiar with that process, feel free to go ahead and do it.

**Comment by mwoehlke-kitware** [comment]
(Also, I believe the entire repo is contained within pip-drake... n.b. robotlocomotion/pip-drake@ec00a8ca8505c393d619d674b96c53ee609f4308)

**Comment by jwnimmer-tri** [comment]
Done.
