### ISSUE TITLE
Visualize hydroelastic meshes

### ISSUE THREAD

**Issue by SeanCurtis-TRI** [RobotLocomotion/drake#15738]
## Problem
In the hydroelastic contact model, declared primitives types (e.g., spheres, cyliders, etc) are represented with a tessellated mesh. The amount of tessellation can depend on a configuration parameter and the resulting meshes (particularly if coarse) can deviate significantly from the idealized primitive. This has been known to lead to surprised users unable to interpret the contacts they are (or aren't) seeing. Being able to *see* the actual mesh involved in the contact can help users reason about the behavior they observe.

## Solution

Ultimately, we'll allow users to configure visualizers in a way that they can declare they'd like to visualize hydroelastic meshes, where available.

[This branch](https://github.com/SeanCurtis-TRI/drake/tree/PR_visualize_hydro_geometries) contains the "full" solution (as full as can be at any given time). The branch will be rebased frequently and pulling a local copy should bear this in mind.

### The plan
- [x] The python path
    - [x] #15707
        - [x] #15762
        - [x] #15773
- [ ] The C++ path
    - [x] #15739
    - [x] #15772
    - [ ] Enable `MeshcatVisualizer` (in `meshcat_visualizer.h`) to visualize hydro geometry. This is *not* defined in the [branch linked above](https://github.com/SeanCurtis-TRI/drake/tree/PR_visualize_hydro_geometries) yet.

**Comment by jwnimmer-tri** [comment]
Transcribing some notes from f2f discussions... hopefully I understood it correctly

The most important visualization is the contact patch mesh.
In the typical case, most users prefer to turn off pressure field visualization.

Thus, doing the patch mesh into MeshCat first would be the priority.

**Comment by jwnimmer-tri** [comment]
As best I can tell, the only remaining work here is to finish this TODO:

https://github.com/RobotLocomotion/drake/blob/6a5fb5acc19f937e9b08175838c09a6b1abde45d/visualization/visualization_config_functions.cc#L51-L52

**Comment by jwnimmer-tri** [comment]
My hypothesis is that #20179 has solved this.  Could either @joemasterjohn and/or @SeanCurtis-TRI please check and confirm, and close if so?

**Comment by jwnimmer-tri** [comment]
Closing for lack of response.
