### ISSUE TITLE
pip install: getDrakePath fails

### ISSUE THREAD

**Issue by BetsyMcPhail** [RobotLocomotion/drake#15769]
Working towards #1183

**Comment by jwnimmer-tri** [comment]
My best guess at a solution here would be for this line ...

https://github.com/RobotLocomotion/drake/blob/611a2f63796f5afa5cddccab7bf59279234f51aa/common/find_resource.cc#L261

... that we need to add a new option `(4)` that contains a new heuristic for the `pip` file layout.

Alternatively, perhaps the function that handles "installed" Drake heuristic ...

https://github.com/RobotLocomotion/drake/blob/611a2f63796f5afa5cddccab7bf59279234f51aa/common/find_resource.cc#L190

... could learn about the `pip` layout in addition to the FHS layout it already knows about.

**Comment by jwnimmer-tri** [comment]
> getDrakePath fails

Just to be totally clear, the function we need to repair will be `FindResource`, which is called by both `FindResourceOrThrow` and `MaybeGetDrakePath`, and `pydrake.getDrakePath` calls `GetDrakePath` which calls `MaybeGetDrakePath`.
