### ISSUE TITLE
Implement non-penetration constraint for nonlinear initial conditions

### ISSUE THREAD

**Issue by RussTedrake** [RobotLocomotion/drake#1577]
- [ ] basic nonlinear constraint class
- [ ] port snopt nonlinear program interface into the new optimizationproblem class
- [ ] implement actual non-penetration constraint
- [ ] convert the getInitialState logic to the optimization problem toolset

**Comment by jwnimmer-tri** [comment]
@RussTedrake I think you have been working on this?  Should this issue be reassigned to you?

**Comment by hongkai-dai** [comment]
There is a new issue #10700 , which add the non-penetration constraint for initial condition. I think we can close this commit?
