### ISSUE TITLE
Cull unused URDF and SDF files

### ISSUE THREAD

**Issue by SeanCurtis-TRI** [RobotLocomotion/drake#15797]
As observed in #15783 review (https://github.com/RobotLocomotion/drake/pull/15783#pullrequestreview-759938490), there appear to be URDFs that Drake is storing which are not used. We should determine which files actually provide value and cull those that don't. For those that *do* provide value which, nevertheless, are not currently referenced, some documentation should be provided so future developers won't have to repeat the task.

**Comment by jwnimmer-tri** [comment]
I believe I solve most of this when I moved files into `package://drake_models`.
