### ISSUE TITLE
pip wheels should not build static libxcrypt

### ISSUE THREAD

**Issue by BetsyMcPhail** [RobotLocomotion/drake#15806]
Related to #15632

libxcrypt is licensed under [LGPLv2.1](https://github.com/besser82/libxcrypt/blob/develop/LICENSING), as such, we must link it dynamically in the wheel (see related #15757)

For the history of why we need libcryptx, see the pip-drake [commit](https://github.com/RobotLocomotion/pip-drake/pull/15/commits/fad9860bbb1201e3461471c439e0b7ea3ce32462).

Currently, both static and shared versions of libxcrypt are built (https://github.com/RobotLocomotion/pip-drake/blob/57dccacfe02d5dc6906df0c19693b3c858b12d7f/image/dependencies/projects/libxcrypt.cmake#L9-L10).

We may already be shipping it dynamically (need to confirm). If so, the only action needed is to remove the static build as to prevent any accidental misuse.

**Comment by mwoehlke-kitware** [comment]
Fixed by RobotLocomotion/pip-drake#21.
