### ISSUE TITLE
consider InitAutoDiffTuple in cassie_bench

### ISSUE THREAD

**Issue by rpoyner-tri** [RobotLocomotion/drake#15820]
Motivated by comments here: https://github.com/RobotLocomotion/drake/pull/15615#pullrequestreview-762633724

Pro:
 * would clean up some egregious index/size math
 * would be a better example (perhaps) of AutoDiffXd usage
Con:
 * it's work

**Comment by jwnimmer-tri** [comment]
This should have been added as TODO comment during the pull request.  Failing that, we're not actually doing to do anything here.
