### ISSUE TITLE
//geometry:meshcat_visualizer_test times out under mac asan

### ISSUE THREAD

**Issue by ggould-tri** [RobotLocomotion/drake#15828]
Observed:
* https://drake-jenkins.csail.mit.edu/user/ggould-tri/my-views/view/Buildcop/job/mac-big-sur-clang-bazel-nightly-everything-address-sanitizer/228/
* https://drake-jenkins.csail.mit.edu/user/ggould-tri/my-views/view/Buildcop/job/mac-catalina-clang-bazel-nightly-address-sanitizer/712/
* https://drake-jenkins.csail.mit.edu/user/ggould-tri/my-views/view/Buildcop/job/mac-catalina-clang-bazel-nightly-everything-address-sanitizer/716/

Typical builds before were circa 10s, while the timeout is at 300s, so this is not a small regression that happened to cross an arbitrary time threshold.  This is likely due to #15788 or some close relative thereof.

This issue may already be resolved in more recent commits; if so it will be closed.  Otherwise it will be worked around by putting a no-asan tag on this test; however the underlying issue remains.

**Comment by ggould-tri** [comment]
CI indicates this bug was solved this morning, possibly by #15823.  Closing now.

**Comment by ggould-tri** [comment]
Reopening: This had another CI failure.

https://drake-jenkins.csail.mit.edu/view/Production/job/mac-big-sur-clang-bazel-nightly-address-sanitizer/227/

**Comment by ggould-tri** [comment]
The workaround is now in place.  This issue remains open as the underlying bug presumably remains.  I am assigning it a low priority for now, since it's not blocking anything.

**Comment by jwnimmer-tri** [comment]
When merging commits to master, please use descriptive subject lines ("Speed up meshcat C++ mtl parsing"); the issue number can be in the commit body, as supplemental information.  Issue numbers do not describe anything, on their own.
