### ISSUE TITLE
Upgrade to ibex-2.8.6

### ISSUE THREAD

**Issue by soonhokong** [RobotLocomotion/drake#15872]
We've found an issue with the current version of ibex (ibex-2.7.4) (see #15789). We will move to `ibex-2.8.6` to resolve the problem. For the record, `ibex>=2.8.7` dropped the CLP support which is the only freely available LP solver (up-to ibex-2.8.6). There is an attempt to bring the CLP support back to ibex, but it's still in-progress.

Action Items:
 - [x] ~Prepare `.deb` for `ibex-2.8.6`.~
 - [x]  ~Provide `ibex@2.8.6` in https://github.com/RobotLocomotion/homebrew-director/tree/master/Formula. Note that this requires generating homebrew bottles.~
 - [ ] Drake needs to use a version of dReal which is compatible with `ibex-2.8.6`.
 - [x] ~Need to update `setup` scripts to use `ibex-2.8.6`.~
 - [x] ~`IbexSolver` implementation needs a few changes to be compatible with `ibex-2.8.6`~

/cc @BetsyMcPhail for heads-up for infrastructure updates.
/cc @RussTedrake

**Comment by jwnimmer-tri** [comment]
> Prepare .deb for ibex-2.8.6.

Where is the deb rebuilding process documented, or more specifically, where does the source code for that `*.deb` originate from?  Since the code is LGPL, we need to ensure that we can provide the sources anytime we provide precompiled binaries.

**Comment by soonhokong** [comment]
It will be uploaded to https://launchpad.net/~dreal/+archive/ubuntu/dreal/+packages where you can download source code as well.

**Comment by RussTedrake** [comment]
ftr -- i have ibex 2.8.4 building from source in bazel now.  will PR it shortly.

**Comment by jwnimmer-tri** [comment]
The latest tag to dReal is 4.21.06.2.  I think we'll need a new version number tag, before we can upgrade.

**Comment by mwoehlke-kitware** [comment]
Just to add a wrinkle... the currently-used-by-drake version of ibex does not compile on Jammy.

**Comment by mwoehlke-kitware** [comment]
See also https://github.com/ibex-team/ibex-lib/issues/461; it appears upstream has re-added CLP support?

**Comment by jwnimmer-tri** [comment]
Not relevant anymore, per #18156.
