### ISSUE TITLE
parking garage urdf needs collision geometry

### ISSUE THREAD

**Issue by RussTedrake** [RobotLocomotion/drake#1589]
@Sproulx -- the parking garage urdf looks great. 

Unfortunately I need it to have the collision geometry, too, for the lidar simulation.  We could implement the option (which we have in matlab) to treat all collision geometry as visual geometry, or something similar, but I think the default should be to support both.

**Comment by Sproulx** [comment]
It should have collision geometry all ready. I'll see if I can figure out why it's not showing up.

**Comment by RussTedrake** [comment]
confirmed.  might have just been my mistake.
