### ISSUE TITLE
Publish manylinux 3.8 and 3.9 pip wheels

### ISSUE THREAD

**Issue by jwnimmer-tri** [RobotLocomotion/drake#15959]
For our stable releases, we should upload additional manylinux CPython wheels to PyPI.

- (We already publish Python 3.6.)
- (We already publish Python 3.7.)
- We should publish Python 3.8 (Focal default).
- We should publish Python 3.9 (bleeding edge).

It's probable that we should improve our whl release automation, testing, and CI prior to attempting this.

**Comment by jwnimmer-tri** [comment]
Requested ETA is Jan 7, 2021.

**Comment by jwnimmer-tri** [comment]
With #16199 merged, I believe that we're close to having 3.8 ready.  I'll open a WIP PR to discuss and evaluate.

**Comment by mwoehlke-kitware** [comment]
> With #16199 merged, I believe that we're close to having 3.8 ready.

Um... I was going to mutter something about needing VTK 9, but... yeah, if we aren't building VTK with Python any more, that should cease being a blocker. Hopefully, then, it Just Works™ and just needs additional targets added to `build-wheels`.

I was tentatively planning to keep Bionic as the base image and just add 38 and 39 Python versions. I believe these should be usable on Focal and Colab.

**Comment by jwnimmer-tri** [comment]
With #16226 merged, we have 3.8 now.  That only leaves 3.9 to wrap up.

I'm actually going to revise what I said this morning (which was that we should build the 3.9 wheels based on Ubuntu 18 inside Docker).  I think it would be fine to build the 3.9 wheels using Ubuntu 20 for the base build image (as well as the test image), if that makes it easier.  If users complain that the glibc is too new in that case, we can come back later and downgrade to 18 as a future enhancement, but I'll bet that nobody will complain.  We'll be dropping Ubuntu 18 support soon enough, anyway.

**Comment by mwoehlke-kitware** [comment]
So, um... it appears that 3.9 is going to be stalled until a new version of audithweel is released. Support for GLIBC 2.31 was only *just* added by pypa/auditwheel@167c75dbddf3af2bc7a7eaf647f877fb33c29896.

**Comment by jwnimmer-tri** [comment]
Looks like it was released yesterday.

**Comment by mwoehlke-kitware** [comment]
See #16308. Not marking that as "fixes" because the summary implies we should wait until a release gets published?

**Comment by jwnimmer-tri** [comment]
As of today's v0.38.0 release, we have CPython 3.6 through CPython 3.9 available for manylinux (and _supported_ for Ubuntu).
