### ISSUE TITLE
pip install drake known issues

### ISSUE THREAD

**Issue by jwnimmer-tri** [RobotLocomotion/drake#15954]
**[Installation via Pip](https://drake.mit.edu/pip.html)** documents our instructions for installing Drake via pip.

For ease of reference, this ticket will consolidate the known issues with `pip install drake`.
- [x] #17906
- [x] #15774
   - Some data files that are usually available as part of the Drake installation are not available in the PyPI wheel, because the files are too large
- [x] #16383
- [x] #15970
- [x] #15957
- [x] #16069
- [x] #15959
- [x] #15961
- [x] #15969
- [x] #15971
  - [x] #17162
- [x] #15958
- [x] #14702
- [x] #17483

Relates to #1183.

Note that sub-issues here are closed when the fix is merged to our master branch.  Not all fixes have been published to pypi yet.

**Comment by RandyChen233** [comment]
is there a way to install Drake in a windows machine? I'm getting the following error while attempting to install it in a Ubuntu terminal:
`ERROR: Could not find a version that satisfies the requirement drake (from versions: none)
ERROR: No matching distribution found for drake`

**Comment by jwnimmer-tri** [comment]
@RandyChen233 sorry you're having trouble!

For support requests, we have some advice in https://drake.mit.edu/getting_help.html -- in short, please post requests for troubleshooting help to StackOverflow, not the issues database.

For installing via pip, please see https://drake.mit.edu/pip.html for instructions.  Note that it links to https://drake.mit.edu/installation.html#supported-configurations which says what we can handle.  We don't support Windows-native wheels per se, but it sounds like you're using Ubuntu on WSL, perhaps.  Per those webpages and the known issues list above, note that we only offer Python 3.6 and Python 3.7 wheels at the moment.  My guess would be that you're trying to use Python 3.8 or newer.

Our wheels also require `pip >= 20.3`, which could also be the cause of that error.  I see now that our documentation doesn't mention this, though it does say to upgrade pip.  I'll update our docs to call out that pip version requirement specifically.

If you're still having trouble installing, please post a StackOverflow question and we can investigate via that forum.

**Comment by rcywongaa** [comment]
FWIW, currently, the default `python3-pip` package offered by Ubuntu 20.04 is `20.0.2` which is incompatible (Drake requires `pip >= 20.3`).

To use a newer pip version, one can do the following
```
python3 -m pip install --upgrade pip
```
and install drake with
```
python3 -m pip install drake
```

**Comment by jwnimmer-tri** [comment]
As of the forthcoming v1.15.0, I think all of the known issues will be fixed.

If anyone has new problems, please open a new issue for it.
