### ISSUE TITLE
Enable SNOPT in pip wheel

### ISSUE THREAD

**Issue by jwnimmer-tri** [RobotLocomotion/drake#15961]
For the https://github.com/RobotLocomotion/pip-drake build, we should build Drake using ` --define=WITH_SNOPT=ON` so that the binaries contain SNOPT, just like all of our other pre-built binaries.

This means that the build will require credentials, which will affect both the developer documentation (whl playbook) as well as #15960.

**Comment by jwnimmer-tri** [comment]
The victory condition here is that the CI "snopt packaging" builds that were added by #15960 produce wheels with SNOPT actually enabled.  (At the time the CI definitions will have been added for #15960, they would claim "snopt" in the their name, but SNOPT would not actually have been enabled yet.)

As with the existing snopt-packaging builds, they would use `RobotLocomotion/snopt`:

https://github.com/RobotLocomotion/drake-ci/blob/b7b58e8e9b14beb3b2c2a94251cc972e07c3e9ca/driver/configurations/cmake.cmake#L80

**Comment by jwnimmer-tri** [comment]
We pin our CI tested / released version of SNOPT here:

https://github.com/RobotLocomotion/drake/blob/57ad937d2fb3a283d0f76f5245472ac589048ee2/tools/workspace/snopt/repository.bzl#L53-L55

Ideally, the whl build would re-use that information directly, by having a working `git clone git@github.com:RobotLocomotion/snopt.git` during the Drake compile.  Alternatively, it could interrogate Drake for that git pin information, run the checkout, and then set `SNOPT_PATH` when building Drake.

**Comment by mwoehlke-kitware** [comment]
So... I think I have this working.

**CAVEAT**: There isn't an obvious, clean way to make SNOPT conditional, which means building the wheels (locally or via CI) will **require** an environment that can fetch SNOPT. Specifically, it means that `build-wheels.sh` must be run in an environment that a) has a working `ssh-agent`, which b) contains (a) key(s) suitable for fetching SNOPT from github ***without a `.ssh/config`***.

At least for me, this means spinning up a fresh agent and re-adding my keys. If you don't already use `ssh-agent`, you will need to do so.

**Comment by jwnimmer-tri** [comment]
If CI can do it, then I'm satisfied.  I don't foresee a large number of people needing to run the wheel build locally.  For those who do need to, some extra preparation steps are fine.

**Comment by jwnimmer-tri** [comment]
This fix was released in `drake==0.36.0`.
