### ISSUE TITLE
singular on rpy(0,pi/20)

### ISSUE THREAD

**Issue by xuhao1** [RobotLocomotion/drake#1596]
For a 6 dof system,drake will face singular problem on point
like q_hover = [0;0;0;0;-pi/2;0].
p.dynamics(0,[q_hover;qd],[0;0.0;10;10])
is that possible for using quaternion on present this state?
I am using a trick [0;0;0;0;-pi/2-0.01;0] now

**Comment by RussTedrake** [comment]
yes.  when you construct the rigid-body system, pass in the option to use the quaternion floating base.
