### ISSUE TITLE
iiwa14_spheres_collision.urdf model is always in self-collision (generating large contact forces)

### ISSUE THREAD

**Issue by RussTedrake** [RobotLocomotion/drake#15965]
This was generated in `meshcat_manual_test` in my forthcoming `MeshcatContactVisualizer` PR, but I'm sure it's reproducible in other viewers as well.
![meshcat (1)](https://user-images.githubusercontent.com/6442292/138572964-c233dd71-77da-4589-b123-31fbab8c0d9c.png)
![meshcat](https://user-images.githubusercontent.com/6442292/138572965-52668ec3-a43e-4672-b2ad-93a03c97ad91.png)

Probably worth adding a collision filter group to the URDF?

**Comment by RussTedrake** [comment]
i don't see this large force anymore when running meshcat_manual_test.  but I don't see any changes to the urdf file.  Not sure what happened?  Did the collision filtering implementation change?

We should remove the mention of this PR from meshcat_manual_test to consider this closed.  But I would like to understand...

**Comment by rpoyner-tri** [comment]
Was is fixed by the change in Mbp to filter all welded subgroups by default? This was in PR https://github.com/RobotLocomotion/drake/pull/16920

**Comment by RussTedrake** [comment]
I bisected and found that it was fixed in #16325.
