### ISSUE TITLE
CI builds for pip wheels

### ISSUE THREAD

**Issue by jwnimmer-tri** [RobotLocomotion/drake#15960]
We need CI coverage for our pip wheels.

It seems like the best way to go about this would be to add the following builds to Drake's Jenkins:

* `manylinux-unprovisioned-py36-experimental-snopt-packaging`
* `manylinux-unprovisioned-py36-nightly-snopt-packaging`
* `manylinux-unprovisioned-py37-experimental-snopt-packaging`
* `manylinux-unprovisioned-py37-nightly-snopt-packaging`

To start out, they should not be in the `Production` tab.  Later, we can promote them there.

To start out, the "snopt" label will be a lie (since we don't turn on SNOPT yet), but hopefully very soon we will, and it's probably not worth churning CI names as we do that.

The build would run on an unprovisioned Bionic instance, and then run the `pip-drake` build script.  If the build (and any automated tests within `pip-drake`) fail, CI should fail.

I think it makes sense to separate to one whl variant per build, so that they all run in parallel.  (Thus, the py36, py37, etc., above.)  I suppose we might as well define `py38` and `py39` in CI while we're at it, even though they probably won't succeed right now.

For now, this build should not publish the resulting `*.whl` files anywhere.  Later, we will probably want to upload them to S3 for inspection, but only after #15695 gets fixed.

**Comment by jwnimmer-tri** [comment]
> The build would run on an unprovisioned Bionic instance ...

Our maintainer tools and release process are shifting to Focal now (#16066), so I'll change my mind here -- the `manylinux` CI builds should run on an unprovisioned Focal instance.  (The Docker containers that the automated pip build scripts _launch_ will still be Bionic, but the CI images don't care about that.)

> ... run the pip-drake build script ...

The `pip-drake` repository has moved into Drake now, so the build scripts are in https://github.com/RobotLocomotion/drake/tree/master/tools/wheel now.

**Comment by BetsyMcPhail** [comment]
The experimental build, [linux-focal-unprovisioned-gcc-wheel-experimental-snopt-release](https://drake-jenkins.csail.mit.edu/view/Wheel/job/linux-focal-unprovisioned-gcc-wheel-experimental-snopt-release/) has been added to Jenkins and runs successfully. The pip build [always uses SNOPT](https://github.com/RobotLocomotion/drake/issues/15961), so we could create _linux-focal-unprovisioned-gcc-wheel-experimental-release_ instead but it seems more informative to include 'snopt' in the name. If this naming convention is ok, then I will create an equivalent nightly build and clean-up the unused wheel jobs.

**Comment by jwnimmer-tri** [comment]
I agree that we should always have "snopt" in the name for snopt-enabled builds.

The original ticket above requested one build per CPython version, so that they could all run in parallel.  If you are not going that route, please explain why in the ticket here.

**Comment by BetsyMcPhail** [comment]
@mwoehlke-kitware can you please comment on the all builds in one job decision

**Comment by mwoehlke-kitware** [comment]
My understanding was that we wanted `build-wheels`, which CI wraps, to build everything, so that we aren't enumerating the possible wheels in multiple places. It shouldn't be difficult to tweak things so CI passes in arguments to select a single wheel, but my understanding was that that isn't desired?

**Comment by jwnimmer-tri** [comment]
@BetsyMcPhail 

There are two spurious jobs defined currently:
- [linux-focal-unprovisioned-gcc-wheel-experimental-release](https://drake-jenkins.csail.mit.edu/view/Wheel/job/linux-focal-unprovisioned-gcc-wheel-experimental-release/)
- [linux-focal-unprovisioned-gcc-wheel-experimental-everything-release](https://drake-jenkins.csail.mit.edu/view/Wheel/job/linux-focal-unprovisioned-gcc-wheel-experimental-everything-release/)

Please remove both of them -- there should not be any non-snopt nor "everything" builds of the wheels.  There is only ever one allowed configuration for the wheel's mathematical solvers, which is "snopt" hard-coded to be "ON" [1].

After that, please add a "nightly" flavor of the one remaining "experimental" wheel build, and then we'll close this ticket.

[1]
https://github.com/RobotLocomotion/drake/blob/53108a927153a68f757f041459225bbd51d879da/tools/wheel/dev/image/build-drake.sh#L18

---

@mwoehlke-kitware 

> ... but my understanding was that that isn't desired?

Well, the call to action atop this issue said the exact opposite.  Please take the time to read the tickets more carefully in the future.

We'll keep the status quo for now, just to not spend any more time on this issue.  We have more important things to focus on at the moment.

**Comment by BetsyMcPhail** [comment]
We were on the same page regarding the experimental builds, I was hoping to to do one update to the jenkins jobs builder when the naming scheme was finalized.

drake-jenkins-jobs has been [updated](https://github.com/RobotLocomotion/drake-jenkins-jobs/commit/512fabac0d303d907761dffa782dd10ca76bf3ad) to create an experimental and nightly wheel build. Note the nightly build is _NOT_ production (yet).

Wheel builds can be viewed in Jenkins [here](https://drake-jenkins.csail.mit.edu/view/Wheel/)

**Comment by jwnimmer-tri** [comment]
Thanks!

As we did with Monterey, we'll let the nightly Wheel build run for a while non-production (maybe through the weekend), and then next week we can promote it to Nightly Production.
