### ISSUE TITLE
precompile swig-matlab

### ISSUE THREAD

**Issue by RussTedrake** [RobotLocomotion/drake#1597]
it's a huge slow download, and doesn't appear to actually change.
the actual swig binary (all that we need) is only 1.8 mb.  plus we're not actually successfully building it on windows.

**Comment by rdeits** [comment]
Another option would be to commit the C++ and python/matlab sources generated by Swig into the repo. That would totally remove the Swig dependency, but would also pollute the repo substantially. I don't think we should do it, but it's an option.

**Comment by RussTedrake** [comment]
closing as duplicate of #1939
