### ISSUE TITLE
runAtlasJumping fails (immediately)

### ISSUE THREAD

**Issue by RussTedrake** [RobotLocomotion/drake#1599]
turned a warning into an error and caught a few bugs.  I suspect this has been failing for a long time.  the first call to solveLCP has u coming in with all nans.  

<matlab_test>strcmp(test_name,'examples/Atlas/runAtlasJumping')</matlab_test>

**Comment by hongkai-dai** [comment]
I turned `use_mex` to `0` in QPController, and then the controller does not output `nan`. I will look into the   `QPControllermex` function

**Comment by rdeits** [comment]
I'm going to delete the entire QPControllermex implementation and flip this test to use the QPController matlab implementation. QPController is the old controller anyway, and it's only being used for this test and for `runAtlasRunning`, so there's no reason to keep or support its non-functional C++ implementation. 

Eventually, we'll port the running and jumping examples to the new controller anyway.
