### ISSUE TITLE
macOS support for Monterey

### ISSUE THREAD

**Issue by jwnimmer-tri** [RobotLocomotion/drake#16001]
https://en.wikipedia.org/wiki/MacOS_Monterey was released last Monday.

We should add Drake support for it, including CI variants.

- [x] Update Drake documentation to remove mentions of Catalina (and indicate that Monterey support is pending).
  - [x] #16041
- [x] Change nightly packaging build to use Big Sur
  - [x] https://github.com/RobotLocomotion/drake-ci/pull/126
  - [x] #16053
- [x] #16054
- [x] #16055
- [x] #16068
- [x] Add Monterey builds (and base images) to CI (non-production).
- [x] Fix any build issues (none).
- [x] Let CI run over the weekend to confirm it's stable.
- [x] https://github.com/RobotLocomotion/drake/pull/16124
- [x] Upgrade Monterey CI builds to production

**Comment by ggould-tri** [comment]
Would it make sense for me to hold the 0.36.0 release for this issue, or do we expect it to be some time away yet?

**Comment by jwnimmer-tri** [comment]
The CI builds should be up relatively soon, at which point we can see how close we are.  In theory, the Big Sur binaries should already work perfectly on Monterey.  In practice... we'll see!

**Comment by BetsyMcPhail** [comment]
The Mac Monterey experimental jobs are up on Jenkins to test out. 

The [unprovisioned build](https://drake-jenkins.csail.mit.edu/view/Mac%20Monterey%20Unprovisioned/job/mac-monterey-unprovisioned-clang-bazel-experimental-release/1/console) needs some updates on the image itself. Current error:

```
[5:00:34 PM]  +/Users/monterey/workspace/mac-monterey-unprovisioned-clang-bazel-experimental-release/ci/setup/mac/install_prereqs:60> brew update
[5:00:34 PM]  Error: Can't create update lock in /usr/local/var/homebrew/locks!
```

The [provisioned build ](https://drake-jenkins.csail.mit.edu/view/Mac%20Monterey/job/mac-monterey-clang-bazel-experimental-release/2/consoleFull) is failing with:

```
[5:00:47 PM]  ERROR: An error occurred during the fetch of repository 'python':
[5:00:47 PM]     Traceback (most recent call last):
[5:00:47 PM]  	File "/Users/monterey/workspace/mac-monterey-clang-bazel-experimental-release/src/tools/workspace/python/repository.bzl", line 136, column 37, in _impl
[5:00:47 PM]  		py_info = repository_python_info(
[5:00:47 PM]  	File "/Users/monterey/workspace/mac-monterey-clang-bazel-experimental-release/src/tools/workspace/python/repository.bzl", line 65, column 13, in repository_python_info
[5:00:47 PM]  		fail(os_result.error)
[5:00:47 PM]  Error in fail: could not determine macOS version: unsupported macOS '12'
```

We need an update to [os.bzl](https://github.com/RobotLocomotion/drake/blob/e637144d8deadeabd2c99638d9af2d34ffbc5f8c/tools/workspace/os.bzl#L140)

**Comment by jwnimmer-tri** [comment]
:facepalm: I'll do the `os.bzl` PR now.

**Comment by BetsyMcPhail** [comment]
[mac-monterey-clang-bazel-experimental-release](https://drake-jenkins.csail.mit.edu/view/Mac%20Monterey/job/mac-monterey-clang-bazel-experimental-release/4/console) succeeded!

**Comment by BetsyMcPhail** [comment]
All of the Monterey experimental jobs passed. Monterey non-production continuous and nightly jobs have been added to Jenkins ([drake-jenkins-jobs](https://github.com/RobotLocomotion/drake-jenkins-jobs/commit/4fe98d84e6c36917469e6d7b82460c99b8611a64))

**Comment by jwnimmer-tri** [comment]
Very cool!  My proposal would be to run it in non-production from now through the weekend, and then (assuming all has a gone well) promote to production and add it as "supported" in our installation docs next week.

**Comment by BetsyMcPhail** [comment]
Monterey Continuous and Nightly jobs have been moved to Production.

**Comment by jwnimmer-tri** [comment]
I see that https://drake-jenkins.csail.mit.edu/view/Nightly%20Production/ and https://drake-jenkins.csail.mit.edu/view/Continuous%20Production/ have Monterey, but the https://drake-jenkins.csail.mit.edu/view/Production/ summary tab still lacks them.  The latter should always be the sum of the two former.

**Comment by BetsyMcPhail** [comment]
Good catch - unfortunately it's a manual process to update each tab. The Production tab includes Monterey now.
