### ISSUE TITLE
Visualizer bugs when display quaternion-based model.

### ISSUE THREAD

**Issue by xuhao1** [RobotLocomotion/drake#1602]
Model on some pose,for example   0.641,0,-0.710,0(w x y z) to 0.641,0,-0.705,0 will cause display jump 
<img width="1365" alt="2016-01-13 4 14 14" src="https://cloud.githubusercontent.com/assets/5087930/12288619/c24e49c6-ba10-11e5-8905-36fc6026b480.png">
<img width="1360" alt="2016-01-13 4 14 21" src="https://cloud.githubusercontent.com/assets/5087930/12288625/cbb0a95a-ba10-11e5-875b-2659e358a354.png">

and program gives follow warning on that point
```
infeasible_constraint_name = 

    'base quat norm = 1'

Warning:   13 nonlinear infeasibilities minimized
 
> In NonlinearProgram/mapSolverInfo (line 1551)
  In NonlinearProgram/snopt (line 1427)
  In NonlinearProgram/solve (line 980)
  In Visualizer/inspector/update_display (line 306) 
```
And there are serval points can cause that problem.

When playback, it looks like my drone transmit from one pose to another pose....But as we know,SO3 is a differential manifold....
I guess when treat quaternion as a constrain here, the solver will fail at solving that constrain.Maybe normalize it direct will be better.
Appendix, rpy value for quad, we can see there is no cliff on this point.
```matlab
>> [r,p,y] = quat2angle( [0.641,0,-0.710,0])

r =

    3.1416


p =

   -1.4687


y =

    3.1416

>> [r,p,y] = quat2angle( [ 0.641,0,-0.705,0 ])

r =

    3.1416


p =

   -1.4758


y =

    3.1416
```

**Comment by RussTedrake** [comment]
I don’t consider that a visualizer bug.  You are passing an ill-defined coordinate (since the norm does not equal 1).

**Comment by xuhao1** [comment]
Ithat value isn't generate by my self,but by robot manipulator dynamics make it don't normalized .and also when using inspector, the norm haven't be keep either...

**Comment by RussTedrake** [comment]
I looks like it came out of an optimization?  the infeasible constraints warning means that the optimization failed.  we’ll need a test case to debug it.

**Comment by xuhao1** [comment]
Sure ... It looks like quaternion was solved as a constrain.

**Comment by xuhao1** [comment]
Alright...my fault,when I use the up-to-date code everything goes prefect...
