### ISSUE TITLE
Specify Geometry Role in SDF visual tag

### ISSUE THREAD

**Issue by TheCynosure** [RobotLocomotion/drake#16043]
I have an SDF that has two possibly models that represent it at different levels of detail. I would like to be able to specify one as an Illustration model and another as a Perception model. This way I can have a lower detail model for the visualizer and higher detail model available for my sensors.

**Comment by SeanCurtis-TRI** [comment]
Here's the shape of the basic solution:

We currently support the `<drake:proximity_properties>` custom tag for both sdf and urdf. It has always been the intent of providing `<drake:illustration_properties>` and `<drake:perception_properties>` as well. Adding these missing tags is the crux of the solution.

Special notes:
  - The current default behavior is that a `<visual>` geometry is used for both illustration and perceptions roles. This should remain the default behavior if neither of the drake role tags are provided.
  - For the diffuse rgba value, for the files that allow definition of *materials*, the rgba value should still be configurable by referencing a defined material.

**Comment by jwnimmer-tri** [comment]
See also #13689 and #11746.

**Comment by jwnimmer-tri** [comment]
> See also https://github.com/RobotLocomotion/drake/issues/13689 and https://github.com/RobotLocomotion/drake/issues/11746.

Those tickets have more information, and as far as I can tell it's the identical request.  Closing this a duplicate of those.
