### ISSUE TITLE
Remove Catalina builds from CI

### ISSUE THREAD

**Issue by jwnimmer-tri** [RobotLocomotion/drake#16054]
Per the plan in #16001, we can turn off Catalina support now.  All of the Jenkins builds for Catalina should be removed.

**Comment by BetsyMcPhail** [comment]
Catalina jobs have been removed and [drake-jenkins-jobs configuration](https://github.com/RobotLocomotion/drake-jenkins-jobs/commit/06ce9b0c26dc023ccf088d966e00cddeed5c3b8a) has been updated.
