### ISSUE TITLE
Installation issue on windows 10

### ISSUE THREAD

**Issue by XuanLin** [RobotLocomotion/drake#1608]
Hi everyone,

I installed drake on my windows 10 system. At the end of the installation I am getting this error:

"C:\Users\Xuan\Documents\simulation\drake-distro\pod-build\ALL_BUILD.vcxproj" (default target) (1) ->
"C:\Users\Xuan\Documents\simulation\drake-distro\pod-build\drake.vcxproj" (default target) (10) ->
(CustomBuild target) ->
  CUSTOMBUILD : error : MEXEXT: Unsupported platform. [C:\Users\Xuan\Documents\simulation\drake-distro\pod-build\drake.
vcxproj]

I run the cartpole example and it is working, but when I try Hongkai's optimal grasp :
testIKGrasp.m

I get this error:

Error using checkDependency (line 442)
Cannot find required dependency: spotless

Error in testIKGrasp (line 5)
checkDependency('spotless');

and we figure out that spotless is downloaded but not installed, so I manually installed it (run spot_install.m), then another error occurs:

Error using checkDependency (line 442)
Cannot find required dependency: lcmgl

Error in testIKGrasp (line 10)
checkDependency('lcmgl');

So we guess that there are still some part of drake which is not installed. Does anyone know how to fix it?

I follow the instructions on wiki and Cmake/Gnu are here:
![capture](https://cloud.githubusercontent.com/assets/10069542/12317049/fb4895a2-ba41-11e5-8e2c-75260cd8715c.JPG)

I am using Microsoft Visual Studio 2015 Community as compiler, and the system variable looks like this:

![image](https://cloud.githubusercontent.com/assets/10069542/12317190/98323bc4-ba43-11e5-9e18-226242a2261a.png)

![image](https://cloud.githubusercontent.com/assets/10069542/12317207/cba26ce0-ba43-11e5-96d5-77b9b040ac42.png)
(it looks like there is a mismatch on Cmake location, but I resolved this issue, the error persists)

Thank you!

**Comment by hongkai-dai** [comment]
Is this still a bug? Which version of cmake are you using? According to this page, http://answers.opencv.org/question/44589/opencv-30-problems-building-dlls-and-libs/, you might check your cmake version, and the linker setting. @RussTedrake , have we tested drake installation on a Windows 10 platform?

**Comment by RussTedrake** [comment]
I've not tested on Windows 10 recently -- i used to, but then someone told me that very few people use windows 10.  :)

If there are many users out there, it would be good to know it.

**Comment by XuanLin** [comment]
I get Cmake from the link given by wikipedia, so that should be the latest version-3.4.2. I can double check it tomorrow when I reach out to my laptop.

By the way it is true that more people work on linux in our lab. But our group do need windows for some specific reason.

**Comment by RussTedrake** [comment]
We definitely want to support windows.  But why windows 10?  I thought most people had decided that Windows 7 was still the best for now…?

**Comment by XuanLin** [comment]
Yes, people update to win 10 and quit due to issue of driver support, I just haven't met any issue yet. I can go back if it's needed.

**Comment by RussTedrake** [comment]
I’m sure it can work.  Just trying to gage the audience.

**Comment by XuanLin** [comment]
I guess when we are not actually communicating with hardware then windows 10 is fine. People in my lab tend to put win10 on personal computer and doing hardware control on a linux machine (I do it on the lab computer, which doesn't have matlab). 
Anyway, let me know if you are going to test it or not, so I can make decisions.
Thanks!

**Comment by RussTedrake** [comment]
We’ll test it, but probably not in the next few weeks.

**Comment by RussTedrake** [comment]
what happens when you run `mex -setup` at the matlab prompt?

**Comment by XuanLin** [comment]
![image](https://cloud.githubusercontent.com/assets/10069542/12533578/ddbeb10c-c1e8-11e5-8398-584a1fea29b0.png)

**Comment by RussTedrake** [comment]
Is it also set up for c++?

**Comment by XuanLin** [comment]
I didn't do mex -setup C++, you want me to try if this solves the issue?

**Comment by RussTedrake** [comment]
Yes please.  That's relatively new in matlab that they're separate.  Perhaps we need to make the install instructions clearer..?

**Comment by XuanLin** [comment]
The issue is still there...
![image](https://cloud.githubusercontent.com/assets/10069542/12533956/5525efc0-c1f9-11e5-8119-3cee97efc9eb.png)

One question:  When I type make option and open up a Cmake, what should I put in "Where is the source code"? I just put "C:/Users/Xuan/Documents/GitHub/drake-distro", so it looks like this:
![image](https://cloud.githubusercontent.com/assets/10069542/12533957/67c0ca38-c1f9-11e5-8a91-32c5eeb30c66.png)

**Comment by XuanLin** [comment]
I double try it. The error occurs right here, if it's useful:
![image](https://cloud.githubusercontent.com/assets/10069542/12534136/3f37ecde-c200-11e5-9cd8-6e73f1e37fbc.png)

**Comment by RussTedrake** [comment]
Is your matlab installed on the P drive? 

Try this:  edit drake-distro/drake/cmake/mex.cmake, line 111.

change 
```
execute_process(COMMAND ${mexext} OUTPUT_VARIABLE MEX_EXT OUTPUT_STRIP_TRAILING_WHITESPACE)
```
to
```
execute_process(COMMAND "${mexext}" OUTPUT_VARIABLE MEX_EXT OUTPUT_STRIP_TRAILING_WHITESPACE)
```
and let me know.

**Comment by RussTedrake** [comment]
you might have to do something similar on line 124.  `${mex}` to `"${mex}"`

**Comment by XuanLin** [comment]
Do you mean this:
![image](https://cloud.githubusercontent.com/assets/10069542/12541166/c80f91ac-c2c7-11e5-851d-358891e3fdc0.png)

I am not sure... When I install drake, I do mex -setup -> git clone -> make options -> make -> addpath_drakeup, up to stetup make options the cmake folder is still empty, so do you mean I that I edit after installation? But the error occurs during installation...

**Comment by RussTedrake** [comment]
That's correct.  Take the current partially-installed directory and make these local edits.  The run make again to see if it helps

**Comment by XuanLin** [comment]
Unfortunately no, the error persists, although it takes less time to finish.
![image](https://cloud.githubusercontent.com/assets/10069542/12608514/6c2bcd44-c491-11e5-94cb-efb1302c06e5.png)

**Comment by RussTedrake** [comment]
This is hard to debug remotely.  For what it’s worth, it looks the same as the issue here:
http://answers.opencv.org/question/44589/opencv-30-problems-building-dlls-and-libs/

Can you confirm that your matlab is installed in the P:\ drive?  (perhaps send the complete path) 
Do you have multiple versions of matlab installed on the machine?  (is there any chance you’re running mex -setup in one, and then cmake is finding a different one)?

**Comment by XuanLin** [comment]
Sorry for the delay here...

Matlab is on P drive, with directory:
P:\Program Files\MATLAB\Matlab2015b\bin\Matlab.exe

I don't have multiple Matlabs on my laptop. Anyway, I will find some way around, maybe use a different operating system.

Thank you!
