### ISSUE TITLE
addpath_drake cannot find pod-build/bindings/matlab folder

### ISSUE THREAD

**Issue by cyndiac** [RobotLocomotion/drake#1613]
I got the same build error with swig as in Issue https://github.com/RobotLocomotion/drake/issues/1604

I turned off swig_matlab in `make options` and the make finished, but when I try to run `addpath_drake` I get the following error because I don't have the folder it is looking for.

`Warning: Name is nonexistent or not a directory: /home/cyndiac/drake-distro/drake/pod-build/bindings/matlab`

However when I comment out this line (line 64), functionality still seems normal, at least for the pulley examples.

**Comment by rdeits** [comment]
ok, thanks. fix is incoming...
