### ISSUE TITLE
Rename and document geometry::MeshFieldLinear::TransformGradients()

### ISSUE THREAD

**Issue by DamrongGuoy** [RobotLocomotion/drake#16168]
After the main task in #15796 is completed, we should clean up geometry::MeshFieldLinear::TransformGradients().
1. Rename it to TransformField(). In addition to changing the gradients, the new coordinates frame also affects an internal representation of the field.
2. Document that it is "(Advanced)".
3. Coordinate the change of coordinates frames in the field with the reference mesh somehow (not sure yet).

**Comment by DamrongGuoy** [comment]
CC: @SeanCurtis-TRI @sherm1

**Comment by jwnimmer-tri** [comment]
Fixed in #16160.
