### ISSUE TITLE
pydrake Visualization problems

### ISSUE THREAD

**Issue by SeanCurtis-TRI** [RobotLocomotion/drake#16183]
A user [has reported that a pydrake program isn't updating visualization state to match plant state](https://stackoverflow.com/questions/69950297/plant-setpositions-does-not-update-visualization/69951636?noredirect=1#comment124147042_69951636).

The discussion (and example code), such as it is, can be found at the stackoverflow link. An earlier error in specifying pose has apparently been reconciled but the visualizer is still not reflecting the expected poses.

Someone should look into it. Note, although labeled pydrake, the problem isn't necessarily related to pydrake (that's just the medium in which the error has been exposed).

**Comment by jwnimmer-tri** [comment]
There is a bug in the sample program.

The `plant_context` is the thing being mutated.  It is a view of the simulator's context.

The context being published from is `diagram_context`, which is completely unrelated to the simulator and plant context.

```python
diagram = builder.Build()
diagram_context = diagram.CreateDefaultContext()
simulator = Simulator(diagram)
plant_context = plant.GetMyContextFromRoot(simulator.get_mutable_context())
plant.SetPositions(plant_context, q.copy())
diagram.Publish(diagram_context)
```
