### ISSUE TITLE
Update swig-matlab to include bison pre-requisite

### ISSUE THREAD

**Issue by iamwolf** [RobotLocomotion/drake#1622]
Installing pre-requisites and then compilingthe current drake head from scratch is failing on my Ubuntu 14.04 system with an error that yacc wasn't installed (which was accurate). It's a pre-req for swig-matlab, but wasn't included in the list of pre-requisites so far.

Cf. https://github.com/rdeits/swig-matlab/pull/1

**Comment by rdeits** [comment]
Ah, that makes sense. It must have been coming in with another Drake pod. I've merged your PR on swig-matlab.
