### ISSUE TITLE
pydrake yaml_dump() of a schema object fails

### ISSUE THREAD

**Issue by ggould-tri** [RobotLocomotion/drake#16262]
The python expression `yaml_dump(UniformVectorX(min=[1.], max=[2.]))` surprisingly fails.
Per https://app.slack.com/client/T0JNB2DS4/C3YB3EV5W/thread/C3YB3EV5W-1640023403.047200 this is the intended behaviour (yaml_dump is not intended to be class-aware) but from a usability perspective it's a bit obnoxious because, correct construction of the tagged map for a schema object is typo-prone and can cause confusing runtime errors.

**Comment by sherm1** [comment]
Assigning to @ggould-tri initially -- please feel free to reassign.

**Comment by jwnimmer-tri** [comment]
The missing feature we want is #19597.  After that, the call to action for this ticket is to make sure that the `yaml_dump` example above gives a good message that points people to `yaml_dump_typed`.

**Comment by jwnimmer-tri** [comment]
... and that is finished.  The only remaining work here is to check and improve the error message.
