### ISSUE TITLE
Support compliant convex geometry for hydroelastic contact

### ISSUE THREAD

**Issue by hongkai-dai** [RobotLocomotion/drake#16278]
See the slack discussion: https://drakedevelopers.slack.com/archives/C2WBPQDB7/p1640137283135300

Currently we don't support compliant convex geometry for hydroelastic contact. When we have a compliant convex geometry, it will incur the point contact query, which is not differentiable, causing issue with MBP<AutoDiffXd>

**Comment by DamrongGuoy** [comment]
@rcory needs it (for a different purpose) too.

**Comment by DamrongGuoy** [comment]
@joemasterjohn is drafting PR #16753 that should fix this issue #16278.
