### ISSUE TITLE
Acceleration/Jerk level constraint for trajectory optimization using Direct collocation

### ISSUE THREAD

**Issue by Mahdi-Javadi** [RobotLocomotion/drake#16295]
I wanted to know if there is an elegant way to impose acceleration/jerk level constraint on the trajectory optimization using the DirectCollocation class. 
I am working with an Acrobot system, and I have already included the velocity level constraint, but I wanted to have a minimum/smooth jerk optimal trajectory. 
This is also posted on https://stackoverflow.com/questions/70540739/acceleration-jerk-level-constraint-for-trajectory-optimization-using-direct-coll.
Thank you in advance.

**Comment by sherm1** [comment]
Thanks Mahdi. I'll close this in favor of the answer you got on StackOverflow.

**Comment by Mahdi-Javadi** [comment]
Dear Michael,
Thank you so much
