### ISSUE TITLE
Reconfigure causes unnecessary rebuild

### ISSUE THREAD

**Issue by patmarion** [RobotLocomotion/drake#1630]
If I run make from drake/pod-build with all targets up to date, it runs very quickly, nothing rebuilds.  If I reconfigure cmake, then make will recompile some files and re-link almost everything, this takes a long time.  This often occurs when cmake configure rewrites generated files which are compile dependencies.  Sometimes this is easy to fix, sometimes you have to implement more robust dependency logic.  In this case, maybe it's from Path.h?  There might be others.  Path.h could be generated with the configure_file() command which properly tracks dependencies, rather than file(WRITE).

**Comment by RussTedrake** [comment]
I'll bet you're right.  Path.h is probably causing it.  Good call.

**Comment by patmarion** [comment]
If you'd like, I can try writing a pull request to use configure_file() to generate Path.h.  I would make a new file called Path.h.in in the source director which cmake will copy to the build generated directory with the configure_file() command.

**Comment by RussTedrake** [comment]
Sounds great.  Thank you.
