### ISSUE TITLE
[tutorials] mathematical_program.ipynb does not render math properly in deepnote

### ISSUE THREAD

**Issue by RussTedrake** [RobotLocomotion/drake#16316]
I'll fix most of these, but this one is going to take some work/creativity.  

I've added a few notes about latex rendering in the readme in https://github.com/RobotLocomotion/drake/pull/16314.

@hongkai-dai -- can you take this one?

Notebook is here: https://deepnote.com/project/Tutorials-K0_FCa7yQX2kDWBx3-2RmQ/%2Fmathematical_program.ipynb

**Comment by shensquared** [comment]
Fwiw, [Mathpix](https://mathpix.com/) should help automate it somewhat (i.e. make it less tedious and errer-prone) if this is just a matter of complying with `$\begin{aligned}` KaTeX delimiters?
