### ISSUE TITLE
`UnitInertia::SolidCapsule(...)`

### ISSUE THREAD

**Issue by RussTedrake** [RobotLocomotion/drake#16342]
We support the Capsule shape, but don't offer the helper method for computing it's unit inertia.  I need it for the mujoco parser.
https://drake.mit.edu/doxygen_cxx/classdrake_1_1multibody_1_1_unit_inertia.html

I hope this is a quick request.  It should be simple!  @sherm1 -- could you please delegate so we can knock it out?

**Comment by sherm1** [comment]
@xuchen, for a look at another part of the code can I interest you in adding the inertia properties for capsule and ellipsoid to UnitInertia? Russ would like this asap. LMK if you can't fit this in soon.

**Comment by xuchenhan-tri** [comment]
Sure. I'll take a stab today, but it might be tight with RTO stuff and meetings. Tuesday for sure.

**Comment by RussTedrake** [comment]
Perfect.  Thank you!
