### ISSUE TITLE
Implement `CalcVolume` for mesh shapes

### ISSUE THREAD

**Issue by RussTedrake** [RobotLocomotion/drake#16355]
#16354 adds a new API method for `drake::geometry::Shape` to calculate the volume.  We still need to implement the calculation for the `ConvexMesh` and `Mesh` types.

The immediate use case for this is to produce default inertial values for geometries specified in an xml file without having their inertias declared explicitly.  It is called from the parser, not a simulation control loop, so does not need to be optimized for speed.

**Comment by sherm1** [comment]
cc @rpoyner-tri @joemasterjohn

**Comment by RussTedrake** [comment]
Closed by #16354.
