### ISSUE TITLE
[multibody] Provide basic support for MuJoCo MJCF xml format

### ISSUE THREAD

**Issue by RussTedrake** [RobotLocomotion/drake#16369]
I've written a basic MJCF parser and am opening this issue to document my PR strategy and progress.  Reviewers will want to use the MuJoCo documentation, especially the XML scheme [here](https://mujoco.readthedocs.io/en/latest/XMLreference.html).

General strategy:
- I will incrementally add support for the essential aspects of the schema; the parser will log warnings for any unsupported tags, and throw errors if an unsupported tag would lead to erroneous behavior.
- The first PR will have almost no value... it will just establish the basic parser and add some test files.
- Once I support enough functionality to load all of the files in the OpenAI mujoco gym environment, then I will consider the parser to be potentially useful, and will add it to the main `Parser` class, including into `AddModelFromFile` and `AddModelFromString`, add python bindings, and close this issue.  We can add additional features/support incrementally thereafter.

Initial PR train:
- [x] Establish basic parser and test files
- [x] Parse world/anchored geometry using primitive shapes (no meshes)
- [x] Parse "default" parameters
- [x] Parse inertial bodies
- [x] Parse joints
- [x] Parse motors
- [x] Add to `Parser` class and python bindings

**Comment by DamrongGuoy** [comment]
Does this mean, in some examples, we'll have side-by-side comparisons of MuJoco and Drake?

**Comment by RussTedrake** [comment]
My goal here is to make models/environments/assets authored for MuJoCo available in Drake.  

If it also enables side-by-side comparisons, that is of course fantastic. But that will require running MuJoCo separately.  This issue has nothing to do with connecting to the mujoco source code nor library, only parsing the description format.
