### ISSUE TITLE
Switch documentation and mirroring builds to Ubuntu 20.04 Focal

### ISSUE THREAD

**Issue by jwnimmer-tri** [RobotLocomotion/drake#16379]
Similar to #14928 -- with our Ubuntu 18.04 support drawing down soon, and most of the core Drake team using 20.04 locally now, we should switch our documentation pipeline to prefer 20.04 as the "active" build, i.e., the one that actually touches the outside world (vs just smoke-testing).

https://github.com/RobotLocomotion/drake-ci/blob/f7f9f0fc85d54edd4c8587418f1915fbed1595b7/driver/environment.cmake#L203-L209

Ditto for the S3 mirroring job.

https://github.com/RobotLocomotion/drake-ci/blob/f7f9f0fc85d54edd4c8587418f1915fbed1595b7/driver/environment.cmake#L214-L220

When the documentation build changes, the release playbook will also need to reflect that:

https://github.com/RobotLocomotion/drake/blame/480c3bc2c8cb17cf5c8d2e0ef6ec1a14e8aa8218/doc/_pages/release_playbook.md#L137

**Comment by BetsyMcPhail** [comment]
While looking into this I noticed that we have continuous _and_ nightly production mirroring builds:

[linux-bionic-unprovisioned-gcc-bazel-nightly-mirror-to-s3](https://drake-jenkins.csail.mit.edu/job/linux-bionic-unprovisioned-gcc-bazel-nightly-mirror-to-s3/)
[linux-focal-unprovisioned-gcc-bazel-nightly-mirror-to-s3](https://drake-jenkins.csail.mit.edu/job/linux-focal-unprovisioned-gcc-bazel-nightly-mirror-to-s3/)
[linux-bionic-unprovisioned-gcc-bazel-continuous-mirror-to-s3](https://drake-jenkins.csail.mit.edu/job/linux-bionic-unprovisioned-gcc-bazel-continuous-mirror-to-s3/)
[linux-focal-unprovisioned-gcc-bazel-continuous-mirror-to-s3](https://drake-jenkins.csail.mit.edu/job/linux-focal-unprovisioned-gcc-bazel-continuous-mirror-to-s3/)

Only one of these, as determined by ci in link above, runs the [mirror_to_s3 ](https://github.com/RobotLocomotion/drake/blob/master/tools/workspace/mirror_to_s3.py) script.

The nightly jobs should be removed.

**Comment by BetsyMcPhail** [comment]
Jenkins changes removing redundant jobs --> https://github.com/RobotLocomotion/drake-jenkins-jobs/commit/f5662c88dfe7f2ed01e4b174cca0077410aecca8

**Comment by BetsyMcPhail** [comment]
In `documentation_instructions.md`, the example using a bionic documentation job needs to be update (https://github.com/RobotLocomotion/drake/blob/504c6f182ccad3e01889a732e2550e3cb0c271eb/doc/_pages/documentation_instructions.md?plain=1#L84)

**Comment by jwnimmer-tri** [comment]
There are still two stray mirroring jobs defined:

https://drake-jenkins.csail.mit.edu/job/linux-bionic-unprovisioned-gcc-bazel-continuous-mirror-to-s3/
https://drake-jenkins.csail.mit.edu/job/linux-bionic-unprovisioned-gcc-bazel-experimental-mirror-to-s3/

There are still three stray documentation jobs defined:

https://drake-jenkins.csail.mit.edu/view/Documentation/job/linux-bionic-unprovisioned-gcc-bazel-continuous-documentation/
https://drake-jenkins.csail.mit.edu/view/Documentation/job/linux-bionic-unprovisioned-gcc-bazel-experimental-documentation/
https://drake-jenkins.csail.mit.edu/view/Documentation/job/linux-bionic-unprovisioned-gcc-bazel-nightly-documentation/

**Comment by jwnimmer-tri** [comment]
I might not have been totally clear (even to myself) about whether to disprefer, disable, or entirely remove these jobs.  I think removal is the right answer at this point.

**Comment by jwnimmer-tri** [comment]
I'll toss in a related task here as well, since it's probably easy to do in the same PR.

Please remove all of the bionic-based Coverage jobs (~20 of them):

https://drake-jenkins.csail.mit.edu/view/Coverage/

**Comment by BetsyMcPhail** [comment]
Bionic mirroring and documentation jobs have been removed from CI. The following jobs are still available:

- [linux-focal-unprovisioned-gcc-bazel-continuous-mirror-to-s3](https://drake-jenkins.csail.mit.edu/job/linux-focal-unprovisioned-gcc-bazel-continuous-mirror-to-s3/) <-- Configured to publish
- [linux-focal-unprovisioned-gcc-bazel-experimental-mirror-to-s3](https://drake-jenkins.csail.mit.edu/job/linux-focal-unprovisioned-gcc-bazel-experimental-mirror-to-s3/)
- [linux-focal-unprovisioned-gcc-bazel-continuous-documentation](https://drake-jenkins.csail.mit.edu/view/Documentation/job/linux-focal-unprovisioned-gcc-bazel-continuous-documentation/)
- [linux-focal-unprovisioned-gcc-bazel-nightly-documentation]( https://drake-jenkins.csail.mit.edu/view/Documentation/job/linux-focal-unprovisioned-gcc-bazel-nightly-documentation/) <-- Configured to publish
- [linux-focal-unprovisioned-gcc-bazel-experimental-documentation](https://drake-jenkins.csail.mit.edu/view/Documentation/job/linux-focal-unprovisioned-gcc-bazel-experimental-documentation/)

**Comment by BetsyMcPhail** [comment]
Bionic coverage jobs have also been removed.
