### ISSUE TITLE
MultibodyPlant should ignore collisions between two bodies welded to the same link

### ISSUE THREAD

**Issue by hongkai-dai** [RobotLocomotion/drake#16422]
Currently SceneGraph ignores collisions between two bodies both welded to the world. Following the same logic we should ignore the collision between two bodies both welded to the same link.

See slack discussion https://drakedevelopers.slack.com/archives/C2WBPQDB7/p1642886146051700

**Comment by jwnimmer-tri** [comment]
See also #13672.

**Comment by rpoyner-tri** [comment]
I think maybe the right place to land a fix is actually in MultibodyPlant, which is where the magic/implicit collision filtering is added now. Modifying the title to reflect this.

**Comment by rpoyner-tri** [comment]
Also related: #11117.

**Comment by rpoyner-tri** [comment]
I have some work-in-progress that (plausibly) does the right thing, but needs both some unit tests, and possibly more serious testing. @hongkai-dai , do you have any example code hanging around to help inspire some tests?

**Comment by rpoyner-tri** [comment]
Nevermind. I have a test case going. The sad discovery is that the existing behavior (filter world-weld subgraph only) is completely untested. Still working on what to do about that.
