### ISSUE TITLE
ContactResultsToMeshcat deprecation does not properly deprecate AddToBuilder

### ISSUE THREAD

**Issue by RussTedrake** [RobotLocomotion/drake#16464]
The deprecation in #16437 was not sufficient for the most common use case of this system.  All of my notebooks which used the system current throw an error:
```
    ContactResultsToMeshcat.AddToBuilder(
AttributeError: 'function' object has no attribute 'AddToBuilder'
```

**Comment by jwnimmer-tri** [comment]
Apologies, and thanks for reporting.

Of course, the one function that we point people to use was the one I missed.  A PR is up now with the fix.
