### ISSUE TITLE
Change MathematicalProgram::decision_variables_ to type std::vector<Variable>

### ISSUE THREAD

**Issue by hongkai-dai** [RobotLocomotion/drake#16470]
Currently if we repeatedly calling `MathematicalProgram::NewVariables`, the speed is very slow, due to this line https://github.com/RobotLocomotion/drake/blob/e944bdb72cdd5235ed7896f42b6c34268b5ca124/solvers/mathematical_program.h#L3400-L3401

After discussing with @jwnimmer-tri on slack https://drakedevelopers.slack.com/archives/C2ETTRXT7/p1643567204908549, we think the performance would be much better, if we change the data type of `MathematicalProgram::decision_variables_` to std::vector<Variable>.

So I think we need to do following things

1. Change the data type of `MathematicalProgram::decision_variables_` to `std::vector<Variable>`.
2. For the public function `MathematicalProgram::decision_variables()` we need to change the return type, to either `const std::vector<Variable>&` or `Eigen::Map<const VectorX<symbolic::Variable>>`.

The same change should be applied to `MathematicalProgram::indeterminates_`.

I am not sure how to handle the second step so that the downstream users would be aware of the change. Should I deprecate the current function `MathematicalProgram::decision_variables()`?

**Comment by jwnimmer-tri** [comment]
I suggest directly changing the current function to return the `Map<...>`, and then see if any code in Drake or Anzu breaks.  It appears to be a fairly safe change, without a need for deprecation.  If we find some current code breaks, then we can take a closer look.
