### ISSUE TITLE
refactor RotationMatrix::IsIdentityToInternalTolerance() => IsNearlyIdentity() 

### ISSUE THREAD

**Issue by mitiguy** [RobotLocomotion/drake#16551]
This follows issue #16524 that was resolved with PR #16541 which changed:

RigidTransform::IsIdentityToEpsilon(double translation_tolerance) to
RigidTransform::IsNearlyIdentity(double translation_tolerance);

Similarly, the related methods in RotationMatrix are:
Public methods:
RotationMatrix::IsExactlyIdentity();
RotationMatrix::IsIdentityToInternalTolerance();
RotationMatrix::IsNearlyEqualTo(const RotationMatrix& other, double tolerance);
RotationMatrix::IsExactlyEqualTo(const RotationMatrix& other);
Private method:
static boolean IsNearlyEqualTo(const Matrix3& R, const Matrix3& other, double tolerance);

For consistency, and per Jeremy's suggestion in issue #16524, change
RotationMatrix::IsIdentityToInternalTolerance() to
RotationMatrix::IsNearlyIdentity(double tolerance = get_internal_tolerance_for_orthonormality()) const;

**Comment by xuchenhan-tri** [comment]
Looks like `RotationMatrix::IsIdentityToInternalTolerance()` is already deprecated. Are we ready to close this issue?

**Comment by mitiguy** [comment]
Resolved with PR #16541.
