### ISSUE TITLE
LinearConstraint should store a sparse matrix

### ISSUE THREAD

**Issue by hongkai-dai** [RobotLocomotion/drake#16580]
I have a Drake MathematicalProgram object that takes 60GB of memory to construct.

One of the problem is that in LinearConstraint, it stores a dense matrix `A` for lb <= A*x <= ub https://github.com/RobotLocomotion/drake/blob/4d11342274394ad2d90f7cfdb12dc088b5bd55d0/solvers/constraint.h#L624. But in many cases `A` is a sparse matrix. For example, when we construct a BoundingBoxConstraint, which is derived from LinearConstraint, we set its `A` matrix to the dense identity matrix. This takes up a lot of memory.

I propose we change the internal storage type of `A` to Eigen::SparseMatrix<double>.

cc @jwnimmer-tri

**Comment by jwnimmer-tri** [comment]
Would it make sense to change the storage for BoundingBoxConstraint, but leave LinearConstraint (and LinearEqualityConstraint) alone?  How sparse or dense is the typical non-bbox LinearConstraint?

**Comment by jwnimmer-tri** [comment]
My first bid would be to remove the implementation inheritance, and thus there is no `A_` in the first place.

**Comment by hongkai-dai** [comment]
Close this in lieu of #16894
