### ISSUE TITLE
Upgrade Gurobi to 9.5

### ISSUE THREAD

**Issue by jwnimmer-tri** [RobotLocomotion/drake#16604]
FYI see #12419 for the most recent update (which was to 9.0.2).

@hongkai-dai Do you have any vote for whether and/or when Drake should switch to using Gurobi 9.5?

**Comment by BetsyMcPhail** [comment]
There are several steps that need to be coordinated to upgrade Gurobi:

- [x] Update required version in Drake itself #16716
- [ ] Update [Gurobi cask](https://github.com/RobotLocomotion/homebrew-director/blob/46439b995f89270951b3f6db84c67bb39823a2f5/Casks/gurobi.rb#L34)
- [ ] Update [CI pre-provisioning scripts](https://github.com/RobotLocomotion/drake-ci/blob/52e19788fe3e5d93ec48914d51b0896218e94595/setup/ubuntu/install_prereqs)
- [ ] Re-run `grbgetkey` command on CI. We happen to have a new license key for Gurobi (#16640), so we can update the license key at the same time
- [ ] Update CI unprovisioned Mac and Linux images
