### ISSUE TITLE
Multiple contact forces between Box and larger Box below it

### ISSUE THREAD

**Issue by richardrl** [RobotLocomotion/drake#16627]
For a small stacking demo, where the top box is initialized with a small orientation offset from the bottom box, there is this strange behavior where there are 2-4 contact forces reported by:

`        ConnectContactResultsToDrakeVisualizer(builder, plant, scene_graph, lcm)
`

when I assume there should only be 1.

https://user-images.githubusercontent.com/5181990/154777307-492a562b-e61f-41e3-9831-2f9db23d8d4f.mp4

**Comment by richardrl** [comment]
lcm output:

![image](https://user-images.githubusercontent.com/5181990/154778089-4cf035de-a1f0-49c6-ad7f-4fe958116873.png)

**Comment by jwnimmer-tri** [comment]
+@sherm1 to assign someone to reply.

**Comment by sherm1** [comment]
I can't tell from this issue whether there is something wrong.
@DamrongGuoy can you take a quick look to see if you understand the complaint here? (You looked at a related one in #16634)

**Comment by DamrongGuoy** [comment]
@richardrl could you provide the python example to reproduce the problem, please?

**Comment by DamrongGuoy** [comment]
I close this issue now since I haven't heard back from @richardrl for a week.
