### ISSUE TITLE
Update CI AMIs for Ubuntu

### ISSUE THREAD

**Issue by jwnimmer-tri** [RobotLocomotion/drake#16642]
Per #16622, the Ubuntu AMIs in CI should gain a new `libomp-9-dev` package installed.  Please push out this update.

**Comment by jwnimmer-tri** [comment]
(Requested ETA: prior to next Monday, Feb 28th.)

**Comment by BetsyMcPhail** [comment]
The Bionic and Focal images have been updated. As usual, it may take Jenkins awhile to cycle through and use the new images.
