### ISSUE TITLE
CI Mosek and Gurobi Licenses

### ISSUE THREAD

**Issue by BetsyMcPhail** [RobotLocomotion/drake#16640]
The Mosek and Gurobi licenses expire next month.

Mosek March 17
Gurobi March 28 

@RussTedrake can you please help coordinate the license renewal? I can update CI when the updated licenses are available.

**Comment by BetsyMcPhail** [comment]
A Slack notification reminded us that the Mosek license expires soon (2 weeks from today). @RussTedrake let me know if there's anything I can do to help.

**Comment by RussTedrake** [comment]
I've supported the support request to renew gurobi, and will send the mosek update to you directly.
