### ISSUE TITLE
GeometrySet doxygen does not document any Add() methods

### ISSUE THREAD

**Issue by ggould-tri** [RobotLocomotion/drake#16648]
If you read https://drake.mit.edu/doxygen_cxx/classdrake_1_1geometry_1_1_geometry_set.html you will see that it mentions methods called `Add()` and `add()` but neither appears in the documentation.

In fact the latter method does not exist and the former has solidly ten overloads none of which appears in the docs.  This makes it somewhat baffling to try to write code that manipulates geometry sets.

Presumably this is due to some sort of typo in the second group comment in `geometry_set.h`

(default-assigning @sherm1 for now)

**Comment by sherm1** [comment]
Assigning to Rico for disposition.
