### ISSUE TITLE
Check boundedness of `Intersection` of convex sets

### ISSUE THREAD

**Issue by TobiaMarcucci** [RobotLocomotion/drake#16663]
As discussed with @RussTedrake and @mpetersen94, currently the boundedness check for the `Intersection` of convex sets throws unless any of the intersected sets are bounded. But it can be that even if all of the sets are unbounded the intersection is bounded. Here I report the math (might need some cleaning) that I believe we should implement for this check.

- The problem of determining if the intersection of convex sets is bounded is equal to the problem of checking if a convex set of the form `S = {x: g_i(x) <= 0 for all i}` is bounded.
- We form the recession `K` cone of `S`. This will have the form `K = {x: h_i(x) <= 0 for all i}`. To construct the functions `h_i` from the `g_i` we will need a separate method for each `ConvexSet`. For example, if a set is a polyhedron, then `g_i(x) = a' x - b` and `h_i(x) = a' x`. For an `Ellipsoid` the cone `K` is the nullspace of the Hessian. Etc.
- The set `S` is bounded iff `K` contains a nonzero point.
- First we check if `K` is pointed. If not, then `S` is unbounded. One way to do this is to check if the linearizations of the `h_i(x)` at `x = 0` form a basis for `R^n`.
- If `K` is pointed then we have `h_i(x) = 0` for all `i` iff `x = 0`.
- Finally, we then check if `K` contains a point `x != 0` by solving the convex program: `find x, y` such that ` h_i(x) <= y for all i`, `y <= 0`, and `sum_k y_k <= - 1`.
- If `K` has a nonzero point `x` in it, then the problem above is feasible. This because `x != 0` implies  `h_i(x) < 0` for some `i`.
- If `K = {0}` then the above problem is infeasible.

Note: This is essentially the dual of the check we currently do to see if a polyhedron is bounded. For a polyhedron `{x: A x <= b}` the check of pointedness of `K` becomes `ker(A) = {0}`. And the convex program becomes the LP `find x, y` such that ` A x <= y`, `y <= 0`, and `sum_k y_k <= - 1`. When we implement the stuff above, I'd also modify the check for the polyhedron since I think this primal LP is much easier to interpret than the dual check we are currently doing.

**Comment by EricCousineau-TRI** [comment]
(Just assigning based on [Platform Reviewer Checklist](https://drake.mit.edu/platform_reviewer_checklist.html) - please change if need be!)

**Comment by cohnt** [comment]
Here's a possibility for a temporary solution, which would be easy to implement, but certainly less efficient than Tobia's idea. If S is the intersection, and e_i the ith standard basis vector, we could iteratively solve `min <e_i, x> s.t. x in S` and `max <e_i, x> s.t. x in S` for i=1,...,dim(S). Unless I'm overlooking something, we should have S bounded iff all of these programs have a finite optimum. This would require solving up to 2n convex programs (where n is the ambient dimension).
