### ISSUE TITLE
Drake v1.0.0 apt packages

### ISSUE THREAD

**Issue by jwnimmer-tri** [RobotLocomotion/drake#16708]
Follow-up from #16601:

Please manually tag docker images and upload the releases to S3.

Binary date: `20220303`
Commit SHA: `06e1deb12539f05eff968c5bd9e11d259916f268`
Release tag: `v1.0.0`

**Comment by BetsyMcPhail** [comment]
Note that in #16678 and the follow-up  [drake-ci #135](https://github.com/RobotLocomotion/drake-ci/pull/139) **setup_drake_colab.py** was removed. The portion of the `push_release` script dealing with this file needed to be removed.

**Comment by BetsyMcPhail** [comment]
Docker images and S3 are all set.

Still working on apt packages.

**Comment by BetsyMcPhail** [comment]
Apt packages are also done
