### ISSUE TITLE
SAP Solver PR train

### ISSUE THREAD

**Issue by amcastro-tri** [RobotLocomotion/drake#16738]
This issue provides a sketch of the PR train needed to complete the [SAP solve project](https://github.com/RobotLocomotion/drake/projects/10). Refer to the project's description for more information.

Find [SapSolver project here](https://github.com/RobotLocomotion/drake/projects/10). Full working prototype in https://github.com/RobotLocomotion/drake/pull/16543.

- [x] [SapContactProblem](https://github.com/RobotLocomotion/drake/pull/16548) (230 LOCs)
  - Without SapContraint 
  - Without ContactProblemGraph
  - Define cliques
- [x] [SapConstraint](https://github.com/RobotLocomotion/drake/pull/16553) (386 LOCs)
  - Reference SapContactProblem's docs on cliques
- [x] [ContactProblemGraph](https://github.com/RobotLocomotion/drake/pull/16570)  (340 LOCs)
- [x] [SapContactProblem::AddConstraint()](https://github.com/RobotLocomotion/drake/pull/16618)  (224 LOCs)
- [x] [SapConstraintBundle](https://github.com/RobotLocomotion/drake/pull/16697)  (621 LOCs)
- [x] [PartialPermutation](https://github.com/RobotLocomotion/drake/pull/16596)  (354 LOCs)
- [x] [Contact graph provides participating cliques](https://github.com/RobotLocomotion/drake/pull/16694)  (86 LOCs)
- [x] [FrictionConeConstraint](https://github.com/RobotLocomotion/drake/pull/16715)  (655 LOCs)
  - Use MP to get a numerical solution to the projection.
- [x] [Update MultibodyTreeTopology to provide tree information needed by the manager.](https://github.com/RobotLocomotion/drake/pull/16725)  (230 LOCs)
  - num_tree_velocities_: Needed to compute per-tree A and J blocks.
  - body_to_tree_index_: Needed to determine clique given a body in contact.
  - tree_velocities_start_: needed to extract per tree Jacobian blocks.
  - dof_to_tree_index_: Thus far only used when adding distance constraints. I'll just add all these in a single PR.
- [x] [SapModel](https://github.com/RobotLocomotion/drake/pull/16713)  (724 LOCs)
- [x] [Complete SapModel features + unit tests:](https://github.com/RobotLocomotion/drake/pull/16771)
  - Regularizer cost
  - Gradient of the cost.
  - Hessian of the cost
  - United with 2D boxes with contact and AutoDiff for gradients.
- [x] CompliantContactManager makes SapContactProblem
  - Eval contact Jacobian as needed.
  - Eval? SapContactProblem?, a function of state after all.
- [x] SapContactSolver is no longer a ContactSolver
- [x] SapSolver makes use of SapModel
- [x] SapSolverResults
  - Introduce results compatible with a given SapContactProblem
  - Extract ContactResults utility for contact reporting.
- [x] Incorporate SapSolver into CompliantContactManager
  - Testing strategy?
- [x] Limit constraint.
- [x] CompliantContactManager adds limit constraint to the SapContactProblem.
- [x] SapSolver uses supernodal algebra.
- [x] Implicit treatment of joint dissipation.
- [x] Manager computes acceleration kinematics.
- [x] Exact line search
- [x] Parsing of dissipation time scale for SAP dissipation model
- [x] MultibodyPlant option to use SapSolver
  - MBP API.
  - MultibodyPlantConfig
    - solver option
    - regularization params option?
  - Add gflag to opt-in for SAP in some of our examples:
    - Falling cylinder
    - Acrobot
    - Atlas
    - ManipulationStation
- [ ] SapSolver and CompliantContactManager log timing statistics. 
- [x] ~CouplerConstraint~. SapHolonomicConstraint
- [x] Plant API to add coupler constraints.
- [x] Plant API to add distance constraints.
- [ ] Plant APIs for PD controller constraint
  - Ports for desired state.
  - Actuation and generalized forces input ports are additive. (this enables things like gravity compensation, slow, plus PD controllers, fast)
- [ ] (stretch) SapSolver unit tests
  - Push box
  - Falling cylinder
  - Painleve rod
  - Coupler and distance constraints.
- [x] [Support for joint locking](https://github.com/RobotLocomotion/drake/pull/18983).
  - [x] [Include locking in ForwardDynamics](https://github.com/RobotLocomotion/drake/pull/19420).
  - [x] [Reduce SapContactProblem](https://github.com/RobotLocomotion/drake/pull/19488).
  - [x] [Expand ContactSolverResults](https://github.com/RobotLocomotion/drake/pull/19607)

**Comment by sherm1** [comment]
Should we add "support joint locking" to this list?

**Comment by DamrongGuoy** [comment]
It is so great to see the plan. Thank you!

**Comment by edrumwri** [comment]
Could I make two requests?

1. Could you bump the priority for joint locking?
2. Would you cause SAP solver to fail fast if joint locking is enabled? We spent three hours of engineering time tracking down why our locked bodies were no longer stationary.

**Comment by chen-tianjian** [comment]
May I ask what the status is for joint locking and free body locking with SAP?

**Comment by jwnimmer-tri** [comment]
@amcastro-tri This is finished, I think?
