### ISSUE TITLE
Unable to add drake path using latest build

### ISSUE THREAD

**Issue by eric-wieser** [RobotLocomotion/drake#1674]
Built from source on windows using d1d451bca787a0a2504ce47ddf396a6b52b3b1bd

```
>> run('C:\Users\wiese\Documents\Courses\6.832\drake-install\matlab\addpath_drake.m')
Out of memory. The likely cause is an infinite recursion within the program.

Error in fileparts (line 40)
if ispc
```

**Comment by eric-wieser** [comment]
Ok, seems i was running the wrong file. What purpose does this file serve though? It seems like it inevitably runs itself in a recusion loop...

**Comment by RussTedrake** [comment]
it is supposed to call the other addpath_drake.  somehow the install must have written the wrong path into that file?  would be good to resolve..

**Comment by eric-wieser** [comment]
For me, that file contains:

```
function addpath_drake()
  mfiledir = fileparts(which(mfilename));
  wd = cd(fullfile(mfiledir,''));
  addpath_drake();
  cd(wd);
end
```

**Comment by RussTedrake** [comment]
The relpath logic failed you on install.  see here: https://github.com/RobotLocomotion/drake/blob/master/drake/CMakeLists.txt#L229

**Comment by eric-wieser** [comment]
Why do we invoke python to get relative paths instead of using `file(RELATIVE_PATH from to)`?

**Comment by RussTedrake** [comment]
Some of this is old code.  I agree, it looks like using file (RELATIVE_PATH ) is better.  updating it would be great.

**Comment by billhoffman** [comment]
We sort of need matlab for this one...   But we have a trial one.  Might want to look at licenses.
