### ISSUE TITLE
 Dropping Ubuntu 18.04 (Bionic) CI

### ISSUE THREAD

**Issue by jwnimmer-tri** [RobotLocomotion/drake#16842]
The first task in #13391 is to turn off CI jobs for Bionic.

- [x] Ensure that Drake v1.1.0 has been released.
- [x] Switch all pre-merge PR build choices to use `focal` flavors
- [x] Drop Bionic from https://drake-jenkins.csail.mit.edu/
- [x] Drop Bionic from https://github.com/RobotLocomotion/drake-external-examples/tree/main/.github [PR#222](https://github.com/RobotLocomotion/drake-external-examples/pull/222)

Feel free to start landing this work on 2022-04-01 even without TRI reviews (we'll be out).  The only gating item is that we should be sure that Drake v1.1.0 gets released before we shut down Bionic.

\CC @rpoyner-tri FYI as release manager for v1.1.0.

**Comment by BetsyMcPhail** [comment]
Note, the current pre-merge builds are:

`linux-bionic-clang-bazel-experimental-everything-release`
`linux-bionic-clang-bazel-experimental-release`
`linux-bionic-clang-cmake-experimental-release`
`linux-bionic-gcc-bazel-experimental-debug`
`linux-bionic-gcc-bazel-experimental-everything-release`
`linux-bionic-gcc-bazel-experimental-release`            
`linux-bionic-gcc-cmake-experimental-release`
`linux-focal-clang-bazel-experimental-leak-sanitizer`
`linux-focal-gcc-bazel-experimental-release`


`linux-bionic-gcc-bazel-experimental-release` will be a duplicate when switched to focal, so there will be 8 pre-merge builds after the switch.

**Comment by BetsyMcPhail** [comment]
I confirmed that the Bionic CI jobs, in general and production, are a subset of the Focal jobs.

**Comment by BetsyMcPhail** [comment]
@jwnimmer-tri last time we changed pre-merge jobs it required some intervention from you on Github (https://drakedevelopers.slack.com/archives/C270MN28G/p1644614660867079). I have the Jenkins changes ready to go, let me know when would be a good time for you to do the switch.

**Comment by jwnimmer-tri** [comment]
GitHub's project settings have the new builds as required on pull requests now:

![image](https://user-images.githubusercontent.com/17596505/162772265-f59e46dd-a078-4604-ac7c-ef737c2418cb.png)

**Comment by BetsyMcPhail** [comment]
Bionic jobs have been removed from Jenkins and CI no longer supports Bionic ([PR #146](https://github.com/RobotLocomotion/drake-ci/pull/146))
