### ISSUE TITLE
Port runAtlasJumping and runAtlasRunning to PlanEval/InstQP

### ISSUE THREAD

**Issue by rdeits** [RobotLocomotion/drake#1685]
- [ ] support V.S being a trajectory instead of a constant
- [ ] support 2- or 3-dimensional linear systems in the LQR data
- [ ] switch footContactBlock to contactSensor
- [ ] switch link_constraints to BodyMotionData
- [ ] construct QPLocomotionPlan

**Comment by RussTedrake** [comment]
related to #6831.  with that pointer established, I will close this one.
