### ISSUE TITLE
profiling recommendations on website cleanup

### ISSUE THREAD

**Issue by RussTedrake** [RobotLocomotion/drake#16856]
We have profiling locations on two different pages on the website.  Both were difficult to find.

I would consider the main documentation to be here:
https://drake.mit.edu/profiling.html

We also have some instructions for mac buried in here: https://drake.mit.edu/bazel.html

Searching `site:drake.mit.edu profiling` on google pointed me to yet another (unhelpful) stub at: https://drake.mit.edu/development_on_mac.html 
(and also to the bazel page, which took additional work to uncover)

Entering `profiling` on the search page on the website runs a similar search on duckduckgo, which only turned up the bazel page.  I had to manually enter the url for profiling.html (which I found through search on my local code checkout), in order to get it to appear in my browser.

**Comment by jwnimmer-tri** [comment]
My vote is that we should in case move the macOS profiling information from bazel.html to profiling.html (or else purge it entirely, if we don't think anyone is using or validating it anymore anyway).
