### ISSUE TITLE
Jenkins https certificate invalid

### ISSUE THREAD

**Issue by tkoolen** [RobotLocomotion/drake#1688]
Clicking on the Jenkins Details link in the build results for a pull request results in:

![image](https://cloud.githubusercontent.com/assets/2585880/12797858/20b6f24a-ca94-11e5-950d-a7e29642fb9b.png)

**Comment by billhoffman** [comment]
Yup, it is a self generated certificate.   @RussTedrake I think you were going to look into possibly getting a certificate from MIT, if not we would have to purchase one.  For now just click advanced and to to the site.

**Comment by RussTedrake** [comment]
I believe i already sent Jamie the info for the mit bits.  - Russ

**Comment by jamiesnape** [comment]
I only have information about the IP address. Nothing about an SSL certificate.

**Comment by RussTedrake** [comment]
Can you follow up with @mpearrow about it?

**Comment by jamiesnape** [comment]
Sure.

**Comment by jamiesnape** [comment]
Certificate request is being processed now. Should be available by tomorrow.

**Comment by tkoolen** [comment]
Awesome. Other than that the Jenkins build process seems to be going smoothly!

**Comment by jamiesnape** [comment]
Issued and deployed.

**Comment by tkoolen** [comment]
Verified fixed.
