### ISSUE TITLE
ExtractAndAppendVariablesFromExpression is slow

### ISSUE THREAD

**Issue by hongkai-dai** [RobotLocomotion/drake#16895]
This function uses `conservativeResize` which involves a lot of heap memory allocation https://github.com/RobotLocomotion/drake/blob/e6c31419faf9a3f6b429a6194d594cdb72eb43ca/common/symbolic_decompose.cc#L112

I propose that we change the signature of this function, the input type of `VectorX<Variable>* vars` should be changed to `std::vector<Variable>* vars`, so that we use `std::vector::push_back` to avoid linear number of heap memory allocation.

cc @jwnimmer-tri

**Comment by jwnimmer-tri** [comment]
For all of these performance improvements, it would be helpful to write application-level benchmarks (e.g., constructing and populating a MathematicalProgram) so that we can demonstrate the improvement, and check for regressions over time.
