### ISSUE TITLE
TrajectorySource with PiecewiseQuaternion does not give expected result

### ISSUE THREAD

**Issue by CWEzio** [RobotLocomotion/drake#16909]
My original Stackoverflow question is over [here](https://stackoverflow.com/questions/71747834/trajectorysource-with-piecewisepose-does-not-give-expected-rotation-result).

I am playing with PiecewisePose and TrajectorySource. I want to create a linear interpolation trajectory from an inital pose to the goal pose. After creating the trajectory, I add it to the TrajectorySource and use LogVectorOutput to save the log. Here is my code:
```
sample_times = [0., 3.0]
X_0 = RigidTransform()
X_1 = RigidTransform(RotationMatrix.MakeXRotation(np.pi/2), [1, 1, 1])
Xs = [X_0, X_1]
traj = PiecewisePose.MakeLinear(sample_times, Xs)

builder = DiagramBuilder()
plant, scene_graph = AddMultibodyPlantSceneGraph(builder, 0.1)
plant.Finalize()
traj_R = traj.get_orientation_trajectory()
traj_p = traj.get_position_trajectory()

R_source = builder.AddSystem(TrajectorySource(traj_R))
p_source = builder.AddSystem(TrajectorySource(traj_p))
logger_R = LogVectorOutput(R_source.get_output_port(), builder)
logger_p = LogVectorOutput(p_source.get_output_port(), builder)

diagram = builder.Build()
simulator = Simulator(diagram)
context = simulator.get_context()

simulator.AdvanceTo(3.0)
```
To see the result, I print the log:
```
log_R = logger_R.FindLog(context)
print(log_R.data())
```
However, the result is quiet surprising:
```
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0.]]
```

As @xuchenhan-tri answered in my Stackoverflow question, this seems like a bug : 
>`TrajectorySource` evaluates the trajectory at the sample times by invoking `Trajectory::value()`, however `PiecewiseQuaternion` spits out rotation matrices as values instead of quaternions. Therefore the first column of the rotation matrix and the first entry in the second column is being copied to the Trajectory source, which is garbage.
>The documentation of `Trajectory` says that the size of the output returned by `value()` should have rows() and cols(). For `PiecewiseQuaternion`, rows and cols are 4 and 1 respectively, but `value()` spits out a 3x3 rotation matrix.

**Comment by rpoyner-tri** [comment]
Assigning to @xuchenhan-tri for triage and maybe further delegation.
