### ISSUE TITLE
Errors with SNOPT 7.5 due to incompatible snsolve() signature

### ISSUE THREAD

**Issue by samkhal** [RobotLocomotion/drake#1696]
I was having trouble getting runAtlasRunning to work with SNOPT 7.5, because the parameter list for snsolve had changed; in 7.5 it tries to match the signature of fmincon. The error I was getting was "Wrong number of input arguments".

To fix this I simply replaced the original snsolve call in nonlinearCollocation.m
```
[xstar, fval, ~, ~, exitflag] = snsolve(x0,xlow,xupp,xmul,xstate,    ...
               Flow,Fupp,Fmul,Fstate,      ...
               ObjAdd,ObjRow,A_sn(iAndx),iAfun,jAvar,...
               iGfun,jGvar,'snoptUserfun');
```
with the same signature that the fmincon call uses:
```
[xstar, fval, exitflag] = snsolve(@objfun, x0, sparse(A), b, ...
                  sparse(Aeq), beq, lb, ub, @constraints, ...
                  optimset('Algorithm', 'interior-point', ...
                  'DerivativeCheck', 'on', ...
                  'GradConstr', 'on', ...
                  'GradObj', 'on', 'OutputFcn',{}));
```
It looks like the setup that preceded the snsolve call is now all done within snsolve itself. 

I know compatibility with snopt 7.5 is on the roadmap, but figured I'd post to make fixing this issue a bit easier for people in the meantime.

**Comment by RussTedrake** [comment]
thank you for documenting this.  I will close the bug, but appreciate having it available for anyone who searches.
