### ISSUE TITLE
Remove support for Binder

### ISSUE THREAD

**Issue by jwnimmer-tri** [RobotLocomotion/drake#16969]
Split out from https://github.com/RobotLocomotion/drake/issues/13683#issuecomment-999807942.

Tasks (in order, one by one):
- [x] Remove the Binder-specific ("PUSHING NIGHTLY RELEASE BINDER BRANCH") code from [step-push-nightly-release-branch.cmake](https://github.com/RobotLocomotion/drake-ci/blob/7ab0fedc16645832eb00967a75d001b2bc89a347/driver/configurations/bazel/step-push-nightly-release-branch.cmake#L62-L102).  (Keep the "PUSHING NIGHTLY RELEASE BRANCH" portion, we still want a nightly tag, just not a binder-specific nightly tag.)
- [x] Delete the `nightly-release-binder` [branch](https://github.com/RobotLocomotion/drake/branches) from Drake's git repository.  This will probably require an Admin user to disable the branch protections on it, first.
- [ ] Delete the `.binder` directory from Drake master.  Use "release notes: yes" label.

**Comment by jwnimmer-tri** [comment]
Within Drake, the only mention of "binder" is either in documentation that mentions a long list of potential online notebooks (_"Note that some commercial solvers are not included in the pre-compiled Drake binaries, and therefore not on Deepnote/Colab/Binder."_), or the top-level `.binder` folder.  In drake-ci, we have some [special code](https://github.com/RobotLocomotion/drake-ci/blob/7ab0fedc16645832eb00967a75d001b2bc89a347/driver/configurations/bazel/step-push-nightly-release-branch.cmake#L62-L102) to push a binder-specific branch that pins binder to the most recently nightly [docker image](https://drake.mit.edu/docker.html).

Now that our tutorials are hosted on Deepnote, and  we offer drake wheels on pypi, I think the binder-specific image is not as useful as it used to be.

The only purpose of the dotfile directory in Drake is to run Drake's tutorials on Binder.  I'd rather not support that -- I think we should maintain exactly one tutorials host, so that there's only one thing we need to test.  Thus, we should purge the dotfile directory.

As such, the `drake-ci` logic to update the branch will also need to go.  There no more Dockerfile to re-pin every night.

I don't think we need any deprecation announcement for this.  The binder files and branch are not part of the [Stable API](https://drake.mit.edu/stable.html).

**Comment by jwnimmer-tri** [comment]
\CC @RussTedrake I'm going to schedule this for Kitware soon.  Let us know if you have any concerns.

**Comment by RussTedrake** [comment]
SGTM

**Comment by jwnimmer-tri** [comment]
I've just deleted the `nightly-release-binder` branch (and changed the branch protection rule pattern from `*release*` to just `nightly-release` directly).
