### ISSUE TITLE
make -j in drake-distro broken

### ISSUE THREAD

**Issue by tkoolen** [RobotLocomotion/drake#1697]
It appears that running make -j in drake-distro with all supported externals is broken (at least on OS X). Just running make is fine. Not sure, but I think it's caused by the textbook because of this line in the build output:
```
make[3]: *** [textbook-prefix/src/textbook-stamp/textbook-build] Error 2
```
Any ideas?

**Comment by psiorx** [comment]
Not sure if this is related but I had to run `sudo pip install beautifulsoup4` to get the textbook stuff to go through.

**Comment by rdeits** [comment]
`pip install beautifulsoup4` is included in the textbook repo's `install_prereqs.sh`, so you should have that already.

**Comment by tkoolen** [comment]
Yup, I have beautifulsoup4 installed already. Still broken.

**Comment by tkoolen** [comment]
I think something is going wrong during the download step. I don't get any errors, but my drake-distro/drake/doc/textbook directory is empty.

**Comment by mwoehlke-kitware** [comment]
What do I need to reproduce this?

**Comment by tkoolen** [comment]
build on OSX, `make options` in drake-distro, select WITH_ALL_SUPPORTED_EXTERNALS, `make -j`.

**Comment by RussTedrake** [comment]
confirmed that this is resolved.  thanks @mwoehlke-kitware
