### ISSUE TITLE
Drake v1.2.0 docker and apt packages

### ISSUE THREAD

**Issue by jwnimmer-tri** [RobotLocomotion/drake#16999]
Please manually tag docker images and upload the releases to S3.

Release notes PR: #16939 
Binary date: `20220420`
Commit SHA: 4e1146e7251aaff1e263b3b10a41f915827d9acb
Release tag: https://github.com/RobotLocomotion/drake/releases/tag/v1.2.0

**Comment by BetsyMcPhail** [comment]
Docker images are done

**Comment by BetsyMcPhail** [comment]
Apt packages are also complete.
