### ISSUE TITLE
MOSEK loader paths test within Drake

### ISSUE THREAD

**Issue by jwnimmer-tri** [RobotLocomotion/drake#16990]
In #16985, we fixed a bug in Drake's installer that was only ever caught in drake-external-examples CI.  We'd much rather catch this during Drake's normal (Continuous) CI.

We should try to add an `install_test` for this case.

I hope that we could look at the `otool` output for the installed library, and alert on any paths that are incorrectly formulated.

Relatedly, we also have a lot of otool-scraping code currently committed, and more on the way in #16872.  It might also be nice to factor out otool scraping into a Drake-internal python library, so that it can be easily reused everywhere, and so that only one function needs to be carefully commented about the otool output formats, instead of doing brittle string parsing in several places.

\CC @BetsyMcPhail @svenevs FYI

**Comment by svenevs** [comment]
See also: https://github.com/RobotLocomotion/drake/pull/16991#pullrequestreview-947476675

When implementing the tests, reverting #16991 and #16985 will be a pathway for "testing the tests."

**Comment by mwoehlke-kitware** [comment]
Can we not add a test that the installed libraries are _usable_? That seems like it would be more valuable than adding ad-hoc tests for individual libraries.

**Comment by jwnimmer-tri** [comment]
The problem comes when the paths refer to libraries that exist, but only in the build tree.  It's difficult to make the build tree evaporate or become inaccessible when running the tests.  That's why an allow-list for well-formed paths is probably the most cost-effective testing mechanism.
