### ISSUE TITLE
runAtlasDynamics fails on drake001

### ISSUE THREAD

**Issue by tkoolen** [RobotLocomotion/drake#1702]
See e.g. the test result in this build of master: http://kobol.csail.mit.edu/cd/testDetails.php?test=3616246&build=21232. Path LCP reaches its iteration limit.

Possibly related: I see this warning in the test output, which doesn't appear on my system:
```
[ Warning: This timestep violated our assumptions about which contacts could
possibly become active in one timestep.  Consider reducing your dt.  If it
seems to happen a lot, then please let us know about it.] 
```

**Comment by tkoolen** [comment]
@billhoffman, for this type of issue, it would be very useful to see when this particular test first started failing on drake001. Is there any way to see that quickly with CDash?

**Comment by RussTedrake** [comment]
not sure why drake001 would be any different?

**Comment by tkoolen** [comment]
Closing since drake001 is not a thing anymore. Please open a different issue if this happens on a different machine.
