### ISSUE TITLE
Upgrade Mosek to Mosek 10

### ISSUE THREAD

**Issue by hongkai-dai** [RobotLocomotion/drake#17026]
As mentioned in https://drakedevelopers.slack.com/archives/C3L92BM2Q/p1650594410258979

We need to complete following tasks

- [x] Upgrade TRI's Mosek license to Mosek 10.
- [x] Upgrade Drake CI's Mosek license to Mosek 10 (see #17514).
- [x] Change Drake's build system to use Mosek 10
- [ ] Change solvers::MosekSolver class to use the affine cone constraints.
- [X] Re-enable macOS arm64 Mosek support in `--config everything` builds (revert: #17269, done in #17870).

**Comment by jwnimmer-tri** [comment]
Will we upgrade while MOSEK 10 is still in Beta, or will we be waiting for an official release first?

**Comment by hongkai-dai** [comment]
Perfect timing, I just received an email from Mosek author saying that the performance of Mosek on semidefinite programming problem has improved significantly. I just sent him an email asking when the stable version will be released. I will update this thread once I hear back from them.

I tried to change the build file to use version 10.0.16 directly, but got error on compiling clk5 library.

**Comment by jwnimmer-tri** [comment]
Right.  If I recall correctly, Mosek 10 uses a different multithreading substrate, so we 'll need to do surgery on our BUILD files (and distribution scripts) to account for the changed dependency.

**Comment by hongkai-dai** [comment]
Right, in their blog post they mention that in Mosek 9 the computation time with multithread is almost the same as with the single thread. But on mosek 10 multithread is much faster https://themosekblog.blogspot.com/2022/06/on-performance-improvement-of-semi.html

**Comment by hongkai-dai** [comment]
Its twitter says the stable version is going to be released in mid-August https://twitter.com/mosektw?lang=en

Given the large performance boost on Mosek 10 with multi-thread, I think it makes sense to upgrade to version 10 sooner? Especially because it will take some time to modify our MosekSolver implementation, as some of the old Mosek API are deprecated, so I will need to re-write the code to parse Lorentz cone constraint in mosek_solver.cc. What do you think?

**Comment by jwnimmer-tri** [comment]
I think it would be a good idea to start a shared development branch for the proposed changes (e.g., "Draft PR" with "allow edits from maintainers" checked), so that we can start developing, testing, and debugging the feature.

As to whether we land that PR in master, while Mosek 10 is still in Beta stage?  My current vote is "no" -- we shouldn't ship beta dependencies.  However, we can wait to re-assess that once we have the code working and know more about the actual trade-offs.

**Comment by hongkai-dai** [comment]
Thanks! Yes, I think a developement branch makes sense. I can also test our optimization code on that dev branch.

**Comment by hongkai-dai** [comment]
I would like to work on this dev branch as soon as possible. In my research I encounter some problems that Mosek 9.3.20 cannot solve, while Mosek 10.0.16 can solve. So I think it makes sense to try out the new version. @jwnimmer-tri I tried to change the version in the mosek build bazel file to 10.0.16 directly but ran into build error with clk5 library. May I ask you to help me on the build files (after the TRI holidays)? Thanks a lot!

**Comment by jwnimmer-tri** [comment]
@hongkai-dai Open a PR with your progress so far and ensure `Allow edits by maintainers` is checked "yes".  Then we can each push commits to incrementally improve it.

**Comment by hongkai-dai** [comment]
Sounds great, I filed PR https://github.com/RobotLocomotion/drake/pull/17490

**Comment by jwnimmer-tri** [comment]
Given the "everything" configuration test failures in #17490 ("RuntimeError: Could not acquire MOSEK license."), it seems like we _also_ need to upgrade Drake CI's MOSEK license to enable Mosek 10?  I didn't see a checklist item atop this issue with that task yet.

**Comment by hongkai-dai** [comment]
Ah you are right. I forgot that the drake CI doesn't use TRI's mosek license. Is the CI using MIT's mosek license?

**Comment by jwnimmer-tri** [comment]
Yes, that's right.  I opened #17514 with the request.

**Comment by svenevs** [comment]
> Change Drake's build system to use Mosek 10

I think we can mark this as complete.

> Change solvers::MosekSolver class to use the affine cone constraints.

[m1 everything builds](https://drake-jenkins.csail.mit.edu/job/mac-m1-monterey-provisioned-clang-bazel-experimental-everything-release/) will use mosek 10 on macOS arm64.  More m1 flavors inbound now that everything finally works, just wanted to mention that we should at last be in a place where changing this can be fully tested in CI on linux, mac, and m1 mac.

**Comment by jwnimmer-tri** [comment]
> > Change Drake's build system to use Mosek 10
>
> I think we can mark this as complete.

Yes, as of https://github.com/RobotLocomotion/drake/pull/17490.  I'll do that now.

> Change solvers::MosekSolver class to use the affine cone constraints.

@hongkai-dai Maybe we should open a use issue for that enhancement?  The upgrade is finished.

**Comment by hongkai-dai** [comment]
> @hongkai-dai Maybe we should open a use issue for that enhancement? The upgrade is finished.

I think this is completed in https://github.com/RobotLocomotion/drake/pull/18114. We can close this issue.
