### ISSUE TITLE
SWFWriter does not run on Ubuntu 14.04

### ISSUE THREAD

**Issue by vtjeng** [RobotLocomotion/drake#1706]
When attempting to use SWFWriter to export a `swf` file, `pdf2swf` is not available in the standard `swftools` package. 

This leads to the writer failing with the following error message:

```
failed running this on the command line:
    pdf2swf -s framerate=30 /home/vtjeng/drake-distro/drake/examples/DubinsCar/plots/sample_frames/merge.pdf /home/vtjeng/drake-distro/drake/examples/DubinsCar/plots/sample.swf
Make sure that you have the command line tool installed and have address all path/library issues.
Error using SWFWriter/close (line 100)
swf writing failed

Error in Visualizer/playbackSWF (line 499)
        swf.close();

Error in runPlaneVisualizer (line 85)
    v.playbackSWF(xtraj);
```

According to [serverfault.com](http://serverfault.com/questions/623604/install-pdf2swf-on-ubuntu-trusty-tahr14-04), `pdf2swf` has been removed from swftools in the Ubuntu 14.04 repository; this means that to use this tool, you would need to use the work-around provided in the link.

**Comment by RussTedrake** [comment]
Thanks for reporting this and linking to the fix. 

Sadly, I think SWF is essentially extinct.  I badly want a vectorized graphics format to replace it.  SVG animations are the closest that I know, but I haven’t pushed on that pipeline yet to see how well it works.

I will close this, but it’s great to have it available for those who search the issues.
