### ISSUE TITLE
Double underscores in link names don't work with CollisionFilterGroup

### ISSUE THREAD

**Issue by samkhal** [RobotLocomotion/drake#1707]
CollisionFilterGroup assumes that link names don't contain "__", so uses that to attach robotnum to a string of links. Naturally, if the link name contains double underscores this breaks and the error is hard to find. I ran into this when trying to import an auto-generated URDF which used double underscores in link names.

While they're not supported, somewhere during the URDF import process drake should warn about double underscores. Maybe using a special character disallowed in the xml would be better.

[CollisionFilterGroup.m line](https://github.com/RobotLocomotion/drake/blob/9a67372fa00054aedf8a9f30684bdd5dc2ee9b0d/drake/systems/plants/collision/CollisionFilterGroup.m#L28)

**Comment by RussTedrake** [comment]
good catch.  thanks.
