### ISSUE TITLE
Upgrade externals to latest - May 2022

### ISSUE THREAD

**Issue by BetsyMcPhail** [RobotLocomotion/drake#17093]
Follow [Semi-automated monthly upgrades](https://github.com/RobotLocomotion/drake/blob/master/tools/workspace/README.md#semi-automated-monthly-upgrades) documentation.

Prior issue: #16879

**Comment by BetsyMcPhail** [comment]
Note to myself, still outstanding:

petsc needs upgrade from v3.16.5 to v3.17.1

**Comment by jwnimmer-tri** [comment]
The only work remaining here is the PETSc upgrade.  I will own that now (with help from @xuchenhan-tri).
