### ISSUE TITLE
Does ContactImplicitTrajectoryOptimization support Bullet ?

### ISSUE THREAD

**Issue by zamzami** [RobotLocomotion/drake#1709]
In an attempt to verify the quality of trajectories generated by `ContactImplicitTrajectoryOptimization` against `TimeSteppingRigidBodyManipulator`, I started by testing different geometries using `contactImplicitBrick` as a testbed.  

No contact detected using `Capsule.urdf`, `Ball.urdf` and `wheel.urdf`  with `options.use_bullet=true`. Apparently `plant.contactConstraints` doesn't use Bullet (`collisionDetectmex`) and refers to `getTerrainContactPoints`  which is only defined for `obj.radius < 1e-6`

_*_How can I ensure that Bullet is working properly with`ContactImplicitTrajectoryOptimization` ? *__

This figure shows that capsule continue falling past the flat terrain with `ContactImplicitTrajectoryOptimization` while stopping at contact for`TimeSteppingRigidBodyManipulator`
![contactimplicitcapsule](https://cloud.githubusercontent.com/assets/9399029/13030892/d95f1e62-d2b9-11e5-9f47-afbfd8d090b9.jpg)

**Comment by jwnimmer-tri** [comment]
Closing as won't-fix, because #6369 will be removing the relevant software.

If I'm confused and this should in fact stay open, please re-open an clarify the remaining unsolved problem(s) in a new comment here.
