### ISSUE TITLE
is playbackAVI deprecated on MatlabR2015b

### ISSUE THREAD

**Issue by zamzami** [RobotLocomotion/drake#1710]
I received the following error after calling `playbackAVI`

`>>v.playbackAVI(ytraj,'step00001')
Error using getframe (line 74)
The specified rectangle is not fully contained within the figure. MATLAB no longer supports this
capability.`

`Error in Visualizer/playbackAVI (line 423)
          fr=getframe(f,[0 0 width height]);  % explicitly ask for the same size, otherwise videowriter
          will complain`

**Comment by RussTedrake** [comment]
won’t fix.  (focused on c++ version for now)
