### ISSUE TITLE
Changes to CI schedule frequency

### ISSUE THREAD

**Issue by jwnimmer-tri** [RobotLocomotion/drake#17124]
To remove:

- [x] `linux-focal-unprovisioned-clang-bazel-continuous-(debug|release|everything-debug|everything-release)` remove.
  - We already have it in Nightly, and we don't need fast feedback here.
-  [x] `linux-focal-unprovisioned-gcc-bazel-continuous-(debug|everything-debug|everything-release)` remove.
  - We already have it in Nightly, and we don't need fast feedback here.
  - Note that `linux-focal-unprovisioned-gcc-bazel-continuous-release` stays as Continuous.
- [x] `linux-focal-gcc-cmake-continuous-(debug|everything-debug|everything-release)` remove.
  - We already have it in Nightly, and we don't need fast feedback here.
  - ~Also remove `linux-focal-clang-cmake-continuous-release`.~
  - Note that only `linux-focal-gcc-cmake-continuous-release` stays as Continuous.
- [x] `linux-focal-clang-bazel-continuous-everything-(debug|release)` remove.
  - We already have it in Nightly, and we don't need fast feedback here.
- [x] `linux-focal-gcc-bazel-continuous-everything-debug` remove.
  - We already have it in Nightly, and we don't need fast feedback here.
- [x] `linux-focal-clang-bazel-continuous-(address|leak)-sanitizer` remove.
  - We already have it in Nightly, and we don't need fast feedback here; the "everything" variant is still in Continuous.
- [x] `mac-monterey-clang-cmake-continuous-release` remove.
  - We already have it in ~Nightly~ Weekly, and we don't need fast feedback here.
- [x] `mac-monterey-unprovisioned-clang-bazel-continuous-snopt-mosek-packaging` remove.
  - We already have it Weekly, and we don't use these tarballs for anything.

---

To change schedule:

- [x] `linux-focal-(gcc|clang)-bazel-nightly-everything-coverage` switch to Weekly instead of Nightly.
  - This is unlikely to fail individually, and is expensive.

**Comment by jwnimmer-tri** [comment]
If my math is correct, that will leave only these jobs in Continuous:
- `linux-focal-clang-bazel-continuous-debug`
- `linux-focal-clang-bazel-continuous-everything-address-sanitizer`
- `linux-focal-clang-bazel-continuous-everything-leak-sanitizer`
- `linux-focal-clang-bazel-continuous-release`
- `linux-focal-gcc-bazel-continuous-debug`
- `linux-focal-gcc-bazel-continuous-everything-release`
- `linux-focal-gcc-bazel-continuous-release`
- `linux-focal-gcc-cmake-continuous-release`
- `linux-focal-unprovisioned-gcc-bazel-continuous-documentation`
- `linux-focal-unprovisioned-gcc-bazel-continuous-mirror-to-s3`
- `linux-focal-unprovisioned-gcc-bazel-continuous-release`
- `linux-focal-unprovisioned-gcc-bazel-continuous-snopt-mosek-packaging`
- `mac-big-sur-clang-bazel-continuous-release`
- `mac-big-sur-clang-cmake-continuous-release`
- `mac-big-sur-unprovisioned-clang-bazel-continuous-snopt-mosek-packaging`
- `mac-monterey-clang-cmake-continuous-release`

**Comment by BetsyMcPhail** [comment]
Note that linux-focal-clang-cmake jobs were all removed in #17073

**Comment by BetsyMcPhail** [comment]
The Continuous list in Jenkins now matches with what is listed above, with the exception of `mac-monterey-clang-bazel-continuous-release`  which has _not_ been removed yet, see my previous comment.

**Comment by jwnimmer-tri** [comment]
> mac-monterey-clang-cmake-nightly-release doesn't exist. Should this be mac-big-sur-clang-cmake-continuous-release?

I'm not sure what I was thinking, but yes this sounds better.  I think my goal was for only one mac cmake build to run in Continuous.  Seems like big-sur is the right choice for that.

**Comment by BetsyMcPhail** [comment]
Changes to drake-jenkins-job are at [f779025](https://github.com/RobotLocomotion/drake-jenkins-jobs/commit/f77902524b94ab44a7aa7bb515a0da9a8fe70c38)
