### ISSUE TITLE
Add Polynomial::Expand() function

### ISSUE THREAD

**Issue by hongkai-dai** [RobotLocomotion/drake#17130]
We have `Expression::Expand()`. I think it is natural to add `symbolic::Polynomial::Expand()`
```cc
symbolic::Polynomial Polynomial::Expand();
```
which expands all the coefficients for every monomial, and returns the expanded polynomial.

One question I have is about monomial with 0 coefficient. From the user's perspective, is it more natural to keep or remove the monomial with 0 coefficient after expansion? I am leaning towards removing the zero-monomial as it is redundant, and `Expression::Expand()` function does a lot of work to remove the redundancy. But I would like to hear the user's opinion.

@jwnimmer-tri  what do you think?

**Comment by jwnimmer-tri** [comment]
My impression is that `symbolic::Polynomial` maintains an invariant that no coefficient can ever be zero.  There is a lot of code to already enforce that (though there are a few glaring errors where we fail to preserve it, e.g., `Polynomial::EqualToAfterExpansion`).  I think we should strip out zero coefficients.

**Comment by hongkai-dai** [comment]
>  (though there are a few glaring errors where we fail to preserve it, e.g., Polynomial::EqualToAfterExpansion).

Yeah I also notice that EqualToAfterExpansion doesn't strip zero. I will fix it.
