### ISSUE TITLE
try enabling lcm for 32-bit windows 

### ISSUE THREAD

**Issue by RussTedrake** [RobotLocomotion/drake#1715]
@jhoare -- you said that lcm was working now on 32-bit windows (or specifically, that you didn't need the if 32-bit logic in the lcm CMakeLists.txt).  But lcm is not being build by the drake test suite on 32-bit because of the logic in the drake superbuild at https://github.com/RobotLocomotion/drake/blob/master/CMakeLists.txt#L38 .

If you pull the lcm option ON out of those conditionals and get it to build on win32 (really 32), then fantastic.  otherwise, we should probably put the win32 check back into the lcm CMakeLists.txt, too?  The best, of course, would be to successfully build lcm on win32.

**Comment by billhoffman** [comment]
It will not work with the super build and 32 bit because the gtk libraries are 64 bit.  So, the check needs to stay.

**Comment by RussTedrake** [comment]
Good point.  Does lcm fail with a useful error on 32-bit because it cannot find glib?  if yes, then we can simply close this.  If no, then we should restore that original check (assuming I remember correctly that it was removed)

**Comment by jhoare** [comment]
It looks like we should be able to build lcm on windows32 and windows 64. There was an issue with gtk-pod which always installed 64bit version of gtk. 

See https://github.com/RobotLocomotion/gtk-pod/pull/3

**Comment by RussTedrake** [comment]
Awesome. Good catch. I’ve merged the other PR. Please give it a shot!
