### ISSUE TITLE
Question: Interactive marker?

### ISSUE THREAD

**Issue by tdinesh** [RobotLocomotion/drake#1717]
What is the interactive marker used in the following video. Could you please point me to the right example/usage? 
https://www.youtube.com/watch?v=iyWYXnJ0yQE

Thanks!

**Comment by iamwolf** [comment]
Hey @tdinesh!
The video uses the interactive IK functionality of https://github.com/RobotLocomotion/director as shipped as part of https://github.com/openhumanoids/oh-distro. It can be accessed through the Teleop Panel.

**Comment by tdinesh** [comment]
Thanks @iamwolf! I will take a look.
