### ISSUE TITLE
Parametrizing `ConstraintRelaxingIk` to specify max num / add timeout logic

### ISSUE THREAD

**Issue by 5yler** [RobotLocomotion/drake#17189]
Context: 
- I'm using `ConstraintRelaxingIk` when planning online during robot operation in a context where speed is important. 
- The current implementation has [a few hardcoded parameters](https://github.com/RobotLocomotion/drake/blob/88fea982f7e7c10d1a809cf73c1c90a14719b8ba/manipulation/planner/constraint_relaxing_ik.cc#L58-L64) including `kMaxNumConstraintRelax`.
- IK calls which fail to find a solution take a much longer time to return vs. a successful IK call.

I'm looking into rewriting the class in a way that would:
- load the linked parameters above instead of hardcoding, and/or 
- allow a timeout value to be specified for the computation (regardless of whether or not the IK call succeeds)

Wondering if anyone has looked into this problem already, and/or has thoughts on the best way to structure the above.

**Comment by hongkai-dai** [comment]
@siyuanfeng-tri as the original author of ConstraintRelaxingIk, could you take a look at this issue? Thanks!

**Comment by 5yler** [comment]
As a simple workaround I just added a `const int64_t timeout_ms` argument with a default value to the `PlanSequentialTrajectory` function, and break out of the while loop if the timeout is exceeded. I think making it optional in that way takes care of any reverse compatibility issues but also gives greater control to the caller on when to fail out of trying to solve.

**Comment by 5yler** [comment]
Alternatively: I tried putting together a derived class of `ConstraintRelaxingIk` with an overridden `PlanSequentialTrajectory` function but ran into issues with things being declared `private` - could these be changed to `protected`? I'm happy to PR either change but adding a timeout argument would be an actual API change to `PlanSequentialTrajectory`

**Comment by jwnimmer-tri** [comment]
It would be very easy change those constants into parameters.  Something like this:
 
```c++
struct ConstraintRelaxingIkParams {
  int max_num_initial_guess = 50;
  int max_num_constraint_relax = 10;
  Vector3d initial_pos_tolerance(0.01, 0.01, 0.01);
  double initial_rot_tolerance = 0.01;
  double constraint_shrink_factor = 0.5;
  double constraint_grow_factor = 1.5;
};
```

Then for the user to specify them, we could have some combination of:

(1) Optionally pass `ConstraintRelaxingIkParams` to the constructor.

(2) Call `ConstraintRelaxingIkParams::SetParams(ConstraintRelaxingIkParams)`.

(3) Optionally pass `ConstraintRelaxingIkParams` to `PlanSequentialTrajectory`.

Would that be enough to resolve the request?

If you actually need a user-defined customization (e.g., timeout), then we would probably do that by providing a callback argument on `PlanSequentialTrajectory`, so the user can do as they like.  In your case, you could have your callback check the wall clock and tell the planner to cancel in case it's been too long.

**Comment by jwnimmer-tri** [comment]
Update from offline chat -- simply offering `ConstraintRelaxingIkParams` will not be good enough; we basically want to offer cancellation in this API, via some kind of callback (or future/signal).
