### ISSUE TITLE
Revisit macOS skipped examples

### ISSUE THREAD

**Issue by svenevs** [RobotLocomotion/drake#17297]
Followup: https://github.com/RobotLocomotion/drake/pull/17292#pullrequestreview-990805453

Affects at least:

- https://github.com/RobotLocomotion/drake/blob/master/examples/manipulation_station/end_effector_teleop_sliders.py
- https://github.com/RobotLocomotion/drake/blob/master/examples/manipulation_station/end_effector_teleop_mouse.py

**Comment by jwnimmer-tri** [comment]
As of #18299, this seems finished to me.
