### ISSUE TITLE
consider making the planner instance of the System concept

### ISSUE THREAD

**Issue by RussTedrake** [RobotLocomotion/drake#1732]
@rdeits and I talked about this a bit.  planEval definitely feels like a system (albeit one that has an event input).  but should we also think about having planners defined as systems (which generate the events).

two arguments in favor include
- we ultimately do want to be able to verify a closed-loop system with a planner in the loop
- MPC (which is definitely a system)

**Comment by RussTedrake** [comment]
@david-german-tri -- something to consider in the future evolution of the new System classes.

**Comment by david-german-tri** [comment]
I think the current System2 design allows and encourages this sort of thing, so I'm going to close this as resolved.
