### ISSUE TITLE
Add wheel test for file size limit

### ISSUE THREAD

**Issue by jwnimmer-tri** [RobotLocomotion/drake#17395]
In order to host our wheels on PyPI they must be less than [100 MiB](https://github.com/pypa/warehouse/blob/2dc7fced1df51d50c142ab810c4ca736dd9163e6/warehouse/forklift/legacy.py#L72) each.

When the wheel-builder is run in test mode, it should check the `*.whl` file against that limit so that our CI build(s) will tell us in case we overstep.  Otherwise, we won't notice until the next monthly release playbook, at which point it's too late to fix the git tag.

(Even on master as of today, we're at 106 MiB so the next release will fail.)

**Comment by jwnimmer-tri** [comment]
Wheel size claims can be had via `unzip -lv foo.whl | cut -c17-26,59- | sort -rn`.  Adding MOSEK grabbed up ~9 MB of our headroom, but nothing we can do about that anymore.  I'm running a bisect now to see which commit broke the camel's back.

We'll need to find some model files to purge from the whl for now (like we already do with Atlas, etc) to get back under the limit.  I'd say `examples/hydroelastic/spatula_slip_control` is a good candidate to drop from the whl.  After that if we still need more room, maybe throw away _all_ of the YCB data (not just the pngs), since those models are already somewhat degraded anyway (without the pngs).

**Comment by jwnimmer-tri** [comment]
I tried a few options locally until I got under the size.  Please see https://github.com/jwnimmer-tri/drake/commits/whl-size for the commit that should get into master ASAP.

**Comment by mwoehlke-kitware** [comment]
> Please see https://github.com/jwnimmer-tri/drake/commits/whl-size for the commit that should get into master ASAP.

Is there a PR for that, or are you asking me to make one?

In general, I agree with Russ (not sure what happened to his comment); we very likely need to make a serious effort at excising the data files (#15774). This isn't just a problem for PyPI, it's an issue for self-hosting (i.e. AWS) nightly wheels, as it looks like we are going to have *at least* four separate wheels eventually. That's a lot of data being duplicated four times eating into our storage budgets, when we might not even need to store *any* copies.

**Comment by jwnimmer-tri** [comment]
> Is there a PR for that, or are you asking me to make one?

Please make a PR with that commit.  (There is a release due any day now, yet we cannot actually cut the release until the size is back under 100 MiB.)

> ... that's a lot of data being duplicated four times ...

That's not an accurate summary.  As of the whl-size commit above, only ~11% of the whl file (~10 MiB) is `pydrake/share`.  Certainly not nothing, but neither is it anywhere near a majority.

**Comment by mwoehlke-kitware** [comment]
> Please make a PR with that commit

#17401.
