### ISSUE TITLE
Code base should follow style guide

### ISSUE THREAD

**Issue by david-german-tri** [RobotLocomotion/drake#1741]
We should flesh out the style guide (https://github.com/RobotLocomotion/drake/wiki/Code-Style-Guide), or just adopt the ROS or Google style guide by reference, and then ensure that style is consistent across the code base.  

For either style guide, there is a clang-format style that will fix the formatting, but other issues (e.g. trailing underscores for class members) will require manual cleanup.

**Comment by jamiesnape** [comment]
I would recommend adopting either the ROS or Google code styles without modification. Then you have many tools automatically available to you (for instance, if you adopt Google you can use cpplint and include-what-you-use).

**Comment by billhoffman** [comment]
@bradking do you have any comments on this?

**Comment by bradking** [comment]
I like the use of clang-format.  I have no strong preference on the style itself.

**Comment by jhoare** [comment]
I would vote for ROS code guidelines only because I imagine there would be a lot of overlap between ROS users and drake users so not needing to switch styles would be helpful.

**Comment by psiorx** [comment]
I'd vote for the Google Style Guide with the exception of file extension naming (I prefer `.cpp` instead of `.cc`).  It's also a lot closer to the existing code we have and is more comprehensive than the ROS counterpart.

Also, the ROS Style guide encourages a number of things that we generally don't like such as passing raw pointers and putting opening curly braces on their own line.

**Comment by tkoolen** [comment]
I'm fine with either ROS or Google, with a preference for Google. I agree with John's comments. Additionally, many C++ IDEs (including mine) and text editors come with a built in google style format that you can just switch to; people wouldn't have to create their own.

**Comment by bradking** [comment]
Another advantage of Google style is that the `.clang-format` file would be very short:

    ---
    BasedOnStyle:  Google

**Comment by david-german-tri** [comment]
I'd prefer the Google style guide for comprehensiveness, and because I trust the team that maintains it. </xoogler-vote>

**Comment by liangfok** [comment]
I vote for starting with the Google style guide since its comprehensiveness will likely result in greater consistency. Also, I believe it will be easier to start with stricter guidelines and then to gradually relax them rather than the other way around.

**Comment by david-german-tri** [comment]
There seems to be a pretty strong majority for the Google style guide.  Let's start following it in new pull requests.  I'll add a .clang-format today.  Of course, there are plenty of style violations that the formatter can't handle, so those will have to be fixed up manually over time as we touch the code.  [cpplint](https://pypi.python.org/pypi/cpplint) will be useful.

Here at TRI yesterday, we discussed a multi-level code review process to take some load off of @RussTedrake.  The proposal is:

1. Get a preliminary code review from someone else.  I think ideally this would be cross-team (Kitware reviews TRI, TRI reviews Kitware) to spread knowledge.

2. Get an approval code review from @RussTedrake.  Ideally, there will be few issues requiring comment from Russ, and as a result he'll be able to approve more pull requests faster.

Any objections to giving this a try?  In the Kitware->TRI direction, you can load-balance across myself and @liangfok.  Who should we ping on the Kitware side?

**Comment by tkoolen** [comment]
I would be strongly in favor of first having a single pull request that only reformats (using an automated tool) all of the existing code without changing functionality, instead of only enforcing the style in new pull requests. 

If we don't reformat existing code first, diffs in pull requests will involve a lot of formatting changes, making code reviews harder. Plus you can't really do the formatting correctly only in the parts of a file that you've changed (e.g. indentation will be annoyingly inconsistent between parts of the file that you've changed and untouched parts). Not reformatting first would also make this transition drag on forever.

**Comment by david-german-tri** [comment]
Good point, how about this:

1. I'll reformat the entire code base in one shot using clang-format today.
2. Style requirements not related to formatting will be enforced on new pull requests in code review.

**Comment by rdeits** [comment]
Exciting :). And I agree with @tkoolen. Having accidentally caused massive diffs by having "eliminate trailing whitespace" turned on in my editor, I'm all for starting from a consistent style.

**Comment by jamiesnape** [comment]
I can set up jobs on Jenkins that run cpplint and [include-what-you-use](http://include-what-you-use.org/). They will cause a lot of noise at first, so it may be best to have them just run nightly or on-demand for the first few days.

**Comment by jamiesnape** [comment]
If anyone would like other tools to run on Jenkins, create a ticket and ping me on it.

**Comment by RussTedrake** [comment]
it seems like once negative consequence of this idea is that @david-german-tri will suddenly be the last committer for basically every line in the cpp files (git blame will always blame you).  Is that an acceptable loss?

**Comment by david-german-tri** [comment]
I'm inclined to think it is. Even if we reformatted incrementally, we'd
have the same problem on a file by file basis. It's easy enough to adjust
the git-blame revision to look past.

**Comment by RussTedrake** [comment]
OK. Agreed.

**Comment by iamwolf** [comment]
@david-german-tri Out of curiosity: On a local machine ``git blame -w -M`` ignores formatting changes (apart from linebreaks), how is it handled on [GitHub](https://help.github.com/articles/using-git-blame-to-trace-changes-in-a-file/)?

**Comment by bradking** [comment]
> it seems like once negative consequence of this idea is that david-german-tri will suddenly be the last committer for basically every line in the cpp files 

For automated conversions like that I typically use a "robot" user to take the blame.  That makes it clear that something automated was done when such lines are seen in the blame output.

I also record the script (or equivalently precise instructions) used to do the conversion in the commit message.  That way anyone can reproduce the conversion, and anyone with open topics can run the conversion themselves to help them rebase cleanly.

**Comment by RussTedrake** [comment]
Great suggestions.

On Fri, Feb 26, 2016 at 8:26 AM, Brad King <notifications@github.com> wrote:
it seems like once negative consequence of this idea is that david-german-tri
will suddenly be the last committer for basically every line in the cpp files

For automated conversions like that I typically use a "robot" user to take the
blame. That makes it clear that something automated was done when such lines are
seen in the blame output.

I also record the script (or equivalently precise instructions) used to do the
conversion in the commit message. That way anyone can reproduce the conversion,
and anyone with open topics can run the conversion themselves to help them
rebase cleanly.

—
Reply to this email directly or view it on GitHub
[https://github.com/RobotLocomotion/drake/issues/1741#issuecomment-189271507] .[https://github.com/notifications/beacon/AGJNNFh9kk2VzlJCWcaRx5TeucinqxXCks5poEoBgaJpZM4Hg9Lw.gif]

**Comment by david-german-tri** [comment]
@iamwolf I don't see a way to change the actual blame command on GitHub, but you can move backwards in time on the History tab and the blame updates accordingly.

**Comment by RussTedrake** [comment]
just spent some time (for the first time), reading the google style guide more carefully.  there are going to be a lot of painful changes.  (ex: using namespace Eigen, using namespace std, which we have at the top of most of our .cpp files are not allowed; many variable names will change; ... ).  i support this and will comply, but it's going to take time and patience to completely conform.

as much as I prefer .cpp to .cc, it seems pretty arbitrary for us to accept the entire style guide except for this rule.  i know we'll be making some amendments to the style guide, but i don't think this one is valuable enough to warrant non-compliance.  if we're going all in, then we should probably only make exceptions on moral grounds, or because of the particular demands of our codebase, not because of our own coding style inertia.

**Comment by jamiesnape** [comment]
@RussTedrake I agree. The initial pain will be worth it in the long term.

**Comment by jwnimmer-tri** [comment]
> using namespace Eigen, using namespace std, which we have at the top of most of our .cpp files are not allowed

I would support a variance to the guide to generally allow 'using namespace foo;' statements in *.cc files (but still forbid them in *.h files).  The pollution argument cited by google-styleguide is valid, but I'd rather trust our committers to use good judgement and write clear code -- and sometimes the clearest code will be with 'using namespace ...' statements atop the *.cc file.

**Comment by jamiesnape** [comment]
I would say avoiding `using namesphere` anywhere is a good thing, especially `using namespace std`. You can use a namespace alias for code clarity.

**Comment by david-german-tri** [comment]
I agree with @jamiesnape.  When namespaces are verbose, the style guide permits `using really_long_namespace::Bar;` statements for the specific names that a given .cc file uses.  In addition to keeping pollution under control and reducing collision risk (versus `using` the whole namespace), this approach documents where the name came from.

**Comment by liangfok** [comment]
I vote for avoiding the use of "using namespace foo" since it requires someone to guess where certain names come from. I would rather have numerous `using namespace::Bar` statements at the top of the file to avoid that confusion.

**Comment by jwnimmer-tri** [comment]
Sounds like a consensus, then, and OK with me.

**Comment by david-german-tri** [comment]
The Google Style Guide has been officially adopted in the docs:

https://github.com/RobotLocomotion/drake/blob/277817621bfc7a381755a109f7378253b4118978/drake/doc/code_style_guide.rst#L14
