### ISSUE TITLE
Framework for C++ Unit Tests

### ISSUE THREAD

**Issue by david-german-tri** [RobotLocomotion/drake#1743]
Rather than rolling our own ad-hoc test framework (drake/util/testUtil.h), we should consider using googletest: https://github.com/google/googletest

**Comment by RussTedrake** [comment]
That would be fantastic.

On Tue, Feb 23, 2016 at 6:23 PM, david-german-tri <notifications@github.com>
wrote:
Rather than rolling our own ad-hoc test framework (drake/util/testUtil.h), we
should consider using googletest: https://github.com/google/googletest [https://github.com/google/googletest]

**Comment by RussTedrake** [comment]
google test looks great.  @kitware -- is there a recommended way to use google test with ctest / cdash?
