### ISSUE TITLE
get rid of cygwin and cygpath stuff in pods.cmake

### ISSUE THREAD

**Issue by billhoffman** [RobotLocomotion/drake#1747]
Look into removing all cygwin stuff from the cmake drake stuff.

**Comment by david-german-tri** [comment]
@RussTedrake Does this imply we should delete the Cygwin install instructions?

**Comment by RussTedrake** [comment]
Yes.  Let's zap them.

**Comment by david-german-tri** [comment]
Windows is no longer supported.

**Comment by david-german-tri** [comment]
However, that actually doesn't resolve this issue!

**Comment by david-german-tri** [comment]
Done in #3801.
