### ISSUE TITLE
Upgrade externals to latest - July 2022

### ISSUE THREAD

**Issue by BetsyMcPhail** [RobotLocomotion/drake#17494]
Follow [Semi-automated monthly upgrades](https://github.com/RobotLocomotion/drake/blob/master/tools/workspace/README.md#semi-automated-monthly-upgrades) documentation.

Prior issue: https://github.com/RobotLocomotion/drake/issues/17306

- [x] #17496
- [x] #17505
- [x] #17495

**Comment by jwnimmer-tri** [comment]
> ... given that OSQP has not moved, QDLDL should not be touched?

I've opened a reminder here => https://github.com/RobotLocomotion/drake/issues/17506.
