### ISSUE TITLE
YAML round trip of `infinity` throws exception

### ISSUE THREAD

**Issue by dmcconachie-tri** [RobotLocomotion/drake#17503]
### What happened?

Somewhere in the YAML parsing/saving process, an "infinity" value does not survive a round trip. To reproduce, add the following to `yaml_io_test.cc`:

```
GTEST_TEST(YamlIoTest, DoubleInfRoundTripTest) {
  const DoubleStruct data_struct{
    .value = std::numeric_limits<double>::infinity(),
  };
  const std::string data_string = SaveYamlString(data_struct);
  const auto result = LoadYamlString<DoubleStruct>(data_string);
  EXPECT_EQ(result.value, data_struct.value);
}
```

Changing the `infinity` to something like `1.0` allows this test to pass.

(Presumably somewhere like `yaml_read_archive_test` or `yaml_write_archive_test` is a better place for this test at the end of the day.)

### Version

b98434ac68fd675ab10cca07c4aadbe512dae638

### What operating system are you using?

Ubuntu 20.04

### What installation option are you using?

compiled from source code using Bazel

### Relevant log output

```shell
[==========] Running 15 tests from 1 test suite.
[----------] Global test environment set-up.
[----------] 15 tests from YamlIoTest
[ RUN      ] YamlIoTest.DoubleInfRoundTripTest
unknown file: Failure
C++ exception with description "YAML node of type Mapping (with size 1 and keys {value}) could not parse double value entry for double value." thrown in the test body.
[  FAILED  ] YamlIoTest.DoubleInfRoundTripTest (1 ms)
```

**Comment by jwnimmer-tri** [comment]
Indeed, you're right.  `YamlWriteArchive::VisitScalar` is just calling `fmt` to format the data (which ends up as `inf`), yet https://yaml.org/spec/1.2.2/#10214-floating-point says it needs to be `.inf`.
