### ISSUE TITLE
CI: Mac Nightly jobs aren't launched

### ISSUE THREAD

**Issue by BetsyMcPhail** [RobotLocomotion/drake#17598]
**Description of problem:**

In the morning, all of the nightly (and weekly if Sunday night) Mac builds will be queued in the Jenkins Build Queue. The console logs will have the message:

`Waiting for next available executor on ‘[mac-....]’`

When this happens, it affects all Mac builds on VSphere (Monterey and Big Sur) and, as of this weekend, M1 Orka jobs as well.

To get jobs running again, log onto VSphere and power on _any_ image and then power off the image. Jobs will start launching immediately. 

**History:**

First reported on [March 4](https://drakedevelopers.slack.com/archives/C270MN28G/p1646418235965299)

[March 9](https://drakedevelopers.slack.com/archives/C270MN28G/p1646836355979709)

[March 14](https://drakedevelopers.slack.com/archives/C270MN28G/p1647268464625049)

[April 15](https://drakedevelopers.slack.com/archives/C270MN28G/p1650030626161669)

[July 18 and 19](https://drakedevelopers.slack.com/archives/C270MN28G/p1658158205433559)

Some older issues that may be relevant:
#2633
#2747

cc/ @svenevs

**Comment by BetsyMcPhail** [comment]
M1 jobs have a further issue, after they start running they hang with the error message:

`mac-m1-monterey-provisioned_19b23f7350009 was marked offline: Connection was broken: java.io.EOFException`


For example, [mac-m1-monterey-provisioned-clang-bazel-nightly-non-production-release](https://drake-jenkins.csail.mit.edu/view/Mac%20M1/job/mac-m1-monterey-provisioned-clang-bazel-nightly-non-production-release/6/). This error also appeared with Friday's nightly builds

**Comment by BetsyMcPhail** [comment]
Current plan:

- [ ] Open an issue with MacStadium. There was an upgrade on Friday just before these issues started.
- [ ] For a workaround, create a job that does nothing but connect to a VSphere node once every 2 or so hours.
- [ ] Update the Orka Jenkins plugin. This will involve a Jenkins restart so we'll need to schedule a good time to do this.

**Comment by BetsyMcPhail** [comment]
Possibly related to #17440

**Comment by BetsyMcPhail** [comment]
Sometime after 10pm on July 20, all of the VSphere snapshots disappeared and the Mac nightlies once again didn't start. The most recent snapshots have been re-created and Mac jobs are running again.

**Comment by svenevs** [comment]
We optimistically are closing this issue as resolved for this round.  Canary job for vSphere connectivity problems: https://drake-jenkins.csail.mit.edu/job/mac-monterey-vsphere-keepalive/ (simple cron that runs every 2 hours, just clones on an agent and exits).
