### ISSUE TITLE
[multibody] Inconsistent notation in WeldJoint

### ISSUE THREAD

**Issue by RussTedrake** [RobotLocomotion/drake#17600]
### What happened?

The joint documentation (e.g. the figure/text at the top of https://drake.mit.edu/doxygen_cxx/classdrake_1_1multibody_1_1_joint.html ) uses P for the parent body, F for the joint frame on the parent body, M for the joint frame on the child body and B for the child body.  We actually use C for the child body often; there are *many* instances of `X_PC` in the code.

The `WeldMobilizer` constructor is consistent, taking `X_FM` in the constructor here: https://github.com/RobotLocomotion/drake/blob/c1fa510ad96de5fe350d1cc18ffbef9fa6de9a47/multibody/tree/weld_mobilizer.h#L32-L34
But the `WeldJoint` takes `X_PC` in the constructor and passes it as `X_FM` into the mobilizer blueprint call here:
https://github.com/RobotLocomotion/drake/blob/c1fa510ad96de5fe350d1cc18ffbef9fa6de9a47/multibody/tree/weld_joint.cc#L54-L55

This inconsistency causes at least two bugs in the current code, where `weld_joint.X_PC()` is being used as the parent body to child body transform (not `X_FM`):
- GlobalInverseKinematics uses it here: https://github.com/RobotLocomotion/drake/blob/03858348696e9ac5ba4985ac005d74ec5c42a476/multibody/inverse_kinematics/global_inverse_kinematics.cc#L133
- The Mujoco Parser passes in the parent body to child body transform (not `X_FM`) into the WeldJoint here: https://github.com/RobotLocomotion/drake/blob/03858348696e9ac5ba4985ac005d74ec5c42a476/multibody/parsing/detail_mujoco_parser.cc#L690

Proposal:
- [ ] Change the argument name in the constructor of `WeldJoint` from `X_PC` to `X_FM`.
- [ ] Change the argument name in `Multibody::WeldFrames` from `X_PC` to `X_FM`.  This is used *everywhere*.
- [ ] Change the implementation of `WeldJoint::X_PC()` to return the composition `X_PF * X_FM * X_MC`.  (these two will fix GlobalIK)
- [ ] Update the mujoco parser to just pass the identity matrix for `X_FM`.   
- [ ] Add a few tests to lock this in.

Question: Should we change the diagram in the Joint doxygen to use C for the child body instead of B?  Or should we perhaps use `X_PB` instead of `X_PC` in my proposals above?

**Comment by xuchenhan-tri** [comment]
I don't have a preference between B and C. However, if we are to change from B to C, we should make sure to go through each subclass of Joint to make sure the notation is consistent.

For example:
 https://github.com/RobotLocomotion/drake/blob/9bd32e2e9ca05601f22d24f5322e496b0b0e86f1/multibody/tree/revolute_joint.h#L40-L42

\cc @mitiguy for awareness.

**Comment by amcastro-tri** [comment]
This issue right now is a combination of what I see as three separate issues. I am trying to figure out who is the owner for each of these. As far as I can tell:
 1. Per f2f with @RussTedrake last week, there definitely is room for improvement in our documentation to ensure notation is consistent all across the code base. We like the notation in [this figure](https://drake.mit.edu/doxygen_cxx/classdrake_1_1multibody_1_1_joint.html) naming bodies P/B and their respective joint frames F/M.
  2.  MuJoCo parser bug fix.
  3. Global IK bug fix.

Regarding ownership of these three separate issues:
 1. Documentation should be easy to address. We just need to arrive to an agreement.
 2. What about the MuJoCo parser? is anyone working on this already? @RussTedrake are you working on this one?
 3. I imagine @hongkai-dai is the owner for the Global IK code, is this assumption correct?
 
 I propose we open an issue for these three separate tasks and assign ownership separately.

**Comment by RussTedrake** [comment]
The global IK bug was fixed in #17608.

**Comment by amcastro-tri** [comment]
@joemasterjohn will work on this one next. Thank you @joemasterjohn!

**Comment by joemasterjohn** [comment]
We decided in #17696 to deprecate `WeldJoint::X_PC()` instead of turning it into a sugar method to compute the pose of the child body frame in the parent's body frame. If this sugar is really necessary (currently the only use of `X_PC()` was in global inverse kinematics), then I think `Joint` would be a more appropriate place to put it.

Also, my reading of the mujoco parser and mujoco documentation do not seem to be in error. For a mujoco model specifying a welded body:
```
<body name="body1">
  <body name="body2" pos="1 2 3" euler="30 45 60" >
  ...
```
"pos" and "euler" will be parsed into the transform `X_PB` and the weld joint will be created between body1's body frame `P` and body2's body frame `B` where the pose of frame `B` in `P` is given by `X_PB`.
