### ISSUE TITLE
[geometry] MeshFieldLinear has broken public copy semantics

### ISSUE THREAD

**Issue by SeanCurtis-TRI** [RobotLocomotion/drake#17638]
### What happened?

`MeshFieldLinear` makes use of `DRAKE_DEFAULT_COPY_AND_MOVE_AND_ASSIGN`. It also has a `reset_on_copy<Mesh*>` field. This allows the mesh field to be easily, mindlessly copied but left in an invalid state. Any invocation on the field that requires operations on the mesh turns into a null pointer dereference.

There is a utility for cloning a `MeshFieldLinear` while accounting for the mesh semantics (`CloneAndSetMesh`). It makes (indirect) use of the copy constructor, so one should be maintained. But it should probably be private.

The move semantics *can* be public.

This came up, for example, in python bindings for the field. Through an oversight, the field was implicitly copied (allowed by the defaulted copy constructor) which led to incorrect bindings.

### Version

1.5

**Comment by DamrongGuoy** [comment]
I assume this issue is `priority: medium`.  I'll add it to my Q3 OKRs.

Is this a possible solution?  Change `reset_on_copy<const MeshType*> mesh_;` to `const MeshType* mesh_;` and document that it is a shallow copy.

**Comment by SeanCurtis-TRI** [comment]
I'd just make the copy semantics private. If anyone ever wants to clone a field, they should have to call `CloneAndSetMesh()`.

**Comment by DamrongGuoy** [comment]
Perhaps I don't understand "make the copy semantics private".  I failed to build my prototype #17670.  Please feel free to comment there. I might miss something in C++.

In the meantime, I also prototype #17671 to remove `reset_on_copy` and wait for CI now.  It built ok on my Puget.

**Comment by DamrongGuoy** [comment]
Again thanks for helping me fix #17670. I'll start the review process shortly after cleaning up.
