### ISSUE TITLE
Upgrade externals to latest - August 2022

### ISSUE THREAD

**Issue by BetsyMcPhail** [RobotLocomotion/drake#17659]
Follow [Semi-automated monthly upgrades](https://github.com/RobotLocomotion/drake/blob/master/tools/workspace/README.md#semi-automated-monthly-upgrades) documentation.

Prior issue: #17494

- [x] #17664
- [x] #17669
- [x] #17673
- [ ] #17506

**Comment by BetsyMcPhail** [comment]
@mwoehlke-kitware can you please do the updates this month? Thanks!

**Comment by mwoehlke-kitware** [comment]
Do we want to keep chasing mypy master, or wait to update that until there's a new release that incorporates our changes? (My intention had been the latter...)

**Comment by jwnimmer-tri** [comment]
Done except for https://github.com/RobotLocomotion/drake/issues/17506 which is already tracked separately.
