### ISSUE TITLE
nightly builds / releases

### ISSUE THREAD

**Issue by RussTedrake** [RobotLocomotion/drake#1766]
Moving the last remaining discussion from #1526 (and closing that issue).

everyone agrees we want nightly releases, and we need build servers running tests on those releases (ideally before it was posted, but github has a webhook for release postings that could make it easy to do things serially).
Specifically:
- [] nightly build should replace a single "nightly" release on the github release page.
- [] we can tag a good release (and increment the version num)
- [] we carry a branch "stable" which gets moved up to the latest release, and the default install instructions tell people to clone stable.

**Comment by jamiesnape** [comment]
Jenkins can post nightly builds on success. Ideally, I would post these to an S3 bucket with a public link. You could place a link the latest nightly on the wiki. I would reserve the GitHub releases for the stable versions.

**Comment by RussTedrake** [comment]
Great. Let me know the link.
On Tue, Mar 1, 2016 at 10:52 AM, Jamie Snape <notifications@github.com> wrote:
Jenkins can post nightly builds on success. Ideally, I would post these to an S3
bucket with a public link. You could place a link the latest nightly on the
wiki. I would reserve the GitHub releases for the stable versions.

—
Reply to this email directly or view it on GitHub
[https://github.com/RobotLocomotion/drake/issues/1766#issuecomment-190779847] .[https://github.com/notifications/beacon/AGJNNPeC8H7x8xD4xib87yYwCl3vY7PUks5ppGClgaJpZM4Hkeks.gif]

**Comment by jamiesnape** [comment]
Will do. To get this fully functional, we first need to resolve #1751 and #1781.

**Comment by billhoffman** [comment]
Work on a partial one for linux that uses the shell scripts.

**Comment by RussTedrake** [comment]
note: have to be very careful to not include proprietary source.  (e.g. snopt).  we have some “release_filelist” logic in the make files which help with this.  i can also share our existing packaging scripts.

**Comment by jamiesnape** [comment]
Are they the scripts in the admin repo?

**Comment by RussTedrake** [comment]
Yes.  In the www subdir

**Comment by RussTedrake** [comment]
Make that packaging subdir :-/

**Comment by RussTedrake** [comment]
the other thing that we will want to be conscious of (eventually) is to have the minimum required versions for all of the libraries on the servers that build the official releases.  (see e.g. #1428)

**Comment by david-german-tri** [comment]
Downgraded to medium because this is blocked on having code that's stable enough to release.

**Comment by jwnimmer-tri** [comment]
So here's a good question.  Should the releases be the C++ and Python code only, or also include the MATLAB support?  It seems like a big delta on effort to add MATLAB.

**Comment by RussTedrake** [comment]
I’ve been leaning to not including the matlab, just to get these up.  We’ll still need to supply some files from the source directory (urdf + meshes), but the list should be pretty reasonable.  Will also have to address path relocation issues.

**Comment by jamiesnape** [comment]
I will start with C++ and take it from there. Dealing with the pure CMake projects should be relatively easy, since the functionality for creating packages is built-in. It is mostly a case of ensuring that everything that needs to be in the installer has an `install` command in front of it.  If projects (especially Drake) are not using CMake life gets more difficult.

**Comment by jamiesnape** [comment]
The other question is which externals would you like to include. Given the variety of licenses, that impacts packaging and distribution.

**Comment by RussTedrake** [comment]
Looks like it might be worth cleaning up a little more on #4045, like setting the eigen flag and resolving the thirdParty issues in drake.  (plus resolving, or explaining, the remaining ???s)

It looks like we can get pretty far using drake + the BSD-3 and Zlib (bullet is worth including) licensed externals.  How restrictive is Zlib?

**Comment by jwnimmer-tri** [comment]
IMO Zlib is comparable with BSD-3 -- you have to be careful about labeling and notices, but it's permissive use otherwise.

**Comment by jwnimmer-tri** [comment]
Also FYI, the Eigen MPL-only flag is done (per #4065).

**Comment by RussTedrake** [comment]
Great.  Can we update #4045 with both of these comments?  (sorry I asked on this thread instead)

**Comment by jamiesnape** [comment]
I added a few notes. Bullet should be fine, I just need to double check we do not use the small amount of code under different licenses.

**Comment by jamiesnape** [comment]
If we need a solver, including part of ipopt is not out of the question. It just depends on the minimum functionality that is needed.

**Comment by RussTedrake** [comment]
sorry, i forgot.  We have permission fromthe author to redistribute code linked (statically) against snopt, but not to distribute the snopt libraries themselves.  We should definitely handle that case here (snopt is the solver of choice)

**Comment by jamiesnape** [comment]
Cool. That makes life easier.

**Comment by jamiesnape** [comment]
(I am assuming no SNOPT headers may be distributed, which is not an issue at present.)

**Comment by jamiesnape** [comment]
@RussTedrake Would you like to distribute binaries of the examples, or just libraries?

**Comment by RussTedrake** [comment]
definitely examples, too.  thanks!

**Comment by david-german-tri** [comment]
This is actively being worked, bumping the priority.

**Comment by david-german-tri** [comment]
Note from f2f: We will need to make sure that build tree RPATHs do not leak into the installed package.

**Comment by patmarion** [comment]
btw, regarding RPATH and redistributable packages, Director has packaging for linux and mac that fix up RPATH and I am quite happy with how it works!

https://github.com/RobotLocomotion/director/tree/master/distro/package

**Comment by jamiesnape** [comment]
Cool. Looks useful.

**Comment by patmarion** [comment]
fyi, I just tested Director's packaging script on the drake superbuild.  It successfully makes redistributable packages for director that also include all of drake.  If you want nightly packages/releases, I'd recommend turning this on as a starting point.

**Comment by stonier** [comment]
Jenkins now has a set of jobs under [Packaging](https://drake-jenkins.csail.mit.edu/view/Packaging/).

**Comment by EricCousineau-TRI** [comment]
BTW Should we consider this closed for now?
While explicit tagging is not being done, we can just "manually" tag the releases, and possibly mirror the release to a different URL if so desired?

**Comment by jamiesnape** [comment]
This issue about nightly releases, so tags and the whole stable release process would be different issue anyway.

**Comment by EricCousineau-TRI** [comment]
Sounds good! Closing for now.
