### ISSUE TITLE
gz_math_internal needs upgrade

### ISSUE THREAD

**Issue by mwoehlke-kitware** [RobotLocomotion/drake#17665]
August's round of release updates (#17659) reports:
```
gz_math_internal needs upgrade from ignition-math6_6.11.0 to ignition-math6_6.12.0
```

It appears a number of new files have been added and need to be sorted into appropriate groups.

**Comment by ggould-tri** [comment]
Tagging this as CI / Betsy for now (mirroring of externals) for now ; feel free to re-tag and re-assign as appropriate.
