### ISSUE TITLE
[meshcat] Hydroelastic Contact Visualization

### ISSUE THREAD

**Issue by joemasterjohn** [RobotLocomotion/drake#17679]
This issue documents the outstanding tasks to be completed to bring hydroelastic contact visualization in Meshcat to feature parity with DrakeVisualizer and beyond. This work has already started in #16913 and #17599 adding basic functionality visualizing contact patches and their corresponding force and moment vectors.

### Remaining Tasks

- [ ] #17680
- [ ] #17681
- [ ] #17682
- [ ] #17683

**Comment by jwnimmer-tri** [comment]
I think we can just prioritize the 4 existing issues individiually / independently, without an Epic grouping them.
