### ISSUE TITLE
drake-cdash-bot is loud

### ISSUE THREAD

**Issue by tkoolen** [RobotLocomotion/drake#1767]
I'm a strong proponent of restricting the conversation section of pull requests to human authors only. The standard github API for build server notifications is a much better solution than automatically posting comments to the pull request in my opinion.

**Comment by jamiesnape** [comment]
You will lose the direct links to CDash and will have to click through at least three pages to find the build error.

**Comment by jamiesnape** [comment]
Note, also the drake-jenkins-bot has to be able to comment, so we cannot restrict to human authors.

**Comment by jamiesnape** [comment]
@RussTedrake I have disabled the bot. Let me know if you change your mind.

**Comment by billhoffman** [comment]
Maybe put them all under one comment.

**Comment by billhoffman** [comment]
Look at making it less verbose.

**Comment by david-german-tri** [comment]
No one except me seems to miss this, and now that I've learned my way around the Jenkins UI I don't even miss it very much.  Resolving.
