### ISSUE TITLE
Enhance MeshcatVisualizer to offer collision geometry checkbox

### ISSUE THREAD

**Issue by jwnimmer-tri** [RobotLocomotion/drake#17688]
In #17595, we added collision geometry visualization to meldis.  We should offer the likewise feature to MeshcatVisualizer (including the alpha sliders and enable/disable checkbox control).

Details to follow.

**Comment by jwnimmer-tri** [comment]
The current meldis implementation lives at https://github.com/RobotLocomotion/drake/blob/master/bindings/pydrake/visualization/meldis.py.

The place where we add the new feature to MeshcatVisualizer is https://github.com/RobotLocomotion/drake/blob/master/geometry/meshcat_visualizer.cc.

**Comment by RussTedrake** [comment]
This would be great. For completeness: once it is implemented, we will also want to remove the manual implementation of this feature from the "authoring multibody simulation" tutorial.

**Comment by jwnimmer-tri** [comment]
(1) Run meldis to see how this feature works.  There are tickyboxes for collision vs visual, and sliders for visual alpha and collision alpha.  Do this using a simulation or example or tutorial, _not_ the model_visualizer.

(2) It's okay for the tickybox names for in the scene tree to differ between meldis and this tool.  Neither tree of names is that stellar anyway currently.

(3) TBD
