### ISSUE TITLE
Staging vs Experimenal builds

### ISSUE THREAD

**Issue by jwnimmer-tri** [RobotLocomotion/drake#17692]
See https://github.com/RobotLocomotion/drake/pull/17646#issuecomment-1198398909

**Comment by BetsyMcPhail** [comment]
drake-jenkins-job PR [#27](https://github.com/RobotLocomotion/drake-jenkins-jobs/pull/27)

**Comment by BetsyMcPhail** [comment]
Confirmed that in #17710 `@drake-jenkins-bot mac-big-sur-unprovisioned-clang-wheel-experimental-snopt-mosek-release please` launched the expected job ([here](https://drake-jenkins.csail.mit.edu/job/mac-big-sur-unprovisioned-clang-wheel-experimental-snopt-mosek-release/18/)) but no staging job ([staging jobs](https://drake-jenkins.csail.mit.edu/view/Staging/job/mac-big-sur-unprovisioned-clang-wheel-staging-snopt-mosek-release/))
