### ISSUE TITLE
Ubuntu Wheel Staging in Jenkins

### ISSUE THREAD

**Issue by jwnimmer-tri** [RobotLocomotion/drake#17699]
Please add a https://drake-jenkins.csail.mit.edu/view/Staging/ build for the linux wheels as well.  Then we can update the https://drake.mit.edu/release_playbook.html to instruct the release manger to use Staging for all of the wheel builds, instead of compiling locally.

See also #17692.

**Comment by svenevs** [comment]
Job is created on Jenkins, waiting to confirm test jobs complete before adding docs PR to the release playbook.  Right now it is split into mac and linux instructions, presumably we can fold this into one section?

**Comment by jwnimmer-tri** [comment]
Yeah, whatever will make the most sense to the person stepping through the instructions will be fine.
