### ISSUE TITLE
Is the robotiq urdf kinematically accurate?

### ISSUE THREAD

**Issue by hjjayakrishnan** [RobotLocomotion/drake#1771]
I'm modelling a similar underactuated hand in openrave. It's not exactly urdf, but the model is written in xml. Prof. Russ shows a short video of the simulation of the underactuated robotiq hand in the manipulation lectures. If you notice closely, the free closing motion (without any obstacle) of the finger is not acurate. The distal phalange is not exactly normal to the palm (https://www.youtube.com/watch?v=NgZqVjcI7P0, [0.00-0.06]s). It is important that it remains normal to the palm so as to enable the hand to perform pinch grasps. Inorder for that to happen, I've added some springs in my design (https://www.youtube.com/watch?v=AvN2G0klk2s&index=3&list=PLADOxch6A_u_s3gcbzPGKNARsj7xWaHrm). I'm guessing Robotiq also uses a similar strategy. Why was it neglected in drake? Cant springs be modelled in URDF?

**Comment by RussTedrake** [comment]
Springs can definitely be modeled in drake, and we made the robotiq hand urdf
quickly (under time pressure before the DARPA challenge) so might have taken
some short-cuts. We’d welcome any contributions that would improve the model.
There are two types of spring models you can add in drake — torsional springs
(http://drake002.csail.mit.edu/drake/urdf/drakeURDF_xsd.html#torsional_spring)
and linear springs
(http://drake002.csail.mit.edu/drake/urdf/drakeURDF_xsd.html#linear_spring_damper).
Adding those springs will (slightly) increase the complexity of the model; you
almost certainly won’t notice a difference in simulation, but it might effect
some of our analysis. For that reason, the best way to contribute would probably
be to add a robotiq_w_springs.urdf alongside the existing urdf.
- Russ
