### ISSUE TITLE
Initialize the floating base quaternion to non-zero value in IK

### ISSUE THREAD

**Issue by hongkai-dai** [RobotLocomotion/drake#17726]
Currently in InverseKinematics class, for each floating base, we add a constraint `zᵀz = 1` for its quaternion `z`. On the other hand, we initialize all decision variables to 0 by default. This is a very bad initialization for quaternions, as the gradient of the constraint `zᵀz-1 = 0` is 0 at this initialization `z=0`, hence the gradient-based optimizer will likely get stuck here.

I propose that when we add the constraint `zᵀz=1`, we also set the initial guess of `z` to a non-zero value, for example [1, 0, 0, 0].

**Comment by RussTedrake** [comment]
This seems like a very simple fix.  I'll go ahead and PR it.
