### ISSUE TITLE
Release v1.7.0 follow-up

### ISSUE THREAD

**Issue by jwnimmer-tri** [RobotLocomotion/drake#17759]
Following up from #17758.

Please manually tag docker images and upload the releases to S3.

```
binary date: 20220822
commit SHA: 7abea0556ede980a5077fe1a8cfbae59b57c7c27
release tag: v1.7.0
```

**Comment by BetsyMcPhail** [comment]
Docker images have been created and .tar.gz packages are on S3.

@jwnimmer-tri do we also want to create the apt packages?

**Comment by jwnimmer-tri** [comment]
Yes, please.

(The https://drake.mit.edu/release_playbook.html is slightly out of date.  It's boilerplate for the message I posted above failed to mention apt.  I'll add that info to the playbook soon.)

**Comment by BetsyMcPhail** [comment]
Apt packages have also been created.
