### ISSUE TITLE
install Matlab on AWS instances for Jenkins testing

### ISSUE THREAD

**Issue by billhoffman** [RobotLocomotion/drake#1782]

**Comment by billhoffman** [comment]
@RussTedrake and @jamiesnape, I tried to use the license.lic file and key.   However, sadly it does not work.  After typing in the license key and giving it the path to the license.lic file it complains that the license.lic was generated for a different computer:

![matlab-error](https://cloud.githubusercontent.com/assets/186488/13438431/f4b5448e-dfb6-11e5-80e8-a590508a4a58.png)

Might be that we have to run a license server to get this to work.

**Comment by RussTedrake** [comment]
we got the licenses for this, and @jamiesnape has made progress.  reassigning this to him.  @jamiesnape would love an update on this.

**Comment by jamiesnape** [comment]
We have nightly and continuous MATLAB builds for Linux and GCC running on Jenkins now. Some more externals need switching on and I need to finish porting the known issues script. After that we will be good from a technical point of view.

**Comment by jamiesnape** [comment]
Licenses expire in 18 days.

**Comment by RussTedrake** [comment]
great. thank you

**Comment by billhoffman** [comment]
Waiting on Matlab working on windows in CI.  Which is waiting on not using perl.

**Comment by jamiesnape** [comment]
MATLAB is installed. See #2155 and #2156 for follow up.
