### ISSUE TITLE
Should upgrade to libsdformat13

### ISSUE THREAD

**Issue by EricCousineau-TRI** [RobotLocomotion/drake#17873]
Not going to be released til end of month, but would be nice to get out in front of it.

Per VC, this came in (yay)! https://github.com/gazebosim/sdformat/pull/1112
Affected code:
https://github.com/RobotLocomotion/drake/blob/a2caba14526d6d3e8b0a8e783eb7d55ed303f813/multibody/parsing/detail_sdf_parser.cc#L548-L562

There also may be name remapping for `ign*` to `gz*` for things like math components.

**Comment by scpeters** [comment]
I am working on this in the following branch:

* https://github.com/RobotLocomotion/drake/compare/master...scpeters:drake:libsdformat13

**Comment by scpeters** [comment]
> I am working on this in the following branch:
> 
> * [master...scpeters:drake:libsdformat13](https://github.com/RobotLocomotion/drake/compare/master...scpeters:drake:libsdformat13)

I've opened a draft pull request in https://github.com/RobotLocomotion/drake/pull/17913
