### ISSUE TITLE
ScrewJoint should accept axis unit vector in constructor

### ISSUE THREAD

**Issue by scpeters** [RobotLocomotion/drake#17882]
**Is your feature request related to a problem? Please describe.**

The parameters to the `ScrewJoint` constructor are not consistent with the parameters used in other joints. The `RevoluteJoint` and `PrismaticJoint` constructors accept a unit vector parameter for the axis direction, but the `ScrewJoint` constructor has no such parameter. See the comment thread starting with https://github.com/RobotLocomotion/drake/issues/17765#issuecomment-1234928546.

**Describe the solution you'd like**

Add a `const Vector3<double>& axis` parameter to the `ScrewJoint` constructor and update the ScrewJoint mobilizer to support it to match the behavior of other joints.

**Describe alternatives you've considered**

**Additional context**

**Comment by sherm1** [comment]
cc @amcastro-tri

**Comment by scpeters** [comment]
I started work on this before noticing it is assigned to @amcastro-tri. I've started by adding a `Vector3<double>` argument to the joint and mobilizer constructor API in https://github.com/scpeters/drake/commit/0fea93a07a645da2e0803134600f55f34a334770, but I haven't yet updated the math from z-axis to use the arbitrary axis.

**Comment by xuchenhan-tri** [comment]
@scpeters Feel free to finish the working branch and turn it into a PR to Drake. I believe the issue was assigned to Alejandro simply according to component ownership: https://drake.mit.edu/issues.html.

**Comment by scpeters** [comment]
I think I've updated the math correctly, so I've opened a draft pull request in #18019
