### ISSUE TITLE
CMake on Jammy erroneously warns about python versions

### ISSUE THREAD

**Issue by RussTedrake** [RobotLocomotion/drake#17892]
### What happened?

A user reported to me: Did anybody successfully build drake on Ubuntu 22.04?
https://drake.mit.edu/from_source.html advertises the support, but I get the following with cmake:
```
-- Found Python: /usr/bin/python3 (found suitable exact version "3.10.4") found components: Development Interpreter NumPy Development.Module Development.Embed 
CMake Warning at CMakeLists.txt:252 (message):
  Python version 3.10 is NOT supported.  Python code in project
  drake_cxx_python may fail at runtime.
```

Looking at CMakeLists.txt [here](https://github.com/RobotLocomotion/drake/blob/360133f6efe33e2606b31836d1dcd643e97aa7af/CMakeLists.txt#L251-L256), I see 
```
if(NOT PYTHON_VERSION_MAJOR_MINOR VERSION_EQUAL SUPPORTED_PYTHON_VERSION)
  message(WARNING
    "Python version ${PYTHON_VERSION_MAJOR_MINOR} is NOT supported. Python "
    "code in project drake_cxx_python may fail at runtime."
  )
endif()
```

and [just above](
https://github.com/RobotLocomotion/drake/blob/360133f6efe33e2606b31836d1dcd643e97aa7af/CMakeLists.txt#L204-L208)
I see
```
if(APPLE)
  set(SUPPORTED_PYTHON_VERSION 3.10)
else()
  set(SUPPORTED_PYTHON_VERSION 3.8)
endif()
```

It looks like we need to update this logic to include Jammy?

### What operating system are you using?

Ubuntu 22.04

### What installation option are you using?

compiled from source code using CMake

**Comment by svenevs** [comment]
To clarify, we want it to warn on Linux if it's not 3.8 (focal) and not 3.10 (jammy)?

The wheel builds (not via cmake) also support 3.9 which is why I'm asking.

**Comment by jwnimmer-tri** [comment]
CMake should warn in case the user's version differs from the support matrix for source builds:
https://drake.mit.edu/from_source.html#supported-configurations
