### ISSUE TITLE
Canary weekly builds

### ISSUE THREAD

**Issue by jwnimmer-tri** [RobotLocomotion/drake#17946]
We've seen some CI failures in the weekly builds recently.

On principle, when a build fails on a less-frequent trigger schedule, we need to escalate it to a quicker schedule.  (Conversely, when build flavors are consistently passing, we can demote them to less frequent.)  This makes bisect / blame / revert much easier.

For the https://drake-jenkins.csail.mit.edu/view/Weekly%20Production/ schedule, please move one each of the linux single-solver builds (snopt, mosek, gurobi) from weekly to nightly.  Probably the best candidates are the Release builds:
- linux-focal-clang-bazel-nightly-gurobi-release
- linux-focal-clang-bazel-nightly-mosek-release
- linux-focal-clang-bazel-nightly-snopt-release

**Comment by BetsyMcPhail** [comment]
Resolved by drake jenkins jobs [PR #32]( #32)

Deleted:
linux-focal-clang-bazel-weekly-gurobi-release
linux-focal-clang-bazel-weekly-mosek-release
linux-focal-clang-bazel-weekly-snopt-release

Created:
linux-focal-clang-bazel-nightly-gurobi-release
linux-focal-clang-bazel-nightly-mosek-release
 linux-focal-clang-bazel-nightly-snopt-release
