### ISSUE TITLE
Release 1.8.0 apt, docker, S3

### ISSUE THREAD

**Issue by jwnimmer-tri** [RobotLocomotion/drake#17952]
Please manually tag docker images and upload the releases to S3:

https://github.com/RobotLocomotion/drake/releases/tag/v1.8.0

https://github.com/RobotLocomotion/drake/pull/17853

**Comment by BetsyMcPhail** [comment]
@jwnimmer-tri which SHA should used for this release?

**Comment by jwnimmer-tri** [comment]
The git sha is `ec6cf7cd27253d4d5066f2efc3cde35ced11a2d6`.

It's on the "release" page in the lower right:

![image](https://user-images.githubusercontent.com/17596505/191114428-6bef9368-faeb-4f8a-bfae-a62c21cfdeb4.png)

**Comment by BetsyMcPhail** [comment]
Thanks for the pointer!

**Comment by BetsyMcPhail** [comment]
As it turns out, we don't need the SHA with the new process.

Everything has been updated.
