### ISSUE TITLE
Homebrew periodically breaks mac unprovisioned builds

### ISSUE THREAD

**Issue by ggould-tri** [RobotLocomotion/drake#17979]
Mac unprovisioned builds pull the latest homebrew; this occasionally breaks Drake by introducing a new dependency version that we do not support, or occasionally an outright version conflict.

* Errors such as missing input file 'external/vtk/include/vtk-8.2/vtk_kwiml.h' indicate that the vtk bottles need to be rebuilt because a dependency changed.
  * See, e.g., https://github.com/RobotLocomotion/drake/issues/14206
  * Strongest indicator this is the problem: the phrase `.reinstall` is found in the logs.
* Errors where major python libraries are missing (`ModuleNotFoundError: No module named 'scipy'` or similar) indicate that homebrew changed its python revision.
  * See, e.g., https://github.com/RobotLocomotion/drake/issues/14243
 * (please add to this list as you discover new failure modes)

This is a known issue with homebrew's release engineering philosophy and we do not expect that it will ever be fixed.  This issue exists to put it on buildcop's list of known failures and cause searches to find this.

**Comment by jwnimmer-tri** [comment]
Note at least that the VTK problem will be solved by #16502 (because we'll no longer be using bottles).

**Comment by jwnimmer-tri** [comment]
Closing until we have a second occurrence to note, at which point we can re-open.
