### ISSUE TITLE
matplotlib sometimes breaks CI with "fontList.json" complaint

### ISSUE THREAD

**Issue by ggould-tri** [RobotLocomotion/drake#17980]
Matplotlib breaks bazel test isolation by allowing a local font cache to influence builds.  This cache can occasionally be corrupted, causing a build failure.  The build failure will contain the string `fontList.json` and will typically clear when re-run.

Thus far this issue has only been observed in linux provisioned builds.

```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/matplotlib/font_manager.py", line 1448, in <module>
    fontManager = json_load(_fmcache)
  File "/usr/lib/python3/dist-packages/matplotlib/font_manager.py", line 977, in json_load
    with open(filename, 'r') as fh:
FileNotFoundError: [Errno 2] No such file or directory: '/home/ubuntu/.cache/matplotlib/fontList.json'
```

The underlying issue was discarded as "WONTFIX" in #14250 so this issue simply serves to alert buildcops to the resulting CI noise defect.

**Comment by jwnimmer-tri** [comment]
Closing until we see evidence of additional occurrences that would merit more investment.
