### ISSUE TITLE
Linking SNOPT outside of Drake build process

### ISSUE THREAD

**Issue by Rahtron3030** [RobotLocomotion/drake#1799]
I have configured and built Drake without SNOPT. I have SNOPT installed separately from the Drake build process. How do I link my external SNOPT to Drake? SNOPT is not linked from my /usr/local/bin.

**Comment by RussTedrake** [comment]
To use snopt in matlab, you should simply have to add the matlab directory to your path.  To link it from c, you'll need to make a pkgconfig file.  Mine looks like this:

```
drake008% more snopt_c.pc
prefix=/Users/russt/drake-distro/build
exec_prefix=${prefix}
libdir=${exec_prefix}/lib
includedir=${prefix}/include

Name: snopt_c
Description: snopt_c
Requires:
Version: 0.0.1
Libs: -L${libdir}  -L/Users/russt/drake-distro/build/lib -lsnopt_c -lf2c
Cflags: -I${includedir}  -I/Users/russt/drake-distro/build/include/snopt
classpath=
```
where snopt_c is the library that results from building the csrc directory.
