### ISSUE TITLE
Upgrade externals to latest - October 2022

### ISSUE THREAD

**Issue by BetsyMcPhail** [RobotLocomotion/drake#18023]
Follow [Semi-automated monthly upgrades](https://github.com/RobotLocomotion/drake/blob/master/tools/workspace/README.md#semi-automated-monthly-upgrades) documentation.

- #18028
- #18031
- #18032
- #18033
- #17910

Note also that qdldl is also still in a weird state; see #17506.

Prior issue: #17807

**Comment by jwnimmer-tri** [comment]
For the new issues #18031 and #18032 and #18033, please finish this part of the instructions:

> [... open an issue and ...] assign it to the feature owner associated with that external ...

**Comment by jwnimmer-tri** [comment]
All of the upgrades are either merged, or filed as distinct issues.
