### ISSUE TITLE
bot2-lcmgl not found 

### ISSUE THREAD

**Issue by zeber19** [RobotLocomotion/drake#1804]
Hi I am running into the following error when attempting to make from source on linux (ubuntu 14.04)

`[ 87%] Performing configure step for 'drake'
-- CMAKE_INSTALL_PREFIX=/home/masher/git/drake-distro/build
CMake Warning at cmake/mex.cmake:241 (message):
  Your MEX compiler flags contained '-ansi', but we've removed that flag for
  compatibility with C++11
Call Stack (most recent call first):
  CMakeLists.txt:120 (mex_setup)

-- Found matlab
CMake Error at CMakeLists.txt:178 (message):
  

  

  ----- ERROR: bot2-lcmgl not found

-- Configuring incomplete, errors occurred!
`

I have been tracking down missing dependencies but am seemingly out of ideas at this point. How should I proceed?

Thanks

**Comment by RussTedrake** [comment]
My guess is it's this #1774

**Comment by zeber19** [comment]
Yes, that seemed to be the problem. Thanks much
