### ISSUE TITLE
Release v1.9.0 docker and apt

### ISSUE THREAD

**Issue by jwnimmer-tri** [RobotLocomotion/drake#18064]
Please manually tag docker images and upload the releases to S3.

https://github.com/RobotLocomotion/drake/releases/tag/v1.9.0

Date: `20221009`

Git sha: `a1a5acb35c41708a2a6f0b00c7391cf79d7a3e05`

**Comment by BetsyMcPhail** [comment]
S3 and docker are complete for Focal and Jammy.

**Comment by BetsyMcPhail** [comment]
Apt is also complete for Focal.

**Comment by BetsyMcPhail** [comment]
The jammy apt package is up!
