### ISSUE TITLE
Parser: add a "plural" method for string input

### ISSUE THREAD

**Issue by rpoyner-tri** [RobotLocomotion/drake#18060]
#18059 recommends deprecation and removal of the "singular" parser methods. Before we can do that, we should add a "plural" string input parser method, since none currently exists.

**Comment by jwnimmer-tri** [comment]
Related to this and #18059, I'd posit that the current functions names are a bit awkward, so we could simplify:

```c++
class Parser {
  std::vector<ModelInstanceIndex> AddModels(file_name);
  std::vector<ModelInstanceIndex> AddModelsFromString(file_contents, file_type);
};
```

I'd probably advocate that `AddAllModelsFromFile` stay around without deprecation markers for a while, so we can give a bit longer for a transition time on such a central API.
