### ISSUE TITLE
[pydrake/math] need bindings for RigidTransform::GetMaximumAbsoluteTranslationDifference and friends

### ISSUE THREAD

**Issue by RussTedrake** [RobotLocomotion/drake#18071]
Several of the RigidTransform methods do not have bindings yet in pydrake.

**Comment by sherm1** [comment]
Would you take a look at this please @mitiguy ?

**Comment by mitiguy** [comment]
I am starting this now.

**Comment by mitiguy** [comment]
PR #18173 resolves issue #18071.
