### ISSUE TITLE
De-duplicating Nightly Production vs Continuous Production

### ISSUE THREAD

**Issue by jwnimmer-tri** [RobotLocomotion/drake#18088]
These jobs are scheduled in both Continuous and Nightly:

```
linux-focal-clang-bazel-debug
linux-focal-clang-bazel-everything-address-sanitizer
linux-focal-clang-bazel-everything-leak-sanitizer
linux-focal-clang-bazel-release
linux-focal-gcc-bazel-debug
linux-focal-gcc-bazel-everything-release
linux-focal-gcc-bazel-release
linux-focal-gcc-cmake-release
linux-focal-unprovisioned-gcc-bazel-release
mac-big-sur-clang-bazel-release
mac-big-sur-clang-cmake-release
mac-monterey-clang-bazel-release
```

(Or at least, they are scheduled in 2 of the 3 {Continuous, Nightly, Weekly}, most likely Continuous and Nightly.)

There's not really any reason why they need to run Nightly in addition to Continuous.  True, if there were not PRs being merged then they would go for a day or two without re-running, but I don't think that risky in these cases.

Please remove the slower schedule flavor for the above jobs (e.g., remove Nightly if it's already in Continuous; remove Weekly if it's already in Nightly).

---

To be clear, the jobs below _are also_ duplicated in both Continuous and Nightly but that's working as intended.  They publish artifacts so it's important to keep those on a dual schedule.

```
linux-focal-unprovisioned-gcc-bazel-documentation
linux-focal-unprovisioned-gcc-bazel-snopt-mosek-packaging
mac-big-sur-unprovisioned-clang-bazel-snopt-mosek-packaging
```

**Comment by BetsyMcPhail** [comment]
Note: `mac-monterey-clang-bazel-release` was a weekly job, the remainder were nightly. 

Jenkins has been updated.
