### ISSUE TITLE
build documentation to a proper web server

### ISSUE THREAD

**Issue by RussTedrake** [RobotLocomotion/drake#1810]
I’m currently hosting sphinx and doxygen output on drake002.csail.mit.edu using a post-commit hook and some custom scripts.  Would much prefer to have that on a better server (and not using my scripts).

**Comment by jamiesnape** [comment]
readthedocs.org is the obvious place as you are using sphinx. They have support for custom domain names too.

**Comment by jamiesnape** [comment]
Duplicate of #2150.
