### ISSUE TITLE
Should upgrade to libsdformat 13.1.0

### ISSUE THREAD

**Issue by scpeters** [RobotLocomotion/drake#18129]
I noticed in https://github.com/RobotLocomotion/drake/pull/18127 that some recent changes to libsdformat (probably https://github.com/gazebosim/sdformat/pull/1147) have added API overloads that take a `ParserConfig` object, which causes some `Drake must never use ParserConfig::GlobalConfig()` exceptions in the `//multibody/parsing:detail_sdf_geometry_test` test. It should be straightforward to fix.

**Comment by scpeters** [comment]
draft PR in https://github.com/RobotLocomotion/drake/pull/18130

**Comment by jwnimmer-tri** [comment]
For the record -- there's no need to open a tracking issue concurrently with a PR.  You can just open the PR, for simplicity.
