### ISSUE TITLE
RotationMatrix to RPY

### ISSUE THREAD

**Issue by paarthshah-tri** [RobotLocomotion/drake#18151]
**Is your feature request related to a problem? Please describe.**
No explicit problem, just a simple feature request.

**Describe the solution you'd like**
The RotationMatrix class should have a  function .toRollPitchYaw() simliar to the .ToQuaternion() and .ToAngleAxis() functions, especially given that it has a constructor that takes in a RollPitchYaw class.

**Describe alternatives you've considered**
Create a RollPitchYaw function from the RotationMatrix since

**Comment by ggould-tri** [comment]
Assigning @rpoyner-tri for now per component ownership; Rico, feel free to reassign.

**Comment by mitiguy** [comment]
I talked to @paarthshah-tri early about this and will do it now.

**Comment by mitiguy** [comment]
PR #18172 helps to address the C++ part of issue #18151.
A separate PR will create Python bindings to finish resolving that issue.

**Comment by mitiguy** [comment]
PR https://github.com/RobotLocomotion/drake/pull/18187 resolves issue https://github.com/RobotLocomotion/drake/issues/18151.
