### ISSUE TITLE
bot2-lcmgl not found

### ISSUE THREAD

**Issue by RoboEngineer** [RobotLocomotion/drake#1817]
Hi all,

I installed Java but still got an error on "bot2-lcmgl not found" with the following errors. 
Here is the link I downloaded the javaJDK for a mac 64bit version. Later I tried to turn off "with_lcm" and "with_libbot". It still gets the same error.
http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html

"-- Configuring incomplete, errors occurred!
See also "/Users/Y/drake-distro/drake/pod-build/CMakeFiles/CMakeOutput.log".
make[3]: *** [drake-prefix/src/drake-stamp/drake-configure] Error 1
make[2]: *** [CMakeFiles/drake.dir/all] Error 2
make[1]: *** [all] Error 2
make: *** [all] Error 2"

Could you please give a little bit more detail instruction on how to solve it? Please help! Thank you very much!

**Comment by RussTedrake** [comment]
see #1774

**Comment by RoboEngineer** [comment]
Thanks Russ! But I am not sure how to check for java at the drake-distro level and error out immediately (before they get to compiling libbot)? Do you think you could provide a more detail instruction? Really appreciate!

**Comment by jonathan-owens** [comment]
@RoboEngineer Hey Robo -- Try running ``make clean`` in your super-build directory, then clean your CMake cache and reconfigure and regenerate and then rebuild drake. 

I am working on a fix right now so this doesn't happen while still allowing one to specify which Java in the super-build and then have that propagate to the external projects.

**Comment by RoboEngineer** [comment]
@jonathan-owens Thank you very much Jonathan. I got some error when I just type in `make clean`. But I can clean it with 'rm -rf build'. 
And I redid the steps starting from "Mandatory platform specific instructions" then it works!

Thank you very much!

**Comment by jonathan-owens** [comment]
Yes, the ``make clean`` has some errors, that is expected. That's being addressed. See, e.g., issue #1338. Glad you're up and working!

@RussTedrake should we close this?
