### ISSUE TITLE
Wheel CMake Build Improvements

### ISSUE THREAD

**Issue by svenevs** [RobotLocomotion/drake#18233]
Redirect from #18189.  None of these issues are show-stoppers.

- [x] bzip2 `length modifier 'L' results in undefined behavior or no effect with 'u' conversion specifier [-Wformat]`, try updating version.
- [x] `libtiff` `Manually-specified variables were not used by the project`, set `JPEG_INCLUDE_DIRS` and `LIBLZMA_INCLUDE_DIRS` (`find_package` finds the right thing because of library roots also specified)
- [x] `mumps`: longstanding warnings about `Type mismatch in argument 's' at (1); passed INTEGER(4) to LOGICAL(4)`, likely no solution (`gfortran`)
- [x] arm64 builds littered with `warning: could not create compact unwind for`, no known solution

**Comment by mwoehlke-kitware** [comment]
FYI, we're already using the latest bzip2.

**Comment by jwnimmer-tri** [comment]
> libtiff Manually-specified variables were not  ...

Fixed in #18630, looks good.

> bzip2 length modifier 'L' results in undefined behavior or no effect with 'u' conversion specifier [-Wformat], try updating version.

Not worth exploring.  The warning seems unlikely to be a problem in practice.

> mumps: longstanding warnings about Type mismatch in argument 's' at (1); passed INTEGER(4) to LOGICAL(4), likely no solution (gfortran)

Not worth exploring.  The warning seems unlikely to be a problem in practice.

> arm64 builds littered with warning: could not create compact unwind for, no known solution

IIRC @williamjallen mentioned a bazel output filter flag that could fix this.  I'm pretty sure it happens on non-Wheel builds as well.
