### ISSUE TITLE
create a fork of Bullet to keep patches in and use in bullet-pod

### ISSUE THREAD

**Issue by billhoffman** [RobotLocomotion/drake#1824]
See https://github.com/RobotLocomotion/bullet-pod/pull/10 for discussion.

**Comment by RussTedrake** [comment]
just created https://github.com/RobotLocomotion/bullet3 and gave you guys write access.

**Comment by RussTedrake** [comment]
this was done.  and @erwincoumans has a PR to bring it upstream:
https://github.com/bulletphysics/bullet3/pull/581
