### ISSUE TITLE
macOS arm64 CI cache server

### ISSUE THREAD

**Issue by svenevs** [RobotLocomotion/drake#18286]
Prototype on orka CI for arm64 the cache server.  Relates: #17210.

- MacStadium is developing macOS and linux cache server prototypes that we will be able to test soon.  [Ticket 142250](https://portal.macstadium.com/support-center/tickets/SERVICE-142250).

**Comment by jwnimmer-tri** [comment]
I don't recall any specific testing ideas.  Best is probably just to point a bazel build at the cache server and see what happens.  Run it once to populate the cache, then a new build (on a different machine) should be very fast (order of ~10x faster).  Those builds could be run by hand, or using Jenkins triggers, either way.

**Comment by svenevs** [comment]
Anticipated start date to be able to begin diagnostics and storage analysis: week of 11/30/2022 (after the orka update in #18287).  The hope is to be able to test prototypes of a couple of different flavors of the [cache server options](https://bazel.build/remote/caching#cache-backend).  They appear to almost have a macOS option available but are also looking into getting a linux host connected to try out as well.

**Comment by svenevs** [comment]
I found a nice article talking about the bazel cache and it mentions something we may want to look into about the `disk cache`, only skimmed the article for now, putting a bookmark here for later: https://brentley.dev/bazels-remote-caching-and-remote-execution-explained/

**Comment by svenevs** [comment]
Whoops!  Sorry for accidentally closing...

Intended to add a followup, in `nginx` land we upload to `${server}:${port}/${build_salt}` where the `build_salt` is just a [hash of various components of the build](https://github.com/RobotLocomotion/drake-ci/blob/main/driver/configurations/cache.cmake).

In [`bazel-remote` land](https://github.com/buchgr/bazel-remote#http11-rest-api) discussing:

> Cache entries are set and retrieved by key, and there are two types of keys that can be used:
>
> 1. Content addressed storage (CAS), where the key is the lowercase SHA256 hash of the entry. The REST API for these entries is: `/cas/<key>` or with an optional but ignored instance name: `/<instance>/cas/<key>`.
> 2. Action cache, where the key is an arbitrary 64 character lowercase hexadecimal string. Bazel uses the SHA256 hash of an action as the key, to store the metadata created by the action. The REST API for these entries is: `/ac/<key>` or with an optional instance name: `/<instance>/ac/<key>`.
>
> ...
>
> **If the `--enable_ac_key_instance_mangling` flag is specified and the instance name is not empty, then action cache keys are hashed along with the instance name to produce the action cache lookup key. Since the URL path is processed with Go's [path.Clean](https://golang.org/pkg/path/#Clean) function before extracting the instance name, clients should avoid using repeated slashes, ./ and ../ in the URL.**

@jwnimmer-tri when you read that do you agree that this instance mangling flag is what we're looking for?  My previous attempt overlooked needing to launch the server with this flag and I'll be able to test that once the current builds finish.  Otherwise, you had mentioned in the meeting that there may be some cache specific flags for salting or doing something like `--action_env=cache_salt=${salt}`?  Did you ever find those flags?

**Comment by jwnimmer-tri** [comment]
I think we need even the CAS cache to be partitioned by the drake-ci `DASHBOARD_REMOTE_CACHE_KEY`.  When two builds differ by the GCC version, we need them to use separate caches, because with the way we have Bazel configured, it won't notice the different minor or patch versions.

If there isn't any better flag for it, we can pass `--action_env=REMOTE_CACHE_KEY=...` to mix our key into every action.

**Comment by jwnimmer-tri** [comment]
From f2f: let's just add `action_env` noted above for all CI-cached builds.  That should be safe in all cases.

(It actually wouldn't hurt to add everywhere, other than possibly confusing us maintainers reading the logs.)

**Comment by svenevs** [comment]
First, some metrics.  Analysis to follow in a summary paragraph -- quick disclaimers about the benchmarks:

- Some of these jobs were sampled a couple of times and averaged.  Some jobs data was only collected once.
- Averaged builds included two versions:
    - A node with both VMs deployed, but one was idle.
    - A node with both VMs deployed, and both running at max capacity.
    - Example: debug everything cache read build took ~2345 seconds to read the cache when there was an idle VM, or ~3445 seconds when both VMs were running full blast.

Takeaway: the metrics are good estimators, but the timings and "speedup" metrics have some pretty large "margins of error".  Some measurements taken early on may be slower than true for CI, I learned at one point that attaching a "ScreenShare" session would crash debug builds (likely too little RAM available) but worked via SSH.  Some release benchmarks were taken via "ScreenShare" though.

Job categories:

- Populate: how long a clean build / test takes to fully populate an empty cache server.
- Isolated: how long it takes to do a clean build / test without any cache server uploading.
- Cached: how long it takes to do a clean build / test reading from the already populated cache.

## `clang-bazel-experimental-release` on `nginx` server

```console
bazel test --test_timeout=300,1500,4500,-1 --keep_going --config=clang --compilation_mode=opt //...
```


| Job      | Time (minutes) | Time (seconds) |
|:--------:|:--------------:|:--------------:|
| Populate | 52.1198        | 3127.19        |
| Isolated | 50.6997        | 3041.98        |
| Cached   | 4.9054         | 294.3267       |

* Cache Size: **11.85935831 GB**
* Speedup (cached / isolated): **9.67549644%**

## `clang-bazel-experimental-release` on `bazel-remote` server

```console
bazel test --test_timeout=300,1500,4500,-1 --keep_going --config=clang --compilation_mode=opt //...
```


| Job      | Time (minutes) | Time (seconds) |
|:--------:|:--------------:|:--------------:|
| Populate | 47.4333        | 2846.0         |
| Isolated | 50.6997        | 3041.98        |
| Cached   | 3.2917         | 197.5          |

* Cache Size: **3.45825966 GB**
* Speedup (cached / isolated): **6.49248187%**

## `clang-bazel-experimental-everything-release` on `bazel-remote` server

```console
bazel test --test_timeout=300,1500,4500,-1 --keep_going --config=clang --compilation_mode=opt --config=everything //...
```


| Job      | Time (minutes) | Time (seconds) |
|:--------:|:--------------:|:--------------:|
| Populate | 61.7856        | 3707.135       |
| Isolated | 59.3333        | 3560.0         |
| Cached   | 18.7762        | 1126.5725      |

* Cache Size: **3.46907305 GB**
* Speedup (cached / isolated): **31.64529494%**

## `clang-bazel-experimental-debug` on `bazel-remote` server

```console
bazel test --test_timeout=300,1500,4500,-1 --keep_going --config=clang --compilation_mode=dbg //...
```


| Job      | Time (minutes) | Time (seconds) |
|:--------:|:--------------:|:--------------:|
| Populate | 139.2093       | 8352.56        |
| Isolated | 124.3148       | 7458.89        |
| Cached   | 24.095         | 1445.7         |

* Cache Size: **17.9241088 GB**
* Speedup (cached / isolated): **19.38224052%**

## `clang-bazel-experimental-everything-debug` on `nginx` server

```console
bazel test --test_timeout=300,1500,4500,-1 --keep_going --config=clang --compilation_mode=dbg --config=everything //...
```


| Job      | Time (minutes) | Time (seconds) |
|:--------:|:--------------:|:--------------:|
| Populate | 160.281        | 9616.86        |
| Isolated | 143.2622       | 8595.73        |
| Cached   | 36.5528        | 2193.17        |

* Cache Size: **144.31127262 GB**
* Speedup (cached / isolated): **25.51464506%**

## `clang-bazel-experimental-everything-debug` on `bazel-remote` server

```console
bazel test --test_timeout=300,1500,4500,-1 --keep_going --config=clang --compilation_mode=dbg --config=everything //...
```


| Job      | Time (minutes) | Time (seconds) |
|:--------:|:--------------:|:--------------:|
| Populate | 145.9667       | 8758.0         |
| Isolated | 143.2622       | 8595.73        |
| Cached   | 45.4636        | 2727.8167      |

* Cache Size: **18.01683944 GB**
* Speedup (cached / isolated): **31.73455503%**

-----------------------

- The cache sizes of the `bazel-remote` server vs the `nginx` server are substantially different.  145GB debug everything on `nginx` vs 18GB.
    - It is very unclear what is _actually_ getting cached and why or why not.  And concerning in a "too good to be true" sense?
- The salting for `nginx` works exactly as we expect, storage more or less doubles.
- The salting for `bazel-remote` does not appear to be working at all.  They only salt the ActionCache entries, not the ContentAddressedStorage.
- There are a number of really nice features of `bazel-remote` we would love to have: status queries, performance metrics if we want them, automatic storage cleanup when we hit capacity (least recently used eviction policy).  We just aren't sure about the job salting and if we can get away with only salting the action cache or if content addressed storage needs it too.

Some additional data (less organized, need to get to our meeting sorry!) on storage concerns with smaller samples follows.

## bazel-remote (with `--enable_ac_key_instance_mangling`)

```console
$ bazel test --test_timeout=300,1500,4500,-1 --keep_going --config=clang --compilation_mode=opt //common/symbolic/expression/...
```

Note: server starts initially using 3162112 bytes ~ 3.162112 MB to start with.

### Sizes

- Bytes after first run: 14241298 bytes ~ **14.241298 MB**
    - Used root url: http://10.221.188.4:9090
- Bytes after second run: 14344524 bytes ~ **14.344524 MB**
    - Used root url: http://10.221.188.4:9090/saltysalt
- Bytes after third run: 14447929 bytes ~ **14.447929**
    - Used root url: http://10.221.188.4:9090/verysalty

After resetting, just using root url http://10.221.188.4:9090

- Bytes after first run: 14241579 bytes ~ **14.241579 MB**
    - Used no `--action_env=cache_salt=...`
- Bytes after second run: 15069553 bytes ~ **15.069553 MB**
    - Used `--action_env='cache_salt=salttown'`
- Bytes after third run: 15433938 bytes ~ **15.433938 MB**
    - Used `--action_env='cache_salt=town-of-salt'`

### Files

File counting (via `curl http://10.221.188.4:9090/status`):

- First run: **1050 files**
    - Used root url: http://10.221.188.4:9090
- Second run: **1078 files**
    - Used root url: http://10.221.188.4:9090
    - Added 28 files.  Expected: no files to be added?
- Third run: **1347 files**
    - Used root url: http://10.221.188.4:9090/3e388d9a39ba701622c41092adc21b0c44394a25f09999c51c54b9dbf243fb5a
    - Added 269 files.  Expected: 1050?
- Fourth run: **1615 files**
    - Used root url: http://10.221.188.4:9090/eb2bf8f6e2cbf8d7a59e27c1bd3e650dabca054faffaf08c7787e51fdfde26fd
    - Added 268 files.  Expected: 1050?

Sanity check, with the server launched **without** adding `--enable_ac_key_instance_mangling`:

- First run: **1050 files**
    - Used root url: http://10.221.188.4:9090
- Second run: **1074 files**
    - Used root url: http://10.221.188.4:9090
    - Added 24 files.  Expected: no files to be added?
- Third run: **1098 files**
    - Used root url: http://10.221.188.4:9090/3e388d9a39ba701622c41092adc21b0c44394a25f09999c51c54b9dbf243fb5a
    - Added 24 files.  Seems to be expected?
- Fourth run: **1118 files**
    - Used root url: http://10.221.188.4:9090/eb2bf8f6e2cbf8d7a59e27c1bd3e650dabca054faffaf08c7787e51fdfde26fd
    - Added 20 files.  Seems to be expected?

## nginx

### Sizes

- macOS `du` size: 85166 ~ **41.5849609375 MB**
    - Used root url: http://10.221.188.13:6060
- macOS `du` size: 170332 ~ **83.169921875 MB**
    - Used root url: http://10.221.188.13:6060/alpha
- macOS `du` size:
    - Used root url: http://10.221.188.13:6060/beta

After resetting, just using root url http://10.221.188.13:6060

- macOS `du` size after first run: 85166 ~ **41.5849609375 MB**
    - Used no `--action_env=cache_salt=...`
- macOS `du` size after second run: 87483 ~ **42.71630859375 MB**
    - Used `--action_env='cache_salt=salttown'`
- macOS `du` size after third run: 89786 ~ **43.8408203125 MB**
    - Used `--action_env='cache_salt=town-of-salt'`

### File Counts

File analysis (`find /Volumes/orka/cache -type f | wc -l`):

- First run: **1050 files**
    - Used root url: http://10.221.188.13:6060
- Second run: **1072 files**
    - Used root url: http://10.221.188.13:6060
    - Added 22 files.  Seems expected given other results above.
- Third run: **2122 files**
    - Used root url: http://10.221.188.13:6060/supersalty
    - Added 1050 files.  Expected behavior!
- Fourth run: **3172 files**
    - Used root url: http://10.221.188.13:6060/ytlasrepus
    - Added 1050 files.  Expected behavior!

**Comment by jwnimmer-tri** [comment]
I've skimmed all of the numbers, but not in a ton of detail.

To me it seems like the summary is that `nginx` and `bazel-remote` are similar in terms of timing (number of seconds for various builds to do their thing).  Maybe 10-30% here or there, but nothing like a 2x factor.

Since nginx is acceptably fast, and seems lower risk (it's what we were doing before, and is a conceptually simpler architecture), it seems like a no-brainer to settle on nginx as the choice?  Is that basically what you're asking?

**Comment by svenevs** [comment]
> To me it seems like the summary is that nginx and bazel-remote are similar in terms of timing (number of seconds for various builds to do their thing). Maybe 10-30% here or there, but nothing like a 2x factor.

Correct, they both seem more or less equivalent.  However, where `bazel-remote` really sticks out is the significant reduction in disk space used.  If it is working correctly and as we need it to, if we use `bazel-remote` we could start caching the debug builds for mac as well.

The concern being that if the ActionCache being salted is not enough (the content should also be getting salted), that's not possible.  I took a quick look, in theory it could be added, but I kind of feel like the authors there chose not to for a reason?  In `nginx` land storage doubles, in `bazel-remote` it basically doesn't change with different salts, it is unclear if that is OK or if we'd run into trouble.

> is a conceptually simpler architecture

If anything it's the opposite (with `nginx` we have to implement storage cleanup / cache eviction), but not significantly so.  `bazel-remote` stuck out because it cleans itself and has status checks (could be automated for buildcops), but the main one is cached debug builds.  That said, we currently don't have those so we aren't losing anything by staying with `nginx`, just potentially missing an opportunity to (somewhat dramatically) speedup debug CI.

**Comment by svenevs** [comment]
Sorry, final clarification: we're really concerned over the salting as a "why `bazel-remote`" may not be good enough.  If we're over-caching things, bugs introduced now may not even get flagged in CI until weeks or months (whenever the cache gets evicted).  That sounds horrifying to me...

**Comment by jwnimmer-tri** [comment]
Could you explain why caching debug builds with nginx (and its larger storage size) would be a problem?  Is is that we have too many Debug variations, and there is some upper-bound on disk space on the cache server storage?  Maybe we should drop support for Everything-Debug on macOS.

Anyway, I think the choice is clear -- nginx is safe and we should do it.

**Comment by svenevs** [comment]
Infrastructure docs (closing this issue) are here: https://github.com/RobotLocomotion/drake-ci/pull/198.

**Comment by BetsyMcPhail** [comment]
The buildcop documentation should probably be updated to mention the cache warning emails? Also, the do buildcops need to check an ARM job to make sure the cache is up-and-running?

**Comment by jwnimmer-tri** [comment]
From f2f -- action for @svenevs here is to write up a list of remaining work (docs, landing the CI PR, etc.).  It's fine if you prefer to open a new issue with those items instead.

**Comment by svenevs** [comment]
Finishing the work in #19146, macos side is more or less complete minus some small cleanup that may happen in the unification.
