### ISSUE TITLE
Release process => Monterey

### ISSUE THREAD

**Issue by jwnimmer-tri** [RobotLocomotion/drake#18294]
"Big Sur" is dead to us.  The release process document should refer to Monterey.

**Comment by jwnimmer-tri** [comment]
From f2f: somewhere on the website, we should have note "The last version of Drake that supported Big Sur was v1.9.0", with a link to that releases page https://github.com/RobotLocomotion/drake/releases/tag/v1.9.0.

**Comment by BetsyMcPhail** [comment]
The Mac CI jobs are being updated as part of #17869
