### ISSUE TITLE
plant.set_velocities(...) not affecting plant?

### ISSUE THREAD

**Issue by andreaswestre** [RobotLocomotion/drake#18306]
### What happened?

I am trying to set the initial angular rotation for my robot plant. The model consists of a RigidBody with four legs attached. Gravity is disabled, such that there should be no forces acting on the plant.

```
unique_ptr<Context<double>> root_context = diagram->CreateDefaultContext();
  Context<double>& plant_context = plant.GetMyMutableContextFromRoot(root_context.get());  

  
  Eigen::VectorXd velocity = Eigen::VectorXd::Zero(plant.num_velocities());
  velocity[4] = 10;
  velocity[1] = 10;

  plant.SetVelocities(&plant_context, velocity);

  /*plant.SetFreeBodySpatialVelocity(&plant_context, 
  plant.GetBodyByName("main_body",body_indices[0]),
  SpatialVelocity<double>{ Vector3d(5.0, 5.0, 0.0), Vector3d(10.0, 10.0, 0.0)});*/
```

I tried using both plant.SetVelocities(...) and plant.SetFreeBodySpatialVelocity(...), but the body does not move in either cases. I have tried putting every state to 10, and not attaching the legs to the robot.

### What operating system are you using?

macOS 12 (Monterey)

### What installation option are you using?

compiled from source code using CMake

**Comment by jwnimmer-tri** [comment]
I see that https://stackoverflow.com/questions/74408904/plant-set-velocities-not-affecting-plant already has the same question.  For clarity, we shouldn't split the discussion across two places at once, so let's use the StackOverflow Q&A instead of the bug tracker.
