### ISSUE TITLE
There is a bug

### ISSUE THREAD

**Issue by Peacetimes** [RobotLocomotion/drake#18325]
'pydrake.multibody.parsing.Parser' object has no attribute 'AddModels'

**Comment by jwnimmer-tri** [comment]
It works fine for me (see below evidence).

The function was only recently added, and is not yet part of a stable release; it (so far) only exists in the nightly releases.  Perhaps you are using a too-old version of Drake.

```console
jwnimmer@call-cps:~/tmp$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.5 LTS
Release:	20.04
Codename:	focal

jwnimmer@call-cps:~/tmp$ python3 -m venv env
jwnimmer@call-cps:~/tmp$ env/bin/pip install --upgrade pip
...
Successfully installed pip-22.3.1

jwnimmer@call-cps:~/tmp$ env/bin/pip install https://drake-packages.csail.mit.edu/drake/nightly/drake-latest-cp38-cp38-manylinux_2_31_x86_64.whl
Collecting drake==latest
...
Installing collected packages: drake
  Attempting uninstall: drake
    Found existing installation: drake 1.9.0
    Uninstalling drake-1.9.0:
      Successfully uninstalled drake-1.9.0
Successfully installed drake-0.0.20221115

jwnimmer@call-cps:~/tmp$ env/bin/python3 -c 'import pydrake.multibody.parsing; \
help(pydrake.multibody.parsing.Parser.AddModels); \
pydrake.multibody.parsing.Parser().AddModels()'

Help on instancemethod in module pydrake.multibody.parsing:

AddModels(...)
    AddModels(self: pydrake.multibody.parsing.Parser, file_name: str) -> List[drake::TypeSafeIndex<drake::multibody::ModelInstanceTag>]
    
    Parses the input file named in ``file_name`` and adds all of its
    model(s) to ``plant``.
    
    Parameter ``file_name``:
        The name of the file to be parsed. The file type will be inferred
        from the extension.
    
    Returns:
        The set of model instance indices for the newly added models,
        including nested models.
    
    Raises:
        RuntimeError in case of errors.

Traceback (most recent call last):
  File "<string>", line 1, in <module>
TypeError: __init__(): incompatible constructor arguments. The following argument types are supported:
    1. pydrake.multibody.parsing.Parser(plant: drake::multibody::MultibodyPlant<double>, scene_graph: drake::geometry::SceneGraph<double> = None)
```

**Comment by Peacetimes** [comment]
Thank you very much for your answer.
The problem has been solved!




……和平年代
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "RobotLocomotion/drake"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月15日(星期二) 晚上10:42
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [RobotLocomotion/drake] There is a bug (Issue #18325)





 
It works fine for me (see below evidence).
 
The function was only recently added, and is not yet part of a stable release; it (so far) only exists in the nightly releases.  Perhaps you are using a too-old version of Drake.
 ***@***.***:~/tmp$ lsb_release -a No LSB modules are available. Distributor ID:	Ubuntu Description:	Ubuntu 20.04.5 LTS Release:	20.04 Codename:	focal ***@***.***:~/tmp$ python3 -m venv env ***@***.***:~/tmp$ env/bin/pip install --upgrade pip ... Successfully installed pip-22.3.1 ***@***.***:~/tmp$ env/bin/pip install https://drake-packages.csail.mit.edu/drake/nightly/drake-latest-cp38-cp38-manylinux_2_31_x86_64.whl Collecting drake==latest ... Installing collected packages: drake   Attempting uninstall: drake     Found existing installation: drake 1.9.0     Uninstalling drake-1.9.0:       Successfully uninstalled drake-1.9.0 Successfully installed drake-0.0.20221115 ***@***.***:~/tmp$ env/bin/python3 -c 'import pydrake.multibody.parsing; \ help(pydrake.multibody.parsing.Parser.AddModels); \ pydrake.multibody.parsing.Parser().AddModels()' Help on instancemethod in module pydrake.multibody.parsing: AddModels(...)     AddModels(self: pydrake.multibody.parsing.Parser, file_name: str) -&gt; List[drake::TypeSafeIndex<drake::multibody::ModelInstanceTag&gt;]          Parses the input file named in ``file_name`` and adds all of its     model(s) to ``plant``.          Parameter ``file_name``:         The name of the file to be parsed. The file type will be inferred         from the extension.          Returns:         The set of model instance indices for the newly added models,         including nested models.          Raises:         RuntimeError in case of errors. Traceback (most recent call last):   File "<string&gt;", line 1, in <module&gt; TypeError: __init__(): incompatible constructor arguments. The following argument types are supported:     1. pydrake.multibody.parsing.Parser(plant: drake::multibody::MultibodyPlant<double&gt;, scene_graph: drake::geometry::SceneGraph<double&gt; = None)
