### ISSUE TITLE
MeshcatPointCloudVisualizer in meldis

### ISSUE THREAD

**Issue by jwnimmer-tri** [RobotLocomotion/drake#18333]
For backwards compatibility with [show_point_cloud](https://github.com/RobotLocomotion/drake/blob/v1.10.0/tools/workspace/drake_visualizer/_drake_visualizer_builtin_scripts/show_point_cloud.py) from `drake_visualizer`, we should have meldis listen for point-cloud LCM messages and display them.

We already have a class `MeshcatPointCloudVisualizer` to publish point clouds into `Meshcat`.  We just need to wire it up.

**Comment by jwnimmer-tri** [comment]
\CC @siyuanfeng-tri @EricCousineau-TRI FYI

**Comment by zachfang** [comment]
I will start looking into this as the next Drake Adoption task.

**Comment by zachfang** [comment]
From reading through different components, this is my understanding of how to resolve this issue.

We already have `MeshcatPointCloudVisualizer` for the regular Meshcat visualization and the LeafSystem `PointCloudToLcm` to convert Pointcloud to LCM messages when using Meldis.

> meldis listen for point-cloud LCM messages and display them.  

The only code change needed is in [`_meldis.py`](https://github.com/RobotLocomotion/drake/blob/master/bindings/pydrake/visualization/_meldis.py#L401-L412) to subscribe to the type of LCM message and the handler function for displaying, plus unit testing.

**Comment by jwnimmer-tri** [comment]
Yes, in short the only new function we need is to convert a `lcmt_point_cloud` message into a pydrake `PointCloud` object.

Then to visualize that point cloud object in `Meshcat`, we can either use a `MeshcatPointCloudVisualizer`  or possibly just call into `Meshcat->SetObject(path, cloud)` directly.
