### ISSUE TITLE
Auto-reload in ModelVisualizer

### ISSUE THREAD

**Issue by jwnimmer-tri** [RobotLocomotion/drake#18334]
I common use case for ModelVisualizer is creating a new model from scratch.

When doing that, the user will typically
- edit their model file(s) in their IDE, then
- re-launch the ModelVisualizer to see the effect, then
- close the visualizer, then repeat.

It would help speed up their workflow if they didn't need to re-launch the visualizer every time.  Ideally, it would monitor the input file(s) for changes, and if there was a change either (1) automatically reload the model, or (2) provide a "reload" button for the user to click at their leisure.  If we do (2), maybe the button could always be there (i.e., without trying to detect changes).

**Comment by SeanCurtis-TRI** [comment]
With the presence of the button, it would be *nice* if the visualizer reported that there *was* a change or not. Updating files in the wrong directory is a common enough mistake, it would be nice to help users realize that they don't see any changes because the visualizer says there *aren't* any changes.

**Comment by trowell-tri** [comment]
That's a good idea. We should have some kind of error reporting anyway, for malformed model files (maybe it already does this, I haven't tried) so this is just an extension of that.

**Comment by jwnimmer-tri** [comment]
At the moment, there is no way to ask the Parser "which files did you load?".  (Recall that files can include other files or meshes, so monitoring only the one filename we pass to the parser is _not_ sufficient on its own.)  We'd need to add that feature before ModelVisualizer could report whether or not anything changed.

**Comment by trowell-tri** [comment]
I've added an optional (for now, via a command-line switch) reload button so we can try this out and discuss future directions.

**Comment by jwnimmer-tri** [comment]
We discussed this a bit today.

My decision is that for now, we'll de-scope "auto" as the feature.  I think the "Reload" button is very useful on its own, and should suit this use case OK.

Trying to instrument "auto" would mean that the Parser needs to reach down into the SceneGraph to understand which exact mesh / material / texture files it loaded.  That level of implementation cost doesn't seem worth the benefit of the "auto" feature.
