### ISSUE TITLE
//systems/lcm:lcm_interface_system_test may have false positives

### ISSUE THREAD

**Issue by liangfok** [RobotLocomotion/drake#18346]
### What happened?

This test failed in the following nightly-production build:

https://drake-cdash.csail.mit.edu/test/898569555

It involves the following code: https://github.com/RobotLocomotion/drake/blob/4c4b9f7c829f21822c57267f01916851bc7d15c9/systems/lcm/test/lcm_interface_system_test.cc#L108-L123

It appears there is a race condition between the transmit thread publishing and the time `simulator.reset()` and `HandleSubscriptions(0)` are executed, meaning it is possible for subsequent calls to `drake_lcm->HandleSubscriptions(1)` to still return a non-zero value.

### Relevant log output

```shell
[ RUN      ] test/LcmInterfaceSystemTest.AcceptanceTest/3
systems/lcm/test/lcm_interface_system_test.cc:123: Failure
Expected equality of these values:
  total
    Which is: 1
  0
[  FAILED  ] test/LcmInterfaceSystemTest.AcceptanceTest/3, where GetParam() = 3 (448 ms)
```

**Comment by jwnimmer-tri** [comment]
Closing per "The first time an unexplained failure occurs, close the issue immediately..."
-- https://drake.mit.edu/buildcop.html#process

**Comment by ggould-tri** [comment]
https://drake-jenkins.csail.mit.edu/view/Production/job/mac-arm-monterey-clang-bazel-nightly-everything-release/79/
Reopening per procedure; this is a twice in three months bug so lowest priority.  Assigning @sammy-tri (LCM owner) for delegation and triage.

**Comment by jwnimmer-tri** [comment]
We should just `flaky = True` in the BUILD file.
