### ISSUE TITLE
Saving Meshcat static html results in a file that does not open

### ISSUE THREAD

**Issue by mpetersen94** [RobotLocomotion/drake#18342]
### What happened?

I generated a simulation and tried to save the resulting meshcat visualization as an html. When I try to open that file, nothing pops up and I repeatedly get the error `Uncaught (in promise) TypeError: viewer.handle_command_bytearray is not a function`. I got the same result when I tried to open the html file generated by `//geometry:meshcat_manual_test`.

cc @cohnt @RussTedrake 

### Version

55409b1e2130e895f2930baec246c8c04bdc723e

### What operating system are you using?

Ubuntu 20.04

### What installation option are you using?

compiled from source code using Bazel

### Relevant log output

```shell
Uncaught TypeError: this.connection is undefined
    handle_gamepads file:///[path]/meshcat_static.html:71
    animate file:///[path]/meshcat_static.html:85

Uncaught (in promise) TypeError: viewer.handle_command_bytearray is not a function
    <anonymous> file:///[path]/meshcat_static.html:113
```

**Comment by RussTedrake** [comment]
The fix is in https://github.com/rdeits/meshcat/pull/134 .  I'll follow up with the drake PR to upgrade meshcat as soon as that lands.
