### ISSUE TITLE
PBH test for stabilizability assumes abs(eigen) < 1

### ISSUE THREAD

**Issue by Silur** [RobotLocomotion/drake#18359]
Correct me if I'm wrong but to best of my knowledge in control theory, the PBH test for stabilizability only assumes all eigenvalues (that satisfy `rank(lambda@I - A | B) = n`) to be greater than 0, nothing on being less than 1.

https://github.com/RobotLocomotion/drake/blob/a2390791c201a87925e3214299dcbf0c349ca808/math/discrete_algebraic_riccati_equation.cc#L26

**Comment by hongkai-dai** [comment]
For continuous time system, the stability test is that all eigen values have negative real values. For discrete time system, the test is all eigen value with length less than 1. Here we solve the discrete time Riccati equation for a discrete time system, hence we check the length <= 1.
