### ISSUE TITLE
Upgrade to Gurobi 10

### ISSUE THREAD

**Issue by hongkai-dai** [RobotLocomotion/drake#18352]
Gurobi 10 is released https://www.gurobi.com/whats-new-gurobi-10-0/

I will contact the gurobi vendor to check if we need to upgrade our licenses.

**Comment by jwnimmer-tri** [comment]
@hongkai-dai do you have any timeline / goal for this upgrade?

**Comment by hongkai-dai** [comment]
I will do it next week.

**Comment by RussTedrake** [comment]
I guess we never finished this upgrade?

**Comment by hongkai-dai** [comment]
Oops, sorry for the delay. I will work with Gurobi and TRI's IE team to upgrade our license server.

**Comment by jwnimmer-tri** [comment]
Actually there are two things possibly required -- update the CI provisioning to install Gurobi 10, and then (if necessary) also upgrade the license.

**Comment by hongkai-dai** [comment]
BTW, Gurobi just received our payments and updated our license to the newest version. We will need to run `grbgetkey` to obtain the new license.

Does the Drake CI uses TRI's gurobi license?

**Comment by RussTedrake** [comment]
> Does the Drake CI uses TRI's gurobi license?

No.

**Comment by BetsyMcPhail** [comment]
Using the prior upgrade issue (#16604) as reference, there are several steps that need to be coordinated to upgrade Gurobi:


- [ ]  Update required version in Drake itself
- [ ]  Update [Gurobi cask]
- [ ]  Update Drake CI scripts
- [ ] Check if current license will support 10.0 and upgrade if needed
- [ ]  Update license server. We may have a new license and a new software version, these can both be updated at the same time.
- [ ]  Update CI provisioned Mac and Linux images

**Comment by svenevs** [comment]
@BetsyMcPhail lets coordinate offline, rather than needing a flag day transition in CI, we might want to stage it so that we can install two versions of gurobi.

https://github.com/RobotLocomotion/homebrew-director/tree/master/Casks

we can do versioning.  Lets talk offline when you are back about what will be the easiest long term solution.

**Comment by BetsyMcPhail** [comment]
The CI License server has been updated (https://support.gurobi.com/hc/en-us/articles/360040451771-How-do-I-update-my-token-server-to-a-newer-version-).

Note that Gurobi licenses should be backwards compatible (https://support.gurobi.com/hc/en-us/articles/360013417471-How-do-I-request-a-license-for-an-older-version-of-Gurobi-#:~:text=Gurobi%20licenses%20are%20backwards%20compatible,C%3A%5Cgurobi%5C%20on%20Windows), so this step can be completed first, before any changes to drake / drake-ci / etc.

**Comment by BetsyMcPhail** [comment]
Experimental job with both drake and drake-ci PRs: https://drake-jenkins.csail.mit.edu/view/Everything/job/linux-focal-unprovisioned-clang-bazel-experimental-everything-release/33

**Comment by BetsyMcPhail** [comment]
Linux provisioned images are ready: **drake-linux-focal-2023-08-08** and **drake-linux-jammy-2023-08-08**
