### ISSUE TITLE
macOS arm jenkins jobs incomplete

### ISSUE THREAD

**Issue by svenevs** [RobotLocomotion/drake#18363]
We seem to be missing some macOS arm build flavors.

https://drake-jenkins.csail.mit.edu/view/Mac%20ARM/job/mac-arm-monterey-unprovisioned-clang-bazel-experimental-release/

There is no corresponding `debug` unprovisioned experimental build.  Probably a few more.  Flagging now before I forget.  CC @BetsyMcPhail

**Comment by BetsyMcPhail** [comment]
There has historically never been any Mac unprovisioned debug builds. On VSphere, we would have to increase the unprovisioned image size. See #17869 for a discussion of the current matrix of Mac builds (specifically [here](https://github.com/RobotLocomotion/drake/issues/17869#issuecomment-1304591223))

**Comment by svenevs** [comment]
I see, lets keep this one on hold then until after the orka updates.  I don't see why the vsphere limitations should prevent us from enabling unprovisioned debug experimental builds for arm64.  They currently have minute value to me, but I don't need CI for what I'm testing.

**Comment by svenevs** [comment]
Closing as stale / irrelevant now.
