### ISSUE TITLE
[setup] Ubuntu Jammy may have libgcc-12-dev, which breaks mkdoc if libstdc++-12-dev is not present

### ISSUE THREAD

**Issue by EricCousineau-TRI** [RobotLocomotion/drake#18370]
### What happened?

Relates https://github.com/RobotLocomotion/drake/issues/15652#issuecomment-904774598

See more details in https://drakedevelopers.slack.com/archives/C0KDGF4V9/p1669663654774429
\cc @calderpg-tri @ggould-tri @jwnimmer-tri @rpoyner-tri 

As Grant indicated, can repro as follows:
``
bazel build @drake//bindings/pydrake:documentation_pybind.h
``

If you have `libgcc-12-dev` installed, but *not* `libstdc++-12-dev`, then it will fail with something like:
```
bazel-out/k8-opt/bin/external/drake/bindings/pydrake/documentation_pybind.h.tmp_artifacts/mkdoc_glue.h:1:10: fatal error: 'optional' file not found
Ubuntu clang version 12.0.1-19ubuntu3'
...
RuntimeError: The operating system's C++ standard library is not installed correctly.
```

If you run off of bare Ubuntu install (e.g. `ubuntu:22.04` in Docker / Apptainer), then it's fine.
If you install `libgcc-12-dev`, then it breaks.
If you then install `libstdc++-12-dev`, then it's fine.

Also note that we configure `.bazelrc` as follows for Jammy on Anzu:
```sh
# Use GCC 11 to match Jammy's default.
build --action_env=CC=/usr/bin/gcc-11
build --action_env=CXX=/usr/bin/g++-11
```

### Version

2b49d9bf3a971620ec00673949d91339f8162c2c

### What operating system are you using?

Ubuntu 22.04

### What installation option are you using?

compiled from source code using Bazel

**Comment by EricCousineau-TRI** [comment]
Narrowed repro from missing `g++-12` to `libstdc++-12-dev`

**Comment by jwnimmer-tri** [comment]
The solution path here will be to improve the error message from #15652 even more, perhaps by listing out some package names more specifically.  In general, our `install_prereqs` can't fix this automatically -- because we don't know what the user already has installed (and there's no way to change how `libclang` searches for GCC's libraries).

**Comment by jwnimmer-tri** [comment]
Here's the tl;dr for how to fix this:

On Jammy if you install `libgcc-12-dev`, then in order to compile Drake you **must** also install `libstdc++-12-dev` (or uninstall `libgcc-12-dev`).
