### ISSUE TITLE
16-bit RGBA textures silently break rendering

### ISSUE THREAD

**Issue by SeanCurtis-TRI** [RobotLocomotion/drake#18393]
### What happened?

A user attempted to load a [model of a screwdriver](https://drive.google.com/file/d/12sfIAnnrqckGaVDc6VGZTi61EDlecdUk/view?usp=share_link) with the perception role. Although the model showed up, and was clearly affected by the texture, the end result was incorrect. In place of a black handle with green accents, they got this:

![image](https://user-images.githubusercontent.com/22159799/205305169-6556c23a-f197-4473-bc44-9fa2ee78c344.png)

The problem proved to be that the png was encoded with 16-bit channels. The png loader interpreted it as an 8-bit image which led to the seemingly arbitrary result.

There are three things that *could* be done (in order of increasing complexity):

1. Update the documentation to warn about the bit-depth of the images.
2. Detect the bit-depth of the image and throw with an appropriate runtime message.
3. Do the "right" thing for 16-bit images. There are two potential "right" things:
    - automatically reduce it to 8-bits (which should probably be accompanied with some message about precision loss)
    - just use a 16-bit image.

### Version

v1.10.1

**Comment by zachfang** [comment]
Looking into the issue and will put that into my backlog. In general, what's the priority or timeline for a user-reported bug?

**Comment by SeanCurtis-TRI** [comment]
I have the following thoughts:

1. If we're unsure on how to give targeted errors (or making it work) or even unsure on what the timing is, then we should bias ourselves towards documenting it quickly.
2. As for detecting/making it work, I'd ping kitware/vtk forums. Ultimately, the solution will live there as we're using VTK to parse the png.

**Comment by zachfang** [comment]
Working. I started a feature branch last night toward updating documentation and throwing exceptions. I should have that ready later today, if not tomorrow.

After that, I will ping Kitware or the VTK forums for a longer-term solution/discussion.

**Comment by zachfang** [comment]
Update- In #18410, we combined options 1 and 3 to cast non-uchar-channel pngs to uchar channels with a warning (and proper documentation). This issue is considered resolved for now.
