### ISSUE TITLE
Linux Python 3.11 support

### ISSUE THREAD

**Issue by svenevs** [RobotLocomotion/drake#18417]
Putting this on the board, ETA unknown, relates to the release cycle and current plans.

Redirect from https://github.com/RobotLocomotion/drake/pull/18262#issuecomment-1340187394, relates: #18415

We may want to extract some of the patches from #18262 independently depending on the timeline.

CC @jwnimmer-tri @BetsyMcPhail

**Comment by jwnimmer-tri** [comment]
Per f2f: time permitting, we should add a manylinux 3.11 wheel to the nightlies (akin to how manylinux 3.10 works), and then as of the next stable release add official support (uploading to pypi).
