### ISSUE TITLE
RenderRpc: Add the libcurl external to wheel builds

### ISSUE THREAD

**Issue by zachfang** [RobotLocomotion/drake#18423]
- [x] Add `libcurl` to the wheel builds (Done by #17755)
- [ ] Revert #17697

**Comment by zachfang** [comment]
@EricCousineau-TRI This is the issue aggregating all the relevant information I am aware of. Thanks for helping look into this.

**Comment by jwnimmer-tri** [comment]
The "Add libcurl to the wheel builds" part was already done in #17755.  The only remaining work is to change the visibility back to public and refresh `build_components.bzl`.

**Comment by zachfang** [comment]
Ah, got it. I will give it a try today. Thanks, Jeremy.
