### ISSUE TITLE
Upgrade tinyobjloader to latest commit 

### ISSUE THREAD

**Issue by BetsyMcPhail** [RobotLocomotion/drake#18437]
Follow up to #18379.

After updating tinyobjloader to the latest commit, `//geometry/render_gl:internal_shape_meshes_test` fails.

Example of failing test: https://drake-cdash.csail.mit.edu/test/912804436

See PR #18436 for all of the failing pre-merge jobs.

**Comment by mwoehlke-kitware** [comment]
This appears to have been fixed by #18479.
