### ISSUE TITLE
Upgrade to Bazel 6.0

### ISSUE THREAD

**Issue by jwnimmer-tri** [RobotLocomotion/drake#18508]
We should upgrade our supported Bazel version to https://github.com/bazelbuild/bazel/releases/tag/6.0.0.

In #18246, I tested a couple of early release candidates and fixed some compatibility problems, so hopefully this is as simple as switching the `setup` scripts (`.bazeliskrc` and `setup/ubuntu/source_distribution`) plus the documentation.

**Comment by BetsyMcPhail** [comment]
For reference, #16447 upgraded to 5.0

**Comment by jwnimmer-tri** [comment]
FYI one new thing compared to the 5.0 upgrade process --

On macOS today, our bazel version comes from a _dotfile_, which means that CI testing of the PR can use the **Provisioned** images (without any CI maintainer involvement).

The Ubuntu is unchanged -- it comes from a `setup` script, which means that CI testing of the PR needs to use the **Unprovisioned** job names.

**Comment by rpoyner-tri** [comment]
Predictably, kcov integration needs love. https://github.com/RobotLocomotion/drake/issues/18615

**Comment by BetsyMcPhail** [comment]
Linux provisioned images have been updated in CI.
