### ISSUE TITLE
Upgrade Externals January 2023

### ISSUE THREAD

**Issue by BetsyMcPhail** [RobotLocomotion/drake#18510]
Follow [Semi-automated monthly upgrades](https://github.com/RobotLocomotion/drake/blob/master/tools/workspace/README.md#semi-automated-monthly-upgrades) documentation.

Issues remaining from previous months:

- #17910 
- #18435
- #18437

New issues:
- #18520
  - #18534
- #18524

Prior issue: #18379

**Comment by jwnimmer-tri** [comment]
> As part of this work, could I ask you to also PR a related documentation change? ...

For the record, this was completed in #18517.

**Comment by jwnimmer-tri** [comment]
To my reading, all of the January upgrades have either been merged already, or filed as distinct issues.  Closing.
