### ISSUE TITLE
DifferentialInverseKinematics deprecations

### ISSUE THREAD

**Issue by jwnimmer-tri** [RobotLocomotion/drake#18512]
In #17977, several DiffIK parameters were deprecated.

The date has come to remove that code now (search for `2023-01-01`).

(Ping to @RussTedrake, or maybe @rpoyner-tri wants to grab it.)

**Comment by sherm1** [comment]
Assigned to Rico for disposition

**Comment by rpoyner-tri** [comment]
I'm curious -- why is this an issue, and not a removal PR?

**Comment by jwnimmer-tri** [comment]
I'm trying to delegate more, rather than do all of Drake's maintenance on my own.

**Comment by rpoyner-tri** [comment]
See #18549
