### ISSUE TITLE
Jammy AMI upgrades (BLAS)

### ISSUE THREAD

**Issue by jwnimmer-tri** [RobotLocomotion/drake#18541]
As of #18540, our Ubuntu 22 Jammy setup dependencies have changed.  Please update the Provisioned Jammy AMIs with the change.  There's no need to change the Focal AMIs.

Note that incrementally re-running the `install_prereqs` script is not enough, since the goal of that PR is to _remove_ packages.  Not only should the openblas packages be removed (`libopenblas-dev libopenblas-pthread-dev libopenblas0 libopenblas0-pthread`), but also `python3-scipy` and any dependencies that it brought in.

It's probable that removing those 5 packages and then `sudo apt autoremove` should do it.  But it's probably worth cross-checking the installed list against an empty machine after `install_prereqs` to see if there's any gotchas.

**Comment by BetsyMcPhail** [comment]
It may be easier to start with the Unprovisioned Jammy AMI and run the setup scripts.

**Comment by jwnimmer-tri** [comment]
Sure, sounds fine to me.  I wasn't sure how much manual inertia there was in the existing images.  If we can repave from scratch, that'll be the most robust.

**Comment by BetsyMcPhail** [comment]
I started with the Jammy unprovisioned image and then ran the [CI setup script](https://github.com/RobotLocomotion/drake-ci/blob/main/setup/ubuntu/install_prereqs) and then the normal [install_prereqs](https://github.com/RobotLocomotion/drake/blob/master/setup/ubuntu/install_prereqs.sh).

Jenkins has been updated and a test run has been started: https://drake-jenkins.csail.mit.edu/view/Linux%20Jammy/job/linux-jammy-gcc-bazel-experimental-release/1732/

**Comment by BetsyMcPhail** [comment]
The AMI is still pending... giving it time and will try again.

**Comment by BetsyMcPhail** [comment]
Let's try this again: https://drake-jenkins.csail.mit.edu/job/linux-jammy-gcc-bazel-experimental-release/1735/

**Comment by BetsyMcPhail** [comment]
Test build passed, closing
