### ISSUE TITLE
Python bindings for DiscreteTimeTrajectory

### ISSUE THREAD

**Issue by jwnimmer-tri** [RobotLocomotion/drake#18568]
We should bind `drake/common/trajectories/discrete_time_trajectory.h` into pydrake, for completeness.

The `common.trajectories` package is an essential part of the toolbox.  We need to ensure that 100% of it is bound.

(Also, it seems to be missing from our current Doxygen output on the C++ side.  I haven't looked at why.)

**Comment by EricCousineau-TRI** [comment]
Self-assign per component ownership + platform checklist

**Comment by jwnimmer-tri** [comment]
New plan -- we're not going to file issues requesting bindings.  When they are needed, someone can PR the binding.
