### ISSUE TITLE
Deploy 1.13.0 tutorials

### ISSUE THREAD

**Issue by ggould-tri** [RobotLocomotion/drake#18579]
Tutorials have not been updated for the 1.12.0 drake release.

The release playbook for updating tutorials seems to be out of date, per https://drakedevelopers.slack.com/archives/C01JSGRR1QS/p1673291854790029 .

Assigning to @jwnimmer-tri per his request on slack.

**Comment by jwnimmer-tri** [comment]
Done now.

Given the recent Deepnote changes, the process was just
(1) Checkout Drake v1.13.0 locally.
(2) Drag and drop the ipynb files into the Notebooks pane.
(3) Manually delete the old ipynb files from the Files pane.
(4) Run the notebooks to make sure they work.
