### ISSUE TITLE
Use of the term "floating" in inconsistent in the `Body` class

### ISSUE THREAD

**Issue by xuchenhan-tri** [RobotLocomotion/drake#18570]
#18390 changed the definition of a "floating body" to "a body that's mobilized by a 6-dof mobilzer AND parent body of the mobilizer is world". However, some documentation in the `Body` class uses the term "floating" inconsistently with this definition. Some uses are just wrong.

For example, the documentation of `Body::has_quaternion_dofs()` claims 
> If `true`, this body is a floating body modeled with a quaternion floating mobilizer. By implication, is_floating() is also `true`.

which is incorrect, when the body's parent is not world.

Other functions whose documentation needs a fix include

- Body::floating_positions_start
- Body::floating_velocities_start
- Body::floating_position_suffix
- Body::floating_velocity_suffix
- Body::Lock
- Body::Unlock

**Comment by sherm1** [comment]
I'll take this Xuchen.
