### ISSUE TITLE
CLion debug session "times out"

### ISSUE THREAD

**Issue by amcastro-tri** [RobotLocomotion/drake#1868]
I decided to give Clion another shot after adding more memory to my workstation. I followed the instructions [here](https://github.com/tkoolen/drake/wiki/CLion-setup-(experimental)) to set it up.

I am able to compile and run from within CLion. However when trying to debug (Shift+F9) the debugging panel opens up but however CLion stays there waiting for gdb. After a while (like about 2 minutes or so) I get a little bubble with the message "command timed out".

A google search on this revealed that apparently this is a know issue for large projects that CLion has been having even for the latest releases.

I tried their [Early Access Program](https://confluence.jetbrains.com/display/CLION/Early+Access+Program) (build # 145.257) version and this ones does start the debugger, but after a long wait of about 3 minutes!

Any word on how to get this running properly for Drake?

**Comment by RussTedrake** [comment]
@tkoolen is our expert.

**Comment by tkoolen** [comment]
Unfortunately I don't have any experience with debugging using gdb in CLion; I use lldb myself (on OSX).

Browsing CLion's issues, I found:
* https://youtrack.jetbrains.com/issue/CPP-4952. This one was resolved; it was due to using tcsh instead of bash; might want to check it out if you're using tcsh.
* https://youtrack.jetbrains.com/issue/CPP-3311. Error message is different, but could be related. Suggests that pointing CLion to a newer version of gdb may solve the problem.
* https://youtrack.jetbrains.com/issue/CPP-5508. Unresolved

**Comment by amcastro-tri** [comment]
Anybody using CLion in Ubuntu with gdb?

**Comment by sherm1** [comment]
> Anybody using CLion in Ubuntu with gdb?

@chrisdembia, are you still using CLion? If so do you have any advice for Alejandro (@amcastro-tri)?

**Comment by chrisdembia** [comment]
I am still using CLion, but on OSX with lldb, like @tkoolen. I'm eager for version 1.5 so that I can choose the location of the build directory. Good luck Alejandro.

**Comment by amcastro-tri** [comment]
I am considering to create ("generate" in cmake's terms) and IDE's project files with cmake option -G. I was considering to test this with Eclipse. Any inputs on that? is anybody else using another IDE?

**Comment by chrisdembia** [comment]
Eclipse works with the UNIX Makefiles generate, I believe. And I've heard that Eclipse with C++ is pretty slow and doesn't handle big projects well. On Ubuntu, CLion is the best option, but you could also try Code::Blocks.

**Comment by tkoolen** [comment]
I was frustrated by the lack of development being done on the Eclipse CDT. It also didn't handle templates well last I tried it.

**Comment by RussTedrake** [comment]
i believe this discussion has runs its course, so will close it.

**Comment by emmjaykay** [comment]
Still an issue with me on 2017.3. Ubuntu 16

**Comment by amcastro-tri** [comment]
I believe @SeanCurtis-TRI debugs under CLion. I actually got used to the workflow of debugging with `gdb` and I use CLion for its awesome navigation features for C++ projects

**Comment by aljohnston112** [comment]
I am getting timeouts. Makes debugging impossible after one evaluation.

CLion 2023.3.1
Build #CL-233.11799.287, built on December 11, 2023
Runtime version: 17.0.9+7-b1087.7 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 32768M
Cores: 12
Registry:
  debugger.attach.dialog.enabled=true
  run.processes.with.pty=TRUE
  ide.experimental.ui=true

**Comment by sherm1** [comment]
You can adjust the timeout: https://www.jetbrains.com/help/clion/configuring-debugger-options.html#gdb-startup
