### ISSUE TITLE
Deprecation removals 2023-02

### ISSUE THREAD

**Issue by jwnimmer-tri** [RobotLocomotion/drake#18688]
The following code is scheduled for deprecation removals on 2023-02-01.

I'm looking for a volunteer to prepare the pull request.  It's probably easiest to do them all at once since they are each pretty small on their own.

From #18179 via @hongkai-dai:
- `drake/common/symbolic/trigonometric_polynomial.h`
- `drake/bindings/pydrake/symbolic_py.cc`
- `drake/bindings/pydrake/test/symbolic_test.py`

From #18094 via @sherm1:
- `drake/systems/framework/system.h`

From #18122 via @amcastro:
- `drake/bindings/pydrake/multibody/tree_py.cc`

(Other code due 2023-02 has already been filed at #18686 and #18689.)

**Comment by rpoyner-tri** [comment]
I'll take a look and continue the dep-removal theme of my platform review day.

**Comment by rpoyner-tri** [comment]
See #18716.
