### ISSUE TITLE
Upgrade Externals February 2023

### ISSUE THREAD

**Issue by jwnimmer-tri** [RobotLocomotion/drake#18724]
Follow [Semi-automated monthly upgrades](https://github.com/RobotLocomotion/drake/blob/master/tools/workspace/README.md#semi-automated-monthly-upgrades) documentation.

- [x] #18753
- [x] #18754

Prior issue: #18510.

**Comment by BetsyMcPhail** [comment]
@mwoehlke-kitware can you please take care of the external updates this month?

**Comment by jwnimmer-tri** [comment]
TTBOMK this is finished.
