### ISSUE TITLE
Drake should support planar joints in URDF under the standard `joint` tag

### ISSUE THREAD

**Issue by rpoyner-tri** [RobotLocomotion/drake#18730]
### What happened?

An URDF file with a planar joint failed to parse, with the error:

```
Joint joint0 of type planar is a custom joint type, and should be a <drake:joint>
```
but, in fact, `planar` is a standard joint type in URDF.

Slack discussion here: https://drakedevelopers.slack.com/archives/C2WBPQDB7/p1675340885355229

### Version

v1.11+

### What operating system are you using?

Ubuntu 22.04

### What installation option are you using?

compiled from source code using Bazel

**Comment by SeanCurtis-TRI** [comment]
@rpoyner-tri I've assigned this to you as resident parser king. Feel free to pass it along as appropriate.

**Comment by SeanCurtis-TRI** [comment]
Did #18735 close this?

**Comment by xuchenhan-tri** [comment]
#18735 closes this but somehow the github keyword didn't kick in.

**Comment by jwnimmer-tri** [comment]
(The magic has to be in the PR description (top post) for it to have the auto-close effect.)
