### ISSUE TITLE
Include arbitrary constraints in reaction forces

### ISSUE THREAD

**Issue by amcastro-tri** [RobotLocomotion/drake#18749]
The computation of reaction forces essentially boils down to performing a free body diagram and therefore it requires the spatial forces applied on each body. Therefore to include arbitrary constraints in the reaction forces, constraints must be able to translate constraint multipliers to actual spatial forces we can use in this computation. 

Ideally, once the impulses (gamma) are computed as `ContactSolverResults`, we could interrogate constraints to perform this translation for us, from impulses to spatial forces. The DiscreteUpdateManager would then loop through each constraint and accumulate their effect from within `DoCalcDiscreteUpdateMultibodyForces()`.

Therefore what we need is:
  1. API to interrogate arbitrary constraints so that they can tell us the multibody forces that result from a given set of constraint multipliers.
  2. Teach `CompliantContactManager::DoCalcDiscreteUpdateMultibodyForces()` to loop through constraints and accumulate results.

**Comment by sherm1** [comment]
👍
