### ISSUE TITLE
Buildifier needs update to latest

### ISSUE THREAD

**Issue by mwoehlke-kitware** [RobotLocomotion/drake#18754]
Per `new_release`, buildifier needs upgrade from 5.1.0 to 6.0.1. However, `new_release` is unable to do so automatically, nor is it immediately obvious how to upgrade this manually.

**Comment by jwnimmer-tri** [comment]
To upgrade, switch `version = "5.1.0"` to say 6.0.1 instead, and then update the sha256 checksums to match these binaries from the release page:

https://github.com/bazelbuild/buildtools/releases/download/6.0.1/buildifier-linux-amd64
https://github.com/bazelbuild/buildtools/releases/download/6.0.1/buildifier-darwin-amd64
