### ISSUE TITLE
tags = ["manual"] breaking on macOS

### ISSUE THREAD

**Issue by svenevs** [RobotLocomotion/drake#18762]
Buildcop discussion [on slack](https://drakedevelopers.slack.com/archives/C270MN28G/p1675953863786089).

Relates: #18742 (offending test), #18657 (_should_ have avoided this problem), revertings #18758 #18759 #18760.

Failed builds in question:

- [mac-arm-monterey-clang-bazel-nightly-debug](https://drake-jenkins.csail.mit.edu/view/Nightly%20Production/job/mac-arm-monterey-clang-bazel-nightly-debug/94/)
- [mac-x86-monterey-clang-bazel-nightly-debug](https://drake-jenkins.csail.mit.edu/view/Nightly%20Production/job/mac-x86-monterey-clang-bazel-nightly-debug/90/)
- [mac-x86-monterey-clang-bazel-nightly-everything-debug](https://drake-jenkins.csail.mit.edu/view/Nightly%20Production/job/mac-x86-monterey-clang-bazel-nightly-everything-debug/94/)

It is very unclear why, but a non-everything mac build hit a `mosek_test_tags() + ... + ["manual"]`:

https://github.com/RobotLocomotion/drake/blob/e51565608b03a54286620057c59f66fa83d059d3/geometry/optimization/dev/BUILD.bazel#L103-L108

This test should not be running in CI at all.  It appears it is on mac, possibly just debug?  From digging online some possibly related issues implying there's something going on with drake's bazel macros:

- https://github.com/bazelbuild/bazel/issues/4380
- https://github.com/bazelbuild/bazel/issues/2303
- [Current docs on manual tag](https://bazel.build/reference/be/common-definitions#common.tags), emphasis mine:

    > `manual` keyword will exclude the target from expansion of target pattern wildcards (`...`, `:*`, `:all`, etc.) and `test_suite` rules which do not list the test explicitly when computing the set of top-level targets to build/run for the `build`, `test`, and `coverage` commands. It does not affect target wildcard or test suite expansion in other contexts, including the `query` command. **Note that `manual` does not imply that a target should not be built/run automatically by continuous build/test systems. For example, it may be desirable to exclude a target from bazel test ... because it requires specific Bazel flags, but still have it included in properly-configured presubmit or continuous test runs.**

To add to the confusion, it _appears_ that this only affects debug flavors:

- [Continuous release build with the broken test](https://drake-jenkins.csail.mit.edu/view/Continuous%20Production/job/mac-x86-monterey-clang-bazel-continuous-release/416/consoleFull) only runs `//geometry/optimization/dev:cspace_free_polytope_test` not the mosek one that was actually broken.

Additional thoughts: #18657 landed _after_ #18545, so this may just be a hidden bazel 6 problem and it is just surfacing this way.

**Comment by svenevs** [comment]
@jwnimmer-tri when you are back we may need your help triaging this.

**Comment by jwnimmer-tri** [comment]
Is there still any relevant work here?  If CI is passing now (by fixing the test), it seems like we can close this and revisit only if it comes up again.

**Comment by svenevs** [comment]
Happy to close, CI is OK for now.  However, it's likely this is going to come back up again in the future.  Linux correctly skips the tests, it seems really problematic that we even had the CI failures in the first place.  So if there is an action item for this ticket, it's "identify why the test was running" and then subsequently remedy that.

**Comment by jwnimmer-tri** [comment]
Yup.  FYI there is https://stackoverflow.com/questions/7208070/googletest-how-to-skip-a-test another way to skip googletests.  Also `args = ["--test_filter=..."]` is another option.
