### ISSUE TITLE
Release v1.13.0 follow-up

### ISSUE THREAD

**Issue by jwnimmer-tri** [RobotLocomotion/drake#18794]
Binary date: `20230215`

Commit SHA: `f062738a338ab26776d24c14e6d5d79b2280a79c`

Release tag: `v1.13.0.`

**Comment by BetsyMcPhail** [comment]
Docker and S3 are all set. Apt packages will be updated shortly.

**Comment by BetsyMcPhail** [comment]
And Apt packages are ready
