### ISSUE TITLE
YCB Collision Geometry Sphere Placement

### ISSUE THREAD

**Issue by nepfaff** [RobotLocomotion/drake#18839]
### What happened?

I looked at the [YCB mustard bottle collision geometry](https://github.com/RobotLocomotion/drake/blob/master/manipulation/models/ycb/sdf/006_mustard_bottle.sdf) and noticed that the spheres are offset from the main box primitive. Wouldn't the desired placement be at the box edges?

A collision geometry visualization with the sphere radii inflated from 1e-7 to 1e-3 for visibility:
![image](https://user-images.githubusercontent.com/53228351/220398862-7831976d-91e4-495f-a555-bb828cd05b49.png)

**Comment by jwnimmer-tri** [comment]
+@EricCousineau-TRI is there any history here we should know about?

**Comment by EricCousineau-TRI** [comment]
Nothing that I'm aware of, unfortunately.

**Comment by jwnimmer-tri** [comment]
Re-filed in new home of YCB objects: https://github.com/RobotLocomotion/models/issues/39
