### ISSUE TITLE
Contact Model Equations

### ISSUE THREAD

**Issue by Cfather** [RobotLocomotion/drake#18881]
Hi,

I’m very interested in how Drake deals with contact constraints. I’ve gone through the documentation and they are really helpful! But I wonder if there’s a more mathematical introduction, like how you formulated the LCP problem. Is there any paper that you have referred to to implement the contact model?

Many thanks!

**Comment by sherm1** [comment]
How about this fine paper by Castro, et al.: https://arxiv.org/abs/2110.10107

**Comment by ggould-tri** [comment]
Assigning @sherm1 as a placeholder; feel free to reassign.

**Comment by sherm1** [comment]
Closing this issue -- if the paper doesn't answer your questions, please ask on Stackoverflow (tag "drake")
