### ISSUE TITLE
Unnecessary heap allocations in GeometryProperties::GetPropertyOrDefault()

### ISSUE THREAD

**Issue by edrumwri** [RobotLocomotion/drake#18897]
Per this line, https://github.com/RobotLocomotion/drake/blob/54667de5c2df601ddb3ca4b2fced0d7f21ec91e3/geometry/geometry_properties.h#L396, we've found that GeometryProperties::GetPropertyOrDefault() is needlessly allocating heap and impacting performance. We're trying to use this functionality in real time code for visualization, so the heap allocation is not helpful.

I'd suggest simply swapping the first string parameter of GetValueOrThrow() to a string_view, which would seem to be a pretty minimal change.

**Comment by SeanCurtis-TRI** [comment]
Yep. The current API is a bit archaic -- it predated our use of `string_view`.
