### ISSUE TITLE
Hydroelastic user guide features is out of date

### ISSUE THREAD

**Issue by SeanCurtis-TRI** [RobotLocomotion/drake#18913]
## Visualization
The user guide was written when `drake_visualizer` was still supported (and represented the "premium" hydro visualization mechanism). Those days are gone and it we should no longer feature that in the user guide. The discussion and images should be updated to reflect the current set of tools and visualization capabilities.

In addition to visual quality that hasn't currently been reproduced, we go so far as to show `drake_visualizer`-only visualizer configuration. E.g.: 

![image](https://user-images.githubusercontent.com/22159799/222156394-82ddb371-2eae-4e5a-856a-32a7043b3727.png)

See the guide's current treatment on [Visualizing hydroelastic contact](https://drake.mit.edu/doxygen_cxx/group__hydroelastic__user__guide.html#hug_visualizing).

## Compliant meshes

There's no mention of introducing compliant meshes (as vtk file). This is obviously something that would likewise be worthwhile to note in the user guide.

### Version

v1.13.0

**Comment by jwnimmer-tri** [comment]
@DamrongGuoy @rpoyner-tri This becomes ever more pressing, as almost everyone is using Jammy now and Focal support will be dropped in ~7 months.

It also relates to #16216, where several hydro examples are still hard-coded to use `//tools:drake_visualizer`.

**Comment by DamrongGuoy** [comment]
@jwnimmer-tri Thanks for asking.  Please kindly have `#drake-adoption` work on it.

**Comment by jwnimmer-tri** [comment]
> There's no mention of introducing compliant meshes (as vtk file). This is obviously something that would likewise be worthwhile to note in the user guide.

That's a pretty distinct request vs fixing the visualization, so I've broken it out into #20176.  I'll leave this ticket focused on fixing our documentation related to hydro visualization.
