### ISSUE TITLE
Upgrade Externals March 2023 

### ISSUE THREAD

**Issue by BetsyMcPhail** [RobotLocomotion/drake#18914]
Follow [Semi-automated monthly upgrades](https://github.com/RobotLocomotion/drake/blob/master/tools/workspace/README.md#semi-automated-monthly-upgrades) documentation.

- [x] #18926
- [x] #18929
- [x] #18931

Prior issue: #18724

**Comment by jwnimmer-tri** [comment]
Checklist complete.  Moving to In Progress => Done.
