### ISSUE TITLE
Make Prius URDF and SDF Models Symmetric

### ISSUE THREAD

**Issue by liangfok** [RobotLocomotion/drake#1896]
As mentioned in https://github.com/RobotLocomotion/drake/issues/1714#issuecomment-198941587, the Prius models are currently not symmetric across the sagittal plane.

**Comment by david-german-tri** [comment]
Is this still open?

**Comment by liangfok** [comment]
Yes. I have not had time to revisit it. The Prius URDF and SDF models are definitely not symmetric around the sagittal plane right now. :frowning: 

Will work on fixing this soon.

**Comment by jwnimmer-tri** [comment]
I re-read #1714.  That was an adventure.  I believe its conclusion is that the car's wheels are asymmetric by 13 microns.  I'm going to call that wont-fix.
