### ISSUE TITLE
CollisionCheckerParams option to disable preallocated contexts

### ISSUE THREAD

**Issue by jwnimmer-tri** [RobotLocomotion/drake#18982]
The `CollisionChecker::AllocateContexts()` function (called from the constructor) pre-allocates collision checking contexts so that the checker can be used in an OpenMP par-for loop.  For example, my computer has 48 vcpus, so the class constructs 48 contexts.

In some cases, the user knows that they will not be using OpenMP calls into the checker, in which case these extra contexts are a waste of resources.

We should consider adding a flag to `CollisionCheckerParams` for the user to opt-out of the per-thread contexts.  If they opt-out but still try to use the checker in a par-for loop, the checker should throw an exception.

\CC @calderpg-tri FYI.

**Comment by jwnimmer-tri** [comment]
As a work-around for now, you can use something like this class to disable OpenMP prior to creating a CollisionChecker:

https://github.com/ToyotaResearchInstitute/common_robotics_utilities/blob/89435ebf4621f4e92d3b4c2a18aec7fa91e0cb75/include/common_robotics_utilities/openmp_helpers.hpp#L181

Any future clones of that checker will also be throttled to just use 1 thread & 1 context.

Setting `OMP_NUM_THREADS=1` environment variable is probably another option.

**Comment by jwnimmer-tri** [comment]
Maybe a good answer here would be to add `Parallellism parallelism` to the `CollisionCheckerParams` struct?

@calderpg-tri WDYT?

**Comment by calderpg-tri** [comment]
Yes, my thinking is to replace the current logic in `AllocateContexts` with a provided `Parallelism` (defaulted to `Parallelism::Max()`). The same holds for `PerThreadRandomSource` in anzu, which uses essentially identical logic for allocating per-thread generators.
