### ISSUE TITLE
RollPitchYaw API suggestion for getting RpyDt from AngularVelocityInChild

### ISSUE THREAD

**Issue by youngiltrictr** [RobotLocomotion/drake#18984]
**Is your feature request related to a problem? Please describe.**
It's not a critical problem but just for completeness, I think it would be nice that `RollPitchYaw` provides `CalcRpyDtFromAngularVelocityInChild` too. It only provides `CalcRpyDtFromAngularVelocityInParent`.

For the other direction, `RollPitchYaw` provides two methods
`CalcAngularVelocityInChildFromRpyDt` and `CalcAngualrVelocityInParentFromRpyDt`

**Comment by jwnimmer-tri** [comment]
FYI This issue arose from [a slack thread](https://app.slack.com/client/T0JNB2DS4/C3YB3EV5W/thread/C3YB3EV5W-1677807690.318249).

One suggestion there was:

> In the meantime, since  w_AD_A = R_AD * w_AD_D,  you can use something like:
CalcRpyDtFromAngularVelocityInParent( R_AD *  w_AD_D);
where w_AD_D is body D's angular velocity in A, expressed in D, i.e., AngularVelocityInChild.

**Comment by mitiguy** [comment]
PR #19018 helps address issue #18984

**Comment by mitiguy** [comment]
PR [19074](https://github.com/RobotLocomotion/drake/pull/19074) resolves issue [18984](https://github.com/RobotLocomotion/drake/issues/18984).
