### ISSUE TITLE
Namespace for render-related Python bindings

### ISSUE THREAD

**Issue by zachfang** [RobotLocomotion/drake#19088]
In #18877, we make efforts for the namespaces in three `RenderEngine` implementations to be consistent. We should also revisit render-related Python bindings due to the changes on the C++ side.

CC\ @jwnimmer-tri

**Comment by jwnimmer-tri** [comment]
See #11802 and #12055.  The overall goal is to use less deeply nested module names.

We should aim for everything in https://drake.mit.edu/pydrake/pydrake.geometry.render.html to move up 1 level (i.e., drop the `.render` qualifier), no matter which C++ namespace it uses.
