### ISSUE TITLE
Add OpenMP selection in CMake builds

### ISSUE THREAD

**Issue by jwnimmer-tri** [RobotLocomotion/drake#19091]
We offer CMake flags like `-DWITH_SNOPT=ON` to configure optional components of Drake.  However, we're missing one for OpenMP (e.g., `-DWITH_OPENMP`).

We should either add such an option, or provide documentation for how to do it manually (by setting `CFLAGS` uniformly for the entire downstream project).

Whatever we decide, we should fix CI jobs for "CMake Everything" on Ubuntu to turn on OpenMP.  Currently, it is off in CMake jobs but on in "Bazel Everything" jobs.

**Comment by jwnimmer-tri** [comment]
One question is whether there is some canonical spelling in CMake options for something like `-DWITH_OPENMP`.  If there is a convention (or at least, a commonly-found spelling in the wild), we should use that.

**Comment by jwnimmer-tri** [comment]
Drake is `--config=omp` added to the rcfile.

**Comment by jwnimmer-tri** [comment]
Re-opening to track adding the CI coverage.

**Comment by mwoehlke-kitware** [comment]
https://github.com/RobotLocomotion/drake-ci/pull/260

**Comment by BetsyMcPhail** [comment]
CI changes have also been merged, closing.
