### ISSUE TITLE
macOS CI job shuffle

### ISSUE THREAD

**Issue by jwnimmer-tri** [RobotLocomotion/drake#19097]
Down to one x86 node.  (Cut down 50%; max 3 concurrent jobs; losing cache server.)
- Wheel kicks at 1am.
- Nightly kicks off at 2am.

Action items

- [x] Remove x86 Nightly jobs as specified above
- [x] As soon as the Experimental job passes, add `mac-arm-monterey-clang-bazel-nightly-everything-address-sanitizer`
- [x] Turn off x86 Mac caching in drake-ci. There's currently an issue with the cache server anyway ([slack conversation](https://drakedevelopers.slack.com/archives/C270MN28G/p1680191275334209))
- [x] Remove mention of x86 Mac caching from [build cop documentation](https://drake.mit.edu/buildcop.html)
- [X] Update Jenkins configuration for max x86 VSphere jobs to ~~3~~ 2 (can wait until we only have one node to do this)

**Comment by jwnimmer-tri** [comment]
I'll defer to #18327 for adding the Ventura ARM jobs.  We'll need the bigger ARM cluster in place first, so it'll be easier to track it there.  This issue can be about just the x86 spin-down.

**Comment by BetsyMcPhail** [comment]
> With the timing of jobs, we have ~2 hours of wheel + packaging, which won't finish (on 1 node) before the rest of the nightly builds launch. Possibly we will need to either change the trigger times, or else ensure that Packaging and Wheel get scheduling priority over the rest of Nightly.

This is exactly what prompted the Packaging and Wheel jobs to be moved to an earlier start. They are scheduled first and any other Nightly jobs will queue up behind them.

**Comment by BetsyMcPhail** [comment]
Action items

- [ ] Remove x86 Nightly jobs as specified above
- [ ] As soon as the Experimental job passes, add `mac-arm-monterey-clang-bazel-nightly-everything-address-sanitizer`
- [ ] Turn off x86 Mac caching. There's currently an issue with the cache server anyway ([slack conversation](https://drakedevelopers.slack.com/archives/C270MN28G/p1680191275334209))
- [ ] Update Jenkins configuration for max x86 VSphere jobs to 3 (can wait until we only have one node to do this)

**Comment by svenevs** [comment]
@BetsyMcPhail we may be able to add it, but that job is a long running one.

1. mac-arm-monterey-clang-bazel-nightly-address-sanitizer: ~2.5hrs, reliably starting around 3am.
2. mac-arm-monterey-clang-bazel-nightly-debug: ~3 hours, reliably starting around 4am
3. mac-arm-monterey-clang-bazel-nightly-everything-release: ~1hr 45min, reliably starting around 3am.
4. mac-arm-monterey-clang-cmake-nightly-everything-release: ~30min, reliably starting around 445am.
5. mac-arm-monterey-clang-cmake-nightly-release: ~30 min, reliably starting around 420am.
6. mac-arm-monterey-unprovisioned-clang-bazel-nightly-packaging: ~30minutes, starts at 1am.
7. mac-arm-monterey-unprovisioned-clang-bazel-nightly-release: ~1hour 45min, reliably starting around 245am.
8. mac-arm-monterey-unprovisioned-clang-wheel-nightly-release: ~40 minutes, starts at 1am.

Can we just change `mac-arm-monterey-clang-bazel-nightly-address-sanitizer` to be `everything-address-sanitizer`?  I think based on the above if we added it, it still looks like it would finish before 9am, but it may be tight.

**Comment by jwnimmer-tri** [comment]
Fine by me.  New plan:

```patch
--- jobs-prior.txt
+++ jobs-future.txt
@@ -1,20 +1,15 @@
 mac-arm-monterey-clang-cmake-nightly-release
 mac-arm-monterey-clang-cmake-nightly-everything-release
 mac-arm-monterey-clang-bazel-continuous-release
 mac-arm-monterey-clang-bazel-nightly-everything-release
 mac-arm-monterey-clang-bazel-nightly-debug
-mac-arm-monterey-clang-bazel-nightly-address-sanitizer
+mac-arm-monterey-clang-bazel-nightly-everything-address-sanitizer
 mac-arm-monterey-unprovisioned-clang-bazel-nightly-release
 mac-arm-monterey-unprovisioned-clang-bazel-nightly-packaging
 mac-arm-monterey-unprovisioned-clang-wheel-nightly-release
-mac-x86-monterey-clang-cmake-nightly-release
-mac-x86-monterey-clang-cmake-nightly-everything-release
 mac-x86-monterey-clang-bazel-continuous-release
-mac-x86-monterey-clang-bazel-nightly-everything-release
-mac-x86-monterey-clang-bazel-nightly-debug
 mac-x86-monterey-clang-bazel-nightly-everything-debug
-mac-x86-monterey-clang-bazel-nightly-address-sanitizer
-mac-x86-monterey-clang-bazel-nightly-everything-address-sanitizer
 mac-x86-monterey-unprovisioned-clang-bazel-nightly-release
 mac-x86-monterey-unprovisioned-clang-bazel-nightly-packaging
 mac-x86-monterey-unprovisioned-clang-wheel-nightly-release
```

**Comment by svenevs** [comment]
Backend vSphere cleanup (storage purging to meet the reduced capacity in particluar) are complete.  Our Jenkins configs reflect the new one-node usage allowing 2 executors at once.  If nightlies over the next couple of days are not finishing in time we can re-evaluate, but for now we consider this resolved.
