### ISSUE TITLE
MultibodyPlant random contexts fall back to zero positions, not defaults

### ISSUE THREAD

**Issue by jwnimmer-tri** [RobotLocomotion/drake#19106]
### What happened?

See [StackOverview](https://stackoverflow.com/questions/75881315/pydrake-montecarlosimulation-pose-of-freebody-being-reset) for the original discovery.

Right now, if I don't set up any random distributions on a MultibodyPlant and then I call `SetRandomContext`, the state I get back is all zeros (except for the '1' in any quaternions).  This happens even if I've previously called `SetDefaultFreeBodyPose` on a free body.

The thing I assumed I would get would be the default joint postures as-if from CreateDefaultContext, for state where I haven't configured any random distribution yet.

### Version

v1.14.0

### What operating system are you using?

Other

### What installation option are you using?

Unknown / Other

**Comment by jwnimmer-tri** [comment]
My testing was only with free bodies (quaternion floating joints).  However, I _think_ the same bug probably also applies to all joint types.

**Comment by jwnimmer-tri** [comment]
Ping to @xuchenhan-tri for your "MbB bugs worth fixing" panel.

**Comment by xuchenhan-tri** [comment]
@jwnimmer-tri do you want to assign a priority label to this issue?

**Comment by jwnimmer-tri** [comment]
I don't have any particular urgency one way or the other.

In the regime of "MbP computes the wrong answer" bugs, things like #18682 seem more urgent.  For my taste though, I still think we should fix "computes wrong answer" bugs before working on adding any new features.
