### ISSUE TITLE
Upgrade Externals April 2023

### ISSUE THREAD

**Issue by BetsyMcPhail** [RobotLocomotion/drake#19137]
Follow [Semi-automated monthly upgrades](https://github.com/RobotLocomotion/drake/blob/master/tools/workspace/README.md#semi-automated-monthly-upgrades) documentation.

- [x] #19185
- [x] #19189
- [x] #19186
- [ ] #19187

Prior issue: #18914

**Comment by BetsyMcPhail** [comment]
@mwoehlke-kitware thanks for the reminder! Here's the issue for April external updates.

**Comment by mwoehlke-kitware** [comment]
Notes:
- It wasn't immediately obvious how to obtain the checksums needed to do a manual upgrade of buildifier.
- Per https://github.com/RobotLocomotion/drake/blob/master/tools/workspace/qdldl_internal/README.md, as OSQP has not changed and SCS appears to be working, QDLDL has not been changed.

PR's for the others will be coming...

**Comment by jwnimmer-tri** [comment]
> It wasn't immediately obvious how to obtain the checksums needed to do a manual upgrade of buildifier.

If you set the checksum to an incorrect value (e.g., `"0" * 64), the complaint when you run bazel will contain a printout of the correct value.  Alternatively, you can download the buildifier file by hand and run `sha256sum` on it.

**Comment by mwoehlke-kitware** [comment]
> If you set the checksum to an incorrect value, the complaint when you run bazel will contain a printout of the correct value.

I assumed that would be the case, but wouldn't that require doing so on every platform that has a different binary?

> Alternatively, you can download the buildifier file by hand and run `sha256sum` on it.

That's what I did for #19189. The main thing that "wasn't immediately obvious" was where to *find* those files. I added a note to the `repository.bzl` that should make it more obvious next time.

**Comment by jwnimmer-tri** [comment]
Everything has either been upgraded to delegated to a separate already-open PR.
