### ISSUE TITLE
RenderEngineGl supports MTL files

### ISSUE THREAD

**Issue by zachfang** [RobotLocomotion/drake#19188]
Currently, `RenderEngineGl` **can** load MTL files via `tiny_obj_loader`, but the code ignores it to be consistent with other RenderEngine implementations.

As the first pass to support MTL files in RenderEngineGl, we will only accept an MTL file with one texture, i.e., a phong texture or `map_Kd`, and ignore if an MTL file has multiple textures with a warning.

**Comment by jwnimmer-tri** [comment]
See https://github.com/RobotLocomotion/drake/issues/18844#issuecomment-1602137932 for some more details.

@SeanCurtis-TRI @zachfang we should probably use this ticket to discuss GL details, instead of the Epic ticket?

**Comment by zachfang** [comment]
Sounds good. I used that comment to capture the status for all three RenderEnigines and agreed we should have any follow-up Gl-specific discussions here.
