### ISSUE TITLE
Missing MultibodyPlant::GetDefaultPositions()?

### ISSUE THREAD

**Issue by EricCousineau-TRI** [RobotLocomotion/drake#19203]
**Is your feature request related to a problem? Please describe.**
I would like to access the default positions in the same way that I mutate them via `SetDefaultPositions()`.

**Describe the solution you'd like**
`GetDefaultPositions()` (both full and model-instance variant) exist

**Describe alternatives you've considered**
Inverting and rewriting the `SetDefaultPositions()` logic from scratch

**Additional context**
Control involving more than one model instance / a mask set.

**Comment by jwnimmer-tri** [comment]
FYI the workaround for now is `Eigen::VectorXd{plant.GetPositions(*plant.CreateDefaultContext())}` or `plant.GetPositions(*plant.CreateDefaultContext(), model_instance)`
