### ISSUE TITLE
Determining More Linear System Properties (Beyond Controllability)

### ISSUE THREAD

**Issue by cohnt** [RobotLocomotion/drake#19227]
It's useful to check if a linear system (A,B) is controllable (with `drake::systems::IsControllable`) before attempting to construct certain controllers. There are other conditions one might also want to check

- Stabilizability. See [this lecture](https://solmaz.eng.uci.edu/Teaching/MAE270A/Lec/Lec15.pdf), slide 3 for a necessary and sufficient condition.
- Observability. One checks the rank of the [observability matrix](https://en.wikipedia.org/wiki/Observability#Observability_matrix). It is also [equivalent](https://aswani.ieor.berkeley.edu/teaching/SP17/265/lecture_notes/ieor265_lec10.pdf) to the controllability of  (B',A').
- Detectability. Is is [equivalent](https://aswani.ieor.berkeley.edu/teaching/SP17/265/lecture_notes/ieor265_lec10.pdf) to the stabilizibility of (B',A').

As examples of their usefulness, [this source](https://www.egr.msu.edu/classes/me851/mukherji/09-LQR.pdf). notes that stabilizability and detectability serve as necessary and sufficient conditions for the existence of a stabilizing LQR solution

Note that these each of these conditions can be checked with some relatively straightforward linear algebra. I'm not sure what the threshold for something to be included in Drake is, but this seems pretty similar to `IsControllable`. Feel free to close the issue if this is insignificant.

(Related to #19191)

**Comment by EricCousineau-TRI** [comment]
Assigning @hongkai-dai for disposition
