### ISSUE TITLE
v1.15.0 tag docker images

### ISSUE THREAD

**Issue by EricCousineau-TRI** [RobotLocomotion/drake#19224]
@BetsyMcPhail Would you be able to manually tag docker images and upload releases to S3?

binary date: 20230418
release tag: v1.15.0

https://github.com/RobotLocomotion/drake/releases/tag/v1.15.0
https://drake.mit.edu/release_notes/v1.15.0.html

**Comment by BetsyMcPhail** [comment]
Docker and apt have been updated for the 1.15.0 release.
