### ISSUE TITLE
Python Bindings for MobyLCP and UnrevisedLemkeSolver

### ISSUE THREAD

**Issue by FranekStark** [RobotLocomotion/drake#19259]
For now there is no binding available to directly instantiate and use MobyLCP solver or UnrevisedLemkeSolver from Python. 
There is a hacky workaround: https://stackoverflow.com/questions/75230323/where-is-mobylcpsolver

However, I think it would be great to have both these Solvers also in the python bindings available.

**Comment by ggould-tri** [comment]
Labeled `mathematical program` and assigned Hongkai for delegation.
