### ISSUE TITLE
Failure in nightly CI: ELF load command address/offset not properly aligned

### ISSUE THREAD

**Issue by SeanCurtis-TRI** [RobotLocomotion/drake#19261]
### What happened?

As of the [night of April 23, 2023, `linux-focal-unprovisioned-gcc-wheel-nightly-release` is failing](https://drake-jenkins.csail.mit.edu/view/Nightly%20Production/job/linux-focal-unprovisioned-gcc-wheel-nightly-release/50/) with the following complaint:

```
ImportError: libtbb-fb00472a.so.12.6: ELF load command address/offset not properly aligned
```

Leading to failure of `Executing test tests/pyi-install-test.py`.

The error persisted across a retriggered build. Presumably, some system package upgrade has moved out from under us. We need to scrub through the logs to see what is different from the 22nd.

### Version

8524daf

### What operating system are you using?

Ubuntu 20.04

**Comment by jwnimmer-tri** [comment]
During `RUN /image/provision-python.sh 3.8 `:
* Prior nightly passing: `patchelf-0.17.2.1`.
* Current nightly failing: `patchelf-0.18.0.0`.

**Comment by jwnimmer-tri** [comment]
Upstream just worked around it:
https://github.com/mayeut/patchelf-pypi/issues/87#issuecomment-1520658884
