### ISSUE TITLE
RigidBodySystem shouldn't contain every specific RigidBodySensor

### ISSUE THREAD

**Issue by david-german-tri** [RobotLocomotion/drake#1927]
RigidBodySystem (.h and .cpp) has become pretty bloated.  @psiorx, would you consider moving your various RigidBodySensor subclasses to their own separate files?  It would also be a good opportunity to make them [style guide compliant](https://google.github.io/styleguide/cppguide.html).

@rpoyner-tri FYI

**Comment by psiorx** [comment]
I agree.  I'm a strong believer of the one class per file rule.  Sensors should probably even have their own directory.

@RussTedrake Was there a specific reason for having multiple classes in the same file?  I've seen this in a few other places as well (CascadeSystem comes to mind).

**Comment by RussTedrake** [comment]
Not a good reason (was just trying to push out a boat load of functionality 
before the influx of developers). Much better to have separate files.

**Comment by david-german-tri** [comment]
This is moot now that System1 is gone.
