### ISSUE TITLE
Maximum iteration / time option for BranchAndBound algorithm

### ISSUE THREAD

**Issue by FranekStark** [RobotLocomotion/drake#19284]
As far as I can oversee the API there is currently no way to give the mixed integer branch and bound algorithm a maximum number of iterations or more importantly time. So it comes to the fact that it computes in difficult cases very long, uses a lot of resources and can hardly or not at all be stopped. 

I think a maximum time or iteration could solve this problem easily.

**Comment by hongkai-dai** [comment]
Thanks @FranekStark , I can add that feature later on the iteration (or number of nodes that has been explored by the tree).

Just curious, have you considered using Gurobi or Mosek for your mixed-integer problem?

**Comment by FranekStark** [comment]
Thank you @hongkai-dai!
Actually yes. However, we are working on an open-source project for that we try to avoid using a commercial solver. For now, the simple Branch and Bound algorithm gives some promising results why I use it for now. Just this "getting" stuck is a bit annoying and the reason for my feature request.

**Comment by hongkai-dai** [comment]
BTW, I submitted #19366 Sorry for the delay.

**Comment by FranekStark** [comment]
Thanks!
