### ISSUE TITLE
Incoroporate H&C into SAP

### ISSUE THREAD

**Issue by amcastro-tri** [RobotLocomotion/drake#19320]
Since SAP was merged into Drake, we found out H&C is a better model of compliant contact. We also found out that we need more freedom when choosing both our compliant contact model and our regularization of friction. An example of this is the "popping" artifact observed in #18241. Moreover,  recent anlysys of both models show us that objects' bounce velocity is bounded for H&C but not for the linear model of dissipation.
The good news is that now our research showed us how to make this happen. We know now how to incorporate arbitrary models of compliance and regularization.

This issue tracks progress towards a H&C model with regularized frction (via stiction tolerance as in TAMSI) in SAP.

**Comment by DamrongGuoy** [comment]
I added that in H&C dissipation model, the bounce velocity v_b is bounded from above by 1 /h, where h is [drake:hunt_crossley_dissipation](https://drake.mit.edu/doxygen_cxx/group__multibody__parsing.html#tag_drake_hunt_crossley_dissipation). In the linear dissipation model, the bounce velocity is bounded from above by x0 / tau, where x0 is the deepest penetration distance and tau is [drake:relaxation_time](https://drake.mit.edu/doxygen_cxx/group__multibody__parsing.html#tag_drake_relaxation_time).

H&C:   v_b < 1 / h
Linear:  v_b < x0 / tau

In H&C, the upper bound of bounce velocity doesn't depend on how deep the penetration is.  In the linear model, that upper bound does depend on the penetration, in addition to [drake:relaxation_time](https://drake.mit.edu/doxygen_cxx/group__multibody__parsing.html#tag_drake_relaxation_time).

**Comment by jbinagia** [comment]
A quick question. Once H&C is incorporated into SAP, will the former model of dissipation (i.e. specifying `relaxation_time`) be deprecated? We have some SDF files that currently specify both `relaxation_time` and `hunt_crossley_dissipation` (knowing that the latter is ignored by the parser currently when using SAP); I just want to double-check that no unexpected behavior will result once the switch to H&C is made.

**Comment by amcastro-tri** [comment]
Sorry, forgot to answswer this @jbinagia. As we've done with other deprecated features/apis, these two parameters will coexist in Drake for a while. Therefore if a user selects the SAP contact model, the H&C dissipation will be ignored and the relaxation time will parameterize dissipation. Conversely, if the user selects the convex H&C model.

I imagine that long before deprecation happens, the H&C model will become the default model, followed by SAP becoming the default solver. Then users will have the preferered model/solver as default, but could opt-in for the older SAP model (and/or TAMSI). 

Finally, there might never be a deprecation.
