### ISSUE TITLE
ModuleNotFoundError: No module named 'pydrake.planning.common_robotics_utilities'

### ISSUE THREAD

**Issue by dbdxnuliba** [RobotLocomotion/drake#19346]
### What happened?

>>> from IPython.display import HTML, SVG
>>> from pydrake.geometry import MeshcatVisualizer, MeshcatVisualizerParams, Role, StartMeshcat
>>> from pydrake.geometry.optimization import IrisInConfigurationSpace, IrisOptions
>>> from pydrake.multibody.parsing import LoadModelDirectives, Parser, ProcessModelDirectives
>>> from pydrake.multibody.plant import AddMultibodyPlantSceneGraph
>>> from pydrake.planning.common_robotics_utilities import SimpleRRTPlannerState
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'pydrake.planning.common_robotics_utilities'
>>> import pydrake.planning
>>> 

### Version

drake-1.13.0

### What operating system are you using?

Ubuntu 20.04

### What installation option are you using?

compiled from source code using CMake

### Relevant log output

```shell
cd /home/dell/ref/drake-1.13.0
mkdir drake-build
cd drake-build
cmake -DWITH_GUROBI=OFF -DWITH_MOSEK=OFF -DWITH_SNOPT=ON ..
make -j2

and finish install it into /home/dell/ref/drake-1.13.0/drake-build/install

and then sudo gedit ~/.bashrc
#bazel related
source /home/dell/.bazel/bin/bazel-complete.bash
export PATH=$PATH:$HOME/bin

export DRAKE_BUILD_DIR=$HOME/ref/drake-1.13.0/drake-build
export PYTHONPATH=${DRAKE_BUILD_DIR}/install/lib/python3.8/site-packages:${PYTHONPATH}
```

**Comment by jwnimmer-tri** [comment]
>  ModuleNotFoundError: No module named 'pydrake.planning.common_robotics_utilities'

There has never been such a module as part of Drake.  I am not sure where you found that line, but maybe it was from someone who was using a fork of Drake.

Do you have any more details you could offer?

**Comment by dbdxnuliba** [comment]
@jwnimmer-tri 
I find here https://github.com/mpetersen94/gcs/blob/main/reproduction/prm_comparison/prm_comparison.ipynb
![image](https://user-images.githubusercontent.com/13350158/236359898-f25a5f2a-d209-49ba-8f1a-071d51e11c1e.png)

**Comment by jwnimmer-tri** [comment]
Okay, thanks for the link.  That example from `mpetersen94` repository must not have been using an official version of Drake.  Perhaps you can ask over in that repository how to run that reproduction.

In any case, there is no bug in Drake.  There has never been `pydrake.planning.common_robotics_utilities` module as part of Drake.

**Comment by dbdxnuliba** [comment]
OK ,thanks a lot
