### ISSUE TITLE
Buildcop email template changes URL not isolated to failed build

### ISSUE THREAD

**Issue by svenevs** [RobotLocomotion/drake#19340]
You get an email like

```
Subject: [drake-developers] Jenkins build is unstable: linux-jammy-gcc-bazel-continuous-debug #329

Body:
See <https://drake-jenkins.csail.mit.edu/job/linux-jammy-gcc-bazel-continuous-debug/329/display/redirect?page=changes>
```

Redirect page does not isolate you to the changes associated with the build, which (at least today) can be more confusing than helpful when there's failed builds stacked up coming in at different times (e.g., the fix has already landed):

https://drake-jenkins.csail.mit.edu/job/linux-jammy-gcc-bazel-continuous-debug/329/display/redirect?page=changes => https://drake-jenkins.csail.mit.edu/job/linux-jammy-gcc-bazel-continuous-debug/changes

There is a url https://drake-jenkins.csail.mit.edu/job/linux-jammy-gcc-bazel-continuous-debug/329/changes which I think is what we want

Fix in yaml side is easy, relevant section

```
emailext (
    subject: "${{subject}}: ${{env.JOB_NAME}} #${{env.BUILD_NUMBER}}",
    body: "See <${{env.BUILD_URL}}display/redirect?page=changes>",
    to: '$DEFAULT_RECIPIENTS',
)
```

`${{env.BUILD_URL}}display/redirect?page=changes` => `${{env.BUILD_URL}}changes` AFAICT.

I don't have any strong opinions though.  Easy to close as #wontfix if we like the current setup.

CC @BetsyMcPhail @jwnimmer-tri

**Comment by jwnimmer-tri** [comment]
I'm not a buildcop so the people who are should weigh in, but for my money the only thing email is good for is as a timely reminder to go open up https://drake-jenkins.csail.mit.edu/view/Production/ and see what's what.  That page is the way any the light.

**Comment by svenevs** [comment]
CC buildcops for low priority bikeshedding conversation: @rpoyner-tri @BetsyMcPhail @liangfok @EricCousineau-TRI @SeanCurtis-TRI @ggould-tri @mwoehlke-kitware @DamrongGuoy @xuchenhan-tri

**Comment by DamrongGuoy** [comment]
Do I get it correctly?  The two candidates are:

### A. Series of changes
https://drake-jenkins.csail.mit.edu/job/linux-jammy-gcc-bazel-continuous-debug/329/display/redirect?page=changes
![image](https://user-images.githubusercontent.com/42557859/236100419-35b28355-551f-423a-a287-b31491ddbb07.png)

### B. Specific to one change
https://drake-jenkins.csail.mit.edu/job/linux-jammy-gcc-bazel-continuous-debug/329/changes
![image](https://user-images.githubusercontent.com/42557859/236100554-9d50685c-5aec-4640-acbd-c088cb37d504.png)


### My preference
I like **B. Specific to one change**, so I don't have to remember the change number (329 in this case).

**Comment by svenevs** [comment]
Yes, thank you for clarifying -- pictures were much more valuable here...  Currently we have A, my preference is also B.

**Comment by SeanCurtis-TRI** [comment]
I have a small bias for having the context. I rely on that as much as the specific failed build. So, whether I start with context and need to remember which build was specifically flagged (if it isn't obvious by being the only angry build within a recent window) or whether I'm looking at an unambiguously called-out build but have to go fishing for the context, there's the potential for a two-step operation for me. The current seems to carry less friction for how I think about it.

That said, if the majority prefer a more targeted link, I wouldn't grouse.

**Comment by svenevs** [comment]
All good points.  It's not particularly obvious how to get to link A on your own and it can be helpful as stated.

When I am expecting a ripple through failure that I know is already fixed, I want link B to be able to quickly confirm "is this the commit I know is already fixed, or do I need to worry more."

Easy solution: I'll just add the link B after link A.  We can have two bicycle  wheels.

**Comment by BetsyMcPhail** [comment]
@mwoehlke-kitware while you're editing Jenkins, this issue should be quick to implement.

**Comment by svenevs** [comment]
The emails will now include both A and B (`See <${{env.BUILD_URL}}display/redirect?page=changes> and <${{env.BUILD_URL}}changes>`)
