### ISSUE TITLE
Allow increasing Meshcat kMaxPort

### ISSUE THREAD

**Issue by nepfaff** [RobotLocomotion/drake#19362]
**Is your feature request related to a problem? Please describe.**
At the moment, we are limited to 100 meshcat ports, and it is not possible to close a port without exiting the script that opened them. This is limiting if I want to run lots of simulations in a script and save the meshcat recording for each of them. This is a quite common scenario for me, and I keep running into this issue.

**Describe the solution you'd like**
From https://github.com/RobotLocomotion/drake/pull/15618, the reason for the current limit is docker:
>Yes. I've made it 7099, since that's the number of ports that the docker instances open up for meshcat (but it's all pretty arbitrary, i guess... I've rarely needed more than 2!). I've added a comment in the constructor, which I think is the right place since we may offer passing a port number as a constructor option in the future.

I would suggest adding an option to specify a custom value for `kMaxPort` to allow overriding the docker-motivated limit.

**Comment by ggould-tri** [comment]
Assigning @joemasterjohn as component owner.

**Comment by jwnimmer-tri** [comment]
My vote would not be for a config option, but instead to bump up our `kMaxPort` constant to be much larger (`32767`, to stop before we hit linux's ephemeral ports range).

Or if we want a config option, it would be something like `meshcat_params.listen = false;` which would not bind *any* port number.  The `Meshcat` object then could only be used for making recordings, not anything interactive.

**Comment by jwnimmer-tri** [comment]
Once #19960 lands, the linear search range will be wider.  More importantly for this use case, you can also specify `port = 0` which will let the kernel assign a port number automatically from a pool of >16,000.
