### ISSUE TITLE
discuss/resolve the way we handle external dependencies

### ISSUE THREAD

**Issue by RussTedrake** [RobotLocomotion/drake#1939]
I've started a google doc here:
https://docs.google.com/document/d/1RMDja0UcU1t5ASRSeu7kW2ZuWMb7u6mhswWPP4QT4xU/edit?usp=sharing

Please comment (right on the google doc)!  My goal is to flesh this out, make some decisions, and the move this into sphinx documentation.

**Comment by patmarion** [comment]
Perhaps the google doc can also indicate whether a dependency is required or optional, and if optional, what additional functionality it provides?

**Comment by RussTedrake** [comment]
Added required/optional column

**Comment by david-german-tri** [comment]
Since the Google Docs margin note conversations have died inconclusively (after a lot of great data gathering), I'll try to restart this thread.  

@jwnimmer-tri pointed out that the success criteria for changes to dependency management are unclear, and I agree.  @RussTedrake, maybe you can tell us more about the decisions you want this thread to yield?

**Comment by liangfok** [comment]
Suggested success criteria: Drake successfully compiles and runs 100% of the time assuming users follow the [system configuration requirements](http://drake.mit.edu/developers.html#supported-configurations) and [installation instructions](http://drake.mit.edu/installation.html) to a T.

**Comment by liangfok** [comment]
Suggested secondary success criteria: 100% of users can compile and run Drake without installing any proprietary or code with viral licenses.

**Comment by david-german-tri** [comment]
friendly ping to @RussTedrake re. https://github.com/RobotLocomotion/drake/issues/1939#issuecomment-221438529

**Comment by jwnimmer-tri** [comment]
I wonder if we should just close this issue?

**Comment by david-german-tri** [comment]
I believe we should close this issue, yes.  The relationship to external dependencies will be more explicit and clear in Bazel, and we've already agreed that the supported, CI-tested modes will be fewer: "open source" and "everything".
