### ISSUE TITLE
Improve on the accuracy of the contact and collision engine

### ISSUE THREAD

**Issue by amcastro-tri** [RobotLocomotion/drake#1940]
I've been working with height maps in #1616 and in my last test that you can see [here](https://www.youtube.com/watch?v=BOGBV8s14GQ) I get very unphysical results when a ball collides with a height map in an angle. 

I therefore made a simpler test of a ball bouncing on an inclined plane at 45 degrees. An analytical solution is available in this case. No friction, no damping. Second order RK. No multi-contact. You can see an animation [here](https://www.youtube.com/watch?v=2T47WVrhBFk).

![inclined_plane_vs_ball](https://cloud.githubusercontent.com/assets/17601461/14045387/39052dea-f270-11e5-8fcd-cc793b4043c1.png)

As you can see the physics is also wrong in this simple example with convex objects (using Drake's original implementation).

**Comment by amcastro-tri** [comment]
This is my plan for the upcoming days:

1. Submit a pull request with the height map implementation for #1616 
2. Work on a solution to handle concave objects for #1616. Using Bullet's collision dispatcher is an option.
3. Analyze this new issue #1940 to understand what collision forces act on the sphere and why. Solve it.

**Comment by amcastro-tri** [comment]
We talked this morning with @david-german-tri about #1933 which relates to this issue and #1616. We agreed on taking the following path:
1. @david-german-tri will work an a purely Drake solution to filtering collisions using [`RigidBody::collidesWith`](https://github.com/RobotLocomotion/drake/blob/master/drake/systems/plants/RigidBody.h#L65).
2. I'll work myself with Bullet's dispatcher to handle also concave shapes
3. Hopefully @david-german-tri will be able to expand on my work to use Bullet's filters in the future.

**Comment by sherm1** [comment]
The sideways bounce looks like a coordinate frame mixup. One talk I could give while I'm out in Boston (Apr 6-12) is how to write frame-intensive code using notation that makes it (almost) impossible to make mistakes. Hint: if transform is named "transform" or "pose" or "world2link" it is probably going to be wrong!

**Comment by amcastro-tri** [comment]
Yes, that's a good observation. I always wondered what a good notation for this kind of things would be in code. I really liked the notation I found in [this](https://www.cs.ubc.ca/grads/resources/thesis/Nov02/Michael_Cline.pdf) thesis by Bradley Cline and I use it since. But this notation really useful in paper does not translate well to code variable names. 
Looking forward to your talk!
