### ISSUE TITLE
Add macOS build to pull request triggers

### ISSUE THREAD

**Issue by jwnimmer-tri** [RobotLocomotion/drake#19472]
**Is your feature request related to a problem? Please describe.**

Occasionally, we'll have code that builds and passes all tests on Ubuntu, but then fails on macOS.  Sometimes we won't notice this until after the pull request has merged and a `Continuous` job fails to build or fails to pass some new test, which means that the buildcop needs to put on their uniform and triage the situation, costing us time and money.

**Describe the solution you'd like**

I'd like to have macOS results available pre-merge, so that we can avoid merging broken pull requests.

I think the best way to try doing that is to add `mac-arm-ventura-clang-bazel-experimental-release` to the pull request triggers.

In the initial version, we would not mark it as `Required` in GitHub.  Rather, it would be informational-only.  This guards against the hazard that it's too slow or too broken; we don't want to interrupt the pull request flow on a rainy day; we just want the helpful "unit test has failed" information available for developers to respond to on a sunny day.

**Describe alternatives you've considered**

The CI machine load might be too much.  In that case, we could imagine using the `configuration: mac` label to mark PRs that want mac testing, or `configuration: linux` to mark those that don't, in order to more optimally portion out build minutes.

**Additional context**

I vaguely recall that we might end up needing an Orka plugin for this?  Because the current plugin doesn't cancel jobs for old pushes when a new push happens?  In any case we could try it even with that misfeature. Maybe it's not too bad.

**Comment by BetsyMcPhail** [comment]
The drake-jenkins PR is ready, we probably need to coordinate deploying the changes to Jenkins and updating Github.

**Comment by BetsyMcPhail** [comment]
This change has been deployed to Jenkins. Closing the issue for now, we can reopen if needed.
