### ISSUE TITLE
Why Meldis visualizer is freezing during simulation? 

### ISSUE THREAD

**Issue by dvogureckiy99** [RobotLocomotion/drake#19471]
### What happened?

I trying run `deformablesdrake/deformable_torus.ipynb` project, but when I am running `python3 -m pydrake.visualization.meldis` Meldis visualizer it's freezing during simulation, during `simulator.AdvanceTo(simulation_time)`.

### P.S.
I checked my GPU/CPU stat and it showed me that only 80% was used by GPU and only 1/4 cores of my CPU cores is 100%, while others lower. 

### Version

the last source from git

### What operating system are you using?

Ubuntu 20.04

### What installation option are you using?

compiled from source code using CMake

### Relevant code
```
import numpy as np

from pydrake.all import *
```
```
# Desired duration of the simulation [s].
simulation_time = 15.0
# Desired real time rate.
realtime_rate = 1.0
# Discrete time step for the system [s]. Must be positive.
time_step = 1e-2
# Young's modulus of the deformable body [Pa].
E = 5e3
# Poisson's ratio of the deformable body, unitless.
nu = 0.4
# Mass density of the deformable body [kg/m³].
density = 8e2
# Stiffness damping coefficient for the deformable body [1/s].
beta = 0.001
```
```
def run_demo():
    builder = DiagramBuilder()

    plant_config = MultibodyPlantConfig()
    plant_config.time_step = time_step
    # Deformable simulation only works with SAP solver.
    plant_config.discrete_contact_solver = "sap"

    plant, scene_graph = AddMultibodyPlant(plant_config, builder)

    # Minimum required proximity properties for rigid bodies to interact with
    # deformable bodies.
    # 1. A valid Coulomb friction coefficient, and
    # 2. A resolution hint. (Rigid bodies need to be tesselated so that collision
    # queries can be performed against deformable geometries.)
    rigid_proximity_props = ProximityProperties()
    # Set the friction coefficient close to that of rubber against rubber.
    surface_friction = CoulombFriction(1.15, 1.15)
    rigid_proximity_props.AddProperty("hydroelastic",
                                      "resolution_hint", 1.0)
    AddContactMaterial(friction = surface_friction,
                       properties = rigid_proximity_props)
    
    # Set up the ground.
    ground = Box(4, 4, 4)
    X_WG = RigidTransform(RotationMatrix(), [0, 0, -2])
    plant.RegisterCollisionGeometry(plant.world_body(), X_WG, ground,
                                    "ground_collision", rigid_proximity_props)
    
    plant.RegisterVisualGeometry(plant.world_body(), X_WG, ground,
                                 "ground_visual", [0.7, 0.5, 0.4, 0.8])

    # TODO: Add gripper

    # Set up a deformable torus.
    owned_deformable_model = DeformableModel(plant)

    deformable_config = DeformableBodyConfig()
    deformable_config.set_youngs_modulus(E)
    deformable_config.set_poissons_ratio(nu)
    deformable_config.set_mass_density(density)
    deformable_config.set_stiffness_damping_coefficient(beta)

    # Load the geometry and scale it down to 65% (to showcase the scaling
    # capability and to make the torus suitable for grasping by the gripper).
    scale = 4
    torus_mesh = Mesh("./torus.vtk", scale)
    # Minor diameter of the torus inferred from the vtk file.
    kL = 0.09 * scale
    # Set the initial pose of the torus such that its bottom face is touching the
    # ground.
    X_WB = RigidTransform(RotationMatrix(), [0, 0, kL/2+kL*10])
    torus_instance = GeometryInstance(X_WB, torus_mesh, "deformable_torus")

    # Minimumly required proximity properties for deformable bodies:
    # A valid Coulomb friction coefficient.
    deformable_proximity_props = ProximityProperties()
    AddContactMaterial(friction = surface_friction,
                       properties = deformable_proximity_props)
    torus_instance.set_proximity_properties(deformable_proximity_props)

    # Registration of all deformable geometries ostensibly requires a resolution
    # hint parameter that dictates how the shape is tesselated. In the case of a
    # `Mesh` shape, the resolution hint is unused because the shape is already
    # tessellated.
    # Though unused, we still asserts the resolution hint is positive.
    unused_resolution_hint = 1.0
    owned_deformable_model.RegisterDeformableBody(
        torus_instance, deformable_config, unused_resolution_hint)

    plant.AddPhysicalModel(owned_deformable_model)

    deformable_model = owned_deformable_model

    # All rigid and deformable models have been added. Finalize the plant.
    plant.Finalize()

    # It's essential to connect the vertex position port in DeformableModel to
    # the source configuration port in SceneGraph when deformable bodies are
    # present in the plant.
    builder.Connect(
        deformable_model.vertex_positions_port(),
        scene_graph.get_source_configuration_port(plant.get_source_id()));
    
    # meshcat = Meshcat()
    # vis = MeshcatVisualizer.AddToBuilder(builder, scene_graph, meshcat)
    DrakeVisualizer().AddToBuilder(builder, scene_graph)

    diagram = builder.Build()
    diagram_context = diagram.CreateDefaultContext()
    simulator = Simulator(diagram)
    simulator.Initialize()
    simulator.set_target_realtime_rate(realtime_rate)

    print("deformable_model.num_bodies()= %d"%deformable_model.num_bodies())

    # vis.StartRecording()
    # simulator.AdvanceTo(simulation_time)
    # vis.StopRecording()
    
    # import time
    # while True:
    #     vis.PublishRecording()
    #     time.sleep(simulation_time)
    while 1:
        simulator.AdvanceTo(simulation_time)

run_demo()
```

**Comment by xuchenhan-tri** [comment]
There is no `deformable_torus.ipynb` in Drake but I assume the thing you are running is the python script provided in the issue.

I was able to run the script you provided locally (not in a notebook) just fine. Meldis is able to visualize a deformable torus dropped from height and lands on a rigid body weld to the world and jiggles.

Could you describe in more details of what you mean by "freezing"? The `while 1` loop looks a bit suspicious to me and it might not do what you intend to do. To be clear, this doesn't put the simulation in a loop. The expected effect is that the simulation runs to time `simulation_time` and stops there.

**Comment by dvogureckiy99** [comment]
@xuchenhan-tri 
1. I converted this script from `.ipynb` to `.py`
2. Deleted `while 1` loop.
3. and runned it locally, but the problem remains the same: 
during the simulation, my cursor freezes and any commands from the periphery are not processed, after a couple of seconds everything is defrosted, but at the same time the simulation continues not from the moment of hanging, but after a few seconds. 
If it were possible to loop the simulation in Meldis, then this problem would be solved, since freezes after a few seconds pass.

**Comment by xuchenhan-tri** [comment]
> In Meshcat I solved this problem by looping simulation

Is it true that the freezing also happens when you run Meshcat with a rigid body simulation?

This sounds to me like a Meshcat issue more than a deformable body simulation issue.

**Comment by dvogureckiy99** [comment]
@xuchenhan-tri 

Yes, it is freezing even with the rigid bodies.

**Comment by jwnimmer-tri** [comment]
Okay, that sounds like a problem particular to your computer.  We do not see any freezing when we run these things.

For us to help with fixing it, ideally we would be able to reproduce the problem.  Is there anything you can think of about your computer that might be unique, that we could try to replicate on our side?  A particular web browser product or version?  Running in a virtual machine?  Discrete graphics card versus built-in Intel graphics?

Also, please try running in a private window (so that all browser extensions and add-ons are disabled).

**Comment by dvogureckiy99** [comment]
@jwnimmer-tri 
Thank you.
I am using:
Mozilla Firefox for ubuntu 113.0.2 (64-bit)
Running on nonvirtual machine Ubuntu 20.04
Discrete graphic card NVIDIA GeForce 920MX

 I tried run in a private window, but freezing the same as before.

**Comment by jwnimmer-tri** [comment]
Hm.  We have similar things here with no trouble.

We are usually Ubuntu 22 (not 20), but it is unlikely that Ubuntu version is related to the problem though so I'm not worried about that part.

I suggest:

(1) Make sure the nvidia drivers are installed correctly from Ubuntu, e.g., something like one of these is installed:
https://packages.ubuntu.com/focal/nvidia-driver-525
or
https://packages.ubuntu.com/focal/nvidia-driver-530

We don't typically run using https://packages.ubuntu.com/jammy/xserver-xorg-video-nouveau so if you are using Nouveau that might be related to the problem.

(2) Make sure that you have rebooted in case the driver has been upgraded recently (even in the background by auto-update).

**Comment by dvogureckiy99** [comment]
@jwnimmer-tri  yes, I am using Nouveau, but how to solve this ?

**Comment by dvogureckiy99** [comment]
I tried today run this file on GPU GeForce RTX 3080 and it turns out simulating without freezing.

**Comment by jwnimmer-tri** [comment]
I don't think there's much we can do to debug computer-specific problems.

We are open to pull requests if anyone whose computer is struggling can figure out the root cause and provide a solution.
