### ISSUE TITLE
Upgrade Externals June 2023

### ISSUE THREAD

**Issue by BetsyMcPhail** [RobotLocomotion/drake#19511]
Follow [Semi-automated monthly upgrades](https://github.com/RobotLocomotion/drake/blob/master/tools/workspace/README.md#semi-automated-monthly-upgrades) documentation.

- [x] #19536
- [x] #19537
- [x] #19538
- [x] #19539
- [x] #19540

Note: Per https://github.com/RobotLocomotion/drake/blob/master/tools/workspace/qdldl_internal/README.md, QDLDL *may* be skipped because SCS has not changed, and OSQP is still using the same version as far as I can tell. (However, the OSQP ran into problems; if that wishes to also update QDLDL, that would be acceptable, but at any rate, it won't be done as part of the main PR.)

Prior issue (May 2023): #19319

**Comment by jwnimmer-tri** [comment]
All the PRs have landed.
