### ISSUE TITLE
[PR:1949]compilation error

### ISSUE THREAD

**Issue by RussTedrake** [RobotLocomotion/drake#1956]
looks like you missed removing these lines...
```
#ifndef DRAKE_DRAKEMEXFUNCTIONS_H
```

**Comment by jwnimmer-tri** [comment]
And second question.... what did I do wrong do not see this locally?  Possibly by not having matlab enabled?

**Comment by RussTedrake** [comment]
correct.  that would not compile w/o matlab.  didn't realize that gitcolony would create a github issue for my comment!
