### ISSUE TITLE
Visual Studio solution doesn't include header files

### ISSUE THREAD

**Issue by sherm1** [RobotLocomotion/drake#1963]
I'm using a CMake-generated solution file in Visual Studio 2015 IDE. Doing "Find in Files" for the "Entire Solution" returns matches in `.cc` and `.cpp` files, but nothing in header files.

In other CMake-built projects I've worked on, the "Entire Solution" find includes both source and headers, so I think the Drake `CMakeLists.txt` is missing something.

**Comment by billhoffman** [comment]
The .h files need to be added to the source lists of the targets.  They will be ignored by generators that do not use them.  Drake does not seem to be doing that. https://github.com/RobotLocomotion/drake/blob/master/drake/solvers/CMakeLists.txt#L36

**Comment by sherm1** [comment]
@billhoffman, any progress on this? It is hard to get around in the IDE without it. Can header dependencies be generated automatically somehow? It doesn't seem maintainable to list the explicitly.

**Comment by david-german-tri** [comment]
Windows is no longer supported.
