### ISSUE TITLE
Opt-in to -Werror=unqualified-std-cast-call

### ISSUE THREAD

**Issue by jwnimmer-tri** [RobotLocomotion/drake#19646]
Newer versions of Apple Clang have `-Wunqualified-std-cast-call` on by default.  We should promote that to an error so that we don't accidentally ignore those warnings.

See https://github.com/RobotLocomotion/drake/pull/19380#issuecomment-1600727997 for discussion and ideas on the solution.

**Comment by svenevs** [comment]
```
clang -dM -E - < /dev/null

XCode 14.1
#define __apple_build_version__ 14000029
#define __clang_version__ "14.0.0 (clang-1400.0.29.202)"

XCode 14.3
#define __apple_build_version__ 14030022
#define __clang_version__ "14.0.3 (clang-1403.0.22.14.1)"
```

dumping this before closing the editor on that computer, will tackle this soon

**Comment by svenevs** [comment]
The thing that blocked us was version detection for Xcode.  We have now upgraded past this, and should be able to add this flag unconditionally to the xcode builds without doing the version detection.

**Comment by jwnimmer-tri** [comment]
I think our Ubuntu Clang 15 have this now too, which should make this even easier.
