### ISSUE TITLE
Drake Wiki is Missing a Page Listing All Platforms Supported

### ISSUE THREAD

**Issue by liangfok** [RobotLocomotion/drake#1968]
PR https://github.com/RobotLocomotion/drake/pull/1967 contains the phrase "all platforms supported by Drake". We should add a page on Drake's wiki that aggregates details about all of these platforms.

This issue goes beyond https://github.com/RobotLocomotion/drake/issues/1923 by requiring that the supported configurations be officially documented on the wiki.

**Comment by RussTedrake** [comment]
duplicate of #1923
