### ISSUE TITLE
[pydrake] Disable spdlog redirection when using multithreaded C++ code?

### ISSUE THREAD

**Issue by EricCousineau-TRI** [RobotLocomotion/drake#19680]
**Is your feature request related to a problem? Please describe.**
I am writing Python bindings in a downstream project (Anzu) that does work in a multithreaded fashion, and calls `drake::log()->info()`, `->debug()`, `->trace()`, etc., in those separate threads.

Even though this code doesn't explicitly call Python code in those other threads (e.g. not via `std::function<>` or C++ <-> Python polymorphism), it still seemed to deadlock.

If I commented out this line, my multithreaded code seemed to work fine:
https://github.com/RobotLocomotion/drake/blob/b9813a712454580cd6bc0724f8d2506d85412e58/bindings/pydrake/common/module_py.cc#L103

**Describe the solution you'd like**
Perhaps an environment variable, like `PYDRAKE_NO_SPDLOG_REDIRECT`, or a function to call from pydrake that undoes the effects of `MaybeRedirectPythonLogging()` and related methods.

**Describe alternatives you've considered**
(1) Writing a C++ pybind11 module as follows, then importing it before `pydrake`, fixes the "seems to deadlock" issue:
https://gist.github.com/EricCousineau-TRI/ff52a8e3be0ca5fd085307c16ff09dbc

(2) Set spdlog's debugging level such that no messages are printed

(3) Add an option to only redirect to Python if it's the main thread. If it isn't the main thread, it should ideally emit directly to `stderr` as the nominal sink would.

**Additional context**
https://drakedevelopers.slack.com/archives/C3YB3EV5W/p1687807563590549

\cc @jwnimmer-tri @dmcconachie-tri @sammy-tri

**Comment by jwnimmer-tri** [comment]
If we end up with an environment variable, my vote to best align with [the current names](https://drake.mit.edu/doxygen_cxx/group__environment__variables.html) would be to name it starting with `DRAKE_`.

Perhaps `DRAKE_PYTHON_LOGGING`, where unset or set-to-empty means the status quo and `DRAKE_PYTHON_LOGGING=0` switches `MaybeRedirectPythonLogging()` to be a no-op.

**Comment by jwnimmer-tri** [comment]
> Perhaps an environment variable ... or a function to call from pydrake that undoes the effects of MaybeRedirectPythonLogging ...

Either (or both) of those features sound fine to me.  The environment variable is probably the easier one to implement, but the undo function would probably cover more use cases.

**Comment by jwnimmer-tri** [comment]
> ... undoes the effects of MaybeRedirectPythonLogging ...

Even before a Drake feature that encapsulates this, I think end-users can accomplish it already:

```c++
// Remove the pylogging_sink (if it exists).
drake::log()->sinks().resize(1);

// Use only the stderr sink.
dynamic_pointer_cast_or_throw<spdlog::sinks::dist_sink_mt>(drake::get_dist_sink())->set_sinks({
  std::make_shared<spdlog::sinks::stderr_sink_mt>()});
```
