### ISSUE TITLE
Upgrade Externals July 2023

### ISSUE THREAD

**Issue by jwnimmer-tri** [RobotLocomotion/drake#19715]
Follow [Semi-automated monthly upgrades](https://github.com/RobotLocomotion/drake/blob/master/tools/workspace/README.md#semi-automated-monthly-upgrades) documentation.

Prior issue (June 2023): #19511

- [x] #19773
- [ ] #19775 
- [x] #19776
- [ ] #19777
- [x] #19778
- [ ] `common_robotics_utilities` and `voxelized_geometry_tools` are upgraded in #19729

**Comment by BetsyMcPhail** [comment]
All upgrades either are complete or have their own issue. The work for this issue is complete.
