### ISSUE TITLE
LoadModelDirectives gives unhelpful message when one forgets the "directives:"

### ISSUE THREAD

**Issue by RussTedrake** [RobotLocomotion/drake#19725]
I often write model directives directly in my code:  e.g.
```
      model_directives = R"""( 
directives:

# Add shelves
- add_model:
    name: shelves
    file: package://gcs/models/shelves/shelves.sdf
...
)""";
      parser.AddModelsFromString(model_directives, ".dmd.yaml");
```
One time I forgot to add the `directives:` signature at the top... an honest mistake!  I was rewarded with the output:
```
abort: Failure at common/yaml/yaml_read_archive.cc:270 in MaybeGetSubNode(): condition 'root_->IsMapping()' failed.)
```

I had to step into the debugger to figure out what I had done wrong. 

Request: Drake provides a more helpful error message for this case.

**Comment by rpoyner-tri** [comment]
@jwnimmer-tri are you interested in taking this one?
