### ISSUE TITLE
DependencyTracker::NotifySubscribers is extremely expensive

### ISSUE THREAD

**Issue by pierricgimmig** [RobotLocomotion/drake#19759]
### What happened?

Around 10% of our "AdvanceTo" call is spent in deep recursive calls to `DependencyTracker::NotifySubscribers`, which is by far the most expensive function in the Drake simulation for our use case, more so than any of the actual core math/physics functions in the simulation.

![image](https://github.com/RobotLocomotion/drake/assets/3687222/bd352872-7b18-449c-aee1-eda6f2ea04cd)

![image](https://github.com/RobotLocomotion/drake/assets/3687222/438fef2e-2b62-456e-9a0f-20fe3b28bfa7)

Is there a way to make this faster?

### Version

1.17.0

### What operating system are you using?

Ubuntu 22.04

### What installation option are you using?

compiled from source code using Bazel

**Comment by sherm1** [comment]
I would note that 90% of your simulation time is _not_ dependency notification so even if the cost were 0 you'd run only 10% faster. That said, I do think we can reduce that substantially -- #9261 laid out some possible speedups that we haven't pursued. Might be time!

BTW it would be helpful to have a relevant benchmark. Can you provide yours or describe the structure? It's unusual to see such a long chain of dependencies.

**Comment by jwnimmer-tri** [comment]
FWIW, sometimes I've seen too much invalidation happen when System(s) fail to declare the dependency tickets of their ports, e.g., if an output port doesn't depend on some or all inputs, or only depends on discrete state but not continuous state, etc., it can help to set `prerequisites_of_calc` to something other than "all sources".

**Comment by jwnimmer-tri** [comment]
We won't be able to do anything here unless you can provide a reproduction recipe for this bug.  We're not going to try to guess what you're doing that results in slowness.

**Comment by pierricgimmig** [comment]
> We won't be able to do anything here unless you can provide a reproduction recipe for this bug. We're not going to try to guess what you're doing that results in slowness.

I totally understand. I'll try to find a public Drake scene that exhibits the same behavior.

**Comment by jwnimmer-tri** [comment]
We just landed #21134, which might happen to help here.  In any case, until we have some kind of outline of the situation that's slow, there's no action we can take here for now.  Closing as "not planned", pending more information.

**Comment by pierricgimmig** [comment]
Thanks for the heads up, we'll try it out on our side, and update here. Cheers!
