### ISSUE TITLE
System::Clone has incorrect SystemIDs for the ports

### ISSUE THREAD

**Issue by RussTedrake** [RobotLocomotion/drake#19758]
### What happened?

Initially reported by @AlexandreAmice ... the following test
```
GTEST_TEST(PendulumPlantTest, Clone) {
  const PendulumPlant<double> plant;
  auto clone = plant.Clone();
  auto context = clone->CreateDefaultContext();
  clone->get_input_port(0).FixValue(context.get(), Vector1d::Zero());
}
```
fails with 
```
C++ exception with description "InputPort: The Context given as an argument was not created for this InputPort[0] (tau) of System ::_ (PendulumPlant<double>)" thrown in the test body.
```

Digging around in lldb (with a breakpoint on the last line), I see
```
(lldb) p plant.get_system_id()
(drake::systems::internal::SystemId) $5 = (value_ = 6)
(lldb) p clone->get_system_id()
(drake::systems::internal::SystemId) $6 = (value_ = 9)
(lldb) p plant.CreateDefaultContext()->get_system_id()
(drake::systems::internal::SystemId) $7 = (value_ = 6)
(lldb) p clone.CreateDefaultContext()->get_system_id()
(drake::systems::internal::SystemId) $8 = (value_ = 9)
(lldb) p clone->CreateDefaultContext()->get_system_id()
(drake::systems::internal::SystemId) $11 = (value_ = 9)
(lldb) p clone->get_input_port(0).owning_system_id_
(const drake::systems::internal::SystemId) $12 = (value_ = 8)
```

Stepping into the code, I believe that the problem probably happens [here](https://github.com/RobotLocomotion/drake/blob/8b25bb8cd378802e1b819d66b4fba724d4b2fcc9/systems/framework/system.cc#L42).... it looks like the system's ID gets reset, but the port's IDs do not.

**Comment by sherm1** [comment]
Looks like first transmogrify bumped the id to 7, next one to 8. Most likely those battle-tested steps update all the ids correctly. Then the cloning code does a final bump of the system ID to 9. Maybe that last bump isn't necessary?

**Comment by jwnimmer-tri** [comment]
My recollection is that I wrote the `result->ResetSystemId();` code because I was under the impression that scalar conversion kept the SystemId intact, but for sure we need the Clone to report a different ID.  If the scalar conversion is already bumping the ID each time, we can probably nuke the `ResetSystemId` entirely.
