### ISSUE TITLE
Add visualization of triads to Meldis

### ISSUE THREAD

**Issue by AdityaBhat-TRI** [RobotLocomotion/drake#19811]
**Is your feature request related to a problem? Please describe.**
As of now, it's not easy to visualize frames in Meldis. Restoring this feature (which was once a part of drake visualizer) is important now as it becomes very difficult to visualize the frame transforms in simulation.  

**Describe the solution you'd like**
Restore the feature of visualization of frames (similar to the drake visualizer).

**Comment by jwnimmer-tri** [comment]
Adding some cross references / search keywords:
- Slack thread: https://app.slack.com/client/T0JNB2DS4/C43KX47A9/thread/C43KX47A9-1686755592.829789
- LCM channel name: `DRAKE_DRAW_FRAMES*`.

**Comment by AdityaBhat-TRI** [comment]
PR in https://reviewable.io/reviews/RobotLocomotion/drake/19848

**Comment by jwnimmer-tri** [comment]
Fixed in #19848.
