### ISSUE TITLE
Port hydroelastic examples to meldis and/or meshcat

### ISSUE THREAD

**Issue by jwnimmer-tri** [RobotLocomotion/drake#19870]
This is a follow-up from #16216, and relates to #18913.

These four demos still claim to require `//tools:drake_visualizer` and its hydroelastic plug-ins:
- `example/hydroelastic/python_ball_paddle`
- `example/hydroelastic/python_nonconvex_mesh`
- `examples/hydroelastic/spatula_slip_control`
- `examples/hydroelastic/ball_plate`

We need to port them to use Meshcat or Meldis (or both).

Where possible, we should also update them to use `AddDefaultVisualization` (ala #17687) instead of copy-pasted setup code.

If there are missing visualization features that stand in the way of the porting, we should itemize those here.

**Comment by jwnimmer-tri** [comment]
Reminder: Some of the `--help` strings also encode details about `drake_visualizer`.  Those should also be fixed along with the README files.

**Comment by jwnimmer-tri** [comment]
In #20175, I've fixed the `ball_plate`.  It seems like Meldis works fine now.  I'll follow up and fix the rest, later on.

**Comment by DamrongGuoy** [comment]
The `examples/hydroelastic/spatula_slip_control` uses Meshcat already. Its README instructs users to use `http://localhost:7000/`.  I think now we have two examples left:

- `example/hydroelastic/python_ball_paddle`
- `example/hydroelastic/python_nonconvex_mesh`

I'm experimenting with `example/hydroelastic/python_nonconvex_mesh` in draft PR #20220

**Comment by jwnimmer-tri** [comment]
The `spatula_slip_control` still has this in its README:

```
**WARNING**: According to issue
[17681](https://github.com/RobotLocomotion/drake/issues/17681),
only the legacy `//tools:drake_visualizer` application of days past, not
MeshCat nor meldis, can draw wireframe of the contact surfaces.
As a result, you will need `//tools:drake_visualizer` to visualize the 
difference between the `triangle` option and the default `polygon` option.
However, `//tools:drake_visualizer` is only available in the older
Ubuntu Focal, not Jammy.
```

This ticket was intended to also encompass fixing the documentation such as READMEs, gflags help strings, etc.
