### ISSUE TITLE
Support "SetCameraTarget" in Meshcat

### ISSUE THREAD

**Issue by RussTedrake** [RobotLocomotion/drake#19885]
[Meshcat supports a `set_target`](https://github.com/rdeits/meshcat/blob/master/Readme.md) command for setting "the target of the 3D camera, around which it rotates."  We should add this support to Drake's Meshcat c++.

Requested by @pathammer .

**Comment by cohnt** [comment]
I would also be an eager user of such a feature

**Comment by SeanCurtis-TRI** [comment]
I'm going to grab this and knock out the PR. Stay tuned.

(This is under the assumption that no one else has started...let me know if I'm wrong.)

**Comment by SeanCurtis-TRI** [comment]
For those interested, the PR is now in flight.
