### ISSUE TITLE
Windows Installation Instructions Require Refinement

### ISSUE THREAD

**Issue by liangfok** [RobotLocomotion/drake#1991]
The [Windows installation instructions](http://drake002.csail.mit.edu/drake/sphinx/windows.html) omit some details that may confuse a newbie like myself (I haven't developed software on Windows in 5 years). Below are my working notes on additional details that should be added to the Windows install instructions. _Note that some of the details below may be incorrect since I haven't gotten the unit tests to pass yet!_

# Visual Studio - Custom Install

The default installation options are insufficient. Instead, select custom install, then select Programming Languages, Visual C++ as shown below. Without this, the C++ compiler will not be available.

![visual_studio_select_cpp_features](https://cloud.githubusercontent.com/assets/1388098/14230754/f8fe6bfc-f932-11e5-94d7-dae563125d34.png)

# CMake Options

When executing `make options` for the first time, the CMake Options GUI will show up but be blank, as shown below.

![cmake_gui_blank](https://cloud.githubusercontent.com/assets/1388098/14230772/8cb6e68a-f933-11e5-82a6-37598edd1de8.png)

Towards the top of the GUI, there are two fields labeled "Where is the source code" and "Where to build the libraries". Manually enter the following

* Where is the source code: `[path to drake distro]`
* Where to build the libraries: `[path to drake distro]/pod-build`

![cmake_gui_dirs](https://cloud.githubusercontent.com/assets/1388098/14230773/9047adb6-f933-11e5-9594-701635cdf9e5.png)

**Comment by david-german-tri** [comment]
Windows is no longer supported.
