### ISSUE TITLE
Design numerical accuracy tests for rigid body simulation

### ISSUE THREAD

**Issue by RussTedrake** [RobotLocomotion/drake#1993]
What are the right tests?  Don't need contact at first -- how about something as simple as an undamped pendulum (or multi-link pendulum) that preserves it's total energy?

These should be good forcing functions for getting the best integrations schemes going in the c++ code

**Comment by sherm1** [comment]
First thought: I would partition these into three categories:
- tests of the rigid body model
- tests of numerical integrators
- tests of known-good integrators applied to known-good rigid body models

Error controlled integrators are notorious for covering up errors in rigid body models, especially when there are constraints involved. And symplectic integrators are awesome at conserving energy while producing terrible answers.

**Comment by tri-ltyyu** [comment]
Per issue scrub, we have many tests for rigid body model, numerical integrator, etc. Closing this as tests will be done ongoing basis.
