### ISSUE TITLE
Setting GCC default to 4.9

### ISSUE THREAD

**Issue by peteflorence** [RobotLocomotion/drake#1996]
Going through new Ubuntu build instructions, http://drake002.csail.mit.edu/drake/sphinx/ubuntu.html

Think we need a line that ensures switching default over to GCC 4.9, I'm getting message below,. `gcc -v` says I am still on 4.8.5

I'll look up a fix.  Also is the Sphinx documentation in git somewhere, and can I contribute to that directly?

peteflo@peteflo:~/drake-distro$ env CXX=g++-4.9 CC=gcc-4.9 make options
Configuring with CMAKE_FLAGS: -DCMAKE_BUILD_TYPE=Release
CMake Error at CMakeLists.txt:5 (message):
  GCC version must be at least 4.9

-- Configuring incomplete, errors occurred!
See also "/home/peteflo/drake-distro/pod-build/CMakeFiles/CMakeOutput.log".
make: *** [configure] Error 1

**Comment by liangfok** [comment]
Yes, the Sphinx documentation is in [drake/doc](https://github.com/RobotLocomotion/drake/tree/master/drake/doc).

**Comment by peteflorence** [comment]
Thanks @liangfok

**Comment by jwnimmer-tri** [comment]
I believe the instructions are correct?  Did you install `g++-4.9-multilib`?  What does `g++-4.9 --version` report on the command line (without CMake or make involved)?

**Comment by peteflorence** [comment]
Problem solved, thanks @patmarion . I had run `make` once prior to to going through platform-specific instructions.  `rm -rf pod-build` fixed my problem, it must have been cached on 4.8.5

**Comment by jwnimmer-tri** [comment]
Aha! Another vote for #1973's pending tip of:
 - _The build system isn't working? `git clean -fdx` from orbit, it's the only way to be sure_.
