### ISSUE TITLE
matlab unit test missing dependency logic should move out matlab and into cmake

### ISSUE THREAD

**Issue by RussTedrake** [RobotLocomotion/drake#1997]
right now every test runs, fires up matlab, and then returns "PASS" if the missing dependency is caught by the matlab code.  we should instead simply not run those tests.

once this is resolved, we should aim to get rid of the custom add_matlab_test script in favor of using
https://github.com/Kitware/CMake/blob/master/Modules/FindMatlab.cmake#L754

**Comment by jamiesnape** [comment]
Taking this on as it will speed up CI builds (especially OS X)  if we do not have to startup MATLAB only to find we do not have the dependencies.

**Comment by jamiesnape** [comment]
This was fixed quite some time ago.
