### ISSUE TITLE
Upstream FindMatlab to CMake from drake, the drake one is now running all the Matlab tests

### ISSUE THREAD

**Issue by RussTedrake** [RobotLocomotion/drake#1998]
as discussed in #1992

**Comment by billhoffman** [comment]
The FindMatlab in CMake has a matlab_add_unit_test that looks good and handles the same thing as the perl script here:
https://github.com/Kitware/CMake/blob/master/Modules/MatlabTestsRedirect.cmake

https://github.com/Kitware/CMake/blob/master/Modules/FindMatlab.cmake#L727

It would be good to use this, and we could copy the module into drake with some guards to remind us to remove it when we require a new enough cmake by default.  It would be good to contribute any changes back to CMake.  But, the code looks good from a read.

**Comment by jamiesnape** [comment]
@billhoffman Can this be closed or is there more to do?

**Comment by billhoffman** [comment]
This is working, but I am leaving the issue open because it still needs to be upstreamed in CMake.

**Comment by billhoffman** [comment]
This has now been done.  Drake will use the new one when a 3.7 cmake is used on drake.
