### ISSUE TITLE
Magic "retest this please" is confusing; recommend "jenkins: retest this please" or similar.

### ISSUE THREAD

**Issue by jwnimmer-tri** [RobotLocomotion/drake#2000]
The magic "retest this please" github comment should have a clearer referent, something like "jenkins: retest this please" (or @drake-jenkins-bot by name, perhaps?).  Just about ~everyone who sees this message on their PR for the first time thinks that they have to do something.  ("I should retest it?  How do I do that?  I already tested it.")

I am not sure if we can just change sphinx to recommend the new spelling, or if the magic glue also has to change.

**Comment by jamiesnape** [comment]
It is a non-trivial change, and our mileage may vary with the reliability of a non-standard phrase.

**Comment by jwnimmer-tri** [comment]
In that case, maybe a better solution is just adding a clearer note to the new-developer training checklist (and making sure new developers actually review it).

**Comment by jamiesnape** [comment]
So it turns out that text before and after the regex should be ignored. So we could try `jenkins test this please`, `jenkins test this please`, etc.,  without reconfiguration.

**Comment by jamiesnape** [comment]
I seem to recall it not being 100% reliable, but it does not hurt to try.

**Comment by jwnimmer-tri** [comment]
I tried it with the at-command form, and it jenkins dutifully started up: https://github.com/RobotLocomotion/drake/pull/1999#issuecomment-205535487

I will prepare a documentation PR changing the `jenkins.rst` to suggest this by default.

**Comment by jamiesnape** [comment]
`@drake-jenkins-bot test this please` is working fine, so can this be closed? I see you have a follow up ticket #1973.

**Comment by jwnimmer-tri** [comment]
Sure, it's just a doc problem now, so #1973 can cover it.

**Comment by tombroi** [comment]
retest this please
