### ISSUE TITLE
[tutorial] Offer an URDF-file hydroelastic config tutorial or example

### ISSUE THREAD

**Issue by rpoyner-tri** [RobotLocomotion/drake#20034]
**Is your feature request related to a problem? Please describe.**
There is no explicit tutorial or example showing the full range hydroelastic configuration in an **URDF** model. Russ has been feeling the lack of one.

**Describe the solution you'd like**
Write an example or tutorial that exercises and explains hydro configuration settings in an URDF model.

**Describe alternatives you've considered**
Other possibilities are: improvements to existing documentation, stricter URDF error checking (which will also happen -- see #16997). Perhaps the example/tutorial is useful independent of these.

**Additional context**
None.

**Comment by rpoyner-tri** [comment]
Motivated by a TRI-internal slack thread with Russ.

**Comment by jwnimmer-tri** [comment]
Is this tutorial good enough now?

https://github.com/RobotLocomotion/drake/blob/master/tutorials/hydroelastic_contact_nonconvex_mesh.ipynb?short_path=04b5878#L185

Or is there still work to be done here -- e.g. a parser docs improvement?

**Comment by jwnimmer-tri** [comment]
Closing for lack of response.  If @rpoyner-tri or @RussTedrake want to add more specifics about why this isn't fixed yet, feel free to re-open.
