### ISSUE TITLE
Cache server file removal windows may need to change

### ISSUE THREAD

**Issue by svenevs** [RobotLocomotion/drake#20066]
I happened to be at my computer when this crashed: https://drake-jenkins.csail.mit.edu/view/Nightly%20Production/job/linux-focal-nightly-cache-server-health-check/103/

I was able to quickly run the file removal and restore things, when the cache server windows were decided Nightlies were populating the cache.  Now we have continuous doing it.

On https://github.com/RobotLocomotion/drake-ci/blob/main/cache_server/README.md search for `8-22`.  There is at least one flaw: the disk usage monitoring cron jobs should run all day.  Right now, I don't have access to anything after 10:30pm (it was 69% full).

But I would appreciate input: do we want to just change the file removal to be running every 15 minutes for the whole day?  I think that's probably OK, related [slack discussion here](https://drakedevelopers.slack.com/archives/C270MN28G/p1689785292525009).  We went a month without issue after changing to 15 minutes, it seems like the right value, just needs to run all day.

CC @jwnimmer-tri @BetsyMcPhail

**Comment by jwnimmer-tri** [comment]
Yes, all of the `8-22` in the crontab are suspicious.  We should have a uniform rate 24 hours a day.
