### ISSUE TITLE
Drake binaries for linux/arm64

### ISSUE THREAD

**Issue by jiuguangw** [RobotLocomotion/drake#20075]
**Is your feature request related to a problem? Please describe.**

I was building a Dockerfile on my M2 Macbook Air and encountered errors on the following line (abridged):

```
FROM ros:humble-ros-base-jammy
...

RUN python -m pip install --no-cache-dir --upgrade pip==22.3.1 \
    && pip install --root-user-action=ignore --no-cache-dir --default-timeout=900 \
    drake==1.15.0 \

...
```

I verified that if I build it for linux/amd64, the Dockerfile works as expected, i.e.,:
`docker buildx build --platform linux/amd64 -t image:whatever -f Dockerfile .`

**Describe the solution you'd like**
Release wheels for `linux/arm64`

https://pypi.org/project/drake/#files

**Describe alternatives you've considered**

**Additional context**

**Comment by jwnimmer-tri** [comment]
That's for your interest!  We're already tracking this family of requests at #13514, so I'll close this issue as a duplicate.  I'll edit the summary over there to underline a new `*.whl` file as a specific request.
