### ISSUE TITLE
Upgrade Externals September 2023

### ISSUE THREAD

**Issue by jwnimmer-tri** [RobotLocomotion/drake#20108]
Follow [Semi-automated monthly upgrades](https://github.com/RobotLocomotion/drake/blob/master/tools/workspace/README.md#semi-automated-monthly-upgrades) documentation.

Prior issue (August 2023): #19865.

- [x] #20148 
- [ ] #20145 
- [ ] #20146
- [x] #20147

**Comment by BetsyMcPhail** [comment]
Everything has been updated or assigned an issue, the work for this issue is done.
