### ISSUE TITLE
GetGraphvizString segfault / ell0 not captured

### ISSUE THREAD

**Issue by richardrl** [RobotLocomotion/drake#20113]
### What happened?

```
solver = ScsSolver()

options = GraphOfConvexSetsOptions()
options.preprocessing = True
options.max_rounded_paths = 10
options.convex_relaxation = True
options.solver = solver
result = G.SolveShortestPath(start, ro_aggregation, options)
```

I am using GCS with the MakeSemidefiniteRelaxation with the above settings. I get the result, then try to display it as follow:

```
from graphviz import Source
src = Source(G.GetGraphvizString(result=result, show_slacks=False, precision=2))
```
This errors with:
`*** ValueError: GetVariableValue: ell0 is not captured by the variable_index map.
`

If I put `show_slacks=True`, I get a segfault.

If I run the above with `show_slacks=True`, I get a segfault. I'm not really sure how to reduce my code to an MVP, so I'm hoping a GCS author can comment on why `ell0` might be erroring.

 

### Version

cce6c06531d94c376b79aeef124db0ed62a4c61a

### What operating system are you using?

Ubuntu 20.04

### What installation option are you using?

compiled from source code using Bazel

**Comment by RussTedrake** [comment]
I hope it throws, not segfaults.  But I can definitely see how this could happen -- if you having rounding enabled then there might not be any slacks to display available in the program result.  I will check and fix.
