### ISSUE TITLE
Drake examples

### ISSUE THREAD

**Issue by beatsal** [RobotLocomotion/drake#2011]
I tried addpath_drake while in the drake directory but still get error; beed doing this for a day - no luck. Please help!

**Comment by RussTedrake** [comment]
you'll have to tell us more than that for help.  what error are you seeing?

**Comment by beatsal** [comment]
I am in c-users-admin-documents-matlab-drake-drake-Eigen-0.9.6-drake-examples-PlanarMonopodHopper. I key in:

>>cd PlanarMonopodHopper
>> StateMachineControl.run

I get the error:
The specified superclass 'HybridDrakeSystem' contains a parse error, cannot be found on MATLAB's search path, or is
shadowed by another file with the same name.


Kindly help.


Thanks


________________________________

**Comment by RussTedrake** [comment]
I agree that It looks like you have not successfully run addpath_drake.

**Comment by beatsal** [comment]
I did add "addpath_drake" in the drake folder, so may be something wrong in drake?


________________________________

**Comment by RussTedrake** [comment]
what was the output of addpath_drake?

**Comment by beatsal** [comment]
Yes, it was the addpath_drake command that was not working. I deleted and re-installed Drake 3 times and tried, the last time I put it in the Matlab folder and then only it worked. Maybe that should be in the install instructions or I missed it (more likely!).


I am really enjoying the course and thank you for putting together such a challenging course. The only thing missing is doing a useful project that makes use of the material learnt in the course. This could be fee-based.

Hope you will consider.


Sincerely,


Ken Dias

________________________________

**Comment by RussTedrake** [comment]
glad it works and that you're enjoying the course.

**Comment by beatsal** [comment]
Sorry to bother you but don't know whom to ask. Think there is a bug in Drake:

Ex 3.6 of text book shows 2 cases which we are asked to try out. 'Quadrotor2D' works fine and a figure of the Quad is shown but not 'Quadrotor' (3D version) where no figure appears.


Thanks,


Ken


________________________________
