### ISSUE TITLE
try using RUN_SERIAL again to enable multi-process unit tests

### ISSUE THREAD

**Issue by RussTedrake** [RobotLocomotion/drake#2012]
@billhoffman said

```
add_test(foo ....)
set_tests_properties(foo PROPERTIES RUN_SERIAL TRUE)
```

i said "pretty sure that didn’t work for me before.  (to the point that it didn’t even appear in the ctesttestfile)"

@billhoffman said:
Might be a CMake version thing.

Looks like it was fixed here:

https://gitlab.kitware.com/cmake/cmake/commit/dfdaf7019477c13be9aa330a319ca538df0ec22b

**Comment by jamiesnape** [comment]
`RUN_SERIAL` will work fine on CI and, when following the installation instructions, every platform except Ubuntu.
