### ISSUE TITLE
pointcloud_voxelization_test appears flakey on macOS

### ISSUE THREAD

**Issue by svenevs** [RobotLocomotion/drake#20133]
The test `//tools/workspace/voxelized_geometry_tools:pointcloud_voxelization_test` seems to be failing on macOS (arm64 _and_ x86_64).  CI has been happy with them for quite some time, but locally this test fails for me on any clean build.

https://github.com/RobotLocomotion/drake/commit/72c24dc29fd804017ddbf3891bfe4ba3339fe4b7

The bisect was a bit strange, there were a couple commits that if I re-ran it I could get it to fail or succeed (seemed arbitrary...).  Factoring out of https://github.com/RobotLocomotion/drake/pull/19945#pullrequestreview-1612040605

CC @jwnimmer-tri for delegation / prioritization please.

---

```
==================== Test output for @voxelized_geometry_tools//:pointcloud_voxelization_test:
[==========] Running 2 tests from 2 test suites.
[----------] Global test environment set-up.
[----------] 1 test from SerialDispatchPointCloudVoxelizationTest/PointCloudVoxelizationTestSuite
[ RUN      ] SerialDispatchPointCloudVoxelizationTest/PointCloudVoxelizationTestSuite.Test/0
# of threads = 1
Trying voxelizer [0] OpenCL - Platform name: [Apple] Vendor: [Apple] Device: [Apple M1]
Option [DISPATCH_PARALLELIZE] found, value [0]
Option [DISPATCH_NUM_THREADS] found, value [1]
Dispatch parallelism disabled
Option [OPENCL_PLATFORM_INDEX] found, value [0]
Using OpenCL Platform [0] - Name: [Apple], Vendor: [Apple]
Option [OPENCL_DEVICE_INDEX] found, value [0]
Using OpenCL Device [0] - Name: [Apple M1]
Trying voxelizer [1] CPU/async (parallel)
Option [CPU_PARALLELIZE] found, value [1]
Option [CPU_NUM_THREADS] found, value [1]
Configured parallelism using provided number of threads 1
Trying voxelizer [2] CPU (serial)
Option [CPU_PARALLELIZE] found, value [0]
Option [CPU_NUM_THREADS] found, value [1]
Parallelism disabled
Trying voxelizer [0] OpenCL - Platform name: [Apple] Vendor: [Apple] Device: [Apple M1]
Trying voxelizer [1] CPU/async (parallel)
Trying voxelizer [2] CPU (serial)
[       OK ] SerialDispatchPointCloudVoxelizationTest/PointCloudVoxelizationTestSuite.Test/0 (120 ms)
[----------] 1 test from SerialDispatchPointCloudVoxelizationTest/PointCloudVoxelizationTestSuite (120 ms total)

[----------] 1 test from ParallelDispatchPointCloudVoxelizationTest/PointCloudVoxelizationTestSuite
[ RUN      ] ParallelDispatchPointCloudVoxelizationTest/PointCloudVoxelizationTestSuite.Test/0
# of threads = 2
Trying voxelizer [0] OpenCL - Platform name: [Apple] Vendor: [Apple] Device: [Apple M1]
Option [DISPATCH_PARALLELIZE] found, value [1]
Option [DISPATCH_NUM_THREADS] found, value [2]
Configured dispatch parallelism using provided number of threads 2
Option [OPENCL_PLATFORM_INDEX] found, value [0]
Using OpenCL Platform [0] - Name: [Apple], Vendor: [Apple]
Option [OPENCL_DEVICE_INDEX] found, value [0]
Using OpenCL Device [0] - Name: [Apple M1]
external/voxelized_geometry_tools/test/pointcloud_voxelization_test.cpp:130: Failure
Expected equality of these values:
  cmap_occupancy
    Which is: 0.5
  0.0f
    Which is: 0

Trying voxelizer [1] CPU/async (parallel)
Option [CPU_PARALLELIZE] found, value [1]
Option [CPU_NUM_THREADS] found, value [2]
Configured parallelism using provided number of threads 2
Trying voxelizer [2] CPU (serial)
Option [CPU_PARALLELIZE] found, value [0]
Option [CPU_NUM_THREADS] found, value [2]
Parallelism disabled
Trying voxelizer [0] OpenCL - Platform name: [Apple] Vendor: [Apple] Device: [Apple M1]
Trying voxelizer [1] CPU/async (parallel)
Trying voxelizer [2] CPU (serial)
[  FAILED  ] ParallelDispatchPointCloudVoxelizationTest/PointCloudVoxelizationTestSuite.Test/0, where GetParam() = 4-byte object <02-00 00-00> (14 ms)
[----------] 1 test from ParallelDispatchPointCloudVoxelizationTest/PointCloudVoxelizationTestSuite (14 ms total)

[----------] Global test environment tear-down
[==========] 2 tests from 2 test suites ran. (134 ms total)
[  PASSED  ] 1 test.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] ParallelDispatchPointCloudVoxelizationTest/PointCloudVoxelizationTestSuite.Test/0, where GetParam() = 4-byte object <02-00 00-00>

 1 FAILED TEST
================================================================================
@voxelized_geometry_tools//:pointcloud_voxelization_test                 FAILED in 0.2s
  /private/var/tmp/_bazel_stephen.mcdowell/4daccd7bf83e756159958c03a09c3e0e/execroot/drake/bazel-out/darwin_arm64-opt/testlogs/external/voxelized_geometry_tools/pointcloud_voxelization_test/test.log

Executed 2 out of 7083 tests: 7082 tests pass and 1 fails locally.
```

**Comment by jwnimmer-tri** [comment]
After the CI load calms down later, my plan is to fire off a few PR test builds to see if it reproduces in CI (by setting `tags` that force it to be uncached.)

**Comment by jwnimmer-tri** [comment]
\CC @calderpg-tri FYI.  At the moment, my guess is this is a CI infra problem.  In case I get any evidence otherwise, I might ping you for more help.

**Comment by jwnimmer-tri** [comment]
Forcing the test to re-run on arm64 [passed without any problem](https://drake-jenkins.csail.mit.edu/job/mac-arm-ventura-clang-bazel-experimental-release/2155/console).   (I nerfed a bunch of unrelated stuff, so the overall job failed for other reasons, but that `PASSED` line for this test is there, green, and uncached.)

Also remember that macOS x86_64 doesn't have any remote caching, so was already running on every single [mac-x86-monterey-clang-bazel-continuous-release](https://drake-jenkins.csail.mit.edu/view/Continuous%20Production/job/mac-x86-monterey-clang-bazel-continuous-release/) since forever.

I think this problem is only that "the tests fail on @svenevs for some reason that is not captured by CI".

**Comment by svenevs** [comment]
> "the tests fail on @svenevs for some reason that is not captured by CI".

Sounds right to me.  I'm happy to just say "CI is happy" and reopen this if it resurfaces.

**Comment by calderpg-tri** [comment]
I have been able to reproduce flaky behavior in the test on my M2 machine, for both serial and parallel kernel dispatch. I haven't looked at the intermediate tracking and filter grids yet, but the nature of the test failures makes me suspect the issue has to do with kernel dispatch/sequencing - an explanation of the failures would be that the filter phase is somehow running before the raycasting phase has completed.

**Comment by calderpg-tri** [comment]
From more testing, I strongly suspect that something with the macOS implementation of `clEnqueueBuffer` is just *broken*. Looking at the pre-raycasting and post-raycasting tracking grid data, it's full of repeating garbage values that change from run to run, but generally using much of the range of an `int32_t`. If I replace the current [allocate + zero](https://github.com/ToyotaResearchInstitute/voxelized_geometry_tools/blob/master/src/voxelized_geometry_tools/opencl_voxelization_helpers.cc#L382-L407) with an allocate-as-copy buffer using zeroed host memory, everything works.
