### ISSUE TITLE
Is Ubuntu 12.04 Support Still Needed?

### ISSUE THREAD

**Issue by david-german-tri** [RobotLocomotion/drake#2015]
There are various shards of documentation related to Ubuntu 12.04 in the wiki.  Open question: does the Drake community think it's important to continue 12.04 support?  Options are:

- Leave it in the current ambiguous state
- Officially cease support for 12.04 and remove references to it
- Officially support 12.04 with CI coverage
- Your ideas here

**Comment by liangfok** [comment]
+1 for "Officially cease support for 12.04 and remove references to it"

Later this month: rapidly spin up official support for 16.04.

**Comment by jamiesnape** [comment]
> Later this month: rapidly spin up official support for 16.04.

I think we should concentrate on getting every currently supported platform fully tested with all optional dependencies on CI first. Day one support of a new OS is not realistic at present.

**Comment by patmarion** [comment]
The target platform for OpenHumanoids is Ubuntu 14.04, so with that requirement in mind I would not miss Ubuntu 12 support.

That said, I wish drake could support the default compiler on ubuntu 14... :)

**Comment by david-german-tri** [comment]
Hearing no demand for Ubuntu 12, I'm going to drop it.  Thanks all!
