### ISSUE TITLE
[examples] ManipulationStation fails when no Setup function has been called

### ISSUE THREAD

**Issue by AlexandreAmice** [RobotLocomotion/drake#20211]
### What happened?

Currently, the `ManipulationStation` documentation reads:

```
A system that represents the complete manipulation station, including exactly one robotic arm (a Kuka IIWA LWR), one gripper (a Schunk WSG 50), and anything a user might want to load into the model.
```

Additional documentation suggests that `Setup` methods are available, but does not specify that any of these methods **must** be called.

Therefore, I would expect the following code to run correctly in pydrake
```
from pydrake.examples import ManipulationStation
station = ManipulationStation(time_step=0.001)
station.Finalize()
```

Instead one receives:
```
SystemExit: Failure at examples/manipulation_station/manipulation_station.cc:580 in Finalize(): condition 'iiwa_model_.model_instance.is_valid()' failed.
```

### Version

6e741c0dd0dda93886a59b426491db09b87dcda7

### What operating system are you using?

Ubuntu 22.04

### What installation option are you using?

compiled from source code using Bazel

**Comment by Kzernobog** [comment]
I believe what `ManipulationStation` returns is a `diagram` and not a `MultibodyPlant`. You can only call `Finalize` of `MultibodyPlant` type object. The way you would use the `ManipulationStation` would be to add it as a sub-diagram in the following way.

```   
station = builder.AddSystem(
        MakeManipulationStation(model_directives=model_directives))
```
