### ISSUE TITLE
Documentation for CalcGeneralizedForces is incorrect/misleading

### ISSUE THREAD

**Issue by RussTedrake** [RobotLocomotion/drake#20244]
### What happened?

The documentation for `MultibodyPlant::CalcGeneralizedForces` says that the method computes τ = τₐₚₚ + J_WBo⋅F.  Based on the documentation just below, for `CalcGravityGeneralizedForces`, it's clear that the tau_app should not include tau_g. 
 `Mv̇ + C(q, v)v = tau_g(q) + tau_app`.  But it does.

```
from pydrake.all import MultibodyPlant, Parser, MultibodyForces, JointIndex

plant = MultibodyPlant(time_step=0)
parser = Parser(plant)
parser.AddModelsFromUrl("package://drake/examples/pendulum/Pendulum.urdf")
plant.GetJointByName("theta").set_default_damping(0)
plant.Finalize()

# Evaluate the dynamics numerically
q = [0.1]
v = [1]
context = plant.CreateDefaultContext()
plant.SetPositions(context, q)
plant.SetVelocities(context, v)
print(plant.CalcGravityGeneralizedForces(context))

forces = MultibodyForces(plant)
plant.CalcForceElementsContribution(context, forces)
print(plant.CalcGeneralizedForces(context, forces))
```
returns
```
[-0.48968291]
[-0.48968291]
```

**Comment by xuchenhan-tri** [comment]
I don't see where the inconsistency is. You are explicitly adding gravity to the external forces via `plant.CalcForceElementsContribution(context, forces)`. So we should expect to see the generalized forces resulting from `forces` to match the generalized forces resulting from gravity.
