### ISSUE TITLE
No test should demand to run with realtime performance by default

### ISSUE THREAD

**Issue by jwnimmer-tri** [RobotLocomotion/drake#2024]
By default, no test should run in realtime by when invoked by CTest -- the developer's computer may not be very fast (may be virtualized), and/or CI may not be very fast.

In #1920, we fixed this for one test, but there are least several more:
 - [ ] examples/Pendulum/runDynamics.cpp:33:  options.realtime_factor = 1.0;
 - [ ] examples/Pendulum/runEnergyShaping.cpp:36:    options.realtime_factor = 1.0;
 - [ ] examples/Pendulum/runLQR.cpp:35:  options.realtime_factor = 1.0;
 - [ ] examples/Quadrotor/runLQR.cpp:42:  options.realtime_factor = 1.0;

Once I figure out better things to grep for, I may find more examples.

Given the extent of the problem, the solution in #1920 likely should be factored out into a helper, rather than copy-pasted everywhere.

Example failure under OS X CI:
https://drake-jenkins.csail.mit.edu/job/experimental/681/compiler=clang,label=mac/

**Comment by liangfok** [comment]
I believe the code that should be factored out into a helper method is the command-line parsing code that obtains the desired real-time factor and whether to issue a warning vs. assertion if it is violated, which starts [here](https://github.com/RobotLocomotion/drake/blob/master/drake/examples/Quadrotor/runDynamics.cpp#L19).
