### ISSUE TITLE
Ventura packaging jenkins jobs

### ISSUE THREAD

**Issue by jwnimmer-tri** [RobotLocomotion/drake#20340]
In preparation for #20339 versus the upcoming #20326, I'd like to see if it's possible to bump our arm packaging up to Ventura as a minimum.

For me to test that, I'll need at least these two jobs added to drake-jenkins-jobs:
```
mac-arm-ventura-unprovisioned-clang-wheel-experimental-release
mac-arm-ventura-unprovisioned-clang-bazel-experimental-packaging
```

If it makes sense, we might also define the staging variation at the same time.  (Switching the release playbook to use these new jobs would happen separately.)
```
mac-arm-ventura-unprovisioned-clang-wheel-staging-release
mac-arm-ventura-unprovisioned-clang-bazel-staging-packaging
```

(Once I have the experimental jobs passing and tested, a subsequent request will be to switch the nightly flavor of these to Ventura.)

**Comment by BetsyMcPhail** [comment]
After I created the new jobs for this PR, I tried running the new auto-generate experimental jobs script and was surprised that it didn't have any updates. I realized the script is only looking for *Production* jobs, not *Staging*.  I think this is working as intended as Staging jobs will typically have a corresponding Continuous/Nightly Production job.

**Comment by jwnimmer-tri** [comment]
Yes, working as intended.  We do not want our pull request developers anywhere near the Staging jobs.

**Comment by BetsyMcPhail** [comment]
Both the experimental and staging jobs have been added to Jenkins.
