### ISSUE TITLE
Adding Collision Models to Acrobot URDF Breaks Numerous Unit Tests

### ISSUE THREAD

**Issue by liangfok** [RobotLocomotion/drake#2034]
# Note: This issue is only relevant if https://github.com/RobotLocomotion/drake/pull/1898 is merged.

A key objective of https://github.com/RobotLocomotion/drake/pull/1898 is to make SDF models identical to URDF models. This involved adding collision models to Acrobot.urdf since they were present in Acrobot.sdf.  Unfortunately, adding collision models to Acrobot.urdf breaks the following unit tests:
1. [addRobotFromURDFStringTest.m](https://github.com/RobotLocomotion/drake/blob/master/drake/systems/plants/test/addRobotFromURDFStringTest.m) 
2. [runTrigLQR.m](https://github.com/RobotLocomotion/drake/blob/67747606c0c8274139cecb2aee9f6c606dccab1e/drake/examples/Acrobot/runTrigLQR.m)
3. [trigPolyTest.m](https://github.com/RobotLocomotion/drake/blob/67747606c0c8274139cecb2aee9f6c606dccab1e/drake/examples/Acrobot/test/trigPolyTest.m)

`addRobotFromURDFStringTest.m` fails because the two `RigidBodyManipulator` models that are derived from the URDF cannot be compared using Matlab's [isequal()](http://www.mathworks.com/help/fixedpoint/ref/isequal.html) method. More details here: https://github.com/RobotLocomotion/drake/pull/1898#issuecomment-207197831. As a temporary workaround, I created a version of Acrobot without the collision model called `Acrobot_no_collision.urdf` and modified addRobotFromURDFStringTest.m to use it rather than Acrobot.urdf, which has the collision models. Here is the commit: https://github.com/liangfok/drake/commit/b43408979e8ac6da0112e550dca2b2125b445938

I got around the `runTrigLQR.m` failure using the same solution: https://github.com/liangfok/drake/commit/fd4137da50211ddef4f6148656b67dca75ee0467

I got around the `trigPolyTest.m` failure using the same solution: https://github.com/liangfok/drake/commit/2a4eade7633ccca316d9837e6c1bd7b2e1d04302

Key questions:
- [ ] Why does adding collision models to Acrobot.urdf result in a [FunctionHandleConstraint](https://github.com/RobotLocomotion/drake/blob/master/drake/solvers/FunctionHandleConstraint.m) being added to the rigid body manipulator model?
- [ ] Why does `runTrigLQR.m` fail when using a model of Acrobot with collision elements?
- [ ] Why does `trigPolyTest.m` fail when using a model of Acrobot with collision elements?

**Comment by jwnimmer-tri** [comment]
Over to @sherm1 to decide if we care / reassign within his team / close?

**Comment by sherm1** [comment]
Punting to @SeanCurtis-TRI. Sean, is there anything worth pursuing here? Should these Matlab tests be ported to C++ and nuked? Please feel free to close if this is no longer relevant.

**Comment by SeanCurtis-TRI** [comment]
I'll take a look.

**Comment by RussTedrake** [comment]
without looking at the details, it seems like a very reasonable action to take here would be to remove the `compareParsers` test.  We should just admit that the parsers are going to move forward in c++ and not in matlab (therefore the two will diverge).

**Comment by jwnimmer-tri** [comment]
Closing as won't-fix, because #6369 will be removing the relevant software.  (Furthermore, I believe the test in question in this issue has _already_ been removed.)

If I'm confused and this should in fact stay open, please re-open an clarify the remaining unsolved problem(s) in a new comment here.
