### ISSUE TITLE
WinRM Hiccups Lead to Spurious CI Failures

### ISSUE THREAD

**Issue by david-german-tri** [RobotLocomotion/drake#2035]
e.g. https://drake-jenkins.csail.mit.edu/job/experimental/712/compiler=msvc-64,label=windows/console

We get 1+ of these per day.  @jamiesnape, you previously mentioned that this would be hard to fix, but it's becoming a significant nuisance.  Hypothetically, how would you fix it?

**Comment by jamiesnape** [comment]
Nothing I can do, unfortunately, short of filing bug reports with Microsoft.

**Comment by david-german-tri** [comment]
Just for my edification, can you explain in a little more detail what's going wrong?

**Comment by jamiesnape** [comment]
The WinRM connection restarts randomly for no reason. It is known problem and why you see the message `WinRM service responded. Waiting for WinRM service to stabilize....` for 3 minutes when the slave starts as an attempted workaround (it is more likely be drop earlier than later in the build).

**Comment by jamiesnape** [comment]
The best you can do is limit your exposure. You may wish to consider the use cases for 32-bit builds.

**Comment by jwnimmer-tri** [comment]
It is possible (easy?) to have a failure of results upload still leave the build green?  Perhaps make it a second build step whose result is ignored?

**Comment by jamiesnape** [comment]
It would stay green, but it is not the upload that is failing. The slave is losing its connection.

**Comment by david-german-tri** [comment]
Oh, interesting.  Is it just coincidence that the WinRM connection often seems to drop after `make test` succeeds?

**Comment by jamiesnape** [comment]
Probably down to timing.

**Comment by jwnimmer-tri** [comment]
Possibly results upload is saturating the link, causing WinRM to declare connection loss?

**Comment by jwnimmer-tri** [comment]
Anyway, knowing nothing, perhaps I should bow out.  But +1 for any way that we can make merges not depend on winning the WinRM lottery.

**Comment by jamiesnape** [comment]
I am assuming having stable builds is more important that uploading build artifacts for now?

**Comment by jamiesnape** [comment]
The trouble is, currently build artifact upload is all platforms or none.

**Comment by jwnimmer-tri** [comment]
The artifacts are... the compiled binaries? or just the build logs? or ...?

**Comment by jamiesnape** [comment]
Both.

**Comment by jamiesnape** [comment]
Probably more than we need, but code and logs are scattered everywhere.

**Comment by billhoffman** [comment]
Since it is the default build that you get on Windows, I would say it should be supported.

**Comment by david-german-tri** [comment]
Two questions: 

How hard would it be to disable build artifact upload on win32/win64?  If this is doable, I think we should try it just to see if it decreases flakiness.

How hard is it to upload build logs but not compiled binaries?  I can't really think of a reason we'd want to retrieve the compiled binaries from an experimental CI build (on any platform).

**Comment by jamiesnape** [comment]
Artifact upload has been disabled since yesterday.

**Comment by billhoffman** [comment]
I think it has been more stable.  I have not seen drops like we were getting.

**Comment by jamiesnape** [comment]
After some research, apparently issues with large file uploads are also a known WinRM issue. Anything over ~2 MB is a problem. This is not limited to Jenkins, it is just that WinRM was not really designed with large uploads in mind.

**Comment by jamiesnape** [comment]
When we start building nightly packages, we will need to work around this (not difficult, but something extra to configure).

**Comment by RussTedrake** [comment]
I believe this must have been discussed, but i don't think we need the build artifacts from the PRs.  Just the cdash upload, which should be way below that threhold.  Correct?

**Comment by jamiesnape** [comment]
Yes. There will only be artifacts on some nightly builds, not on PR or continuous.

**Comment by jamiesnape** [comment]
Artifacts are off on Windows builds and they seem much more stable. Otherwise, short of rewriting the Jenkins plugin or WinRM client, there is not much more we can do for now, so this ticket is not really resolvable. Can this be closed?
