### ISSUE TITLE
Is 32-bit Windows support still needed?

### ISSUE THREAD

**Issue by david-german-tri** [RobotLocomotion/drake#2038]
We currently have CI for both 32-bit and 64-bit Windows.  This is somewhat costly, and it increases our exposure to #2035 errors.  Open question for the community: is there a need to continue official support for 32-bit Windows?

**Comment by sherm1** [comment]
Win32 :-1:

**Comment by billhoffman** [comment]
It is the default build type for Visual Studio, so at least doing a nightly or a continuous might not be a bad idea.

**Comment by RussTedrake** [comment]
This has come up many times now.  I originally added support due to a request from edx, but now think it's very valuable for catching alignment issues (which are real but could fail silently on different platforms).

**Comment by david-german-tri** [comment]
Sounds like the conclusion is: Yes.  Closing.
