### ISSUE TITLE
Add Gurobi in Continuous Integration

### ISSUE THREAD

**Issue by david-german-tri** [RobotLocomotion/drake#2040]
This is the only remaining blocker for turning down drake005 (Linux), and will help clear the way to killing drake003 and drake006 as well.

**Comment by david-german-tri** [comment]
Looks like this requires:

(1) Get an academic multi-user license: http://www.gurobi.com/academia/for-universities

(2) Run a "Gurobi Token Server": http://www.gurobi.com/products/licensing-pricing/licensing-detail#FL

(3) Add Gurobi to the CI images.

**Comment by RussTedrake** [comment]
i've put in the (email) request for a multi-user license.

**Comment by RussTedrake** [comment]
i've done my part.  @jamiesnape is taking it from here.

**Comment by jamiesnape** [comment]
Enabled for all future Linux and OS X builds.
