### ISSUE TITLE
Linux AMI Cleanup

### ISSUE THREAD

**Issue by svenevs** [RobotLocomotion/drake#20440]
We have a handful of extra linux provisioned focal and jammy AMI hanging around.  Two updates came from this week (#20402, #20354).  Some may be possibly getting kept because of the #18726 `apt-mark` hold issues.

We should delete the extras on or after 2023-10-30 (after the most recent ones have run through a full array of weekly builds).

CC @jwnimmer-tri @BetsyMcPhail

**Comment by BetsyMcPhail** [comment]
I confirmed that there are no extra Jammy AMIs.

All of the Focal AMIs have been deleted. In addition, the focal configurations in Jenkins were deleted.
