### ISSUE TITLE
API for visual and collision elements should be as similar as possible

### ISSUE THREAD

**Issue by sherm1** [RobotLocomotion/drake#2044]
Conceptually a visual element on a body consists of a (geometry, visual material, pose) triple, and a collision element consists of (geometry, collision material, pose). (Geometry and pose specifics will be different but the types are the same.) The only difference in the specification is the kind of properties associated with the material, so one would expect very similar APIs! However, here is an example from `Cars/simulateLCM.cpp`:

``` c++
    world->addVisualElement(
        DrakeShapes::VisualElement(geom, T_element_to_link, color));
    tree->addCollisionElement(
        RigidBody::CollisionElement(geom, T_element_to_link, world), *world,
        "terrain");
```

Here the visual element gets added to a body (world) while the collision element gets added to the tree as a whole, with the particular body specified (twice!) in the argument list. In the above "color" is a simplified visual material, but there is no corresponding contact material.

We should add a notion of contact material, with properties like stiffness, friction coefficients, etc. and modify the API to treat visual and contact elements similarly (even if they are handled differently internally).

(Discussed with @amcastro-tri)

**Comment by RussTedrake** [comment]
+1

**Comment by sherm1** [comment]
Closing this -- it refers to deprecated code that we aren't going to modify now.
