### ISSUE TITLE
Coverage builds run linter, very expensive and not helpful

### ISSUE THREAD

**Issue by ggould-tri** [RobotLocomotion/drake#20480]
### What happened?

Per discussion on developers slack of CI failure at https://drake-jenkins.csail.mit.edu/view/Production/job/linux-jammy-gcc-bazel-weekly-mosek-coverage/4 , @jwnimmer-tri writes:

> The main problem is that we're collecting coverage instrumentation for our linters themselves.  We should probably turn off the linters in coverage builds.

That seems correct, so filing this issue to record it.

### Relevant log output

```shell
//multibody/tree:py/multibody_tree_core_cpplint                         TIMEOUT in 600.6s
```

**Comment by jwnimmer-tri** [comment]
Again today https://drake-jenkins.csail.mit.edu/view/Production/job/linux-jammy-gcc-bazel-weekly-snopt-coverage/20/.
