### ISSUE TITLE
URDF parser: mimic joint with multiple model instances does not parse

### ISSUE THREAD

**Issue by dmcconachie-tri** [RobotLocomotion/drake#20538]
### What happened?

When processing model directives that have multiple instances of the same gripper with a mimic joint, the parser crashes part way through with the error shown below. A stack trace points to https://github.com/RobotLocomotion/drake/blob/ce83cacd7216d73a1239361f0971c7b7a66f0965/multibody/parsing/detail_urdf_parser.cc#L680

### Version

7d55aff3225da608d0fd5a64b8232b29e42ed580

### What operating system are you using?

Ubuntu 22.04

### What installation option are you using?

compiled from source code using Bazel

### Relevant log output

```shell
terminate called after throwing an instance of 'std::logic_error'
  what():  HasJointNamed(): A Joint named 'panda_finger_joint2' appears in multiple model instances (right::panda_hand, left::panda_hand); you must provide a model_instance argument to disambiguate.
```

**Comment by joemasterjohn** [comment]
Thanks, Dale. Working now.
