### ISSUE TITLE
Please manually tag docker images and upload the releases to S3

### ISSUE THREAD

**Issue by EricCousineau-TRI** [RobotLocomotion/drake#20558]
New release/tag is v1.23.0

https://github.com/RobotLocomotion/drake/releases/tag/v1.23.0

Commit sha: 6955a46

**Comment by BetsyMcPhail** [comment]
Docker and S3 are complete.

apt is still outstanding, I expect that to be finished soon as well.

**Comment by BetsyMcPhail** [comment]
apt is also complete
