### ISSUE TITLE
Optimize The Way Floating Joints Are Added To A Robot Model

### ISSUE THREAD

**Issue by liangfok** [RobotLocomotion/drake#2058]
Currently, each time a new model is added to a rigid body tree, every link in the tree is searched regardless of whether it is a member of the newly added model. This occurs when the floating joints are being added to connect the newly added model to the tree. We can optimize this by keeping track of which links are part of the newly added model and only search over these links. We can further optimize things by keeping track of which newly added links have no joints.

**Comment by sherm1** [comment]
Is this a performance problem? If it only occurs during modeling maybe the dumb method is good enough?

**Comment by david-german-tri** [comment]
I think this is a reference to #2053.  It is indeed an issue at modeling time only, so the peformance problem is incidental.  The real issue is code clarity, and I'm not (yet) convinced it's OK to defer a fix, but we should probably keep discussion on the PR.

**Comment by liangfok** [comment]
Yes, this is in reference to #2053. I will publish my reasoning to kick-the-can-down-the-road soon :).
