### ISSUE TITLE
GCS Graph of Convex Sets quadrotor example hangs

### ISSUE THREAD

**Issue by shaoyifei96** [RobotLocomotion/drake#20625]
### What happened?

I am using drake docker robotlocomotion/drake:latest through Distrobox on Ubuntu 22.
then I cloned git@github.com:mpetersen94/gcs.git  and was able to run the simple_2D_planning.ipynb.

However when I run the uav_planning.ipynb. It **hangs** in the solving step with no terminal output, and no CPU usage.
I also tried to compile from the source. The result is the same.

The problem goes away when I turn off pre-processing but it throws an error of non positive semidefinite matrix

Any pointers are appreciated, thanks!

### Version

20231203193232 HEAD

### What operating system are you using?

Ubuntu 22.04

### What installation option are you using?

compiled from source code using Bazel

**Comment by caseypen** [comment]
I met with the same problem [here](https://github.com/RobotLocomotion/gcs-science-robotics/issues/7).

**Comment by calcualatexzy** [comment]
May I ask if this issue is solved? I meet the same problem, and I would be appreciated to know the answer.

**Comment by RussTedrake** [comment]
The `mpetersen94/gcs` repo used a custom fork of drake (+ some dependencies) and is difficult for me to maintain.  We've been pushing all of the best capabilities into Drake.  

Please see https://github.com/RussTedrake/underactuated/blob/09da23e40591640c4709139a39b00320b59cbca3/book/trajopt/gcs_quadrotor.ipynb . This version should work today (except we need one more PR in Drake for the minimum snap objective, #19308), and this is the version that I will continue to maintain and improve.
