### ISSUE TITLE
the library - manipulation Error

### ISSUE THREAD

**Issue by REN12234** [RobotLocomotion/drake#20648]
I  writte
"import numpy as np
from IPython.display import clear_output
from pydrake.all import (
    AddMultibodyPlantSceneGraph,
    Box,
    Cylinder,
    DiagramBuilder,
    InverseKinematics,
    MeshcatVisualizer,
    MeshcatVisualizerParams,
    RigidTransform,
    Role,
    RollPitchYaw,
    RotationMatrix,
    Solve,
    StartMeshcat,
)"

from manipulation import running_as_notebook
from manipulation.meshcat_utils import MeshcatPoseSliders
from manipulation.scenarios import AddIiwa, AddShape, AddWsg

 but  name 'AddIiwa' is not defined

**Comment by RussTedrake** [comment]
This would be a bug report on the manipulation repo, not on drake.  But that method is definitely defined, so i suspect you are getting a very old version of the manipulation repo, perhaps by installing pip with an older python version?  The supported configurations are here: https://drake.mit.edu/installation.html
