### ISSUE TITLE
Hyperrectangle::MaybeCalcAxisAlignedBoundingBox Doesn't Catch Unbounded Hyperellipsoid

### ISSUE THREAD

**Issue by cohnt** [RobotLocomotion/drake#20667]
### What happened?

The function `Hyperrectangle::MaybeCalcAxisAlignedBoundingBox` should return nullopt if the set it's called on is unbounded. However, when called on an unbounded hyperellipsoid, specifically on the build "linux-focal-clang-bazel-experimental-release", it does not return nullopt. I first encountered this in [this build](https://drake-jenkins.csail.mit.edu/job/linux-focal-clang-bazel-experimental-release/10629/consoleFull), and verified it in [this build](https://drake-jenkins.csail.mit.edu/job/linux-focal-clang-bazel-experimental-release/10630/consoleFull).  I'm not able to replicate this behavior on my local machine. The following code snippet can be added to any of the tests to replicate the behavior:
```
Hyperellipsoid H(Eigen::MatrixXd::Zero(2, 2), Eigen::VectorXd::Zero(2));
EXPECT_FALSE(Hyperrectangle::MaybeCalcAxisAlignedBoundingBox(H).has_value());
```

cc @sadraddini 

### Version

170a0f46c6a19684162c5ebd73911b20755f399b

**Comment by EricCousineau-TRI** [comment]
Assigning @hongkai-dai per component leads

**Comment by hongkai-dai** [comment]
Assign this to @sadraddini as the original author of hyperrectangle

**Comment by sadraddini** [comment]
I could replicate this on `focal`. Yikes. Investigating
