### ISSUE TITLE
Parsing include tags in xml doesn't seem to work

### ISSUE THREAD

**Issue by jbruedigam-bdai** [RobotLocomotion/drake#20683]
### What happened?

When parsing Mujoco xmls, [`<include>`](https://mujoco.readthedocs.io/en/latest/XMLreference.html#include) tags are apparently not parsed.
Maybe as a solutiuon, could you temporarily build the full xml and then parse this temporary xml?

### Version

1.23.0

### What operating system are you using?

Ubuntu 22.04

### What installation option are you using?

Unknown / Other

**Comment by sherm1** [comment]
Assigned to Rico for disposition

**Comment by rpoyner-tri** [comment]
\cc @RussTedrake . Looking at the Mujoco docs, this element is a bit different than anything else we support. A correct implementation would require a preprocessing step that processes and deletes the `<include>` node, replacing it with (a portion of) the tinyxml parse of the included file.

**Comment by RussTedrake** [comment]
That seems reasonable to me.  I agree it would be good to support this.

FWIW -- SDF does have an `<include>`, which we now support, via libsdf.  http://sdformat.org/tutorials?tut=composition .

**Comment by rpoyner-tri** [comment]
I was aware of SDFormat include, but the implementations will have essentially nothing in common. I'll start investigating this more closely.
