### ISSUE TITLE
Installing `drake-dev` appears to affect `mypy` checks outside of `drake` libraries

### ISSUE THREAD

**Issue by bhung-bdai** [RobotLocomotion/drake#20685]
### What happened?

Installing the `drake-dev` Debian package as outlined in the [install page](https://drake.mit.edu/apt.html) results in `mypy` failing and being affected for type checks both within and outside of `pydrake`. For example: 
(Within Drake)
![image](https://github.com/RobotLocomotion/drake/assets/137220849/ec050823-b399-4c91-a12b-eb0e4bc33d55)
(Outside Drake)
![image](https://github.com/RobotLocomotion/drake/assets/137220849/5ab8143c-afc3-4ada-8a54-f68b0025f420)
These errors only appeared after installing 'drake-dev'; prior, the type checking was all passing. What part of the `drake-dev` install could be causing this? 

### Version

Drake 1.23.0

### What operating system are you using?

Ubuntu 22.04

### What installation option are you using?

Unknown / Other

**Comment by jwnimmer-tri** [comment]
Please supply more information here so that the bug is actionable.  Specifically, what are the necessary steps for someone else to be able to reproduce the problem?

**Comment by jwnimmer-tri** [comment]
Ping @bhung-bdai for more information, please.
