### ISSUE TITLE
Please manually tag docker images and upload the releases to S3

### ISSUE THREAD

**Issue by xuchenhan-tri** [RobotLocomotion/drake#20687]
New release/tag is v1.24.0

https://github.com/RobotLocomotion/drake/releases/tag/v1.24.0

Commit sha: https://github.com/RobotLocomotion/drake/commit/9ba8f5d8d4ee6919ec41542d47509549cfa8d919

**Comment by BetsyMcPhail** [comment]
S3/docker/apt have all been updated
