### ISSUE TITLE
Enable substituting symbolic variables with autodiff variables

### ISSUE THREAD

**Issue by nepfaff** [RobotLocomotion/drake#20696]
**Is your feature request related to a problem? Please describe.**
I have some symbolic expressions stored on disk that I want to use in a non-convex program with autodiff variables. This requires me to substitute the symbolic variables with the autodiff variables.

Minimal toy example:
```python
from pydrake.all import (
    MathematicalProgram,
    SnoptSolver,
    Variable,
)

# Loaded from disk
x = Variable("x")
cost_expression = x**2

prog = MathematicalProgram()
x_vars = prog.NewContinuousVariables(1, "x")


def cost_func(vars):
    var = vars[0]
    return cost_expression.Substitute({x: var})


prog.AddCost(cost_func, vars=x_vars)

# Use Snopt with autodiff as the real problem won't be convex
solver = SnoptSolver()
result = solver.Solve(prog)
```

I have taken this from [this](https://stackoverflow.com/questions/77687354/substitute-symbolic-variables-with-autodiff-variables?noredirect=1#comment136960705_77687354) StackOverflow post.

**Describe the solution you'd like**
Being able to run the above example by enabling the substitution of symbolic variables with autodiff variables.

**Describe alternatives you've considered**
Manually evaluating the value and derivatives of the resulting autodiff variable.
Example:
```python
from pydrake.all import AutoDiffXd, Expression, Variable

x = Variable("x")
y = Variable("y")
z: Expression = 3 * x + y**2 + x * y

x_ad = AutoDiffXd(1.0, [1, 0])
y_ad = AutoDiffXd(2.0, [0, 1])

z_val = z.Evaluate({x: x_ad.value(), y: y_ad.value()})
z_grad_wrt_x = (
    z.EvaluatePartial({y: y_ad.value()}).Differentiate(x).Evaluate({x: x_ad.value()})
)
z_grad_wrt_y = (
    z.EvaluatePartial({x: x_ad.value()}).Differentiate(y).Evaluate({y: y_ad.value()})
)
z_grad = [z_grad_wrt_x, z_grad_wrt_y]
z_ad = AutoDiffXd(z_val, z_grad)
```
This works but isn't very neat.

**Additional context**
I would be happy to help implement this!

**Comment by nepfaff** [comment]
Updated the "Describe alternatives you've considered" section with manual evaluation

**Comment by nepfaff** [comment]
@jwnimmer-tri suggestion of using `ExpressionCost` works beautifully, as detailed [here](https://stackoverflow.com/a/77694087/11721691).

Should we close this? The only downside of `ExpressionCost` is that the name "cost" makes its use case less obvious in this scenario, and adding it as synthetic sugar to `Expression::Evaluate` might be helpful in that regard.

**Comment by hongkai-dai** [comment]
Sure, we can close this issue. 

BTW, evaluating ExpressionCost and ExpressionConstraint with AutoDiffXd is quite slow. I would strongly encourage to write your own constraint/cost which natively supports AutoDiffXd if the computation speed becomes a concern/
