### ISSUE TITLE
PR builds have confusing status colors

### ISSUE THREAD

**Issue by jwnimmer-tri** [RobotLocomotion/drake#2071]
When we submit a PR, it kicks off a jenkins build.  If we click through on github to the jenkins build, jenkins presents a colored-globe matrix with the build status from the 'experimenal' configuration.

The problem is, everyone's PRs go into 'experimental', but jenkins is trying to show the "history" of the experimental build, so it looks misleadingly like my build has failed (lots of red!) even though it was the prior experimental build that had failed.

We should try to make jenkins only show red globes if the in-progress build has a problem.

Here's PR 2070's current status, as an example:
![screenshot from 2016-04-12 09 54 09](https://cloud.githubusercontent.com/assets/17596505/14462374/c363ba56-0094-11e6-8531-40f41a0525d0.png)

**Comment by jamiesnape** [comment]
This is a core functionality of Jenkins. We cannot change it. Sorry.
