### ISSUE TITLE
Upgrade Externals January 2024 

### ISSUE THREAD

**Issue by jwnimmer-tri** [RobotLocomotion/drake#20723]
Follow [Semi-automated monthly upgrades](https://github.com/RobotLocomotion/drake/blob/master/tools/workspace/README.md#semi-automated-monthly-upgrades) documentation.

Prior issue (December 2023): #20594

- [x] #20742
- [x] #20744
- [x] #20745

**Comment by BetsyMcPhail** [comment]
@mwoehlke-kitware can you please do the January external upgrades?

**Comment by mwoehlke-kitware** [comment]
All PRs have landed.
