### ISSUE TITLE
`common.schema.Transform.Sample()` silently discards `base_frame`

### ISSUE THREAD

**Issue by ggould-tri** [RobotLocomotion/drake#20754]
### What happened?

The `common.schema.Transform` class has a member `base_frame`.

The `common.schema.Transform.Sample()` method returns `RigidTransformd`, not `Transform`.

`math.RigidTransformd` does not have a `base_frame`, so anyone consuming a `Transform` via `Sample` has to save off the base frame out-of-line.

It is unintuitive that `Sample` discards non-distribution information; moreover because `RigidTransformd` convert-contructs to `common.schema.Transform`, the extremely obvious code
```
Transform transform_distribution = [ mumble ]
Transform concrete = transform_distribution.Sample()
```
...compiles and runs without warning but is incorrect.

Assuming that we don't want `common.schema.Transform.Sample()` to return `common.schema.Transform`, it should instead assert that `base_frame` is nullopt.

(cc @calderpg-tri per our discussion)

**Comment by jwnimmer-tri** [comment]
> Assuming that we don't want common.schema.Transform.Sample() to return common.schema.Transform, it should instead assert that base_frame is nullopt.

This would be fine by me.

If we like, we could add a different function name to return a sampled copy of the `Transform` with the base name intact.

**Comment by jwnimmer-tri** [comment]
I would have thought that the same complaint about "silently ignoring base_frame" would have applied to `GetDeterministicValue()` as well?
