### ISSUE TITLE
Add build system support for long-running regression tests

### ISSUE THREAD

**Issue by jwnimmer-tri** [RobotLocomotion/drake#2078]
In #2068, Russ asked for:
> Is there a standard development solution for adding regression tests to the system
> which are not run for CI? For instance, it looks like we could restrict a test to only
> the nightly configuration in add_test . RobotLocomotion/kitware — what are the
> ctest recommended best practices for this?

(See a few comments atop there for initial discussion.)

The general idea here is that we want to write tests, but not have them run by default by developers, nor by PR builders.  We just want to run them on master CI, and let developers opt-in to running them if they want to explore something.

**Comment by jwnimmer-tri** [comment]
From today's discussion, there is no way to teach CTest that a test should be off by default.  Kitware may file a CTest feature request to see if that can be made to happen.

Thus, so far these options to achieve this:
- Label the test and use CTest to opt out of specific labels.  This means that developers would need to have a longer CTest command line (or we have a drake wrapper script that encapsulates this option).
- Add a CMake option with an if-block around the add_test calls.  The downside is a trip through CMake to turn them on or off (maybe this is fine).

Feel to correct this if I got anything wrong.

**Comment by jwnimmer-tri** [comment]
I believe that the LONG_RUNNING_TESTS has solved this?

Though perhaps _how_ to run the tests via CMake on your workstation still needs to be documented in developers.rst or something?

**Comment by liangfok** [comment]
I believe the instructions on how to run unit tests are here and that they also apply to long running tests: http://drake.mit.edu/unit_testing_instructions.html

**Comment by jwnimmer-tri** [comment]
Possibly, but did you try it?  I didn't think CTest knows the long running test names that match its `-R` argument unless you have manually configured LONG_RUNNING_TESTS=ON in your CMakeCache.

**Comment by liangfok** [comment]
Oh yeah, you're right. Looks we need to run `cmake -DLONG_RUNNING_TESTS=ON ..` from within the build artifacts directory to get them to show up. I'm testing now and will issue a PR if this is correct.

**Comment by sammy-tri** [comment]
I've only been able to figure out how to get the long running tests to show up by editing the CMakeCache (at @jwnimmer-tri 's suggestion).  A command line equivalent which could be invoked for a single ctest run would be interesting if it were doable.

**Comment by liangfok** [comment]
I'm updating the wiki right now with instructions.  Please hold...
