### ISSUE TITLE
CDash: certificate update

### ISSUE THREAD

**Issue by BetsyMcPhail** [RobotLocomotion/drake#20819]
- [x] CDash is currently using an Aurora version compatible with MySQL 5.7. Support for this version ends in October, need to update to latest version (https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/Aurora.VersionPolicy.html).

- [x] Once that update is complete, we can consider switching from "Aurora Standard" and "Aurora I/O-Optimized".

- [ ] While updating the DB, we should also update the instance certificates which will expire on August 22, 2024.

**Comment by williamjallen** [comment]
Database CA has been updated.  This should be a one-off change.  The new CA expires in 2061.
