### ISSUE TITLE
Require CMake 3.5 and update installation steps

### ISSUE THREAD

**Issue by david-german-tri** [RobotLocomotion/drake#2082]
CMake 3.5 would simplify and modernize the CMake lists.  Let's make it a requirement, and update the installation instructions appropriately.  (As discussed offline.)

**Comment by rpoyner-tri** [comment]
Looks like CMake 3.4 would enable this, for example: https://blog.kitware.com/create-dlls-on-windows-without-declspec-using-new-cmake-export-all-feature/

.. and eventual removal of various declspec scars in source code and build systems.

Count me in.

**Comment by liangfok** [comment]
+1

**Comment by jamiesnape** [comment]
We install 3.5 on all the CI machines for compatibility with CDash, so personally, I would say just require 3.5.

**Comment by david-german-tri** [comment]
@jamiesnape Done.

**Comment by wxmerkt** [comment]
I'm curious, what's the intended timeline/sequence of actions on this?

Ubuntu 16.04 appears to ship with 3.5.1, the most recent version on Ubuntu 14.04 is 2.8.12.2. Drake already requires adding a PPA for gcc-4.9 - this appears as requiring to add another non-standard PPA for CMake-3.x (maybe [this one here](http://askubuntu.com/questions/610291/how-to-install-cmake-3-2-on-ubuntu-14-04)). Or would it be possible to get CMake 3.5.x and gcc-4.9 from the same PPA?

**Comment by jamiesnape** [comment]
No, and I would recommend downloading the binary from the CMake website. All dependencies are bundled so it works on any Linux distribution.

**Comment by bradking** [comment]
With #2415 merged, this is now resolved.
