### ISSUE TITLE
OOM failures in mac-arm CI

### ISSUE THREAD

**Issue by liangfok** [RobotLocomotion/drake#20823]
This ticket tracks CI OOM failures involving mac-arm builds that are not attributable to a specific commit that can be reverted.

mac-arm-ventura-unprovisioned-clang-bazel-nightly-release:
- https://drake-cdash.csail.mit.edu/viewBuildError.php?buildid=1758050 (2024-01-23)

mac-arm-ventura-clang-bazel-nightly-debug:
- https://drake-cdash.csail.mit.edu/viewBuildError.php?buildid=1758309 (2024-01-24)
- https://drake-cdash.csail.mit.edu/viewBuildError.php?buildid=1758403 (2024-01-24)

**Comment by EricCousineau-TRI** [comment]
Assigning @BetsyMcPhail per component lead chart

**Comment by liangfok** [comment]
https://drake-jenkins.csail.mit.edu/view/Nightly%20Production/job/mac-arm-ventura-clang-bazel-nightly-everything-release/260/
