### ISSUE TITLE
Initial CI support for Noble

### ISSUE THREAD

**Issue by jwnimmer-tri** [RobotLocomotion/drake#20835]
Towards #21335.

Over the next few months, we'll want to start preparing for Ubuntu 24.04 ("Noble") so that we can officially support it once it's released.  To that end, it would help to be able to test some early PRs in CI.

Please create a job `linux-noble-unprovisioned-gcc-bazel-experimental-release` so that PR authors can launch that.  We don't need any Continuous, Nightly, nor Provisioned flavors for now.

It's possible that the the base image we start from isn't available yet, so this ticket isn't immediately actionable.

**Comment by jwnimmer-tri** [comment]
See also #21008.

**Comment by jwnimmer-tri** [comment]
As of today (or yesterday?) there are official EC2 AMIs now.

**Comment by BetsyMcPhail** [comment]
`linux-noble-unprovisioned-gcc-bazel-experimental-release` is ready for testing. Not surprisingly there's a few test failures, but CI support (and this ticket) are complete.
