### ISSUE TITLE
accessing manipulatorDynamics in feedback/control

### ISSUE THREAD

**Issue by mjbeardsley** [RobotLocomotion/drake#2085]
I have a TimeSteppingRigidBodyManipulator robot with a PD feedback control loop, and I'd like to access the manipulatorDynamics function of the robot in the feedback loop. Rather than adding the huge matrices to the robot's output frame, is it possible for the PD DrakeSystems to access the manipulatorDynamics differently (e.g. passing the robot object by reference into the PD block DrakeSystem constructors)? 

I know that for classes, in order to pass-by-reference the class needs to subclass handle, but short of changing DynamicalSystem to subclass handle or adding the dynamics matrices to the robot's output frame, is there a better way for other blocks to access the robot manipulatorDynamics?

Thanks!

**Comment by RussTedrake** [comment]
You can use getManipulator to get a copy for your PD controller.  It's true that it's pass by value, so acts like a copy, but if you don't modify it then the matlab backend seems to optimize this away pretty well.  You could probably even get away with calling getManipulator in the loop and not see a big performance hit.

**Comment by mjbeardsley** [comment]
Ah yes this will work, I got a little mixed up about how getManipulatorDynamics worked. All good now though, thanks!
