### ISSUE TITLE
gurobi license on drake005 is expired

### ISSUE THREAD

**Issue by sammy-tri** [RobotLocomotion/drake#2088]
All builds on drake005 are failing due to an expired gurobi license.

Examples:

http://drake005.csail.mit.edu/drake/pull-rpoyner-tri-fix-issue-2077-into-RobotLocomotion-master_20160413-1831-Experimental

http://drake005.csail.mit.edu/drake/pull-sammy-tri-nlopt_osx-into-RobotLocomotion-master_20160413-1918-Experimental

**Comment by RussTedrake** [comment]
Will address this as soon as I'm at my laptop tonight

**Comment by RussTedrake** [comment]
should be resolved now
