### ISSUE TITLE
CMake wrapper run the install step when calling the build step

### ISSUE THREAD

**Issue by j-rivero** [RobotLocomotion/drake#20908]
### What happened?

When using the Drake CMake wrapper I noticed that running a plain `make` call with the default target ended up installing the building artifacts in the specified final destination (mostly declared via `DESTDIR` and `CMAKE_INSTALL_PREFIX`). 

This is a bit different from the usual functionally of the default target in make (the all target) which restrict its goal to build all the specified artifacts inside a building directory but not in the final filesystem destination reserved for doing a `make install` call.

Looking into the build log looks like the building is done fine in temporary building directories but at some point the `strip` step uses the `install` command to do the its magic.

```
[32m[0 / 1][0m [Prepa] BazelWorkspaceStatusAction stable-status.txt
Target //:install up-to-date:
  /tmp/binarydeb/ros-rolling-drake-vendor-1.25.5/.obj-x86_64-linux-gnu/drake-prefix/src/drake-build/_bazel_/54c7e0b241e3ddac25283e0b95a56108/execroot/drake/bazel-out/k8-opt/bin/install_test_commands
  /tmp/binarydeb/ros-rolling-drake-vendor-1.25.5/.obj-x86_64-linux-gnu/drake-prefix/src/drake-build/_bazel_/54c7e0b241e3ddac25283e0b95a56108/execroot/drake/bazel-out/k8-opt/bin/install
[32mINFO: [0mElapsed time: 0.985s, Critical Path: 0.01s
[32mINFO: [0m1 process: 1 internal.
[32mINFO:[0m Build completed successfully, 1 total action
[32mINFO: [0mRunning command line: /tmp/binarydeb/ros-rolling-drake-vendor-1.25.5/.obj-x86_64-linux-gnu/drake-prefix/src/drake-build/_bazel_/54c7e0b241e3ddac25283e0b95a56108/execroot/drake/bazel-out/k8-opt/bin/install --strip_tool /usr/bin/strip --color /opt/ros/rolling/opt/drake_vendor
[0m[36mInstalling the project stripped...[0m
-- Installing: /tmp/binarydeb/ros-rolling-drake-vendor-1.25.5/debian/ros-rolling-drake-vendor//opt/ros/rolling/opt/drake_vendor/lib/python3.10/site-packages/pydrake/lcm.cpython-310-x86_64-linux-gnu.so
-- Installing: /tmp/binarydeb/ros-rolling-drake-vendor-1.25.5/debian/ros-rolling-drake-vendor//opt/ros/rolling/opt/drake_vendor/lib/python3.10/site-packages/pydrake/_lcm_extra.py
```

### Version

1.25.0

### What operating system are you using?

Ubuntu 22.04

### What installation option are you using?

compiled from source code using CMake

**Comment by jwnimmer-tri** [comment]
FYI We expect that a very simple repro will work here, something like:

```
git clone drake
mkdir build && cd build
cmake ../drake
make
```

We want the `make` step to just do `bazel build //:install`, not `bazel run //:install`.

Per f2f we think maybe the "ExternalProject_Add" is what's gumming things up.
