### ISSUE TITLE
Problems with build to non-default location

### ISSUE THREAD

**Issue by sherm1** [RobotLocomotion/drake#2093]
With #1884, @mwoehlke-kitware relocated all generated files under a single build directory (goodbye, pod-builds!) and allowed choice of out-of-source build. I tried this on Windows, choosing `drake-distro-build` for artifacts rather than the default `drake-distro/build`. I ran into a few remaining CMakeLists problems:
- Two variables in the CMake GUI still contained the `drake-distro/build` directory: `CMAKE_INSTALL_PREFIX`, and `_build_dir`. I had to change those manually to use the new build directory.
- Despite redirecting all the visible build names, generating in CMake caused the default build directory to get created. It contained
`C:\Users\Sherm\Documents\GitHub\sherm1\drake-distro\build\externals\googletest\googlemock\gmock.dir\Debug\gmock.tlog\*.tlog` and nothing else.

I believe there remain some additional problems mentioned in comments in #1884 where a few externals still place artifacts in the default location. However, the present issue refers only to problems with the CMake configure & generate steps.

Assigning this to @mwoehlke-kitware for a first look.

**Comment by mwoehlke-kitware** [comment]
Thanks for pointing this out. I believe #2099 will fix these issues.
