### ISSUE TITLE
Fatal Python error trying to run drake-visualizer on Mac

### ISSUE THREAD

**Issue by ErikSobel-TRI** [RobotLocomotion/drake#2095]
I'm getting the following error when I try to run drake-visualizer on my Max (OS X El Capitan).

Fatal Python error: PyThreadState_Get: no current thread
Abort trap: 6

Stackoverflow says this is usually because a different Python interpreter is getting invoked at runtime than what the system expected to use when it was built.  

$ which python
/usr/local/bin/python
$ python -V
Python 2.7.11

How do I determine which python it was expecting from the build.

**Comment by liangfok** [comment]
I am able to run `drake-visualizer` on my OS X machine and the return values to `which python` and `python -V` are the same as yours.

Unfortunately, I don't know how to tell which interpreter is being used during compile-time.
