### ISSUE TITLE
Appearance of proximity meshes in meshcat

### ISSUE THREAD

**Issue by SeanCurtis-TRI** [RobotLocomotion/drake#20988]
There are a number of artifacts vis a vis how proximity geometry gets visualized. This issue tracks a number of related issues.

These are considered obvious improvements/requirements:
- [x] #20618
- [x] #20983
- [x] #20984
- [ ] #21291

These ideas are more speculative, with speculative benefits:
- [ ] #20986
- [ ] #20987

**Comment by jwnimmer-tri** [comment]
@SeanCurtis-TRI my preference would be to prioritize all of those issues independently, and just close this Epic?  At least for me, it's not adding value.  If you like it we can keep it though.

**Comment by SeanCurtis-TRI** [comment]
Feel free to close it. The issues themselves maintain a record of this. The ability to get from one of those issues to other related issues is now baked in. So, whatever value this issue serves, it serves it just as well closed.
