### ISSUE TITLE
Bad numerics when converting from HPolyhedron to VPolytope

### ISSUE THREAD

**Issue by chsahit** [RobotLocomotion/drake#20985]
### What happened?

I have a block with dimensions 0.03m x 0.03m x 0.075m represented as an HPolyhedron. This is a 3 dimensional block, however when I convert it to a VPolytope the resulting object only has 4 vertices (rather than 8). This is not a problem when the block is 3m x 3m x 7.5 m, pointing to bad numerics when the conversion is occurring. One way to deal with this problem which came up in discussion with @cohnt is to not perform the projection into the affine subspace when the polyhedron is full dimensional. 

Here is some code to replicate the error on my machine (NB: I pip installed drake, so Gurobi/MOSEK are not enabled afaik):
```
import numpy as np
from pydrake.all import HPolyhedron, VPolytope
A1 = np.array([[1, 0, 0], [0, 1, 0], [0, 0, 1], [-1, 0, 0], [0, -1, 0], [0, 0, -1]])
b1 = np.array([0.03, 0.03, 0.075, 0.03, 0.03, 0.075])
H = HPolyhedron(A1, b1)
V = VPolytope(H)
print(V.vertices())
```
And here is a deepnote link with that code:
https://deepnote.com/workspace/robot-8b6e-0c23709f-282f-4cb6-9f2c-5f0f6b6ae534/project/01-Introduction-Duplicate-8da81b4c-e019-405e-9890-ed0632b1892c/notebook/intro-a15aa6c570764ee3a4f8427b456f4208

I don't know if this should be a separate issue, but also the `tol` parameter when converting in the other direction (VPolytope -> HPolyhedron), is not exposed in the python bindings and is probably similarly relevant when working with smaller (yet physically plausible manipuland-sized) objects. 

### Version

1.25.0

### What operating system are you using?

Ubuntu 20.04

### What installation option are you using?

pip install drake

**Comment by cohnt** [comment]
So an immediate fix I can apply is adding the tolerance parameter as a changeable parameter. I'll have a PR up for that shortly.

A longer-term fix would be to rewire the logic used to compute the affine hull. We know that the builtin solvers don't have great numerics when working with VPolytope objects, so getting the affine hull via a rank-revealing decomposition should be more reliable numerically.

**Comment by chsahit** [comment]
Thanks for looking into this! FWIW the tolerance param I mentioned/that is documented only exists for the VPolytope -> HPolyhedron direction. I don't think exposing that in the python binding actually addresses the test case in the code snippet in my original message, where I convert from HPolyhedron->Vpolytope.
