### ISSUE TITLE
Proximity geometry in a default-configured meshcat can never be opaque

### ISSUE THREAD

**Issue by SeanCurtis-TRI** [RobotLocomotion/drake#20984]
## Problem statement

When we visualize proximity geometry, it's baseline opacity is *always* semi-transparent. This is because [the default `default_proximity_color` defined in `VisualizationConfig` has a 50% alpha](https://github.com/RobotLocomotion/drake/blob/master/visualization/visualization_config.h#L53-L55).

A user is free to define an alternative value in configuration, but it may not be apparent or convenient for them to do so. It is also unnecessary; we have a proximity slider that allows for controlling the global opacity of all collision geometry.

## Proposal

The default `default_proximity_color` should have 100% opacity. However, we should default the corresponding *slider* value to 0.5 (instead of the 1.0 that it currently sits at). Thus, the default behavior looks the same (50% opaque collision geometry). But the user can use the proximity alpha slider to render the geometries fully opaque. This can help the user to understand the collision geometries (particularly those generated by Drake -- e.g., hydroelastic tessellations or convex hulls).

**Comment by jwnimmer-tri** [comment]
Agreed.  I think this stems from the old days when there was only one alpha between the color and the slider.  Now that the slider is independent, I agree the color should go back to 1.0 alpha.
