### ISSUE TITLE
Allow `TrajectorySource` with `output_derivative_order` > 0 without requiring `MakeDerivative`

### ISSUE THREAD

**Issue by nepfaff** [RobotLocomotion/drake#20982]
**Is your feature request related to a problem? Please describe.**
The current implementation of `TrajectorySource` requires the trajectory to implement `MakeDerivative` (see [here](https://github.com/RobotLocomotion/drake/blob/master/systems/primitives/trajectory_source.cc#L30)). However, there are cases when it is more natural/ easier to provide `DoEvalDerivative` only. An example is `PathParameterizedTrajectory`. I had a similar situation with one of my custom trajectories, where providing `DoMakeDerivative` added unnecessary overhead while `DoEvalDerivative` was `O(1)` anyways.

**Describe the solution you'd like**
Allow `TrajectorySource` with `output_derivative_order` > 0 without requiring `MakeDerivative`. In particular, it should support `PathParameterizedTrajectory`.

**Comment by RussTedrake** [comment]
It seems like the first step towards this would be to split `Trajectory::has_derivative` to enable declaring support for `EvalDerivative` independently from `MakeDerivative`.

**Comment by jwnimmer-tri** [comment]
> It seems like the first step towards this would be to split Trajectory::has_derivative to enable declaring support for EvalDerivative independently from MakeDerivative.

I would rather say that any class that implements one of the two should always implement both.  In other words, `PathParameterizedTrajectory` should implement `MakeDerivative`.  We could even have a common helper class `DerivativeTrajectory` that wraps an underlying `Trajectory` with an `int order`, calling `underlying.EvalDerivative` for the actual logic.

**Comment by jwnimmer-tri** [comment]
In fact, `PathParameterizedTrajectory` is outright wrong.  The docs for `Trajectory::has_derivative()` say that if you return true, you must provide an implementation for _both_ functions, yet it fails to do so.

**Comment by RussTedrake** [comment]
I agree that PathParameterizedTrajectory is wrong in this way.  
We also have a request for a FunctionHandleTrajectory in #20699.  Implementing that could make the DerivativeTrajectory class even easier.
