### ISSUE TITLE
Fix wheel AMIs and/or setup to enable docker on Jammy

### ISSUE THREAD

**Issue by svenevs** [RobotLocomotion/drake#21007]
Lower priority outcropping of #20954, relates: https://github.com/RobotLocomotion/drake-jenkins-jobs/pull/113

There's no actual ticket for this right now.  Will let us close #20954 without this blocking, it seems likely it's just an AMI fix but we need to discover and document it somewhere.

CC FYI @jwnimmer-tri @BetsyMcPhail @mwoehlke-kitware

**Comment by jwnimmer-tri** [comment]
Also for bookeeping: this is/was related to https://github.com/RobotLocomotion/drake/issues/20953.

**Comment by jwnimmer-tri** [comment]
Reminder for tracking purpose: we should revert #21020 once we have Docker Jammy working in CI and Focal goes away.

**Comment by BetsyMcPhail** [comment]
The commands needed to add to the image:

```
sudo groupadd docker
sudo usermod -a G docker ubuntu
```

The internal CI doc has been updated to included these.

**Comment by BetsyMcPhail** [comment]
I did a very basic test with the wheel from https://drake-jenkins.csail.mit.edu/view/Wheel/job/linux-jammy-unprovisioned-gcc-wheel-experimental-release/3/

```
$ env/bin/pip install https://drake-packages.csail.mit.edu/drake/experimental/drake-0.0.2024.2.28.19.53.24%2Bgit1dd73812-cp310-cp310-manylinux_2_35_x86_64.whl
Collecting drake==0.0.2024.2.28.19.53.24+git1dd73812
  ...
Successfully installed drake-0.0.2024.2.28.19.53.24+git1dd73812
$ env/bin/python
...
>>> from pydrake.all import *
```
