### ISSUE TITLE
Linux AMI refresh

### ISSUE THREAD

**Issue by jwnimmer-tri** [RobotLocomotion/drake#21038]
Somehow, it seems like we have Boost installed in our provisioned AMIs, even though our setup scripts for unprovisioned do not install it.

This is probably just some vestigial leftovers from prior upgrades.

I think the corrective action we want is to just re-make the provisioned linux images from scratch?

**Comment by BetsyMcPhail** [comment]
We are also overdue for the biannual kernal update, so I'll do that as well while I'm updating things.

**Comment by BetsyMcPhail** [comment]
`drake-linux-jammy-2024-03-01` and ` drake-linux-jammy-unprovisioned-2024-03-01` have been deployed. Note the date is for tomorrow, there was already an unprovisioned image for today.
