### ISSUE TITLE
Rename CMake Option "WITH_[name]" to be Something More Accurate

### ISSUE THREAD

**Issue by liangfok** [RobotLocomotion/drake#2108]
At the super-build level, `[drake-distro]/CMakeLists.txt` contains numerous options named "WITH_[name]". If `ON`, Drake will ~~install~~ download and use the external. It is not meant to enable / disable features in Drake. Thus, we should come up with a more accurate name for these options. I suggest "INSTALL_[NAME]". Thoughts?

Related: https://github.com/RobotLocomotion/drake/pull/2103#issuecomment-210443049

**Comment by liangfok** [comment]
Perhaps "INSTALL_[NAME]" is too frightening since someone may think the external software package will be installed in a system-wide fashion. Thus, how about: "INSTALL_IN_DRAKE_SUPERBUILD_[NAME]"?

**Comment by RussTedrake** [comment]
see also #1523

**Comment by jamiesnape** [comment]
`INSTALL_*` is not correct, anyway. The external will neither download nor build, and it does not really install in either case. `WITH_*` and `USE_*` are pretty common names for such CMake variables.

**Comment by liangfok** [comment]
Aren't the externals being downloaded (and thus installed) into `[drake distro]/externals/[external name]/` when running `make` or `make download-all` at the super-build level?

**Comment by jamiesnape** [comment]
Downloaded and installed are not equivalent in CMake.

**Comment by liangfok** [comment]
Since the CMake world likes `USE_*` and the POD world actually downloads the externals, how about let's use `DOWNLOAD_AND_USE_*` as the variables in Drake's super-build level?

**Comment by jamiesnape** [comment]
Maybe. Personally, I would table this until we have decided if/when/how we are going to replace the current external build system. If we use a pre-existing solution, the naming convention may be dictated by that.

**Comment by liangfok** [comment]
OK I agree and will re-open this issue when / if the time is right.
