### ISSUE TITLE
Update Convex semantics and functionality

### ISSUE THREAD

**Issue by SeanCurtis-TRI** [RobotLocomotion/drake#21125]
## Problem statement

As of #21061 and #21066 Drake now computes the convex hull of `Convex` and `Mesh` shapes. This was done with the specific end in mind of visualizing convex hulls when we're using convex hulls. So, when you ask to visualize the proximity geometry in meshcat, instead of seeing the original obj, you see the convex hull that is actually used in, say, point contact.

The introduction of this functionality invites us to revisit the `Convex` shape specification. The initial purpose of the `Convex` type was to allow proximity computations to use convex-dependent algorithms on polytopes (as opposed to Drake's family of primitives). However, it was always a bit of a bluff. If a user declared it was properly convex, we'd trust them and cross our fingers. We never took the time to validate the validity of the assertion.

Now we have an out. We can compute its convex hull and know, by construction, that it is a valid convex hull. That invites us to revisit the question of what the `Convex` shape *means*.

As of the time of this authorship, the [definition of `Convex` is vague at best](https://github.com/RobotLocomotion/drake/blob/ed30f9eb87046825999672be9634e448a78dfdde/geometry/shape_specification.h#L187-L200). It *purports* to be the specification of a convex shape and *assumes* the input mesh is a proper polytope.

## Proposal

I propose that we tighten up the definition of `Convex`. It should mean, "Use the convex hull of the mesh I've specified. Period." The value of the input mesh is solely to define the convex hull. To that end, only the vertex positions and matter, and those, only until I have the actual convex hull.

### Implications

For proximity geometries, this is largely a no brainer. It improves our implementation vis a vis FCL right out of the gate because we'd always have a convex hull that we *know* satisfies FCL's requirements for the fast, most robust kind of convex hull. We could re-interpret what it means to assign the compliant hydroelastic property to an .obj as a compliant mesh built of the .obj's *convex hull*.

For the visual roles, it has a further implication. If someone passed in an elaborate geometry with extensive materials to `Convex`, we would throw out all of those materials and textures because they don't contribute to the definition of the convex hull. The only way to control the color of the `Convex` shape would be via the `("phong", "diffuse")` property. Up to this point, the mesh, with all of its visualization data, would be taken verbatim into renderers and visualizers (e.g., meshcat). If someone happened to define a *visual* geometry using `Convex`, this kind of change would change the appearance of the geometry. It would cease to be the arbitrary input mesh, and be the flat-shaded, single-colored convex hull.

Note: they could always restore the visualization of the model by passing the same file to a `Mesh` instead of a `Convex`.

The single greatest value is that `Convex` now has a single behavior across all roles that is easily described. Furthermore, it better differentiates `Convex` from `Mesh`. And that distinction would become even more pronounced as we finally finish implementing the `Mesh` type (i.e., allowing point contact with an arbitrary .obj file).

**Comment by jwnimmer-tri** [comment]
This seems OK to me.

For some users, it might help here to explain that the `<drake:declare_convex/>` element in input files (SDFormat, URDF) is the relevant question here.  In case you have `<visual>` meshes marked with that element, their appearance may change in visualizers and render engines.
