### ISSUE TITLE
Meshcat animations

### ISSUE THREAD

**Issue by SeanCurtis-TRI** [RobotLocomotion/drake#21139]
### What happened?

During the effort of implementing a solution to #19142, we became aware of a number of quirks with the animation mechanism.

The goal of this issue is as follows:
  1. Enumerate the current behavior (at the time the issue was authored).
  2. Determine if that behavior is intended/acceptable and if our documentation is sufficient to the behavior.
  3. Determine if there's any future work we need to do to change the behavior/documentation.

## Current behavior

TBD (Ran out of time today, I'll come back to fill this in later. This is a concrete placeholder to remind myself to capture this. Harass me if you don't see it.)

**Comment by jwnimmer-tri** [comment]
> Harass me if you don't see it.

Ping.

**Comment by jwnimmer-tri** [comment]
Per f2f: closing as currently unactionable.
