### ISSUE TITLE
msan reporting uninitialized values in Bullet

### ISSUE THREAD

**Issue by david-german-tri** [RobotLocomotion/drake#2114]
This is likely another compile/link flag issue, but needs investigation.  See #2016 for history.

https://drake-cdash.csail.mit.edu/viewDynamicAnalysisFile.php?id=2718

**Comment by jamiesnape** [comment]
Why do you think it is a linker issue?

**Comment by david-german-tri** [comment]
No reason other than that it's in an external.  I hope to actually look at it today.

**Comment by david-german-tri** [comment]
Aside: We currently have 18 msan failures like this one in `getPairCache`, 5 from [lcm_parse_url](https://drake-cdash.csail.mit.edu/viewDynamicAnalysisFile.php?id=2731), and 1 [assertion failure](https://drake-cdash.csail.mit.edu/viewDynamicAnalysisFile.php?id=2719)

**Comment by sherm1** [comment]
@amcastro-tri, does this look like a bug in Bullet to you?

**Comment by amcastro-tri** [comment]
I would need to investigate further. I'll talk to @david-german-tri since he was involved in this.

**Comment by jwnimmer-tri** [comment]
The original report is no longer available from CDash, and we're not planning on using Bullet in new code.  No reason to keep this open.
