### ISSUE TITLE
Allow User to Set SolverOptions for IrisInConfigurationSpace

### ISSUE THREAD

**Issue by cohnt** [RobotLocomotion/drake#21150]
Currently, there's no way for the user to specify solver options to be applied to the counterexample searches used by IrisInConfigurationSpace. For example, if I want to set the feasibility or optimality tolerances in SNOPT to be loose, I don't have such an option. This would be useful for generating rough candidate regions, where we don't need such tight tolerances or guarantees.

cc @rhjiang @wernerpe

**Comment by EricCousineau-TRI** [comment]
per platform checklist, assigning @hongkai-dai for delegation

**Comment by hongkai-dai** [comment]
I will send a PR later.
