### ISSUE TITLE
Nested Class CollisionElement Not Supported

### ISSUE THREAD

**Issue by liangfok** [RobotLocomotion/drake#2115]
Here's the warning being reported by the compiler (gcc/linux):

```
drake/systems/plants/RigidBody.h:142: Warning 325: Nested class not currently supported (CollisionElement ignored)
```

I believe the best fix for this is to move `CollisionElement` into its own .h/cc files.

Here is a sequence of commands that you can execute to replicate the warning:

```
$ cd [drake distro]/drake/
$ rm -rf pod-build
$ make -j8
```

**Comment by sherm1** [comment]
I agree this should be moved. @amcastro-tri is working to clean up this mess. But I'm curious as to whether this is a new problem and what compiler is complaining about nested classes -- those have been supported for a long time.

**Comment by liangfok** [comment]
I don't believe it's a new problem because I recall seeing the warning for months now. Here's the compiler I'm using that resulted in the above warning being printed:

```
$ /usr/bin/gcc-4.9 --version
gcc-4.9 (Ubuntu 4.9.3-8ubuntu2~14.04) 4.9.3
```

**Comment by liangfok** [comment]
**Update:** I also see this warning on OS X. 

```
$ clang --version
Apple LLVM version 7.3.0 (clang-703.0.29)
Target: x86_64-apple-darwin15.4.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

**Comment by jwnimmer-tri** [comment]
This is a swig warning, not a compiler warning.  I don't think it matters, other than possibly suppressing it to tidy up the default build output.

**Comment by jwnimmer-tri** [comment]
I am going to take a crack at this; the CDash board is always polluted by this warning.
