### ISSUE TITLE
merge QPController logic with LeggedRobot class

### ISSUE THREAD

**Issue by RussTedrake** [RobotLocomotion/drake#212]
I think we should relate the systems/controllers/QPController to the LeggedRobot class in systems/robotInterfaces. The user should be able to describe the feet only once to be a LeggedRobot, and you should be able to use all that information here (though maybe you want something a little more general, which also declares the hands, etc).

And even though the QPController is a system, and therefore needs it's own class, you could have a method in LeggedRobot like constructQPController(), which constructs an instance of this class.

The LeggedRobot class is also going to be the home of all of the ZMP code, etc, so it should be able to set up the QPControllerData for you (directly from the planner, etc)

**Comment by jwnimmer-tri** [comment]
I can't quite tell if this is related only to MATLAB software (and thus should be closed along with #6369), or if its still relevant to the C++ and new-bindings.  Thoughts?

**Comment by RussTedrake** [comment]
i think it's safe to close.  @siyuanfeng-tri has already generalized the language to "inverseDynamicsController" in his c++ implementation.  We will necessarily revisit the "LeggedRobot" api logic when we decide to pursue it in c++.
