### ISSUE TITLE
CI: Upgrade to CDash 3.4

### ISSUE THREAD

**Issue by BetsyMcPhail** [RobotLocomotion/drake#21203]
The CI CDash instance is currently at version 3.2. Update to CDash 3.4 after it is released (expected at the beginning of April).

Prior issue: #19605

**Comment by jwnimmer-tri** [comment]
Update: the rc is ready now, but our plan is to wait for the final release until we upgrade our Drake infra.

**Comment by BetsyMcPhail** [comment]
CDash has been updated to 3.4.2
