### ISSUE TITLE
CI: Downgrade xz on provisioned ARM Mac images

### ISSUE THREAD

**Issue by BetsyMcPhail** [RobotLocomotion/drake#21239]
Both provisioned Ventura and Sonoma images are using xz 5.6.0. Out of an abundance of caution, downgrade to 5.4.6.

Note that unprovisioned images were downgraded when brew reverted to 5.4.6.

Linux images no longer use xz.

For background, see https://github.com/orgs/Homebrew/discussions/5243

**Comment by williamjallen** [comment]
Both provisioned images have been rebuilt, and are now using xz 5.4.6.
