### ISSUE TITLE
Website deployment updates

### ISSUE THREAD

**Issue by jwnimmer-tri** [RobotLocomotion/drake#21259]
I received the following email from GitHub.  We should investigate and see whether / what changes we need to make.

---

Hello,

We are writing to inform you about an important update regarding GitHub Pages.

What is happening?

Delivering on our continued commitment to enhance security, protect your data, and deliver an overall improved experience, we will be phasing out our legacy pagesworker architecture by the end of June 2024.

What is replacing legacy pagesworker?

Since August 2022, GitHub Pages sites have been built and deployed with GitHub Actions. However for repositories where Actions is unavailable, we used the legacy pagesworkers for Pages builds and deployments.

Going forward, GitHub Actions will become a requirement for deploying Pages sites that require a build step, such as those utilizing Jekyll. We chose to implement this change because Actions provides developers a modern, secure sandbox that surpasses the capabilities of pagesworker. With Actions you get your choice of operating system, log streaming, dependency caching, custom gates, and modern CI/CD features. Additionally, we are pleased to announce the general availability of the feature allowing you to delegate Pages deployments to Actions alongside a source branch.

How can I tell if my Pages site will be impacted?

If your Pages site is being built by the legacy infrastructure, a warning message will be displayed in your Pages settings starting today. Note that the vast majority of pages sites have already been leveraging Actions. We only fall back to the legacy build infrastructure if Actions is unavailable in your repository.

We understand that change can be challenging, and we apologize for any inconvenience this may cause. Our priority is to continue delivering a more secure platform for all of our users, and we appreciate your understanding as we make these necessary adjustments.

If you have any questions or concerns about this announcement, please don't hesitate to reach out to our support team for assistance. We are here to help and ensure a smooth transition for all our users.

Thank you for being a valued member of the GitHub community.

**Comment by jwnimmer-tri** [comment]
FYI https://github.com/RobotLocomotion/RobotLocomotion.github.io/

**Comment by mwoehlke-kitware** [comment]
If I am understanding correctly, the only way to serve pages via GitHub going forward is to use a GitHub Action to publish them (even if all you're doing is serving up the repository contents).

Do we have any concerns enabling actions on the RobotLocomotion.github.io repo?

Note: I'm not sure how that repository is managed, but we probably need to be able to add `.github/` to it.

**Comment by jwnimmer-tri** [comment]
> Do we have any concerns enabling actions on the RobotLocomotion.github.io repo?

Sounds fine, go ahead.
