### ISSUE TITLE
Odd error message from snoptmex

### ISSUE THREAD

**Issue by samkhal** [RobotLocomotion/drake#2127]
I'm running into an odd error message from snoptmex: "F has incorrect row dimensions 101. Should be length 51". However, none of the variables that are getting passed to it have those dimensions, as you can see from my workspace. I'm not sure this has to do with Drake, but was wondering if anyone knew what might be causing this.

This doesn't relate to Atlas; I'm trying to run planFootsteps for my own biped.

 ![Image of Error](https://i.imgur.com/0nvwXVo.jpg)

**Comment by jwnimmer-tri** [comment]
There's some chance that the now-merged #2133 fix is related?

**Comment by RussTedrake** [comment]
Actually, those changes are completely independent for now.

**Comment by hongkai-dai** [comment]
It is complaining that the argument of your `nonlcon` has incorrect dimension. It probably has dimension 101 or 100. Could you evaluate your `nonlcon` at `x0` and check the return arguments?

**Comment by samkhal** [comment]
I've since adjusted unrelated parameters that led to this error disappearing, and I can't seem to reproduce it again. I'll close the issue for now, then.
