### ISSUE TITLE
Some Unit Tests Employ Random Irreproducible Test Cases

### ISSUE THREAD

**Issue by liangfok** [RobotLocomotion/drake#2130]
Two unit tests that come to mind are:

1. drake/systems/plants/test/compareRigidBodySystems.cpp
2. drake/util/test/testDrakeGeometryUtil.cpp (Related: https://github.com/robotlocomotion/drake/pull/2124#issuecomment-212492719)

There may be more. All unit tests should be deterministic.

@jwnimmer-tri I'll assign this to you so you can dole it out to the appropriate person to fix (feel free to bounce it back to me).

**Comment by jwnimmer-tri** [comment]
While I appreciate the sentiment, I am disinclined to do anything about this until (1) the test is otherwise being functionally enhanced, which is a good time to fix additional deficiencies, or (2) if it is flaking a lot in CI.

**Comment by liangfok** [comment]
OK I shall close this until the time is right.
