### ISSUE TITLE
New images for clang-15

### ISSUE THREAD

**Issue by jwnimmer-tri** [RobotLocomotion/drake#21348]
For all Provisioned images in CI (both macOS and Ubuntu), we'll need a refresh to match #21339.  Because the Drake PR merge and the Provisioned swap-in must happen in lockstep or else builds will fail, we'll need to coordinate the two activities.

Please prepare the images when you can.  When you're ready to deploy, either Sherm or I can force-merge the PR to skip the pre-merge checks (that are currently failing), if that helps.

**Comment by BetsyMcPhail** [comment]
The jammy provisioned image is also ready.

**Comment by BetsyMcPhail** [comment]
Images were updated in Jenkins and the PR was merged yesterday afternoon.
