### ISSUE TITLE
Error creating or communicating with child process

### ISSUE THREAD

**Issue by jwnimmer-tri** [RobotLocomotion/drake#2135]
The windows continuous builders are spewing "Error creating or communicating with child process" left and right, for example:
- https://drake-jenkins.csail.mit.edu/view/Continuous/job/windows-msvc-32-continuous-release/139/
- https://drake-jenkins.csail.mit.edu/view/Continuous/job/windows-msvc-32-continuous-release/140/

**Comment by david-german-tri** [comment]
This is also happening to all experimental builds, and therefore is blocking all Drake development.  

Visual studio error code is `D8040`.  Documentation is pretty well nonexistent.  Compiler bugs :tada:

**Comment by david-german-tri** [comment]
@jamiesnape I'm trying to reproduce this.  I've got a local Windows laptop, but it would be better if I could launch and remote into a buildslave VM.  Do you happen to have a recipe for doing that?

Also, if you have any thoughts on the issue itself they would of course be appreciated.  :-)

**Comment by jamiesnape** [comment]
Log into https://us-west-1.console.aws.amazon.com/ec2/v2/home?region=us-west-1 and launch an instance from ami-1ce29d7c. It needs to be in us-west-1 because of issues with the Jenkins EC2 plugin.

**Comment by jamiesnape** [comment]
@billhoffman thinks it may be due to a Windows compiler flag.

**Comment by billhoffman** [comment]
OK, this is most likely the -MP flag I added last night to speed up the builds.  I will remove it.

**Comment by billhoffman** [comment]
Just pushed a new build script up.   Lets see if the next build works.

**Comment by david-german-tri** [comment]
@jamiesnape The AMI number you mentioned appears to be a Linux AMI, and there are no Windows AMIs in us-west-1.  Did you mean ami-18504972 (N. Virginia)?

**Comment by billhoffman** [comment]
Let's see if the MP flag removal fixes it.

**Comment by david-german-tri** [comment]
@billhoffman Indeed, but launching a buildslave to reproduce a failure is something TRI devs need to know how to do anyway, so I want to push forward with it.

**Comment by jamiesnape** [comment]
No, I meant us-west-1 (N. California):

https://us-west-1.console.aws.amazon.com/ec2/v2/home?region=us-west-1#Images:sort=name

You cannot use us-east-1 without risking the integrity of the build farm.

**Comment by jamiesnape** [comment]
Sorry, I copied the wrong AMI. One moment.

**Comment by jamiesnape** [comment]
ami-50e09f30

**Comment by jwnimmer-tri** [comment]
I believe this is fixed now that `/MP` or whatever was removed?

**Comment by billhoffman** [comment]
Yes, /MP was removed and it fixed the problem, we are back to single threaded builds...
