### ISSUE TITLE
Superbuild failure in spotless, when matlab is not installed

### ISSUE THREAD

**Issue by david-german-tri** [RobotLocomotion/drake#2138]
From @jwnimmer-tri:  a clean superbuild with `env PATH=/usr/lib/ccache:$PATH CXX=g++-4.9 CC=gcc-4.9 make options (ceceg) && env PATH=/usr/lib/ccache:$PATH CXX=g++-4.9 CC=gcc-4.9 make -j8` randomly dies in superbuild externals for no discernable reason.  I eventually just gave up, did it under -j1, and now just use -j8 in drake.

**Comment by jamiesnape** [comment]
We run `-j8` on non-MATLAB Ubuntu CI builds.

**Comment by jwnimmer-tri** [comment]
But CI doesn't run `make` like I do, does it?  It runs `cmake`?

**Comment by jamiesnape** [comment]
Which runs `make -j8` under the hood.
```cmake
set(CTEST_CMAKE_GENERATOR "Unix Makefiles")
set(CTEST_BUILD_FLAGS -j8)
```

**Comment by jwnimmer-tri** [comment]
Somehow, even though I don't have matlab, spotless is still trying to get involved, and of course is not working.  I am working to find a clear reproduction recipe.

**Comment by jwnimmer-tri** [comment]
Here's my steps on Ubuntu 14.04 without matlab installed:
 ```
jwnimmer@call:~/tmp$ git clone https://github.com/RobotLocomotion/drake.git drake-distro
jwnimmer@call:~/tmp$ cd drake-distro/
jwnimmer@call:~/tmp/drake-distro$ env CXX=g++-4.9 CC=gcc-4.9 make options  #ceceg
Configuring with CMAKE_FLAGS: -DCMAKE_BUILD_TYPE=Release -DPOD_BUILD=TRUE
...
-- CMAKE_INSTALL_PREFIX=/home/jwnimmer/tmp/drake-distro/build
-- Found Java: /usr/bin/java (found version "1.8.0.77") 
Looked for MATLAB but could not find it.
-- Preparing to build cmake with dependencies: 
...
-- Preparing to build spotless with dependencies: 
...
-- Preparing to build drake with dependencies: cmake;eigen;googletest;lcm;bot_core_lcmtypes;libbot;bullet;swig_matlab;swigmake;yaml_cpp
...
-- Build files have been written to: /home/jwnimmer/tmp/drake-distro/pod-build
jwnimmer@call:~/tmp/drake-distro$ env CXX=g++-4.9 CC=gcc-4.9 make download-all
Configuring with CMAKE_FLAGS: -DCMAKE_BUILD_TYPE=Release -DPOD_BUILD=TRUE
-- CMAKE_INSTALL_PREFIX=/home/jwnimmer/tmp/drake-distro/build
Looked for MATLAB but could not find it.
...
-- Preparing to build spotless with dependencies: 
...
jwnimmer@call:~/tmp/drake-distro$ env CXX=g++-4.9 CC=gcc-4.9 make -j8
...
[ 70%] CMake Error at CMakeLists.txt:16 (message):
  Could not find matlab executable
...
[ 11%] make[3]: *** [spotless-prefix/src/spotless-stamp/spotless-configure] Error 1
```

**Comment by jwnimmer-tri** [comment]
Possibly a regression from #2109.  Next question: why didn't CI fail?

**Comment by jwnimmer-tri** [comment]
When I try the make command over and over again with `-j8`, the superbuild continues to fail.

When I remove the `-j8`, the build instead reports:
```
[ 56%] Performing update step for 'download-spotless'
[ 56%] No configure step for 'download-spotless'
[ 56%] No build step for 'download-spotless'
[ 57%] No install step for 'download-spotless'
[ 57%] Completed 'download-spotless'
[ 59%] Built target download-spotless
```
and is totally happy.

**Comment by david-german-tri** [comment]
I can reproduce this on Windows too.

**Comment by sherm1** [comment]
Similar symptoms reported in discussion on #2118. 

/cc @mwoehlke-kitware

**Comment by billhoffman** [comment]
Must be a missing depend.  With j8 it is building in a different order.

**Comment by jwnimmer-tri** [comment]
I guess?  But the fact that anything related to spotless happens at all, when there is no matlab, seems like a bigger issue.

**Comment by david-german-tri** [comment]
@jwnimmer-tri I agree.  I think https://github.com/RobotLocomotion/drake/pull/2146 is the fix, PTAL?

**Comment by billhoffman** [comment]
LGTM

**Comment by jwnimmer-tri** [comment]
Even with #2146 PR fix for this defect, we still need to understand why the CI didn't catch this.  The (for example) most recent [linux-gcc-continuous-release](https://drake-jenkins.csail.mit.edu/view/Continuous/job/linux-gcc-continuous-release/164/consoleFull) does not mention spotless in its build log output, which means that what the CI is doing differs from what the developer instructions were doing, which leads to PRs that pass CI, but break for end-users.  Bad mojo.

**Comment by jamiesnape** [comment]
CI cannot select options interactively, unfortunately.

**Comment by jwnimmer-tri** [comment]
Right.  Either we teach CI to feed keystrokes into 'make options', or we stop telling developers to run 'make options'.

**Comment by mwoehlke-kitware** [comment]
>  Either we teach CI to feed keystrokes into 'make options'

What would that do that can't be accomplished by running CMake twice (once with no options, once with the options to be "interactively selected")?

**Comment by david-german-tri** [comment]
Before we start discussing solutions, I for one could use a little more clarity on why there was a discrepancy in the first place.  @jamiesnape How does WITH_SPOTLESS get set to false in the no-MATLAB CI builds?

**Comment by jamiesnape** [comment]
A cache variable.

**Comment by david-german-tri** [comment]
OK.  And am I correct in thinking that cache variable is derived from this line?

https://github.com/billhoffman/drake/blob/build-scripts/scripts/drake_jenkins_ctest.cmake#L360

**Comment by jamiesnape** [comment]
Yes.

**Comment by david-german-tri** [comment]
OK.  In that case, I claim #2146 is sufficient to resolve the discrepancy between the default `make options` build and CI: now, in both cases, when matlab is off, spotless is off.  

I also think @jwnimmer-tri is right: we need some mechanism to make sure the default superbuild config agrees with the one that `drake_jenkins_ctest.cmake` generates.  Opened https://github.com/RobotLocomotion/drake/issues/2148
