### ISSUE TITLE
GraphOfConvexSets Ignores Certain Infeasible Constraints

### ISSUE THREAD

**Issue by cohnt** [RobotLocomotion/drake#21386]
### What happened?

When GCS takes the perspective of constraints, it is able to ignore trivially-satisfied constraints like x >= -inf. But the [isInf check](https://github.com/RobotLocomotion/drake/blob/a5638694d4a24642cbe2e60f46ce459442531fa1/geometry/optimization/graph_of_convex_sets.cc#L775) used will also trigger for infeasible constraints like x >= inf. Such constraints should make the problem infeasible, but because they're ignored, they remain feasible. (For example, this is why #21383 didn't lead to any test cases failing.)

**Comment by jwnimmer-tri** [comment]
I'll assign +@cohnt for bookkeeping purposes, but others are welcome to jump in and help fix this.
