### ISSUE TITLE
[ci] Config changes for Noble support

### ISSUE THREAD

**Issue by jwnimmer-tri** [RobotLocomotion/drake#21475]
Changes to pre-merge:
- [x] Replace `linux-jammy-clang-bazel-experimental-release` with the noble flavor instead
- [x] Replace `linux-jammy-gcc-bazel-experimental-release` with the noble flavor instead

Changes to Continuous Production:
- [x] Replace `linux-jammy-clang-bazel-continuous-release` with the noble flavor instead (concurrently with pre-merge change, to keep them aligned)
- [x] Replace `linux-jammy-gcc-bazel-continuous-release` with the noble flavor instead (concurrently with pre-merge change, to keep them aligned)

Changes to Nightly Production:
- [x] Add `linux-noble-clang-bazel-nightly-release`
- [x] Add `linux-noble-gcc-bazel-nightly-everything-debug`
- [x] Add `linux-noble-gcc-cmake-nightly-everything-release`
- [x] Add `linux-noble-unprovisioned-gcc-cmake-nightly-packaging`

Changes to Weekly Production:
- None.  (I hope to purge "Weekly" as a concept soonish.)

Change to Staging:
- [x] Add `linux-noble-unprovisioned-gcc-cmake-staging-packaging`

As usual, everything in Production should have an Experimental twin if it doesn't already, and it's fine to have larger matrix of Experimental jobs than we cover in Production.

**Comment by jwnimmer-tri** [comment]
FYI @BetsyMcPhail I just cross-checked the above; no changes.

**Comment by BetsyMcPhail** [comment]
Noble jobs have not been automatically added to https://github.com/RobotLocomotion/drake/tree/jenkins-jobs-experimental, need to investigate before closing this issue

**Comment by jwnimmer-tri** [comment]
Interesting.  Right now, it duplicates the Continuous job, doesn't it?  I'm not sure what I was thinking.  So yes, let's use Everything for the nightly one.
