### ISSUE TITLE
Updated macOS Provisioned images

### ISSUE THREAD

**Issue by jwnimmer-tri** [RobotLocomotion/drake#21473]
We have two PRs on deck that change the macOS prereqs:
- #21454
- #21135

~Just before merging those, we'll want to switch our CI provisioned images to reflect the setup changes.~

~Please prep the images.  I guess you'll need to cherry-pick both branches.  It looks like they should both be OK to pick without any merge conflicts, but I could prepare a single branch in case that helps.~

~Once the image is ready, feel free to remove the "do not merge" labels and merge both PRs.~

**Comment by jwnimmer-tri** [comment]
Per f2f, we decided to merge the changes now and then deploy new images tomorrow.

**Comment by williamjallen** [comment]
The Mac provisioned images have been updated.
