### ISSUE TITLE
LINK : warning LNK4044: unrecognized option '/pthread'; ignored 

### ISSUE THREAD

**Issue by billhoffman** [RobotLocomotion/drake#2147]
https://github.com/RobotLocomotion/drake/blob/master/drake/CMakeLists.txt#L190 unconditionally adds -pthread with no checks on the compiler or platform being used.  Came from this commit:  https://github.com/RobotLocomotion/drake/commit/9f730dad353389947ed3110f3f392285c8bf144e, looks like from @david-german-tri .   Not all platforms/compilers will have this flag.  Windows I know does not.  Might be others in the future.  Could use FindThreads.cmake to get correct flags.

**Comment by sherm1** [comment]
:+1: for fixing this -- it's annoying on Windows.

**Comment by billhoffman** [comment]
There is also a fPIC showing up on windows.   People should not add compiler specific flags into the cmake files without guarding them with checks on the compiler being used.  There are several places where -fPIC is being added without checking the system as well.

**Comment by mwoehlke-kitware** [comment]
Is the `-pthread` is even needed? I removed it, and things are still building...?

Also, (@david-german-tri) what is the purpose of all the `GTEST_FOUND` checks when gtest is `REQUIRED`?

**Comment by david-german-tri** [comment]
I vaguely recall that `-pthread` was a hack to fix the Mac build.  If I'm wrong and it's unnecessary, then please feel free to delete it!

I started adding `GTEST_FOUND` checks to hedge my bets, since there was some pushback on making gtest `REQUIRED`.  No one has complained about that in a while, so perhaps we can drop them.

**Comment by mwoehlke-kitware** [comment]
> I vaguely recall that `-pthread` was a hack to fix the Mac build. If I'm wrong and it's unnecessary, then please feel free to delete it!

I'll remove it and check the CI once there is a PR. If it breaks, I'll add a proper (or at least platform-specific) fix.

> I started adding `GTEST_FOUND` checks to hedge my bets, since there was some pushback on making gtest `REQUIRED`.  No one has complained about that in a while, so perhaps we can drop them.

I probably won't be so ambitious as to systematically remove them :smile:; just wanted to make sure I wasn't missing something.

Thanks.
