### ISSUE TITLE
repack_deb support for Noble

### ISSUE THREAD

**Issue by jwnimmer-tri** [RobotLocomotion/drake#21488]
Refer to the crash in the [linux-noble-unprovisioned-gcc-cmake-nightly-packaging job](https://drake-jenkins.csail.mit.edu/view/Production/job/linux-noble-unprovisioned-gcc-cmake-nightly-packaging/).

As of Noble, there is no longer any `lsb_release.py` module offered for us to import.  Instead, we'll either need to open `/etc/lsb-release` and read out the `DISTRIB_CODENAME` or subprocess call `/usr/bin/lsb_release -cs`.

**Comment by mwoehlke-kitware** [comment]
FYI, LSB hasn't been updated since 2015 and is effectively deprecated. Ubuntu seems to be holding onto its corpse, but in the longer run, we should consider moving away from it.
