### ISSUE TITLE
Ensure the default superbuild config cannot drift away from drake_jenkins_ctest.cmake

### ISSUE THREAD

**Issue by david-german-tri** [RobotLocomotion/drake#2148]
As discussed on #2138, we need a mechanism that ensures the options selected by default in the superbuild are covered by the corresponding cases in `drake_jenkins_ctest.cmake`.

**Comment by jamiesnape** [comment]
One problem is that options are the superbuild are not especially logical. Many MATLAB only related options are ON even without MATLAB. Spotless is just about the only thing that is set correctly now.

**Comment by david-german-tri** [comment]
I believe this was done in https://github.com/RobotLocomotion/drake-ci/pull/27.
