### ISSUE TITLE
The `new_release` script reports the incorrect version for ros_xacro_internal

### ISSUE THREAD

**Issue by BetsyMcPhail** [RobotLocomotion/drake#21535]
### What happened?

While doing the monthly external upgrades as part of #21507, `bazel-bin/tools/workspace/new_release` reported that: `ros_xacro_internal needs upgrade from 2.0.10 to xacro-1.7.5` The version to upgrade to should be 2.0.11.

**Comment by jwnimmer-tri** [comment]
Best guess, we need to update this pattern to ignore those really old tags that start with `xacro-...`:
https://github.com/RobotLocomotion/drake/blob/7228fd95e301bf0bea212bca23c60b42a6989b63/tools/workspace/new_release.py#L78

**Comment by BetsyMcPhail** [comment]
Related to this, I've been caught twice by the Gymnasium update to `v1.0.0a1`. The new_release script should ignore alpha/beta/pre-releases.

**Comment by mwoehlke-kitware** [comment]
> The new_release script should ignore alpha/beta/pre-releases.

We do that for `["alpha", "beta", "rc", "pre"]` in `_is_ignored_tag`. The parsing is fairly dumb (it just checks if those strings are *anywhere* in the commit), so I don't think you'd want to add `a` to the global ignore list, but this looks like a good case for adding a rule to `_IGNORED_TAGS`.
