### ISSUE TITLE
Run OS X MATLAB builds on pull requests

### ISSUE THREAD

**Issue by jamiesnape** [RobotLocomotion/drake#2155]

**Comment by jwnimmer-tri** [comment]
@billhoffman I do not see mac_matlab in [experimental](https://drake-jenkins.csail.mit.edu/job/experimental/) yet?

**Comment by david-german-tri** [comment]
@jwnimmer-tri I suggested we only run mac_matlab and windows_matlab on continuous+nightly, and Russ OK'ed it.

**Comment by jwnimmer-tri** [comment]
Ah right, WONTFIX.  Got it, thanks!
