### ISSUE TITLE
Docker release v1.30.0

### ISSUE THREAD

**Issue by jwnimmer-tri** [RobotLocomotion/drake#21573]
Please manually tag docker images and upload the releases to S3:
- https://github.com/RobotLocomotion/drake/releases/tag/v1.30.0

**Comment by jwnimmer-tri** [comment]
Once you finish this, please check that #21576 works as expected now, and we can close that issue as well.

**Comment by BetsyMcPhail** [comment]
After following the [Add a package](https://github.com/RobotLocomotion/drake/tree/master/tools/release_engineering/dev#optional-add-a-package) section of the Docker / Apt / S3 Release Process documentation, I confirmed that Noble apt packages are now available.

Docker / S3 artifacts have also been uploaded for all platforms.
