### ISSUE TITLE
HybridDrakeSystem get state frame for each mode

### ISSUE THREAD

**Issue by hongkai-dai** [RobotLocomotion/drake#2169]
Currently when we call `getStateFrame` for a `HybridDrakeSystem` (for example, a SLIP model), what it returns is the state frame of mode 1. This has a problem if different modes have a different state frames. Alternatively, we can get the state frame of each of the modes, using `getMode(mode_num).getStateFrame`, but what it returns does not include the discrete state (the mode number). I believe the correct solution is to overload the `getStateFrame/getOutputFrame` method for `HybridDrakeSystem`, and pass the mode number as the input argument to those functions. So
```
SLIP.getStateFrame(stance_mode_number)
```
will return a frame like `[stance_mode_number;r;theta;r_dot;theta_dot;x_toe]`, with 6 states
```
SLIP.getStateFrame(flight_mode_number)
```
will return a frame like `[flight_mode_number;x;y;xdot;ydot]`, with 5 states

**Comment by RussTedrake** [comment]
Seems reasonable to me.

**Comment by hongkai-dai** [comment]
@RussTedrake , this was a problem in the MATLAB code, do we want to fix the MATLAB code?

**Comment by RussTedrake** [comment]
if it’s not blocking anybody and is not a trivial fix, then let’s resolve this as “won’t fix”.

**Comment by hongkai-dai** [comment]
won't fix
