### ISSUE TITLE
New macOS CI provisioned images

### ISSUE THREAD

**Issue by jwnimmer-tri** [RobotLocomotion/drake#21699]
At some point after all of the macOS Nightly Unprovisioned builds are passing (possibly as early tomorrow morning?), we should refresh the Provisioned images with all of the latest updates from Homebrew and Drake's install_prereqs.

**Comment by williamjallen** [comment]
Unless anyone has objections to doing so, I'll plan to build new provisioned images on this Friday, July 12.

**Comment by williamjallen** [comment]
The provisioned images were updated today, July 12.
