### ISSUE TITLE
Parallelize the Preprocessing in GraphOfConvexSets

### ISSUE THREAD

**Issue by cohnt** [RobotLocomotion/drake#21705]
The optional preprocessing stage of GraphOfConvexSets involves solving a small linear program for every edge in the graph. This seems like an obvious target for parallelization -- up to n programs could be solved in parallel (with n threads).

The speedup for this would be very significant in some of the problems I've dealt with. In these cases, the presolve takes a long time, but results in a relatively easy and quick-to-solve GCS problem. But skipping the presolve leaves a much harder GCS problem, leading to a host of problems.

I'll self-assign this for now, since I've been meaning to learn to use multithreading (and I need it to tackle #21351, which is also assigned to me). But someone else can feel free to jump in if they want it done sooner.

**Comment by RussTedrake** [comment]
I think we should land #17024 before we do this. It will potentially change the form of the computation pretty significantly.
