### ISSUE TITLE
[render_vtk] Remove X server requirement

### ISSUE THREAD

**Issue by jwnimmer-tri** [RobotLocomotion/drake#21700]
(This was split out of #21050.)

**Is your feature request related to a problem? Please describe.**

There's no real reason for an X server to be a strict requirement for this renderer. It makes it harder to deploy to headless environments for containerized environments.

**Describe the solution you'd like**

Build VTK and RenderEngineVtk with EGL support, and provide a `RenderEngineVtkParams` config option to select EGL instead of GLX.

**Describe alternatives you've considered**

Users can do `xvfb` but that does non-HW-accelerated rendering and would be a bottleneck.

**Comment by jwnimmer-tri** [comment]
See https://github.com/RobotLocomotion/drake/issues/21050#issuecomment-2028311291 for a WIP idea.

**Comment by jwnimmer-tri** [comment]
> Build VTK and RenderEngineVtk with EGL support, ...

What we're looking for from Kitware is this part.  It's OK to hard-code the rendering to EGL during that initial prototyping.

> ... and provide a RenderEngineVtkParams config option to select EGL instead of GLX.

If this part is too high of a learning curve for Kitware people, TRI people can collaborate on adding the params flag and wiring it up.

**Comment by sankhesh** [comment]
Thank you for clarifying @jwnimmer-tri. I'll hope to have the initial build available for prototyping soon. We can then iterate over the flags required for switching between engines.

**Comment by jwnimmer-tri** [comment]
With EGL, setting `show_window = True` will be a no-op, because our EGL will always be offscreen.

Then, get all the tests passing and open a draft PR.

For for the RenderEngineVtkParams config flag for which backend to use, we should allow it to be blank, in which case Drake gets to choose a default.  On macOS, it _must_ be blank because neither GLX nor EGL are wired up for macOS within Drake.  (We won't have a "Cocoa" string option.)

**Comment by jwnimmer-tri** [comment]
This issue is becoming ever-more important to TRI.  Now that we're back after the holiday, anything we can do to help move this faster would be appreciated.

**Comment by jwnimmer-tri** [comment]
I think TRI would be happy to help give ideas and/or debug it (and I'll \CC @SeanCurtis-TRI who will probably have better answers than me), but surely we can't do that in the absence of any code?   Please open a (draft) pull request with the code, so we have somewhere to start from.  It's fine if the code is unfinished / unclean for now.

**Comment by sankhesh** [comment]
I've pushed my debug branch here: https://github.com/RobotLocomotion/drake/compare/master...sankhesh:drake:egl-rebased

Yes, I also think that there's something weird going on with the `ShallowCopy`. I realized that there are two props in the scene - a plane and a sphere. I did a couple of experiments and realized that for some odd reason, the order in which the cloned props are added to the viewport matters. In the latest changes on my branch referenced above, I tricked it to add the sphere after the plane and that seems to work. This is abnormal behavior for vtk. The order of prop addition shouldn't matter in a 3D view. And I know that this is not a EGL or vtkEGLRenderWindow limitation since the baseline case renders the two props fine.

The branch above also writes out the rendered views as png files so I could introspect.

**Comment by SeanCurtis-TRI** [comment]
Let me know if you definitively want me to explore. I'll wait til I hear from you to avoid duplication.

**Comment by sankhesh** [comment]
Yes please take a look. I'm trying to decipher the vtk usage as I debug but it would be much faster for you. If you don't see anything major, I can try reproducing it with a minimal example outside of drake.

**Comment by SeanCurtis-TRI** [comment]
Ok, I've pullsed your branch. From the earlier post, it looks like things have moved a bit. Obviously, now the sphere appears. But it isn't illuminated in the same way. I'm getting the following images. Can you confirm that you're getting the same?

Baseline:
![w_0](https://github.com/user-attachments/assets/f46c3f48-89cd-4b1b-b166-665d64a899db)

CLone:
![w_1](https://github.com/user-attachments/assets/1ac7bd26-2759-4088-93d1-670e7f353ef9)

**Comment by SeanCurtis-TRI** [comment]
BTW My first guess is that this  isn't a material or geometry problem. I'm guessing it's a light problem. I'll let you know how it goes.

**Comment by SeanCurtis-TRI** [comment]
Hmmmm....when I reconfigure the render engine to have a directional light shining from the side, the two images differ even more:

![baseline](https://github.com/user-attachments/assets/d0bc11cb-0cd7-4e64-a12c-153ea0473c14)

![clone](https://github.com/user-attachments/assets/74039a75-f1fd-40d5-a83c-d00b6972dcae)

So, something more fundamental is happening. So, what would account for the darker rim *and* the reversed direction?

**Comment by SeanCurtis-TRI** [comment]
And yet another pertubation -- if I displace the camera a bit (so the sphere is no longer centered), I get:

Baseline
![baseline](https://github.com/user-attachments/assets/2e8d0505-f382-45bb-bd99-512010ef6658)

Clone
![clone](https://github.com/user-attachments/assets/26bfcf7c-a6f8-46d4-8d14-42b02fdccc87)

The mystery deepens.

**Comment by SeanCurtis-TRI** [comment]
The face culling we're seeing in the clone happens in the depth image as well. (Presumably it happens in the label image, but beacuse we can see through and see the other side, it doesn't appear in the rendered label image.

The curios thing is that the image as the faces get "removed", what is revealed is the correct rendering. (Same for the depth image.) So, it's like the mapper is getting something backwards...all normals flipped? But then as the relationship between camera and geometry changes, some faces get culled away and we see through to the correct faces. (Note: I tried toggling two-sided shading in the renderers, and it made no difference to the rendered output.)

**Comment by SeanCurtis-TRI** [comment]
If I *delete* the original engine prior to rendering, the cloned rendering comes out exactly right. The clone shares *some* data with the original, either it's too much or not enough.

**Comment by SeanCurtis-TRI** [comment]
FYI This feels like it might be related to #20002. Clones fighting each other. The fight with the EGL renderer may be different than the fight with the OpenGL renderer, but fights are still happening? It may simply be that the current test that is failing now was insufficiently sophisticated to reveal the failure. Furthermore, our usage may also be contributing not falling in the trap even though Drake has an original `RenderEngine` (the model) and a clone (in the context) active during simulation. We only ever render on one of those render engines, so we don't observe conflict.

**Comment by SeanCurtis-TRI** [comment]
Ok, it's definitely interference between the two render engines.

I changed the test to do the following:

1. Create original render engine.
2. Clone it.
3. Render from clone
4. Render from original
5. Render from original again
6. Render from clone again

The first rendering is correct, the second is messed up, the third is correct again. Surprisingly, the fourth is also correct.

The same thing happens if I flip the render engines in steps 3-6.

So, it seems like one RenderEngine is updating the VTK state for itself, the other accepts it (in some sense) even though it isn't quite appropriate for it. But after one rendering, it gets a chance to correct for itself. But those corrections appear to stick? I'm not sure if that's completely true or if there's some sequence of further renderings that would show further corruption of the image.

I'm going to try this same test on the original OpenGl implementation to see if we get a similar outcome. Stay tuned...

**Comment by SeanCurtis-TRI** [comment]
Nope. It doesn't happen with the OpenGL-backed RenderEngineGl. So, while we know there's *some* form of interference between the other kind (#20002) it's not the same source as what's effecting us with the egl-backed implementation.

Let me know if you'd like me to push my current experiment to your branch.

**Comment by sankhesh** [comment]
Hi @SeanCurtis-TRI Thank you for your help investigating this. I am still trying to wrap my head around the rendering pipeline in drake. My assumption was that each run is a single render engine - so when I run the vtk tests, vtk is solely responsible for rendering. Based on your last comment about interference, that understanding seems wrong. How do two render engines play with each other?

**Comment by sankhesh** [comment]
> Ok, I've pullsed your branch. From the earlier post, it looks like things have moved a bit. Obviously, now the sphere appears. But it isn't illuminated in the same way. 

Note that in the latest change, I trick the logic to add the cloned sphere **after** the cloned plane to the renderer. Without this trick, the sphere doesn't show up. I did a poor job explaining this in https://github.com/RobotLocomotion/drake/issues/21700#issuecomment-2332173519 but essentially, there is something fundamentally flawed with the *cloned* renderer itself. The order of actor addition doesn't determine depth/visibility/occlusion - point coordinates and opacity do.

**Comment by sankhesh** [comment]
> 
> Let me know if you'd like me to push my current experiment to your branch.

Yes, please free to.

**Comment by SeanCurtis-TRI** [comment]
- RE: pushing my current experiment to your branch
  - I don't believe I have permissions. I've tried pushing and get the following response:
```bash
 ! [remote rejected]       egl-rebased -> egl-rebased (permission denied)
error: failed to push some refs to 'github.com:sankhesh/drake.git'
```

- RE: Interference between a `RenderEngineVtk` and its clone.
 - Ultimately, this comes down to the [`RenderEngineVtk` copy constructor](https://github.com/RobotLocomotion/drake/blob/master/geometry/render_vtk/internal_render_engine_vtk.cc#L497-L533).
    - The newly constructed engine instance
        - [Builds its own pipelines](https://github.com/RobotLocomotion/drake/blob/master/geometry/render_vtk/internal_render_engine_vtk.cc#L500-L502).
        - [Initializes those new pipelines](https://github.com/RobotLocomotion/drake/blob/master/geometry/render_vtk/internal_render_engine_vtk.cc#L506).
        - But gets *shallow copies* of all of the geometry data ([via calling `ShallowCopy` on every actor](https://github.com/RobotLocomotion/drake/blob/master/geometry/render_vtk/internal_render_engine_vtk.cc#L516)).

So, the two independent pipelines (which can be configured independently), nevertheless share data. We've got two possible problems:

1. Something is being persisted within the data (`vtkActor`, `vtkMapper`, `vtkSomething` (TM)). (I've seen this in the past where a render pass would mutate the lights while doing its own work, messing up calculations for other render passes).
2. Drake's tracking of those items is creating the entanglement.

I would recommend taking the operations on the VTK code *out* of Drake and running it directly against VTK. BUild the original pipeline, clone it in the same way, perform some renderings and see if they interfere. It'll be tedious. The *best* case scenario is that you observe interference *outside* of Drake (then we know it's something in VTK).

If we *don't* observe interference, there are two possibilities:
 - The extracted test didn't extract enough.
 - Drake is interfering with VTK's natural operations.

I'd propose we do the "extraction experiment" first and see if we're lucky. If it doesn't reveal a corresponding issue, then we can look at the test and persuade all parties that it captured everything Drake is doing with VTK.  After that, we can look at what Drake is doing on top of it.

**Comment by sankhesh** [comment]
@SeanCurtis-TRI Just a quick update that I am still looking into this issue and I think it is just a manifestation of https://github.com/RobotLocomotion/drake/issues/20002. WIth EGL it seems to happen all the time.

**Comment by jwnimmer-tri** [comment]
The PR #22025 mostly finishes this work.  After that, only a few loose ends remain:
- [ ] Hunt down a (nerfed) unit test failure.
- [ ] Default to EGL on Ubuntu.
- [ ] Can EGL work on macOS?
