### ISSUE TITLE
[RgbdSensor] `X_PB_` is not externally accessible

### ISSUE THREAD

**Issue by siddancha** [RobotLocomotion/drake#21788]
### Problem
- In `RgbdSensor`, the member `X_PB_` is private and cannot be accessed externally. However, it can be pretty useful to access it.
- Both [RgbdSensorAsync](https://github.com/RobotLocomotion/drake/blob/fb4a2eb7d5b4332549441a35041126876f9ef728/systems/sensors/rgbd_sensor_async.h#L130-L131) and [SimRgbdSensor](https://github.com/RobotLocomotion/drake/blob/fb4a2eb7d5b4332549441a35041126876f9ef728/systems/sensors/sim_rgbd_sensor.h#L68) expose their X_PB transforms. I don't see a reason why `RgbdSensor` shouldn't also do the same.

### Solution
- It is straightforward to expose the private member `X_PB_` through a const getter function:
  ```c++
  const RigidTransformd& RgbdSensor::X_PB() const { return X_PB_; }
  ```
  similar to `X_BC()` and `X_BD()`.
 - It is also straightforward to create Python bindings for this function.
 
### Pull request
 The above solution is implemented in #21789

**Comment by EricCousineau-TRI** [comment]
Assigning @SeanCurtis-TRI as potential owner; did not see an obvious entry in our component table. Feel free to delegate or reassign.
