### ISSUE TITLE
GCS: GetGraphvizString() bindings cannot accept default `active_path`.

### ISSUE THREAD

**Issue by RussTedrake** [RobotLocomotion/drake#21816]
### What happened?

Calling
```
spp.GetGraphvizString(),
```
alongside the other calls to spp.GetGraphvizString in `bindings/pydrake/geometry/test/optimization_test.py` fails with
```
  File "/home/russt/.cache/bazel/_bazel_russt/a0bdb2099cb05916281dea472bfce61b/sandbox/linux-sandbox/75/execroot/drake/bazel-out/k8-opt/bin/bindings/pydrake/geometry/py/optimization_test.runfiles/drake/bindings/pydrake/geometry/test/optimization_test.py", line 808, in test_graph_of_convex_sets
    spp.GetGraphvizString(),
TypeError: GetGraphvizString(): incompatible function arguments. The following argument types are supported:
    1. (self: pydrake.geometry.optimization.GraphOfConvexSets, result: pydrake.solvers.MathematicalProgramResult = None, options: pydrake.geometry.optimization.GcsGraphvizOptions = GcsGraphvizOptions(show_slacks=True, show_vars=True, show_flows=True, show_costs=True, scientific=False, precision=3), active_path: list[pydrake.geometry.optimization.GraphOfConvexSets.Edge] = None) -> str
    2. (self: pydrake.geometry.optimization.GraphOfConvexSets, result: pydrake.solvers.MathematicalProgramResult = None, show_slacks: bool = True, show_vars: bool = True, show_flows: bool = True, show_costs: bool = True, scientific: bool = False, precision: int = 3, active_path: list[pydrake.geometry.optimization.GraphOfConvexSets.Edge] = None) -> str
```
The problem appears to be that pybind changes `std::vector<Edge*>*` into `list[Edge]`, and the default value of `nullptr` to `None`, but does not recognize `None` as an viable candidate for `list[Edge]`.  `spp.GetGraphvizString(active_path=None)` also fails.

This appears to have been broken by https://github.com/RobotLocomotion/drake/pull/21749 (fyi @cohnt).  I will PR the fix.

### Version

master

### What operating system are you using?

Ubuntu 22.04

### What installation option are you using?

compiled from source code using Bazel

**Comment by cohnt** [comment]
[This one is partially pybind's fault](https://pybind11.readthedocs.io/en/stable/advanced/functions.html#allow-prohibiting-none-arguments), for not accepting None as an argument for `std::vector<...>*` arguments. Sorry for missing this in the last PR -- I fixed the problem for the other functions, but guess I missed this due to a lack of test cases of the Python bindings. Thanks for PRing the fix!
