### ISSUE TITLE
Python Bindings for ConvexHull

### ISSUE THREAD

**Issue by cohnt** [RobotLocomotion/drake#21835]
[ConvexHull](https://drake.mit.edu/doxygen_cxx/classdrake_1_1geometry_1_1optimization_1_1_convex_hull.html), a new subclass of ConvexSet, was added in #21594. It would be nice to have python bindings for this class and its methods.

**Comment by sadraddini** [comment]
I can add them
+@sadraddini

**Comment by cohnt** [comment]
This was completed by #21849, but for some reason, the issue was not closed.
