### ISSUE TITLE
Updated Ubuntu AMI (zip)

### ISSUE THREAD

**Issue by rpoyner-tri** [RobotLocomotion/drake#21865]
In https://github.com/RobotLocomotion/drake/pull/21863, the `install_prereqs` changed. Please re-bake new Ubuntu Provisioned AMIs for CI and deploy them.

**Comment by BetsyMcPhail** [comment]
Noble and Jammy provisioned images have been updated.

**Comment by rpoyner-tri** [comment]
Thanks for working on this. As I look at the Jenkins board, it looks like the `noble` executors have loaded the new image, but the `jammy` executors have not. Is that something that will get updated automatically?
