### ISSUE TITLE
Upgrade Externals September 2024

### ISSUE THREAD

**Issue by BetsyMcPhail** [RobotLocomotion/drake#21870]
Follow [Semi-automated monthly upgrades](https://github.com/RobotLocomotion/drake/blob/master/tools/workspace/README.md#semi-automated-monthly-upgrades) documentation.

Prior issue: #21759

- [x] #21887
- [x] #21878
- [x] #21888
- [x] #21893
- [ ] ~~#21894~~

**Comment by mwoehlke-kitware** [comment]
All PRs should be up now; nlopt and VTK need additional attention. (The former likely just needs patches fixed, the latter is introducing test failures.)

**Comment by mwoehlke-kitware** [comment]
As it is now October, I'm going to roll over VTK updates to #21979 and close this out.
