### ISSUE TITLE
Add a "timestamp" item to the `info` return value from `DrakeGymEnv.step(...)`

### ISSUE THREAD

**Issue by samzapo** [RobotLocomotion/drake#21899]
It is often helpful to have the simulation timestamp after a call to `env.step()` to, e.g. render a video of image observations with simulation time as the video's timestamp.

https://github.com/RobotLocomotion/drake/blob/59a15c38f3489d3b97406baa9c3b2e3eaa8cea4a/bindings/pydrake/gym/_drake_gym_env.py#L209

**Comment by jwnimmer-tri** [comment]
Given #21900, I'll assign @samzapo on this issue.
