### ISSUE TITLE
macOS Sequoia (15) support / CI

### ISSUE THREAD

**Issue by BetsyMcPhail** [RobotLocomotion/drake#21910]
Prior issue adding Sonoma (14) support: #20339

Tasks:

- [x] Determine when our VM hosting in CI can run Sequoia
- [x] #21978 
- [x] Add initial set of experimental sequoia jobs to d-j-j https://github.com/RobotLocomotion/drake-jenkins-jobs/pull/156
- [x] Update Jenkins cloud configuration from Ventura to Sequoia
- [x] Remove Ventura images from orka cluster
- [x] Create unprovisioned Sequoia images
- [x] Updated drake-ci: setup script, cmake scripts, etc. https://github.com/RobotLocomotion/drake-ci/pull/297
- [x] Fix any issues with unprovisioned jobs setup (so that provisioned jobs can be created)
- [x] Create provisioned Sequoia images
- [x] Fix remaining issues so that all experimental Sequoia jobs pass. PR to disable failing test #22320, tracking issue #22322
- [x] Create Production Continuous and Nightly jobs
- [ ] Update Docs: Add Sonoma to our support matrix. Likewise update the release playbook.

**Comment by williamjallen** [comment]
As per MacStadium's response to my recent [support ticket](https://portal.macstadium.com/support-center/tickets/SERVICE-189160), MacOS Sequoia will not be supported in Orka Cluster until "mid October".

**Comment by williamjallen** [comment]
MacStadium add this update to our ticket today:

> Mid-October is to be expected for Sequoia support as it is coming with Orka 3.2-GA. We are in a release and testing cycle it is closing soon. I will keep this ticket open for more updates as they become available.

**Comment by williamjallen** [comment]
Orka 3.2 is now available, and I have scheduled a meeting for the 21st @ 9:00 AM EST to upgrade our instance.  It is unclear to me what this process requires, so I have reached out to MacStadium to determine if downtime will be necessary.

**Comment by williamjallen** [comment]
The issue was resolved by MacStadium.  MacOS Sequoia unprovisioned jobs are now available for testing.  The old Ventura images have also been removed.

@BetsyMcPhail, all of the tasks in the issue description have been resolved.  Do you want to keep this open until the provisioned images are available, or should we close this now and open new issues for individual tasks as they come up?

**Comment by BetsyMcPhail** [comment]
Thanks @williamjallen. Please keep it open, I will add more tasks for getting jobs to pass, adding continuous and nightly jobs, etc.

**Comment by jwnimmer-tri** [comment]
From the Drake Developers point of view, it's okay now to bake a Sonoma Provisioned images.  All of the remaining fixes we anticipate will be to Drake's code, not Drake's setup scripts.

**Comment by williamjallen** [comment]
Sequoia provisioned images are now available for use.  Closing this ticket since no further work is needed.

**Comment by BetsyMcPhail** [comment]
My checklist had a few items missing! Reopening so that I can finish those.

**Comment by BetsyMcPhail** [comment]
Based on the prior Ventura/Sonoma configurations (documented [here](https://github.com/RobotLocomotion/drake/issues/21978#issuecomment-2388824384)), the Sequoia jobs that need to be created are:

**Continuous**
mac-arm-sequoia-clang-bazel-continuous-release

**Nightly**
mac-arm-sequoia-clang-bazel-nightly-everything-release
mac-arm-sequoia-clang-cmake-nightly-everything-release
mac-arm-sequoia-clang-cmake-nightly-release
mac-arm-sequoia-unprovisioned-clang-bazel-nightly-release

@jwnimmer-tri can you please confirm if this seems reasonable to you. Also, I was going to go ahead and put them into production immediately, with a warning to buildcops.

**Comment by jwnimmer-tri** [comment]
Yes, exactly.  Agreed on both counts.
