### ISSUE TITLE
Cannot close Schunk gripper to 0 position

### ISSUE THREAD

**Issue by hongkai-dai** [RobotLocomotion/drake#21920]
# Symptom 1
If the Schunk gripper is initialized to a non-zero position, and commanded to close the gripper to 0 position, then the gripper will just stay at the current position, as shown in my [branch](https://github.com/hongkai-dai/drake/tree/schunk_gripper_close_init). To reproduce this error, run the test
```
bazel test //manipulation/schunk_wsg:build_schunk_wsg_control_test
```
Note that if we command the gripper to close to 10mm, it works fine. Only 0mm position command causes problem.

The reason is that the context of the schunk gripper` context.get_discrete_state(0).last_target_position()` is initialized to 0. So if the target position is also 0, then in this if-else branch https://github.com/RobotLocomotion/drake/blob/b5c15082fe608f7f49fe779757ce53cdfe97148c/manipulation/schunk_wsg/schunk_wsg_trajectory_generator.cc#L91-L101
`last_traj_state->last_target_position() - target_position` = 0, and the code will not enter into the `if` branch that updates the trajectory, but jumps to the `else` branch. As a result, in `OutputTarget` function, since `trajectory_` is empty (because `UpdateTrajectory()` was not called), the schunk will just set the last position as the target position, as in https://github.com/RobotLocomotion/drake/blob/b5c15082fe608f7f49fe779757ce53cdfe97148c/manipulation/schunk_wsg/schunk_wsg_trajectory_generator.cc#L48-L55

One quick fix is to force calling `UpdateTrajectory()`. But I think a better solution is to default-initialize the context gripper `context.get_discrete_state(0).last_target_position()` to a non-zero value, like kInf?

cc @IanTheEngineer , this is why in the slack discussion https://tri-internal.slack.com/archives/C05N7QM7GGL/p1726093498365569 the gripper doesn't close at the beginning.

# Symptom 2
A closely related symptom happens when I try to re-produce a simulation of the gripper. In the initial simulation, the gripper grasps an object and tries to close the gripper to commanded position 0mm. Because the object is in its way, the finger cannot completely close, and hence the finger position is at 70mm. Now I would like to re-simulate this gripper motion. I set the initial gripper position to 70mm, and set the command position to 0mm. But because `trajectory_` is empty at the start of the simulation, the gripper would just output the current position (70mm) as the target position. The gripper would not apply a gripping force if it wants to keep its current position, and hence the object would fall from the grasp.

**Comment by jwnimmer-tri** [comment]
Possibly easier -- if `trajectory_` is nullptr, then always recompute it?  Don't look at the history in that case.

**Comment by sammy-tri** [comment]
>  if trajectory_ is nullptr, then always recompute it? Don't look at the history in that case.

I'd just go with this fix (and it works).  I can PR or if hongkai wants to add the change to his branch and PR that's fine too.
```
-  if (std::abs(last_traj_state->last_target_position() - target_position) >
-      kTargetEpsilon) {
+  if (!trajectory_ || (
+          std::abs(last_traj_state->last_target_position() - target_position) >
+          kTargetEpsilon)) {
```
