### ISSUE TITLE
Windows buildslaves not coming up for experimental builds

### ISSUE THREAD

**Issue by david-german-tri** [RobotLocomotion/drake#2199]
https://drake-jenkins.csail.mit.edu/job/experimental/1069/compiler=msvc-32,label=windows/console

It looks like the last time we actually got messages from a Windows build was 10:29:

https://drake-jenkins.csail.mit.edu/job/experimental/

@jamiesnape, any idea what's up?

**Comment by jamiesnape** [comment]
Everything seems fine to me. There are eight Windows builds in progress, some of which started minutes ago.

**Comment by sammy-tri** [comment]
https://drake-jenkins.csail.mit.edu/job/experimental/1061/compiler=msvc-32,label=windows/console

https://drake-jenkins.csail.mit.edu/job/experimental/1066/compiler=msvc-64,label=windows/console

https://drake-jenkins.csail.mit.edu/job/experimental/1067/compiler=msvc-32,label=windows/console

https://drake-jenkins.csail.mit.edu/job/experimental/1062/compiler=msvc-32,label=windows/console

https://drake-jenkins.csail.mit.edu/job/experimental/1062/compiler=msvc-64,label=windows/console

**Comment by jamiesnape** [comment]
Looks like instance "drake-windows-2016-04-20-c4.4xlarge (i-406077db)" went bad. Not much I can do about that.

**Comment by sammy-tri** [comment]
Does this mean that whatever happened with that instance is not expected to continue?

**Comment by jamiesnape** [comment]
That instance is destroyed now, so yes.

**Comment by david-german-tri** [comment]
Destroyed by manual action on your part, or some watchdog script, or just timing out?

**Comment by jamiesnape** [comment]
Timing out. I am looking at ways of killing bad slaves earlier, but it is a work in progress.

**Comment by david-german-tri** [comment]
If we wanted to kill them manually, is stopping them in the AWS UI good enough?

**Comment by jamiesnape** [comment]
No, you need to delete them in Jenkins.

**Comment by billhoffman** [comment]
Is this still an issue?

**Comment by jamiesnape** [comment]
No. Bad instances are killed automatically.
