### ISSUE TITLE
RigidBodyTree::inverseDynamics bug when acceleration is nonzero

### ISSUE THREAD

**Issue by tkoolen** [RobotLocomotion/drake#2201]
I recently looked over the RigidBodyTree::inverseDynamics code again and found that I had made a mistake that causes the torques returned by inverseDynamics to be wrong when `vd` (the desired acceleration vector) is nonzero. Luckily we've never used it with nonzero `vd` in the rest of the Drake codebase, but it still needs to be fixed of course. Just wanted to report it for now.

**Comment by liangfok** [comment]
Thanks for reporting this. Just wondering what's the logic behind using the name "vd" for "acceleration vector"?

**Comment by sherm1** [comment]
Wild guess: vd = time derivative of velocity?

**Comment by tkoolen** [comment]
Yep.

**Comment by amcastro-tri** [comment]
That's interesting that is never called with non-zero acceleration. What are the uses of this method then?

**Comment by tkoolen** [comment]
Computing the Coriolis, gravity, and external force terms in the equations
of motion.

**Comment by tkoolen** [comment]
I have the time to fix this now and write the corresponding tests. @sherm1, is that OK, or would you prefer to do it yourself? @liangfok, are you actively working on this code?

**Comment by liangfok** [comment]
I am not working on this at this time. Would be great if you can fix this!

**Comment by sherm1** [comment]
> I have the time to fix this now and write the corresponding tests. 

That would be great, Twan!
