### ISSUE TITLE
 Upgrade Externals November 2024

### ISSUE THREAD

**Issue by jwnimmer-tri** [RobotLocomotion/drake#22087]
Follow [Semi-automated monthly upgrades](https://github.com/RobotLocomotion/drake/blob/master/tools/workspace/README.md#semi-automated-monthly-upgrades) documentation.

Prior issue: #21979.

- [x] #22119
- [x] #22082
- [x] #22118
- [x] #22121
- [x] #22129
- [x] #22130
- [x] #22165

**Comment by BetsyMcPhail** [comment]
All updates have been merged, this can be closed.
