### ISSUE TITLE
Create a Drake System That's Able to Publish the Frame Transformation for ROS' /tf Infrastructure

### ISSUE THREAD

**Issue by liangfok** [RobotLocomotion/drake#2211]
See: http://wiki.ros.org/tf

This is necessary to properly view the LIDAR sensor data being published in https://github.com/RobotLocomotion/drake/pull/2126 using  [RViz](http://wiki.ros.org/rviz) and other ROS GUI tools.

It is also needed to view the various models like the car and garage in said GUI tools.

**Comment by liangfok** [comment]
I believe the appropriate component-based system architecture should be:

```
[Drake] →[Robot State Publisher] → [RViz]
```

References:
* http://wiki.ros.org/robot_state_publisher
* http://wiki.ros.org/rviz

**Comment by liangfok** [comment]
I completed the initial `Drake` → `RViz` integration in https://github.com/liangfok/drake/commit/d5cc7a10062d2f53d48af8dc2008cc158fc3fb3c.

The `tf` transforms are being directly published by a Drake system, which are used by `RViz` to visualize the Prius. In the screenshot below, the left GUI is `Drake Visualizer` and the right GUI is `RViz`.

![drake_rviz_integration](https://cloud.githubusercontent.com/assets/1388098/14968836/0b481440-108d-11e6-9099-a1181d365709.png)

The next step is to visualize the LIDAR sensor data in RViz.

**Comment by liangfok** [comment]
I completed the `Drake` + `Prius` + `4 LIDAR sensors` → `RViz` integration in https://github.com/liangfok/drake/commit/51c95802a4b9ac1fb87c4ffaa0f3e0e9c77270e9.

We are now able to visualize the results of the four LIDAR sensors mounted on the Prius in RViz:

![prius_rviz_with_lidar](https://cloud.githubusercontent.com/assets/1388098/14974494/8a118d5c-10c3-11e6-9bca-7ddaae80b5ac.png)

Here's a video showing how the LIDAR sensor data changes as the car drives around in the Stata garage:

[![IMAGE ALT TEXT HERE](https://img.youtube.com/vi/KupilUrFrco/0.jpg)](https://www.youtube.com/watch?v=KupilUrFrco)

The next step is to clean up the code and then issue a PR.

**Comment by jwnimmer-tri** [comment]
Done.
