### ISSUE TITLE
Car and SimpleCarDemo Employ Inconsistent Frame Conventions

### ISSUE THREAD

**Issue by liangfok** [RobotLocomotion/drake#2224]
All car-related demos in Drake should use the same frame conventions for the most critical DOFs, which include the wheel joints, the steering joints, and the frame of the car's root link (which should be the vehicle's chassis).

Currently, a positive steering angle makes the Car demo's car turn left, and the SimpleCar demo's car turn right.

**Comment by jwnimmer-tri** [comment]
I'm partway through fixing this in an upcoming PR.
