### ISSUE TITLE
Add python bindings for ```AffineBall::MakeAffineBallFromLineSegment```

### ISSUE THREAD

**Issue by frouhi** [RobotLocomotion/drake#22250]
**Is your feature request related to a problem? Please describe.**

This function is available in the c++ library (seems to have been added recently), but the python bindings are missing: https://github.com/RobotLocomotion/drake/blob/master/bindings/pydrake/geometry/geometry_py_optimization.cc#L190

**Describe the solution you'd like**

This is a pretty useful function, and it is already implemented, so it would be nice if the python bindings could be added.

**Describe alternatives you've considered**

I'm thinking about workarounds, but given that the function is already implemented, I think adding the bindings is the cleanest solution.

**Additional context**

N/A

**Comment by jwnimmer-tri** [comment]
CC @sadraddini as author of #20645.
