### ISSUE TITLE
add minimal dependencies build to supported configuration 

### ISSUE THREAD

**Issue by RussTedrake** [RobotLocomotion/drake#2227]
and cover it with a nightly build.  this configuration should only use externals which are freely available to all users.  building this only on ubuntu should be sufficient.

potentially also support an "academic" configuration, which would include the additional externals which are free for academics.

official support for these configuration should be documented in sphinx.

**Comment by jwnimmer-tri** [comment]
See also #1923, where I proposed configurations like this, but which was resolved without adding them.  Might be good food for thought as this issue is pursued.

**Comment by david-german-tri** [comment]
This is done.
