### ISSUE TITLE
Wrong date in macOS packaging nightlies

### ISSUE THREAD

**Issue by jwnimmer-tri** [RobotLocomotion/drake#22308]
In the [the log](https://drake-jenkins.csail.mit.edu/view/Packaging/job/mac-arm-sonoma-unprovisioned-clang-cmake-nightly-packaging/73/consoleFull) from last night's nightly packaging build, we can see this:

```
Upload complete: https://drake-packages.csail.mit.edu/drake/nightly/drake-0.0.20241212-mac-arm64.tar.gz
```

It should have said `20241213` not `20241212` (off by one day).

I assume this happens because the timezone in the new images is set incorrectly.

**Comment by williamjallen** [comment]
I just confirmed that the timezone is set to `US/Pacific` in one of the currently running macOS VMs.  I'll investigate further.

**Comment by williamjallen** [comment]
I fixed the timezone in the Xcode base image, rebuilt the entire stack on top of it, and activated the new images in CI.
