### ISSUE TITLE
Need Drake System that Takes as Input ROS ackermann_msgs/AckermannDrive Messages

### ISSUE THREAD

**Issue by liangfok** [RobotLocomotion/drake#2256]
We need a Drake system that can take the steering / throttle commands from [ROS ackermann_msgs/AckermannDriveStamped](http://docs.ros.org/api/ackermann_msgs/html/msg/AckermannDriveStamped.html) and pass them to the controllers in the car simulation. Once we have this, we can perform a close-loop integration with autonomous vehicle A.I. software.

**Comment by liangfok** [comment]
This issue was resolved in commit https://github.com/liangfok/drake/commit/7dbd661dd17e3097f2cea453eea414f90a1297fd.

Here's a video:

[![IMAGE ALT TEXT HERE](https://img.youtube.com/vi/3nyq1Ew_hZE/0.jpg)](https://www.youtube.com/watch?v=3nyq1Ew_hZE)

I'll clean up the code and submit a PR soon. However, PR  https://github.com/RobotLocomotion/drake/pull/2253 should probably get merged first since this builds upon that.

**Comment by liangfok** [comment]
I am waiting for https://github.com/RobotLocomotion/drake/issues/2369 to be closed before proceeding to issue PRs containing Drake systems that interact with ROS.

**Comment by jwnimmer-tri** [comment]
@liangfok I am guessing this should be "backlog" and not "high"?

**Comment by liangfok** [comment]
I'll set it to "medium" since folks are asking for it. It was working in System 1.0 and is now waiting on being ported to System 2.0.

**Comment by jwnimmer-tri** [comment]
Ditto per #1759 comment -- I still advocate for "backlog" here.
