### ISSUE TITLE
drake.mit.edu 404s

### ISSUE THREAD

**Issue by wxmerkt** [RobotLocomotion/drake#2264]
Hi @RobotLocomotion/kitware,
When opening ``drake.mit.edu`` a 404 is returned. ``dig drake.mit.edu`` shows that it's CNAMEd to ``http://robotlocomotion.github.io/``, which works. 

Is it possible that the domain [hasn't been associated properly with GitHub Pages](https://help.github.com/articles/using-a-custom-domain-with-github-pages/)?

- Wolfgang

Related issue: https://github.com/RobotLocomotion/drake/issues/2149

**Comment by jamiesnape** [comment]
Should be fixed now. We had to remove the CNAME file until MIT finished setting up the domain.

**Comment by wxmerkt** [comment]
Thanks @jamiesnape! 👍
