### ISSUE TITLE
 Fix or suppress cpplint warnings for build/include_what_you_use

### ISSUE THREAD

**Issue by jwnimmer-tri** [RobotLocomotion/drake#2270]
We should fix cpplint's `build/include_what_you_use` warnings throughout our code (and/or suppress them on a one-by-one-basis), and then stop suppressing the warning globally in `drake-distro/drake/CPPLINT.cfg`.  This is a break-out from #2064.

Depending on what fixing the errors looks like, we might also decide to permanently suppress this warning globally.  I will follow-up later with more specific recommendation for this particular warning set.

**Comment by jwnimmer-tri** [comment]
These should be pretty easy to fix, and uncontroversial.  Very straightforward.

**Comment by jamiesnape** [comment]
You can use the include-what-you-use job on Jenkins for this.

**Comment by jwnimmer-tri** [comment]
Yes, though note that cpplint is only tagging missing libstdcxx includes, not the full suite of libraries that llvm can find in that build.
