### ISSUE TITLE
 Fix or suppress cpplint warnings for runtime/references

### ISSUE THREAD

**Issue by jwnimmer-tri** [RobotLocomotion/drake#2274]
We should fix cpplint's `runtime/references` warnings throughout our code (and/or suppress them on a one-by-one-basis), and then stop suppressing the warning globally in `drake-distro/drake/CPPLINT.cfg`.  This is a break-out from #2064.

Depending on what fixing the errors looks like, we might also decide to permanently suppress this warning globally.  I will follow-up later with more specific recommendation for this particular warning set.

**Comment by jwnimmer-tri** [comment]
This is a tough one.  I know @sherm1 really wants to use non-const references as function parameters.  I don't think we should allow that (and neither does cpplint).

We should first decide whether we like the rule or not, and them update our cpplint integration to match that decision.

**Comment by sherm1** [comment]
> I know @sherm1 really wants to use non-const references as function parameters

No, I'm willing to change my ways on that. I just never knew it was a problem before!

**Comment by jwnimmer-tri** [comment]
Sounds promising!  (Though I don't have any immediate need to discuss; I'm happy to leave it to a PR-centric discussion or pre-discussion once it becomes relevant.)

**Comment by jwnimmer-tri** [comment]
This is a good onramp candidate, once #3490 is merged.
