### ISSUE TITLE
The 'make test' target should not upload user data to the web

### ISSUE THREAD

**Issue by jwnimmer-tri** [RobotLocomotion/drake#2279]
The `drake-distro/drake/Makefile`'s `make test` target should not upload user data to the web by default (https://drake-cdash.csail.mit.edu/index.php?project=Drake).  It is mean to take users' test result data and publish it for all to see without their consent.

**Comment by david-german-tri** [comment]
This looks pretty trivial to fix.  Testing a solution now.
