### ISSUE TITLE
Drake Documentation Should Specify Default Units and Coordinate Frames Used By Code

### ISSUE THREAD

**Issue by liangfok** [RobotLocomotion/drake#2284]
It will prevent needing to include the units in variable names when they use the default units / frames.

Suggested defaults: http://www.ros.org/reps/rep-0103.html

This should go somewhere in the wiki.

**Comment by jwnimmer-tri** [comment]
This doesn't seem worth keeping open for so long.  Can we add a Doxygen or code_style_guide entry that says "use MKS" and then close this?
