### ISSUE TITLE
Some possible constantness issues identified. 

### ISSUE THREAD

**Issue by amcastro-tri** [RobotLocomotion/drake#2292]
Some constantness issues were identified by @jwnimmer-tri in #2207. Resolving these issues in #2207 would make the PR even bigger of what it already is and therefore this new issue is opened. 
- `RigidBodyFrame::body`: RigidBodyFrame should know what body it belongs to but most likely it should not modify it. Therefore this member should be a constant pointer to a constant RigidBody. 
- `RigidBodyTree::findLink`: this method should probably return a constant pointer.

**Comment by jwnimmer-tri** [comment]
To be clear, on things like findLink, the problem is a const method returning a non-const pointer into our representation.  If calling code wants to get non-const pointers out of us that's fine, but they shouldn't use an object-const method to do it.

**Comment by liangfok** [comment]
Regarding:

> RigidBodyTree::findLink: this method should probably return a constant pointer.

Instead of "return a constant pointer" do you mean "return a pointer to a const member variable"? Or, do you mean "return a const pointer to a const member variable"?
