### ISSUE TITLE
RigidBodyConstraint does not conform to style guide

### ISSUE THREAD

**Issue by liangfok** [RobotLocomotion/drake#2306]
Mostly it's just the locations of the `&` and `*` symbols.

Run `clang-format` to see.

**Comment by liangfok** [comment]
Oops, I mistakenly assigned this to @amcastro-tri thinking he was working on this class. @amcastro-tri, if you are not working on this class, please re-assign it to someone who is.

**Comment by sammy-tri** [comment]
I've been in here lately, I can take a swing at it.  @amcastro-tri, feel free to reassign to me if you like.

**Comment by liangfok** [comment]
Thanks @sammy-tri!

**Comment by amcastro-tri** [comment]
Thanks @sammy-tri!!

**Comment by sammy-tri** [comment]
PR #2325 fixes some of the style guide conformance issues.

**Comment by jwnimmer-tri** [comment]
For whoever next picks up this issue, please start by breaking up RigidBodyConstraint.h/cpp into separate, smaller files (with appropriate snake_case_name.cc).  That will make it easier to iterate on the remaining style fixes.

**Comment by sammy-tri** [comment]
This shouldn't actually be closed yet.  #2325 wasn't nearly enough to fix all the style problems...

**Comment by sammy-tri** [comment]
Removing myself as assignee -- I don't have any more cleanups planned in the near future.

**Comment by sherm1** [comment]
I think it is safe to say we won't be going any further with this cleanup.
