### ISSUE TITLE
Remove Notion of World from RigidBody

### ISSUE THREAD

**Issue by liangfok** [RobotLocomotion/drake#2315]
It should go in the `RigidBodyTree`. Higher-level abstractions like `RigidBodySystem` can know about the "world" abstraction, but not software abstractions at the `RigidBody` level or below.

Here is the review comment that triggered this issue: https://github.com/RobotLocomotion/drake/pull/2303#issuecomment-218277954

**Comment by amcastro-tri** [comment]
@liangfok, I don't think the concept of "world" is anywhere else in `RigidBody` right now. You just introduced this "world-like" member in `RigidBody` in #2303. I'd say you fix it there since it was not introduced yet.

**Comment by liangfok** [comment]
OK I will retake ownership of this issue.
