### ISSUE TITLE
linkname Needs to be Updated to Conform To Style Guide

### ISSUE THREAD

**Issue by liangfok** [RobotLocomotion/drake#2316]
`RigidBody::linkname` should become `RigidBody::link_name_` and ideally should be private with accessors returning a const reference.

Parameters and local variables named `linkname` throughout the code need to become `link_name`.

The Matlab code needs to be updated to match the C++ code.

Since this touches so much code in Drake, I would consider this a major operation.

Here is the review comment that triggered this issue: https://github.com/RobotLocomotion/drake/pull/2303#discussion_r62749558

**Comment by jwnimmer-tri** [comment]
You can change the C++ code, but leave the matlab API the same, via the `*.i` file wrapper specifications.

**Comment by liangfok** [comment]
True, but would it be bad that the C++ and Matlab code diverge in variable names?

**Comment by jwnimmer-tri** [comment]
It's a tradeoff.  To me, leaving matlab alone is probably worth the divergence.  It's essentially the public API of Drake right now.  We could provide both spellings to matlab if we wanted to, though perhaps that is even worse.

**Comment by sherm1** [comment]
@amcastro-tri, I'm assigning this to you since you are modifying RigidBody.

**Comment by amcastro-tri** [comment]
This is actually solved. @liangfok renamed it to a private member `RigidBody::name_` with public setter `set_name()` and getter `get_name()`.
