### ISSUE TITLE
examples/Cars: car_jump.urdf is no longer loadable.

### ISSUE THREAD

**Issue by rpoyner-tri** [RobotLocomotion/drake#2319]
Since the car_sim_lcm program can no longer load URDF format world models, car_jump.urdf is not usable. I propose either translating it to SDF or deleting it and updating the gallery documentation appropriately.

**Comment by liangfok** [comment]
I was able to get the demo to work by re-enabling URDF-based world models. Here are the commands using a `ninja` style build:

```
// Starts the Drake Visualizer.
$ cd drake-build
$ ./install/bin/drake-visualizer &

//  Starts the Steering Command Driver.
$ cd drake-distro/examples/Cars
$ export PYTHONPATH=drake-build/drake/lcmgen/lcmtypes:$PYTHONPATH
$ ./steering_command_driver.py

// Starts the Drake Simulator.
$ cd drake-build/drake
$ ./bin/car_sim_lcm /Users/liang/dev/drake-distro/drake/examples/Cars/models/prius/prius.urdf /Users/liang/dev/drake-distro/drake/examples/Cars/models/car_jump.urdf
```

Here's a screenshot:

<img width="1137" alt="screen shot 2016-06-17 at 12 27 24 am" src="https://cloud.githubusercontent.com/assets/1388098/16140792/6b0e70b4-3422-11e6-89aa-64c40b346f7f.png">
