### ISSUE TITLE
Simplify cmake download-all target

### ISSUE THREAD

**Issue by billhoffman** [RobotLocomotion/drake#2329]
Use ExternalProject_Add_StepTargets to create the download-all target so that you do not have to break the External projects into a project and a project-download.  This will fix a race condition with ninja.

**Comment by bradking** [comment]
The `ExternalProject_Add_StepTargets` feature has been around since CMake 2.8.3, but we need the `NO_DEPENDS` option which has only existed since CMake 3.2.

**Comment by david-german-tri** [comment]
#2487 will close this.

**Comment by david-german-tri** [comment]
From weekly sync: can we just remove the `download-all` target?

**Comment by bradking** [comment]
For reference, this issue as originally recorded was addressed by #2487 and can therefore be closed.

> can we just remove the download-all target?

Perhaps, but IMO we should discuss it in a separate issue to avoid confusion.
