### ISSUE TITLE
Binary File drake/examples/Atlas/test/results_testRunning.mat Is Being Version Controlled

### ISSUE THREAD

**Issue by liangfok** [RobotLocomotion/drake#2337]
Should it be? It seems strange to version control a binary results file.

https://github.com/RobotLocomotion/drake/blob/master/drake/examples/Atlas/test/results_testRunning.mat

**Comment by RussTedrake** [comment]
yes, it was done intentionally.  (the optimization takes a long time, and this test was to evaluate the stabilization).  we might revisit on further cleanup, but will close this for now.
