### ISSUE TITLE
drake/common declarations should be in `drake::` namespace

### ISSUE THREAD

**Issue by sherm1** [RobotLocomotion/drake#2348]
I think that code that goes into the `drake/common` directory should reside in the `drake::` namespace. That seems sufficient to indicate that it is common across Drake. Putting it in `drake::common::` (which I did by rote for [NiceTypeName](https://github.com/RobotLocomotion/drake/blob/master/drake/common/nice_type_name.h#L11)) just mean a lifetime of unnecessary extra typing.

Does anyone think `drake::common::` adds anything useful over `drake::` here?

**Comment by david-german-tri** [comment]
I agree.

**Comment by liangfok** [comment]
I can think of equally strong arguments in either direction and will thus abstain.

**Comment by jwnimmer-tri** [comment]
I can go along with this under two conditions, (1) no other directory populates `drake::` directly, and (2) given an identifier (`NiceTypeName` in this case) it is reasonably clear which `#include` statement it came from (true in this case).
