### ISSUE TITLE
Enable NLOPT on Windows (and in Windows CI)

### ISSUE THREAD

**Issue by david-german-tri** [RobotLocomotion/drake#2351]
There is a third-party CMake file that might be useful.

http://ab-initio.mit.edu/wiki/index.php/NLopt_on_Windows

**Comment by jamiesnape** [comment]
Is this being handled by the optimization team (per the label)? What is the priority? It would probably be best to split the CI part into a different ticket and assign it to me.

**Comment by sammy-tri** [comment]
It's not currently bring handled by the optimization team.  We've actually found some fairly major issues with NLopt, so it might be best to wait on this one until we've found the right strategy going forward.

**Comment by jamiesnape** [comment]
That is fine. Just checking that you were not waiting on us for any reason.

**Comment by ggould-tri** [comment]
Dropping this to backlog due to more general nlopt issues.  If some future nlopt version is more promising, or if we can bound the bad behaviour classes of optimization problem, we can revisit it.

**Comment by sammy-tri** [comment]
Closing since windows support is no longer an issue.
