### ISSUE TITLE
Enable SNOPT in Windows CI

### ISSUE THREAD

**Issue by david-german-tri** [RobotLocomotion/drake#2352]
https://github.com/RobotLocomotion/drake-ci/blob/master/ctest_driver_script.cmake#L522

There's no corresponding condition in the Drake superbuild proper:

https://github.com/RobotLocomotion/drake/blob/master/CMakeLists.txt#L118

**Comment by jamiesnape** [comment]
Because we cannot enable private repos on Windows due to a bug in Jenkins.

**Comment by david-german-tri** [comment]
Proposed workaround from f2f discussion: bake SNOPT into the Windows AMI for now.

**Comment by david-german-tri** [comment]
Update: @jamiesnape is still looking into working around the Jenkins bug to use SNOPT as a git external, but will time-box that at one day and dump it in the image instead.

**Comment by jamiesnape** [comment]
Bug has been worked around, but now blocked by some sort of resolution of #2554.

**Comment by david-german-tri** [comment]
Windows is no longer supported.
