### ISSUE TITLE
Matlab License Error

### ISSUE THREAD

**Issue by liangfok** [RobotLocomotion/drake#2366]
I'm encountering the following problem:

```
Unrecognized MATLAB option "wait".
License checkout failed.
License Manager Error -97
License Manager cannot start. 
Check that the specified ports in the license file are not already in use. 
Restarting your machine may clear the ports.

Troubleshoot this issue by visiting: 
http://www.mathworks.com/support/lme/R2016a/97

Diagnostic Information:
Feature: MATLAB 
License path: /home/liang/.matlab/R2016a_licenses:/usr/local/MATLAB/R2016a/licenses/license.dat:/usr/local/MATLAB/
R2016a/licenses/network.lic 
Licensing error: -97,121.
```
@amcastro-tri also occasionally encounters this problem, which is sporadic and unpredictable.

**Comment by david-german-tri** [comment]
This is a TRI-internal IT issue, not a Drake issue.

**Comment by liangfok** [comment]
Should Drake's build system automatically switch to non-Matlab Drake when it encounters a problem with the local Matlab installation?

Perhaps print a warning prior to the switch?

I ask because I was just trying to build the documentation when this error popped up.

**Comment by jwnimmer-tri** [comment]
If you've asked to have a particular working copy be a matlab build, and then matlab stops working, I think its entirely reasonable for the build / build system to complain and fail.  Build systems that say "oh well" and ignore problems are _not_ good build systems.  The textual output doesn't matter (so the warning text doesn't help); the only relevant output of a build should be its exitcode.

**Comment by liangfok** [comment]
I don't mean to cause a ruckus but I don't think I "asked to have a particular working copy be a matlab build." Instead, the build system decided for itself to be a matlab build presumably because it found MATLAB in the path. Perhaps this brings about a bigger question of how much control we should have over the build settings.

**Comment by jwnimmer-tri** [comment]
Yup.  And if you don't want to have matlab on by default, you can run `make options` again either with matlab unfindable on your path, or with `DISABLE_MATLAB=True` set.

**Comment by liangfok** [comment]
Yeah, I'll use that. I was just thinking that if the build system can decide by itself to use matlab, it should also be able to decide by itself not to use matlab if it encounters a problem.
