### ISSUE TITLE
 Fix or suppress cpplint warnings for runtime/string

### ISSUE THREAD

**Issue by jwnimmer-tri** [RobotLocomotion/drake#2367]
We should fix cpplint's `runtime/strong` warnings throughout our code (and/or suppress them on a one-by-one-basis), and then stop suppressing the warning globally in `drake-distro/drake/CPPLINT.cfg`.  This is a break-out from #2064.

**Comment by rpoyner-tri** [comment]
I'm taking assignment of this as a placeholder -- I may pass it off to a new TRI employee as an easy get-acquainted task.

**Comment by rpoyner-tri** [comment]
Assigning @jadecastro this issue. It should result in a trivial PR to allow him to get familiar with the tools and processes.

**Comment by jwnimmer-tri** [comment]
The above-linked PR actually fixed this.
