### ISSUE TITLE
Mac CI is flaky due to...system clock?

### ISSUE THREAD

**Issue by david-german-tri** [RobotLocomotion/drake#2387]
https://drake-jenkins.csail.mit.edu/job/experimental/1531/compiler=clang,label=mac/consoleFull

From the `nlopt-build` step:

```
16:40:07 checking whether build environment is sane... configure: error: newly created file is older than distributed files!
16:40:08 Check your system clock
```

The ultimate failure on `Could NOT find GTest` is a red herring.  The superbuild terminated on the NLOPT build problem before it could get around to building GTest, but proceeded to try to build Drake anyway.

**Comment by jamiesnape** [comment]
Very strange.

**Comment by jamiesnape** [comment]
Fixed via vSphere configuration.
