### ISSUE TITLE
CI shouldn't bother trying to build or test Drake if the superbuild fails

### ISSUE THREAD

**Issue by david-german-tri** [RobotLocomotion/drake#2388]
See #2387 for an example.

**Comment by jamiesnape** [comment]
There is a fundamental problem with Drake, I think. Normally, the child build would not happen.

**Comment by david-german-tri** [comment]
As discussed f2f, this should be possible to short-circuit in the CI script.

**Comment by jamiesnape** [comment]
e.g., https://drake-jenkins.csail.mit.edu/job/mac-clang-continuous-debug/189/console

**Comment by david-german-tri** [comment]
very nice!
