### ISSUE TITLE
Drake Doxygen Website Does Not Include Examples

### ISSUE THREAD

**Issue by liangfok** [RobotLocomotion/drake#2393]
It would be nice to generate the Doxygen webpages for the C++ files within `drake/examples`. At a minimum, this would enable us to verify that our Doxygen comments are rendered correctly.

**Comment by liangfok** [comment]
I traced the problem to: https://github.com/RobotLocomotion/drake/blob/master/drake/doc/Doxyfile_CXX.in#L128

**Comment by sherm1** [comment]
I think this could be confusing, Liang. The examples are likely to have many repeated symbol names. Nice doxygen could be made for them but not the way we usually do it -- I think they would need to have their own topics and be documented consciously as examples.

**Comment by liangfok** [comment]
Yeah I was just thinking the same. Maybe each example can have its own Doxygen website that is built using:

```
$ make documentation-[example name]
```

**Comment by sherm1** [comment]
I think the example documentation should just get built along with Sphinx and the API documentation -- it's too much work to ask for manual builds of each example.

**Comment by liangfok** [comment]
OK about generating both Drake's library API and its examples using the same build target and command. How about we enable example documentation when [INTERNAL_DOCS = YES](https://github.com/RobotLocomotion/drake/blob/master/drake/doc/Doxyfile_CXX.in#L75) (it will be by default set to `NO`)?

**Comment by jwnimmer-tri** [comment]
Possibly fixed?

**Comment by RussTedrake** [comment]
yes.  examples are built in the main documentation.
