### ISSUE TITLE
Mac builds are having MATLAB licensing issues.

### ISSUE THREAD

**Issue by jonathan-owens** [RobotLocomotion/drake#2394]
See, e.g., https://drake-cdash.csail.mit.edu/testDetails.php?test=696611&build=22322 or https://drake-cdash.csail.mit.edu/testDetails.php?test=697366&build=22531 for a couple examples.

This doesn't happen in every (or even most) MATLAB tests.

**Comment by jonathan-owens** [comment]
Seemed to be a network error that worked itself out.

**Comment by jonathan-owens** [comment]
This is continuing to happen. Seems to be much more regularly.

https://drake-cdash.csail.mit.edu/viewTest.php?onlyfailed&buildid=41461

**Comment by david-german-tri** [comment]
No longer a problem, as far as I know.
