### ISSUE TITLE
Windows builds failing functional_form_test

### ISSUE THREAD

**Issue by jonathan-owens** [RobotLocomotion/drake#2398]
See, e.g. https://drake-cdash.csail.mit.edu/testDetails.php?test=701236&build=22748.

@bradking: The below changes seem to have broken the Windows builds.

https://github.com/RobotLocomotion/drake/commit/ab8bf49c61cec1192b6b179f3de4a136cc7ccd1f

**Comment by bradking** [comment]
See PR #2400.

**Comment by bradking** [comment]
Strange that it worked locally and in all the pre-integration tests.  I suspect the difference is whether `PATH` in the environment contains `$top/drake/lib/$config` in addition to `$top/install/lib`.  With both entries then the install rule is not needed to run the test.

**Comment by billhoffman** [comment]
I don't think it is a PATH issue unless this test requires a different PATH than any of the other tests.

**Comment by billhoffman** [comment]
It is just failing on the nightly build: https://drake-cdash.csail.mit.edu/testSummary.php?project=1&name=functional_form_test&date=2016-05-19

**Comment by bradking** [comment]
> I don't think it is a PATH issue

My PR fixes it, but I'm wondering how this was passing anywhere before the fix.

**Comment by billhoffman** [comment]
Seems like the ctest script has too much in the PATH... It has this:     "${DASHBOARD_WORKSPACE}/drake/pod-build/lib/Release"  That would explain why it failed on MS IDE Debug, and all Ninja builds, but passed on all release builds.

**Comment by bradking** [comment]
> Seems like the ctest script has too much in the PATH

Yes, that should be removed so all the builds work consistently.

**Comment by billhoffman** [comment]
Yup, we are removing it.

**Comment by bradking** [comment]
With PR 2400 merged this issue is resolved.
