### ISSUE TITLE
Linux buildslaves appear to be not working

### ISSUE THREAD

**Issue by jwnimmer-tri** [RobotLocomotion/drake#2405]
Linux buildslaves appear to be not working well (at least, their throughput is way down)...

@jonathan-owens (buildcop) please take a look, for example: https://drake-jenkins.csail.mit.edu/job/experimental/1582/ ... a while ago none of the linux builds were started, and only just now did cpplint start up.

**Comment by jamiesnape** [comment]
Were any Linux slaves offline or dead?

**Comment by david-german-tri** [comment]
`i-edd77977` appeared offline in Jenkins, but appeared live in AWS.

**Comment by jamiesnape** [comment]
Not seeing anything obvious in the logs.

**Comment by jwnimmer-tri** [comment]
Things seem to be healthy again now.  I am content to let kitware keep this open if they want to root cause it; otherwise it can be closed.
