### ISSUE TITLE
MATLAB tests fail when drake\pod-build\lib\Release is not in PATH on Windows

### ISSUE THREAD

**Issue by jamiesnape** [RobotLocomotion/drake#2416]
See https://drake-cdash.csail.mit.edu/viewTest.php?onlyfailed&buildid=23667. A build directory should not need to be in the PATH. A library may not be getting installed correctly.

FYI @RussTedrake.

**Comment by RussTedrake** [comment]
Could to catch and flag these.  I know that we were not sufficiently careful about this in the past.

**Comment by RussTedrake** [comment]
@jamiesnape -- totally agree this is a bug.  do you have someone that can investigate and resolve?

**Comment by RussTedrake** [comment]
when resolved, we should also be able to remove this line:
https://github.com/RobotLocomotion/drake/blob/master/drake/addpath_drake.m#L90
(in fact, I'm not sure how the matlab tests are failing, since this line should cover that case)

**Comment by david-german-tri** [comment]
Closing the loop on an offline conversation related to #2448: I don't think there's an analogy between this discussion and C++ linking.  It's normal and necessary for some build targets to link against libraries that aren't installed.

**Comment by jamiesnape** [comment]
Of course, but in the world of PODs apparently everything should be installed and have a pkg-config file.

**Comment by RussTedrake** [comment]
That’s not necessarily true of PODs.  Only libraries that are shared across pods should be installed.

**Comment by david-german-tri** [comment]
PODs: we will not miss them.

**Comment by jamiesnape** [comment]
That was not the case here either before or after #2455. Either way, it should be tidier if/when we follow the normal CMake patterns.
