### ISSUE TITLE
Jenkins seems to be buliding origin/master instead of origin/pr/XXXX/merge

### ISSUE THREAD

**Issue by sammy-tri** [RobotLocomotion/drake#2435]
Jenkins builds on new PRs are building from origin/master instead of the merged PR.  Seems to have started sometime on the morning of the 23rd.

Build 1623 seems OK: https://drake-jenkins.csail.mit.edu/job/experimental/1623/compiler=clang,label=linux/git/

Build 1630 seems to be from master: https://drake-jenkins.csail.mit.edu/job/experimental/compiler=clang,label=linux/1630/git/

**Comment by david-german-tri** [comment]
And /cc @jamiesnape who has requested to be pinged on all things CI.

**Comment by david-german-tri** [comment]
`master` is the default value of the `sha1` parameter in the experimental build, but I think that's been true for a while...trying to confirm from the Jenkins config history, and to figure out how it's overridden on a per-build basis.

**Comment by jamiesnape** [comment]
The GitHub pull request builder plugin sets $sha1.

**Comment by jamiesnape** [comment]
It looked like someone manually triggered a job today too, for some reason, so $sha1 there would be whatever they entered.

**Comment by jamiesnape** [comment]
https://github.com/janinko/ghprb#parameterized-builds

**Comment by david-german-tri** [comment]
Another interesting difference between build 1623 and build 1630 is that 1623 has one instance of "Parameters" in its left menu, while 1630 has fourteen.

**Comment by jamiesnape** [comment]
GitHub hooks have been flaky today too, since GitHub has had API problems.

**Comment by david-german-tri** [comment]
GitHub is claiming their fires are out: https://status.github.com/.  I've kicked off a retest on #2431 to see if we're back to normal behavior.

**Comment by jamiesnape** [comment]
Something is very wrong. We have 221 builds in the queue.

**Comment by jamiesnape** [comment]
Up to 297. I am going to reboot Jenkins before it melts down.

**Comment by sammy-tri** [comment]
And based on https://drake-jenkins.csail.mit.edu/job/experimental/compiler=cpplint,label=linux/1656/console, they're still not building the desired targets...

**Comment by jamiesnape** [comment]
Some are and some aren't. Not sure why yet.

**Comment by jamiesnape** [comment]
Something is definitely wrong with how parameters are passed down to the matrix.

**Comment by jamiesnape** [comment]
The changelog is correct: https://drake-jenkins.csail.mit.edu/job/experimental/1713/

**Comment by jamiesnape** [comment]
But the SHA is not passed down to the matrix builds.

**Comment by jamiesnape** [comment]
https://issues.jenkins-ci.org/browse/JENKINS-34758

**Comment by jamiesnape** [comment]
Compiling a version of the plugin with the fix now.

**Comment by jamiesnape** [comment]
Looks like we are fixed now.

**Comment by jamiesnape** [comment]
I am thinking it may be better to not have a default value for `$sha1` for these builds. Not many people manually run them and a failure would be preferable to building the wrong branch.

**Comment by david-german-tri** [comment]
agreed

**Comment by jamiesnape** [comment]
Done.
