### ISSUE TITLE
Provide pod wrapper for the student version of snopt

### ISSUE THREAD

**Issue by junji15** [RobotLocomotion/drake#245]
Hello. I am trying to install Drake (rigidbody) of Ubuntu 12.04.1 
After the installation and make from source file, if I try to use "addpath_drake.m", the below is apeeared in Matlab:

---

Error using addpath_drake (line 24)
You must run make first (and/or add your pod build/matlab directory to the matlab path)

Error in run (line 63)
evalin('caller', [script ';']);

---

But I cannot find "build/matlab directory" in drake-distro. The build folder includes only "bin","include","lib","share".

I would appreciate it very much if you could advise me anything.
Junji Kikuchi

**Comment by RussTedrake** [comment]
@sammy-tri -- it would be good to get your input on how we'll link the c++ snopt wrapper to the student version, in case there are potential roadblocks there.

**Comment by david-german-tri** [comment]
Evicting from the Kitware queue and handing over to @sammy-tri, based on @RussTedrake's last comment.

**Comment by sammy-tri** [comment]
The link above for student SNOPT is dead, and I can't seem to find any live links poking around on google.  Is this still something we're interested in?  Also our SNOPT build got a bit more custom during the process of adding IPOPT (fortran symbol collisions in versions of BLAS packaged with both libraries, IIRC), so if the student version is binary-only, that could also present some issues.

Of course, that assumes I could find that version to test with.

**Comment by ljarin** [comment]
I have a full version of SNOPT - but I want to build with ROS. I see people posted a makefile for using student snopt, but is there a way I could get the CMakeLists.txt from externals/snopt?

**Comment by RussTedrake** [comment]
Hi @ljarin.  You're actually a special case (being at MIT), so I will send you an email on how to proceed.

**Comment by jwnimmer-tri** [comment]
It would be nice to get a refresh on what's still wanted here.  Could someone post a new summary below?

**Comment by RussTedrake** [comment]
not everyone has a snopt license.
students can download a restricted version of snopt (with a variable limit).  it would be nice to be able to let MathematicalProgram call that version instead.  but right now we've forked the main snopt repo and updated the build to link against it.

Perhaps a useful summary might be to support "using system snopt".  If we can use a version of snopt that someone already has installed, then lots of things get easier.  And the student version should work, too.

**Comment by jwnimmer-tri** [comment]
Within TRI, I have BUILD files written for using pristine upstream SNOPT.  We could first switch back Drake to use pristine SNOPT, and after that it should be fairly easy to let the user change which tarball Bazel refers to.

**Comment by RussTedrake** [comment]
Sounds excellent.  I believe that the student snopt is, from the perspective of the build system, identical to the licensed snopt (it just adds a variable limit somewhere in the code).   @hongkai-dai -- chime in if you know otherwise?

**Comment by hongkai-dai** [comment]
Sorry for being late. I believe they should be identical. If the student SNOPT is in 7.2.12. The newer SNOPT 7.5 has different API from ours, and I do not know if we can build SNOPT 7.5.

**Comment by jwnimmer-tri** [comment]
Since I am about to start on #7240, which we believe will resolve this issue, I will also take ownership here.

**Comment by jwnimmer-tri** [comment]
On master right now, http://drake.mit.edu/bazel.html documents how to set the `SNOPT_PATH` environment variable to a tarball of the SNOPT source archive one wants to use.  I _think_ that is all we need to support the student version, but I can't be sure without the ability to duplicate the students' setup.  I'll kick this over to @RussTedrake for any testing or delegation to confirm it works, before closing it out.

**Comment by RussTedrake** [comment]
I would have to register as a student and get approved to test this myself.  Based on my reading, I think that we can safely consider it resolved.  Thank you!

N.B. the https://bazel.build/versions/master/docs/bazel-user-manual.html#bazelrc link on http://drake.mit.edu/bazel.html is broken.

**Comment by jwnimmer-tri** [comment]
> N.B. the https://bazel.build/versions/master/docs/bazel-user-manual.html#bazelrc link on http://drake.mit.edu/bazel.html is broken.

Ah yes, they have redirects for most URLs but they messed up that one.  I'll PR that.
