### ISSUE TITLE
No clear way to determine if a revision passed continuous

### ISSUE THREAD

**Issue by ggould-tri** [RobotLocomotion/drake#2461]
Our process requires in some cases that particular commits pass continuous (see, eg, the case of a fixing patch in the revert process).  However it is very difficult to determine when this has happened without clicking through to every continuous builder's page in Jenkins (also it seems to be entirely impossible via cdash).

In buildbot, for instance, there are time- and revision-centric interfaces; see e.g. http://trac.buildbot.net/wiki/ScreenShots .  Jenkins and CDash seem to lack such a view, or at least to lack in our configuration.

**Comment by jamiesnape** [comment]
Best I can do is this:

https://drake-jenkins.csail.mit.edu/view/Continuous/job/linux-clang-continuous-debug/changes

Otherwise, it is out of our control for Jenkins.

**Comment by jamiesnape** [comment]
I am asking about possibilities for CDash.

**Comment by jamiesnape** [comment]
We can now filter CDash builds by revision, for example:

https://drake-cdash.csail.mit.edu/index.php?project=Drake&filtercount=1&showfilters=1&field1=revision&compare1=61&value1=d57f429a75347ea58f7792be34585d39bd5a1063

**Comment by david-german-tri** [comment]
FYI, filtering CDash by revision always comes up empty for me.  Low priority, though.

**Comment by jamiesnape** [comment]
Seems fine. The nightly revision was 48de280b26b451458bbd2127a4d14cb435b315f4. Hence,
https://drake-cdash.csail.mit.edu/index.php?project=Drake&filtercount=1&showfilters=1&field1=revision&compare1=63&value1=48de280b26b451458bbd2127a4d14cb435b315f4

**Comment by david-german-tri** [comment]
Huh, OK, that link works.
