### ISSUE TITLE
Document our code_style_guide rules for python

### ISSUE THREAD

**Issue by jwnimmer-tri** [RobotLocomotion/drake#2465]
We need to document our `code_style_guide.rst` rules for python code.  We have C++, Java, and MATLAB rules now, but not python.

For the record, in #1741 we choose googlestyle for C++ but didn't appear to discuss other languages.  I don't think there's anything else major we've missed, though.

**Comment by jwnimmer-tri** [comment]
For starters, I think its obvious to elect [PEP-8](https://www.python.org/dev/peps/pep-0008/) as the basic rules.  We can tack on more beyond that if we start to care.

Probably also worth documenting how to run the `pep8` style-checker tool.

**Comment by liangfok** [comment]
+1 for PEP-8.

**Comment by jamiesnape** [comment]
Would you like me to run `flake8` or `pylint` on PR's.

**Comment by jamiesnape** [comment]
The Google style guide for Python seems reasonable. As far as I can tell it is PEP8 plus a few other things.

**Comment by jwnimmer-tri** [comment]
> Would you like me to run flake8 or pylint on PR's?

Possibly in the future, but for now I'd suggest that someone to test it locally and in integrate into drake-distro first, and then toss it into jenkins.   Also there's not _that_ much python code in Drake, so probably not a high priority.

**Comment by david-german-tri** [comment]
Sounds reasonable to me.

**Comment by rdeits** [comment]
FYI: the `pep8` package has been renamed to the more-readable [pycodestyle](https://pypi.python.org/pypi/pycodestyle) package going forward.

**Comment by jamiesnape** [comment]
There is also [yapf](https://github.com/google/yapf) to autoformat Python files in the same spirit as `clang-format`.

**Comment by jwnimmer-tri** [comment]
Let me try kicking this over to @david-german-tri, since I'm not foresee-ably going to work on it, ever.

**Comment by david-german-tri** [comment]
I'm never going to work on this either.  Dropping it to the backlog.

**Comment by jwnimmer-tri** [comment]
I wonder if @rpoyner-tri would be interested in taking a stab at this, and perhaps relating it to TRI python style?

**Comment by rpoyner-tri** [comment]
Sure.
