### ISSUE TITLE
Replace PODs with conventional CMake workflow

### ISSUE THREAD

**Issue by jamiesnape** [RobotLocomotion/drake#2482]
Note: This is an epic on our [ZenHub](https://www.zenhub.io) board. Please do not remove or rename the [Epic](https://github.com/RobotLocomotion/drake/labels/Epic) label.

**Comment by jamiesnape** [comment]
@david-german-tri Can you add the "Epic" back? We need it for our ZenHub board.

**Comment by david-german-tri** [comment]
Sorry about that.  Done.

**Comment by jamiesnape** [comment]
For the benefit of non-ZenHub users, the initial list of issues in the epic was #1747, #1751, #1781, #1859, #1909, #1963, #1989, #1994, #2046, #2094, #2118, #2251, #2307, #2329, #2341, #245, #2483, #2484, #2486, and #2487.

**Comment by david-german-tri** [comment]
When you get a chance, could you generate a burndown list for PODs dependencies?

**Comment by jamiesnape** [comment]
#3326, #3327, #3328, #3329, #3330, #3331, #3332, #3333, #3334, #3335, #3336, #3337, #3338, #3341.

**Comment by david-german-tri** [comment]
See #1859 for some useful discussion and history.
