### ISSUE TITLE
LQRTree problem

### ISSUE THREAD

**Issue by lavrinovu4** [RobotLocomotion/drake#2519]
Hi all,

I am trying run LQRTree on pendulum.
But It crashes with error:

for now, I require that G matches V at the final conditions

I get exemples of values for tspan(end):
Vtraj(V)
[  (8.0211e-05)_x1+(9.5326)_x1^2+(1.7459e-05)_x2+(0.87599)_x2^2+(2.9633)_x2_x1  ]
Vparent(G)
[  (40.82)+(39.363)_x1+(9.5326)_x1^2+(6.8069)_x2+(0.87599)_x2^2+(2.9633)_x2_x1  ]

So what can be wrong?
Thank you in advance.

**Comment by RussTedrake** [comment]
The LQRTree code in matlab needs updating, but will be matured into c++ implementations soon.
