### ISSUE TITLE
Current implementation of coulomb friction (at the joint level) is incorrect

### ISSUE THREAD

**Issue by RussTedrake** [RobotLocomotion/drake#2537]
From the schema doc:

> determines the threshold in qd when the coulomb term saturates (F_c = sgn(qd)_coulomb_friction.
> total friction force is a piecewise linear approximation of sgn(qd)_Fc + qd_Fd:
> f_friction = min(1,max(-1,qd./m.coulomb_window'))._m.coulomb_friction' + m.damping'.*qd

But the force in the sticking mode should be whatever force is required by the dynamics to prevent the motion.  (Here it is zero).  The real solution is an LCP.

**Comment by kuindersma** [comment]
We used this approximation to avoid chattering around the velocity zero-crossing when performing inverse dynamics on Atlas. Chapter 9 of Khalil and Dombre includes this model.

**Comment by RussTedrake** [comment]
i see.  For that case, presumably we were never actually at zero measured velocity?  Do you think a more useful model would have some deadband for the sticking?

**Comment by kuindersma** [comment]
I'm not sure I'm completely parsing the model you're proposing, but I think as long as there's velocity noise, any model with a discontinuous jump will potentially cause chattering problems.

**Comment by kuindersma** [comment]
Oh, nvm! Yeah, I think what you're saying could work.

**Comment by RussTedrake** [comment]
this is matlab-only, and is no longer relevant (the new models in c++ are correct).
