### ISSUE TITLE
Change cpplint from a system dependency, to a superbuild external

### ISSUE THREAD

**Issue by jwnimmer-tri** [RobotLocomotion/drake#2539]
We should change cpplint from a system dependency, to a superbuild external.  Different versions will give different errors, and we should all be using the same version.  This may also allow us to tweak cpplint to our liking, if need be.

- [x] Add `google-styleguide` as a superbuild external.
- [x] Add drake-specific `cpplint_wrapper.py`.
- [x] Add unit test coverage.
- [x] Add sphinx documentation.
- [x] Add `drake-distro/ros` to the default search list of `cpplint_wrapper.py`.
- [x] Change jenkins to call drake's `cpplint_wrapper.py` instead of drake-ci's wrapper.

**Comment by jamiesnape** [comment]
Can we just commit it to this repo? It is only one Python file.

**Comment by jwnimmer-tri** [comment]
That's a good consideration.  Let me think about it.

**Comment by jwnimmer-tri** [comment]
WIP https://github.com/jwnimmer-tri/drake/tree/cpplint-as-external

The `cpplint.py` is just one file, but it's ~250kB, so I'm exploring doing it as an external.  Also, it might end up being nice to have a copy of googlestyle IDE plug-ins in a well-known place for us to reference in our documentation.

**Comment by jamiesnape** [comment]
Jenkins is now using cpplint from superbuild.

**Comment by mwoehlke-kitware** [comment]
...and the cpplint build now seems to be broken: https://drake-jenkins.csail.mit.edu/job/experimental/3608/compiler=cpplint,label=linux,type=debug/ ...`-DWITH_DRAKE=OFF` missing?

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-cpplint-experimental please

**Comment by jamiesnape** [comment]
The standalone job worked: https://drake-jenkins.csail.mit.edu/view/Lint/job/linux-cpplint-experimental/164/

**Comment by mwoehlke-kitware** [comment]
@jamiesnape, on second thought... maybe it's not doing a merge build? (Are the default experimental builds not merge builds?)

**Comment by jamiesnape** [comment]
No, they are merge, unless you have a merge conflict.

**Comment by jamiesnape** [comment]
> ...unless you have a merge conflict.

Which you do in this instance.

**Comment by mwoehlke-kitware** [comment]
> ...unless you have a merge conflict. Which you do in this instance.

Bother :weary:... okay, seems better now; thanks.
