### ISSUE TITLE
MathematicalProgram needs test coverage

### ISSUE THREAD

**Issue by ggould-tri** [RobotLocomotion/drake#2556]
MathematicalProgram uses the C++ type system to implement a lattice of problem types.  This lattice was initially simple and lived without test coverage.  As the categories of problems and solvers becomes more complex, unit tests will be required.

These tests should be relatively black-box tests of choice of solvers given particular constraints, costs, and solver availabilities, as it is not clear that a type-system-based lattice will fully express solver choice decisions in the future once we can demand additional solver features (eg, active constraint sets).

**Comment by jwnimmer-tri** [comment]
Solver choice dispatch has a unit test now: https://github.com/RobotLocomotion/drake/blob/df86de15c0ba63a616dd347b263d8e2cc083875d/solvers/test/choose_best_solver_test.cc
