### ISSUE TITLE
IPOPT should be enabled on Windows

### ISSUE THREAD

**Issue by sammy-tri** [RobotLocomotion/drake#2569]
PR #2505 introduces IPOPT support, compiling from source on OSX and Linux.  We should add support for Windows, either by fetching the precompiled library from the IPOPT authors (they distribute one as documented in http://www.coin-or.org/Ipopt/documentation/node15.html ), or compiling from source.  

Personally, I suspect the precompiled version will be easier.

**Comment by sammy-tri** [comment]
Anyone at kitware have some cycles to look into fixing this?   (and a working Windows devel environment?)

**Comment by jamiesnape** [comment]
Could you add a priority tag?

**Comment by sammy-tri** [comment]
Done

**Comment by david-german-tri** [comment]
Windows is no longer supported.
