### ISSUE TITLE
Drake Wiki Not Being Updated As Often as Expected

### ISSUE THREAD

**Issue by liangfok** [RobotLocomotion/drake#2587]
https://github.com/RobotLocomotion/drake/pull/2575 was merged about 26 hours ago but the [Drake Wiki page](http://drake.mit.edu/unit_testing_instructions.html#defining-the-build-artifacts-directory) does not reflect the changes yet. Isn't the wiki supposed to be updated nightly?

**Comment by liangfok** [comment]
FTR, the wiki is still not updated this morning.

**Comment by david-german-tri** [comment]
Sure enough.  @jamiesnape, any ideas?

**Comment by jamiesnape** [comment]
I see the issue. Working on a fix now.

**Comment by liangfok** [comment]
FYI. I just noticed that http://drake.mit.edu/from_source.html still does not contain the changes in https://github.com/RobotLocomotion/drake/pull/2555.

**Comment by jamiesnape** [comment]
Still working on the fix. I will update this ticket once it is working again.

**Comment by jamiesnape** [comment]
@bradking Is the documentation no longer installed into `build/share/doc`?

**Comment by bradking** [comment]
See #2558 and RobotLocomotion/drake-ci#3.  If the doc robot is not setting `BUILD_DOCUMENTATION_ALWAYS` then it will not build the docs unless it explicitly builds the `documentation` target.  I'm not aware of any other recent changes to the documentation infrastructure.

The `drake/doc/CMakeLists.txt` file still has:

```cmake
set(DRAKE_DOCUMENTATION_DIR ${CMAKE_INSTALL_PREFIX}/share/doc)
```

**Comment by jamiesnape** [comment]
`BUILD_DOCUMENTATION_ALWAYS` and `BUILD_DOCUMENTATION` are both set to be `ON` and I am not seeing anything in `build/share/doc` anymore.

**Comment by jamiesnape** [comment]
I think I see the problem. Starting a new build:
https://drake-jenkins.csail.mit.edu/job/linux-gcc-continuous-matlab/360/

**Comment by jamiesnape** [comment]
https://github.com/RobotLocomotion/drake/commit/af7323fe00b8769130b56a65cb22d5b74f51ec3a

**Comment by liangfok** [comment]
The problem appears to have reappeared. https://github.com/RobotLocomotion/drake/pull/2734 was merged yesterday but its changes have not shown up on http://drake.mit.edu yet.

**Comment by jamiesnape** [comment]
Apparently I forgot to toggle the flag on Jenkins. Should be back after build 419 or 420 of linux-gcc-continuous-matlab.

**Comment by liangfok** [comment]
LGTM. Closing this issue now.
