### ISSUE TITLE
URDF Parser Needs To Be Updated to Support Visualizations with Textures

### ISSUE THREAD

**Issue by liangfok** [RobotLocomotion/drake#2588]
Currently, in ~`RigidBodyTreeURDF.cpp`~ `urdf_parser.cc`, method `parseVisual()` only supports `<material>` elements with `<color>` child elements. The [URDF specification](http://wiki.ros.org/urdf/XML/link) states that `<texture>` child elements should also be supported.

**Comment by liangfok** [comment]
I believe this should wait until #4337 is resolved.

**Comment by amcastro-tri** [comment]
More specifically to our new infrastructure with MBP/SG/sdformat, we'd like to update our sdformat based parser to read textures and other visual information.

**Comment by tri-ltyyu** [comment]
Need more specifics. Please open new issue if still a problem
