### ISSUE TITLE
Remove "make options" from Drake

### ISSUE THREAD

**Issue by liangfok** [RobotLocomotion/drake#2594]
It's confusing since it only supports `make` whereas we are now supporting both `make` and `ninja` (assumes https://github.com/RobotLocomotion/drake/pull/2555 is merged).

It's unnecessary since we can always use `ccmake` directly. 

It conflicts with https://github.com/RobotLocomotion/drake/issues/2484.

Before removing the `make options` build target, we need to update the following instructions:

1. drake/doc/fedora.rst
2. drake/doc/homebrew.rst
3. drake/doc/ubuntu.rst

**Comment by RussTedrake** [comment]
this can probably be closed now?

**Comment by jwnimmer-tri** [comment]
The `fedora.rst` still mentions it.

**Comment by david-german-tri** [comment]
We deleted `fedora.rst` in #3744, so it's done now.
