### ISSUE TITLE
Add intro comments and citation to simple dynamics planning classes 

### ISSUE THREAD

**Issue by avalenzu** [RobotLocomotion/drake#260]
RussTedrake:

> can you add comments on how this is different that COMDynamicsFullKinematicsPlanner?
> should we only be committing one of them (the winner), or is their value in having both?
> 
> also, the COMDynamicsFullKinematics planner should cite the humanoids paper submission in the header documentation.

avalenzu:

> I'll add comments on the relationship between SimpleDynamicsFullKinematicsPlanner and COMDynamicsFullKinematicsPlanner.
> 
> There can't be a "winner" in this case, because SimpleDynamicsFullKinematicsPlanner is an abstract parent of COMDynamicsFullKinematicsPlanner. This leaves us the option of defining planners with different simple dynamics in the future.

avalenzu:

> I'll add the citation to the humanoids paper submission.

**Comment by jwnimmer-tri** [comment]
Is this MATLAB-only?  Should we close it as part of #6369?

**Comment by jwnimmer-tri** [comment]
Ping @avalenzu @hongkai-dai -- should this issue remain open?

**Comment by hongkai-dai** [comment]
Yes, this is MATLAB only. Close the issue.
