### ISSUE TITLE
Python Binding Unit Tests Rely on URDFs in Examples

### ISSUE THREAD

**Issue by liangfok** [RobotLocomotion/drake#2611]
The unit tests in `drake-distro/drake/bindings/python/pydrake/test/`all access URDFs in `drake-distro/drake/examples/`. This violates the order-of-includes rule we're trying to enforce.

Related:
- https://github.com/RobotLocomotion/drake/issues/1987 - "Dependency visibility should be enforced"
- https://github.com/RobotLocomotion/drake/pull/2533 - "Add drake/util/scan_subdirectory_order.py"
- https://github.com/RobotLocomotion/drake/issues/2548 - "Shared models directory"

**Comment by jwnimmer-tri** [comment]
So between (1) a revised understanding of what's allowed to depend on what (tests may in general depend on anything anywhere), and (2) its pydrake (so who cares), I think that this is no longer an issue.  Resolved-invalid.
