### ISSUE TITLE
Previously accessible file ${FILENAME} is now inaccessible

### ISSUE THREAD

**Issue by jonathan-owens** [RobotLocomotion/drake#2625]
On [several MATLAB tests in Windows](https://drake-cdash.csail.mit.edu/viewTest.php?onlyfailed&buildid=39656), the test fails with the following (or similar) error:

```
Previously accessible file "C:\Program Files\MATLAB\R2015b\toolbox\matlab\demos\subsref.m" is now inaccessible.
```

I have only seen this issue on Windows, though I cannot claim that it is exclusive to that environment. A quick Google search pointed to [this](https://www.mathworks.com/matlabcentral/answers/259268-standalone-error-accessible-file-is-now-inaccessible-and-mclfreestacktrace) possible solution. Note this doesn't seem to necessarily be a reoccurring issue yet, either.

**Comment by jonathan-owens** [comment]
This has happened [some more](https://drake-cdash.csail.mit.edu/viewTest.php?onlyfailed&buildid=39902).

**Comment by david-german-tri** [comment]
Windows is no longer supported.
