### ISSUE TITLE
Update addpath_drake.m To Include Optional Build Artifacts Directory Parameter

### ISSUE THREAD

**Issue by liangfok** [RobotLocomotion/drake#2627]
Currently, `drake/addpath_drake.m` assumes that the build artifacts are in a directory called `drake-build`. While this is the [documented standard](http://drake.mit.edu/from_source.html), very frequently, developers will maintain many different builds in differently named directories. Thus, it would be nice if an optional input parameter can be added to `drake/addpath_drake.m` that allows a non-standard build artifacts directories to be added.

FTR: https://reviewable.io/reviews/robotlocomotion/drake/2599#-KKt2-AMHI7Nih24HyfY

**Comment by david-german-tri** [comment]
> Currently, drake/addpath_drake.m assumes that the source code is in a directory called drake-distro. 

I don't think this is true (before or after #2599).  Did you mean to refer to the build tree?

**Comment by liangfok** [comment]
Sorry, yes, fixed. Thanks!
