### ISSUE TITLE
Create SWIG + Deprecation Unit Example Demonstrating Syntax Error

### ISSUE THREAD

**Issue by liangfok** [RobotLocomotion/drake#2646]
In #2597, marking a method as deprecated resulted in SWIG complaining about a syntax error. The current work around is to add an extra set of `#ifndef SWIG .... #endif` guards to ensure the `DRAKE_DEPRECATED()` macro is not included when SWIG is in use. We should create a unit example  demonstrating that this problem continues to exist in isolation.

See: https://reviewable.io/reviews/robotlocomotion/drake/2597#-KKyshnUyy05WVVvAuQd

**Comment by jwnimmer-tri** [comment]
No extra docs needed.
