### ISSUE TITLE
ROS support should be optional

### ISSUE THREAD

**Issue by jhoare** [RobotLocomotion/drake#2675]
Right now ROS support is enabled if CMake is able to find ROS. There should be a way to not build with ROS support, even if it is installed. 

There is a DISABLE_MATLAB flag, perhaps there should be a DISABLE_ROS flag?

**Comment by liangfok** [comment]
SGTM.

**Comment by jhoare** [comment]
This is no longer necessary with the new way we are building drake for ROS.
