### ISSUE TITLE
ASan/MSan/TSan builds are failing after update to CMake bot_core_lcmtypes

### ISSUE THREAD

**Issue by jamiesnape** [RobotLocomotion/drake#2708]
* https://drake-jenkins.csail.mit.edu/job/linux-clang-nightly-memcheck-asan/144/
* https://drake-jenkins.csail.mit.edu/job/linux-clang-nightly-memcheck-msan/144/
* https://drake-jenkins.csail.mit.edu/job/linux-clang-nightly-memcheck-tsan/126/

**Comment by mwoehlke-kitware** [comment]
I think we should turn off asan for lcmgen: https://github.com/lcm-proj/lcm/blob/master/lcmgen/lcmgen.c#L45.

I can't figure out how to do that, though; even removing the `-fsanitize=` from the compile flags doesn't seem sufficient...?

**Comment by mwoehlke-kitware** [comment]
> I can't figure out how to do that, though; even removing the -fsanitize= from the compile flags doesn't seem sufficient...?

Arf, missed the one in `CMAKE_EXE_LINKER_FLAGS`...

**Comment by mwoehlke-kitware** [comment]
...aaaaaaaand libbot is broken because it *isn't* using the san flags, but LCM (newly) *is*...

**Comment by jwnimmer-tri** [comment]
IMO those builds are of extremely low value, and we should disable them instead of burning time on them.

**Comment by jamiesnape** [comment]
> IMO those builds are of extremely low value, and we should disable them instead of burning time on them.

I strongly disagree. People should be taking more notice of them.

**Comment by mwoehlke-kitware** [comment]
I don't think this can be fixed without overhauling the libbot build system... would it be acceptable to disable libbot for the sanitizer builds?

**Comment by jamiesnape** [comment]
I think so.
