### ISSUE TITLE
Documentation Needed on Unit Test Dependencies

### ISSUE THREAD

**Issue by liangfok** [RobotLocomotion/drake#2733]
We should update Drake's website with a page listing every unit test and their dependencies. That way we won't be left wondering why certain unit tests appear missing.

For context, see: https://github.com/RobotLocomotion/drake/issues/2728#issuecomment-230124852. In that example, long running unit tests are enabled but the following unit tests are still missing presumably due to lack of certain dependencies:

```
-- Not running examples/Atlas/runAtlasBalancing because gurobi was not installed.
-- Not running examples/Atlas/runAtlasBalancingPerturb because gurobi was not installed.
-- Not running examples/Atlas/runAtlasBalancingWithContactSensor because gurobi was not installed.
-- Not running examples/Atlas/runAtlasManip because gurobi was not installed.
-- Not running examples/Atlas/test/testCollisionVolumes because iris was not installed.
-- Not running examples/Pendulum/globalStability because mosek was not installed.
```

The above output indicates that the unit tests are "not running". In fact, they don't even appear in the list of available unit tests when executing `ctest -N`.

**Comment by jwnimmer-tri** [comment]
It seems like a website with this information would go out-of-date immediately.

Are the `CMakeListst.txt` annotations good enough for this now (to close the issue)?
https://github.com/RobotLocomotion/drake/blob/282d0576437ffae167aa8f37dcfa7ef1e7be5a48/drake/examples/Atlas/CMakeLists.txt#L32

**Comment by jwnimmer-tri** [comment]
CMake changes already done are good enough.
