### ISSUE TITLE
Clang-Mac CI Failure: No rule to make target: libpython2.7.dylib

### ISSUE THREAD

**Issue by liangfok** [RobotLocomotion/drake#2736]
# Example Log

Here are some example logs:

* https://drake-jenkins.csail.mit.edu/job/experimental/2469/compiler=clang,label=mac/consoleFull
* https://drake-jenkins.csail.mit.edu/job/experimental/2468/compiler=clang,label=mac/consoleFull
* https://drake-jenkins.csail.mit.edu/job/experimental/2464/compiler=clang,label=mac/consoleFull
* https://drake-jenkins.csail.mit.edu/job/experimental/2458/compiler=clang,label=mac/consoleFull

# The Error

Here is an example error:

```
10:01:33 [  8%]make[9]: *** No rule to make target `/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/libpython2.7.dylib', needed by `lib/libvtkDRCFiltersPythonD.dylib'.  Stop.
```

# Root Cause Analysis

I haven't positively identified the root cause, but one thing I'm suspicious about is the fact that a different version of Python was found earlier in the same log:

```
10:01:28 -- Found PythonLibs: /usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/libpython2.7.dylib (found version "2.7.12") 
```

Note that the version found is version 2.7.12 whereas the version mentioned in the error message is 2.7.11.

**Comment by sherm1** [comment]
Could someone at Kitware take a look at this persistent Mac failure (@jamiesnape?). Thanks!

**Comment by jamiesnape** [comment]
Looking at it now.

**Comment by jamiesnape** [comment]
An issue with an old VTK config file on the image. Now fixed. Unrelated to current OS X outage which is hardware related.
