### ISSUE TITLE
 Build broken on GCC & Clang when Matlab and octomap are present

### ISSUE THREAD

**Issue by jwnimmer-tri** [RobotLocomotion/drake#2745]
Broken out from #2743, as reported by @gizatt.

On GCC & Clang builds, when Matlab and octomap are present, the `octomapWrapper.cpp` file is added to the build, but fails due to `-Werror=sign-compare` errors.

**Comment by jwnimmer-tri** [comment]
@gizatt Can you provide more details?

According to [this build log](https://drake-jenkins.csail.mit.edu/view/Continuous/job/linux-gcc-continuous-matlab/413/consoleFull), `octomapWrapper.cpp` is being compiled by Jenkins, and is producing no warnings or errors.

**Comment by gizatt** [comment]
I can't reproduce -- looking back at my console logs I can only guess I misread the output and attributed a build fail to the wrong thing. My bad! I'll keep an eye out for this resurging but I think it's safe.
