### ISSUE TITLE
Drake installation procedure

### ISSUE THREAD

**Issue by hongkai-dai** [RobotLocomotion/drake#2768]
I followed the source installation page (http://drake.mit.edu/from_source.html) to install drake on my Ubuntu 14.04 machine, I notice some guidelines might not be exactly correct.

- Before setting  my own fork of drake as the `origin` remote, I need to remove the `origin` first. This is what I did

  ```
git clone git@github.com:RobotLocomotion/drake.git drake-distro
cd drake-distro
git remote add upstream git@github.com:RobotLocomotion/drake.git
git remote remove origin
git remote add origin git@github.com:[your github user name]/drake.git
git remote set-url --push upstream no_push
  ```
  Otherwise it will throw the error
  ```
  fatal: remote origin already exists.
  ```
  if I call `git remote add origin git@github.com:[your github user name]/drake.git` directly.
- Where should I call `make` command? Following http://drake.mit.edu/from_source.html#build-with-make, I create a folder `build` inside drake-distro, and run `make` within that `build` folder. Then all the objects live within the `build` folder. But in http://drake.mit.edu/from_source.html#stay-up-to-date, we should run `make` command in `drake-distro` folder, this will create directories `build`, `pod-build`, `drake/pod-build` inside `drake-distro` folder. Which one is correct?
- Should we still call `addpath_pods` when launching MATLAB? In http://drake.mit.edu/from_source.html#test-your-installation, it says we only need to call `addpath_drake`.

I also had several problems to call MATLAB functions if I run `make` within the `drake-distro/build` folder. 
  - If I call `drake-distro/drake/addpath_drake`, I then get the error

    ```
Adding /home/hongkai/drake-distro/build/matlab to the matlab path
Error using addpath_drake (line 24)
You must run make first (and/or add your pod
build/matlab directory to the matlab path)
    ```
    I have to add `drake-distro/build/install/matlab` to my matlab path, so that I can call `addpath_drake`. 
  - Another problem is that when I call `getCMakeParam` in MATLAB, it looks into the cache file in `drake-distro/drake/pod-build/CMakeCache.txt`, which does not exist if I call `make` in `drake-distro/build` folder. But this file exists if I call `make` in `drake-distro` folder.

**Comment by liangfok** [comment]
Oops. Thanks for catching these errors. I'll submit a PR to fix the problems soon. Here are some quick responses:

> Before setting my own fork of drake as the origin remote, I need to remove the origin first. 

You don't necessarily have to _remove_ origin, just set its URL:

```
git remote set-url origin git@github.com:[your github user name]/drake.git
```

> Where should I call make command?

Since we're going to remove `drake-distro/Makefile` (see: https://github.com/RobotLocomotion/drake/pull/2758), the former is correct. We should run `make` from within `drake-distro/build`.

> Should we still call addpath_pods when launching MATLAB? 

No since we're moving away from PODs.

> I also had several problems to call MATLAB functions if I run make within the drake-distro/build folder.

Yes, I believe we need to update `addpath_drake`. there's an open PR for that here: https://github.com/RobotLocomotion/drake/pull/2599. It needs to be updated to support the fact that our current official way of build drake is within `drake-distro/build/`.
