### ISSUE TITLE
Add catkin-tools to the build servers

### ISSUE THREAD

**Issue by jhoare** [RobotLocomotion/drake#2773]
Please install ``python-catkin-tools`` package on the ubuntu AWS images.

**Comment by jhoare** [comment]
@jamiesnape Will you have a chance to get to this soon?

**Comment by jamiesnape** [comment]
Hopefully, once the OS X builds are fixed.

**Comment by jhoare** [comment]
Understood, ROS coverage is certainly less important than OS X coverage.

**Comment by jamiesnape** [comment]
Done.
