### ISSUE TITLE
support mosek solver in MixedIntegerConvexProgram

### ISSUE THREAD

**Issue by hongkai-dai** [RobotLocomotion/drake#2787]
I find `MixedIntegerConvexProgram` very convenient to use. Currently it only supports `gurobi` solver, I would like to add the support for `mosek` solver. My experience is that `mosek` can be faster than `gurobi` on some conic programming problems. @RussTedrake , what do you think?

**Comment by RussTedrake** [comment]
I think we should add it in the c++ interface, and think about taking the first pass at replacing the matlab optimization stack with mex wrappers to the c++ code.  That will be so much cleaner/better.
