### ISSUE TITLE
Taylor Approximation

### ISSUE THREAD

**Issue by dhruba-chowdhury** [RobotLocomotion/drake#2796]
Hi can you explain the Taylor Approx function because I know it is not the simple taylor series expansion that is used because the examples of Acrobot using the Taylor Approx function converts the rational dynamics  into a polynomial one.
Any comments will be helpful

**Comment by RussTedrake** [comment]
The TaylorVar class does indeed do a simple taylor approximation.  For the acrobot examples were we use taylor approximations, we simply take the expansion of e.g. `xdot = f(x,u) = H^{-1}(Bu - c)`
