### ISSUE TITLE
Add a Mac MATLAB JDK 8 Nightly Build

### ISSUE THREAD

**Issue by david-german-tri** [RobotLocomotion/drake#2800]
This is a common enough configuration that we should support it, even though the system and MATLAB JDK versions will be in conflict.  See #2772.

**Comment by jamiesnape** [comment]
I suggest we only support that. I have to rebuild the image anyway, so I suggest we test El Capitan and Java 1.8.

**Comment by david-german-tri** [comment]
Sounds reasonable to me.

**Comment by jamiesnape** [comment]
Done.
