### ISSUE TITLE
Document the Locations of the "Build" and "Install" Directories

### ISSUE THREAD

**Issue by liangfok** [RobotLocomotion/drake#2808]
Prior to #2706, they were `drake-distro/pod-build` and `drake-distro/build`, respectively.

Post #2706, they are `drake-distro/build` and `drake-distro/build/install`, respectively.

**Comment by david-german-tri** [comment]
To be clear, the statements in the original post are for `make` builds.

**Comment by liangfok** [comment]
What are the build and install directories for ninja-based builds?

**Comment by david-german-tri** [comment]
Pre-#2706, we recommended `drake-build` (and thus `drake-build/install`).

**Comment by david-german-tri** [comment]
As part of this issue, we should also check for hard-coded paths thoughout Drake.

**Comment by RussTedrake** [comment]
yes -- searching for 'pod-build' in drake reveals a number of tests and pieces of documentation that will be broken.

**Comment by david-german-tri** [comment]
All the MATLAB references to `pod-build` are now cleaned up in #2599.

**Comment by david-german-tri** [comment]
This isn't totally closed because #2599 hasn't merged yet.
