### ISSUE TITLE
Mysterious CI Flake - Unable to Checkout MATLAB License

### ISSUE THREAD

**Issue by liangfok** [RobotLocomotion/drake#2810]
# The Error

```
License checkout failed.
License Manager Error -15
MATLAB is unable to connect to the license server. 
Check that the license manager has been started, and that the MATLAB client machine can communicate
with the license server.
```
# Example Logs

* https://drake-jenkins.csail.mit.edu/job/experimental/2694/compiler=gcc,label=linux_matlab/

**Comment by jamiesnape** [comment]
Isolated network issue. Nothing I can do about it.

**Comment by liangfok** [comment]
This seems to be back: https://drake-jenkins.csail.mit.edu/job/experimental/compiler=gcc,label=linux_matlab/

**Comment by jamiesnape** [comment]
License server was down after the EC2 outage. Back now.
