### ISSUE TITLE
remove HybridSimulationConstructionSetRobot from Drake

### ISSUE THREAD

**Issue by hongkai-dai** [RobotLocomotion/drake#2814]
As mentioned in #2788, we have not used simulation construction set for a while, and we should remove the related code. Currently we have two files related

- `drake/systems/plants/dev/HybridSimulationConstructionSetRobot.m`
- `drake/examples/dev/SpringFlamingo/SpringFlamingoPlant.m`

**Comment by RussTedrake** [comment]
please do.  @hongkai-dai, fyi -- please attach labels and an assignee to any issues you create (documented here: http://drake.mit.edu/issues.html)
