### ISSUE TITLE
CTest is not respecting the return values that are explicitly set in the CI driver script

### ISSUE THREAD

**Issue by jamiesnape** [RobotLocomotion/drake#2817]
Consolidates #2342 and #2791.

I consider it high priority, but I do not think others agree, so @david-german-tri can you assign a priority?

(Note this caused a high priority issue, #2791)

**Comment by david-german-tri** [comment]
Could you elaborate the common cause of failure at work here?  Perhaps with code links to the return values that are being ignored?

**Comment by jamiesnape** [comment]
https://github.com/RobotLocomotion/drake-ci/blob/master/ctest_driver_script.cmake#L1301

**Comment by jamiesnape** [comment]
And the implicit return 0 at the end of that script. I think we went over this in detail F2F on Wednesday.

**Comment by david-german-tri** [comment]
Ah, right, I remember now - you were saying CTest does some kind of deeper inspection of the intermediate test results.  I agree this is high priority, but you gave me the impression it was low feasibility, because upstream changes to CTest would be required?

**Comment by jamiesnape** [comment]
Since we maintain CTest, it is feasible. It just may take a little time.

**Comment by david-german-tri** [comment]
OK, sounds good!  Have at it.

**Comment by jamiesnape** [comment]
Fixed in upcoming CMake 3.7.

**Comment by billhoffman** [comment]
Leaving this open, when we move to 3.7 for CI we can do the switch, it will mean changes to the ctest scripts.

**Comment by david-german-tri** [comment]
from f2f conversation with @jamiesnape, this is fixed and live in CI.

**Comment by jamiesnape** [comment]
Unfortunately.

**Comment by jamiesnape** [comment]
No longer live.

**Comment by jamiesnape** [comment]
@billhoffman `CMAKE_CAPTURE_ERROR` appears to be giving different results to `RETURN_VALUE` for at least `ctest_build()` and `ctest_test()`.

**Comment by jamiesnape** [comment]
Polar-opposite results in some cases.

**Comment by EricCousineau-TRI** [comment]
@jamiesnape Is this still relevant?
