### ISSUE TITLE
IPOPT requires F77 Environment variable to be set every time

### ISSUE THREAD

**Issue by jhoare** [RobotLocomotion/drake#2835]
CMake does not cache the variable F77 which one of the third party packages that IPOPT builds requires. 

If I have the variable set, and run cmake, I would expect it to be cached. If I try to build using the generated Makefiles/Ninja but don't have the environment variables set, the build will fail. If I had a `gfortran` library installed on my system, it would build using that, instead of the one I pointed it to at configure time, which was `gfortran-4.9`

**Comment by david-german-tri** [comment]
I think #4143 fixed this.
