### ISSUE TITLE
MATLAB on OS X with Java 8 tests failing due to segmentation violation

### ISSUE THREAD

**Issue by jamiesnape** [RobotLocomotion/drake#2839]
For example:
* https://drake-cdash.csail.mit.edu/viewTest.php?onlyfailed&buildid=53278
* https://drake-cdash.csail.mit.edu/viewTest.php?onlyfailed&buildid=53338

FYI @RussTedrake.

**Comment by david-german-tri** [comment]
Do we know with reasonable certainty that this is due to Java 8, and not due to a PR that landed during the Mac CI hardware outage?

**Comment by jamiesnape** [comment]
It could be either, but I would lean toward it being a Java 7/8 issue.

**Comment by david-german-tri** [comment]
In that case, we should bisect it.  I've kicked off an experimental build at 41d2dc2f507f36f14d5296ec6d4e440c6eb7132b - it will be #4 here once it starts up:

https://drake-jenkins.csail.mit.edu/view/Experimental/job/mac-clang-ninja-experimental-matlab/#

**Comment by jamiesnape** [comment]
https://drake-jenkins.csail.mit.edu/view/Experimental/job/mac-clang-ninja-experimental-matlab/6/

**Comment by RussTedrake** [comment]
this is the known issue with the instantaneousQP controller.  see #2165.  those tests should have been disabled.

**Comment by jamiesnape** [comment]
FYI, we also have some tests segfaulting in #2916. Once #2947 is fixed, we can evaluate whether to close this ticket.

**Comment by RussTedrake** [comment]
@jamiesnape -- please close if/when those tests are disabled.

**Comment by david-german-tri** [comment]
My memory is that we disabled these, and mac-clang-ninja-nightly-matlab-{experimental, release} is blue in CI.
