### ISSUE TITLE
file INSTALL cannot copy file liblcmtypes_bot2-core.a

### ISSUE THREAD

**Issue by jamiesnape** [RobotLocomotion/drake#2865]
https://drake-cdash.csail.mit.edu/viewBuildError.php?onlydeltap&buildid=55146

```
CMake Error at lcmtypes/cmake_install.cmake:117 (file):
  file INSTALL cannot copy file
  "/Users/elcapitan/workspace/mac-clang-continuous-release/pod-build/externals/bot_core_lcmtypes/lcmtypes/liblcmtypes_bot2-core.a"
  to
  "/Users/elcapitan/workspace/mac-clang-continuous-release/build/lib/liblcmtypes_bot2-core.a".
Call Stack (most recent call first):
  cmake_install.cmake:32 (include)


make[3]: *** [install] Error 1
```

**Comment by mwoehlke-kitware** [comment]
I have *no idea* what would cause this... it looks like a strange system error (out of disk space?).

**Comment by mwoehlke-kitware** [comment]
Is there a(n accessible) machine that is reproducing this reliably?

**Comment by jamiesnape** [comment]
Not as far as I know.

**Comment by mwoehlke-kitware** [comment]
Oh! Actually, I have a theory for what causes this and similar errors (e.g. "file too small (length=0) file '.../lib/liblcmtypes_bot2-core.a' for architecture x86_64"). Both libbot and bot2_core_lcmtypes generate this library. In parallel builds, it may be that they are tripping over each other in various ways. Probably we should either not build both, or make one depend on the other to at least force them to not be parallel. (Eventually I'd like to get rid of monolithic libbot entirely.)

**Comment by jwnimmer-tri** [comment]
We are getting unlucky, and seeing this error more often locally now.  Adding a dependency from one to the other seems like an expedient and fair work-around.
