### ISSUE TITLE
Many MATLAB tests failing during coverage builds

### ISSUE THREAD

**Issue by jamiesnape** [RobotLocomotion/drake#2916]
e.g., https://drake-jenkins.csail.mit.edu/job/linux-gcc-ninja-nightly-coverage-matlab/132/,
https://drake-cdash.csail.mit.edu/viewTest.php?onlyfailed&buildid=61035.

Note that coverage builds run in `Debug` configuration, compared with `Release` for regular builds.

FYI @david-german-tri @mwoehlke-kitware @RussTedrake.

**Comment by david-german-tri** [comment]
The Nightly -debug builds that @jamiesnape added this week confirm the problem is due to debug configuration, not due to coverage per se.  Someone needs to actually look at the root causes for these memory problems; I guess that's me and @liangfok, as this week's on-call build cops.

**Comment by jamiesnape** [comment]
If Windows is anything to go by, the mex options are suggesting one set of compiler flags and cmake is suggesting another that at least partially conflict.

**Comment by david-german-tri** [comment]
This appears fixed since the August 26 nightly.
