### ISSUE TITLE
CMake.org is really slow

### ISSUE THREAD

**Issue by wxmerkt** [RobotLocomotion/drake#2918]
Low priority/usability
Kitware/CMake doesnt have an issue tracker, so posting here and cc'ing @RobotLocomotion/kitware / @billhoffman @jamiesnape 

When going over the instructions for a new machine today and downloading CMake 3.5.2 I've noticed that the CMake servers are really, really slow - i.e. ~200KB/s average (so downloading CMake took 4mins on a GBit line). Is that normal?

Should the URL in the instructions perhaps be updated to the versions released on GitHub (they've got superfast connection), cf. https://github.com/Kitware/CMake/releases ?

**Comment by jamiesnape** [comment]
https://gitlab.kitware.com/cmake/cmake/issues
