### ISSUE TITLE
Add joint ForceTorqueSensor

### ISSUE THREAD

**Issue by mposa** [RobotLocomotion/drake#292]
A feature request to add a new sensor type, similar to the wrist force/torque sensor on Atlas. The sensor would be attached a joint between two links. This will probably require compiling a smaller RBM that consists of the children of the joint and computing its inverse dynamics to back the external wrench. Care will have to be taken to add in contact and other constraint forces.

**Comment by gizatt** [comment]
Has there been any progress on this? This would be nice to have esp. now that we're thinking about the force/torque sensor on both the arm and Atlas

**Comment by sherm1** [comment]
@mposa: by ForceTorqueSensor do you mean obtaining the reaction force at a joint as described [here](https://simtk.org/api_docs/simbody/latest/classSimTK_1_1SimbodyMatterSubsystem.html#adc629077769b8c767bd1bc160787d4af)?

**Comment by tri-ltyyu** [comment]
Use case is likely outdated. Closing for now. File new issue if needed.

**Comment by huihuaTRI** [comment]
The first step is to create a plan for this task.

**Comment by sherm1** [comment]
Fixed by #12123 -- reaction forces at joints can serve as force/torque sensors. Insert a fixed (weld) joint where the sensor should be, then use the MBP reaction forces output port to read out the forces and torques the weld is applying to hold things together.

**Comment by RussTedrake** [comment]
nice!  might it be worth adding that idea to the documentation somehwere?  so it would come up on a search?  (wouldn't it be nice if doxygen provided that search...)

**Comment by sherm1** [comment]
Thanks, Russ -> issue #12790
