### ISSUE TITLE
CDash update step failing on MATLAB non-open-source builds

### ISSUE THREAD

**Issue by jamiesnape** [RobotLocomotion/drake#2921]
Would be fixed by merging the following pull requests:
- https://github.com/RobotLocomotion/bertini/pull/3
- https://github.com/RobotLocomotion/gloptipoly3/pull/3

**Comment by david-german-tri** [comment]
General FYI - those links will 404 for anyone not on the ACL for those repositories.

**Comment by jamiesnape** [comment]
@david-german-tri Do you have push access to those repos? The pull requests are trivial additions to the .gitignore files.

**Comment by david-german-tri** [comment]
I don't.  I think this has to go through @RussTedrake.

**Comment by RussTedrake** [comment]
both of those commits have been merged.  assigning back.

**Comment by jamiesnape** [comment]
Still a problem due to the binaries in the sedumi repo.
