### ISSUE TITLE
Undefined function or variable 'slinstallprefs'.

### ISSUE THREAD

**Issue by liangfok** [RobotLocomotion/drake#2936]
Examples:
- https://drake-jenkins.csail.mit.edu/job/experimental/3065/compiler=gcc,label=linux_matlab/

**Comment by jamiesnape** [comment]
Also on MSVC 32: https://drake-cdash.csail.mit.edu/testDetails.php?test=2163344&build=86337

**Comment by david-german-tri** [comment]
Closing as wontfix in keeping with #2336.
