### ISSUE TITLE
OS X / MATLAB builds broken due to -Werror, -Wshadow

### ISSUE THREAD

**Issue by jamiesnape** [RobotLocomotion/drake#2947]
e.g., https://drake-cdash.csail.mit.edu/viewBuildError.php?buildid=61093

FYI @david-german-tri @jwnimmer-tri @mwoehlke-kitware.

**Comment by jwnimmer-tri** [comment]
Adding @rpoyner-tri FYI.

**Comment by jwnimmer-tri** [comment]
I think #2943 might be the fix here; I've just merged it.

**Comment by rpoyner-tri** [comment]
Yes, #2943 fixes all that.
