### ISSUE TITLE
Sphinx Warnings When Rendering CLion.rst

### ISSUE THREAD

**Issue by liangfok** [RobotLocomotion/drake#2949]
# The Warnings

```
/home/liang/dev/drake-distro-2/drake/doc/clion.rst:24: WARNING: Enumerated list ends without a blank line; unexpected unindent.
/home/liang/dev/drake-distro-2/drake/doc/clion.rst:28: WARNING: Bullet list ends without a blank line; unexpected unindent.
/home/liang/dev/drake-distro-2/drake/doc/clion.rst:29: WARNING: Block quote ends without a blank line; unexpected unindent.
```

**Comment by amcastro-tri** [comment]
How can I reproduce this warning @liangfok?

**Comment by liangfok** [comment]
Here are the commands assuming you're using `make` (replace `make` with `ninja` if you're using `ninja):

```
cd drake-distro/build/drake/
rm -rf doc
make documentation
```

**Comment by amcastro-tri** [comment]
@liangfok. With `ninja` I get:

`
FAILED: cd /home/amcastro/Drake/Master/drake-distro/build/drake/doc && /usr/local/bin/sphinx-build -b html -c /home/amcastro/Drake/Master/drake-distro/build/drake/doc -d /home/amcastro/Drake/Master/drake-distro/build/drake/doc/doctrees /home/amcastro/Drake/Master/drake-distro/drake/doc /home/amcastro/Drake/Master/drake-distro/build/drake/doc/sphinx
Error: Config directory doesn't contain a conf.py file.
ninja: build stopped: subcommand failed.
`

**Comment by liangfok** [comment]
Based on @jwnimmer-tri's suggestion, I updated the reproduction instructions to use `touch` instead of `rm`. @jwnimmer-tri was able to reproduce the warning using `ninja`.

**Comment by amcastro-tri** [comment]
I am able to reproduce the same warnings. If I remove (or add) CR's as requested by the warnings (that's what I understand), the warnings go away. However, the parsed documentation does not look right. 

The problem here is that I have a bullet list nested inside a numbered list. Maybe sphinx doesn't like that? ideas?

**Comment by liangfok** [comment]
I recommend figuring out how to supress the warnings since the existing `clion.rst` renders OK.

**Comment by jwnimmer-tri** [comment]
Eep, no!  Just figure out the correct `rst` syntax from the ReST specification / tutorial / documentation.

**Comment by liangfok** [comment]
FTR, this warning is still present: https://drake-cdash.csail.mit.edu/viewBuildError.php?type=1&buildid=69086
