### ISSUE TITLE
When bullet is disabled, drake no longer compiles

### ISSUE THREAD

**Issue by jwnimmer-tri** [RobotLocomotion/drake#2958]
These are the error messages:
- /home/jwnimmer/jwnimmer-tri/drake-distro/drake/systems/plants/collision/DrakeCollision.cpp:45:69: error: ‘DRAKE_ABORT_UNLESS’ was not declared in this scope
- /home/jwnimmer/jwnimmer-tri/drake-distro/drake/systems/plants/collision/DrakeCollision.cpp:47:1: error: no return statement in function returning non-void [-Werror=return-type]

**Comment by amcastro-tri** [comment]
@jwnimmer-tri: I was able to replicate the problem. Working on a solution now.
