### ISSUE TITLE
Mysterious CI Failure - foo_test - Timeout

### ISSUE THREAD

**Issue by liangfok** [RobotLocomotion/drake#2959]
# Example Errors

```
17:22:27 74/74 Test #54: lcm_publisher_system_test ................***Timeout 500.00 sec
11:21:29 74/74 Test #72: run_kuka_iiwa_arm_dynamics ...............***Timeout 500.00 sec
```

# Example Logs

## lcm_publisher_system_test
* https://drake-jenkins.csail.mit.edu/job/experimental/3132/compiler=msvc-ninja-64,label=windows/consoleFull
* https://drake-jenkins.csail.mit.edu/job/experimental/3138/compiler=msvc-ninja-64,label=windows/console

## run_kuka_iiwa_arm_dynamics
* https://drake-jenkins.csail.mit.edu/job/experimental/3143/compiler=msvc-ninja-32,label=windows/console

**Comment by david-german-tri** [comment]
Closing since Windows is no longer supported.
