### ISSUE TITLE
Consider adding "minimal externals" to supported configurations

### ISSUE THREAD

**Issue by jwnimmer-tri** [RobotLocomotion/drake#2962]
http://drake.mit.edu/developers.html lists our supported configurations.  For the "Superbuild Deps" we have both `"Default"` and `"Default + MATLAB"`.

Perhaps we should consider adding a `"Minimal"` supported configuration as well, where only `Eigen` and `googletest` are used.  Untested code is broken code -- and if we actually want to support use of Drake with a minimal footprint, we need to bring that under test.

When I tried turning off all the dependencies today as an experiment, I found several regressions: bullet (#2958), lcm (#2960), swig_matlab (#2961), and ipopt (RobotLocomotion/drake-ci#18).

What do folks think?

**Comment by jwnimmer-tri** [comment]
/CC to @RussTedrake and @david-german-tri and @jamiesnape specifically for thoughts.

**Comment by david-german-tri** [comment]
:+1:

**Comment by jamiesnape** [comment]
Sure. Debug or Release by default?

**Comment by jwnimmer-tri** [comment]
For pre-merge testing I would propose Debug, to get the best diagnostic output.  Since many, many tests will be disabled, I suspect the runtime duration of the build would be alright.  For post-merge testing, we'd probably want to have both Debug and Release (at least on one easy target, such as ubuntu).

**Comment by jamiesnape** [comment]
`WITH_SPDLOG` on or off for a minimal build?

**Comment by sherm1** [comment]
I vote for spdlog "on".

**Comment by jwnimmer-tri** [comment]
It should be off -- it is not required, and has specific code to stub spdlog when unavailable that we should be testing.

**Comment by RussTedrake** [comment]
i definitely support.  but my view is that externals should (almost) always be built in release mode.  only drake should have to go into debug mode.

**Comment by jwnimmer-tri** [comment]
I think #3092 fixed every question here.
