### ISSUE TITLE
Document the requirements / tips for adding a new external to Drake

### ISSUE THREAD

**Issue by jwnimmer-tri** [RobotLocomotion/drake#2978]
We should document the requirements / tips for adding a new external to Drake.  It is a bit error-prone at the moment.

**Comment by mwoehlke-kitware** [comment]
#2896 is going to significantly change (hopefully simplify, in some ways) the process...

**Comment by jwnimmer-tri** [comment]
I suspect that such documentation is not important; the Bazel `WORKSPACE` is fairly well documented already.  We can supplement (or fix) those upstream docs when we find a specifically confusing point.
