### ISSUE TITLE
Move RigidBodyForceElement and RigidBodySensor Vectors into RigidBodyTree

### ISSUE THREAD

**Issue by liangfok** [RobotLocomotion/drake#2979]
As requested by @amcastro-tri here: https://reviewable.io/reviews/RobotLocomotion/drake/2976#-KNqrkEnixWRftsq4j3t

The motivation is `RigidBodyForceElement` and `RigidBodySensor` are not "systems" in and of themselves. Instead, they are more like things that are contained in and attached to a `RigidBodyTree`.

Once this change is made, the description of `class ModelElementId` should be updated to indicate it reference modeling elemenents in a `RigidBodyTree` as opposed to a `RigidBodySystem`.

**Comment by liangfok** [comment]
@amcastro-tri: This may be easier said than done because doing this will change the composition of `RigidBodyTree`'s state vector, which is currently `[joint position values][joint velocity values]`. If we decide to move sensors and actuators into the `RigidBodyTree`, its state vector may need to be `[joint position values][joint velocity values][sensor state values][actuator state values]`. Significant code changes will be required in both `RigidBodyTree` and `RigidBodySystem`.

**Comment by liangfok** [comment]
@amcastro-tri, I'm going to close this issue since I assume it'll be superseded by the switch to `MultibodyWorld`. Please re-open if I'm wrong.

**Comment by amcastro-tri** [comment]
Thank you @liangfok. Yes, MBT will provide `ForceElement` objects.
