### ISSUE TITLE
Undefined function 'etime' for input arguments of type 'double'

### ISSUE THREAD

**Issue by liangfok** [RobotLocomotion/drake#3002]
# The Error

```
Undefined function 'etime' for input arguments of type 'double'.

Error in spot_etime (line 3)
wel = etime(t2{2},t1{2});
```

# Example Logs

* https://drake-jenkins.csail.mit.edu/job/experimental/3210/compiler=gcc,label=linux_matlab/consoleFull

**Comment by jamiesnape** [comment]
I do not think this is CI specific.

**Comment by liangfok** [comment]
OK I will close this issue and only re-open it if the error is encountered again.
