### ISSUE TITLE
Problem with Bertini External

### ISSUE THREAD

**Issue by liangfok** [RobotLocomotion/drake#3005]
# The error

```
$ cd drake-distro
$ git submodule update
Cloning into 'externals/bertini'...
ERROR: Repository not found.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:RobotLocomotion/bertini.git' into submodule path 'externals/bertini' failed
```

# The Problem

Repository https://github.com/RobotLocomotion/bertini does not appear to exist: https://github.com/RobotLocomotion?page=1

**Comment by jamiesnape** [comment]
It exists and is private, so this behavior is by design and not a bug.

**Comment by liangfok** [comment]
Ah. That explains why I did not see it. Thanks.

**Comment by soonho-tri** [comment]
@liangfok, I have the same problem. Do you think an easy solution is to ask a permission for `RobotLocomotion/bertini` repository?

@jamiesnape, I added a submodule on machine A and made a commit. I moved to machine B, pulled the commit. Now, I want to update submodules, so I do `git submodule update --recursive` but this issue terminates the update process in the middle. Is there an easy workaround (other than having a read permission on bertini repo)?

**Comment by jamiesnape** [comment]
CMake will run the submodule update for you automatically. If you really do not want to do that, update the submodules independently instead of using recursive.

**Comment by soonho-tri** [comment]
@jamiesnape, I see. Thank you!
