### ISSUE TITLE
support unity as an additional visualizer

### ISSUE THREAD

**Issue by RussTedrake** [RobotLocomotion/drake#3006]
@psiorx has a version of this already working... he wrote a C# module that communicates via a custom tcp/ip interface to accept draw commands (he also publishes depth buffer outputs to be used as a laser sim).  But unity loads it's own environment model directly, and drake is only thinking about the dynamics (and publishing the state) of the vehicle -- drake doesn't load the same environment.   That interface is here: https://github.com/psiorx/camera_simulator

"This repository contains some simple C# scripts that can be loaded into Unity to interface with the frame buffer and communicate with an arbitrary external system over TCP.  I have additional scripts(not in that repo) which handle extracting the depth buffer from the GPU for simulating a depth sensor as well as raycasting for simulating a scanning lidar sensor.  If interested, I can make those scripts available as well."

@LukeFletcher-TRI, @MikeElkins-TRI, and others have asked before about support for unity rendering, e.g. for VR support.  @psiorx looked into what it would take to load a urdf or similar in unity and sent this response:

"It turns out that Unity cannot load arbitrary mesh resources at runtime out of the box.  The typical workflow in Unity is to create meshes in a 3D modelling program and then convert them to the Unity GameObject format through the use of an import tool.  There is functionality that allows for loading of pre-created "AssetBundles" at runtime if the Pro version of Unity is purchased but that would still mean that any mesh would need to be specially imported into the bundle before usage.   

That being said, it is possible to create a mesh programmatically by specifying all the vertices, indices, texture coordinates, and so forth manually but that would require either writing a custom parser in C# for each of the mesh formats that is to be supported or defining an interface through which the geometry data can be communicated directly to Unity after being parsed elsewhere.

Depending on the formats that need to be supported, a custom parser could be non-trivial to create but simple text-based formats like .obj wouldn't be too bad.  If I remember correctly, Robin worked on getting raw mesh data packed into LCM message so that could be a starting point if we want to go down that route."

I figured I would move the discussion here in case others are interested as well.  Marking as backlog for now.

**Comment by tri-ltyyu** [comment]
@RussTedrake, is it still needed? If not, please close
