### ISSUE TITLE
Add gflags as a required external dependency and make use of it in Drake's executables

### ISSUE THREAD

**Issue by liangfok** [RobotLocomotion/drake#3027]
One of the first places to use it would be in `drake-distro/drake/examples/Cars/car_simulation.cc`.

**Comment by sherm1** [comment]
:+1: great idea!

**Comment by david-german-tri** [comment]
:+1: gflags would also supersede `drakeAppUtil.h`.  (Closed #1768 as a duplicate of this issue.)

**Comment by jwnimmer-tri** [comment]
I've filed a PR to attempt this, though I ported an LCM test program, not the (more complicated) cars example.

I kind of hate the `gflags` global variable meme; the composeability of `boost::program_options` is much superior IMO, but perhaps this will grow on me.  In any case, it's better than `drakeAppUtil.h`.
