### ISSUE TITLE
Should we add style guide exception for member variable names that are mathematical objects?

### ISSUE THREAD

**Issue by liangfok** [RobotLocomotion/drake#3060]
Specifically, should we allow these variable names to not have a trailing underscore?

For context, see: https://reviewable.io/reviews/RobotLocomotion/drake/2913#-KOKXMaBdJAD0EzWAk_0

**Comment by sammy-tri** [comment]
One vote against.

**Comment by david-german-tri** [comment]
I also vote against.

**Comment by sherm1** [comment]
I also vote against an exception for the trailing `_`. 

Occasionally a member exactly represents a mathematical object that is used in referenced theory or collocated documentation. In that case the short symbol name *may* result in the clearest code, and reviewers should consider that IMO. It should still have a trailing `_` though!

**Comment by rpoyner-tri** [comment]
also vote against. The trailing underscore convention solves a problem of c++ notation and clarity that overrides any misguided attempts to "match the textbook".

**Comment by liangfok** [comment]
The vote is clear. 👎
