### ISSUE TITLE
Rename RigidBodyConstraint::m_model_instance_id_set_ to be RigidBodyConstraint::model_instance_id_set_

### ISSUE THREAD

**Issue by liangfok** [RobotLocomotion/drake#3067]
The `m_` prefix and `_` suffix are redundant.

**Comment by jwnimmer-tri** [comment]
Is `RigidBodyConstraint` going to live on, or be rewritten?  If the latter, perhaps this issue should be closed.

**Comment by jwnimmer-tri** [comment]
It's in the attic, and we're no longer enhancing it.  Closing now.
