### ISSUE TITLE
Mysterious CI Failure - Marking the build as aborted.

### ISSUE THREAD

**Issue by liangfok** [RobotLocomotion/drake#3079]
# The Error

```
[drake:make] -- Installing: /home/ubuntu/workspace/linux-gcc-exBuild timed out (after 240 minutes). Marking the build as aborted.
20:06:49 Build was aborted
```

# Example Logs

* https://drake-jenkins.csail.mit.edu/job/linux-gcc-experimental-ros/75/console

**Comment by jamiesnape** [comment]
Jobs time out after 240 minutes. Your build was hanging, so the CI behaved as expected.

**Comment by liangfok** [comment]
OK thanks. It's a mystery to me why it hanged. Oh well. I will close this issue unless the problem returns.
