### ISSUE TITLE
Update LinearSystem API to return int instead of size_t

### ISSUE THREAD

**Issue by liangfok** [RobotLocomotion/drake#3086]
# Motivation

We are trying to avoid using unsigned integer values. See: http://drake.mit.edu/code_style_guide.html#clarifications

# Specific Methods

``
AffineSystem::getNumStates() const;
AffineSystem::getNumInputs() const;
AffineSystem::getNumOutputs() const;
```

Note that the above methods actually cast signed integer values into an unsigned values!

**Comment by jwnimmer-tri** [comment]
These methods are per the System1 API that uses `size_t` for the _System Concept_.  I think our time is best spent deleting System1, rather than gold plating it.

**Comment by liangfok** [comment]
Ah. I didn't realize these were specified by System 1.

**Comment by jwnimmer-tri** [comment]
Yup.  That's one of the downsides of using concepts instead of interfaces.
