### ISSUE TITLE
Add a windows-msvc-32-experimental-debug build in Jenkins

### ISSUE THREAD

**Issue by david-german-tri** [RobotLocomotion/drake#3100]
Right now, we don't have a way to do one-off testing of fixes to the Win32 debug build, e.g. #3099.

cc @hongkai-dai

**Comment by jamiesnape** [comment]
Experimental builds are parameterized. Tick the checkbox marked "debug".

**Comment by david-german-tri** [comment]
Ah, right!  I've gotten spoiled by the @drake-jenkins-bot notation.  Thanks for the reminder.
