### ISSUE TITLE
Implement System<T>::get_num_input_ports()

### ISSUE THREAD

**Issue by amcastro-tri** [RobotLocomotion/drake#3127]
Per discussion [here](https://reviewable.io/reviews/robotlocomotion/drake/3102#-KOpArdAlRcA0s6ojY8k) and f2f with @david-german-tri and @sherm1, the user should ask questions about system's connectivity to the system. The context is just used to represent the "mental picture" of the system's state.

**Comment by david-german-tri** [comment]
Under #3102, this is just a convenience wrapper around `get_input_topology().size()`.
