### ISSUE TITLE
IPOPT needs tuned to pass IK tests

### ISSUE THREAD

**Issue by sammy-tri** [RobotLocomotion/drake#3128]
Currently IPOPT doesn't pass the MATLAB testIK or the C++ and MATLAB implementation of testIKtraj.  I don't think it's a fundamental limitation of the solver, but rather just some tuning parameters.  If we want an open-source solver which works for most of our IK test suite, we'll need to figure out how to tune IPOPT.

Note that this ticket is tracking an issue where the test works using SNOPT but not IPOPT.

**Comment by tkoolen** [comment]
testIKMoreConstraints should be added to the list after https://github.com/RobotLocomotion/drake/pull/3300 was merged.

**Comment by tkoolen** [comment]
Related: https://github.com/RobotLocomotion/drake/pull/3712.

**Comment by sammy-tri** [comment]
Also, if IPOPT tuning finally becomes a thing, consider fixing the trajectory optimization test which got nerfed in #6440

**Comment by hongkai-dai** [comment]
Close this issue as we don't have testIK matlab code any more.
