### ISSUE TITLE
Add GMock to the Bazel build

### ISSUE THREAD

**Issue by david-german-tri** [RobotLocomotion/drake#3133]
CMake provides `find_package(GTest)` but not, apparently, `find_package(GMock)`.  Not sure what the best approach is.

https://github.com/RobotLocomotion/drake/blob/master/drake/CMakeLists.txt#L191

**Comment by jwnimmer-tri** [comment]
This should probably happen in the Bazel workspace, not the CMake superbuild.  Thus, we can do it ourselves anytime we want.

**Comment by david-german-tri** [comment]
> This should probably happen in the Bazel workspace, not the CMake superbuild. Thus, we can do it ourselves anytime we want.

I agree, but we can't actually start using it until the CMake build is turned down, so I'm going to leave this issue open to track it.

**Comment by david-german-tri** [comment]
Assigning to @jamiesnape for delegation as needed.  Not urgent.

**Comment by jamiesnape** [comment]
Separate library to gtest, or like this: https://github.com/google/protobuf/blob/master/gmock.BUILD.

**Comment by jamiesnape** [comment]
Ignore that. I guess they basically need to be together.
