### ISSUE TITLE
Modify Drake Appendix to Allow Direct Linking to Subsections

### ISSUE THREAD

**Issue by liangfok** [RobotLocomotion/drake#3146]
For example, I'd like to link directly to subsection D.3.

**Comment by RussTedrake** [comment]
We’re putting all of the appendix D documentation into sphinx, pulling the textbook out of the drake externals, and having the textbook pull in drake instead (flipping the dependency).  This particular issue is no longer relevant, but similar feature requests might pop up again.

**Comment by RussTedrake** [comment]
This issue is also covered by https://github.com/RussTedrake/underactuated/issues/8 .
