### ISSUE TITLE
Problems during Source installation on Windows

### ISSUE THREAD

**Issue by chang-liang** [RobotLocomotion/drake#3156]
Never succeed in "Compile Drake" in "Drake Windows Installation Instructions http://drake.mit.edu/windows.html. 
After i typed in the codes bellows, (**July 29**)
`$ cd [build artifacts directory]
$ cmake --build . --target ALL_BUILD --config **RelWithDebInfo** `
i got this problem shown on Windows PowShell which you can see here 

![1 warning and eorrs after 1 5hrs](https://cloud.githubusercontent.com/assets/6902821/17758957/29063dde-6526-11e6-8342-d41b8fc094fb.PNG)
![2 warning and eorrs after 1 5hrs](https://cloud.githubusercontent.com/assets/6902821/17758956/2904051e-6526-11e6-8417-3628b74b8ce1.PNG)

And, 
after i typed in the codes bellows, (**Aug 16**)
`$ cd [build artifacts directory]
$ cmake --build . --target ALL_BUILD --config ** Release** ` 
i got this problem shown on Windows PowShell which you can see here 

![1](https://cloud.githubusercontent.com/assets/6902821/17758968/3381ccce-6526-11e6-8498-f26d5ee22c35.PNG)
![2](https://cloud.githubusercontent.com/assets/6902821/17758970/33959bc8-6526-11e6-9739-1cbb8512d6ee.PNG)
![3](https://cloud.githubusercontent.com/assets/6902821/17758969/338c59a0-6526-11e6-8a06-470bf4384afa.PNG)
![4](https://cloud.githubusercontent.com/assets/6902821/17758967/337b3b52-6526-11e6-9d3a-8821c8684eca.PNG)

And it stoped in here after Compiling for about 1hr.

Software version :

- Visual  Studio 14 2015 Win64

- Matlab 2016a

- Cmake 3.5.2

**Comment by chang-liang** [comment]
stuck again in here today... please help... @jwnimmer-tri  , @hongkai-dai , @liangfok .
![1](https://cloud.githubusercontent.com/assets/6902821/17778813/efdbb846-6597-11e6-89a8-cb1f9ccd99cd.PNG)
![2](https://cloud.githubusercontent.com/assets/6902821/17778812/efd9f998-6597-11e6-9482-315c89b6ffcf.PNG)
![3](https://cloud.githubusercontent.com/assets/6902821/17778815/efea5b12-6597-11e6-9818-04e18fed9164.PNG)
![4](https://cloud.githubusercontent.com/assets/6902821/17778816/efec602e-6597-11e6-85b7-dc87752b23ef.PNG)
![5](https://cloud.githubusercontent.com/assets/6902821/17778814/efe6418a-6597-11e6-8dc2-ddf41fcf40c1.PNG)
![6](https://cloud.githubusercontent.com/assets/6902821/17778811/efd6eabe-6597-11e6-98fc-7dca910653c8.PNG)

**Comment by jwnimmer-tri** [comment]
I apologize, but I cannot offer windows help.  Perhaps someone from robot locomotion group can assist.

**Comment by david-german-tri** [comment]
Windows is no longer supported.
