### ISSUE TITLE
Decide, Document, and then Enforce the Names Spaces in C++ Drake

### ISSUE THREAD

**Issue by liangfok** [RobotLocomotion/drake#3162]
For example, can we decide by default to make the name spaces match the directory structure except for specific exceptions?

**Comment by sherm1** [comment]
Related discussion: #2348.

**Comment by jwnimmer-tri** [comment]
I think this will be ripe to fix as soon as the #3481 fix lands, and the Bazel support is a bit more mature.  The fix will either be "no change needed" or a simple rule relating directories to libraries.

**Comment by jwnimmer-tri** [comment]
I think it's been going pretty well.  I'm not sure what beyond cppguide we need here.  Resolved-invalid.
