### ISSUE TITLE
Audit superbuild to assess where downloads are coming from

### ISSUE THREAD

**Issue by jwnimmer-tri** [RobotLocomotion/drake#3187]
In #2771, we were downloading a tarball from Zurich, on an old FTP server that was slow and eventually failed, which meant all of our builds broke.  That's not quite to the level of leftpad, but we can do better.

With all externals turned on, we should see where any "download from the internet" are happening, and ensure we have an MIT- or TRI-controlled distribution mechanism -- either as a backup as least, or as the canonical location if possible.

I assert that Drake should download exclusively from github or Amazon, except where licensing concerns prevent us from redistributing the artifacts.

If possible, it would be awesome if CI could enforce this by firewalling the general internet, and then only whitelisting certain servers.

**Comment by jamiesnape** [comment]
The firewalling is a little tricky as it would have to be IP address based and the relevant IP ranges are not guaranteed.

**Comment by jamiesnape** [comment]
Or at least I would have to install and configure and completely different firewall or a proxy to be able to do so.

**Comment by david-german-tri** [comment]
I'm kind of surprised by that, and would like to know more, but let's take this conversation off public GitHub.

**Comment by jamiesnape** [comment]
Sure.

**Comment by jamiesnape** [comment]
Eigen comes from bitbucket. I would have thought that would be fine, but I can put a tarball in S3 if you prefer.

**Comment by jamiesnape** [comment]
GTK+ comes from win32builder.gnome.org.

**Comment by jwnimmer-tri** [comment]
I have a final answer or strong opinion about which servers we should rely on.  Perhaps we can collect the list of non-Amazon, non-github servers, and then take an overall decision?

**Comment by liangfok** [comment]
^^^ Missing "don't after "I"?

**Comment by david-german-tri** [comment]
This is trivial in the Bazel WORKSPACE file, so I'm going to close as wontfix for CMake.
