### ISSUE TITLE
Update to Eigen 3.3 beta 2 

### ISSUE THREAD

**Issue by amcastro-tri** [RobotLocomotion/drake#3211]
Thank you @tkoolen for noticing this. This would fix the issue with #3145

**Comment by tkoolen** [comment]
Just self-assigned, let me know if you're already on it.

**Comment by amcastro-tri** [comment]
Great! thank you! I'm glad you want to do this but please don't feel obliged to.

**Comment by tkoolen** [comment]
I'm running into compilation issues within `Eigen::PolynomialSolver` after updating. Trying to figure it out.

**Comment by amcastro-tri** [comment]
I figured it wouldn't be that easy, take your time. I actually still didn't close the bug issue on Eigen just to see what feedback we get from them.

**Comment by tkoolen** [comment]
Just going to keep commenting on problems I'm finding and solutions for future reference.
The `PolynomialSolver` problem goes away after updating AutoDiffScalar.h to the version in master: https://bitbucket.org/eigen/eigen/src/0b62bc896f8070c48214ffc447bc597c261933bc/unsupported/Eigen/src/AutoDiff/AutoDiffScalar.h?fileviewer=file-view-default

Not there yet.

**Comment by tkoolen** [comment]
Please do close that bug by the way. We know what happened, it's fixed in master, and you'd be wasting their time otherwise.

**Comment by tkoolen** [comment]
Just copying over the AutoDiffScalar file from master causes other problems unfortunately...

**Comment by tkoolen** [comment]
I'm having much better luck with the latest default branch (unmodified, hg 9431:5a47e5a5b02e). There's only one issue with `operator/` for `drake::functional_form` (used as custom scalar type for Eigen matrices).

**Comment by jwnimmer-tri** [comment]
Github comment parsing was overly-optimistic.  Drake still needs to bump its `eigen-pod` version.

**Comment by amcastro-tri** [comment]
@tkoolen, the Eigen people asked me if migrating to 3.3 actually does solve our issue. See here http://eigen.tuxfamily.org/bz/show_bug.cgi?id=1279

Is that correct? it seems like migrating to 3.3 causes even more issues?

**Comment by tkoolen** [comment]
3.3 beta 2 fixes the issue with #3145, but introduced several issues related to AutoDiffScalar. The fixes for those haven't made it into any released version yet.

**Comment by amcastro-tri** [comment]
So #3227 fixes this? and should we document the 
>  introduced several issues related to AutoDiffScalar

?

**Comment by tkoolen** [comment]
Yes.

Bugs fixed since 3.3 beta 2:
* http://eigen.tuxfamily.org/bz/show_bug.cgi?id=1260
* http://eigen.tuxfamily.org/bz/show_bug.cgi?id=1261
* http://eigen.tuxfamily.org/bz/show_bug.cgi?id=1264
