### ISSUE TITLE
Bad attributes in mexfiles break mac matlab builds

### ISSUE THREAD

**Issue by ggould-tri** [RobotLocomotion/drake#3223]
#3065 appears to have caused a nightly CI failure at https://drake-cdash.csail.mit.edu/viewBuildError.php?buildid=88374 .  This is acknowledged at #3206 in the comment at https://github.com/RobotLocomotion/drake/pull/3206#issuecomment-241474837 .

The failure text is a number of instances of:
```
/Users/elcapitan/workspace/mac-clang-nightly-matlab-debug/drake/util/drakeMexUtil.cpp:457:10: error: an attribute list cannot appear here
template DLLEXPORT mxArray* eigenToMatlabSparse(MatrixBase<MatrixXd> const&,
         ^~~~~~~~~
/Users/elcapitan/workspace/mac-clang-nightly-matlab-debug/drake/../drake/util/drakeMexUtil.h:38:19: note: expanded from macro 'DLLEXPORT'
#define DLLEXPORT [[gnu::visibility("default")]]
```

Assigning to @mwoehlke-kitware as he is responsible for #3065 and #3206.

Because #3206 indicates that this is a known issue being actively worked, I am not dropping the revert hammer on it just yet.

**Comment by jwnimmer-tri** [comment]
Was #3210 the fix for these, perhaps?

**Comment by mwoehlke-kitware** [comment]
> Was #3210 the fix for these, perhaps?

Yes. (Supposed to be at least... is it still failing? That *just* got merged, so the failures may predate it...)

**Comment by mwoehlke-kitware** [comment]
(Oh, I see... yes, #3210 didn't land in time to fix last night's nightlies, and there are no corresponding continuous builds that show this error.)

**Comment by ggould-tri** [comment]
I confirm that the build failure is no longer present in nightly (that nightly is yellow, but for other reasons) and so am closing this issue.

Thank you.
