### ISSUE TITLE
Move matlab code into `drake-distro/drake/matlab`

### ISSUE THREAD

**Issue by jwnimmer-tri** [RobotLocomotion/drake#3253]
As begun in #3191, we should move all matlab-related code into `drake-distro/drake/matlab`; this also includes the C++ supporting code for mex.  See https://github.com/RobotLocomotion/drake/pull/3191#issuecomment-240897342 for an overview.

The order of operations will be something like:
- Fix `util`, either:
  - stop using `util` from within non-matlab-related C++ code (ideally) (#3278); move `util` into `matlab/util`; or
  - failing that, for now just split `util` in twain like we did with `solvers` (as a fallback);
- Fix `GetFullPath`, either:
  - invoke the build of `thirdParty/bsd/GetFullPath` from within `drake/matlab` (ideally); or
  - failing that, guard it with `MATLAB_FOUND` at the top level, just like `add_subdirectory(matlab)` is guarded;
- Fix `systems`  by splitting it in twain like we did with `solvers`.
- Fix `regtests` to partition the tests by either matlab-iness, specific plan TBD.
- Consider what to do with `examples` TBD.

**Comment by jwnimmer-tri** [comment]
Given other priorities, and probably wanting to coordinate with other `CMakeLists` refactoring, I am not going to work on this immediately -- but don't be surprised if it crops up again in a few weeks.

**Comment by jwnimmer-tri** [comment]
@RussTedrake for these four files, may I move them into `drake-distro/drake/matlab/` as part of this upcoming PR, or would it be easier to keep them where they are now (`drake-distro/drake/`)?
 1. drake/addpath_drake.m
 1. drake/rmpath_drake.m
 1. drake/Contents.m
 1. drake/runAllTests.m

**Comment by jwnimmer-tri** [comment]
General FYI... work in progress will be here (N.B. will be rebased often):
https://github.com/jwnimmer-tri/drake/commits/the-great-matlab-relocation-of-aught-sixteen

**Comment by RussTedrake** [comment]
Fine to move but you'll need to update the docs in a bunch of places, too.

**Comment by jwnimmer-tri** [comment]
I think we can let `addpath_drake` remain where they are; it's not worth disrupting them, because they are not in the way like the library code was.  I also think that I am content to leave `examples` alone as well.  Thus, once #3861 merges, I think the issue can be closed, modulo a final sanity-check pass.

**Comment by jwnimmer-tri** [comment]
Wrap-up checklist:
- [x] `find drake -name examples -prune -o -name thirdParty -prune -o -name matlab -prune -o -name doc -prune -o -name \*.m -print` is clean.
- [ ] Test with rm-rf matlab and make sure all C++ tests pass.
- [ ] Do we want to rework examples also?

**Comment by jwnimmer-tri** [comment]
One nitpick issue filed as #3982, otherwise this is done.  Closing the meta-ticket.  :100:.
