### ISSUE TITLE
windows-msvc-ninja-64-continuous-debug is down

### ISSUE THREAD

**Issue by ggould-tri** [RobotLocomotion/drake#3267]
Showing `Agent Error` on the continuous.

https://drake-jenkins.csail.mit.edu/view/Continuous/job/windows-msvc-ninja-64-continuous-debug/

Assigning to kitware per buildcop documentation.

**Comment by jamiesnape** [comment]
It is a node issue unrelated to the job. Nothing Kitware can do, unfortunately.

**Comment by ggould-tri** [comment]
Seems to be back to normal
