### ISSUE TITLE
Establish Invariant that RigidBodyTree Must Actually Be a Tree After Compile() is Called

### ISSUE THREAD

**Issue by liangfok** [RobotLocomotion/drake#3293]
There are currently many call sites to `RigidBodyTree::has_parent()` (soon to be renamed `RigidBodyTree::has_inboard_joint()` in #3246) that basically want to avoid (1) the world and (2) the roots of branches that inexplicably have no kinematic path to the world.

I can think of no reason why there should be branch fragments with no kinematic path to the world. 

Thus, I believe we need to establish an invariant that every `RigidBody` in the `RigidBodyTree` have a kinematic path to the world. I suggest putting this enforcement in `RigidBodyTree::compile()`.

**Comment by SeanCurtis-TRI** [comment]
Closed via PR #4632
