### ISSUE TITLE
Standardize on `size` instead of `length` in systems/framework

### ISSUE THREAD

**Issue by david-german-tri** [RobotLocomotion/drake#3294]

**Comment by sherm1** [comment]
I think this should be `size()` for reasons just mentioned on Slack. They are:
- length is a dimension in physical simulation (for us measured in meters)
- size is used for C++ containers and is the term Eigen uses for number of elements in a vector

I would argue that our adoption of Eigen means we have already chosen a convention for this, and it is `size()`.

**Comment by sammy-tri** [comment]
I missed the voting on slack, and agree with both of @sherm1's points.

**Comment by liangfok** [comment]
Sounds like a re-vote is in order. Maybe instead of just a simple binary :+1: and :-1: , we should make it "by approval" and/or "everybody has one hundred tokens; place them in your preferred bin" type voting.

For example, since I'm voting "present", I shall put 50 tokens in :+1: and 50 tokens in :-1: .

**Comment by jwnimmer-tri** [comment]
Any new consensus here?  I'm about to write more code that will be littered with either one or the other.

**Comment by david-german-tri** [comment]
> Any new consensus here?

Not to my knowledge; team sentiment was quite divided.  Personally, I have no interest in this bikeshed, nor does the inconsistency particularly bother me.  If it doesn't bother you either, feel free to perpetuate it!

If it does bother you, maybe PR the fix you prefer?  I'll LGTM it, and anyone who objects can either get over it or escalate to Russ.  (That goes for anyone else as well!)

**Comment by jwnimmer-tri** [comment]
Alright.  I will work on a PR for `size` soon(ish).
