### ISSUE TITLE
Untracked disabled MATLAB tests

### ISSUE THREAD

**Issue by jamiesnape** [RobotLocomotion/drake#3313]
- examples/DubinsCar/runFunnel
- examples/IRB140/runPlanning
- examples/PlanarNLink/runLQR
- examples/PR2/runSaggitalPassive
- examples/Quadrotor/Quadrotor.runOpenLoop
- examples/RimlessWheel/test/testContactGradients
- examples/RimlessWheel/test/testLCPgradients
- examples/SimplePulleys/multiple_pulleys
- examples/SimplePulleys/simple_pulley
- matlab/solvers/test/sixHumpCamel
- systems/plants/test/testRigidBodyInertialMeasurementUnit
- util/test/testQuatConjugate
- util/test/testQuatProduct

**Comment by jamiesnape** [comment]
All are tagged with comments in #3306.

**Comment by RussTedrake** [comment]
won’t fix.   will be replaced by c++ versions.
