### ISSUE TITLE
Can Diagram::GetMutableSubSystemContext() abort instead of returning nullptr?

### ISSUE THREAD

**Issue by liangfok** [RobotLocomotion/drake#3319]
While debugging #3318, @naveenoid and I encountered a situation where [Diagram::GetMutableSubSystemContext()](https://github.com/RobotLocomotion/drake/blob/cf4d7d2d6b69dbf05c0619c0de13506c4cd778af/drake/systems/framework/diagram.h#L221) was returning `nullptr`. This naturally resulted in a segmentation fault in the application's code. It would be helpful if the method could abort rather than return `nullptr` so the problem can be detected earlier.

**Comment by liangfok** [comment]
Another way this issue can be resolved is to update the method's documentation to specify under what conditions `nullptr` may be returned.

**Comment by david-german-tri** [comment]
Yes, documenting it is a good idea.  I'll do that.
