### ISSUE TITLE
Use upstream Eigen instead of POD wrapper

### ISSUE THREAD

**Issue by jamiesnape** [RobotLocomotion/drake#3326]
Yes: https://bitbucket.org/eigen/eigen/ (hg repo)
No: https://github.com/RobotLocomotion/eigen-pod

(Current archive used is https://bitbucket.org/eigen/eigen/get/5a47e5a.tar.gz)

**Comment by tkoolen** [comment]
I'm in favor of this (and the related issues). Just one thing to think about: up until a few days ago (before https://github.com/RobotLocomotion/eigen-pod/pull/7), we were applying our own patches to Eigen. These patches were stored in eigen-pod. Where should they be stored in the future if we needed manual patches again? Or would we just fork Eigen and point to our own branch?

**Comment by jamiesnape** [comment]
First step is to try to upstream them.

**Comment by mwoehlke-kitware** [comment]
Another problem... I don't know that we can use an hg repo as a submodule... maybe we could use e.g. https://github.com/RLovelett/eigen as the upstream instead? (It's... not clear if or how well `git-hg` can be used for a submodule...)

**Comment by tkoolen** [comment]
Another option is to go back to `externalProject_add`.

**Comment by mwoehlke-kitware** [comment]
We never stopped using `externalproject_add`. Yes, it's wrapped in `drake_add_external` right now, but teaching that to handle externals that aren't submodules isn't a problem. The problem is whether we are willing to lose the benefits (change tracking, especially) of having externals as submodules.

**Comment by jamiesnape** [comment]
Being on upstream is more important than having a submodule in my opinion. Otherwise, I guess we mirror to a Git repository.
