### ISSUE TITLE
Use upstream Bullet instead of fork

### ISSUE THREAD

**Issue by jamiesnape** [RobotLocomotion/drake#3327]
Yes: https://github.com/bulletphysics/bullet3
No: https://github.com/RobotLocomotion/bullet3

The non-POD-specific patches in https://github.com/RobotLocomotion/bullet3/pull/1 would need to be upstreamed.

**Comment by david-german-tri** [comment]
We're off of PODS.  I think upstreaming the patches is a non-goal.

**Comment by jwnimmer-tri** [comment]
FWIW the patches are already reimplemented on the Bazel side, so we could switch to upstream once we only pull in Bullet via Bazel.
