### ISSUE TITLE
Use upstream Bertini instead of wrapper

### ISSUE THREAD

**Issue by jamiesnape** [RobotLocomotion/drake#3328]
Yes: https://bertini.nd.edu/BertiniSource_v1.5.1.tar.gz
No: https://github.com/RobotLocomotion/bertini (private repo)

Or even use [Bertini 2.x](https://github.com/bertiniteam/b2) (public repo) if it reaches parity with Bertini 1.x.

Will need logic to set MATLAB search path in Drake.

**Comment by RussTedrake** [comment]
bertini is only used for a small number of tests and is not needed immediately for the c++ development.  this one MAY be useful again soon, but for now I will remove it from the superbuild to simplify our life.
