### ISSUE TITLE
Use upstream GloptiPoly3 instead of wrapper

### ISSUE THREAD

**Issue by jamiesnape** [RobotLocomotion/drake#3329]
Yes: http://homepages.laas.fr/henrion/software/gloptipoly3/gloptipoly3.tar.gz
No: https://github.com/RobotLocomotion/gloptipoly3 (private repo)

Will need logic to set MATLAB search path in Drake.

**Comment by RussTedrake** [comment]
gloptipoly is matlab only and provides limited coverage.  i am planning to remove it.
