### ISSUE TITLE
Use non-POD version of bot2-lcmgl

### ISSUE THREAD

**Issue by jamiesnape** [RobotLocomotion/drake#3342]
Fork: https://github.com/RobotLocomotion/libbot
Upstream: https://github.com/libbot2/libbot2

**Comment by mwoehlke-kitware** [comment]
As a point of clarification: the plan here is to extract just lcmgl from the current monolithic libbot repo and give it a modern build system.

**Comment by david-german-tri** [comment]
This has been done, right?

**Comment by jamiesnape** [comment]
Still a POD as far as I can tell.
