### ISSUE TITLE
Move fork of bot_core_lcmtypes to RobotLocomotion organization

### ISSUE THREAD

**Issue by jamiesnape** [RobotLocomotion/drake#3344]
Fork: https://github.com/mwoehlke-kitware/bot_core_lcmtypes

**Comment by jamiesnape** [comment]
@david-german-tri Do you have sufficient tokens to create a repo?

**Comment by david-german-tri** [comment]
I do.  Can you remind me quickly (a) why we are using a fork from https://github.com/openhumanoids/bot_core_lcmtypes and (b) why bot_core_lcmtypes belongs to OpenHumanoids and not RobotLocomotion in the first place?

@wxmerkt FYI

**Comment by jamiesnape** [comment]
https://github.com/openhumanoids/bot_core_lcmtypes/pull/18

>Hi again, after thinking about this over the weekend, I'm going say that we cannot take on this change.
> I think that what you are suggesting would bring improvements and certainly more modern.
>
> The issue is the we do not have any software engineers working on the openhumanoids project to carry it though our ecosystem. (Compared to the drake, the project is tiny.)
>
> I think the preferred route might be for drake to avoid using this lcmtypes repository.

**Comment by mwoehlke-kitware** [comment]
Please *don't* do this... it should move upstream to the libbot organization. (But feel free to change this issue description accordingly.)

**Comment by jamiesnape** [comment]
Either works for me.

**Comment by david-german-tri** [comment]
There's a `libbot` organization?

**Comment by jamiesnape** [comment]
> There's a `libbot` organization?

News to me too.

**Comment by mwoehlke-kitware** [comment]
> There's a `libbot` organization?

There is in the github sense: https://github.com/libbot2.

**Comment by mwoehlke-kitware** [comment]
On further investigation, the current repo seems to be a dumping ground of LCM types from several projects, including drake itself. It would be good if that situation could be normalized somehow...

**Comment by sammy-tri** [comment]
https://github.com/RobotLocomotion/lcmtypes now exists to collect lcm types, and is a clone of @mwoehlke-kitware's current drake branch.

**Comment by jamiesnape** [comment]
Though we are not actually using it yet. Is there a follow up ticket or should this stay open until we do?

**Comment by david-german-tri** [comment]
Oh, we aren't?  Oops.

**Comment by mwoehlke-kitware** [comment]
Not yet. I am still working on changes on the LCM side (which will eventually become changes to RL/lcmtypes) with the desire/intent to fix all of #3397, #3683 and this at once, rather than needing 2-3 PR's for incremental updates. (Also, there are going to be non-trivial code changes to switch over, since the package name changed.)

**Comment by sammy-tri** [comment]
In https://github.com/RobotLocomotion/lcmtypes/issues/3 we effectively decided not to do this.  Any objections to closing this ticket?
