### ISSUE TITLE
Are the SpringMassSystemTest integrator tests obsolete?

### ISSUE THREAD

**Issue by david-german-tri** [RobotLocomotion/drake#3365]
Has Simulator 2.0 superseded some or all of the bulky tests in https://github.com/RobotLocomotion/drake/blob/master/drake/systems/framework/examples/test/spring_mass_system_test.cc?  If so, perhaps they should be deleted.

**Comment by sherm1** [comment]
They aren't obsolete yet but will be as soon as the Simulator can provide semi-explicit and implicit integrators since those are needed to exercise the full API.

**Comment by jwnimmer-tri** [comment]
I don't know where those tests ended up the past three years.

We now have `./multibody/plant/test/spring_mass_system_test.cc` which seems like it should live on, and `./systems/plants/spring_mass_system/test/spring_mass_system_test.cc` also is okay?  Assuming it's OK to close this for now.
