### ISSUE TITLE
Mirror eigen to RobotLocomotion/eigen-mirror

### ISSUE THREAD

**Issue by jamiesnape** [RobotLocomotion/drake#3370]
Since Eigen uses Mercurial and we need to be able to reference a Git submodule. Toward #3326.

**Comment by jamiesnape** [comment]
FYI @mwoehlke-kitware.

**Comment by jwnimmer-tri** [comment]
Is https://github.com/RLovelett/eigen a sensible alternative?

**Comment by jamiesnape** [comment]
Is the author affiliated with the Eigen project? If not, then it could disappear at any moment.

**Comment by RussTedrake** [comment]
i've created https://github.com/RobotLocomotion/eigen-mirror (currently empty) for you in case you were blocked on that.

**Comment by jamiesnape** [comment]
Thanks.

**Comment by jamiesnape** [comment]
Done.
