### ISSUE TITLE
MATLAB JVM detection logic can produce spurious warnings in ccmake

### ISSUE THREAD

**Issue by david-german-tri** [RobotLocomotion/drake#3379]
Steps to reproduce:

1. Clean checkout of drake on a system where the JDK version mismatches the MATLAB JVM version.
2. `mkdir build && cd build && ccmake ..`
3.  `c` to configure
4. When presented with a warning about mismatched JVM version, `e` to exit and `q` to quit.
5. `ccmake ..` again
6. `c` to configure

Expected behavior: Another warning about JDK version mismatch.
Actual behavior: `Could not determine MATLAB JVM version because MATLAB exited with nonzero result.`

Presumably something is being scribbled on the CMakeCache.txt that accounts for the change.  We should investigate, but in the meantime, it's perfectly OK to press `g` to generate and exit after configuring.  The build will work fine; the warning is spurious.

**Comment by david-german-tri** [comment]
@siyuanfeng-tri @Lucy-tri FYI

**Comment by jamiesnape** [comment]
I see the issue. Patch will be up shortly.

**Comment by david-german-tri** [comment]
Yeah, looks like a nested-conditional thing.

**Comment by jamiesnape** [comment]
(Would cause the warning with repeated `cmake` calls, not just `ccmake`, though it would be less obvious.)
