### ISSUE TITLE
Update links on releases page

### ISSUE THREAD

**Issue by scpeters** [RobotLocomotion/drake#3402]
The [releases page](https://github.com/RobotLocomotion/drake/releases) includes [links to a wiki](https://github.com/RobotLocomotion/drake/wiki/FromBinary) that is no longer hosted in this github repository. I think these links should be redirected to:

* http://drake.mit.edu/from_binary.html

**Comment by liangfok** [comment]
I believe I fixed the issue. PTAL. Thanks.

**Comment by scpeters** [comment]
thanks!
