### ISSUE TITLE
ROS CI Servers not reporting to Drake-ROS CDash

### ISSUE THREAD

**Issue by jhoare** [RobotLocomotion/drake#3418]
Reported in #3409 the ROS CI have not been successfully updating to CDASH.

Some testing has narrowed it down to this change in the CI scripts: https://github.com/RobotLocomotion/drake-ci/commit/c1e545a455241d6df60621fc22abcd0ef099cf83

**Comment by david-german-tri** [comment]
This appears to still be broken, but since no one has complained about it in 6+ months, I'm going to tag it as backlog.

**Comment by jamiesnape** [comment]
Also, how we do ROS builds is more than likely going to change significantly after the Bazel switch, so we should ideally postpone until then.
