### ISSUE TITLE
Improve Robustness of Drake→DrakeVisualizer LoadRobot Message In Terms of Message Loss and Reordering

### ISSUE THREAD

**Issue by liangfok** [RobotLocomotion/drake#3422]
# Problem Definition

Currently, message loss may result in Drake Visualizer not receiving a `LoadRobot` message resulting in an unrecoverable error. This prevents reliably running DrakeVisualizer and Drake on different machines.

This issue should be addressed either after or along with #3421.

# Allowed Assumptions

**None!** The solution to this method must be robust against message loss at any level of the network stack. It must also be robust against out-of-order message delivery. It must guarantee that the Drake Visualizer _eventually_ work as long as some network communication _eventually_ succeeds.

**Comment by rpoyner-tri** [comment]
I don't understand the scope of what is wanted here? Are we "fixing" the properties of UDP multicast in LCM? Are we choosing another transport layer?

**Comment by liangfok** [comment]
Nope. This issue does not replace LCM or its underlying use of UDP. It simply establishes a new Drake-level communication protocol that is not brittle against message loss.

**Comment by liangfok** [comment]
For example, one idea is to modify Directory to tell Drake "hey I haven't received a `LoadRobot` message yet" or "hey, I just received a draw message containing links I'm not aware of, please send me another `LoadRobot` message".

**Comment by jwnimmer-tri** [comment]
I cannot imagine a solution to #3421 that does not also solve this issue.

**Comment by liangfok** [comment]
@rpoyner-tri proposed a launch script solution for #3421 that would not solve this.

**Comment by jwnimmer-tri** [comment]
That's a work-around (on a per-demo basis), not a solution.

**Comment by liangfok** [comment]
@jwnimmer-tri I clarified the difference by updating the descriptions of both this issue and #3421. PTAL.

**Comment by jwnimmer-tri** [comment]
Okay.  I guess if #3421 assumes processes never restart, then some solutions there would not fix this issue.  I still find it likely that any reasonable rework of the message choices would solve both of these issues at once.

**Comment by liangfok** [comment]
:+1: for a single PR that can fix both this issue and #3421. The only reason why I created two issues is because I sensed some pessism in https://github.com/RobotLocomotion/drake/issues/3421#issuecomment-246486286 that it could be solved in a single PR.

Here's to incremental PRs!

**Comment by rpoyner-tri** [comment]
Solving this PR will require some pretty deep semantic changes to the protocol, since it would no longer be adequate to share various resources by file name. I am unconvinced that anyone actually wants this.

**Comment by liangfok** [comment]
Note that solving this PR does **not** require ensuring that Drake and Drake Visualizer can run on different machines. However, this PR can be thought of as a baby step towards that direction.

I think this PR can be solved by a Drake-level protocol involving the retransmission of the `lcmt_viewer_load_robot` message and optimizations to Director that enables it to process such a message without reloading everything.

**Comment by rpoyner-tri** [comment]
Well, if we're not considering ttl>0, I don't think message loss is even worth discussing. Anything else this issue could address is already covered by #3421.
