### ISSUE TITLE
Drake Proper Should Not Use ROS Environment Variables

### ISSUE THREAD

**Issue by liangfok** [RobotLocomotion/drake#3435]
# Problem Definition

Drake's `drake-distro/drake/systems/plants/xmlUtil.cpp` currently contains a method called [populatePackageMap()](https://github.com/RobotLocomotion/drake/blob/master/drake/systems/plants/xmlUtil.cpp#L307) that accesses the following two environment variables, which belong to ROS:
1. ROS_ROOT
2. ROS_PACKAGE_PATH

This causes problems when you have multiple development clones of Drake where one is _inside_ a ROS Catkin workspace while the others are _outside_ of a ROS Catkin workspace (assuming the environment variables are configured to point to the aforementioned ROS Catkin workspace, which will be the case if you've followed [these instructions](http://drake.mit.edu/from_source_ros.html)).

Basically, the problem is where the clones of Drake outside of the ROS Catkin workspace end up searching for resources belonging to Drake inside a Catkin workspace. This problem could be avoided by modifying Drake proper to not make use of ROS' environment variables.
# Proposed Solution

Modify Drake proper to not access ROS environment variables. Remove the `populatePackageMap()` method. Environment variables should generally be avoided if at all possible since they often introduce system variability and difficult-to-resolve bugs.

Instead, the path information contained within the aforementioned ROS environment variables can be passed to Drake as an API parameter, possibly based on command-line arguments. This will allow developers to ensure that a clone of Drake only accesses resources that belong to it.

**Comment by liangfok** [comment]
@jwnimmer-tri informs me that he ran into a seemingly infinite loop when executing `ctest -VV -R rigid_body_constraint` after performing a Bazel build. I suspect this may be caused by `populatePackageMap()`, but haven't verified this.

**Comment by patmarion** [comment]
Quick proposal: the call to populatePackageMap() should be removed from the urdf parser.  Instead, an application could manually call populatePackageMap("ROS_PACKAGE_PATH") if it needed to populate a package map with that environment variable, then pass the result to the urdf parser.  This is how Director functions, it populates a package map in its own application specific way, then passes the data to drake's URDF parser.  Currently, populatePackageMap() is always called by parser_urdf.cc, even if the caller passed in a fully populated package map.

**Comment by patmarion** [comment]
Note, drake's examples will still need to call populatePackageMap() in order to maintain their functionality, but at least they would have the option to restrict the search to a specific location (like a path given on the command line).
