### ISSUE TITLE
CMake installation instructions export PATH in a bad way

### ISSUE THREAD

**Issue by tkoolen** [RobotLocomotion/drake#3463]
The instructions [here](http://drake.mit.edu/ubuntu_trusty.html) end with running a command that adds a line to .bashrc, which prepends the CMake bin directory to path, but in doing so, it evaluates the PATH variable. So instead of ending up with
```
export PATH=/home/twan/tools/cmake-3.6.2-Linux-x86_64/bin:$PATH
```
as desired, you end up with
```
export PATH=/home/twan/tools/cmake-3.6.2-Linux-x86_64/bin:/home/twan/tools/cmake-3.5.2-Linux-x86_64/bin:/usr/lib/ccache:/opt/ros/indigo/bin:/usr/lib/ccache:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
```
This causes future edits to PATH in .bashrc before this line to get clobbered.

**Comment by jhoare** [comment]
This took me a bit to understand until I actually looked at the documentation, and I agree. 

The fix would be to change the document from reading:
```
echo "export PATH=`pwd`:$PATH" >> ~/.bashrc
```

to:
```
echo "export PATH=`pwd`:\$PATH" >> ~/.bashrc
```
