### ISSUE TITLE
move drakeURDF.html to drake.mit.edu

### ISSUE THREAD

**Issue by RussTedrake** [RobotLocomotion/drake#3476]
Related to #2881 .

It looks like drake002 is still used to host the urdf xml schema documentation (which may be out of date by now).  is that already being generated by the AWS host?  if not, what are the remaining steps?

**Comment by liangfok** [comment]
I assume this issue is referring to http://drake002.csail.mit.edu/drake/urdf/drakeURDF.html, which is linked to from http://drake.mit.edu/?

**Comment by RussTedrake** [comment]
correct.

**Comment by jamiesnape** [comment]
> is that already being generated by the AWS host?

No, it is not. Do you have a script to generate it?

**Comment by RussTedrake** [comment]
it was in the makefile that got nuked in the doc directory.  
```
	ifeq ($(shell uname -p),Darwin)
	  cd doc && /Applications/oxygen/schemaDocumentationMac.sh drakeURDF.xsd -cfg:oxygen_export_settings_html.xml	
	else
	  # note that I manually installed oxygen to my home oxygen directory
	  cd doc && $(HOME)/oxygen/schemaDocumentation.sh drakeURDF.xsd -cfg:oxygen_export_settings_html.xml	
	endif 
```

**Comment by david-german-tri** [comment]
Done in https://github.com/RobotLocomotion/drake-ci/pull/72
