### ISSUE TITLE
Consider Generalizing LCM Translator Method Names

### ISSUE THREAD

**Issue by liangfok** [RobotLocomotion/drake#3483]
# Current Proposal
LCM Translators have the following two methods:

1. `LcmAndVectorBaseTranslator::TranslateLcmToVectorBase()`
2. `LcmAndVectorBaseTranslator::TranslateVectorBaseToLcm()`

I'm thinking about simplifying them to be:

1. `LcmAndVectorBaseTranslator::DeSerialize()`
2. `LcmAndVectorBaseTranslator::Serialize()`

There are several motivations:

1. The method names will be easier to read.
2. The intent of the methods will be easier to understand.
3. The same method names can be used by translators for other middleware systems like ROS. This consistency will aid in understanding due to familiarity.

Thoughts?

# Older Proposals

I'm thinking about simplifying it to be:

1. `LcmAndVectorBaseTranslator::FromLcm()`
2. `LcmAndVectorBaseTranslator::ToLcm()`

**Comment by liangfok** [comment]
Actually, another idea is to generalize the translators to support more than just LCM. I'm going to update this issue to reflect this new idea.

**Comment by liangfok** [comment]
Done. @jwnimmer-tri, since you consulted on the original design, I am specifically seeking your opinion.

**Comment by jwnimmer-tri** [comment]
IMO, both new name proposals are superior to the existing names.
I think it's a toss-up for which new pair is better, so you get to choose.

Nit: `DeSerialize` should be just `Deserialize`.

**Comment by liangfok** [comment]
OK thanks. I'll probably go with `Serialize` / `Deserialize` since that's middware agnostic. The middleware will be implied by the name of the translator class.
