### ISSUE TITLE
RigidBodyPlant Unit Test Should Not Rely on Parsers

### ISSUE THREAD

**Issue by liangfok** [RobotLocomotion/drake#3492]
# Problem Definition

The unit test for `RigidBodyPlant`is:

[drake-distro/drake/systems/plants/rigid_body_plant/test/rigid_body_plant_test.cc](https://github.com/RobotLocomotion/drake/blob/131f6f42d0041c910bacee5e7d186c498d137405/drake/systems/plants/rigid_body_plant/test/rigid_body_plant_test.cc)

It currently uses [Drake's URDF parser](https://github.com/RobotLocomotion/drake/blob/ad24abbd7213876169e978fbb383d0561f99e199/drake/systems/plants/parser_urdf.h) to load the `RigidBodyTree` within the `RigidBodyPlant`. This makes the unit test brittle since it will fail on parser-specific bugs. Ideally, it should only fail on bugs that are `RigidBodyPlant`-specific.

A second problem is we want to eventually decouple the parsers from the multi-body dynamics model (which includes the `RigidBodyTree`). Our goal is to allow the software libraries that contain the parsers to link against the libraries that contain the multi-body dynamics model, sensors, actuators, etc., but not the other way around.
# Action Item

Remove the use of the parser from the unit test. Programmatically initialize the `RigidBodyTree` within the `RigidBodyPlant` using its C++ API.

**Comment by RussTedrake** [comment]
I don’t see that as a problem?  perhaps we need coverage for the c++ api, but what you describe sounds to me like the test gives coverage to both the tree and the parser.

**Comment by liangfok** [comment]
My motivation for creating this issue is based on @jwnimmer-tri's comment here: https://github.com/RobotLocomotion/drake/pull/3228#issuecomment-243647053.

Specifically, the statement:

> The unit tests should not be loading sdfs (the parser should be out of scope); the RBTs should be constructed programmatically.

**Comment by nkoenig** [comment]
I try to resolve this pull request.

**Comment by jwnimmer-tri** [comment]
Wontfix.
