### ISSUE TITLE
Mysterious CI Failure - Index File Smaller Than Expected, Unable to Recurse Into Submodule Path

### ISSUE THREAD

**Issue by liangfok** [RobotLocomotion/drake#3499]
# Example Error

```
fatal: index file smaller than expected
Failed to recurse into submodule path 'externals/meshconverters'
```
# Example Logs
- https://drake-jenkins.csail.mit.edu/job/experimental/4742/compiler=gcc,label=linux,type=release/

**Comment by david-german-tri** [comment]
@stonier This is a tracking issue for a CI flake. In my view, no action is required, and it will likely be moot after CMake is turned down.
