### ISSUE TITLE
Use nlopt CMake build instead of autotools

### ISSUE THREAD

**Issue by jamiesnape** [RobotLocomotion/drake#3503]

**Comment by nkoenig** [comment]
I experienced a problem that may be related to this issue. nlopt was not building because `configure` was not found. I had to enter `drake/externals/nlopt` and manually run `./autogen.sh`.

**Comment by jwnimmer-tri** [comment]
@nkoenig FWIW, at one point we were missing `libtool` in the installation instructions that let to errors like that.  Might be worth checking.

**Comment by nkoenig** [comment]
Thanks. I just had to clean out my build, and then it worked.

**Comment by jamiesnape** [comment]
Looks like the latest nlopt only supports CMake now.
