### ISSUE TITLE
drake-jenkins-bot spams PRs from users who are not org members

### ISSUE THREAD

**Issue by david-german-tri** [RobotLocomotion/drake#3537]
"Can one of the admins verify this patch?" ad infinitum.  Most recently #3536 (though apparently someone cleaned up the thread afterwards).

**Comment by jamiesnape** [comment]
Very, very difficult to fix. I will try again, but it is a fundamental problem with the design of the GitHub pull request plugin.

**Comment by david-german-tri** [comment]
Closing as will-not-fix; let's just make sure to add new contributors to the org.

**Comment by jwnimmer-tri** [comment]
@david-german-tri Recent evidence suggests that this failure mode is really no way to run an open-source project.  Can we put this back on the radar, even if it doesn't happen right away?

If nothing else, it seems like forking the plug-in and commenting out the "verify this patch" emission should be a work-around.  I think having the bot post 0 this message times is way better than dozens of times.

**Comment by jwnimmer-tri** [comment]
@jamiesnape @BetsyMcPhail How feasible is it to get _any_ kind of work-around in place for this?  Is it in fact possible to just turn off that one message entirely (or maybe all post-backs entirely)?

**Comment by jamiesnape** [comment]
Someone would need to wade through the spaghetti of code in the plugin, but I think we are currently all backed up with working on the CMake-Bazel changeover, so not sure we have any free cycles to work on it immediately unless you would wish to reprioritize.

**Comment by jwnimmer-tri** [comment]
Can you link to the plugin source code?  I bet @stonier could do it quickly.

**Comment by jamiesnape** [comment]
Here, https://github.com/jenkinsci/ghprb-plugin, but I have to test it before it is deployed on production, and that takes time. That plugin is fundamental to our workflow, so unless this is suddenly a critical issue, this should wait.

**Comment by jwnimmer-tri** [comment]
Alright, maybe we can prepare a candidate change but wait on testing / deploying.

**Comment by jamiesnape** [comment]
Sure.

**Comment by jwnimmer-tri** [comment]
I read through the plug-in's code.  In the Jenkins `/configure` screen, in the "GitHub Pull Request Builder" section, after opening the "Advanced" fold (near the "Admin List" textbox), there is a config setting named "Request for testing phrase".  I believe if we set that to empty, the bot will no longer spam us.

https://github.com/jenkinsci/ghprb-plugin/blob/b49fbc7/src/main/java/org/jenkinsci/plugins/ghprb/GhprbRepository.java#L243

@jamiesnape Can we try this, at some point?

**Comment by jamiesnape** [comment]
We can, but unfortunately I have to go through every single job and update the setting, so it may take a while.

**Comment by jwnimmer-tri** [comment]
I guess I was thinking about doing a quick test to confirm my reading of the code was correct, though yeah -- just changing one build's setting would be difficult to tell whether the spam went down by one.

**Comment by jamiesnape** [comment]
I think this may finally be fixed. I just need a volunteer with a non-whitelisted GitHub account that does not mind the risk of getting spammed 84 times.

**Comment by jamiesnape** [comment]
I guess I had volunteers in #9234 and #9236.
