### ISSUE TITLE
Drake's IIWA Model Cannot be Loaded into Gazebo

### ISSUE THREAD

**Issue by liangfok** [RobotLocomotion/drake#3543]
# Problem Definition

[Drake's IIWA model](https://github.com/RobotLocomotion/drake/blob/a2cb01650579aa0e1ce4a4b19743fa641d7cdc10/drake/examples/kuka_iiwa_arm/urdf/iiwa14.urdf) currently references `.obj` (i.e., [Wavefront](https://en.wikipedia.org/wiki/Wavefront_.obj_file)) files because its visualizer [only supports this format](https://github.com/RobotLocomotion/drake/blob/5a7f663a2b9466c2b7225ad2ad1ebd0751aa5cac/drake/systems/plants/shapes/Geometry.cpp#L191). Unfortunately, Gazebo does _not_ support `.obj` files and instead supports `.dae` (i.e., [COLLADA](https://en.wikipedia.org/wiki/COLLADA)) files. Because of this, we are unable to load Drake's IIWA model into Gazebo. Being able to load the same model into Gazebo is beneficial since it will enable us to do comparisons and provide an alternative framework within which to debug and improve the model.
# Proposed Solutions

The following options are sorted from least effort the most effort.
## Option 0

Automatically convert `.obj` to `.dae` to the other file format on-demand. This can be done automatically by the build system. It could also be done manually by running a script. Basically, the idea is to maintain a single "master" version from which other versions using different file formats can be derived.
## Option 1

Use [xacro](http://wiki.ros.org/xacro) to generate two URDFs. One will be called `iiwa14_drake.urdf`, which references `.obj` files, and other will be called `iiwa14_gazebo.urdf`, which references `.dae` files. Since the same code generator is used to create both files, there shouldn't be a problem keeping the two syncronized.
## Option 2

Convert `iiwa14.urdf` to [SDF](http://sdformat.com/) and use embedded ruby to generate a version for Gazebo and another version for Drake as described here: http://answers.gazebosim.org/question/14063/how-can-i-declare-a-variable-in-modelsdf-file/.
## Options 3

Modify Drake to support `.dae` files or Gazebo to support `.obj` files. I'm unsure how much work and time this will take.
# References

For reference, see: https://github.com/robotlocomotion/drake/pull/3507#issuecomment-248637867

**Comment by sherm1** [comment]
Modifying Gazebo to support `.obj` files for geometry seems like the cleanest solution, and I think it would get used a lot. What do you think @nkoenig ?

**Comment by nkoenig** [comment]
I agree with @sherm1. Gazebo should support `.obj` files. We'll get started on that asap.

**Comment by RussTedrake** [comment]
Actually I believe director supports anything that vtk supports, include dae, etc.

**Comment by nkoenig** [comment]
Gazebo 7 now supports loading OBJ files. A debian release will be available today or tomorrow.

**Comment by sherm1** [comment]
This is great news, Nate -- thanks!

**Comment by jwnimmer-tri** [comment]
Gazebo should be able to do this now / soon.

**Comment by liangfok** [comment]
@nkoenig, does Gazebo 8 not support `.obj`? I just tried loading Drake's IIWA model into Gazebo 8 and the visualizations did not work.
