### ISSUE TITLE
Introduce DrakeNumTraits?

### ISSUE THREAD

**Issue by david-german-tri** [RobotLocomotion/drake#3544]
In the most straightforward (and likely most common) discrete system, the sampling rate is fixed.  Computing the next sample time in this case requires an integer rounding operation such as `ceil`.  Those operations will be available on many important scalar types, such as `double` and `AutoDiffScalar`, but not e.g. on `Polynomial`.  

We would like to be able to support this simple case in `LeafSystem`, but still compile a `LeafSystem` specialized on non-`ceil` ScalarTypes.  Discrete systems specialized on those types should just throw a runtime error if simulated.  To achieve this, we need conditional compilation that selects an appropriate implementation of `DoCalcNextSampleTime` for the scalar type.

`Eigen::NumTraits<T>` is the [type trait struct for Eigen scalars] (https://eigen.tuxfamily.org/dox/NumTraits_8h_source.html).  None of the existing traits answer the question "does `ceil` make sense for this type"?  Therefore, I'm interested in adding a `DrakeNumTraits<T>` to `drake/common` for additional Drake-specific traits.  I think this first use case would be a boolean `IsOnRealLine`, or something like that.  If you set that to true in your traits, you're obligated to implement `ceil`, and the compiler will remind you of that fact as soon as you try to specialize `LeafSystem`.

Any feedback on this idea before I go and do it?

**Comment by sherm1** [comment]
`DrakeNumTraits` seems reasonable. My preference though would be to require all our Scalar types to be execution-compatible like AutoDiffScalar is. (We discussed that previously for FunctionalForm.) Without that numerical carry-along, the Scalar types can't follow the same execution path through the code as a plain double would do which limits their utility to straight-line code. Also, having them executable would avoid a lot of metaprogramming magic of the kind you are contemplating.

**Comment by jwnimmer-tri** [comment]
> ... require all our Scalar types to be execution-compatible like AutoDiffScalar is.

I believe that this would make some kinds of analyses unsound.  Let's be sure to discuss before we choose that road.  (I don't think we need to pursue it immediately?)

**Comment by RussTedrake** [comment]
fwiw - I think implementing our own NumTraits sounds completely reasonable (in fact, I can’t think of any reasonable alternative).

**Comment by RussTedrake** [comment]
Matlab uses isNumeric instead of isOnRealLine.  I like that a bit better

**Comment by amcastro-tri** [comment]
I completely support this!

**Comment by david-german-tri** [comment]
It's in #3587!
