### ISSUE TITLE
Rename RigidBodyTree::get_number_of_foo() to be RigidBodyTree:get_num_foo()

### ISSUE THREAD

**Issue by liangfok** [RobotLocomotion/drake#3549]
Our style guide explicitly allows for the "num" abbreviation:

https://google.github.io/styleguide/cppguide.html#General_Naming_Rules

This rename should happen to be consistent with the usage of "num" in `RigidBodyPlant`.

**Comment by sherm1** [comment]
FYI, @SeanCurtis-TRI.

**Comment by RussTedrake** [comment]
This seems likely to break a lot of external code.  Will you deprecate the previous method names?

**Comment by liangfok** [comment]
Definitely! I don't plan on removing the methods until Release 1.0.
