### ISSUE TITLE
Require that all children of a Diagram have unique names.

### ISSUE THREAD

**Issue by david-german-tri** [RobotLocomotion/drake#3556]

**Comment by sherm1** [comment]
:+1: This would allow unique "pathnames" for each subsystem in a diagram. It could also be used to provide unique input and output port names and unique parameter names.

**Comment by liangfok** [comment]
Just wondering: Does this apply to "immediate" children or all the way down to the youngest descendants? For example, if I create a `Diagram` called "wheel" that contains numerous systems like "Tire", "Rim", "Bearing", "Bushing", "HubCap", "ValveStem", can I add four instances of this `Diagram` to a "Vehicle" Diagram? Is the proposed rule "...to have unique full path names", which includes the name of the ancestor `Diagram` objects?

I was just looking at http://drake.mit.edu/doxygen_cxx/classdrake_1_1systems_1_1_diagram.html#a628bfe0e8835a0144d79b2a38424420d and didn't see a name associated with a `Diagram`.

**Comment by sherm1** [comment]
> Does this apply to "immediate" children or all the way down

Just immediate children -- it's exactly analogous to file names in a directory structure.

**Comment by liangfok** [comment]
Thanks. I just realized that `Diagram` is a subclass of `System`, which has `get_name()` and `set_name()`.

**Comment by david-german-tri** [comment]
There are several existing Diagrams that violate this rule.  I'm sizing up a cleanup pass now.
