### ISSUE TITLE
CLion setup guide is GCC-specific

### ISSUE THREAD

**Issue by tkoolen** [RobotLocomotion/drake#3571]
The CLion setup guide at http://drake.mit.edu/clion.html contains:

> Under CMake Options expand the tab Pass system and custom environment. Add the following environment variables. (You can copy these from this documentation one at a time and click on the paste button at the right of the environment variables dialog.)
> CC=gcc-4.9
> CXX=g++-4.9
> FC=gfortran-4.9
> F77=gfortran-4.9

A labmate who's just getting up to speed on Drake development and is using OSX/clang followed these instructions to the letter, resulting in cmake complaining about not being able to find a compiler.

**Comment by naveenoid** [comment]
I had the same problem after update of my Clion version. Have you got any updates on this issue?

**Comment by tkoolen** [comment]
Just don't define those variables.

**Comment by jwnimmer-tri** [comment]
We just made that edit for Ubuntu 16.04 users to this same document.  Sounds like adding an OSX caveat along the same lines would be an easy fix.

**Comment by RussTedrake** [comment]
@seancurtis-tri has updated the instructions recently and seems to have taken on the role of local clion guru.  assigning this to him (possibly to close as “done”)

**Comment by SeanCurtis-TRI** [comment]
The documentation for this step says:

> [This step only for Ubuntu 14.04 - Trusty]. Under CMake Options expand...

I'm content that it should be sufficiently clear for mac users.  I'm closing this.
