### ISSUE TITLE
Mysterious CI Failure: MATLAB Killed because the Java VM Could not be Terminated

### ISSUE THREAD

**Issue by liangfok** [RobotLocomotion/drake#3592]
# The Error

```
MATLAB killed because the Java VM could not be terminated for 30 seconds.
This could be due to a thread or timer that started right before shutdown,
or a finalizer or shutdown hook that took too long to run.
```

# Example Logs

* https://drake-jenkins.csail.mit.edu/job/experimental/5033/compiler=gcc,label=linux_matlab,type=release/

**Comment by david-german-tri** [comment]
Well, that's a new one.  I'm going to guess it's a flake that will be rarely reproduced and never explained.  @BetsyMcPhail @jamiesnape assigned to you in case you think otherwise, but feel free to close unresolved rather than investigate.

**Comment by jamiesnape** [comment]
I would not know where to start to reproduce it. I doubt it is CI specific.

**Comment by nemo8130** [comment]
Same Error ! 

MATLAB killed because the Java VM could not be terminated for 30 seconds.
This could be due to a thread or timer that started right before shutdown,
or a finalizer or shutdown hook that took too long to run.

I have a 4 GB RAM in Ubuntu 18.04
