### ISSUE TITLE
"test" project does not appear in CLion

### ISSUE THREAD

**Issue by SeanCurtis-TRI** [RobotLocomotion/drake#3610]
The expectation is that there is a CMake target that should appear as a target in build called "test", which should invoke running all tests.  In my particular build (and, anecdotally, others) it is missing.

The full list of targets which CLion _does_ recognize are included below as screen captures.

![targets01](https://cloud.githubusercontent.com/assets/22159799/18927522/2df1f5de-8571-11e6-81fa-a63c154b6fba.png)
![targets02](https://cloud.githubusercontent.com/assets/22159799/18927521/2dd933d2-8571-11e6-8968-37378840e200.png)
![targets03](https://cloud.githubusercontent.com/assets/22159799/18927520/2dd7e810-8571-11e6-8a95-23aac6446eb7.png)
![targets04](https://cloud.githubusercontent.com/assets/22159799/18927519/2dd74f36-8571-11e6-9c61-11859e81ea00.png)

**Comment by jamiesnape** [comment]
@SeanCurtis-TRI Is this still an issue for you. I am assuming probably not.

**Comment by SeanCurtis-TRI** [comment]
Correct. We can close this out.
