### ISSUE TITLE
Drake/ROS CI Needs xacro To Be Installed

### ISSUE THREAD

**Issue by liangfok** [RobotLocomotion/drake#3615]
# Motivation

It is often useful to generate a URDF using [xacro](http://wiki.ros.org/xacro) since it enables small variations of a particular model to be kept in sync and reduces verbosity when a model consists of numerous similar parts (e.g., a left arm and a right arm, or all four wheels of a car).

PR #3609 includes a test that uses `xacro.py` (the main executable script in the `xacro` ROS package) to generate and load a URDF into the ROS parameter server. The apparent lack of `xacro.py` is causing that PR to fail CI testing.

# Action Item

Install `xacro.py` by executing the following command:

```
$ sudo apt-get install ros-indigo-xacro
```

# Additional Note

Drake has a copy of `xacro.py` here: `drake-distro/drake/thirdParty/bsd/xacro/xacro.py`. If we're unable to install the ROS Indigo version of `xacro.py`, I might be able to modify the aforementioned unit test to use the version that's in Drake. I'd prefer to use ROS Indigo's version since I believe it's more "official".

**Comment by liangfok** [comment]
@david-german-tri, I'm going to assign this to you. Can you please reassign it to the appropriate person? Thanks.

**Comment by liangfok** [comment]
In https://github.com/RobotLocomotion/drake/issues/2369, `ros-indigo-desktop` and `ros-indigo-ros-base` are both mentioned as Debian packages to install.

Using `apt-cache showpkg [package-name]`, I see that:

(1) `ros-indigo-xacro` is included by `ros-indigo-robot`.

(2) `ros-indigo-robot` is included by `ros-indigo-desktop` and `ros-indigo-ros-base`.

Thus, I believe `xacro` should be installed on Drake's ROS CI images.

**Comment by liangfok** [comment]
In https://github.com/RobotLocomotion/drake/issues/2369#issuecomment-220453697, @jamiesnape notes that the ROS environment is configured via a driver-script in `drake-ci` since shell startup scripts are not called by Jenkins. 

Here's where the ROS environment is configured: https://github.com/RobotLocomotion/drake-ci/blob/master/ctest_driver_script_catkin.cmake#L97. It looks right since it includes the following two lines, which are necessary to find `xacro`:

```
set(ENV{ROS_PACKAGE_PATH} "/opt/ros/indigo/share:/opt/ros/indigo/stacks")
set(ENV{PYTHONPATH} "/opt/ros/indigo/lib/python2.7/dist-packages:$ENV{PYTHONPATH}")
```

Based on this, I'm beginning to suspect that `ros-indigo-xacro` is not installed on the CI image.

**Comment by liangfok** [comment]
@jamiesnape, do you know if Debian package `ros-indigo-xacro` is installed on the Drake+ROS CI images?

**Comment by jamiesnape** [comment]
@liangfok I will check.

**Comment by jamiesnape** [comment]
My notes say that we ran the following per #2369:
```
sudo apt-get install ros-indigo-ros-base ros-indigo-tf ros-indigo-ackermann-msgs 
```
I will shell into an EC2 instance and look for `xacro`.

**Comment by liangfok** [comment]
Thanks. If it is not installed, can you install it using the following command?

```
$ sudo apt-get install ros-indigo-xacro
```

**Comment by jamiesnape** [comment]
It was not installed. I updated the image.

**Comment by liangfok** [comment]
Thanks!! I will close this issue.
