### ISSUE TITLE
force and B_mod*u have different units in computeSpatialForce 

### ISSUE THREAD

**Issue by anirudhamajumdar** [RobotLocomotion/drake#362]
The interface to computeSpatialForce in RigidBodyThrust.m is a bit weird. In particular the outputs force and B_mod*u have different units even though they get added together. In particular, force is a spatial force (and I believe gets premultiplied by J^T down the chain). Russ says this might need to be fixed.

**Comment by RussTedrake** [comment]
this is much cleaner in the new c++ rigid body system design.  the matlab code will eventually leverage that.  resolving as "won't fix".
