### ISSUE TITLE
Update Jenkins Interaction Documentation to Include Scheduling Via Github Comment

### ISSUE THREAD

**Issue by liangfok** [RobotLocomotion/drake#3625]
This is the page that should be updated:

http://drake.mit.edu/jenkins.html#running-an-on-demand-build

The above-linked website only describes how CI tests can be scheduled through Jenkin's website.
In addition to this, we can also schedule tests via comments in Github that take the following form:

> @drake-jenkins-bot foo-experimental-bar please.

This issue tracks the addition of documentation about this capability.

**Comment by jamiesnape** [comment]
> To schedule a full test of Drake + ROS + MATLAB with gcc, post the following comment on your PR:
>
> @drake-jenkins-bot linux-gcc-experimental-matlab-ros please
> The results will be available here: https://drake-jenkins.csail.mit.edu/view/Experimental/job/linux-gcc-experimental-matlab-ros/.

**Comment by jamiesnape** [comment]
Just above here: http://drake.mit.edu/from_source_ros.html#running-an-example-car-simulation

**Comment by liangfok** [comment]
Sorry, I posted the wrong link. I wanted to updated 'jenkins.rst`. PTAL.

**Comment by david-german-tri** [comment]
This was done at some point: http://drake.mit.edu/jenkins.html?highlight=jenkins
