### ISSUE TITLE
Mex debugging instructions don't work (and haven't for a while)

### ISSUE THREAD

**Issue by tkoolen** [RobotLocomotion/drake#3649]
The instructions at http://drake.mit.edu/clion.html#debugging-mex-functions-in-osx broke some time ago (combination of new matlab version and new xcode version I believe). I haven't been able to figure out how to get mex debugging to work again from CLion. I opened an issue with the mathworks, but they just never bothered to fix it:

> Our development team here at MathWorks is aware of incompatibility with Xcode debugging on El Capitan and may consider fixing it for future releases of MATLAB

Should we just get rid of those instructions?

Came up in https://github.com/RobotLocomotion/drake/issues/3646.

**Comment by jwnimmer-tri** [comment]
Fixed in #7293.
