### ISSUE TITLE
Add "minimal" to pre-merge testing

### ISSUE THREAD

**Issue by jwnimmer-tri** [RobotLocomotion/drake#3663]
We should get "minimal" into the pre-merge tests.  It breaks a lot (relatively speaking), but is _super cheap_ to run.

**Comment by jwnimmer-tri** [comment]
We could consider minimal + cpplint as the front-of-pipeline build if that makes things easier, but highest priority is to get `minimal` covered somehow, lower priority to optimize build time and feedback cycle.

**Comment by david-german-tri** [comment]
Agreed.

**Comment by jwnimmer-tri** [comment]
Breaks almost every day.  Bumping up priority.

**Comment by jamiesnape** [comment]
Debug or Release, Clang or GCC?

**Comment by david-german-tri** [comment]
Maybe gcc/debug, since we already have clang/release, clang/debug, and gcc/release in other configs?

**Comment by jamiesnape** [comment]
My thoughts exactly.

**Comment by jwnimmer-tri** [comment]
Whatever you all decide is fine by me.

**Comment by jamiesnape** [comment]
Now running concurrently with cpplint on pull requests.

https://drake-jenkins.csail.mit.edu/job/experimental/compiler=gcc,label=linux_minimal,type=debug/

**Comment by david-german-tri** [comment]
Having lived with it for the past hour, I'm not actually sure running this concurrent with cpplint was a good idea.  The forced serialization is a noticeable bump in pre-merge CI latency.

**Comment by jamiesnape** [comment]
I think I agree.
