### ISSUE TITLE
bouncing ball example's use of the -inl.h pattern

### ISSUE THREAD

**Issue by RussTedrake** [RobotLocomotion/drake#3679]
@jwnimmer-tri , @jadecastro 
is it bad form to include ball-inl.h from bouncing_ball.h (not just bouncing_ball-inl.h)?

https://github.com/RobotLocomotion/drake/blob/73a65f6c7f59cb5f53f5466c6b072a6316107f72/drake/examples/bouncing_ball/bouncing_ball.h#L5

**Comment by jwnimmer-tri** [comment]
Yes, that line should be removed.

**Comment by jwnimmer-tri** [comment]
Reping @jadecastro for this quick fix.

**Comment by jadecastro** [comment]
just to be clear, 
`#include "drake/examples/bouncing_ball/ball-inl.h"` should not be removed but replaced by `#include "drake/examples/bouncing_ball/ball.h"`, yes?

**Comment by jwnimmer-tri** [comment]
Ah, yes.

**Comment by jadecastro** [comment]
I'm on it..
