### ISSUE TITLE
Race Condition Between Generated C Language LCM Message Dependencies

### ISSUE THREAD

**Issue by liangfok** [RobotLocomotion/drake#3683]
# Problem Definition

There are often dependencies between Drake's LCM messages. For example, [lcmt_qp_controller_input](https://github.com/RobotLocomotion/drake/blob/master/drake/lcmtypes/lcmt_qp_controller_input.lcm) depends on [lcmt_zmp_data](https://github.com/RobotLocomotion/drake/blob/master/drake/lcmtypes/lcmt_zmp_data.lcm). If the dependencies are not correctly specified, race conditions can occur where an LCM message is compiled before all of its dependent LCM messages are generated. An example race condition is here: 

https://drake-jenkins.csail.mit.edu/job/linux-gcc-continuous-matlab-open-source/782/console

The relevant part of the log file is copied below:

```
10:34:20 /home/ubuntu/workspace/linux-gcc-continuous-matlab-open-source/build/drake/lcmtypes/drake_lcmt_qp_controller_input.h:18:33: fatal error: drake_lcmt_zmp_data.h: No such file or directory
10:34:20  #include "drake_lcmt_zmp_data.h"
10:34:20                                  ^
10:34:20 compilation terminated.
10:34:21 make[2]: Entering directory `/home/ubuntu/workspace/linux-gcc-continuous-matlab-open-source/build/drake'
10:34:21 [  7%] Generating drake_lcmt_zmp_data.h, drake_lcmt_zmp_data.c, drake/lcmt_zmp_data.hpp, drake/lcmt_zmp_data.py, drake/lcmt_zmp_data.java
```

The above console output snippet indicates that the compiler tried to find `drake_lcmt_zmp_data.h` before it was generated. Looking in [drake-distro/drake/lcmtypes/CMakeLists.txt](https://github.com/RobotLocomotion/drake/blob/master/drake/lcmtypes/CMakeLists.txt), there is apparently code that ensures the C++ code is generated before building compiled:

https://github.com/RobotLocomotion/drake/blob/4937726eca3dd48dea702479f87c54c8031d42d1/drake/lcmtypes/CMakeLists.txt#L49

However, no such logic appears to exist for the generated C code. Maybe similar logic must be provided for the C code?

**Comment by liangfok** [comment]
@mwoehlke-kitware I'm going to assign this to you since I believe you are most familiar with how this C library is built, based on this commit: 6fcf875cc91308fa3b26549571c6c0c2eef43fe2

**Comment by mwoehlke-kitware** [comment]
After talking to @bradking, this should only affect ninja (or at least, not make); dependency scanning is *supposed* to account for it...

**Comment by liangfok** [comment]
I see. Can we add dependency scanning to `ninja`? I suppose disabling `ninja` is a non-starter?
