### ISSUE TITLE
remove bertini and gloptipoly from drake_ci and prereq instructions

### ISSUE THREAD

**Issue by RussTedrake** [RobotLocomotion/drake#3729]
following on #3727 .
in addition to removing the WITH_ args from ci, we should remove any requirements from the source installation instructions.  i believe mpich is only there due to bertini.  are there others?

**Comment by jamiesnape** [comment]
https://github.com/RobotLocomotion/drake-ci/commit/eb35f2d6d195cab0618f359c077da59650e7c5c2 cleans up CI. I will look at the prereqs documentation now. Definitely `MPICH` can go.
