### ISSUE TITLE
Is it (currently) possible to use the second argument of the Simulator constructor?

### ISSUE THREAD

**Issue by RussTedrake** [RobotLocomotion/drake#3733]
Attempting
```
  auto init = system->CreateDefaultContext();
  drake::systems::Simulator<double> simulator(*system,init);
```
results in
```
[100%] Building CXX object examples/CMakeFiles/simple_ct_example.dir/simple_ct_example.cc.o
/Users/russt/drake-distro/drake/examples/simple_ct_example.cc:70:55: error: call to implicitly-deleted copy constructor of 'std::unique_ptr<Context<double> >'
  drake::systems::Simulator<double> simulator(*system,init);
```

I also don't see it covered by any of the tests in the analysis/test/ directory.

**Comment by sherm1** [comment]
@edrumwri, can you take a look at this? Sounds like it needs a bug fix and a test case.

**Comment by david-german-tri** [comment]
I'm guessing that  `std::move(init)` in the call site will fix it.  (working-from-airport-during-nominal-vacation right now; otherwise, I'd try it myself.)  Certainly agree there should be test coverage.

**Comment by edrumwri** [comment]
Yes- will handle it.
