### ISSUE TITLE
gurobi_solver does not parse multiple quadratic costs correctly

### ISSUE THREAD

**Issue by hongkai-dai** [RobotLocomotion/drake#3736]
`gurobi_solver` cannot parse multiple quadratic costs `sum_i 0.5*x'*Q_i*x+b_i'*x` on the same variable `x`. 

@naveenoid , are you also working on this? Would you like me working on it?

**Comment by naveenoid** [comment]
Lets discuss f2f and then decide if you want to fix it instead.

**Comment by siyuanfeng-tri** [comment]
I vaguely remember this is causing #3818, not quite sure.. I can also fix it if you guys are busy with other stuff.

**Comment by hongkai-dai** [comment]
#3818 is not caused by the cost, but the constraints. The current `gurobi_solver` does not allow to impose constraints on a subset of decision variables. The multiple-costs problem is already fixed in PR #3792. I am going to close this PR.
