### ISSUE TITLE
default DoCalcNextUpdateTime() 

### ISSUE THREAD

**Issue by edrumwri** [RobotLocomotion/drake#3750]
@david-german-tri noted that the default method in System should not require re-implementation as is currently performed in "drake/systems/analysis/test/my_spring_mass_system.h". When the method is not implemented as is done specifically, the simulator test produces the following output:

Running main() from gtest_main.cc
[==========] Running 5 tests from 1 test case.
[----------] Global test environment set-up.
[----------] 5 tests from SimulatorTest
[ RUN      ] SimulatorTest.MiscAPI
[       OK ] SimulatorTest.MiscAPI (0 ms)
[ RUN      ] SimulatorTest.ContextAccess
[       OK ] SimulatorTest.ContextAccess (0 ms)
[ RUN      ] SimulatorTest.SpringMassNoSample
[       OK ] SimulatorTest.SpringMassNoSample (3 ms)
[ RUN      ] SimulatorTest.SpringMass
drake/drake/systems/analysis/test/simulator_test.cc:139: Failure
Expected: (simulator.get_num_steps_taken()) > (1000), actual: 1000 vs 1000
drake/drake/systems/analysis/test/simulator_test.cc:140: Failure
      Expected: simulator.get_num_updates()
      Which is: 0
To be equal to: 30
drake/drake/systems/analysis/test/simulator_test.cc:146: Failure
      Expected: spring_mass.get_update_count()
      Which is: 0
To be equal to: 30
[  FAILED  ] SimulatorTest.SpringMass (3 ms)
[ RUN      ] SimulatorTest.ControlledSpringMass
[       OK ] SimulatorTest.ControlledSpringMass (45 ms)
[----------] 5 tests from SimulatorTest (51 ms total)

[----------] Global test environment tear-down
[==========] 5 tests from 1 test case ran. (51 ms total)
[  PASSED  ] 4 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] SimulatorTest.SpringMass

 1 FAILED TEST

**Comment by david-german-tri** [comment]
This behavior now exists in LeafSystem (and has been subject to a fair amount of scrutiny over floating-point accuracy).  I'll look at switching it over.
