### ISSUE TITLE
Improve syntactic sugar for continuous state allocation

### ISSUE THREAD

**Issue by david-german-tri** [RobotLocomotion/drake#3751]
Requests from @RussTedrake on #3735:

- [ ] Provide a more concise way to access the continuous state variables as a vector

- [ ] Provide a default implementation of `LeafSystem<T>::AllocateContinuousState` that reserves a vector of `z` of a declared size.

- [ ] Rename `ContinuouousState<T>::get_state` to `get_vector`

**Comment by RussTedrake** [comment]
yes, exactly.  thanks!

**Comment by RussTedrake** [comment]
also overload operator[] so that we can have, e.g.
```
initial_conditions->get_mutable_continuous_state()[0] = 0.9;
````
or
```
initial_conditions->get_mutable_continuous_state(0) = 0.9;
```
