### ISSUE TITLE
Flip PidControlledSystem's Equations

### ISSUE THREAD

**Issue by liangfok** [RobotLocomotion/drake#3761]
As mentioned [here](https://reviewable.io/reviews/RobotLocomotion/drake/3742#-KTjSASk1OOTM-QXkHkW), `PidControlledSystem` currently implements:

```
u = -k * (x_actual - x_desired)
```

For increased readability and to eliminate the need for negation systems, let's modify it to be:

```
u = k * (x_desired - x_actual)
```

`PidControlledSystem` inherited its equations from `KukaDemo` here: https://github.com/RobotLocomotion/drake/blob/96090268a98d317e2725b3894be6a7cd0e530a43/drake/examples/kuka_iiwa_arm/controlled_kuka/kuka_demo.cc#L186

**Comment by naveenoid** [comment]
I agree!

**Comment by jwnimmer-tri** [comment]
Can fix later if / when we care.
