### ISSUE TITLE
There should always be state objects, even if they're empty.

### ISSUE THREAD

**Issue by david-german-tri** [RobotLocomotion/drake#3765]
Right now, we have a bunch of nullptr checks on System2 state that aren't really necessary; if we were guaranteed an empty state vector, the behavior they check would gracefully no-op.  For one example, see discussion on #3695.

**Comment by edrumwri** [comment]
This also would seem to fix the issue where I had to create a discrete state vector for simulator_test.cc (Lines 116-119) in order to do discrete updates for systems with zero-dimensional discrete states.
