### ISSUE TITLE
Trajectory Optimization/Dynamics with contacts

### ISSUE THREAD

**Issue by aespielberg** [RobotLocomotion/drake#3811]
Hi all,

I have found the CompassGaitWalker runDircol cycle example helpful for how to construct a Hybrid Trajectory Optimization problem.  However, in this case, the contact dynamics are explicitly written out for the compass gait walker.

Let's say I want to work with a generic robot, loaded from urdf.  In this case, I can rewrite the manipulator equations including the contact constraint force (as in A.2.3 [here](http://underactuated.csail.mit.edu/underactuated.html?chapter=23)).

I am wondering if there is any existing infrastructure in Drake to compute the J matrix, and add the lambda vector to the state of a problem, or some other way to incorporate contact dynamics directly into the problem, or if this is something I will have to do manually (let us say I don't wish to use the contact implicit method).

**Comment by mposa** [comment]
Hi Andrew,
As far as I know, mainstream Drake has no such functionality. On one of my development branches, I do have some code that will run a hybrid trajectory optimization, which explicitly considers contact points as constraints (a mode is defined by a set of points which must remain stationary). The code is very much experimental, but I'd be happy to chat more about it. Here's a link to an example, on one of my branches:

https://github.com/mposa/drake/blob/hybrid-merge/drake/examples/KneedCompassGait/dev/accelopenLoopTrajOptTest.m

The relevant paper is 
http://groups.csail.mit.edu/robotics-center/public_papers/Posa15.pdf
