### ISSUE TITLE
HybridTrajectoryOptimization with ContactImplicitTrajectoryOptimization

### ISSUE THREAD

**Issue by aespielberg** [RobotLocomotion/drake#3812]
Hello,

Have there been any tests using HybridTrajectoryOptimization with ContactImplicitTrajectoryOptimization as the direct optimizer?

**Comment by mposa** [comment]
No, and I would be surprised if it works out of the box. I commented on your other, related issue as well.

**Comment by aespielberg** [comment]
Okay, this confirms my experience.  Thanks!
