### ISSUE TITLE
Skip Python and MATLAB during Valgrind builds

### ISSUE THREAD

**Issue by jamiesnape** [RobotLocomotion/drake#3842]
Get CI working, allow developers to reproduce using ctest, document.

**Comment by jamiesnape** [comment]
FYI @david-german-tri.

**Comment by jamiesnape** [comment]
Need `--trace-children=yes --trace-children-skip=${comma_separated_list}`.

**Comment by david-german-tri** [comment]
@jamiesnape This is done, right?

**Comment by jamiesnape** [comment]
Yes.
