### ISSUE TITLE
fastqp_solver_test is testing snopt

### ISSUE THREAD

**Issue by hongkai-dai** [RobotLocomotion/drake#3855]
@RussTedrake , when I run `fastqp_solver_test.cc`, it actually runs SNOPT solver, at line 59
``` 
result = prog.Solve();  // TODO(russt) call fastQP solver
                              // explicitly
```
Could  you elaborate why we do not have a `FastqpSolver` class as `SnoptSolver`, and explicitly call fastqp solver?

**Comment by RussTedrake** [comment]
Because i want it to call gurobi when that is present!  :)

**Comment by hongkai-dai** [comment]
Excellent! I am turning on gurobi solver for this test. 

But it does not run fastqp currently, instead it runs SNOPT, at least when I tested it on my local machine. Since there is not a branch to run fastqp in `MathematicalProgram::Solve`.

**Comment by RussTedrake** [comment]
Correct. That's still todo. And also depends on being able to extract the
active set information after the solve.
