### ISSUE TITLE
Factor out a `KukaIiwaPlant` from `KukaIiwaArmDynamicsSim` and `kuka_demo.cc`

### ISSUE THREAD

**Issue by liangfok** [RobotLocomotion/drake#3865]
This is to avoid code duplication.

For context, see: https://github.com/RobotLocomotion/drake/pull/3745#issuecomment-255381050

**Comment by sammy-tri** [comment]
I've got a 3rd (at least?) version of the mostly-duplicated code in one of my branches too.  Not sure how close I am to a PR, but I'll avoid worrying about de-duplicating locally if you're working on a generic version already.

**Comment by liangfok** [comment]
Yes, please go ahead and proceed with your 3rd duplicate. We'll factor out a `KukaIiwaPlant` from all three once we get around to addressing this issue.

**Comment by sammy-tri** [comment]
Reassigning to @naveenoid since I think #4521 may accomplish most/all of this.

**Comment by naveenoid** [comment]
Since #4521 has landed the only thing needed is to get KukaIiwaArmDynamicsSim to use the plant model. I will submit a fix PR ASAP.

**Comment by naveenoid** [comment]
Closing this issue in light of the creation of drake/manipulation.
