### ISSUE TITLE
Systems/Observers need porting over to Sys2.0 C++

### ISSUE THREAD

**Issue by naveenoid** [RobotLocomotion/drake#3867]
This is to start discussions on how to effectively port over the observers into Sys2.0 C++. I would like to take a crack at the LuenbergerObserver.m first especially given that Affine/LinearSystem has nearly landed. If any one else has ideas please note here.

**Comment by hongkai-dai** [comment]
LuenbergerObserver sounds a great start. What is the example you have in mind?

**Comment by naveenoid** [comment]
I did not have any clear example in mind except for sample problems in linear observer design. Any recommendations? I personally want to work towards KF/EKF..I figured this would be a perfect first step.

**Comment by jwnimmer-tri** [comment]
https://github.com/RobotLocomotion/drake/tree/master/drake/systems/estimators already has lots.  Update the issue with next steps, or close it?

**Comment by RussTedrake** [comment]
i think it's safe to close.
