### ISSUE TITLE
kuka_demo test doesn't assert anything

### ISSUE THREAD

**Issue by david-german-tri** [RobotLocomotion/drake#3869]
This makes it difficult to tell, after updating it for API changes, whether it still has the correct behavior.

**Comment by Lucy-tri** [comment]
I think this got renamed to controlled_kuka_demo.cc

**Comment by hongkai-dai** [comment]
@sammy-tri is this issue still active?

**Comment by sammy-tri** [comment]
Yes, in the sense that `examples/kuka_iiwa_arm/controlled_kuka/controlled_kuka_multibody_demo.cc`  still doesn't assert anything beyond the fact that the simulation executes at all.  I'm probably not going to change that anytime soon, we could close the issue if we decide it's not a problem.

**Comment by hongkai-dai** [comment]
Close this issue for now, as we will rewrite kuka examples.
