### ISSUE TITLE
Provide valgrind pre-merge build, developer tooling, and documentation

### ISSUE THREAD

**Issue by david-german-tri** [RobotLocomotion/drake#3873]
This checklist will evolve as I figure out what needs to be done.
- [x] Prevent valgrind from traversing MATLAB and Python.
  - [x] In CI. Done https://github.com/RobotLocomotion/drake-ci/commit/45a2d99e7b0c79088d75992d66e45839d8ec9de7 et. seq.
  - [x] In local builds
- [x] Fix the existing memcheck errors (see the [nightly build](https://drake-jenkins.csail.mit.edu/view/Nightly/job/linux-clang-nightly-memcheck-valgrind/))
  - [x] Set the environment variable `GTEST_DEATH_TEST_USE_FORK` for the memcheck build.
    - [x] In CI.  Done https://github.com/RobotLocomotion/drake-ci/commit/3858255566838905669be7980304dc2239ea6748
    - [x] In local builds.
- [x] Audit drake/valgrind.supp for spurious suppressions
  -  ~Use a common suppressions file for Bazel and CMake (cmake will disappear)~
- [x] Make the memcheck build yellow in Jenkins if there are defects.
- [x] Document how developers should invoke the memcheck build locally.
  - [x] Prevent ctest from generating `-q`
- [ ] Promote the valgrind build to Continuous and monitored
- [ ] Get the valgrind build to run in less than 30 minutes by excluding big tests.
- [ ] Promote the valgrind build to pre-merge

**Comment by jamiesnape** [comment]
> Prevent ctest from generating --log-file
Not possible as far as I am aware. CTest needs to be able to parse it.

**Comment by david-german-tri** [comment]
It looks like as long as `-q` is absent, `--log-file` is not a problem.  Updated the checklist accordingly.

**Comment by jamiesnape** [comment]
For developers, what do you want me to do about compiler flags? We basically run `-g -O1 -fno-omit-frame-pointer` on CI. I can add a CMake option that set the flags, simply document the flags, or allow developers to make their own decisions on flags and interpreting the output accordingly.

**Comment by jamiesnape** [comment]
`-O1` is not entirely necessary, of course, but it makes things more bearable.

**Comment by david-german-tri** [comment]
I think an option is the way to go, where the default matches CI.

**Comment by david-german-tri** [comment]
I'm thinking we will need to exclude some tests from memcheck (notably, those that invoke optimizers) because they're just too slow.  Is there a recommended phrasing for that in CMake?

**Comment by jwnimmer-tri** [comment]
If you get the test `SIZE` set appropriately, it will automatically be run either pre-merge and/or continuous and/or nightly (and/or useful for developers who want to filter-by-size as well).

**Comment by jamiesnape** [comment]
@david-german-tri Assuming that there are in `enormous` range for sizing, for the moment, add `NO_MEMCHECK` to the end of the `drake_add_*_test` calls. It will be ignored for now, but I can add something as I am fixing up the compiler flags for developers.

**Comment by david-german-tri** [comment]
It looks like the memcheck build reports success in Jenkins once all the tests are passing, even if there are memory defects:

https://drake-cdash.csail.mit.edu/index.php?project=Drake&showfilters=1&filtercount=2&showfilters=1&filtercombine=and&field1=label&compare1=61&value1=jenkins-linux-clang-nightly-memcheck-valgrind-270&field2=buildstarttime&compare2=84&value2=now

vs 

https://drake-jenkins.csail.mit.edu/view/Nightly/job/linux-clang-nightly-memcheck-valgrind/270/

Adding to checklist in OP.

**Comment by jamiesnape** [comment]
Yes, that was deliberate.

**Comment by david-german-tri** [comment]
> Yes, that was deliberate.

Why?  Seems like the opposite of what we want.

**Comment by jamiesnape** [comment]
It is now, but as there was no move to fix any of the defects it was just noise.

**Comment by jamiesnape** [comment]
Actually, I take that back, we are suppressing coverage errors, not memcheck. I will look into it.

**Comment by jamiesnape** [comment]
(don't fix that detect for now)

**Comment by jamiesnape** [comment]
Apparently `valgrind` passes down the return value of the program that it is simulating unless you pass it an option, and `ctest` is respecting that value. @BetsyMcPhail is looking at a fix.

**Comment by david-german-tri** [comment]
https://github.com/RobotLocomotion/drake-ci/pull/45

**Comment by david-german-tri** [comment]
#3920 checked off a number of boxes here.

**Comment by stonier** [comment]
Right now the valgrind jobs are up and running well, with only the exception that they haven't been moved to Continuous (i.e. PR hooks). With budget constraints we're going to leave them in Nightly and monitor how often they pick up problems. If it turns out to be frequent, then we'll review the decision.

FYI @jwnimmer-tri

**Comment by jwnimmer-tri** [comment]
SGTM.  If Nightly breaks too often, we could `--config fastmemcheck` (instead of `--config memcheck`) atop an existing Release-mode pre-merge build, which I think would be pretty cheap.

(I'm totally happy to keep it Nightly for now though, as you say.)
