### ISSUE TITLE
Consider Making BasicVector Overload `operator<<(string)`.

### ISSUE THREAD

**Issue by liangfok** [RobotLocomotion/drake#3884]
I currently need to do:

```
std::cout << my_basic_vector.get_value() << std::endl;
```

I would be nice if could do:

```
std::cout << my_basic_vector << std::endl;
```

...by overloading [this method](http://www.cplusplus.com/reference/string/string/operator%3C%3C/).

**Comment by david-german-tri** [comment]
Feel free to do that.  I'm happy to review.

**Comment by david-german-tri** [comment]
However, note that this won't be useful with spdlog, which in general you should prefer to cout.
