### ISSUE TITLE
Move deprecated System 1.0 infrastructure to drake/system1

### ISSUE THREAD

**Issue by jwnimmer-tri** [RobotLocomotion/drake#3901]
We should physically separate deprecated System 1.0 infrastructure, both so that the new world is cleaner, and so that we can trivially identify in-tree code that's using deprecated APIs (e.g., `rgrep system1/`).

I have a branch ready at https://github.com/jwnimmer-tri/drake/tree/build-system1 with this change, and will PR once #3861 lands.

**Comment by RussTedrake** [comment]
why not just zap it?  I think someone told me that “git remembers”.  anybody still using it?

**Comment by david-german-tri** [comment]
#3902 suggests there are a dozen or so usages remaining.

**Comment by jwnimmer-tri** [comment]
Right.  If I have permission to remove Atlas, Kuka, Pendulum, Automotive-MultiCar, Trajectory Optimization, and IK from the tree, I'm happy to nix System 1.0.  Otherwise, we now have a nice greppable burn-down list of items to port.
