### ISSUE TITLE
Create a "IIWA World" Grasping Demo

### ISSUE THREAD

**Issue by liangfok** [RobotLocomotion/drake#3910]
# Problem Definition
The current IIWA simulation does not include objects or a demo including the manipulation of objects. Building in this functionality will also be a useful exercise to drive the state-of-the-art in all aspects of Drake's simulation ability.  This task will be organised in a set of spirals similar to PR https://github.com/RobotLocomotion/drake/issues/3919 

# Spirals
- [x] Spiral 1
- [x] Spiral 2
- [x] Spiral 3

# Spiral Details
## Spiral 1 - Uncontrolled IIWA + Objects
An uncontrolled IIWA mounted on the table is loaded along with a couple of demo objects.  

## Spiral 2 - Controlled IIWA and Gripper + Objects
A controlled Kuka IIWA with a gripper on the end deliberately moves to a desired position (under position control) and makes contact with one of the objects; perhaps knocks the object over. 

## Spiral 3 - Controlled IIWA and Gripper + Grasping objects
A controlled Kuka IIWA with a gripper deliberately moves to grasp an object on the table. From prior knowledge of positions of objects and their shapes, the manipulator and gripper trajectories are computed accordingly.

**Comment by naveenoid** [comment]
I can also take a pass at this if you guys are immediately occupied.

**Comment by liangfok** [comment]
Great! I'm working on something else at the moment and will add you to the assignees list.

**Comment by sammy-tri** [comment]
@naveenoid If you could take on getting the initial world put together with the iiwa, the gripper, and an object all in the demo (even if nothing moves on a commanded trajectory), that would be great!

**Comment by sherm1** [comment]
Please let @SeanCurtis-TRI know if the current contact code isn't getting the job done!

**Comment by liangfok** [comment]
@naveenoid, once you get started, please point us to your WIP branch. Let's try to make this a "micro sprint" where multiple developers cooperate to speed up the creation of the initial PR.

**Comment by naveenoid** [comment]
Awesome..Will do!

**Comment by naveenoid** [comment]
Updated the issue in anticipation of my first PR (coming soon). Comments welcome!

**Comment by sammy-tri** [comment]
Current edited version looks pretty much right to me.  We'll need to figure out if/how we want to split up the work once we get to spiral 2.  Looking forward to the PR!

**Comment by naveenoid** [comment]
Final spiral addressed by #5321

**Comment by naveenoid** [comment]
This issue is reopened to track the PR train for the monolithic version of the grasping demo.
