### ISSUE TITLE
Time Varying Affine/Linear Systems

### ISSUE THREAD

**Issue by naveenoid** [RobotLocomotion/drake#3913]
There is a need to build upon #3828 to support time varying Affine/Linear systems. I am not sure how we can enable this functionality with System2.0.

**Comment by liangfok** [comment]
Two ideas I've heard so far:

1. provide the time-varying matrices and vectors through input ports.
2. provide a function as an input parameter that supplies the time varying matrix and vector values.

**Comment by RussTedrake** [comment]
i was going to take a pass at this (to implement tvlqr) probably this weekend.
