### ISSUE TITLE
Generalize AutomotiveSimulator To Support Multi-Body Vehicles

### ISSUE THREAD

**Issue by liangfok** [RobotLocomotion/drake#3919]
# Problem Definition

[AutomotiveSimulator](https://github.com/RobotLocomotion/drake/blob/96090268a98d317e2725b3894be6a7cd0e530a43/drake/automotive/automotive_simulator.h) only supports "box" vehicles, i.e., vehicles that consist of a single rigid body. For simulation and visualization purposes, we want to be able to load and visualize complex multi-body vehicles that look like actual vehicles.
# Spirals
- [x] Spiral 1
- [ ] Spiral 2
- [ ] Spiral 3
- [ ] Spiral 4
- [ ] Spiral 5
# Spiral Details
## Spiral 1 - RPY Floating Joint + Zero Position Single-DOF Joints

This spiral assumes all floating joints are of type `kRollPitchYaw` and all other joints are single-DOF and at their zero positions.
- **Visible feature goal:** Prius with static wheels.
- **Related pull requests:** #3933, #3959 

## Spiral 2 - RPY Floating Joint + Non-Zero Position Single-DOF Joints.

This spiral builds upon spiral 1 by  allowing the rest of the joints to be in non-zero positions. It continues to assume all floating joints are of type `kRollPitchYaw`.
- **Visible feature goal:** Prius with moving and steering wheels.

## Spiral 3 - Quaterion Floating Joint + Non-Zero Position Single-DOF Joints

This spiral builds upon spiral 2 by supporting quaternion floating joints. This is tricky since quaternion floating joints have differing numbers of positions and velocities.
- **Visible feature goal:** Prius with moving and steering wheels. Plus quad-copter drone hovering around Prius. Both Prius and drone are connected to world via quaternion floating joints. Both models move in ways that would cause gimbal lock in RPY floating joints.

## Spiral 4 - Quaterion Floating Joint + Non-Zero Position Multi-DOF Joints

This spiral builds upon spiral 3 by supporting non-zero positions of all joints including non-floating joints.

- **Visible feature goal:** Semi-trailer 18-wheeler truck with steerable wheels and articulated trailer. The trailer is connected to the truck via a ball joint (3 rotational DOFs). The tractor is connected to the world via a quaternion floating joint. The truck moves over rough terrain demonstrating the 3-DOF nature of the joint between the tractor and its trailer.
## Spiral 5 - Stress Test Various Mesh and Texture Formats

Here we verify that the system supports the most popular mesh and material description formats including `.obj`, `.dae`, etc.
- **Visible feature goal:** Semi-trailer 18-wheeler truck with steerable wheels and articulated trailer, and a logo on the side of the trailer.

**Comment by maddog-tri** [comment]
I suggest augmenting the "Spiral N" goals to give them visible feature goals, too --- e.g., "Prius with static wheels" for Spiral 1, "Prius with steerable wheels" for Spiral 2.  (Maybe 3 becomes RPY+multi-DOF joints, with "Semi-trailer truck with steerable wheels and articulated trailer"?)

**Comment by liangfok** [comment]
@maddog-tri, great idea. I updated the original post with visible feature goals. PTAL.

**Comment by jwnimmer-tri** [comment]
I am hesitant to do some of the later spirals until we have GeometryWorld up and running.  The bespoke glue code to work around it is not worth too much investment.  We can accept glue code for demos we _need_, such as multi-car automotive demos, but we shouldn't add quadcopters and such until we have GeometryWorld.

**Comment by liangfok** [comment]
OK SGTM. Is there a PR #, issue #, or some other documentation I can reference to learn more about the aforementioned `GeometryWorld`?

**Comment by jwnimmer-tri** [comment]
I refer to you @david-german-tri who can help coordinate locally and/or refer you to the dynamics team.

**Comment by sherm1** [comment]
Pinging @SeanCurtis-TRI for `GeometryWorld` commentary. My 2 cents: I would rather call this `SharedEnvironment` since it will ultimately include much more than geometry.

**Comment by jwnimmer-tri** [comment]
@liangfok I'm not sure that this issue as currently phrased is helping much.  Is there any work here remaining that's worth capturing before we close this?

**Comment by liangfok** [comment]
I would like to wait for the switch to `PoseAggregator` before continuing work on this issue. I do think it's desirable to eventually support visualization of the wheels spinning, front wheels steering, suspension movements, etc., though not in the near term. I shall thus decrease the priority of this issue for now.

**Comment by jwnimmer-tri** [comment]
Ah, okay.  From the original post, I didn't realize that the goal was to map SimpleCar-like dynamics into improved visualizations by adjusting more of the links during the visualization step.

**Comment by jwnimmer-tri** [comment]
Closing as WONTFIX.
