### ISSUE TITLE
Replace Gain with MimoGain

### ISSUE THREAD

**Issue by liangfok** [RobotLocomotion/drake#3922]
`MimoGain` is a generalization of `Gain` and thus should replace `Gain` under one condition:

_`MimoGain` must provide a constructor that makes it look and behave like `Gain`._

This is a follow up of #3917.

**Comment by naveenoid** [comment]
As stated on slack..I would also rename MimoGain to Gain after building it suitably. Followup PR perhaps?

**Comment by liangfok** [comment]
Yes, I think MimoGain should go in first, then we combine the two in a future PR.

**Comment by liangfok** [comment]
I'll close this issue because it was pointed out to me that it may be useful to keep the two systems (`Gain` and `MatrixGain`) separate.

http://www-rohan.sdsu.edu/doc/matlab/toolbox/simulink/slref/gain.html
