### ISSUE TITLE
Alert/fail if the number of tests drops precipitously.

### ISSUE THREAD

**Issue by david-german-tri** [RobotLocomotion/drake#3923]

**Comment by EricCousineau-TRI** [comment]
Is this still relevant / useful? If not, can we close it out?

**Comment by jamiesnape** [comment]
I guess it would be useful, but whether it is really worth the time, is another question.

**Comment by EricCousineau-TRI** [comment]
Done. Lowered the priority for now.

**Comment by jwnimmer-tri** [comment]
Doesn't seem to be pain point / big risk anymore.
