### ISSUE TITLE
Drake fails to build on OSX if inside a folder with parenthesis (example ~/Dropbox (Personal)/drake-distro

### ISSUE THREAD

**Issue by enriquefernandez** [RobotLocomotion/drake#394]
My drake-distro was installed in:

~/Dropbox (Personal)/Courses/Underactuated/drake-distro

When executing:

`make`

it looks like things build properly until it gets to the MATLAB compilation of drake.
The compilation of the first item fails and reports:
bash: syntax error near unexpected token `('

This happens because the classpath passed to java is not escaped correctly.
Apparently, when you use '(' in bash, you need to enclose the path with " or ', but that's not what the compilation is doing and therefore it fails.

Note that Dropbox folders with parenthesis in it are common if you have also enterprise Dropbox accounts (such as the MIT ones we get now).

Installation worked properly, once I moved the drake-distro to a folder with no parenthesis in it.

If this can't be fixed, I suggest that it's at least mentioned in the installation instructions.

**Comment by david-german-tri** [comment]
I'm going to close this due to low importance and years of inactivity.
