### ISSUE TITLE
Mysterious warning: could not create compact unwind ...

### ISSUE THREAD

**Issue by liangfok** [RobotLocomotion/drake#3953]
Here is the warning on my OS X 10.11.6 system:

```
[14/128] Linking CXX shared library lib/libdrakeOptimization.dylib
ld: warning: could not create compact unwind for ___dmumps_parallel_analysis_MOD_dmumps_715: stack subq instruction is too different from dwarf stack size
```

I started to see this today, though I'm not sure if I simply didn't notice prior to today.

**Comment by david-german-tri** [comment]
so, IPOPT depends on MUMPS, and MUMPS has some code for which the OS X linker can't create a compact unwind (I'm not going to try to figure out why not).  We could maybe pass `-Wl,-no_compact_unwind` to clang, but I actually suspect it's better to have compact unwinding, and this one warning, than to have DWARF unwinding and no warning.  Closing as wontfix.
