### ISSUE TITLE
Update PidControlledSpringMassSystem To Use New Feedback Selector API

### ISSUE THREAD

**Issue by liangfok** [RobotLocomotion/drake#3966]
This should be done once #3947 is merged.

Update this file: drake-distro/drake/systems/analysis/test/controlled_spring_mass_system/controlled_spring_mass_system.cc

It currently wires up a PID controller using primitive systems. Replace with this with `PidControlledSystem`.

**Comment by jwnimmer-tri** [comment]
Fixed in b63975cb6f3f3dc2d0296668a592903af36949e9 a long time ago.
