### ISSUE TITLE
Purge System 1.0 from Acrobot, Pendulum, Quadrotor

### ISSUE THREAD

**Issue by jwnimmer-tri** [RobotLocomotion/drake#3975]
Subtask of #3960.  Purge System 1.0 code from examples/Acrobot, examples/Pendulum, examples/Quadrotor.

If the resolution is to port to System 2.0 instead of deleting them, note that this includes creating a System 2.0-based LQR controller.

**Comment by RussTedrake** [comment]
Pendulum and Acrobot are done.  Quadrotor still has a little purging to do.

**Comment by jwnimmer-tri** [comment]
@RussTedrake Any timeline on Quadrotor purging / porting?  I can just `rm` and "git remembers" if we want (possibly with a README with the last sha or something)?

**Comment by jwnimmer-tri** [comment]
Ah.  Is this just a duplicate of #3994 now?
