### ISSUE TITLE
 Purge System 1.0 from ROS integration

### ISSUE THREAD

**Issue by jwnimmer-tri** [RobotLocomotion/drake#3979]
Subtask of #3960. Purge System 1.0 code from drake-distro/ros.

This is mostly independent of #3978, since this code really only depends on RBS.

To be clear: deleting code that depends on System 1.0 is a valid solution.

**Comment by jwnimmer-tri** [comment]
@liangfok It seems like with the HSR ROS demos coming online, that's a good example of System 2.0 use within ROS.  What's a smart plan for removing System 1.0 support from ROS demos?  Do we need to port any more code, or can we just remove anything that depends on System 1.0?

**Comment by liangfok** [comment]
I will purge all remaining System 1.0 code and rely on Git history for reference as I port the System 1.0 code to System 2.0. A PR for this will be coming soon.
