### ISSUE TITLE
rename SystemPortDescriptor.get_size() to size()?

### ISSUE THREAD

**Issue by RussTedrake** [RobotLocomotion/drake#3998]
most other objects have the size() method

**Comment by david-german-tri** [comment]
I think there is a distinction here - the objects with `.size()` have storage, so the name is analogous to `std::vector::size`.  `SystemPortDescriptor`, in contrast, describes a thing with storage.

I don't feel strongly about it though, and am happy to make the change.

**Comment by RussTedrake** [comment]
agreed that there is a distinction, but get_size() doesn't convey any more information (but requires me or my editor to remember the difference)?  if nobody objects, my vote would be to change it?

**Comment by david-german-tri** [comment]
This was fixed in #4602.
