### ISSUE TITLE
valkyrie_balancing_system_test does not compile and valkyrie_balancing_test exceeds timeout

### ISSUE THREAD

**Issue by jamiesnape** [RobotLocomotion/drake#4000]
Two bugs in play here. One is fixed by #3996 (`snopt_c_FOUND` was not defined), but it exposes a second:
```
error: object of type 'drake::examples::qp_inverse_dynamics::HumanoidStatus' cannot be assigned because its copy assignment operator is implicitly deleted
```

https://drake-cdash.csail.mit.edu/viewBuildError.php?onlydeltap&buildid=171160

Also, `valkyrie_balancing_test` exceeds the timeout in debug mode.

**Comment by david-german-tri** [comment]
Why doesn't this show up in CI?

**Comment by jamiesnape** [comment]
#3996

**Comment by jamiesnape** [comment]
snopt_c_FOUND was not defined. That test has never run.

**Comment by david-german-tri** [comment]
@jamiesnape is disabling both `valkyrie_balancing_test` and `valkyrie_balancing_system_test` in #3996 for now.

**Comment by siyuanfeng-tri** [comment]
I believe they are fixed in https://github.com/RobotLocomotion/drake/pull/3907, waiting for review to finish.. 
I apologize for the delay.
