### ISSUE TITLE
AutoDiffScalar needs isnan() and isinf() overloads

### ISSUE THREAD

**Issue by edrumwri** [RobotLocomotion/drake#4005]
This is necessary for adjusting step sizes in the context of variable step integration.

**Comment by david-german-tri** [comment]
Seems reasonable.  It should be pretty trivial to add this in https://github.com/RobotLocomotion/drake/blob/master/drake/math/autodiff_overloads.h mimicking the existing code.  Any particular reason for assigning it to me?

**Comment by edrumwri** [comment]
I was told that you had written the other code in autodiff_overloads.h, so I figured you "owned" the file. I'm happy enough to write it myself if you prefer.

**Comment by david-german-tri** [comment]
> I was told that you had written the other code in autodiff_overloads.h, so I figured you "owned" the file. I'm happy enough to write it myself if you prefer.

Some of it came from RLG, some from me.  If you need it on a particular timetable, probably best that you write it yourself.

**Comment by edrumwri** [comment]
Addressed by pull request #4008
