### ISSUE TITLE
Remove TaylorVarXd

### ISSUE THREAD

**Issue by david-german-tri** [RobotLocomotion/drake#4013]
It's redundant with AutoDiffXd.  Per @RussTedrake on #3967.

**Comment by jwnimmer-tri** [comment]
@RussTedrake Should _all_ of the  `TaylorVar...` names change to `AutoDiff...` names?  Is there any mnemonic difference between TaylorVar and AutoDiff?

**Comment by RussTedrake** [comment]
all names can change.  there is no difference.  The two names exist simply because @tkoolen and I wrote things in parallel.  (TaylorVar was my choice to match matlab, which is obviously much relevant now).  This concession means that @tkoolen has won. :)
