### ISSUE TITLE
Allow weld_to_frame to Specify both name and body if both are World

### ISSUE THREAD

**Issue by liangfok** [RobotLocomotion/drake#4067]
Currently, in `parser_common.cc`, method `AddFloatingJoint()` will throw an exception if the user specifies both body name "world" and a pointer to the rigid body that represents the world. Update the logic to account for this situation and not throw an exception.

**Comment by amcastro-tri** [comment]
MBP allows to programmatically add a weld joint between two arbitrary bodies in the model,  one of which can also be world.
