### ISSUE TITLE
Generalize URDF parser to Allow Dual Offset (world link and weld_to_frame)

### ISSUE THREAD

**Issue by liangfok** [RobotLocomotion/drake#4069]
The SDF parser was already generalized to support dual offset (actual world to model world + additional offset specified in parameter `weld_to_frame`):

Issue: https://github.com/RobotLocomotion/drake/issues/2003
PR: https://github.com/RobotLocomotion/drake/pull/2053

We should do the same with the URDF parser.

**Comment by naveenoid** [comment]
marked as high priority : This is essential in working with the KUKA IIWA urdf towards building simulations fixing it in arbitrary poses..
