### ISSUE TITLE
Rigid-Body Force Element needs port to System2.0

### ISSUE THREAD

**Issue by foehnph** [RobotLocomotion/drake#4076]
This issue is to discuss the design of a RigidBodyForceElement. One possibility is a Leafsystem which has as input the state of the RigidBodyPlant `q` and the control input `u` and it should generate an output `B(q)*u`.

This leaf system can then be combined in the Diagram with the source RBS.

This leaf system should be generated from parsing the URDF/SDF with the logic sitting inside parser_urdf.h/parser_sdf.h

(tagging @naveenoid )

**Comment by naveenoid** [comment]
Tagging : @liangfok and @david-german-tri 

The first implementation can be tested with the Quadrotor examples. I can work with @foehnph in resolving this once you guys have design feedback.

**Comment by liangfok** [comment]
>One possibility is a Leafsystem which has as input the state of the RigidBodySystem x and the control input u and it should generate an output B(q)*u.

Instead of "RigidBodySytsem" I believe you mean "RigidBodyPlant".

In the above statement, what are variables `B` and `u`?

**Comment by foehnph** [comment]
Thanks for the correction.
`u` is the input to the system and `B(q)` maps this input back into full general coordinates for the plant.
Therefore `u`,`q` could be the inputs to a LeafSystem which generate `B(q)*u` as an output.
This output can then be connected to the input of a RigidBodyPlant.

**Comment by liangfok** [comment]
Just to be clear, is the input, `u`, a vector of force/torque values that specify the force/torque the `RigidBodyForceElement` is asserting on bodies within the `RigidBodyPlant`?

**Comment by sherm1** [comment]
@amcastro-tri, do you any thoughts about how this should be done?

**Comment by amcastro-tri** [comment]
I was talking about this over to lunch with @RussTedrake today. For the case of the quadrotor we would a `DragForceSystem` (probably inheriting from a `ForceSystem`?) that applies the appropriate external force on a given rigid body given its velocity (state) and orientation. Also I guess for the quadrotor you would need something like an `ConstantForceSystem`? for the propellers. 

For something like that I think the input to these force systems could directly be the kinematics of the particular rigid body the force is applied to. In that way `RigidBodyPlant` is responsible for computing this kinematics information and can use caching to do it efficiently. Also the output to the `ForceSystem` could directly be the applied wrench on the body. For that we would probably need to implement input ports on `RigidBodyPlant` for external wrenches. The computation of generalized forces is then done by `RigidBodyPlant` in one place and therefore computations are reused (imagine you could have several `ForceSystem`'s and it would be inefficient having each of those computing the generalized forces for the RBP). 
I am just brainstorming here, thoughts?

**Comment by sherm1** [comment]
I like that idea, @amcastro-tri. The complete force interface to RBPlant should be (1) generalized forces applied to particular dofs (mobilities) and (2) a collection of spatial forces (torque, force) applied at specified points on specified rigid bodies. That way RBTree can do all the messy calculations, and can correctly calculate reaction forces that result from those spatial forces, which it can't do if they are converted first to generalized forces.

**Comment by naveenoid** [comment]
I mostly agree with your plan @amcastro-tri but what about stuff like actuator dynamics etc? I guess we need to then build a custom "source" system which needs to obtain its parameters from urdf / sdf and converts actuation input (currents / voltages / direct positions?) into spatial forces mapping into the corresponding actuator ports. 

Any idea when you might work on this? Or can a part of this task be shared? What would be the best design for RBP? in construction, the URDF needs to be parsed to open sufficient input ports right?

**Comment by amcastro-tri** [comment]
Not a plan yet, I was just openly brainstorming to get the feedback from everybody interested on this. 
I think we should start simple and what the things we need first. Correct me if I am wrong but it seems like the immediate need for the quadrotor example are force systems to model drag and thrust forces.

When you say actuator dynamics you mean for instance modelling a DC motor? in any case, I think we should tackle first the problems we have a direct application/need for, in this case constant forces and drag.

**Comment by siyuanfeng-tri** [comment]
For actuator dynamics, I believe @tkoolen's plan is to compute all the messy actuator stuff outside of RBT, the only input for RBT will be torque. Since actuator dynamics will require additional states and so on, and before we get into coupled joints, it's reasonable to assume independence between joints. #4004 has a sketch of the setup in sys2.

**Comment by liangfok** [comment]
+1 for keeping the messy actuator stuff outside of the RBT.

**Comment by RussTedrake** [comment]
to clarify, i think the proposed input to rigidbodyplant is the generalized forces (torques) + wrenches that can be applied to particular frames.  The list of these inputs (e.g. which joints have actuators, which points on which bodies can take external wrenches) would be built up programmatically.

**Comment by naveenoid** [comment]
@amcastro-tri What is the status of the proposal discussed here? Is it possible to apply a generalized force + torque to a select frame on a select model instance on a RBtree within a RBPlant? If not, could we have a quick f2f soon on what needs to land for that? 
A student here in Zurich is very interested in that.

**Comment by amcastro-tri** [comment]
As we discussed f2f with you here in CAM during your visit, there has not been an immediate need for this to get resolved. My goal was to get all of this functionality ASAP in MBT. However, if there is an immediate need we can talk about how this should look like.

**Comment by sherm1** [comment]
Won't be adding this to RBPlant -- MultibodyPlant yes.
