### ISSUE TITLE
Move RBT parsing files into `drake/multibody/parsers`

### ISSUE THREAD

**Issue by amcastro-tri** [RobotLocomotion/drake#4091]
Once #4058 is merged, move parsing files into their own directory.
What do you think @liangfok?

**Comment by jwnimmer-tri** [comment]
Yes in general the pile of files in `multibody` need further reorganization.  But given the inappropriate class designs (circular dependencies) this is not as simple as just mv'ing some files.

**Comment by amcastro-tri** [comment]
I agree but, would this be a step further towards this reorganization? I think there are no circular dependencies here that would not allow me to do this refactoring.

**Comment by jwnimmer-tri** [comment]
There is a circle now, yes.  The RBT includes the parsers which include the RBT.

**Comment by liangfok** [comment]
One concern I have is the parsers may emit more information than what's stored in `RigidBodyTree`. For example, SDF contains light information, which doesn't seem to belong in a `RigidBodyTree`:

http://sdformat.org/spec?ver=1.6&elem=light

How about let's put the parsers in `drake-distro/drake/parsers`?

**Comment by jwnimmer-tri** [comment]
@liangfok The mandate of `multibody` will be wide and deep.  Not only the kinematic tree, but also the visual scene (including lights), actuators, sensors, etc.  I think more or less we should keep everything that's already in there still in there, until we have a positively-identified need to elevate it.

**Comment by amcastro-tri** [comment]
Humm.... isn't all the parsing code now in `drake/multibody` specific to RBT? in which case moving to `multibody/parsers` would be fine?

**Comment by liangfok** [comment]
Yes. I was just thinking in the future where we will have parsers for things like RNDF, XODR, etc. Will those be in different `parsers/` directories?

**Comment by jwnimmer-tri** [comment]
Umm... yes?

**Comment by liangfok** [comment]
Cool. SGTM...until a single format spans multiple `parsers/` directories.

**Comment by jwnimmer-tri** [comment]
If there exists an input format that merges both SDF and RNDF, I will burn it with fire, rather than write a parser for it.

**Comment by liangfok** [comment]
Consider renaming `parser_urdf` and `parser_sdf` to be `urdf_parser` and `sdf_parser`, respectively, along with their relocation.

**Comment by liangfok** [comment]
How about let's place all parsers in `drake-distro/parsers`?

**Comment by amcastro-tri** [comment]
The parsers no in `drake/multibody` are very RBT specific. I would therefore put those in `drake/multibody/parsers`.

**Comment by liangfok** [comment]
Sorry, I meant to say `drake-distro/drake/parsers`.

OK we can put them in `drake-distro/drake/multibody/parsers` for now, and then move them into a more general location in case they eventually become not multibody specific.
