### ISSUE TITLE
RigidBodyPlant Needs To Provide More Info About the Semantics Of Its Input and Output Ports

### ISSUE THREAD

**Issue by liangfok** [RobotLocomotion/drake#4094]
# Problem Definition

Currently, there is no way to determine the semantics of either the input or output ports of `RigidBodyPlant` since it only provides methods that return the numbers of states, actuators, inputs, and outputs. The lack of semantics is addressed by an implicit  assumption that the ordering within the vectors produced or consumed by the `RigidBodyPlant`'s ports matches the ordering of the actuators and states within the `RigidBodyTree`. 

Is this assumption sufficient? Should a more semantically rich API be provided? At a minimum, the implicit assumption should be explicitly documented in `RigidBodyPlant`.

Note that this problem may become more pressing as we begin developing simulations that consist of more than just one `RigidBodyTree`.

One idea is to subclass `BasicVector` and to include a pointer to the `RigidBodyTree` within the child class.

**Comment by jwnimmer-tri** [comment]
This issue is about the RBT code, in the attic. We're not going to fix it, it's okay to leave it however it is now.
