### ISSUE TITLE
Support finer-grained direct feedthrough

### ISSUE THREAD

**Issue by david-german-tri** [RobotLocomotion/drake#4105]
This is starting to cause pain in some diagrams related to the IIWA arm.

cc @sammy-tri

**Comment by liangfok** [comment]
Is this a duplicate of #2890?

**Comment by sherm1** [comment]
They are certainly related since #2890 is a prerequisite, but I think this is worth tracking separately.

**Comment by david-german-tri** [comment]
API support was added in #5199, but it won't do anything useful until #2890.
