### ISSUE TITLE
Proliferation of Shared Libraries in KUKA IIWA Example Needs Consolidation

### ISSUE THREAD

**Issue by liangfok** [RobotLocomotion/drake#4113]
# Problem Definition

There is a proliferation of libraries in `drake-distro/drake/examples/kuka_iiwa_arm/`:

* `drakeKukaIiwaArmCommon`
* `drakeKukaIiwaArm`
* `drakeKukaIiwaWorld` (pending #4107)

We should reconsider whether having so many libraries is reasonable. For example, maybe all three can be consolidated into one library after System 1.0 is removed.

**Comment by naveenoid** [comment]
Very good point. I will consolidate as soon as #4107 lands.

**Comment by naveenoid** [comment]
Status update : The result of #4107 can easily be merged with `drakeKukaIiwaArmCommon` which in turn can be renamed to `drakeKukaIiwaArm` once issue #3977 is resolved. That is currently blocked by the status of `kuka_plan_runner.cc and `kuka_lcm_visualizer`.
