### ISSUE TITLE
Attach publish handler to diagram

### ISSUE THREAD

**Issue by sherm1** [RobotLocomotion/drake#4114]
@RussTedrake asked me how to capture a trajectory during a simulation. I said, you just need to capture a copy of the Context at each simulation step, or at periodic intervals. You can do that with the Publish() method since it gets called with a const Context at specified sampling times. Russ said, but that only provides the local LeafSystem's subcontext. I said, no, capture it in the Diagram's Publish() ... oops.

Currently I don't think there is a way for a user to provide Diagram-level Publish() behavior. Am I missing something? Otherwise we should provide that so the full Context can be captured.

(A workaround is to call `Simulator::StepTo()` repeatedly for short periods and ask the Simulator for the Context after each interval.)

**Comment by RussTedrake** [comment]
But I still don't think this adequately addresses #3734.  The request is that the simulator not only returns the data as evaluated at each time step (in a trajectory object), but that it returns the correct interpolation scheme given the integration method that was used.  E.g., if ode45 gives 4th order accuracy, then perhaps it returns a fourth order spline trajectory.

**Comment by david-german-tri** [comment]
Yeah, I always assumed this would be implemented in general form in the Simulator, not in user-specific Diagram code.  However, if whole-Diagram Publish is the right thing to do, it would be easy enough to add hooks for that post #4031.

**Comment by sherm1** [comment]
> But I still don't think this adequately addresses #3734. 

I agree. That's a bigger project. But it should be possible to publish whole-Context results from a Diagram; we didn't have a use case before.
