### ISSUE TITLE
Windows install guide

### ISSUE THREAD

**Issue by aespielberg** [RobotLocomotion/drake#4125]
Hi all,

I know that Windows is no longer supported, but would it be possible to get the Windows installation guide back on the webpage (perhaps with an [unsupported] label or something)?  This would be useful for those looking to install with the "Last Windows SHA."

**Comment by jamiesnape** [comment]
https://github.com/RobotLocomotion/drake/blob/last_sha_with_windows_support/drake/doc/windows.rst

**Comment by aespielberg** [comment]
Thanks!
