### ISSUE TITLE
Expected control rate for atlas examples

### ISSUE THREAD

**Issue by samkhal** [RobotLocomotion/drake#4137]
When I run `runAtlasWalking` (from the last matlab-supported SHA) and time the plan and control steps, I get rates on the order of 20 Hz (0.01s for plan, 0.04s for control). I haven't started benchmarking everything yet, but in the relevant papers there were rates of 333 Hz or 1 kHz mentioned (though I don't recall the computer specs).

I'm running on a 2.8 GHz i7-4700MQ on a laptop, with one core maxing out to run this. Are these rates expected? Is there anything I should look at in terms of boosting performance?

**Comment by RussTedrake** [comment]
on the robot, we run each component as a separate executable (communicating over LCM), and of course on a fairly beefy desktop.

**Comment by samkhal** [comment]
Can you share the specs of the computer it was running on? I don't imagine separating the process would affect this question since I'm benchmarking the control process individually. I'm just curious as to why I'm running an order of magnitude slower than you guys were.

**Comment by hongkai-dai** [comment]
Are you compiling in debug mode?

**Comment by samkhal** [comment]
No, my build type is Release.

**Comment by hongkai-dai** [comment]
When you time the control cycle, do you include the simulation time, or only solving the QP?

**Comment by samkhal** [comment]
I'm not including simulation; I'm just timing the function `InstantaneousQPController.updateAndOutput`.

The timing code is already there; I'm just unsuppressing output by setting `quiet = false` in `BipedPlanEvalAndControlSystem.m`
