### ISSUE TITLE
Additional unit testing for RK3 integrator

### ISSUE THREAD

**Issue by edrumwri** [RobotLocomotion/drake#4163]
From Reviewable comments for PR #4033, we need to add the following to the RK3 integrator unit test source:

1. A system composed from two independent mass-spring systems using a Diagram. The inclusion of this system will better stress the vector-based weighting approach used in the error controlled integrator. The two outputs from the independent mass-spring dampers can be checked for accuracy using the existing closed form solution check.
  
2. A check that the system from (1) produces the correct dimensional weighting vectors.

3. Introduction of an auxiliary (`z`) variable, presumably to one of the mass-spring systems, for exercising that aspect of the error norm calculation.

**Comment by sherm1** [comment]
We also need to try RK3 as the default and see what breaks.

**Comment by edrumwri** [comment]
You mean as the default integrator for Simulator?

**Comment by sherm1** [comment]
Yes. For now I mean just to test it (it would have segfaulted with the non-conformant multiplies). I would like a variable step integrator to be the actual default but we need to make sure it works for the existing applications first!

**Comment by sherm1** [comment]
I believe this is well tested now. Closing.
