### ISSUE TITLE
Build libraries in a location that mirrors the source tree

### ISSUE THREAD

**Issue by david-german-tri** [RobotLocomotion/drake#4225]
Libraries are built in `build/lib`, but should be built in `drake/path/to/my/lib.so` by analogy to binaries (post #4162).

**Comment by jwnimmer-tri** [comment]
Is this worth solving in CMake?  Maybe just wait for Bazel?

**Comment by david-german-tri** [comment]
Based on Slack conversation, it sounded pretty trivial to solve.  If it's more than a 30min investment we should rethink.

**Comment by jamiesnape** [comment]
It should just be removing one line from `pods.cmake`.
