### ISSUE TITLE
Need IsContinuousTimeOnly and IsDiscreteTimeOnly for Context<T>

### ISSUE THREAD

**Issue by RussTedrake** [RobotLocomotion/drake#4262]
IsContinuousTimeOnly should return true iff there is continuous state but no discrete nor modal state.  

IsDiscreteTimeOnly should return true iff there is discrete state but no continuous nor modal state.

These will be used, eg, in Linearize/LQR/Kalman/... to justify only examining the Derivatives and making an approximation of xdot, or only discrete analysis.

**Comment by david-german-tri** [comment]
Why on the System, instead of the Context?

**Comment by david-german-tri** [comment]
Updated description from f2f.
