### ISSUE TITLE
Tracking peformance issues with Valkyrie simulation

### ISSUE THREAD

**Issue by amcastro-tri** [RobotLocomotion/drake#4270]
See related issue to Atlas simulation #2287.
This issue is opened to track the evolution of computational cost in the Valkyrie simulation as we fix issues in the dynamics engine. 
Related, closed PR #4249 on poor man's caching for RBP.

These times are measured for 1.0 second of simulated time in my P50. Profiling performed with:
 `valgrind --tool=callgrind ./valkyrie_simulation` and visualized with `kcachegrind callgrind_filename.out`. 
The measurements in parentheses below show ([times called] / [percentage total runtime]).

- 9a620fd (baseline): 24 seconds. `RBT::AllPairsClosestsPoints` (88.2%), `MathematicalProgram::Solve()` (SVD) (3.32%), `RBT::doKinematics()` (0.42%). This method is triggered separately by `EvalTimeDerivatives`, `EvalOutput` and by `DrakeVisualizer::Publish`.
-  86410a7 (PR #4206): 15 seconds. `AllPairsClosestPoints` to + patch filtering out collision pairs after Bullet is called. `RBT::ComputeMaximumDepthCollisionPoints()` (265 / 82.8%), `MathematicalProgram::Solve()` (SVD) (88 / 5.9%), `RBT::doKinematics()` (531 / 0.72%).

**Comment by tri-ltyyu** [comment]
Please use MBP instead. If it's still an issue, please open new issue.
