### ISSUE TITLE
urdf reference link on drake main sphinx documentation page is broken

### ISSUE THREAD

**Issue by RussTedrake** [RobotLocomotion/drake#4319]

**Comment by jwnimmer-tri** [comment]
Ping, /CC @david-german-tri.

The http://drake.mit.edu/urdf/drakeURDF.html#:// is still broken.

**Comment by jamiesnape** [comment]
Closed via RobotLocomotion/drake-ci#72.

**Comment by jamiesnape** [comment]
http://drake.mit.edu/urdf/drakeURDF.html
