### ISSUE TITLE
UpdateStatistics call is using the wrong step size

### ISSUE THREAD

**Issue by sherm1** [RobotLocomotion/drake#4336]
In `IntegratorBase::StepOnceAtMost()` the `UpdateStatistics` call is being fed the maximum allowable step size rather than the one that was actually taken by `DoStepOnceAtMost()`.

Likely DoStepOnceAtMost() needs to return the step it actually took as well as some kind of status return (took whole step, stopped due to zero crossing, ...). (I wouldn't use the floating point time value return to decide if it took the whole step since the low level method can determine that without floating point math.)

**Comment by edrumwri** [comment]
Addressed by #4347.
