### ISSUE TITLE
DiagramBuilder's ExportInput() and ExportOutput() Methods Do Not Provide Port Number Information

### ISSUE THREAD

**Issue by liangfok** [RobotLocomotion/drake#4371]
# Problem Definition

When constructing a `Diagram` that exports more than one input and/or output ports, it is often necessary to know the index of a particular port. This is currently not possible because `drake::systems::DiagramBuilder::ExportInput()` and `drake::systems::DiagramBuilder::ExportOutput()` do not tell the calling code the indices of the ports that were just exported.

In #4296, the `PidControlledSystem` was modified to provide two accessors: `get_control_input_port()` and `get_state_input_port()`. The implementation of these methods hard-code the indices 0 and 1, respectively. This is brittle against the order in which these input ports were declared, which occurs [here](https://github.com/RobotLocomotion/drake/blob/9415dbdf0632ce7b4af08aa54f1a426b4fe580e1/drake/systems/controllers/pid_controlled_system.cc#L117).

# Suggested Solution

Modify `drake::systems::DiagramBuilder::ExportInput()` to return the index of the port that was just declared. This port index can then be used by `PidControlledSystem` to avoid hard-coding the port indices in `get_control_input_port()` and `get_state_input_port()`. Similarly, `drake::systems::DiagramBuilder::ExportOutput()` should be modified in the same manner and for the same purpose.

**Comment by david-german-tri** [comment]
Good point!  The fix SGTM, feel free to PR it (or I'll get to it eventually)

**Comment by liangfok** [comment]
OK thanks. Will do.
