### ISSUE TITLE
System 2 state variable name changes: Modal -> Abstract, Difference -> Discrete

### ISSUE THREAD

**Issue by sherm1** [RobotLocomotion/drake#4373]
Per f2f with @RussTedrake (and general agreement) let's clean up the naming of state variables to use:
- Continuous (numerical, governed by differential equations)
- Discrete (numerical, governed by difference equations)
- Abstract (general type, general update scheme)

The second two replace Difference and Modal, resp. I'm making this high priority since it will require API changes. Existing documentation needs updating, and we ought to mention somewhere for hybrid systems folks that if they have "modal" variables they are encouraged to implement them using Drake's Abstract variables.

@edrumwri has kindly agreed to make these changes.

**Comment by edrumwri** [comment]
Addressed by PR #4430.
