### ISSUE TITLE
simulator should not evaluate at the continuous sampling intervals (as defined by the integrator) if there is no continuous state

### ISSUE THREAD

**Issue by RussTedrake** [RobotLocomotion/drake#4376]
follow-up from #4359.  discussed f2f w/ @sherm1 @david-german-tri et al.  

for example, in the current implementation, if I added a DoPublish to https://github.com/RobotLocomotion/drake/blob/0ae4b48/drake/examples/simple_discrete_time_system.cc , it would get called at every 0.001sec (because that's the default integrator timestep), when it should only be called every 1sec.

EDIT (eric): Estimated a SHA to get a source permalink.

**Comment by sherm1** [comment]
This old issue is resolved now with much better control of events. Please open a new one if you have any complaints about the current behavior.
