### ISSUE TITLE
Design discussion: Sample Times in System 2.0

### ISSUE THREAD

**Issue by RussTedrake** [RobotLocomotion/drake#4377]
See [this google doc](https://docs.google.com/document/d/1NRg5E1ziZ27nnOCppZ7m-E3lXFE6a84IN-QCzlVJTo4) for my current understanding.  Let's iterate and implement.

**Comment by sherm1** [comment]
How I think about discrete events in general: there are *triggers* and *event handlers*. In principal any kind of trigger can can invoke any kind of event handler. We currently distinguish three kinds of event handlers:
- "publish" events (can't affect the trajectory)
- "discrete" events (can only modify numerical "difference" variables xd)
- "unrestricted" events (can modify anything in the Context except time)

Typical triggers:
- successful completion of an integration step (trajectory advancement)
- periodic or specified time reached
- zero crossing of a state-dependent witness (guard) function
- arrival of a message or user input
- simulation initiation or termination

@edrumwri is currently implementing unrestricted events and came up with that term which I think is very accurate.

We will not necessarily implement the full cross product of (triggers X handlers); as long as we have (triggers X unrestricted) we can do anything.

**Comment by david-german-tri** [comment]
I'm generally on board with @sherm1's framework.  I do hope there are intermediate waypoints that will let us update abstract state on a time trigger, though!  There's a lot of demand for that capability.

**Comment by david-german-tri** [comment]
(And from an implementation standpoint, it would be pretty trivial to add to EvalDifferenceUpdates)

**Comment by sherm1** [comment]
> I do hope there are intermediate waypoints that will let us update abstract state on a time trigger, though! There's a lot of demand for that capability.

Glad you said that! See @edrumwri's PR #4382.

**Comment by david-german-tri** [comment]
Closing as fixed, as the result of many PRs.   As @sherm1 mentioned above, #4382 was especially significant.
