### ISSUE TITLE
SteeringCommandDriver.py Throttle Can Only Increase

### ISSUE THREAD

**Issue by liangfok** [RobotLocomotion/drake#4434]
# Problem Definition

When running `drake-distro/drake/automotive/steering_command_driver.py`, the throttle value can only be increased, not decreased.

**Comment by liangfok** [comment]
@shensquared do you have any insights into this?

**Comment by shensquared** [comment]
Yes, I think it used to be binary, pressing the up arrow sends throttle value 1, and releasing the up arrow sends throttle value 0. My PR changes pressing the up arrow to gradually increase the throttle, up to ~26, but broke the releasing up arrow key part: the throttle now keeps the value when the key was released. I'll fix it, will set releasing the up arrow to decrease the throttle to 0 at the same rate that pressing the key increases it.
