### ISSUE TITLE
PidControlledSystem::get_control_input_port()'s Name is Confusing

### ISSUE THREAD

**Issue by liangfok** [RobotLocomotion/drake#4449]
The name `get_control_input_port()` is confusing because the reader may not understand what it means. Consider renaming it to be `get_feedforward_control_input_port()`. This is longer but less confusing because the reader will know that any signals inputted into this port will simply be fed through as part of the PID controller's output control signal.

**Comment by jwnimmer-tri** [comment]
Seems like this is either a 10-minute fix or a WONTFIX, not something to keep open for a long time.

**Comment by sammy-tri** [comment]
Closing as WONTFIX, the doxygen already explains it's the feedforward control input.
