### ISSUE TITLE
Mysterious CI Error: fatal: Not a git repository

### ISSUE THREAD

**Issue by liangfok** [RobotLocomotion/drake#4451]
# The Error:

```
fatal: Not a git repository: ../../../.git/modules/drake/doc/textbook
```

# Example Logs

https://drake-jenkins.csail.mit.edu/job/linux-clang-ninja-experimental-open-source/1476/

**Comment by liangfok** [comment]
Again: https://drake-jenkins.csail.mit.edu/job/linux-gcc-experimental-open-source/1513/

**Comment by david-german-tri** [comment]
@stonier This is a tracking issue for a CI flake.  In my view, no action is required, and it will likely be moot after CMake is turned down.
