### ISSUE TITLE
Should valkyrie_pd_ff_controller Be Added As A Unit Test?

### ISSUE THREAD

**Issue by liangfok** [RobotLocomotion/drake#4456]
The `valkyrie_pd_ff_controller` executable is currently not being executed as a unit test. Should it be?

**Comment by siyuanfeng-tri** [comment]
short answer is no. the feedforward part is computed offline, and will be off pretty substentialy during sim, so it's not a stable test case yet.

**Comment by liangfok** [comment]
OK thanks. I'm messing with the parsers and got it to compile but noticed I wasn't actually testing whether it ran.
