### ISSUE TITLE
Move systems/framework/primitives to systems/primitives

### ISSUE THREAD

**Issue by jwnimmer-tri** [RobotLocomotion/drake#4462]
I recall @RussTedrake suggesting this in the hallway.  Is that correct?

**Comment by RussTedrake** [comment]
Correct!

**Comment by jwnimmer-tri** [comment]
@david-german-tri @sherm1 or anyone else: any objections?

**Comment by david-german-tri** [comment]
Makes sense to me now that we have entered the post-System1, post-MATLAB era.  Feel free to reassign to me if you haven't already started.

**Comment by jwnimmer-tri** [comment]
Sure, thanks!  Beware the conflicting PR #4459 still in flight.

**Comment by sherm1** [comment]
Seems like a good idea to me.

**Comment by naveenoid** [comment]
+1
