### ISSUE TITLE
Warning - SWIG / Python Detected a Memory Leak

### ISSUE THREAD

**Issue by liangfok** [RobotLocomotion/drake#4469]
# Problem Definition

The following warning occurs when the SWIG / Python unit test `test_python_pydrake.test.testPR2IK` or `test_python_pydrake.test.test_urdf_parser` are run:

```
swig/python detected a memory leak of type 'std::map< std::string,int,std::less< std::string >,std::allocator< std::pair< std::string const,int > > > *', no destructor found.
```

# Examples:
* https://drake-cdash.csail.mit.edu/testDetails.php?test=5480982&build=251903
* https://drake-jenkins.csail.mit.edu/view/Continuous%20Production/job/linux-clang-continuous-debug/1387/

**Comment by jwnimmer-tri** [comment]
I'm not sure why we care?

**Comment by liangfok** [comment]
We might not care depending on whether we decide to switch away from SWIG: https://github.com/RobotLocomotion/drake/issues/4486.

**Comment by jwnimmer-tri** [comment]
I mean, say the pydrake bindings leak a little memory.  Do we even care about that?  This is just a console message, not a memcheck warning, not an anything.  I guess it's confusing in the build output, but beyond that I don't see why we care.

**Comment by liangfok** [comment]
Are you saying this warning is not indicative of a defect in C++ Drake?

**Comment by jwnimmer-tri** [comment]
Right.  It's specific to SWIG.

**Comment by liangfok** [comment]
Oh great. That's good to know. I'll close this issue for now pending the resolution of #4486.

**Comment by jamiesnape** [comment]
> not a memcheck warning,

Note that memcheck screams so much when testing the Python bindings that we just switched them off.

**Comment by rdeits** [comment]
This is a symptom of swig being asked to return a type that it hasn't created a destructor for. It's easy to fix on a case-by-case basis, but only if we care enough about making swig work.
