### ISSUE TITLE
steering_command_driver.py Should Be Updated To Support Two Modes (Velocity vs. Acceleration) Use Realistic Acceleration / Jerk Profiles

### ISSUE THREAD

**Issue by liangfok** [RobotLocomotion/drake#4471]
# Problem Definition

`drake/automotive/steering_command_driver.py` is currently being used by both physics-based simulations (e.g., `car_sim_lcm`) and non-physics-based simulations (e.g., the `simple_car` within `automotive_demo`). This is problematic because the two types of simulations expect different input types. Specifically, the physics-based demo wraps a dynamics-based plant in a PID controller that takes as input the _desired velocity_ of the vehicle. In contrast, the non-physics-based demo directly uses a kinematics-based plant that takes as input the _desired acceleration_ of the vehicle. Since both types of vehicles are using the same `steering_command_driver.py`, there is a conflict in terms of interpreting the semantics of the output.

Originally, `steering_command_driver.py` throttle and brake output values were scaled from [0, 1]. They should be interpreted as normalized desired acceleration and deceleration values per #4472. In #4023, @shensquared changed the semantics of these values to be desired velocities rather than desired accelerations. This fixed the `car_sim_lcm` demo but broke `simple_car`. I did not notice because it simply resulted in `simple_car` moving faster than before.

We need to solve the above discrepency by modifying `steering_command_driver.py` to support two modes of operation: (1) velocity or (2) acceleration.

## Velocity Mode

When running in velocity mode, the GUI should only show two values: (1) desired heading and (2) desired normalized velocity. When the up or down arrows are held down, the desired velocity should gradually increase or decrease based on realistic acceleration / deceleration profiles. Typing both keys simultaneously is an error condition and should be treated as a no-op (as if no key was pressed). Releasing the up or down arrow results in the desired velocity not changing, as if the vehicle were in cruise control.

## Acceleration Mode

When running in acceleration mode, the GUI should show three values: (1) desired heading, (2) desired normalized throttle, and (3) desired normalized brake. Pressing and holding the up arrow should result in the desired normalized throttle gradually increasing to 1 using a realistic jerk profile. Releasing the up arrow should result in the desired normalized throttle going to zero, again using a realistic jerk profile. Similar behavior should occur when holding and releasing the down arrow. Typing both the up and down arrows should result in the same behavior, i.e., both the normalized throttle and normalized brake values increase using realistic jerk profiles. This would be analogous to you hitting both the accelerator and brake peddles in your car.

## New LCM Message Type

To avoid confusion, a new LCM message type should be introduced to handle the velocity mode of  `steering_command_driver.py`. The existing `lcmt_driving_command_t` can be used with acceleration mode. However, perhaps it should be renamed `lcmt_driving_acceleration_command_t`. For velocity mode, let's create a `lcmt_driving_command_t` message as follows:

```
struct lcmt_driving_velocity_command_t {
  // The timestamp in milliseconds.
  int64_t timestamp;

  double steering_angle;
  double velocity;
}
```

## Can Acceleration Mode Be Used With A Physics-Based Car?

Yes, however, not if the physics-based car is wrapped in a position/velocity PID controller. One idea is to divide the reference acceleration provided by the `steering_command_driver.py` by the mass of the vehicle to get the force that should be applied to the vehicle's CoM, and then somehow compute the reference torques that needs to be applied to the wheel joints to effectively achieve the same acceleration of the CoM. These reference torques can then be sent into the `RigidBodyPlant` containing the vehicle.

# Old Problem Definition from 2016/12/13

~~`drake/automotive/steering_command_driver.py` currently uses hard-coded and linear jerk profiles when the user hits and holds the up and down keyboard arrows. The shape and slope of this jerk profile is not realistic. This issue tracks the enhancement of this program to use realistic jerk profiles.~~

~~Another issue with `steering_command_driver.py` is the fact that the reference jerk outputted by `steering_command_driver.py` immediately becomes zero when the user releases the forward or backward key. This results in a "step function" in the reference jerk signal for the vehicle's controllers to follow, which is sub-optimal and may result in controller instability.~~

~~/CC: @shensquared - Just wanted you to see this; not assigning it to you since this is a low priority task.~~

**Comment by jwnimmer-tri** [comment]
I mean, the throttle message is batshit anyway.  Sometimes it means target velocity, sometimes it means acceleration.  I feel like we should fix the system models before we fix the key/joy input tool.

**Comment by liangfok** [comment]
Good point. I created #4472 and gave it a higher priority.

**Comment by liangfok** [comment]
Looking at `SimpleCar`'s usage of `lcmt_driving_command_t`  (per @jwnimmer-tri's comment here: https://github.com/RobotLocomotion/drake/issues/4472#issuecomment-266495303), I now see that its `throttle` and `brake` values are actually gains applied to the maximum acceleration / deceleration of the vehicle. Thus, their units are "change in the acceleration per simulation cycle". Thus, the linear increase and decrease in the throttle / brake values that are currently implemented in `steering_command_driver.py` are actually specifying the change in the acceleration per update cycle, which I believe is called the "jerk".

**Comment by jwnimmer-tri** [comment]
Now that we almost have a suite of demos working, we should revisit this in a few weeks.

**Comment by liangfok** [comment]
Closing this since it's been superseded by other steering wheel drivers.
