### ISSUE TITLE
bazel-bin/external and bazel-bin/externals?

### ISSUE THREAD

**Issue by RussTedrake** [RobotLocomotion/drake#4484]
looks like there might be some inconsistency in the BUILD files, since I get both directories appearing in my build output?

**Comment by jwnimmer-tri** [comment]
The distinction here is whether the external has native Bazel support (gflags), or whether Drake adds the BUILD recipes for it (everything else).  I think "working as designed" though re-open if there's some more specific problem or request to fix.
