### ISSUE TITLE
Investigate Bazel support for CLion

### ISSUE THREAD

**Issue by jwnimmer-tri** [RobotLocomotion/drake#4485]
Many Drake developers use CLion.  We should figure out what works and doesn't with Bazel BUILD and WORKSPACE files, consider what improvements we can make, and document the results.

Part of #3129.

**Comment by jwnimmer-tri** [comment]
Possibly relevant bazelbuild/bazel#1029 which pointed me to bazelbuild/intellij#26 :confetti_ball:.

**Comment by RussTedrake** [comment]
fwiw, just lost a few hours trying Tulsi with bazel to work with Xcode.  Long story short, I think it's not going to support our workflow without some work.  I made some local edits to the tulsi code to get fairly far along (https://github.com/RussTedrake/tulsi), but it is not able to understand the "@glib://" deps, which apparently comes in through pkg-config (which comes in through the thirdparty bazel support).  

The local edits that I did make were needed for it to even consider cc_* as valid targets.  It was only looking for e.g. ios_application.  So it's clearly not being used for our workflow yet.

**Comment by jwnimmer-tri** [comment]
IIRC possibly David was going to try to look into this also.

**Comment by david-german-tri** [comment]
Yes, I'm trying to get https://github.com/bazelbuild/intellij/issues/26 working locally.  No luck yet.

**Comment by david-german-tri** [comment]
Fixed in #4814.
