### ISSUE TITLE
vToqdot is very slow, even when it ultimately returns the identity matrix

### ISSUE THREAD

**Issue by RussTedrake** [RobotLocomotion/drake#449]
from the 6.832 discussion boards.

![1412049916289750](https://cloud.githubusercontent.com/assets/6442292/4475438/5871474e-496c-11e4-9fd5-751a7c0c2159.png)

**Comment by tkoolen** [comment]
Sorry for never having fixed this. @rdeits is fixing this now by calling a C++ version.

**Comment by rdeits** [comment]
Switching to the C++ version of this method cuts about 25-30% off the entire time required so simulate Atlas walking. But doing so safely requires vToqdot to take a kinsol as its argument rather than q, which introduces a lot of interface changes.

**Comment by RussTedrake** [comment]
If it's not too much work, I'd say do the interface changes so we can see them in the pull request?

**Comment by tkoolen** [comment]
Fixed in https://github.com/RobotLocomotion/drake/pull/1527. Close?
