### ISSUE TITLE
Unprovisioned nightly Bazel build on Xenial

### ISSUE THREAD

**Issue by david-german-tri** [RobotLocomotion/drake#4496]

**Comment by jamiesnape** [comment]
@BetsyMcPhail Clone `linux-xenial-gcc-bazel-experimental` and set the extra environment variables to trigger the provisioning.

**Comment by BetsyMcPhail** [comment]
Let's give the experimental build a try

@drake-jenkins-bot linux-xenial-unprovisioned-gcc-bazel-experimental please

**Comment by david-german-tri** [comment]
Whoa, does that notation do something on GitHub issues as well as PRs?

**Comment by BetsyMcPhail** [comment]
No, @david-german-tri :( wishful thinking on my part. I'm going to launch it manually.

**Comment by BetsyMcPhail** [comment]
Unprovisioned nightly Bazel Xenial build is should run tonight.

**Comment by BetsyMcPhail** [comment]
Job ran successfully last night.
