### ISSUE TITLE
Mac Bazel build in CI

### ISSUE THREAD

**Issue by david-german-tri** [RobotLocomotion/drake#4497]
Should be pinned to the 0.4.2 release: https://github.com/bazelbuild/bazel/releases/tag/0.4.2

**Comment by jamiesnape** [comment]
@BetsyMcPhail Double check the version of Bazel on the image. If we are lucky and it is 0.4.2, run `brew pin bazel` to pin the version. After that, the logic in the Linux builds should be largely applicable to Mac.

**Comment by david-german-tri** [comment]
I think we're about ready for this, so I'm bumping the priority to medium.

**Comment by david-german-tri** [comment]
It's up!
