### ISSUE TITLE
LcmPublisherSystem should only publish at a fixed rate

### ISSUE THREAD

**Issue by david-german-tri** [RobotLocomotion/drake#4502]
This is now possible in System2/Simulator2 using `CalcNextUpdateTime`.

**Comment by david-german-tri** [comment]
Ditto for DrakeVisualizer.

**Comment by RussTedrake** [comment]
I agree it should be an option, but I’m not sure that this is obviously the right default behavior.  Use the default publish (e.g. any major timestep of the simulator) has the advantage that we publish anytime the simulation decides something.  It’s the best way to keep a downstream lcm subscriber “in step” with the simulation… no?

**Comment by david-german-tri** [comment]
@RussTedrake Sounds good to me.  I have no particular intuition about which is better.  As a bonus, your proposal is a little easier to implement, since it won't require custom [do_publish](https://github.com/RobotLocomotion/drake/blob/master/drake/systems/framework/system.h#L40) callbacks.

**Comment by jwnimmer-tri** [comment]
So #4111 seems to cover (duplicate) the Drake Visualizer System portion of this.
