### ISSUE TITLE
Building against deleted header files

### ISSUE THREAD

**Issue by SeanCurtis-TRI** [RobotLocomotion/drake#4504]
Take this issue modulo the actual answer.

We've encountered an inconvenient build artifact.  The problem is as follows:

  - Drake is built, populating `install` directory.
  - Upstream changes remove a referenced header file from repository.
  - I update my local repo to match the upstream repo (the header disappears from source branch).
  - I can still build because, apparently, the `install` path is part of the include path.
  - `make clean` does not flush the `install` directory -- thus, we still have code that conflicts in reality, but isn't detected in the local build.

Possible solutions:
   1) Build system shouldn't be looking in the `install` directory (although, I can imagine for we're going there for generated headers???)
   2) Have `make clean` flush `install` directory.

**Comment by liangfok** [comment]
Does this problem occur using both CLion and command line?

**Comment by jwnimmer-tri** [comment]
FTR, I have been bitten by this too.  I have chosen to use Bazel to get correctness, rather than fix our use of CMake.

**Comment by SeanCurtis-TRI** [comment]
@liangfok Yep.  Definitely CLion -- can't definitively state command line, but I suspect so.  I can't imagine that CLion would unilaterally extend its include paths.  (And as @jwnimmer-tri has been bitten...it seems to be a very democratic issue; everyone gets some, regardless of IDE.)

**Comment by RussTedrake** [comment]
I can confirm that this has been a known issue for a long, long time.

**Comment by david-german-tri** [comment]
#3129 makes this moot, so closing.
