### ISSUE TITLE
Maliput Should Be Updated To Use Eigen Where Possible

### ISSUE THREAD

**Issue by liangfok** [RobotLocomotion/drake#4542]
# Problem Definition

In #4227 and #4389, custom logic was used to implement basic mathematical concepts like:

* `class Rot3` in `maliput/monolane/lane.h`
* `Rotate()` and `Distance()` in `maliput/api/road_geometry.c`
* numerous structs in `maliput/api/lane_data.h`
* `W_prime_of_prh()` in `maliput/monolane/lane.cc` should use `drake::math::drpy2rotmat()`.
* `CubicPolynomial` in `maliput/monolane/lane.h`

For increased robustness and to reduce lines-of-code, these custom implementations should be updated to use Eigen and `drake::math`, the matrix libraries used by the rest of Drake.

**Comment by jwnimmer-tri** [comment]
I would be curious to see where the _APIs_ should use Eigen but aren't vs the _implementation_.  The former is important to do earlier; the latter can come in due time.  Do we have a write-up or survey of API primitives that duplicate Eigen?

**Comment by liangfok** [comment]
Migrated to downstream repo.
