### ISSUE TITLE
Document CMake build "comprehensive nuke"

### ISSUE THREAD

**Issue by jwnimmer-tri** [RobotLocomotion/drake#4551]
Sometimes, a CMake-generated build gets confused or produces wrong results.  There's various lore floating around in slack land about how to fix it, especially with the case of `git submodules` being used.

Perhaps we should curate and document one good set of instructions for this, and post it into our sphinx docs.  Then we can always point devs at that best advice, instead of some good-but-not-quite variant from last week's slack or etc.

(This issue was broken out of #1973.)

**Comment by jwnimmer-tri** [comment]
@sammy-tri would you like to take a crack at this (or assigning it)?  The manipulation subteam is perhaps the primary user of the CMake build, and does the most playing with externals and such that breaks this?

**Comment by jwnimmer-tri** [comment]
Slightly related #4454 and #4504.

**Comment by liangfok** [comment]
This is a great idea. At @naveenoid's suggestion, we placed the "comprehensive nuke" recipe for Drake + ROS here: http://drake.mit.edu/from_source_ros.html#how-to-perform-a-clean-build. It would be great to document the Drake-only recipe.

**Comment by jwnimmer-tri** [comment]
Ah yes.  I thought I remembered being discussed, but failed to find that write-up.

**Comment by jamiesnape** [comment]
Level 1 nuke for non-MATLAB and non-Python users:
```
rm -rf build
```

Level 2 nuke:
```
rm -rf build
git clean -xfd
git submodule foreach --recursive git clean -xfd
```

Level 3 nuke:
```
rm -rf build
git clean -xfd
git submodule foreach --recursive git clean -xfd
git reset --hard
git submodule foreach --recursive git reset --hard
```
