### ISSUE TITLE
Doxygen File Descriptions Do Not Have Automatically-Generated Links

### ISSUE THREAD

**Issue by liangfok** [RobotLocomotion/drake#4560]
# Problem Definition

Doxygen's [automatic link generation feature](https://www.stack.nl/~dimitri/doxygen/manual/autolink.html) is not working on file descriptions. This became a problem in #4389, which contains file descriptions in `drake-distro/drake/automotive/maliput/monolane/builder.h` and `drake-distro/drake/automotive/maliput/monolane/loader.h` that references numerous classes, structs, etc. When reading the generated Doxygen website, clarity would be greatly improved if the aforementioned references could be links to the classes', structs', etc., documentation.

**Comment by jwnimmer-tri** [comment]
I looked at what Doxygen was giving us for Builder.  The missing links were annoying, but not worth an issue.  However, having to click through into `builder.h` to find the Builder's overview write-up was a real problem.  I've PR'd that fix (which happens to also add the hyperlinks requested in OP).
