### ISSUE TITLE
Provide a drake implementation of the MoveIt! interface

### ISSUE THREAD

**Issue by RussTedrake** [RobotLocomotion/drake#459]
Should be relatively straight-forward:
http://moveit.ros.org/documentation/concepts/

I think there are a lot of people that would try the code / planners if we did this.

**Comment by jwnimmer-tri** [comment]
@RussTedrake is this still relevant / keep it open?

**Comment by davetcoleman** [comment]
+1 to moving forward with this :)

**Comment by RussTedrake** [comment]
@naveenoid -- assigning to you to decide if it's relevant for your project.

**Comment by davetcoleman** [comment]
I'm one of the lead maintainers of MoveIt! - let's get on a phone/video chat to discuss. I just emailed you two.

**Comment by jwnimmer-tri** [comment]
This is a useful background discussion, but we're not going to pursue this feature for a while.
