### ISSUE TITLE
RigidBodyTree::collisionRaycast() Needs To Be Made const.

### ISSUE THREAD

**Issue by liangfok** [RobotLocomotion/drake#4592]
In System 2.0, we need to call `RigidBodyTree::collisionRaycast()` from a `const` context, like from within the bodies of `System::DoCalcUpdate()` and `System::DoPublish()`. Currently, we cannot do this without resorting to using `const_cast`.

**Comment by sherm1** [comment]
While you're in the neighborhood, @SeanCurtis-TRI ...

**Comment by SeanCurtis-TRI** [comment]
This is part of a larger problem; that being the process of querying the tree updates the tree.  We have the same issues when doing contact computation.  This will probably be deferred until `GeometryWorld` takes over these responsibilities and `GeometryQuery` provides an appropriate `const` interface.

**Comment by liangfok** [comment]
Thanks for investigating. I will close this issue and trust that it will be eventually resolved once GeometryWorld and GeometryQuery are introduced.
