### ISSUE TITLE
boxcar.sdf Is Missing Visual Elements - Need to improve automotive_simulator_test.cc to check for visual element of SimpleCar

### ISSUE THREAD

**Issue by liangfok** [RobotLocomotion/drake#4595]
I didn't try to load it but from a quick glance, it appears to be missing any visual element:

https://github.com/RobotLocomotion/drake/blob/09d818b81f79cd054262605ddbe2c6959bae28a8/drake/automotive/models/boxcar.sdf

Is this true? Is this expected?

**Comment by jwnimmer-tri** [comment]
@liangfok You added this model to the repo, for use by unit tests (only).  Probably you are the best person to answer whether its content is as-expected or not.

**Comment by liangfok** [comment]
Oh yeah, you're right. Looks like the unit test (`automotive_simulator_test.cc`) doesn't check the model instance's visualization. It only checks the existence of a link in the model instance. I'll update this issue to reflect the need to improve the unit test.

**Comment by jwnimmer-tri** [comment]
We could also just delete the boxcar(s)?

**Comment by liangfok** [comment]
SGTM. Either way is OK. In the past, having BoxCars was helpful for detecting excessive overhead of using models with multiple articulated bodies and mesh visualizations.

**Comment by jwnimmer-tri** [comment]
@liangfok This is a quick fix either way, yes?  Can you choose one and PR it?  Issues with 2-minute fixes shouldn't linger.

**Comment by liangfok** [comment]
Yes, it's a quick fix. I'm on it.
