### ISSUE TITLE
InputPortDescriptor and OutputPortDescriptor are virtual and copyable

### ISSUE THREAD

**Issue by jwnimmer-tri** [RobotLocomotion/drake#4614]
InputPortDescriptor and OutputPortDescriptor are virtual and copyable.  One or the other choice is wrong -- types shouldn't be both at once (at least not without private clone fanciness), because of the slicing problem.

**Comment by jwnimmer-tri** [comment]
... and if they remain copyable, that should be documented as part of the API overview and/or `= default` methods, so users clearly know they can rely on it.

**Comment by sherm1** [comment]
Related: discussion in #2890.

**Comment by jwnimmer-tri** [comment]
FTR from grepping for similar problems in `framework` the `LeafSystemOutput` and `Context` are both `virtual` (with good purpose) but lack `= delete` of their copy & assign.
