### ISSUE TITLE
Soliciting comments for a LCM tunable variable. 

### ISSUE THREAD

**Issue by siyuanfeng-tri** [RobotLocomotion/drake#4639]
We want to add a mechanism to enable online tunable variables. This is especially useful for tuning gain / parameter interactively. 

The current proposal is to have a LCM handler class that stores a list of variables (e.g. double) and their memory addresses. For each incoming LCM message, the handler updates all the variables in that message by writing the values in the message directly to the corresponding memory addresses. 
This handler will also spawn a publishing thread that periodically sends a status message that contains all the registered variables' names and values. This is useful for updating the user interface automatically. The status message should also contain an unique identifier, so that different handler instances can publish status message to the same LCM channel. 

This design is supposed to be minimalistic and general. The handler class is storing raw memory addresses, so the user can practically bypass anything with this. 

@RussTedrake @sammy-tri @liangfok @patmarion All comments and concern are welcome. This is a very useful tools for many applications, so I want it to be as general as possible. @manuelli already has an initial implementation for valkyrie, unfortunately that lives in a private repo. The design is very simple, so I feel verbal description should suffice. I could just copy that to a public domain if there is interest.

**Comment by siyuanfeng-tri** [comment]
I suppose another big problem is that the stored memory address points to some dynamic thing which can be reallocated (e.g. Eigen::VectorXd).

**Comment by jwnimmer-tri** [comment]
@siyuanfeng-tri Consider closing this?  Is it still relevant?

**Comment by siyuanfeng-tri** [comment]
still relevant, but closing anyhow due to lack of general interest.
