### ISSUE TITLE
Update Drake To Support Various Combinations of SDF Pose Specifications

### ISSUE THREAD

**Issue by liangfok** [RobotLocomotion/drake#4641]
# Problem Definition

In #4615, several combinations of joint outboard frame, link frame, inertia frame, and body frame values were identified as being inconsistently supported or interpreted between Drake vs. Gazebo. This issue tracks the resolution of these discrepancies.

EDIT (eric): This is now geared towards ensuring that we have parity for `MultibodyPlant`; no changes will be made for `RigidBodyTree`.

# Action Items

- [x] #12226 Ensure that Drake MBP can support specifying poses for links. (At present, we discard this information under certain circumstances).
- [ ] #12061 Update to handle the full set of `//pose[@relative_to]` specifications in the upcoming SDFormat 1.7: [docs](http://sdformat.org/tutorials?tut=pose_frame_semantics_proposal&cat=pose_semantics_docs&)

---

# OLD Action Items

- simple_double_pendulum_l_is_not_specified.sdf: Works in both Drake and Gazebo, but differently. In Drake, the unspecified L frame is assumed to equal the mobilizer's outboard frame. In Gazebo, the L frame appears to be made equal to the model's frame.
- simple_double_pendulum_l_equals_i.sdf: Works in Gazebo only. We should update Drake to support this scenario.
- simple_double_pendulum_l_between_b_and_i.sdf: Works in Gazebo only. We should update Drake to support this scenario.

**Comment by liangfok** [comment]
This is blocked on #4337.

**Comment by jwnimmer-tri** [comment]
@EricCousineau-TRI Maybe you want to take over / triage / close this issue, as related to current senatics-related ongoing work?

**Comment by EricCousineau-TRI** [comment]
Done. While the above examples might no longer apply, parity between Gazebo and Drake should be explicitly checked. At present, we have some deviations on MBP, so I'll repurpose this issue for that.
