### ISSUE TITLE
Add Suite of Parsers Frames Unit Test With All Non-Zero Pose Values

### ISSUE THREAD

**Issue by liangfok** [RobotLocomotion/drake#4643]
# Problem Definition

In #4615, @amcastro-tri added a suite of unit tests for evaluating various model frame configurations, which resulted in several bugs being identified (#4641). @sherm1 pointed out that numerous frames employed in that suite were defined using `<pose>0 0 0 0 0 0</pose>`, which may result in additional bugs being hidden.

Here is @sherm1's comment:

> I noticed there are a lot of zeroes in the input file frames, particularly model frames. Those leave open the possibility that a frame might be being ignored since it wouldn't matter. Please consider making as many of the frames non-zero as possible.

# Action Item

Add another suite of similar unit tests where the frame poses are all non-zero, which will hopefully root out additional frame-related bugs.

**Comment by amcastro-tri** [comment]
Great idea @liangfok. Maybe this or another issue, but I think it'd also be a good idea to test the effect of `<use_parent_model_frame>` in `<joint>/<axis>`. The logic inside the SDF parser for this entry is quite obscure and I think we should cover its usage.

**Comment by amcastro-tri** [comment]
cc'ing @clalancette. This had to do with a consistent unambiguous definition of frames.

**Comment by rpoyner-tri** [comment]
This issue is so old, the SDFormat parser (and spec for that matter) have been completely rewritten. Closing.
