### ISSUE TITLE
Remove dv_to_dqdot parameter from `DrakeJointImpl::v2qdot()` and dqdot_to_v parameter from `DrakeJointImpl::qdot2v`, if possible.

### ISSUE THREAD

**Issue by edrumwri** [RobotLocomotion/drake#4651]
These parameters seem to be unused. Per @sherm1's  Reviewable request in PR #4604, adding this issue.

**Comment by jwnimmer-tri** [comment]
This is a RigidBodyTree cleanup, so we will not pursue it.
