### ISSUE TITLE
MultibodyPlant<double> should provide a function to compute Jdot*v

### ISSUE THREAD

**Issue by RussTedrake** [RobotLocomotion/drake#466]
The kinematic methods (e.g. RelativePosition) only return first derivatives so far.  Twan makes a compelling case that we should not implement dJ, but rather have a means to compute Jdot*v directly.  In practice, I need this functionality in order to take the gradients of the constrained dynamics, which happens in `examples/SimpleFourBar/runLQR`.

**Comment by RussTedrake** [comment]
updated name to reflect the fact that this should happen in the c++ function/constraint classes.

**Comment by hongkai-dai** [comment]
I believe this is a feature request to `MultibodyPlant`. I will close this issue and re-open a new one for tracking.

**Comment by hongkai-dai** [comment]
Reopen this issue with updated name, also I changed the assignee.

**Comment by amcastro-tri** [comment]
@hongkai-dai, could we close this one and open a new specific issue (with reference to this if it helps). Lots of old discussions and notation use. Also, there are the `MBP::CalcBiasFor[Your Jacobian type]()` methods. Maybe we just need a new variant of those? would you specify in the new issue?

**Comment by hongkai-dai** [comment]
Close this issue as we have #11013
