### ISSUE TITLE
BUILD file in drake-distro root conflicts with "from source" instructions

### ISSUE THREAD

**Issue by RussTedrake** [RobotLocomotion/drake#4693]
Just went to make a fresh build from master on a different (mac) laptop, and hit this one.

```
31-34-10% cd drake-distro
31-34-10% mkdir build
mkdir: build: File exists
```

nice.  i can't actually create a build directory right now.  and given some assumptions in our cmake files (#4606), I can't name it something else.

**Comment by SeanCurtis-TRI** [comment]
Hard to imagine where the build folder came from; it doesn't appear in master.

**Comment by sherm1** [comment]
There is, OTOH, a *file* named `BUILD` in master. Is this possibly a platform where file names are case-insensitive so that `BUILD` and `build` name the same file?

**Comment by RussTedrake** [comment]
I'm sorry.  I thought all of that was implied.  Yes -- on mac the filenames are case insensitive, so the existence of the BUILD file in drake-distro disallows the creation of a build directory.

**Comment by jamiesnape** [comment]
Just hit that myself today. All our infrastructure uses a directory called `build` so it is somewhat of an issue. OS X CI builds delete `BUILD` (they assume it was a left over `build` directory).

**Comment by jamiesnape** [comment]
This may also be what is caused the update column of CDash to turn red for OS X builds.

**Comment by jwnimmer-tri** [comment]
Understood.  I should be able to get a work-around PR in tonight.  Local work-around would be to build using CMake (with rm BUILD; mkdir build) xor Bazel.

**Comment by jwnimmer-tri** [comment]
Directly on point: bazelbuild/bazel#552.

**Comment by jamiesnape** [comment]
> Is there a reasonably cost-effective way we could have made CI find this for us (even post-merge / nightly)?

It is tricky because cleaning the `build` directory was itself a safety feature in case removal of the workspace from the previous build failed. CDash did pick up that something was wrong, but we do not currently consider failures computing the change log an error. I will give it some thought.
