### ISSUE TITLE
OSX instructions should be updated to work around broken valgrind formula

### ISSUE THREAD

**Issue by rdeits** [RobotLocomotion/drake#4715]
The OSX (with homebrew) instructions ask the user to install, among other things, `valgrind`, but it looks like the `valgrind` formula is currently broken on Sierra (OS X 10.12): 

https://github.com/Homebrew/homebrew-core/issues/4841#issuecomment-254217338
https://github.com/Homebrew/homebrew-core/issues/4841#issuecomment-254217338

the instructions should be updated to mention that for Sierra users.

**Comment by david-german-tri** [comment]
@rdeits, I've reassigned this to you, since you have the most context on the subject.  cc @soonho-tri

**Comment by rdeits** [comment]
Ok. Am I correct in assuming that Valgrind isn't required to build Drake?

**Comment by david-german-tri** [comment]
Yes!
