### ISSUE TITLE
Consider Making 0 Instead of +Inf Signify "Update Every Sim Time Step"

### ISSUE THREAD

**Issue by liangfok** [RobotLocomotion/drake#4747]
Currently, `std::numeric_limits<T>::infinity()` is used to signify to the simulator that a system wants to be updated every major time step of the simulation. This is awkward since it could also be interpreted to mean "never update me" or "update me at time infinity". Consider using a value of 0 to signify the need to update a system every major time step of the simulation. It would be less confusing since, assuming simulation time >= 0, that would mean, "update me now" or "update me yesterday already".

For background context, see @jwnimmer-tri's comment here: https://reviewable.io/reviews/RobotLocomotion/drake/4731#-KaAtj8mLcrcdtXypmiU

**Comment by jwnimmer-tri** [comment]
@liangfok Which method in particular?  I seem to recall that the infinity-semantics in System2 were okay, and only the PR draft was confusing.

**Comment by liangfok** [comment]
Sorry, the method I'm referring to is `System::DoCalcNextUpdateTime()`:

https://github.com/RobotLocomotion/drake/blob/0210c74af7a5b8129388ab92e04c856fefcfe61f/drake/systems/framework/system.h#L851

**Comment by jwnimmer-tri** [comment]
Yeah, that one is no problem IMO.  When the question is "When should I be next updated?" the answer "Never" is perfect.

**Comment by liangfok** [comment]
But does "Never" imply "Update at the next major time step"?

**Comment by jwnimmer-tri** [comment]
Nope.  Updates only happen when you ask.

Note that "Publish every major timestep" is an entirely different concept.

**Comment by liangfok** [comment]
Oh I see. OK. I suppose I'm still getting mixed up between the use of `System<T>::DoCalcNextUpdateTime()` vs. `LeafSystem<T>::DeclarePublishPeriodSec()` to throttle the publishing of LCM messages.
