### ISSUE TITLE
Install clang-3.9 on AMIs used for Bazel builds

### ISSUE THREAD

**Issue by david-german-tri** [RobotLocomotion/drake#4774]
Apparently it isn't already there?  I was surprised.

https://drake-jenkins.csail.mit.edu/job/linux-gcc-bazel-experimental/462/console

**Comment by jamiesnape** [comment]
It is there, but it is at `/usr/local/bin` because the APT packages are broken.

**Comment by jamiesnape** [comment]
(also that is not an unusual location to which Clang would be installed)

**Comment by david-german-tri** [comment]
Ping on this

**Comment by BetsyMcPhail** [comment]
Both Xenial and Trusty images have now been updated so clang-3.9 is in /usr/bin.

Note that it's going to take a little while for Jenkins to completely switch over to the new Trusty AMI.
