### ISSUE TITLE
qp_controller.h Appears To Have Methods Labeled Setters That Are Actually Getters

### ISSUE THREAD

**Issue by liangfok** [RobotLocomotion/drake#4779]
# Examples

https://github.com/RobotLocomotion/drake/blob/2dcd0f5837f1a845f064e8c4be5b1970c9a39a81/drake/examples/QPInverseDynamicsForHumanoids/qp_controller.h#L151

https://github.com/RobotLocomotion/drake/blob/2dcd0f5837f1a845f064e8c4be5b1970c9a39a81/drake/examples/QPInverseDynamicsForHumanoids/qp_controller.h#L448

https://github.com/RobotLocomotion/drake/blob/2dcd0f5837f1a845f064e8c4be5b1970c9a39a81/drake/examples/QPInverseDynamicsForHumanoids/qp_controller.h#L550

https://github.com/RobotLocomotion/drake/blob/2dcd0f5837f1a845f064e8c4be5b1970c9a39a81/drake/examples/QPInverseDynamicsForHumanoids/qp_controller.h#L764

https://github.com/RobotLocomotion/drake/blob/2dcd0f5837f1a845f064e8c4be5b1970c9a39a81/drake/examples/QPInverseDynamicsForHumanoids/qp_controller.h#L888

https://github.com/RobotLocomotion/drake/blob/2dcd0f5837f1a845f064e8c4be5b1970c9a39a81/drake/examples/QPInverseDynamicsForHumanoids/qp_controller.h#L963

https://github.com/RobotLocomotion/drake/blob/2dcd0f5837f1a845f064e8c4be5b1970c9a39a81/drake/examples/QPInverseDynamicsForHumanoids/qp_controller.h#L1041

**Comment by jwnimmer-tri** [comment]
I think this code either disappeared, or has moved into `attic/systems/controllers/qp_inverse_dynamics` which we're not planning on changing anyway.
