### ISSUE TITLE
Visualization problem possibly caused by missing pod-build/share directory

### ISSUE THREAD

**Issue by bzreinhardt** [RobotLocomotion/drake#478]
This error occurs whenever I use an example that calls the 3D visualizer in both Linux and Mac:

Warning: Invalid file or directory
'/Users/Zaaron/drake-distro/spotless/pod-build/share/java/lcmtypes_drake.jar'. 

> In javaclasspath>local_validate_dynamic_path at 274
>   In javaclasspath>local_javapath at 182
>   In javaclasspath at 119
>   In javaaddpath at 71
>   In javaaddpathProtectGlobals at 23
>   In checkDependency at 58
>   In BotVisualizer>BotVisualizer.BotVisualizer at 25
>   In RigidBodyManipulator.RigidBodyManipulator>RigidBodyManipulator.constructVisualizer at 1375
>   In testVisuals at 7 
> Warning: Currently all of your LCM traffic will be broadcast to the network, because:
> /bin/bash: util/check_multicast_is_loopback.sh: No such file or directory
> 
> In checkDependency at 63
>   In BotVisualizer>BotVisualizer.BotVisualizer at 25
>   In RigidBodyManipulator.RigidBodyManipulator>RigidBodyManipulator.constructVisualizer at 1375
>   In testVisuals at 7 
> LCM: Disabling IPV6 support
> LCM: TTL set to zero, traffic will not leave localhost.
> launching drake_viewer...
> Undefined variable "drake" or class "drake.lcmt_viewer_load_robot".

Error in BotVisualizer (line 61)
      vr = drake.lcmt_viewer_load_robot();

Error in RigidBodyManipulator/constructVisualizer (line 1375)
            v = feval(type,arg{:});

Error in testVisuals (line 7)
v = p.constructVisualizer();

**Comment by peteflorence** [comment]
In case it's helpful for future, I also came across an error:

Undefined variable "drake" or class "drake.lcmt_viewer_load_robot".

And it was because I erroneously had:

```
javaaddpath('/usr/local/share/java/lcm.jar')
```

In my startup.m (which I had added due to a suggestion which was given in a previous error message)

Removing the line above from my startup.m, and having instead this correct startup.m, fixed my problem:

```
cd /Users/pflomacpro/drake-distro5/drake-distro/
addpath_pods
cd /Users/pflomacpro/drake-distro5/drake-distro/drake
addpath_drake
```
