### ISSUE TITLE
Bad UX When User Fails To Connect An Input Port.

### ISSUE THREAD

**Issue by liangfok** [RobotLocomotion/drake#4790]
# Problem Definition

If a user fails to connect a `BasicVector` input port, the following error might occur when trying to start a simulation:

```
* thread #1: tid = 0x1f30ca, 0x000000010018f7af libdrakeQuadrotorCommon.dylib`drake::examples::quadrotor::QuadrotorPlant<double>::DoCalcTimeDerivatives(drake::systems::Context<double> const&, drake::systems::ContinuousState<double>*) const [inlined] Eigen::DenseStorage<double, -1, -1, 1, 0>::data() const at DenseStorage.h:557, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x8)
    frame #0: 0x000000010018f7af libdrakeQuadrotorCommon.dylib`drake::examples::quadrotor::QuadrotorPlant<double>::DoCalcTimeDerivatives(drake::systems::Context<double> const&, drake::systems::ContinuousState<double>*) const [inlined] Eigen::DenseStorage<double, -1, -1, 1, 0>::data() const at DenseStorage.h:557
```

From the error message, it's difficult to root-cause the problem.

# Suggested Course of Action

Is there a way for a `System` to declare that an input port is "required" in the sense that it must be connected? With this information, maybe we could add a `Diagram::IsValid()` that checks to ensure that all required input ports within the `Diagram` are connected.

**Comment by david-german-tri** [comment]
System authors are responsible for asserting that input ports the system requires are not nullptr.
