### ISSUE TITLE
MathematicalProgram should not return the shared pointer when adding constraint

### ISSUE THREAD

**Issue by hongkai-dai** [RobotLocomotion/drake#4856]
Currently `MathematicalProgram` stores a vector of shared pointers, pointing to the added constraints. When adding a new constraint to `MathematicalProgram`, the newly created constraint is returned to the user as a shard pointer. The code is like this
```C++
class MathematicalProgram {
 public:
  std::shared_ptr<LinearConstraint> AddLinearConstraint(A, lb, ub, x);
 private:
  std::vector<std::shared_ptr<LinearConstraint>> linear_constrants_;
}
```
I think the reason why we choose to store a shared pointer, is to allow the user to update the constraint, in the following way
```C++
std::shared_ptr<LinearConstraint> lin_con = prog.AddLinearConstraint(A, lb, ub, x);
lin_con->UpdateConstraint(new_A, new_lb, new_ub);
```

Generally using shared pointer raises the eye brow, as it becomes ambiguous who owns the resource. We want to get rid of the shared pointer stored in the MathematicalProgram.

**Comment by liangfok** [comment]
The need to update a constraint could be satisfied if `AddLinearConstraint()` returns a mutable pointer to the added constraint right?

```
LinearConstraint* AddLinearConstraint(...);
```

**Comment by hongkai-dai** [comment]
I think we will stick to using shared pointer in MathematicalProgram.
