### ISSUE TITLE
CI Failure Due to kuka_cartesian_way_point_demo Timing Out

### ISSUE THREAD

**Issue by liangfok** [RobotLocomotion/drake#4857]
# The Error

```
15:55:26 226/229 Test #217: kuka_cartesian_way_point_demo ......................***Timeout  60.01 sec
```

# Example Logs

* https://drake-jenkins.csail.mit.edu/job/linux-clang-continuous-ros-debug/1020/

**Comment by ggould-tri** [comment]
Recurred at https://drake-jenkins.csail.mit.edu/view/Continuous%20Production/job/linux-clang-continuous-ros-debug/1027/

**Comment by ggould-tri** [comment]
Recurred at https://drake-jenkins.csail.mit.edu/view/Continuous%20Production/job/linux-gcc-continuous-ros-debug/998/

**Comment by ggould-tri** [comment]
Based on this occurring every couple of days in CI, I am assigning it a high priority.
