### ISSUE TITLE
Support partial evaluation in symbolic::Expression

### ISSUE THREAD

**Issue by hongkai-dai** [RobotLocomotion/drake#4877]
Currently symbolic::Expression supports evaluation when the values of all variables are specified. Expect a function

```C++
Expression Expression::Evaluate(const Environment& env = Environment{}) const;
```
if `env` does not specify all variable values.

**Comment by soonho-tri** [comment]
From the discussion with @hongkai-dai,

- [ ] Introduce a new type `Substitution` a mapping from an `Variable` to an `Expression` (`std::unordered_map<Variable, Expression>`).
- [ ] Add a substitution function
    ```c++
    Expression Expression::Substitute(const Substitution& subs) const;
    ```
 - [x] We'll keep the current evaluation function
    ```c++
    double Expression::Evaluate(const Environment& env = Environment{}) const
    ```
