### ISSUE TITLE
make drake::symbolic::Variable just drake::Variable

### ISSUE THREAD

**Issue by soonho-tri** [RobotLocomotion/drake#4884]
The goal is to have a single notion of "variable" in drake code base, to avoid code duplication and possible name collisions.

**Comment by soonho-tri** [comment]
@jwnimmer-tri , I'm working on moving `Variable`, `Variables`, and `Environment` classes from `common::symbolic` namespace to `common` namespace. Which one of the followings is the best way to shape them in `BUILD` file?

 1. Keep them under `symbolic` library
 2. Have each in its own library (i.e. `variable.cc` => `variable`)
 3. Have the three in one library (i.e. `variable.cc`, `variables.cc`, `environment.cc` => `variable`)

**Comment by jwnimmer-tri** [comment]
For Bazel, the right answer is the smallest libraries that make sense as standalone components.
