### ISSUE TITLE
Mysterious CI Bazel Error - No Discernible Error

### ISSUE THREAD

**Issue by liangfok** [RobotLocomotion/drake#4908]
# The Problem

A Bazel-based CI run turns red, but the console log contains no discernable error.

# Example Logs

* https://drake-jenkins.csail.mit.edu/job/linux-xenial-gcc-bazel-experimental/808/

**Comment by jamiesnape** [comment]
CTest said pass, but Jenkins said fail. My guess would be some sort of flake that caused the file `SUCCESS` to not be touched.

**Comment by jwnimmer-tri** [comment]
Maybe close this until it happens so much as to be worth root causing?

**Comment by liangfok** [comment]
Agreed.
