### ISSUE TITLE
zap functional_form

### ISSUE THREAD

**Issue by hongkai-dai** [RobotLocomotion/drake#4909]
Will switch to `symbolic::Expression` instead.

**Comment by jwnimmer-tri** [comment]
/CC @soonho-tri Are you nominally working on this (so assign it?)  Or is @hongkai-dai doing it?

**Comment by soonho-tri** [comment]
I am not working on it now. @hongkai-dai , did you start working on this?

**Comment by hongkai-dai** [comment]
Not yet, but I can take it.

**Comment by hongkai-dai** [comment]
I believe "functional_form" is gone in drake.
