### ISSUE TITLE
Remove functions that add cost/constraints in MathematicalProgram for all variables.

### ISSUE THREAD

**Issue by hongkai-dai** [RobotLocomotion/drake#4910]
Currently `MathematicalProgram` has functions like
```
MathematicalProgram::AddLinearConstraint(A, lb, ub);
```
which means imposing the constraint `lb <= A*x<=ub` for ALL variables inside `MathematicalProgram`. Personally I find this function unnecessary. This function also assumes that the user knows the order of the variables stored inside `MathematicalProgram`, as by reversing the order inside `x`, the meaning of this constraint is totally changed. I think that is a very strong assumption, and the user in most cases do not know the order of the variables inside `MathematicalProgram`.

Also, removing this function makes `mathematical_program.h` file a lot smaller, since for each type of cost/constraint, we have a function for all variables.

@sammy-tri and @RussTedrake what do you think?

**Comment by RussTedrake** [comment]
I completely agree.  Let's zap them

**Comment by rdeits** [comment]
I also totally agree.

**Comment by sammy-tri** [comment]
Fine by me.
