### ISSUE TITLE
Using Eigen::Array<Polynomial, Dynamic, Dynamic> for PolynomialMatrix in PiecewisePolynomial

### ISSUE THREAD

**Issue by hongkai-dai** [RobotLocomotion/drake#4911]
Currently we use `Eigen::Matrix<Polynomial, Eigen::Dynamic, Eigen::Dynamic>` as the type of `PolynomialMatrix` inside `PiecewisePolynomial` class. But this can cause confusion since we are doing element-wise product, when multiplying two piecewise polynomials, as we have seen in #4854 

I think the solution is to use `Eigen::Array` instead of `Eigen::Matrix`, as
```C++
typedef Eigen::Array<PolynomialType, Eigen::Dynamic, Eigen::Dynamic> PolynomialMatrix;
```
`Eigen::Array` supports element-wise product and addition.
@siyuanfeng-tri what do you think?

**Comment by hongkai-dai** [comment]
Also @jefesaurus

**Comment by siyuanfeng-tri** [comment]
@hongkai-dai, that should be the correct representation. I will fix it at some point. 
cc @tkoolen @rdeits @RussTedrake, just to make sure nothing is relying on the current "matrix multiplication" behavior.

**Comment by RussTedrake** [comment]
no dependencies from anything I've written.

**Comment by rdeits** [comment]
I don't think I've relied on that behavior anywhere.

**Comment by tkoolen** [comment]
I can't think of anything either.

**Comment by jwnimmer-tri** [comment]
@siyuanfeng-tri Want to take a crack at solving this?  Or else re-assign?

**Comment by siyuanfeng-tri** [comment]
I am tempted to just close it due to lack of strong desire and relative low value added to drake. Moving to backlog for now.

**Comment by jwnimmer-tri** [comment]
Given https://github.com/RobotLocomotion/drake/pull/4854#issuecomment-614764856, this cleanup request is mathematically wrong anyway.
