### ISSUE TITLE
Port automotive demos to use PoseAggregator

### ISSUE THREAD

**Issue by jwnimmer-tri** [RobotLocomotion/drake#5000]
Port automotive demos to use PoseAggregator.

**Comment by jwnimmer-tri** [comment]
This is gradually increasing in priority; bumping up the label accordingly.

**Comment by david-german-tri** [comment]
Thanks to @liangfok's recent efforts, I believe the only remaining use of `DrakeVisualizer` in `drake/automotive` is in `car_sim_lcm_common.cc`.

**Comment by david-german-tri** [comment]
And since `car_sim_lcm` is a dynamics-based simulation, which actually uses a `RigidBodyPlant`, I'm not sure it makes sense to port.  @jwnimmer-tri, are you OK with closing this?

**Comment by jwnimmer-tri** [comment]
I am okay with excluding `car_sim_lcm` from the porting, so if everything else is merged, then yes we're done.
