### ISSUE TITLE
More capable maliput backend

### ISSUE THREAD

**Issue by jwnimmer-tri** [RobotLocomotion/drake#5002]
In the medium term, we want a more capable maliput backend, likely to be waypoint-informed and have multiple lanes, interesting junctions, etc.  This can serve as a point to collect design notes and track completion.

**Comment by stonier** [comment]
@jwnimmer-tri is this the issue that was supposedly informative about a multilane backend?

**Comment by jwnimmer-tri** [comment]
The issue with more details is #4934.

**Comment by stonier** [comment]
Closing this one out, discussion is advancing in #4934.
