### ISSUE TITLE
SeDuMi error in Quadrotor2D example

### ISSUE THREAD

**Issue by MatthewPeterKelly** [RobotLocomotion/drake#502]
When running the Quadrotor2D example I get the error shown below. If I comment out the part in runLQR that calls SeDuMi, then everything everything else works fine, but I can't get the region of attraction for the controller (which is the part that I'm interested in).

I have the most up to date version of both SeDuMi and Drake, at least as far as I can tell. SeDuMi seems to work fine when it is called from SOSTOOLS, also newly installed.

I'm running Ubuntu 14.04 and using the Academic version of Matlab R2014a. Let me know if you have any suggestions, thanks!

```
```

> > runLQR
> > Index exceeds matrix dimensions.

Error in eigK (line 116)
    XX = x(xi+1:xi+qi);

Error in sedumi (line 797)
        info.err(2)=max(0,-min(eigK(full(x(origcoeff.K.f+1:end)),origcoeff.K)/(1+normb)));

Error in spot_sedumi (line 16)
    [x,y,s_info] = sedumi(A,b,c,K,sedumi_options);

Error in spotprog/minimize (line 737)
                [x,y,z,info] = solver(A,b,c,K,options);

Error in spotsosprog/minimize (line 480)
                sol = minimize@spotprog(pr,varargin{:});

Error in PolynomialSystem/regionOfAttraction>levelSetMethod (line 331)
  sol = prog.minimize(-rho,solver,options);

Error in PolynomialSystem/regionOfAttraction (line 136)
      V = levelSetMethod(V,f,options);

Error in PlanarQuadPlant/hoverLQR (line 50)
        V=regionOfAttraction(pp,V0,options);

Error in runLQR (line 7)
  [c,V] = hoverLQR(p);

**Comment by khalil37** [comment]
hi i am runig runTrajectorySwingUpAndBalance.m and i nedd SuDiMi how can i install it
