### ISSUE TITLE
adding cddlib to externals

### ISSUE THREAD

**Issue by hongkai-dai** [RobotLocomotion/drake#5037]
This library is available in https://www.inf.ethz.ch/personal/fukudak/cdd_home/. It is used to compute the two representations of a polyhedron, either using vertices (V representation) or halfspaces (H representation).

@rdeits uses it for IRIS, and I will use it for computing the Newton polytope in sum-of-squares optimization.

**Comment by RussTedrake** [comment]
it looks like cddlib is GPL.  is this license going to get in the way?  @jwnimmer-tri ?

**Comment by liangfok** [comment]
@sherm1's statement here is relevant: https://github.com/RobotLocomotion/drake/issues/3178#issuecomment-241087827

**Comment by rdeits** [comment]
That's highly unfortunate. I may need to modify iris to comply or to remove cddlib.

**Comment by liangfok** [comment]
Or perhaps contact the `cddlib` authors  to see if they're willing to issue a different license like MIT or BSD.

**Comment by hongkai-dai** [comment]
qhull (http://www.qhull.org/) is under MIT license https://github.com/bjnortier/qhull/blob/master/LICENSE, we can potentially use it instead of cddlib.

**Comment by hongkai-dai** [comment]
qhull is not under MIT license, sorry.
