### ISSUE TITLE
Getting active set from a mathematicalprogram solution

### ISSUE THREAD

**Issue by rdeits** [RobotLocomotion/drake#5069]
@hongkai-dai is it possible to retrieve the active set of linear inequalities from a QP in MathematicalProgram? I believe gurobi exposes that information, but I couldn't figure out if it was possible to access from the MathematicalProgram interface.

**Comment by hongkai-dai** [comment]
No we do not have that capability yet.

**Comment by rdeits** [comment]
covered in #4508
