### ISSUE TITLE
add open-source QP solvers

### ISSUE THREAD

**Issue by hongkai-dai** [RobotLocomotion/drake#5071]
per discussion with @edrumwri , we should consider moby, quadprog++, etc.

**Comment by siyuanfeng-tri** [comment]
i have used an eigenfied version of quadprog++ in the past.

**Comment by hongkai-dai** [comment]
Lift the priority of this issue, as Siyuan mentions that we want to solve QP problem at high rate on the robot. Mosek and Gurobi has the license issue (they need to talk to the license server, thus limiting its running speed). SCS is unfortunately inaccurate for this problem. So currently on the robot the code calls SNOPT, which can fail occasionally.

**Comment by hongkai-dai** [comment]
@jamiesnape and @jwnimmer-tri , can we build quadprog++ (https://github.com/liuq/QuadProgpp) in drake through bazel?

**Comment by jwnimmer-tri** [comment]
Yes, it looks trivial.  It would be similar to how we build the `fmt` library (see `tools/workspace/fmt/**` as called by `tools/workspace/default.bzl`), for example.

**Comment by jamiesnape** [comment]
@hongkai-dai Create an issue an assign it to me if you are not comfortable. Since it is a private dependency, it simplifies things even more.

**Comment by hongkai-dai** [comment]
Thanks! I can create a bazel build file for this.

**Comment by RussTedrake** [comment]
cc @frankpermenter

**Comment by arocchi** [comment]
You guys should take a look at qpOases

**Comment by hongkai-dai** [comment]
Thanks @arocchi , qpOASES looks great!

**Comment by Capri2014** [comment]
qpOASES is relatively slow through..

**Comment by frankpermenter** [comment]
A new solver with impressive benchmarks is OSQP.  See:

http://osqp.readthedocs.io/en/latest/
https://github.com/oxfordcontrol/osqp_benchmarks
