### ISSUE TITLE
Promote Parameters from LeafContext to Context

### ISSUE THREAD

**Issue by david-german-tri** [RobotLocomotion/drake#5072]
Contrary to my original belief, there are a few reasons we might want to reason about Parameters independent of a particular LeafSystem's semantics.  One of these is to measure symbolic sparsity.

I vaguely recall that @jadecastro had some other reasons.

**Comment by jadecastro** [comment]
Yeah, it fits well in the realm of parameter-varying systems, where the parameters for a given system are allowed to evolve according to some external process. A simple example of this is linearization of some nonlinear system (where the equilibria can vary with time and are not described by the linearized dynamics).

**Comment by RussTedrake** [comment]
Parameter estimation seems like another clear example.  There are generic tools for this (e.g. take the gradient of the dynamics with respect to the parameters, and update in that direction) that need not understand LeafSystem semantics to be used.
