### ISSUE TITLE
Incorrect detection of non-linear constraint

### ISSUE THREAD

**Issue by rdeits** [RobotLocomotion/drake#5086]
I'm trying to add a constraint to a MathematicalProgram, but I'm getting an error when checking the expression for linearity: 

```python
p = mp.MathematicalProgram()
q = p.NewContinuousVariables(2)
p.AddLinearConstraint(q[1] == q[0] + 0.5 * (q[0] + q[1]))
```

gives:

```
Expression ( - x(0) + x(1) - 0.5 * (x(0) + x(1))) is non-linear.
```

even though the expression is actually linear.

**Comment by hongkai-dai** [comment]
Thanks, I will work on this.

**Comment by rdeits** [comment]
thanks! :smile:

**Comment by hongkai-dai** [comment]
@soonho-tri is working on `Expand()` that expands a symbolic expression. I will try to provide a quick solution, to recursively extract the linear coefficients and constant from a symbolic expression. I think eventually we will just migrate to using `Expand()`.

**Comment by hongkai-dai** [comment]
A quick fix is not to use parenthesis in your expression. I think
```C++
p.AddLinearConstraint(q[1] == q[0] + 0.5 * q[0] + 0.5 *q[1])
```
should work

**Comment by rdeits** [comment]
Ok, thanks. Removing the parentheses does work.
