### ISSUE TITLE
DirectTrajectoryOptimization uses incompatible methods to reconstruct xtraj and utraj

### ISSUE THREAD

**Issue by hongkai-dai** [RobotLocomotion/drake#509]
In `DirectTrajectoryOptimization.reconstructStateTrajectory` and `reconstructInputTrajectory`, it is hard coded such that the both `xtraj` and `utraj` are first order hold trajectories. This is not true in `DirtranTrajectoryOptimization`, when it uses mid point interpolation. `DirtranTrajectoryOptimization` should reload those two methods for mid point interpolation

**Comment by jwnimmer-tri** [comment]
Closing as won't-fix, because #6369 will be removing the relevant software.

If I'm confused and this should in fact stay open, please re-open an clarify the remaining unsolved problem(s) in a new comment here.
