### ISSUE TITLE
Move All CompareToClone() Methods Into Test-Only Code

### ISSUE THREAD

**Issue by liangfok** [RobotLocomotion/drake#5096]
See: https://reviewable.io/reviews/robotlocomotion/drake/4958#-KcPp5CPEjY7xHrKgKPL

**TODO:**
- [x] rigid_body.h/.cc
- [x] rigid_body_frame.h/.cc

**Comment by amcastro-tri** [comment]
Is it really worth spending your energy on this @liangfok? remember this is just part of a sprint to get some partial support for RigidBodyPlant templated on AutoDiffScalar.

**Comment by liangfok** [comment]
@david-german-tri asked that it be done. His explanation is given in the link in this issue's description. I've copy/pasted it below:

> If not, please evict them to a test-only library and rephrase them as free functions. Test-only logic in production classes is an antipattern, because it makes it harder for future readers to tell what the actual code under test is, and because it invites accidental production usage of code that was never intended to be in production.

That being said, I will set the priority of this issue to be backlog since `RigidBodyPlant` will soon be supplanted by `MultiBodyWorld` (or was it called `MultiBodyPlant`?) in the near future.

**Comment by jwnimmer-tri** [comment]
If we are going to invest in Clone on RBT in order to support actual current work, then we need to do it correctly so as to sustain the work.  We can't ignore or indefinitely delay fixing defects.  I remain unconvinced that RBT Clone is a worth project, but others think it is, so let's do it right!

**Comment by liangfok** [comment]
Alright. I'll upgrade the priority a bit.
