### ISSUE TITLE
Improve CDash reporting of Bazel-run unit tests

### ISSUE THREAD

**Issue by jwnimmer-tri** [RobotLocomotion/drake#5098]
When CI runs Bazel tests, it posts the results to the dashboard in such a way that the usual mechanism for clicking through directly to test failure outputs is not specific (it usually just gives the entire log, if I recall correctly).  It would be nice to have only the specific failing tests' output.

**Comment by jwnimmer-tri** [comment]
Possibly there is a good integration seam using https://github.com/bazelbuild/dash, where the Bazel dash APIs could be terminated into something that emits CDash input files or even a direct http-to-http translation (if I understand the tools correctly).

**Comment by david-german-tri** [comment]
@jamiesnape and I also discussed this f2f today.  It isn't top priority but would definitely make everyone's life a little easier.

**Comment by jwnimmer-tri** [comment]
Agreed on both points.

I also like it because it would also be a nice give-back to the open-source community, assuming we can upstream it somehow (and I would support doing so).

**Comment by jamiesnape** [comment]
Fixed by https://github.com/RobotLocomotion/drake-ci/pull/87.
