### ISSUE TITLE
Cull the Trusty CMake pre-merge builds

### ISSUE THREAD

**Issue by david-german-tri** [RobotLocomotion/drake#5103]
At this point, we only really need the following four CMake pre-merge builds on Trusty:

* cpplint
* ROS
* matlab
* clang-debug

cc @jamiesnape

**Comment by BetsyMcPhail** [comment]
Trusty pre-merge:
linux-clang-experimental-debug
linux-cpplint-experimental
linux-gcc-experimental-matlab
linux-gcc-experimental-ros

Xenial pre-merge:
linux-xenial-clang-experimental
linux-xenial-clang-experimental-debug
linux-xenial-cpplint-experimental
linux-xenial-gcc-bazel-experimental

**Comment by BetsyMcPhail** [comment]
Jenkins has been updated as described above.
