### ISSUE TITLE
Bazel errors do not appear in CDash

### ISSUE THREAD

**Issue by Lucy-tri** [RobotLocomotion/drake#5105]
This build has errors:
https://drake-jenkins.csail.mit.edu/view/Continuous%20Production/job/linux-gcc-bazel-continuous-debug/381/
The problem is that if you click on "View in CDash" then click on the build errors, 4 errors are shown, but none of them are actually errors (they are warnings) and none of them point to the true error which you can see in the Console Output:
`//drake/examples/schunk_wsg:schunk_wsg_lift_test                        TIMEOUT in 60.1s`

I'm told this is due to this being a Bazel build. 
@jamiesnape said in Slack: 
> We should probably suppress those non-errors. No reason CDash could not work for Bazel otherwise.

**Comment by jamiesnape** [comment]
They are test failures. CDash previously only displayed build errors.

**Comment by jamiesnape** [comment]
See https://github.com/RobotLocomotion/drake-ci/commit/05698bcc2225f5a2baaf958a39b8c66f183ee638.

**Comment by jamiesnape** [comment]
https://drake-cdash.csail.mit.edu/viewBuildError.php?buildid=376028

**Comment by david-german-tri** [comment]
Nice!
