### ISSUE TITLE
(x * (y + z)).EqualTo(x*y + x*z) returns false.

### ISSUE THREAD

**Issue by hongkai-dai** [RobotLocomotion/drake#5162]
In the current symbolic expression, it does not handle the parenthesis well. The comparison
```C++
(x * (y + z)).EqualTo(x*y + x*z)
```
returns false, when comparing the hash values in https://github.com/RobotLocomotion/drake/blob/master/drake/common/symbolic_expression.cc#L120. But even if I commented out the hash value comparison, it still returns false.

**Comment by soonho-tri** [comment]
This is a duplicate of https://github.com/RobotLocomotion/drake/issues/5087. `Expression::EqualTo` checks structural equality. If you do not expand the two terms, they are structurally different.

**Comment by soonho-tri** [comment]
As we discussed in f2f: I'll add extra documentation clarifying `Expression::EqualTo` method.
