### ISSUE TITLE
Add derivative level to DrakeFunctions

### ISSUE THREAD

**Issue by tkoolen** [RobotLocomotion/drake#518]

**Comment by RussTedrake** [comment]
@avalenzu has a lot on his stack.  @hongkai-dai - can you take this one?

**Comment by hongkai-dai** [comment]
@tkoolen, do you also need property `grad_method`?

**Comment by tkoolen** [comment]
@hongkai-dai I think I just created this issue during a DRC meeting, I'm not actually a stakeholder.

**Comment by RussTedrake** [comment]
will be resolved soundly by the c++ constraint classes.
