### ISSUE TITLE
Bazel error with `*`

### ISSUE THREAD

**Issue by soonho-tri** [RobotLocomotion/drake#5180]
Repro step: `bazel build //drake/common:*`

Errors:
```
INFO: Found 279 targets...
ERROR: missing input file '//drake/common:cpplint.py'.
ERROR: /home/soonhok/work/drake-distro/drake/common/BUILD:516:1: //drake/common:cpplint.py: missing input file '//drake/common:cpplint.py'.
ERROR: /home/soonhok/work/drake-distro/drake/common/BUILD:516:1 1 input file(s) do not exist.
INFO: Elapsed time: 0.205s, Critical Path: 0.00s
```

/cc @david-german-tri , @jwnimmer-tri

**Comment by soonho-tri** [comment]
@david-german-tri suspects that it comes from https://github.com/RobotLocomotion/drake/blob/master/tools/cpplint.bzl#L55

Reference: https://bazel.build/versions/master/docs/bazel-user-manual.html

**Comment by david-german-tri** [comment]
> @david-german-tri suspects that it comes from https://github.com/RobotLocomotion/drake/blob/master/tools/cpplint.bzl#L55

That's now confirmed.
