### ISSUE TITLE
Have tests checking commutativity/associativity of symbolic expression over addition/multiplication

### ISSUE THREAD

**Issue by soonho-tri** [RobotLocomotion/drake#5191]
Suggested by @ggould-tri in the review of https://github.com/robotlocomotion/drake/pull/5182.

**Comment by jwnimmer-tri** [comment]
@soonho-tri Please either fix this or close the issue as WONTFIX.  "Missing tests" issues open for years on end have no useful value.

**Comment by soonho-tri** [comment]
WONTFIX
