### ISSUE TITLE
Feature Request: Modify automotive_demo.py to Optionally Print the Commands It is Executing

### ISSUE THREAD

**Issue by liangfok** [RobotLocomotion/drake#5204]
# Motivation

This would allow us to debug problems related to starting a demo using `automotive_demo.py`. We should be able to copy/paste the commands to execute them manually.

I recently encountered a problem where starting a demo using `automotive_demo.py` would basically cause my CPU to melt. The system would freeze for tens of seconds before displaying the various GUIs and by that time, the interesting part of the simulation was already over. This was on an OSX machine. It may be my fault since the demo is still undergoing review in (#5185).

**Comment by rpoyner-tri** [comment]
Closed by #5208 .
