### ISSUE TITLE
Document sdf/urdf collision semantics in Drake's contact filtering documentation

### ISSUE THREAD

**Issue by SeanCurtis-TRI** [RobotLocomotion/drake#5211]
PR #4890 provides documentation of how Drake handles collision filtering.  There are sections that are incomplete.  Specifically, the discussion of the collision state of SDF and URDF files.  For example, by default is self-collision disabled for whole models?  What tags exist in each of the specifications which are *not* accounted for in this discussion.  How are nested collision statements resolved?  Etc.

**Comment by EricCousineau-TRI** [comment]
Is this relevant any more?

**Comment by SeanCurtis-TRI** [comment]
Just as relevant today as ever.

**Comment by jwnimmer-tri** [comment]
FYI whatever happens for #14785 should also be reflected in the docs.

**Comment by jwnimmer-tri** [comment]
See also #18350.

**Comment by jwnimmer-tri** [comment]
I'm not entirely sure what was wanted here.  Possibly things like https://drake.mit.edu/doxygen_cxx/classdrake_1_1multibody_1_1_multibody_plant.html#ada6a17fc10f55293cc507b583220f8d7 are good enough?

In any case, if there is still more to finish that's fine, but we need a much more specific inventory of missing docs than what was here.
