### ISSUE TITLE
Changing integrator for simulator has unwieldy interface

### ISSUE THREAD

**Issue by SeanCurtis-TRI** [RobotLocomotion/drake#5265]
Currently, to change the integrator a simulator is using, you use something like the following:

```
const auto context = simulator.get_mutable_context();
  simulator.reset_integrator<SemiExplicitEulerIntegrator<double>>(
      *diagram, 1e-4, context);
```

The "unwieldy" part is that we "leak" the `context` out of the simulator to push into an integrator that the simulator owns anyways.  Similarly, the reference to the `diagram` is also shared with the simulator.  So, there are two pieces of data that is, in some sense, owned by the simulator but required externally to instantiate the integrator.

**Comment by sherm1** [comment]
I agree this can be improved! But note that the integrators are designed also to be used standalone (without a Simulator driving them) and that use should be preserved also. We do make use of that capability, especially for low level testing where we need precise control over integration activity. Likely there is some Simulator sugar needed.
