### ISSUE TITLE
Need to Add RgbdCamera to Prius Model Then Integrate with SimpleCar

### ISSUE THREAD

**Issue by liangfok** [RobotLocomotion/drake#5286]
# Problem Definition

We want to provide a multi-vehicle simulation that provides RGBD sensor data to a planner that's being developed. All of the pieces are either in place or soon to be in-place (especially once #5201 is merged); we just need to integrate them. This issue tracks the development of this simulation.

# The Automotive Simulation

Drake currently has an [automotive_demo](https://github.com/RobotLocomotion/drake/blob/master/drake/automotive/automotive_demo.cc) that provides a simulation consisting of a scene (i.e., [RoadGeometry](https://github.com/RobotLocomotion/drake/blob/master/drake/automotive/maliput/api/road_geometry.h)) and various vehicle models (i.e., [SimpleCar](https://github.com/RobotLocomotion/drake/blob/master/drake/automotive/simple_car.h) and [TrajectoryCar](https://github.com/RobotLocomotion/drake/blob/master/drake/automotive/trajectory_car.h)).

## Building the Simulation

Drake's build system is undergoing a transiton from being `CMake`-centric to `Bazel`-centric: #3129. Because we are in this transition period, Drake actually needs to be build twice, once using `cmake` and once using `bazel`.

First build Drake using `CMake` as described here:
http://drake.mit.edu/from_source.html#build-with-ninja

Second build Drake using `bazel` as described here:
http://drake.mit.edu/bazel.html?highlight=bazel. 

## Launching the Automotive Simulation Manually

Open a terminal and start `drake-visualizer`:

```
$ cd drake-distro
$ ./build/install/bin/drake-visualizer
```

Open a second terminal and start the simulation process:

```
$ cd drake-distro
$ ./bazel-bin/drake/automotive/automotive_demo \
    --num_trajectory_car=0 \
    --simple_car_names="mary,ann,joe"
```

Note that the comma separated list of names specifies (1) the number of user-controllable vehicles, (2) their names, and (3) the LCM channels names on which they are listing for driving commands.

For each vehicle added to the simulation, start a `steering_command_driver`, which provides a GUI for issuing throttle and steering commands to a particular vehicle. For example, the command below issues commands to the vehicle named "mary".

```
$ cd drake-distro
$ ./bazel-bin/drake/automotive/steering_command_driver --lcm_tag DRIVING_COMMAND_mary
```

## Launching the Automotive Simulation Automatically

**_N.B. The commands in this section will only work after #5304 is merged._**

Drake provides the following script for launching the various processes related to an automotive simulation: [drake/automotive/automotive_demo.py](https://github.com/RobotLocomotion/drake/blob/master/drake/automotive/automotive_demo.py).

```
$ cd drake-distro
$ bazel run //drake/automotive:demo -- \
    --no-steering-command-driver \
    --num_trajectory_car=0 \
    --simple_car_names="mary,ann,joe"
```

The command above will launch the visualizer, simulation, and tools like `lcm-spy`. Note that the `--no_steering_command_driver` is necessary due to #5291, which is being resolved by #5304. 

To drive the vehicles around, you will need to manually start instances of the `steering_command_driver` as described in the "Launching the Automotive Simulation Manually" section.

**Comment by kunimatsu-tri** [comment]
Things not implemented but necessary from RgbdCamera side are:

- Camera pose update functionality
- Label image output functionality

@StephenMcGill-TRI agreed that these functionalities will not necessarily be merged to master by the time he needs (the week of Feb 27).

**Comment by StephenMcGill-TRI** [comment]
pip install pygame

**Comment by kunimatsu-tri** [comment]
One important note: `RgbdCamera` is only supported by `CMake`, not `Bazel`.

**Comment by kunimatsu-tri** [comment]
FYI, now above two features related to `RgbdCamera` merged to Drake master! You don't need to use my branch anymore.

**Comment by liangfok** [comment]
I'm going to close this issue for now until we have the cycles to carry it forward.
