### ISSUE TITLE
Need to Update automotive_demo.py with --no-steering-command-driver Option

### ISSUE THREAD

**Issue by liangfok** [RobotLocomotion/drake#5291]
When launching a simulation with more than one `SimpleCar`, the automatically-launched `steering_command driver.py` does not work because the LCM channel topic on which the `SimpleCar` vehicles are listening is not what the `steering_command_driver.py` expects. Instead of executing multiple `steering_command_driver.py` instances, once for each `SimpleCar`, I think it would make more sense to allow the user to launch them manually. That would allow the user to bind different `steering_command_driver.py` to different keyboards and/or joysticks.

**Comment by jwnimmer-tri** [comment]
Users who want this can fix it themselves.  I volunteer to review the PR, but we won't need it within the team.  (They can also just run the automotive_demo binary directly, and whatever drivers they want after that.)
