### ISSUE TITLE
LeafSystem::AllocateOutput should be final

### ISSUE THREAD

**Issue by RussTedrake** [RobotLocomotion/drake#5344]
Digging around to decide on the implementation details for #5343, I was troubled to see the existence of both `AllocateOutput` and `AllocateOutputVector` for `LeafSystem`.  Based on my quick inspection, it seems that if a derived system overloads only `AllocateOutput` because it has a special type, then calls to `AllocateOutputVector` could do the wrong thing, and I don't see any guarantee that `AllocateOutputVector` won't be called (it is `protected`).  

I *think* that `AllocateOutput` should be declared final in `LeafSystem`, enforcing that derived classes only overload `AllocateOutputVector`.

**Comment by jwnimmer-tri** [comment]
Since both `AllocateOutputAbstract` and `AllocateOutputVector` exist, subclasses should be able to do all they need by overriding one of both of those, so yes I agree that we should make `AllocateOutput` final.

**Comment by david-german-tri** [comment]
Yeah, I agree; this is an artifact from before `AllocateOutput{Vector,Abstract}` existed.
