### ISSUE TITLE
remove ipopt_solver hard coded options

### ISSUE THREAD

**Issue by hongkai-dai** [RobotLocomotion/drake#5350]
In https://github.com/RobotLocomotion/drake/blob/master/drake/solvers/ipopt_solver.cc#L493~#L498, ipopt hard coded options for optimality tolerance, constraint violation tolerance, etc. It should listen to `MathematicalProgram::SetSolverOption` instead.

**Comment by sammy-tri** [comment]
SetSolverOption can still override these values (see the code immediately after starting at line 500).  IIRC, I found that as defaults these tended to deliver better results on our tests than the IPOPT defaults.

**Comment by jwnimmer-tri** [comment]
Fixed by #10066.
