### ISSUE TITLE
Mysterious CI Error: Failed to Generate Java Binding for an LCM Message - Bad source File

### ISSUE THREAD

**Issue by liangfok** [RobotLocomotion/drake#5356]
# Example Error

```
23:28:07 /home/ubuntu/workspace/linux-xenial-gcc-experimental-open-source/build/drake/lcmtypes/drake/lcmt_viewer_link_data.java:17: error: cannot access lcmt_viewer_geometry_data
23:28:07     public drake.lcmt_viewer_geometry_data geom[];
23:28:07                 ^
23:28:07   bad source file: /home/ubuntu/workspace/linux-xenial-gcc-experimental-open-source/build/drake/lcmtypes/drake/lcmt_viewer_geometry_data.java
23:28:07     file does not contain class drake.lcmt_viewer_geometry_data
23:28:07     Please remove or make sure it appears in the correct subdirectory of the sourcepath.
```

# Initial Analysis

The error occurred at time 23:28:07. The missing file was generated one second earlier at time 23:28:06: 

```
23:28:06 [ 10%] Generating drake_lcmt_viewer_geometry_data.h, drake_lcmt_viewer_geometry_data.c, drake/lcmt_viewer_geometry_data.hpp, drake/lcmt_viewer_geometry_data.py, drake/lcmt_viewer_geometry_data.java
```

Oddly, in a [working build](https://drake-jenkins.csail.mit.edu/job/linux-xenial-gcc-experimental-open-source/1205), the generation of `lcmt_viewer_geometry_data.java` appears twice.

# Example logs

- https://drake-jenkins.csail.mit.edu/job/linux-xenial-gcc-experimental-open-source/1204

**Comment by david-german-tri** [comment]
@stonier This is a tracking issue for a CI flake. In my view, no action is required, and it will likely be moot after CMake is turned down.
