### ISSUE TITLE
Kuka_plan_runner needs encapsulation in a LeafSystem

### ISSUE THREAD

**Issue by naveenoid** [RobotLocomotion/drake#5376]
While a stop-gap measure, it will accomplish Spiral 1 of #5371

**Comment by patmarion** [comment]
We use plan runner on the kuka hardware, so please let me know if you plan to modify plan runner in a way that might impact its usage.

**Comment by naveenoid** [comment]
Actually looks like #5380 will take care of my needs. Wouldnt have affected the hardware work in anycase but thanks for noting!
