### ISSUE TITLE
SAN builds in production

### ISSUE THREAD

**Issue by david-german-tri** [RobotLocomotion/drake#5378]
From f2f and Slack discussion, we should:

- Promote the existing lsan build to pre-merge
- Promote the existing asan build to Continuous Production
- Create Bazel lsan and asan builds, and trial them in nightly

All of this is clang-only, I think.

**Comment by BetsyMcPhail** [comment]
linux-clang-experimental-memcheck-lsan has been promoted to pre-merge

**Comment by BetsyMcPhail** [comment]
linux-clang-continuous-memcheck-asan has been added to Continuous Production

**Comment by jamiesnape** [comment]
Completed by @m-chaturvedi over many months earlier this year.
