### ISSUE TITLE
Cold start, mex-related segfault

### ISSUE THREAD

**Issue by gizatt** [RobotLocomotion/drake#538]
Running MATLAB 2014a, if I fire up MATLAB, run addpath_drake, and then running runAtlasBalancing causes a segfault with message:
Inconsistency detected by ld.so: dl-close.c: 762: _dl_close: Assertion `map->l_init_called' failed!

For me, running pelvisMotionControlMex from the MATLAB command line after addpath_drake but before anything else resolves this, even though the call to pelvisMotionControlMex does nothing but throw a syntax error.

When stepping through, I see the crash very soon after the function RigidBodyManipulator/getMexModelPtr returns. This is called (through a TSRBM wrapper) in QPController.m by
obj.mex_ptr = SharedDataHandle(QPControllermex(0,obj,obj.robot.getMexModelPtr.ptr,getB(obj.robot),r.umin,r.umax,terrain_map_ptr));

**Comment by RussTedrake** [comment]
@gizatt , @mattantone -- have you seen this recently?  perhaps it's finally resolved?

**Comment by gizatt** [comment]
The error paths described here seem to be resolved. I think the DRC side has been plagued by a very similar looking (also dl_close) error associated with the TSRBM that we've been fixing by replacing '''model.gurobi_present = checkDepedency('gurobi');''' with '''model.gurobi_present = true;''', though.

**Comment by RussTedrake** [comment]
confirmed that this was resolved by #1050.
