### ISSUE TITLE
Address object slicing enabled by Geometry copy constructor and clone() method

### ISSUE THREAD

**Issue by gizatt** [RobotLocomotion/drake#5422]
The copy constructor in Geometry makes it possible to unintentionally slice Geometry subclasses into generic Geometry instances, losing shape-specific information. (For a near-case, see comments in `rigid_body_tree_face_extraction_test.cc` in #5248.) It's currently in-use in the clone() method, and by users of Geometry.

Pointed out by @david-german-tri

**Comment by jwnimmer-tri** [comment]
@sherm1 can you manage the assignee of this issue?

**Comment by SeanCurtis-TRI** [comment]
It makes the most sense to roll this into GeometryWorld.

**Comment by jwnimmer-tri** [comment]
This issue is about the RBT code, in the attic. We're not going to fix it, it's okay to leave it slightly brittle.
