### ISSUE TITLE
Unavailable function oldrrt 

### ISSUE THREAD

**Issue by zamzami** [RobotLocomotion/drake#5426]
I wanted to test the kinodynamic version of RRT which is supposedly implemented as `oldrrt` and employed in[ `pendulum_rrt`](https://github.com/RobotLocomotion/drake/blob/master/drake/examples/Pendulum/dev/runRRT.m). However, it appears that it doesn't exist anymore. I can only find the geometrical RRT version in [`MotionPlanningTree`](https://github.com/RobotLocomotion/drake/blob/master/drake/matlab/solvers/MotionPlanningTree.m). 

Is it still possible to find the old implementation somewhere?

**Comment by hongkai-dai** [comment]
I am afraid that code is gone. And we are not maintaining the MATLAB code at the moment.
