### ISSUE TITLE
Binary package of LCM and LCM Types for Windows (py)

### ISSUE THREAD

**Issue by david-german-tri** [RobotLocomotion/drake#5447]
From @RussTedrake: It would be nice to have a small downloadable artifact that allows you to write Python programs that send and receive Drake's LCM messages on Windows.

**Comment by EricCousineau-TRI** [comment]
Closing this, as Windows is not on the roadmap for supported platforms.

**Comment by jamiesnape** [comment]
(Note this issue post-dates dropping Windows support and was separate from Drake support. Probably check in with @RussTedrake, if you have not already done so.)

**Comment by RussTedrake** [comment]
It might always be a “nice to have”, but totally fine to close it.  Thanks for checking!
