### ISSUE TITLE
LeafSystem should support model-value based parameter allocation

### ISSUE THREAD

**Issue by jwnimmer-tri** [RobotLocomotion/drake#5465]
Just like #5431, but for parameters.

**Comment by david-german-tri** [comment]
I have a bunch of in-progress code for #5072.  Can this wait until that lands?  (Next few days)

**Comment by jwnimmer-tri** [comment]
Definitely.

**Comment by jwnimmer-tri** [comment]
@david-german-tri While this is fresh in your head, do you want to take over this fixup?

**Comment by david-german-tri** [comment]
Sure, but no promises about when I get to it.

**Comment by jwnimmer-tri** [comment]
WIP at https://github.com/jwnimmer-tri/drake/tree/framework-model-params
