### ISSUE TITLE
Rename AbstractState and DiscreteState

### ISSUE THREAD

**Issue by david-german-tri** [RobotLocomotion/drake#5490]
Since these are used for both Parameters and State, we should call them something more generic.  @sherm1 suggests `AbstractValues` and `DiscreteValues`, which I like.

**Comment by naveenoid** [comment]
Why not "AbstractParameters" and "AbstractState" ? I realise this comment is a bit late though..

**Comment by david-german-tri** [comment]
There's a single object, now called `AbstractValues`, which is a bag of `AbstractValue` that may or may not be owned.  We use this object to implement both abstract parameters and abstract state, in both diagrams and leaf systems.

**Comment by naveenoid** [comment]
Ah issue text parsing fail..Got it!
