### ISSUE TITLE
Cannot construct Atlas model using pydrake bindings

### ISSUE THREAD

**Issue by rdeits** [RobotLocomotion/drake#5520]
```python
import pydrake.rbtree as rbt
robot = rbt.RigidBodyTree("/home/rdeits/locomotion/drake-distro/drake/examples/Atlas/urdf/atlas_minimal_contact.urdf")
```

gives:

```
RuntimeError: /home/rdeits/locomotion/explorations/drake-mpc/build/drake-prefix/src/drake/drake/multibody/parsers/urdf_parser.cc: ParseGeometry: ERROR: Mesh file name could not be resolved from the provided uri "package://Atlas/urdf/meshes/r_clav.obj".
```

It looks like that constructor needs to be updated to use the package path. I'll look into it.

**Comment by liangfok** [comment]
See `drake/multibody/parsers/package_map.h`, specifically methods `PopulateFromFolder()`,  `PopulateFromEnvironment()`, and `PopulateUpstreamToDrake()`, which might be helpful towards the resolution of this issue.

**Comment by rdeits** [comment]
Yup, thanks @liangfok . That's all working; I just have to figure out how to deal with the way non-copyable types play with pybind11.
