### ISSUE TITLE
Incorporate ability to express velocities within PoseAggregator. 

### ISSUE THREAD

**Issue by jadecastro** [RobotLocomotion/drake#5538]
This is needed for #5113 and #5288.

**Comment by liangfok** [comment]
Will there be a "FrameVelocityBundle" that's analogous to `PoseVector`'s `PoseBundle`?

(I'm thinking about this in #5541.)

**Comment by SeanCurtis-TRI** [comment]
FWIW `GeometryWorld` bundles up frame kinematics: pose, velocity, and acceleration. (And the clock is ticking.... :clock11:

**Comment by jadecastro** [comment]
Addressed by #5609.
