### ISSUE TITLE
Installation issue with ros_common_test: undefined reference to testing::internal::EqFailure(..) 

### ISSUE THREAD

**Issue by orsoromeo** [RobotLocomotion/drake#5579]
I am currently trying to install drake on my PC following the instructions on [http://drake.mit.edu/from_source.html](url) trying to build it as a ROS catkin Package. My PC runs Ubuntu 14.04 and has ROS Indigo installed. 

"catkin build" gives me the following error:

> Errors     << drake_ros_common_test:make /home/user/drake_catkin_workspace/logs/drake_ros_common_test/build.make.001.log           
CMakeFiles/parameter_server_test.dir/test/parameter_server_test.cc.o: In function CmpHelperEQFailure<bool, bool>':
/home/user/drake_catkin_workspace/install/include/gtest/gtest.h:1382: undefined reference to testing::internal::EqFailure(char const*, char const*, std::string const&, std::string const&, bool)'
CMakeFiles/parameter_server_test.dir/test/parameter_server_test.cc.o: In function __static_initialization_and_destruction_0':

and:

> Errors drake_ros_systems:make /home/user/drake_catkin_workspace/logs/drake_ros_systems/build.make.001.log                                                                                                                      
CMakeFiles/ros_test.dir/test/ros_test.cc.o: In function __static_initialization_and_destruction_0:
/home/user/drake_catkin_workspace/src/drake_ros_integration/drake_ros_systems/test/ros_test.cc:10: undefined reference to `testing::internal::MakeAndRegisterTestInfo(char const*, char const*, char const*, char const*, testing::internal::CodeLocation, void const*, void (*)(), void (*)(), testing::internal::TestFactoryBase*)'
collect2: error: ld returned 1 exit status

Here is a screenshot of the same issue:

![drakeissue](https://cloud.githubusercontent.com/assets/14978496/24145435/617b5582-0e31-11e7-9e8b-9d40e0abc1f4.png)

These are other details that relate to my computer environment:
Distributor ID: Ubuntu
Description: Ubuntu 14.04.1 LTS
Release: 14.04
Codename: trusty

MATLAB 9.0.0.341360 (R2016a)
ROS: Indigo
CMake: 3.7.2

gcc: 4.9.4
g++: 4.9.4
gfortran: 4.9.4

Thanks in advance for your help.

**Comment by jwnimmer-tri** [comment]
All issues must have owners; feel free to reassign elsewhere as needed (or close), etc.
