### ISSUE TITLE
LCM failing on new drake installation (Was an OSX 10.10 Yosemite issue with IPV6)

### ISSUE THREAD

**Issue by peteflorence** [RobotLocomotion/drake#558]
Getting following error after calling LCM to set up visualizer outside of MATLAB:

"LC singleton fail: java.net.SocketException: Can't assign requested address"

Some notes:
- Running MATLAB 2013b on Yosemite
- Fresh install of drake from last night was working fine
- Not sure what changed between last night and today, but anything calling lcm to set up the visualizer now crashes MATLAB
- After the above error message, MATLAB instantly crashes
- Captured screenshot below of error message

![lcmissue](https://cloud.githubusercontent.com/assets/5640360/5050138/a6d12094-6bf9-11e4-9788-5d7a041043d8.png)

**Comment by tkoolen** [comment]
Thanks for the detailed description @peteflorence, I had to do this again and your comment was very helpful.

**Comment by peteflorence** [comment]
Glad it was helpful @tkoolen  !

**Comment by RussTedrake** [comment]
:+1:  -- just ran into this on the build server and luckily googling for a solution took me right back to this page.  :)  thanks again @andybarry and @peteflorence

**Comment by peteflorence** [comment]
Glad it helped!

**Comment by peteflorence** [comment]
Added Yosemite and IPV6 to the title to help people find this, seems to keep coming up

**Comment by DiitsGp** [comment]
I got this error again today. It went away after I re-opened MATLAB, but I thought I'd let you know that somehow this can still happen...here's a screenshot of my java.opts file

![image](https://cloud.githubusercontent.com/assets/8225776/9140190/4ec7a726-3cfd-11e5-8d9d-8e509e46b7ee.png)

**Comment by tkoolen** [comment]
Do you have two versions of Matlab maybe?

**Comment by DiitsGp** [comment]
No, just a single install of R2014b. I couldn't replicate the problem so it's probably nothing to worry about, I just found it curious that LCM path thing happened again.

**Comment by liangfok** [comment]
Can LCM be updated to support IPv6?

**Comment by RussTedrake** [comment]
You could post this to the lcm issue page...?

**Comment by liangfok** [comment]
Done: https://github.com/lcm-proj/lcm/issues/59

**Comment by pvarin** [comment]
My installation of Matlab (R2016a for maci64) didn't come with a java.opts file and I was having trouble with getting Matlab to read my java.opts file from the $MATLABROOT/bin/$ARCH directory, so I symlink-ed it to the startup directory (which can be found by running the `userpath` command from the Matlab command line) and it seemed to work.
