### ISSUE TITLE
Count number of times integrator calculated derivatives.

### ISSUE THREAD

**Issue by mitiguy** [RobotLocomotion/drake#5581]
To be able to test integrator performance, it is helpful to know how many times
(integer count) the time-derivatives of the states are calculated.

This is also helpful for testing - where these numbers should be relatively
constant for each benchmark test as he entire code base evolves.
If the number changes significantly, it should be a well-understood 
phenomenon that caused it (e.g., a model of friction changed).

Note: This feature request is specific to numerical integration.
It is unrelated to the system architecture (e.g., unrelated to
system code such as input or output ports).

**Comment by sherm1** [comment]
:+1: In general the integrators (& Simulator) should be instrumented to count everything they do that is remotely interesting.

**Comment by edrumwri** [comment]
This feature was implemented loooong ago.
