### ISSUE TITLE
Retrieve solver time from MathematicalProgram

### ISSUE THREAD

**Issue by rdeits** [RobotLocomotion/drake#5594]
It would be nice to be able to retrieve the time spent in the solver (excluding the time spent setting up the problem in Drake), for benchmarking and comparing different solvers. 

cc @TobiaMarcucci

**Comment by jwnimmer-tri** [comment]
All issues must have owners; feel free to reassign elsewhere as needed (or close), etc.

**Comment by hongkai-dai** [comment]
For solvers like Mosek and Gurobi which report the solver time, we can retrieve the time information form MosekSolverDetails or GurobiSolverDetails.
