### ISSUE TITLE
MathematicalProgram does not error if constraints are added with Bindings to non-decision variables

### ISSUE THREAD

**Issue by RussTedrake** [RobotLocomotion/drake#5623]
I was hoping that if I called `AddCost(Expression)`, where my Expression contains variables that had nothing to do with the MathematicalProgram, the AddCost would throw an error.  It does not.  

Is this a reasonable error to catch?  I know we have a lot of entry points for costs/constraints.  Where is the right place to do this check?

**Comment by hongkai-dai** [comment]
I will work on this. We probably need to do this check in each `AddConstraint(Binding<T>)`, where the `Binding` contains the variables bound to this constraint.

**Comment by RussTedrake** [comment]
This appears to be resolved.  I’ve added a test case for it in #6850.
