### ISSUE TITLE
Failed to extract MATLAB_ROOT

### ISSUE THREAD

**Issue by baxelrod** [RobotLocomotion/drake#564]
There seems to be an issue related to the mex/cmake studd. 
In particular with line 85 of drake/cmake/mex.cmake in the LCM and Master branchs.

I get the following error, and was able to fix it by editing the grep expression on line 85:

Failed to extract MATLAB_ROOT

This is on an athena ubuntu 12.04 machine.

**Comment by RussTedrake** [comment]
i believe this is now long resolved.
