### ISSUE TITLE
Make sure each type of constraint can be added in the symbolic form

### ISSUE THREAD

**Issue by hongkai-dai** [RobotLocomotion/drake#5650]
I believe currently the only left-over is the `AddBoundingBoxConstraint`.

**Comment by hongkai-dai** [comment]
\cc @RussTedrake 
\cc @EricCousineau-TRI

**Comment by soonho-tri** [comment]
@hongkai-dai : I'll do this today (just unassinged you).

**Comment by hongkai-dai** [comment]
Thanks a lot! You may hold off the part on the polynomial constraint. I will send out a PR later to handle it. We currently do not have a `std::vector<Binding<PolynomialConstraint>>` stored inside `MathematicalProgram`. I think we should add that, with the proper test. But the change would be easier to review if it is in a separate PR. What do you think?

**Comment by soonho-tri** [comment]
SGTM.

I'll add the following functions:
```c++
Binding<LinearEqualityConstraint> AddLinearEqualityConstraint(const symbolic::Formula& f);
Binding<BoundingBoxConstraint> AddBoundingBoxConstraint(const symbolic::Formula& f);
```
so that we can write `AddLinearEqualityConstraint(A*x == b)` and `AddBoundingBoxConstraint(A*x <= b)`.

For the latter, I first need to add `operator<=` between `Eigen::Matrix` of symbolic expressions.
