### ISSUE TITLE
common/test/cpplint_wrapper.py assumes cmake

### ISSUE THREAD

**Issue by RussTedrake** [RobotLocomotion/drake#5665]
by virtue of looking for `drake-distro/externals/google_styleguide/cpplint`...

my bazel-only (so far) install doesn't have it.

cc @jwnimmer-tri

**Comment by liangfok** [comment]
Here's a relevant discussion on Slack: https://drakedevelopers.slack.com/archives/C2PMBJVAN/p1486752341001077

Basically, `cpplint` is run when running `bazel test ...`.

**Comment by jwnimmer-tri** [comment]
http://drake.mit.edu/code_style_tools.html#cpplint has the details.  Maybe the error message could be improved, though.

**Comment by RussTedrake** [comment]
great.  i knew it was run from bazel test.  i'm happy with the documentation.
