### ISSUE TITLE
`TestQPonUnitBallExample` inadvertently permits different solver to be dispatched via `MathematicalProgram::Solve`

### ISSUE THREAD

**Issue by EricCousineau-TRI** [RobotLocomotion/drake#5673]
Ran into an issue where `//drake/solvers:ipopt_solver_test` was failing on `QPtest.TestUnitBallExample` (with `kUnknownError`). Hongkai and Sammy tried it out on their machine, and it worked, and Hongkai pointed to a CI machine that also had not had any issues.

Issue ended up being that I set `--config everything` in my `~/.bazelrc` on just this machine, but had not yet installed a Mosek license, so when running the test, it selected the Mosek solver here:
https://github.com/RobotLocomotion/drake/blob/4ee2b61/drake/solvers/test/quadratic_program_examples.cc#L416
We saw this when running the test under valgrind:
```
$ bazel run --run_under='valgrind --tool=memcheck --leak-check=full' //drake/solvers:ipopt_solver_test
```

Sammy suggested changing this to use `RunSolver`, and that worked. Will submit a PR soon.

/cc @sammy-tri 
/cc @hongkai-dai

**Comment by hongkai-dai** [comment]
Thanks for looking into it!
