### ISSUE TITLE
Replace Integer Vehicle ID With a type-safe Identifier.

### ISSUE THREAD

**Issue by liangfok** [RobotLocomotion/drake#5698]
`AutomotiveSimulator` assigns each vehicle instance an integer ID. For increased robustness, these should be replaced with a type-safe identifier:

http://drake.mit.edu/doxygen_cxx/classdrake_1_1geometry_1_1_identifier.html#details

Original comment: https://reviewable.io/reviews/RobotLocomotion/drake/5679#-Kgg2tCUt01rpMEc0NiR

**Comment by jwnimmer-tri** [comment]
Seems fine without.
