### ISSUE TITLE
MonolaneOnrampMerge Needs to be Generalized

### ISSUE THREAD

**Issue by liangfok** [RobotLocomotion/drake#5707]
# Problem Definition

[MonolaneOnrampMerge](https://github.com/RobotLocomotion/drake/blob/e7f5ddcd0f51b43cdf46daae10c6f7c80b77aa34/drake/automotive/monolane_onramp_merge.h#L51) is a [RoadGeometry](https://github.com/RobotLocomotion/drake/blob/6e211f0b03331e6d73a32127927067e2de4f12be/drake/automotive/maliput/dragway/road_geometry.h#L23) generator for on-ramp merge scenarios. Example screenshots are available in #5169 and #5699. The problem is `MonolaneOnrampMerge` is not very flexible in terms of allowing users to specify  properties like the merge angle or distance over which a lateral lane change could occur. This makes it difficult to generate on-ramp scenarios that match a particular real-world scenario.

# Suggested Course of Action

Survey the various on-ramp merge geometries that exist in the real world. Identify parameters that capture the variability across on-ramp merge geometries. Update `MonolaneOnrampMerge` to accept these parameters so users can generate desired realistic on-ramp merge scenarios.

Another possibility is we end up not using `monolane` due to lack of expressiveness and wait for a more expressive road geometry framework like one based on splines, Bezier curves, or Euler spirals, etc.

**Comment by jadecastro** [comment]
Our only use cases for `MultilaneOnrampMerge` are a few unit tests and static demo code, so no need to generalize it.
