### ISSUE TITLE
IiwaPlanSource feedthrough fix needed

### ISSUE THREAD

**Issue by naveenoid** [RobotLocomotion/drake#5736]
The current IiwaPlanSource performs a read of the input ports at the DoCalcOutput method which leads to it becoming a direct feedthrough system. This can perhaps be avoided in a manner similar to the experimental IiwaStateFeedbackPlanSource by moving the input port value to the AbstractState and updated at DoCalUnrestrictedUpdate.

**Comment by sammy-tri** [comment]
Closed in #5916
