### ISSUE TITLE
Move Modeling Files Created by AutomotiveSimulator Into Bazel Sandbox

### ISSUE THREAD

**Issue by liangfok** [RobotLocomotion/drake#5750]
See: https://reviewable.io/reviews/RobotLocomotion/drake/5741#-Kh3DAHYsSPCGMDxzaMg

**Comment by liangfok** [comment]
Since the modeling files were created using `maliput::utility::GenerateUrdfFile()`, I think it may be best to provide a sister `maliput::utility::RemoveGeneratedUrdfFile()` that undoes the filesystem artifacts.

**Comment by jwnimmer-tri** [comment]
A better answer is to create them somewhere that is automatically cleaned up, such as the Bazel sandbox, a system location that has a janitor daemon, and/or a transient filesystem.

Having programmers match create / destroy function calls manually will never work.

**Comment by liangfok** [comment]
Thanks. I've updated the title accordingly.

**Comment by liangfok** [comment]
I'm going to close this issue because the files are currently created in `/tmp`, which is automatically cleared on our target platforms.

I briefly looked into using Bazel's `genrule()` to generate the road network files but figured I can't without explicitly enumerating and thus limiting the types of `maliput::api::RoadGeometry` objects supported. Currently, _any_ `RoadGeometry` can be passed to `AutomotiveSimulator::SetRoadGeometry()`, which then generates the URDF, OBJ, and MTL files in `/tmp`.
