### ISSUE TITLE
Provide a mathematically rigorous definition for the inertia tensor

### ISSUE THREAD

**Issue by amcastro-tri** [RobotLocomotion/drake#5765]
During the review of PR #5524 the Dynamics team discovered that the documentation for `RotationalInertia` is not accurate enough. 
The best way to eliminate the problem is providing a rigorous mathematical definition of the inertia tensor as an (contravariant/covariant?) variant of second order. The definition should be independent of the any basis (and therefore the physical concept still is valid even before the introduction of any basis) and should clearly provide the connection between angular momentum, angular velocity and kinetic energy.

**Comment by mitiguy** [comment]
I expect PR #11773 addressed issue #5765.
https://github.com/RobotLocomotion/drake/pull/11773
