### ISSUE TITLE
How does drake differ from Gazebo?

### ISSUE THREAD

**Issue by CatchMeFastFat** [RobotLocomotion/drake#5778]
First of all I don't mean to spam here, I just want to know which one I should learn as I can see that drake is going to depend on C++ only, so I want to know its pros. and cons.
I am new to both(ros/gazebo and drake).

I don't know anyother place where I can ask that question.

Thanks in advance.

**Comment by RussTedrake** [comment]
drake and gazebo both have simulation capabilities.  

gazebo wraps a number of open-source multi-body dynamics engines, where as drake implements it's own.  we are putting a considerable effort in drake to verify the accuracy of this multi-body engine... perhaps to a degree that has not been done before.  but it is still a work in progress.

drake offers considerably more tools than simply simulation.  it's designed for control design, system analysis, motion planning, etc (as described in the docs).  gazebo, does not provide these tools, but does provide considerably more features for user interface/user experience.  drake is focused on "expert" developers first.  

gazebo is a more mature project, although drake is maturing quickly.
