### ISSUE TITLE
Upgrade to Bazel 0.4.5

### ISSUE THREAD

**Issue by david-german-tri** [RobotLocomotion/drake#5781]
[Bazel 0.4.5](https://github.com/bazelbuild/bazel/releases/tag/0.4.5) provides some useful stuff, especially the `environ` parameter to `repository_rule`, which resolves [this TODO in gurobi.bzl](https://github.com/RobotLocomotion/drake/blob/c4980b854aa751692c4b46740fd052e655056fd9/tools/gurobi.bzl#L8-L9).  

I believe #5762 fixed our last 0.4.5 backwards-compatibility issue - I've been beta-testing 0.4.5 on Linux for the past week with no problems, and @soonho-tri says it's working on Mac too.  So, let's upgrade the CI images, Xenial script, and documentation.

**Comment by BetsyMcPhail** [comment]
CI images (Trusty, Xenial and OS X) have been updated. 

Documentation and Unprovisioned script updates coming shortly.

**Comment by david-german-tri** [comment]
Fixed in #5808 - thanks!
