### ISSUE TITLE
Fail fast on unsupported Bazel versions

### ISSUE THREAD

**Issue by david-german-tri** [RobotLocomotion/drake#5792]

**Comment by jamiesnape** [comment]
Partially related to https://github.com/RobotLocomotion/drake/issues/5744.

**Comment by jwnimmer-tri** [comment]
All issues must have owners; feel free to reassign elsewhere as needed (or close), etc.

**Comment by jamiesnape** [comment]
Protobuf uses this: https://github.com/google/protobuf/commit/35119e39a07f426f3c48a1bfb41d862994223742#diff-14e64c3c0a0449ceb162062b8291fa19
