### ISSUE TITLE
Integer statistics in IntegratorBase should be of type int64_t

### ISSUE THREAD

**Issue by edrumwri** [RobotLocomotion/drake#5798]
Two billion evaluations (MAX_INT) is unlikely but possible for long-running simulations.

**Comment by amcastro-tri** [comment]
Originated from [this comment](https://reviewable.io/reviews/robotlocomotion/drake/5575#-Kh8onqxZqZN7q4L-hMP) in a PR review.

**Comment by jwnimmer-tri** [comment]
This issue appears to be resolve on master; if you agree, please close it.

**Comment by edrumwri** [comment]
Issue has been resolved.
