### ISSUE TITLE
adding per step actions to system (Publish / State updates)

### ISSUE THREAD

**Issue by siyuanfeng-tri** [RobotLocomotion/drake#5825]
here is a draft. https://github.com/siyuanfeng-tri/drake/commit/cd9504f9d55f85b68e9f3e82cdac9a1d4d0d3d5c

it has lots of duplicate code and stuff, but the idea should be clear. 
if @sherm1 @david-german-tri @jwnimmer-tri @edrumwri don't have major objections, i am gonna work on a pr.

**Comment by sherm1** [comment]
Resolved by #5861.
