### ISSUE TITLE
Provide a package for downstream users of Python bindings

### ISSUE THREAD

**Issue by david-german-tri** [RobotLocomotion/drake#5843]
The #5700 Bazel build is only friendly to Bazel consumers.  The `package_drake.sh` tarball should include python binding sources that are easy for downstream projects to use regardless of build system.

cc @rdeits FYI

**Comment by stonier** [comment]
Users are Russ' lab and the CAM manipulation group (for writing scripts that run in director).

**Comment by EricCousineau-TRI** [comment]
Closed, given that `pydrake` is included in packaged releases.
