### ISSUE TITLE
Integrator tests need to use 

### ISSUE THREAD

**Issue by edrumwri** [RobotLocomotion/drake#5844]
A PR is in the works (#5575) that has added closed form solutions to the mass-spring system (and adds another one for a mass-spring-damper system). Code that duplicates the closed-form solution for the mass-spring system needs to be removed from integrators and use this code instead, once this PR is merged.

**Comment by jwnimmer-tri** [comment]
All issues must have owners; feel free to reassign elsewhere as needed (or close), etc.

**Comment by sherm1** [comment]
Integrator tests have been re-engineered since this was filed. Closing.
