### ISSUE TITLE
testIndividualCentersOfPressure fails

### ISSUE THREAD

**Issue by RussTedrake** [RobotLocomotion/drake#585]
i believe it fails reliably, even though it looks like it's numerically close:

Site: DRAKE003
Build Name: precompiled-RobotLocomotion-master
Build Server Directory: C:\cygwin64\tmp\drake-precompiled-12095\drake
CDash: http://kobol.csail.mit.edu/cd/index.php?project=Drake&date=20141127

Most recent commits to drake included in this build:
```
4367981 Merge pull request #581 from RussTedrake/wintests
aa88877 update cmake.  hopefully works for all this time.
ee44891 update cmake
9feda7b update cmake
96abcc9 another attempt at cmake builds for all platforms
```

examples/Atlas/test/testIndividualCentersOfPressure (unknown issue)
```
error_id = Drake:ValueCheck
error_message = Values don't match.  Expected 
[-1.3505484925705 -1.90034872665083;1.60086581345863
1.61466215190119;-9.80153558935972 -9.29230038365085]
but got 
[-1.45661172175738 -1.98643902446545;1.64631043532796
1.63446299810698;-9.81134875986639 -9.34511885116823]
is_segfault = 0
```

<matlab_test>strcmp(test_name,'examples/Atlas/test/testIndividualCentersOfPressure') && strcmp(error_id,'Drake:ValueCheck')</matlab_test>

**Comment by tkoolen** [comment]
Should we just get rid of this functionality? It was kind of tied to how the Atlas controller was set up, but it's currently not being used in drc anymore. I would keep resolveCenterOfPressure, which has a nice clean list of method arguments but throw away anything related to individualCentersOfPressure.

**Comment by tkoolen** [comment]
Note to self: individualCentersOfPressure assumes B is in body frame while it's in world frame.
