### ISSUE TITLE
Support disjunctive constraints

### ISSUE THREAD

**Issue by soonho-tri** [RobotLocomotion/drake#5851]
Feature requested by @RussTedrake.

1. For now, `MathematicalProgram` has a conjunction of constraints (internally represented as vectors of different types of `Binding<Constraint>`s.

    `c1 ∧ ... ∧ cn`

2. We can extend it to have constraints in a mathematical program in CNF (conjunctive normal form).
```
        c1 ∧ ... 
    ∧ (c_{i, 1} ∨ ... ∨ c_{i, m}) 
    ∧ (c_{i + 1, 1} ∨ ... ∨ c_{i + 1, m}) ∧ ...
    ∧ cn
```
3. To implement this extension, we need to the followings:

    - A. Add a private member `vector<vector<Binding<Constraint>>> disjunctive_constraints_;` to Mathematical Program.

    - B. Add a public method `AddDisjunctiveConstraint(const Formula& f)`. It parses a given disjunctive formula, `f`, calls a corresponding `Add*Constraint` for each disjunct to get a Binding<Constraint>, and forms a vector<Binding<Constraint>> representing a disjunction of constraint.

    - C. Add a public method `vector<vector<Binding<Constraint>>> disjunctive_constraints() const` to get a list of disjunctions in mathematical program.

    - D. Implement the disjunctive constraint for various solvers, using something like the min formulation.

Note that the step 3.B. requires generic parsing functionality of symbolic expressions, which I am working on currently. When it's done, I will move on to this item.

/cc @hongkai-dai @EricCousineau-TRI

**Comment by jwnimmer-tri** [comment]
@soonho-tri or @RussTedrake Is this issue still relevant to any ongoing work correctly?  If not, maybe close it?
