### ISSUE TITLE
Gurobi license has expired in CI

### ISSUE THREAD

**Issue by david-german-tri** [RobotLocomotion/drake#5862]
Until the license is restored, I'm going to disable all tests that require Gurobi.

**Comment by david-german-tri** [comment]
#5863 revealed the need for #5864.

**Comment by david-german-tri** [comment]
#5863 appears likely to resolve the emergency - CI is returning green so far.

Follow-up actions:

- [ ] Lift the current moratorium on merges.  @david-german-tri
- [ ] Install a new Gurobi license in CI.  @RussTedrake to obtain, @BetsyMcPhail to install.
- [ ] Revert #5863.  @BetsyMcPhail after installing.
- [ ] Create a reproducing test case for the probable Bazel bug in #5864, and file it.  @david-german-tri

**Comment by david-german-tri** [comment]
Done with my tasks on this issue - remaining items are for @BetsyMcPhail, following up with @RussTedrake as needed.

**Comment by RussTedrake** [comment]
Resolved a few weeks back
