### ISSUE TITLE
Reimplement inverseKin interfaces

### ISSUE THREAD

**Issue by EricCousineau-TRI** [RobotLocomotion/drake#5869]
Re-purposing this to track the re-implementation of inverse kinematics to use MathematicalProgram interface and MBP

Legacy:

Per Hongkai's and Sammy's prior discussions, the present implementations of `inverseKin` / `inverseKinTraj` do not meet coding standards, and the `RigidBodyConstraint` setup should be deprecated and the `solvers::Constraint` setup should be used instead.

Additional items:
* #3675 - No access to the `MathematicalProgram`[s] used to solve the problem.
* `infeasible_constraints` are no longer returned by the present implementation.
* `info` goes through semi-redundant mapping: from `inverseKin(...): SolutionResult result = prog.Solve();`, it is mapped to SNOPT-style codes at `inverseKin(...): info[t_index] = GetIKSolverInfo(prog, result);`.
    * If this is for maintain MATLAB backwards-compatibility, this can be addressed within the wrapper.
* _Will add more as they come up..._

\cc @hongkai-dai @sammy-tri @siyuanfeng-tri

**Comment by RussTedrake** [comment]
In particular, we've discussed implementing inverseKinTraj as a trajectory optimization (using dircol, etc) on a kinematic-only version of rigid body plant.  @avalenzu did a version of this in matlab, and we liked it a lot.  See, e.g. http://drake.mit.edu/doxygen_matlab/class_kinematic_dirtran.html

**Comment by jwnimmer-tri** [comment]
All issues must have owners; feel free to reassign elsewhere as needed (or close), etc.

**Comment by EricCousineau-TRI** [comment]
@hongkai-dai @avalenzu I believe y'all are already handling this. Should I close this if we have another tracking issue? If not, can I reassign one of y'all?

**Comment by avalenzu** [comment]
AFAIK, we don't have another tracking issue. Feel free to assign it to one of us.

**Comment by EricCousineau-TRI** [comment]
K, done.

**Comment by hongkai-dai** [comment]
Just saw this. I think I would like to split this issue to two parts
1. Reimplement inverse kinematics to use MathematicalProgram interface and MBP. This is related to #9341.
2. Implement kinematic trajectory optimization. I think this is related to Andres' B-spline approach. Or we can consider other approaches to interpolate the kinematic trajectory.

**Comment by avalenzu** [comment]
I'd be on board with that split, @hongkai-dai.

**Comment by tri-ltyyu** [comment]
#10188 created for the trajectory optimization.
