### ISSUE TITLE
OutputPort uses different casing than state classes

### ISSUE THREAD

**Issue by david-german-tri** [RobotLocomotion/drake#5878]
From @RussTedrake on #4184: OutputPort GetMutableData / GetMutableVectorData is inconsistent w/ get_mutable_data, etc from the state classes.

This was intended to convey that write operations on the output port invalidate cache.  Of course, so do write operations on state, so I agree there's an inconsistency.  I assume it will be resolved as part of the larger #4127 maelstrom.

**Comment by jwnimmer-tri** [comment]
These methods no longer exist on OutputPort.
