### ISSUE TITLE
Autodiff-to-matrix syntactic sugar for System Framework types

### ISSUE THREAD

**Issue by david-german-tri** [RobotLocomotion/drake#5880]
On #4012, @RussTedrake requested the following (carried over from #4021):

* `autodiffToGradientMatrix(VectorBase)`
* `autoDiffToValueMatrix(VectorBase)`

**Comment by jwnimmer-tri** [comment]
We don't want to use `VectorBase` anymore, and the #15699 family of fixes already tidied up the sugar that we do have.
