### ISSUE TITLE
addpath_snopt uses absolute path from a dev machine 

### ISSUE THREAD

**Issue by baxelrod** [RobotLocomotion/drake#589]
The addpath snopt in the latest binary release looks like this, which doesn't work without changes for me (obviously). 

function addpath_snopt()
  addpath(fullfile('/tmp/drake-precompiled-18332/snopt','matlab'));

when it's called by runPassive in KneedCompassGait. We're having some trouble finding the directory to put here.  

Thanks for releasing the SNOPT binaries by the way! Compiling SNOPT was a pain.

**Comment by RussTedrake** [comment]
i've removed addpath_snopt from the release filelist.
