### ISSUE TITLE
Need to Update PoseBundle to use PoseVector

### ISSUE THREAD

**Issue by liangfok** [RobotLocomotion/drake#5896]
It is currently using `Eigen::Isometry3`. Making `PoseBundle` use `PoseVector` has the following benefits:

1. Simplify debug `ToString()` methods.
2. Potentially unblock `PoseAggregator<symbolic::Expression>`.

Note that `PoseVector` provides `get_isometry()`, which returns an `Eigen::Isometry3`, meaning there should be no loss in capability by this switch.

For more background, see: https://drakedevelopers.slack.com/archives/C2CHRT98E/p1492695320797884.

**Comment by SeanCurtis-TRI** [comment]
Closing this in lieu of #11888
