### ISSUE TITLE
title capitalization in lcm_vector_gen is off for Rod2D

### ISSUE THREAD

**Issue by edrumwri** [RobotLocomotion/drake#5906]
lcm_vector_gen wants to capitalize "rod2d" to "Rod2d", while my class is named "Rod2D". Would it be too dumb to require the caller of lcm_vector_gen to specify the state vector name that they want?

**Comment by jwnimmer-tri** [comment]
The name in which situation?  Classnames (type names) should be capitalized per google styleguide.  But maybe some other use of the name could be lowercased.

**Comment by edrumwri** [comment]
The context is indeed a classname. The google style guide states, "Type names start with a capital letter and have a capital letter for each new word, with no underscores: MyExcitingClass, MyExcitingEnum." This doesn't indicate what should be done for "2D" or "3D", as examples.

**Comment by jwnimmer-tri** [comment]
Oops, I thought the question was about the "R".  I see now its about the "D".

I think it'd be fine to allow the user to omit `--title` and instead specify `--camel` and `--snake` directly.  (I think `screaming_snake` is probably just `snake.upper()`, so should not be separately configurable.)

**Comment by edrumwri** [comment]
Ok, I'll submit a PR on that.

**Comment by jwnimmer-tri** [comment]
All issues must have owners; feel free to reassign elsewhere as needed (or close), etc.

**Comment by sherm1** [comment]
Died for lack of interest.
