### ISSUE TITLE
Systems within Diagrams should be assigned default names

### ISSUE THREAD

**Issue by jwnimmer-tri** [RobotLocomotion/drake#5934]
The restriction in #5866 is too easy for users of Diagram to violate, because the `System` constructor does not demand a name, so it's impossible to fail-fast, and you only find out at runtime that you forgot to bless you System with a name.

We should assign default names if the user left it blank, e.g., `NiceTypeName(*system) + "@" + pointer_to_string(system)`.

**Comment by sherm1** [comment]
:+1: for a default name. I'd prefer a default that was more stable than a pointer, which can change from run to run (and is ugly!). Maybe just NiceTypeName + the subsystem number?

**Comment by jwnimmer-tri** [comment]
My thought was to make it unstable _on purpose_ because it shouldn't be used for anything programmatic, or change any execution properties, etc.

**Comment by sherm1** [comment]
I thought David's motivation was to have names for diagram drawings, for which some stability would be good. My experience with default node names in the past has been that they end up getting used a lot, either out of laziness or just because it is hard to think up better names than say, `gain_1` `gain_2` and `gain_3`. Is there a downside to making the defaults somewhat palatable?

**Comment by jwnimmer-tri** [comment]
My starting position is that if you want a specific name on a drawing, debug text, etc., then you should set the name yourself.  My purpose for adding a default is for cases where nobody asks for the name ever, but the Diagram is still throwing at runtime right now from the empty names.

If we decided we wanted _stable_ default names, then I think they should just be `subsystem[0]`, `subsystem[1]`, etc., since `NiceTypeName` is only suitable for human output (its not stable).  Since the System names are likely to be abused for logic and not just diagnostics, I would prefer that they either be obviously unstable (so e.g. include the pointer as text) or obviously stable (`subsystem_0`).

**Comment by jwnimmer-tri** [comment]
WIP at https://github.com/jwnimmer-tri/drake/tree/framework-default-system-names
