### ISSUE TITLE
gurobi on mac requires gfortran

### ISSUE THREAD

**Issue by RussTedrake** [RobotLocomotion/drake#5935]
but installation instructions don't instruct users to install it.  
```
ERROR: /private/var/tmp/_bazel_russt/3e477aa1673e9c80e91d410bb65d1970/external/ipopt/BUILD.bazel:128:1: no such package '@gfortran//': Traceback (most recent call last):
	File "/Users/russt/drake-distro/tools/gfortran.bzl", line 30
		_find_library(repository_ctx, libgfortran)
	File "/Users/russt/drake-distro/tools/gfortran.bzl", line 7, in _find_library
		repository_ctx.execute([gfortran, "--print-file-name=" ...])
Argument 0 of execute is neither a path nor a string. and referenced by '@ipopt//:lib'.
```
We should either add `brew install gcc` to http://drake.mit.edu/mac.html -- but that's expensive prereq to add -- or (preferrably) add a more helpful error message if gfortran is not found.

**Comment by jwnimmer-tri** [comment]
It's actually `ipopt` that needs `gfortran`, not `gurobi`.

**Comment by RussTedrake** [comment]
oops.  you're right.  so definitely need to add it to the sphinx installation instructions.

**Comment by jwnimmer-tri** [comment]
The `drake/doc/mac.rst` has `brew install ... gcc ...` already (buried in the big line).  Perhaps something else is going wrong -- e.g. `gfortran` is not on your `$PATH` for some reason, though why CI would differ is a mystery.

**Comment by soonho-tri** [comment]
Possibly related item: http://drake.mit.edu/clion.html#a-note-about-environment-variables

Please check the text under "OS X users" item:

> users will get broken behavior by default. When you run an OS X app graphically, the parent process is launchd (PID 1), which provides its own standard environment variables to the child process. In particular, it provides a minimal PATH that does not include /usr/local/bin, where most Homebrew executables are installed. Consequently, the Bazel build will fail to find Homebrew dependencies like glib, pkg-config, and gfortran.

**Comment by RussTedrake** [comment]
thanks all.  most likely i just missed an installation step.  have been installing way too many machines/VMs lately, and have lost track of what ran what when.

**Comment by jwnimmer-tri** [comment]
I think it would be fair to reopen and improve the error message from `gfortran.bzl`.  We are calling `repository_ctx.which` which can return `None`, but we assume the result is non-`None`.
