### ISSUE TITLE
snopt prints to wrong file

### ISSUE THREAD

**Issue by hongkai-dai** [RobotLocomotion/drake#598]
Currently our `NonlinearProgramSnoptmex` prints to `fort.15` file, even if we tell it to print to `print.out`. I think this is because we are using the c++ library of SNOPT, and SNOPT c++ interface can only allow printing to `fort.XX`, where XX is the print number we specify, whatever name the user specifies.

If we run the SNOPT's own C++ example, in drake-distro/snopt/pod-build/bin/ccsntoya, it always prints to `fort.15`, although in its example file drake-distro/snopt/cppexample/sntoya.cc, it specifies the print out file to be `Toy0.out`.

A good news is that SNOPT C interface actually does the right thing. If we run the C example file drake-distro/snopt/pod-build/bin/csntoya, it would print to the right file `sntoya.out`.

Shall we change to link against `snopt_c` instead of `snopt_cpp`? We cannot use the C++ interface anyway, since we defined the `snopt` workspace in `NonlinearProgramSnoptmex` for the f2c issue, and C++ does not allow us to do that.

**Comment by chrisdembia** [comment]
Hey fellow snopt users. I'm trying to use snopt with PSOPT and I get the same exact error related to `U_fp` as you used to get (I'm not using drake, though it looks like I should try it out) Could you explain exactly how you fixed it? Did you just stop using the old f2c interface?

Thank you!

**Comment by hongkai-dai** [comment]
I think there are two major changes in the #588, first we switched to link against snopt C library, instead of its C++ library; second we added a call to `sninit_` before calling `snmema_`. I think your problem should be resolved by linking against snopt C library.

**Comment by chrisdembia** [comment]
Thank you for answering; I'll try that.
