### ISSUE TITLE
Permit adding variables created outside of MathematicalProgram

### ISSUE THREAD

**Issue by EricCousineau-TRI** [RobotLocomotion/drake#5993]
Presently, there is no publicly exposed method to add an existing decision variable (scalar, vector, or matrix) to a `MathematicalProgram`. The current methods are of the form:

```c++
MatrixDecisionVariable<...> New.*Variables(..., const ContainerOf<string>& name_or_prefix) {
   ...
   MatrixDecisionVariable<...> vars = ...;
   NewVariables_impl(..., vars);
   return vars;
}
```

We can introduce a new method, `Add.*Variables(...)`, which would be of the form:

```c++
void Add.*Variables(..., const MatrixDecisionVariable<...> &X) {
    AddVariables_impl(..., X); // could refactor `NewVariables_impl` to possibly use this
}
```

\cc @hongkai-dai @soonho-tri @RussTedrake

**Comment by soonho-tri** [comment]
Closing after further f2f with @EricCousineau-TRI .
