### ISSUE TITLE
kLinearSystem does not check feasibility of solution.

### ISSUE THREAD

**Issue by FischerGundlach** [RobotLocomotion/drake#6042]
I was toying with simple problems using the mathematical_program in c++ drake. I constructed the infeasible problem:

`  drake::solvers::MathematicalProgram prog_;
  drake::solvers::VectorDecisionVariable<1> x_;

  x_ = prog_.NewContinuousVariables(1);
  prog_.AddLinearEqualityConstraint(x_(0)==0);
  prog_.AddLinearEqualityConstraint(x_(0)==10);

  prog_.Solve();
  std::cout << prog_.GetSolution(x_);`

The problem is a) solver_result = 0,  b) solver_type = kLinearSystem and c) with solution x_= 5.

Adding an inequality `prog_.AddLinearConstraint(x_(0),1,5);` (i.e. 1 <= x_(0) <= 5) stops using kLinearSystem and uses Mosek instead which gives the expected infeasible return value. 

I did not dig deeper into it, but apparently KLinearSystem does not check feasibility   ##of its solutions as a final step.

**Comment by jwnimmer-tri** [comment]
All issues must have owners; feel free to reassign elsewhere as needed (or close), etc.
