### ISSUE TITLE
Need to add boost and tinyxml to the prebuilt CI images

### ISSUE THREAD

**Issue by clalancette** [RobotLocomotion/drake#6058]
Based on this review: #6028 , we need to add the libtinyxml-dev dependency to the prebuilt CI images.  Assigning to @BetsyMcPhail

**Comment by jamiesnape** [comment]
Also:
* `sudo apt-get install libboost-dev`
* `brew install boost tinyxml`

**Comment by BetsyMcPhail** [comment]
The Trusty, Xenial and Mac images have been updated.

**Comment by clalancette** [comment]
Thank you!
