### ISSUE TITLE
Need to move the monolithic pick-and-place demo out of dev

### ISSUE THREAD

**Issue by naveenoid** [RobotLocomotion/drake#6082]
Multiple teams are using the KUKA IIWA Arm monolithic pick and place demo as a benchmark. It needs to move out of dev and into mainstream master. This issue tracks the PRs that need to land in order to achieve this.
- [x] Move Iiwa_ik_planner -> add a suitable unit test.
- [ ] Move IiwaWsgPlantGeneratorsEstimatorsAndVisualizer
- [x] Move ActionPrimitives (two or more PRs may be needed here).
- [ ] Move StateMachineAndPrimitives diagram.
- [ ] Move the demo itself (bikeshedding on the name needed!).

**Comment by naveenoid** [comment]
Tagging @sammy-tri @kunimatsu-tri @SeanCurtis-TRI @siyuanfeng-tri @RussTedrake 
(People who might care about this move)

**Comment by sammy-tri** [comment]
Closing because #10591 deleted the relevant code.
