### ISSUE TITLE
Error while executing addpath_drake

### ISSUE THREAD

**Issue by GPrathap** [RobotLocomotion/drake#6095]
I followed drake installing using [make](http://drake.mit.edu/from_source.html#build-with-make). The build was successful. But then I tried to test drake installation in Matlab using [this](http://drake.mit.edu/from_source.html#test-your-installation).  

But I am getting this error. 

```
Error using addpath_drake (line 20)
The Drake build olsutputs are not on the MATLAB path, and could not be auto-detected. Please add the build output directory "matlab" to the path, then re-run addpath_drake.
```

I have checked `drake-distro/build/install/matlab` directory and I can see only these m files. `addpath_sedumi.m  addpath_spotless.m  rmpath_sedumi.m  rmpath_spotless.m`. 

Then I tried to add  addpath_spotless.m and it works fine. Can someone explain is this related build issue or something else.

Environment: 16.04.1-Ubuntu, Matlab16a

**Comment by hongkai-dai** [comment]
Could you make sure that drake is built with MATLAB? You can do the following to check if MATLAB was detected when compiling drake
```
$ cd drake-distro/build
$ ccmake ..
```
When I do this on my machine, it shows the variables DISABLE_MATLAB, MATLAB_EXECUTABLE, Matlab_ROOT_DIR, etc, are set to some values, as in the following screenshot. Can you make sure that cmake detects your MATLAB?
![screenshot from 2017-05-14 23-43-27](https://cloud.githubusercontent.com/assets/6314000/26045516/81782204-38ff-11e7-87b5-26a128ecce21.png)

**Comment by GPrathap** [comment]
Yes, This is my configuration.  
![screenshot_2017-05-15_12-24-45](https://cloud.githubusercontent.com/assets/7587302/26046167/3a623c80-396b-11e7-8818-63d8427f65bc.png)

Anyway thanks for the prompt response. If you have a build can you give me the what files should be in the `drake-distro/build/install/matlab`.

**Comment by hongkai-dai** [comment]
The files in my `drake-distro/build/install/matlab` are
![screenshot from 2017-05-15 09 16 18](https://cloud.githubusercontent.com/assets/6314000/26067520/65a29302-394f-11e7-8da4-5a31501f1523.png)

**Comment by hongkai-dai** [comment]
BTW, the files in `drake-distro/drake/matlab` are
![screenshot from 2017-05-15 09 19 36](https://cloud.githubusercontent.com/assets/6314000/26067615/a22586a4-394f-11e7-9ea5-ab854d7cca4a.png)

**Comment by GPrathap** [comment]
Files in the `drake-distro/drake/matlab` are very similar to what you have. But most of them did not copy to `drake-distro/build/install/matlab`. I will try to install Matlab16b or Matlab17a then will rebuild the drake. Will let you know the result.  Thanks for your time on this.

**Comment by jwnimmer-tri** [comment]
All issues must have owners.  I'm assigning one arbitrarily.  (Fix it up if I'm wrong.)
