### ISSUE TITLE
doxygen doesn't render HTML char entities properly

### ISSUE THREAD

**Issue by soonho-tri** [RobotLocomotion/drake#6099]
Example: http://drake.mit.edu/doxygen_cxx/group__solvers.html

It ignores (`&diams;`, :diamonds:) and (`&dagger;`, †) in https://github.com/RobotLocomotion/drake/blob/master/drake/solvers/mathematical_program.h#L76-L80.

<img width="932" alt="screen shot 2017-05-15 at 11 06 27 am" src="https://cloud.githubusercontent.com/assets/20779767/26064309/90e1c0e2-395e-11e7-9a3d-2a7b59503139.png">

It says it built the documentation using `doxygen-1.8.6`. We can't reproduce the problem with later versions such as `doxygen-1.8.13` (OSX) and `doxygen-1.8.11` (Ubuntu Xenial).

**Comment by jamiesnape** [comment]
@BetsyMcPhail Switch the documentation builds to Xenial. You will need to install the oXygen XML Editor onto the Xenial image and remove it from the Trusty image.

**Comment by BetsyMcPhail** [comment]
The documentation build has been switched from Trusty to Xenial. 

As a result, doxygen has also been updated to 1.8.11.

**Comment by soonho-tri** [comment]
Nice!

**Comment by stonier** [comment]
@soonho-tri should the [Mixed-Integer Convex Optimization](http://drake.mit.edu/doxygen_cxx/group__solvers.html) table be empty?

**Comment by jwnimmer-tri** [comment]
Yes https://github.com/RobotLocomotion/drake/blob/78a2bf6d50ca4c66fceebf30cb5982734033024e/drake/solvers/mathematical_program.h#L94-L118

**Comment by soonho-tri** [comment]
Both of Mosek and Gurobi support mixed integer programming [[1](http://www.gurobi.com/resources/getting-started/mip-basics), [2](http://docs.mosek.com/7.0/tools/The_optimizers_for_mixed-integer_problem.html)]. I will ask @hongkai-dai for details and open a PR to update the doc.
