### ISSUE TITLE
Improve output port error messages

### ISSUE THREAD

**Issue by sherm1** [RobotLocomotion/drake#6113]
PR #6038 changed the output port API to allow separate per-port computation. Many good ideas came up in review that should be considered for follow-on improvements. This issue collects them:

- [ ] Output port error messages include the System name and type but only the port index. Add the port type to the message. (@SeanCurtis-TRI [comment](https://reviewable.io/reviews/robotlocomotion/drake/6038#-KjiJ2lYXOqgfrfQ1ndM)).
- [x] Input ports now look very clunky compared to output ports. At least the InputPortDescriptor should get renamed to InputPort, and the model-based declaration signature should be used everywhere rather than the kVectorValued, etc. stuff.
- [x] Currently OutputPorts are explicitly instantiated for `AutoDiff<Vec2>` and `Vec3` to accommodate some existing test cases. Consider (a) modifying the tests to use `AutoDiff<VecX>`, or (b) add output_port-inl.h so the definitions are visible.
- [x] LeafOutputPort currently permits null allocator/calculator functions and complains only if runtime calls are made that require them. We could likely engineer this to require both functions at compile time. If it turns out we don't make use of the null pointers (e.g. for determining whether we need to generate a calc method from the eval method, or for late binding), then consider enforcement at compile time.

**Comment by jwnimmer-tri** [comment]
Re: naming.  I agree that "Allocate" is not ideal; really, it's just wrapping a constructor, so just "Construct"?

**Comment by jwnimmer-tri** [comment]
I'm guessing here, but I'd wager that the `PortEvalCast` refactoring fixed the only remaining open checklist item, so I think we can call this done.
