### ISSUE TITLE
Add unit tests for installation helpers

### ISSUE THREAD

**Issue by mwoehlke-kitware** [RobotLocomotion/drake#6117]
#6072 adds some internal helper functions that probably should have some unit tests (`strip_prefix` in particular). For that matter, it would be nice to unit test `install` itself if the framework lets us do that. (Inspecting the returned actions for sanity should be sufficient, and can be done against a test project.)

**Comment by jwnimmer-tri** [comment]
Closing as duplicate of #7331.
