### ISSUE TITLE
Drake visualizer window can't be seen. 

### ISSUE THREAD

**Issue by chang-liang** [RobotLocomotion/drake#6122]
For instance, when I run runAtlasWalking.m, Matlab would be working well, showing 'busy' in the left bottom corner of Matlab window, and 'attempt to launch drake director' in the command window.

The Drake visualizer icon shows in the left bar, but I can't see the Drake visualizer window. 
![image](https://cloud.githubusercontent.com/assets/6902821/26158856/0322a54e-3aeb-11e7-8b06-f663d733dc2e.png)

**Comment by liangfok** [comment]
Maybe this will help?
http://blog.vogella.com/2013/06/02/ubuntu-how-to-move-an-application-which-is-displayed-offscreen/

**Comment by chang-liang** [comment]
Your answer is perfect and it works. Thank you!

**Comment by liangfok** [comment]
You're welcome!
