### ISSUE TITLE
"Slow read"s when building with Bazel

### ISSUE THREAD

**Issue by m-chaturvedi** [RobotLocomotion/drake#6129]
For example:
https://drake-jenkins.csail.mit.edu/job/linux-xenial-clang-bazel-experimental-memcheck-valgrind-everything/7/console

at time `17:15:27` in the log above.

**Comment by jwnimmer-tri** [comment]
Probably just due to things like #5900, exacerbated by CI being slower than local workstations.  We might be able to disable the warning, but I'm not sure what else useful we'd expect to do in this issue.

**Comment by stonier** [comment]
@m-chaturvedi brain dump whatever you learn to this issue!

**Comment by m-chaturvedi** [comment]
- This github issue seems related to the problem, https://github.com/bazelbuild/bazel/issues/1210 , #835 which it cites in particular.
- The flag `--local-resources` which can set the available IO (1.0 by default) maybe useful after the changes made in https://github.com/bazelbuild/bazel/issues/835
- When running on my machine I observed higher latency ( external HDD ) gives more number of "slow read"s.

**Comment by jwnimmer-tri** [comment]
All issues must have owners.  I'm assigning one arbitrarily.  (Fix it up if I'm wrong.)

**Comment by stonier** [comment]
From Jamie : can often happen when a new instance is spun up - the remote hard drive is pretty slow getting written to the first time and can trigger this problem. Instances get culled and spun up pretty frequently.
