### ISSUE TITLE
Parse a simple double pendulum with sdformat

### ISSUE THREAD

**Issue by amcastro-tri** [RobotLocomotion/drake#6135]
Recently merged PR #6028 introduces the `sdformat` parser into Drake (yai!).
As a proof of life, this PR introduces a [demo test](https://github.com/RobotLocomotion/drake/blob/master/drake/multibody/parsers/test/sdformat_test.cc) for a simple world containing a single link. How would we go about parsing a file with more than one link? take for instance this very simple example of a [double pendulum](https://github.com/RobotLocomotion/drake/blob/master/drake/multibody/benchmarks/acrobot/double_pendulum.urdf). 
It'd seem we'd need to make repeated calls to `Element::GetNextElement()` since `Element::GetElement()` seems to always return the first child (is that true? there is no doc for either of these).

I think a very good next goal for integrating sdformat into Drake would be to succesfully parse [double pendulum](https://github.com/RobotLocomotion/drake/blob/master/drake/multibody/benchmarks/acrobot/double_pendulum.urdf) (actually it's sdf version). Something as simple as that example would help us learn what are the prefered set of API calls when using sdformat.

**Comment by amcastro-tri** [comment]
cc'ing @clalancette, @stonier, @sherm1

**Comment by sherm1** [comment]
Maybe the next step should be to improve sdformat's documentation?

**Comment by stonier** [comment]
Already bumped OSRC to watch this space and support it with documentation where you guys have questions.

**Comment by stonier** [comment]
I asked the lads from OSRC to run with this and create a more complex introductory example illustrating how to parse it with the c++ api. 

We also talked about a c++ api and tool that could be used to validate them. Apparently there is one in gazebo that could/should be more logically in sdformat. 

@caguero

**Comment by stonier** [comment]
[Validating Sdf Files](https://bitbucket.org/osrf/sdformat/issues/157/validating-an-sdf-from-the-c-api)

**Comment by jwnimmer-tri** [comment]
All issues must have owners.  I'm assigning one arbitrarily.  (Fix it up if I'm wrong.)
