### ISSUE TITLE
Create additional unit tests for  RotationalInertia operator+() and operator/() 

### ISSUE THREAD

**Issue by mitiguy** [RobotLocomotion/drake#6145]
Create unit test in rotational_inertia_tests.cc for:  
 - `RotationalInertia<T> operator+(const RotationalInertia<T>& I_BP_E) const` (It seems only [RotationalInertia::MultiplicationWithScalarFromTheLeft](https://github.com/RobotLocomotion/drake/blob/master/drake/multibody/multibody_tree/test/rotational_inertia_tests.cc#L220) covers this).
 - `RotationalInertia<T> operator/(const T& positive_scalar) const`

**Comment by sherm1** [comment]
Per f2f: just delete it in #5945 and be done with it?

**Comment by jwnimmer-tri** [comment]
Seven years later, we don't seem to have missed the tests.  If they are still relevant, then consider this a reminder to submit the PR promptly.  We don't need a 7-year-old reminder cluttering up the issues database.
