### ISSUE TITLE
Consistent policy for throwing debug-build exceptions for invalid inertias to class UnitInertia

### ISSUE THREAD

**Issue by mitiguy** [RobotLocomotion/drake#6147]
Continue work that has been completed in class RotationalInertia to ensure consistent policy for throwing debug-build exception std::logic_error for invalid inertias.
"Bubble" this up to class UnitInertia (and perhaps SpatialInertia).

The following stack of calls shows this problem (May 20, 2017):
1.  In spatial_inertia_tests.cc
GTEST_TEST(SpatialInertia, IsPhysicallyValidWithCOMTooFarOut) 
calls SpatialInertia() constructor and catches an exception that
is thrown by SpatialInertia's CheckInvariants() method.

2.  In spatial_inertia.h, SpatialInertia() constructor calls
SpatialInertia's  CheckInvariants() which throws an
exception (in both debug and release builds) if
IsPhysicallyValid() returns true.

3.  In spatial_inertia.h, CheckInvariants() calls
SpatialInertia's IsPhysicallyValid() which a
boolean (true/false).  This method should
not thrown an exception - it is just a test.

4.  In spatial_inertia.h, IsPhysicallyValid() calls
UnitInertia's ShiftToCenterOfMass().

5.  In unit_inertia.h, ShiftToCenterOfMass() calls
UnitInertia's ShiftToCenterOfMassInPlace().

6.  In unit_inertia.h, ShiftToCenterOfMassInPlace() calls
RotationalInertia's MinusEqualsUnchecked().
This was done to avoid using `operator-=()` as
operator-=() throws an exception in debug builds
if the underlying rotational inertia is invalid.

## What we want:
 - `IsPhysicallyValid()` should not to throw an exception, but only report `true`/`false`.
    This is the current behavior - and this behavior should continue.

 - Methods in the `ShiftToCenterOfMass()` family to throw exceptions in 
Debug builds (but not release builds) if there are invalid inertia properties.

## Possible Fix

 -  Implement new method `ShiftToCenterOfMassUnchecked()` to avoid
throwing exceptions in all builds (Debug/Release).

-  Consider merging methods such as the `ShiftToCenterOfMassInPlace()`  
into `ShiftToCenterOfMass()`, to minimize members in the Shift .... family.

**Comment by amcastro-tri** [comment]
cc'ing @amcastro-tri

**Comment by jwnimmer-tri** [comment]
All issues must have owners.  I'm assigning one arbitrarily.  (Fix it up if I'm wrong.)

**Comment by jwnimmer-tri** [comment]
Seven years later, it seems like maybe this is not that important -- otherwise we would have done it by now?

Please either close this issue as "not planned", or else add it to a project board for the project that's going to implement it.
