### ISSUE TITLE
Minimal example of a project using drake as an external library on travis

### ISSUE THREAD

**Issue by RussTedrake** [RobotLocomotion/drake#6149]
bonus points: a second example ising just part of drake (eg just drakeOptimization.lib)

Current pain point is that building drake from source takes >1 hr on travis, so would not be free.  Likely best resolution is to finally provide binary releases.

+ @rdeits, @tkoolen

**Comment by jamiesnape** [comment]
Not Jenkins?

**Comment by stonier** [comment]
This is for users outside our periphery who are using drake with their own projects and using travis to avoid having to set up their own CI. We just need to provide an appropriate pipeline for distributing versioned binaries for these people.

**Comment by jamiesnape** [comment]
Fair enough, though we could do with something like this running on Jenkins at some point.

**Comment by stonier** [comment]
Aye, I'm thinking of having a separate repository (repositories) demonstrating in a very simple way a few different use cases. Spinning them up on jenkins would be a good way to test them to make sure it works properly.

**Comment by jamiesnape** [comment]
We basically have this in shambhala now using CircleCI, so maybe this can be closed?

**Comment by jwnimmer-tri** [comment]
@RussTedrake okay to close now?
