### ISSUE TITLE
Refactor CI 'experimental' job names

### ISSUE THREAD

**Issue by stonier** [RobotLocomotion/drake#6240]
These jobs confusingly consist of both pre-merge and defacto experimental jobs.

* [ ] For pre-merge jobs do a "experimental"->"premerge" substitution
* [ ] Update the CI design doc [here](https://docs.google.com/document/d/1oPybZVy5KlPb9IY08t6ol_l-oakXRMV9rmWmpsI_8aw/edit#bookmark=id.i96xhsqarv2) once done.

**Comment by jamiesnape** [comment]
This is extremely non-trivial and will also break the GitHub statuses of open PRs.

**Comment by jamiesnape** [comment]
It will also break links back to Jenkins from CDash on existing builds.

**Comment by stonier** [comment]
Was this visited in the past and discarded with David at some point because of the complications?

**Comment by jamiesnape** [comment]
It was discussed, yes. There are probably ways we can make the PR jobs more prominent, but the names themselves are pretty much immutable.

**Comment by EricCousineau-TRI** [comment]
Will close this for now, as it would cause disruption. Can reopen later if needed.
