### ISSUE TITLE
Supported macOS / OS X versions for binaries

### ISSUE THREAD

**Issue by jamiesnape** [RobotLocomotion/drake#6296]
We currently support Yosemite, El Capitan, and Sierra for binaries, and will inevitably need to support High Sierra in a couple of months as people upgrade or buy new Macs. There is a maintenance cost to all this (we have to maintain 3-4 different VM's on which to create binaries, and High Sierra binaries will have to be created on my development machine until VMware supports the new OS).

The question therefore is which versions should we support?

FYI @stonier.

(We currently use El Capitan on CI, but now that we have to maintain VM's for other versions, it would not be hard to change that.)

**Comment by soonho-tri** [comment]
Here is a survey: https://www.gosquared.com/global/mac/sierra/#month

It seems that supporting the latest three versions (Sierra, El Capitan, and Yosemite) cover about 90% of users. FYI, [bazel.rb](https://github.com/Homebrew/homebrew-core/blob/master/Formula/bazel.rb) only provides pre-built binaries for those three versions.

BTW, how about moving to `Homebrew/homebrew-core` so that we can use their infrastructure to prepare binaries?

**Comment by stonier** [comment]
@soonho-tri what are you and Russ using? Are there other mac users in our group itself?

**Comment by jamiesnape** [comment]
> BTW, how about moving to Homebrew/homebrew-core so that we can use their infrastructure to prepare binaries?

We probably could for VTK eventually, for the others, it unlikely.

**Comment by soonho-tri** [comment]
@stonier , I'm using the latest (Sierra, 10.12.5). I usually do the upgrade after a month of a release.

**Comment by jamiesnape** [comment]
FWIW, I use Sierra too and upgrade a week or so after release on my work machine, earlier at home.

**Comment by jamiesnape** [comment]
Not enough users and it is mostly a GUI.

**Comment by stonier** [comment]
I'd like to propose an N, N-1 support policy, with a small buffer for transition as a new release comes out. That should satisfy the majority of developers. Does anyone object?

**Comment by soonho-tri** [comment]
I like the `N` & `N-1` policy.

Speaking of the macOS versions, do we plan to upgrade the macCI from El Capitan to Sierra? I vaguely remember that there are some issues.

**Comment by jamiesnape** [comment]
Sounds good to me. I would propose deprecating the N-2 one month after a new N release, removing support after three months. CI would move to the N release within those three months. That would probably mean that El Capitan support would be dropped by the end of this calendar year.

Unless someone comments that they need Yosemite, I would like to drop support ASAP.

**Comment by jamiesnape** [comment]
(@soonho-tri Yes, soon, VMware have caught up with support now.)

**Comment by rdeits** [comment]
I use El Capitan but am willing to upgrade if necessary (I'm not that interested in features, so I tend to upgrade roughly whenever a program I care about requires it)

**Comment by RussTedrake** [comment]
i'm on sierra and support N,N-1
