### ISSUE TITLE
Once covered in CI, consider offering a public pre-built drake Docker image

### ISSUE THREAD

**Issue by EricCousineau-TRI** [RobotLocomotion/drake#6315]
Per Brandon's comment in #6196, it would be nice to have a (free) publicly hosted pre-built image of Drake once the time is appropriate.

\cc @stonier @jwnimmer-tri @brandon-northcutt

**Comment by jwnimmer-tri** [comment]
Relates #1183 and #1766.

**Comment by EricCousineau-TRI** [comment]
Closing as dup of #10554
