### ISSUE TITLE
addpathTemporary + clear all causes segfault

### ISSUE THREAD

**Issue by kuindersma** [RobotLocomotion/drake#635]
Example:

```
>> test
>> clear all
>> test % causes segfault
```

where test.m contains
```
function test
path_handle = addpathTemporary({fullfile(getDrakePath,'examples','Atlas','frames')});
options.floating = true;
options.dt = 0.002;
r = Atlas('urdf/atlas_minimal_contact.urdf',options);
end
```

Note: using megaclear instead of clear all works.

**Comment by RussTedrake** [comment]
confirmed that this happens (at least on drake006)
removing NonlinearProgramSnoptmex.mexa64 did *not* fix it.
disabling snoptcmex in checkDependency did resolve it.

**Comment by RussTedrake** [comment]
a pretty minimal way to reproduce:
```
matlab -nodisplay -r "addpath_drake; r = RigidBodyManipulator('examples/Atlas/urdf/atlas_minimal_contact.urdf',struct('floating',true)); x0 = resolveConstraints(r,zeros(getNumStates(r),1)); clear all; which('LinearSystem');"
```
again fails w/ `NonlinearProgramSnoptmex` or `snoptcmex`, but not fmincon.  I strongly suspect snopt at this point.

**Comment by RussTedrake** [comment]
OK.  Spent WAY too much time on this, but whittled it down to what is obviously a matlab bug.  Check out this super minimal example:

(having a reference to the derived class in the base class causes the problem)


```
russt@thrashcan:~/drake-distro/drake/systems$ more classA.m
classdef classA

  methods
    function myfun()
      classB();
    end
  end
end
russt@thrashcan:~/drake-distro/drake/systems$ more classB.m
classdef classB < classA

methods
function myotherfun()
end
end

end
russt@thrashcan:~/drake-distro/drake/systems$ matlab -nodisplay -r "classA(); clear java; which('classB')"

                                                                                    < M A T L A B (R) >
                                                                          Copyright 1984-2014 The MathWorks, Inc.
                                                                            R2014a (8.3.0.532) 64-bit (glnxa64)
                                                                                     February 11, 2014


To get started, type one of these: helpwin, helpdesk, or demo.
For product information, visit www.mathworks.com.

[Please exit and restart MATLAB]>>]>>n
------------------------------------------------------------------------
       Segmentation violation detected at Sun Apr 26 18:43:06 2015
------------------------------------------------------------------------

Configuration:
  Crash Decoding     : Disabled
  Current Visual     : None
  Default Encoding   : US-ASCII
  GNU C Library      : 2.19 stable
  MATLAB Architecture: glnxa64
  MATLAB Root        : /usr/local/MATLAB/R2014a
  MATLAB Version     : 8.3.0.532 (R2014a)
  Operating System   : Linux 3.16.0-33-generic #44~14.04.1-Ubuntu SMP Fri Mar 13 10:33:29 UTC 2015 x86_64
  Processor ID       : x86 Family 6 Model 62 Stepping 4, GenuineIntel
  Virtual Machine    : Java 1.7.0_11-b21 with Oracle Corporation Java HotSpot(TM) 64-Bit Server VM mixed mode
  Window System      : No active display

Fault Count: 1


Abnormal termination:
Segmentation violation

Register State (from fault):
  RAX = 00007ffaa9a44cc0  RBX = 00007ffab5b0dba0
  RCX = 00007ffab5b0d9d0  RDX = 00007ffab5b0d9c8
  RSP = 00007ffab5b0d968  RBP = 00007ffab5b0da80
  RSI = 00007ffab5b0d9c0  RDI = 00007ffaa9a9d380

   R8 = 0000000000000001   R9 = 00007ffaa9b98840
  R10 = 00007ffac7ad6650  R11 = 00007ffac7b10860
  R12 = 0000000000000000  R13 = 0000000000000000
  R14 = 0000000000000000  R15 = 0000000000000002

  RIP = 0000000000000000  EFL = 0000000000010246

   CS = 0033   FS = 0000   GS = 0000

Stack Trace (from fault):
[  0] 0x0000000000000000                                   <unknown-module>+00000000
[  1] 0x00007ffabecced29 /usr/local/MATLAB/R2014a/bin/glnxa64/libmwm_dispatcher.so+00531753 _ZN11mdWhichInfo6filterEv+00000681
[  2] 0x00007ffabecd0eee /usr/local/MATLAB/R2014a/bin/glnxa64/libmwm_dispatcher.so+00540398 _ZN11mdWhichInfo4findEv+00000126
[  3] 0x00007ffa91666c0d /usr/local/MATLAB/R2014a/bin/glnxa64/libmwwkspintrospect.so+00101389
[  4] 0x00007ffabecb2de3 /usr/local/MATLAB/R2014a/bin/glnxa64/libmwm_dispatcher.so+00417251
[  5] 0x00007ffabec9f874 /usr/local/MATLAB/R2014a/bin/glnxa64/libmwm_dispatcher.so+00338036 _ZN13Mfh_MATLAB_fn11dispatch_fhEiPP11mxArray_tagiS2_+00000244
[  6] 0x00007ffabddc720e /usr/local/MATLAB/R2014a/bin/glnxa64/libmwm_interpreter.so+02601486
[  7] 0x00007ffabdd681b0 /usr/local/MATLAB/R2014a/bin/glnxa64/libmwm_interpreter.so+02212272
[  8] 0x00007ffabdd8325f /usr/local/MATLAB/R2014a/bin/glnxa64/libmwm_interpreter.so+02323039
[  9] 0x00007ffabdd87167 /usr/local/MATLAB/R2014a/bin/glnxa64/libmwm_interpreter.so+02339175
[ 10] 0x00007ffabdd8526f /usr/local/MATLAB/R2014a/bin/glnxa64/libmwm_interpreter.so+02331247
[ 11] 0x00007ffabdd85ec4 /usr/local/MATLAB/R2014a/bin/glnxa64/libmwm_interpreter.so+02334404
[ 12] 0x00007ffabdde330b /usr/local/MATLAB/R2014a/bin/glnxa64/libmwm_interpreter.so+02716427
[ 13] 0x00007ffabecf0c5f /usr/local/MATLAB/R2014a/bin/glnxa64/libmwm_dispatcher.so+00670815 _ZN8Mfh_file11dispatch_fhEiPP11mxArray_tagiS2_+00001087
[ 14] 0x00007ffabddb6135 /usr/local/MATLAB/R2014a/bin/glnxa64/libmwm_interpreter.so+02531637
[ 15] 0x00007ffabdd7d0d9 /usr/local/MATLAB/R2014a/bin/glnxa64/libmwm_interpreter.so+02298073
[ 16] 0x00007ffabdd7a9e1 /usr/local/MATLAB/R2014a/bin/glnxa64/libmwm_interpreter.so+02288097
[ 17] 0x00007ffabdd7abf1 /usr/local/MATLAB/R2014a/bin/glnxa64/libmwm_interpreter.so+02288625
[ 18] 0x00007ffabdd7c290 /usr/local/MATLAB/R2014a/bin/glnxa64/libmwm_interpreter.so+02294416
[ 19] 0x00007ffabdd21a75 /usr/local/MATLAB/R2014a/bin/glnxa64/libmwm_interpreter.so+01923701 _Z51inEvalCmdWithLocalReturnInDesiredWSAndPublishEventsPKcPibbP15inWorkSpace_tag+00000085
[ 20] 0x00007ffabfdd8e68   /usr/local/MATLAB/R2014a/bin/glnxa64/libmwiqm.so+00650856 _ZNK3iqm18InternalEvalPlugin24inEvalCmdWithLocalReturnERKSbIDsSt11char_traitsIDsESaIDsEEP15inWorkSpace_tag+00000120
[ 21] 0x00007ffabfdd9328   /usr/local/MATLAB/R2014a/bin/glnxa64/libmwiqm.so+00652072 _ZN3iqm18InternalEvalPlugin7executeEP15inWorkSpace_tagRN5boost10shared_ptrIN14cmddistributor17IIPCompletedEventEEE+00000120
[ 22] 0x00007ffac8dca0c5   /usr/local/MATLAB/R2014a/bin/glnxa64/libmwmcr.so+00434373
[ 23] 0x00007ffabfdcb565   /usr/local/MATLAB/R2014a/bin/glnxa64/libmwiqm.so+00595301
[ 24] 0x00007ffabfdb9b05   /usr/local/MATLAB/R2014a/bin/glnxa64/libmwiqm.so+00523013
[ 25] 0x00007ffabfb1ead9 /usr/local/MATLAB/R2014a/bin/glnxa64/libmwbridge.so+00121561 _Z10ioReadLinebP8_IO_FILERKN5boost8optionalIKP15inWorkSpace_tagEEb+00000345
[ 26] 0x00007ffabfb1f081 /usr/local/MATLAB/R2014a/bin/glnxa64/libmwbridge.so+00123009
[ 27] 0x00007ffabfb23c2d /usr/local/MATLAB/R2014a/bin/glnxa64/libmwbridge.so+00142381
[ 28] 0x00007ffabfb23fe9 /usr/local/MATLAB/R2014a/bin/glnxa64/libmwbridge.so+00143337
[ 29] 0x00007ffabfb2470b /usr/local/MATLAB/R2014a/bin/glnxa64/libmwbridge.so+00145163 _Z8mnParserv+00000587
[ 30] 0x00007ffac8dd792f   /usr/local/MATLAB/R2014a/bin/glnxa64/libmwmcr.so+00489775 _ZN11mcrInstance30mnParser_on_interpreter_threadEv+00000031
[ 31] 0x00007ffac8db8b6d   /usr/local/MATLAB/R2014a/bin/glnxa64/libmwmcr.so+00363373
[ 32] 0x00007ffac8db8be9   /usr/local/MATLAB/R2014a/bin/glnxa64/libmwmcr.so+00363497
[ 33] 0x00007ffac9487e33 /usr/local/MATLAB/R2014a/bin/glnxa64/libmwservices.so+01646131 _ZN10eventqueue18UserEventQueueImpl5flushEv+00000611
[ 34] 0x00007ffabd4921ed   /usr/local/MATLAB/R2014a/bin/glnxa64/libmwuix.so+00221677
[ 35] 0x00007ffac952d6ea /usr/local/MATLAB/R2014a/bin/glnxa64/libmwservices.so+02324202
[ 36] 0x00007ffac952da24 /usr/local/MATLAB/R2014a/bin/glnxa64/libmwservices.so+02325028
[ 37] 0x00007ffac952957f /usr/local/MATLAB/R2014a/bin/glnxa64/libmwservices.so+02307455
[ 38] 0x00007ffac952e9b5 /usr/local/MATLAB/R2014a/bin/glnxa64/libmwservices.so+02329013
[ 39] 0x00007ffac952ede7 /usr/local/MATLAB/R2014a/bin/glnxa64/libmwservices.so+02330087
[ 40] 0x00007ffac952f4c0 /usr/local/MATLAB/R2014a/bin/glnxa64/libmwservices.so+02331840 _Z25svWS_ProcessPendingEventsiib+00000080
[ 41] 0x00007ffac8db9098   /usr/local/MATLAB/R2014a/bin/glnxa64/libmwmcr.so+00364696
[ 42] 0x00007ffac8db93bf   /usr/local/MATLAB/R2014a/bin/glnxa64/libmwmcr.so+00365503
[ 43] 0x00007ffac8db428f   /usr/local/MATLAB/R2014a/bin/glnxa64/libmwmcr.so+00344719
[ 44] 0x00007ffac7d65182              /lib/x86_64-linux-gnu/libpthread.so.0+00033154
[ 45] 0x00007ffac7a9247d                    /lib/x86_64-linux-gnu/libc.so.6+01025149 clone+00000109


If this problem is reproducible, please submit a Service Request via:
    http://www.mathworks.com/support/contact_us/

A technical support engineer might contact you with further information.

Thank you for your help.** This crash report has been saved to disk as /home/russt/matlab_crash_dump.21295-1 **



MATLAB is exiting because of fatal error
Killed
```

**Comment by RussTedrake** [comment]
just for reference, here are some of my working notes:

also fails for Acrobot.urdf.  floating not required.

clear mex and clear classes passes.  clear java causes the fail.



on drake005 with the delay simulink pull request:

matlab -nodisplay -r "addpath_drake; r = RigidBodyManipulator('examples/Acrobot/Acrobot.urdf'); x0 = resolveConstraints(r,zeros(getNumStates(r),1)); inmem, clear java; inmem, which('LinearSystem');"

adding clear classes fixes it.

[m,x,c]=inmem lists these classes in memory
    'containers.Map'
    'java.lang.String'
    'message'
    'MException'
    'java.io.File'
    'MultiCoordinateFrame'
but 
matlab -nodisplay -r "addpath_drake; r = RigidBodyManipulator('examples/Acrobot/Acrobot.urdf'); x0 = resolveConstraints(r,zeros(getNumStates(r),1)); [m,x,c] = inmem; c, clear MultiCoordinateFrame MException message containers.Map java.lang.String java.io.File; [m,x,c]=inmem; c, clear java; which('LinearSystem');"

doesn't fix it.

commented out warning_manager (to get rid of containers.Map) and the hash_map in CoordinateFrame (to get rid of java.lang.String), still get failures.

this also fails:

matlab -nodisplay -r "addpath_drake; r = LinearSystem(1,1,[],[],1,1); x0 = resolveConstraints(r,zeros(getNumStates(r),1)); [m,x,c] = inmem, clear java; [m,x,c] = inmem, which('LinearSystem');"

this fails:
matlab -nodisplay -r "addpath_drake; r = LinearSystem(1,1,[],[],1,1); cd solvers/test; testNLP; [m,x,c] = inmem, clear java; [m,x,c] = inmem, which('LinearSystem');"

this fails:
matlab -nodisplay -r "addpath_drake; r = LinearSystem(1,1,[],[],1,1); nlp0 = NonlinearProgram(0); sol = nlp0.solve([]); [m,x,c] = inmem, clear java; [m,x,c] = inmem, which('LinearSystem');"

this showed something new:
matlab -nodisplay -r "addpath_drake; r = LinearSystem(1,1,[],[],1,1); checkDependency('snopt'); [m,x,c] = inmem, clear java; [m,x,c] = inmem, which('LinearSystem');"

output (after the 2nd inmem): 
Error using DrakeSystem.DrakeSystem>create@(varargin)obj.update(varargin{:})
Too many input arguments.

it failed when I ran which('LinearSystem') manually, but then passed when I tried running the entire thing again.

this failed:
matlab -nodisplay -r "addpath_drake; r = LinearSystem(1,1,[],[],1,1); clear java; checkDependency('snopt'); [m,x,c] = inmem, clear java; [m,x,c] = inmem, which('LinearSystem');"

this passed:
matlab -nodisplay -r "addpath_drake; r = LinearSystem(1,1,[],[],1,1); clear classes; checkDependency('snopt'); [m,x,c] = inmem, clear java; [m,x,c] = inmem, which('LinearSystem');"

so did this!
matlab -nodisplay -r "addpath_drake;  clear classes; r = LinearSystem(1,1,[],[],1,1);checkDependency('snopt'); [m,x,c] = inmem, clear java; [m,x,c] = inmem, which('LinearSystem');"

removed javaaddpath from addpath_drake.  this still fails:
matlab -nodisplay -r "addpath_drake; r = LinearSystem(1,1,[],[],1,1); checkDependency('snopt'); [m,x,c] = inmem, clear java; [m,x,c] = inmem, which('LinearSystem');"

trying to zap a bunch from addpath_drake.m.  this failed:  
matlab -nodisplay -r "addpath_drake; r = LinearSystem(1,1,[],[],1,1); checkDependency('snopt'); [m,x,c] = inmem, h=findobj, clear java; [m,x,c] = inmem, which('LinearSystem');"

this passed:  (!)
matlab -nodisplay -r "addpath_drake; DrakeSystem(0,0,0,0,false,true); checkDependency('snopt'); [m,x,c] = inmem, h=findobj, clear java; [m,x,c] = inmem, which('LinearSystem');"

this passed:
matlab -nodisplay -r "addpath_drake; PolynomialSystem(0,0,0,0,false,true,false); checkDependency('snopt'); [m,x,c] = inmem, h=findobj, clear java; [m,x,c] = inmem, which('LinearSystem');"

this passed:
matlab -nodisplay -r "addpath_drake; LinearSystem([],[],[],[],[],[]); checkDependency('snopt'); [m,x,c] = inmem, h=findobj, clear java; [m,x,c] = inmem, which('LinearSystem');"

this failed:
matlab -nodisplay -r "addpath_drake; r = LinearSystem([],[],[],[],[],[]); checkDependency('snopt'); [m,x,c] = inmem, h=findobj, clear java; [m,x,c] = inmem, which('LinearSystem');"

this passed:
matlab -nodisplay -r "addpath_drake; r = DrakeSystem(0,0,0,0,false,true); checkDependency('snopt'); [m,x,c] = inmem, h=findobj, clear java; [m,x,c] = inmem, which('LinearSystem');"

this passed:
matlab -nodisplay -r "addpath_drake; r = PolynomialSystem(0,0,0,0,false,true,false); checkDependency('snopt'); [m,x,c] = inmem, h=findobj, clear java; [m,x,c] = inmem, which('LinearSystem');"

this failed:
matlab -nodisplay -r "addpath_drake; r = AffineSystem([],[],[],[],[],[],[],[],[]); checkDependency('snopt'); [m,x,c] = inmem, h=findobj, clear java; [m,x,c] = inmem, which('LinearSystem');"

commented out everything in the AffineSystem constructor except the minimal (calling polynomialsystem), and it still failed.

this failed:
matlab -nodisplay -r "addpath_drake; r = AffineSystem([],[],[],[],[],[],[],[],[]); checkDependency('snopt'); [m,x,c] = inmem, clear checkDependency; clear java; [m,x,c] = inmem, which('LinearSystem');"


wow, this failed (snopt is exonerated):
matlab -nodisplay -r "addpath_drake; r = AffineSystem([],[],[],[],[],[],[],[],[]); checkDependency('fmincon'); [m,x,c] = inmem, clear java; [m,x,c] = inmem, which('LinearSystem');"

this passes:
matlab -nodisplay -r "addpath_drake; r = AffineSystem([],[],[],[],[],[],[],[],[]); checkDependency('fmincon'); [m,x,c] = inmem, clear java; [m,x,c] = inmem, which('AffineSystem');"

cd into systems directory, and this still runs and fails:
matlab -nodisplay -r "addpath('../util'); addpath('frames'); r = AffineSystem([],[],[],[],[],[],[],[],[]); checkDependency('fmincon'); [m,x,c] = inmem, clear java; [m,x,c] = inmem, which('LinearSystem');"

commented out coordinate frame calls in DrakeSystem, and this still fails:
matlab -nodisplay -r "addpath('../util'); r = AffineSystem([],[],[],[],[],[],[],[],[]); checkDependency('fmincon'); [m,x,c] = inmem, clear java; [m,x,c] = inmem, which('LinearSystem');"

even this fails:
matlab -nodisplay -r "r = AffineSystem([],[],[],[],[],[],[],[],[]); [m,x,c] = inmem, clear java; [m,x,c] = inmem, which('LinearSystem');"
matlab -nodisplay -r "r = AffineSystem([],[],[],[],[],[],[],[],[]); clear java; which('LinearSystem');"

this still succeeds:
matlab -nodisplay -r "r = PolynomialSystem(0,0,0,0,false,true,false); [m,x,c] = inmem, clear java; [m,x,c] = inmem, which('LinearSystem');"



current minimal failure example:
matlab -nodisplay -r "r = AffineSystem([],[],[],[],[],[],[],[],[]); clear java; which('LinearSystem');"

now, if I comment out the line 381 which references LinearSystem, then it passes!

...

**Comment by avalenzu** [comment]
We should definitely submit this one to the MathWorks too.

**Comment by RussTedrake** [comment]
already done:  
https://mathworksservicerequest.secure.force.com/apex/cp_case_detail?id=500i000000OVeITAA1&isnew=yes&cc=us#

**Comment by RussTedrake** [comment]
note also that changing `clear java;` to `clear java; clear classes` avoids the crash.

**Comment by RussTedrake** [comment]
Hello Russ, 

I am writing in reference to your Technical Support Case #01337410 regarding 'Bug in 2014a 64-bit ubuntu OO logic'. 

Thank you for contacting MathWorks. I believe that you found a bug while working with classes. 

The reproduction steps have been helpful. I have been able to successfully reproduce the issue on Ubuntu with MATLAB release R2014a. However, this issue is not reproducible with R2015a. 

As a workaround for now, you can use R2015a release which can be downloaded as you have valid SMS with your license. 

I will be investigating this bug further with my colleagues and I will get back to you with updates as soon as possible.
