### ISSUE TITLE
Re-create Atlas examples

### ISSUE THREAD

**Issue by jwnimmer-tri** [RobotLocomotion/drake#6381]
PR #6367 removed Drake's MATLAB implementation of many Atlas examples.  We should re-create these examples.

**Comment by RussTedrake** [comment]
@rahulyesantharao has a draft of @rdeits mixed-integer footstep planning code written in pydrake mathematical program at https://github.com/rahulyesantharao/drake-new-code

**Comment by rcywongaa** [comment]
Hi! I have an incredibly inefficient draft of @kuindersma An Efficiently Solvable Quadratic Program for Stabilizing Dynamic Locomotion at https://github.com/rcywongaa/humanoid that I've been working on for a little over half a year.

Any comments/feedback/pointers will be greatly appreciated!
