### ISSUE TITLE
Bazel install framework should not need to jump through hoops to derive original partial paths

### ISSUE THREAD

**Issue by mwoehlke-kitware** [RobotLocomotion/drake#6385]
See bazelbuild/bazel#3227. When (if) this is fixed, we should:

- [ ] Use it, drastically simplifying at least `output_path` and refactoring how `allowed_externals is applied.
- [ ] Adjust the "foreign files" warning to not warn about files in the same workspace but different packages.
- [ ] Audit uses of `allowed_externals` and remove instances made unnecessary by the previous item.

**Comment by jwnimmer-tri** [comment]
Given the lack of motion on the bazelbuild issue, and that we've lived with this for two years without too much trouble, I think this cleanup-related backlog issue can be closed.  Please feel free to reopen if there's some benefit or new plan to address it.
