### ISSUE TITLE
Evaluate using Bullet's regular collision detection (not closest distance) for simulation

### ISSUE THREAD

**Issue by avalenzu** [RobotLocomotion/drake#640]

**Comment by RussTedrake** [comment]
@psiorx -- would you weight in on this one?  should we keep this open and consider it in the future, or do we know enough now to close it out?

**Comment by psiorx** [comment]
Barring the remaining parts of terrain contact and height maps, all of the collision detection functionality we need from bullet is now in and working.

I think this is safe to close.
