### ISSUE TITLE
Ensure low-level unittests for DircolTrajectoryOptimization cover cost

### ISSUE THREAD

**Issue by EricCousineau-TRI** [RobotLocomotion/drake#6427]
As pointed out in #3817 and #6223, ensuring the low-level unittests for `DircolTrajectoryOptimization` cover the cost can help to pinpoint the discrepancy in `DircolTrajectoryOptimization::DoAddRunningCost(const symbolic::Expression&)` between the code and the comment.

\cc @ggould-tri @jadecastro @RussTedrake

**Comment by hongkai-dai** [comment]
direct_collocation_test now checks the total cost.
