### ISSUE TITLE
Oversize PRs should have a nagbot or similar

### ISSUE THREAD

**Issue by jwnimmer-tri** [RobotLocomotion/drake#6436]
See https://github.com/RobotLocomotion/drake/pull/6338#issuecomment-310539421.  When a PR exceeds the hard line limit (or possibly even the soft one), a robot should somehow inform and/or shame the author -- rather than relying on code reviewer(s) to be the bad guy.

**Comment by jamiesnape** [comment]
I am sure @drake-jenkins-bot would be happy to nag.

**Comment by jwnimmer-tri** [comment]
We seem to be surviving without this, so I am inclined to close this, but I'm curious if others wish to keep it alive.

**Comment by EricCousineau-TRI** [comment]
I don't think I've heard anyone complain about inspecting PR sizes, so I'd be fine with closing it down as manual nagging seems sufficient :P
