### ISSUE TITLE
acrobot urdf

### ISSUE THREAD

**Issue by dhruba-chowdhury** [RobotLocomotion/drake#6455]
Hi i have my own set of parameters
m1,l1,lc1,i1,m2,l2,lc2,i2 for the acrobot
how can i use my parameters in the acrobot urdf.

And if possible if i have lumped parameters like
a1 = m2*lc2^2 + m1*l2^2 + i2
a2=m1*lc1^2 + I1 and so on
how do i include these lumped parameters on the urdf

Thanks

**Comment by RussTedrake** [comment]
we don't support parameters from urdf in the c++ parsers yet, I'm afraid.  

the lumped parameters will likely never come directly from urdf.  but we have code to extract the lumped parameters if the original parameters are identified (from urdf or otherwise).
