### ISSUE TITLE
Don't use genrule to compile IPOPT

### ISSUE THREAD

**Issue by jwnimmer-tri** [RobotLocomotion/drake#6513]
Using a `genrule()` to compile C++ software is frowned upon by Bazel upstream, but that's currently how we're building IPOPT.  We should either write `BUILD` file(s) for IPOPT, create a pre-compiled shared library release (e.g. with a Dockerfile), or use the OS's default build of IPOPT (debs /homebrew).  (The OS build may be insufficient; see #4913).

There are several problems with using a genrule:
- the compile step is slow (lots of software), and even with "half the cores" it takes a while locally and is worse in CI;
- because its a genrule, its dependencies are too wide (e.g. on environment variables) and thus it recompiles too often, such as when switching between CLion and console builds (see #6500);
- while we could pass `$COMPILATION_MODE` through the genrule (debug vs release), we cannot pass any other e.g. `$CXX` or `$CXXFLAGS` from `CROSSTOOL` into the compilation step.  Thus, our builds will _always_ use GCC for IPOPT, even if the user has otherwise selected `clang` as their compiler.

Probably the #4913 fix should be rolled into this effort.

**Comment by jamiesnape** [comment]
I have some Fortran rules that really just need some cleanup, and then we could build natively with Bazel.

**Comment by jwnimmer-tri** [comment]
See also #4913 where we are discussing what to do with IPOPT.
