### ISSUE TITLE
Orphaned MATLAB-related C/C++ and Java files

### ISSUE THREAD

**Issue by jamiesnape** [RobotLocomotion/drake#6517]
The following are unused and not included in any build files, whether Bazel or CMake:

C/C++:

* [LCMScope.h](https://github.com/RobotLocomotion/drake/blob/master/drake/matlab/util/LCMScope.h)
* [makeFunction.h](https://github.com/RobotLocomotion/drake/blob/master/drake/matlab/util/makeFunction.h)
* [mexify.h](https://github.com/RobotLocomotion/drake/blob/master/drake/matlab/util/mexify.h)
* [standardMexConversions.h](https://github.com/RobotLocomotion/drake/blob/master/drake/matlab/util/standardMexConversions.h)

Java:

* [BotLCMGLClient.java](https://github.com/RobotLocomotion/drake/blob/master/drake/matlab/util/BotLCMGLClient.java)
* [CoordinateFrameData.java](https://github.com/RobotLocomotion/drake/blob/master/drake/matlab/util/CoordinateFrameData.java)
* [MyLCMTypeDatabase.java](https://github.com/RobotLocomotion/drake/blob/master/drake/matlab/util/MyLCMTypeDatabase.java)
* [LCMCoder.java](https://github.com/RobotLocomotion/drake/blob/master/drake/matlab/util/LCMCoder.java)
* [MessageMonitor.java](https://github.com/RobotLocomotion/drake/blob/master/drake/matlab/util/MessageMonitor.java)
* [Transform.java](https://github.com/RobotLocomotion/drake/blob/master/drake/matlab/util/Transform.java)

Should they be compiled into something or removed?

_Edited to add (jwnimmer-tri): Relates #6369_.

**Comment by jamiesnape** [comment]
And just to double check, it is correct that we are still using [barycentricInterpolation.cpp](https://github.com/RobotLocomotion/drake/blob/master/drake/matlab/util/barycentricInterpolation.cpp), [lcmLogger.cpp](https://github.com/RobotLocomotion/drake/blob/master/drake/matlab/util/lcmLogger.cpp),  and [realtime.cpp](https://github.com/RobotLocomotion/drake/blob/master/drake/matlab/util/realtime.cpp)?

**Comment by RussTedrake** [comment]
not using any of those three anymore.

**Comment by jamiesnape** [comment]
Can anything in the top list be removed?

**Comment by RussTedrake** [comment]
the mexify tools are a strong candidate for writing our matlab bindings when we start using them again.  But given the matlab code has been zapped, it is not being used now.   i think it's aok to zap everything on the top list as well.   cc @jwnimmer-tri

**Comment by jwnimmer-tri** [comment]
SGTM.  git remembers.
