### ISSUE TITLE
Update drakeURDF.xsd

### ISSUE THREAD

**Issue by SeanCurtis-TRI** [RobotLocomotion/drake#6518]
The XML Schema Definition (xsd) file in which we elaborate Drake's support for URDF features (particularly with regards to Drake-specific features) has fallen out of sync with the current code/functionality. It needs to be triaged and updated so that Drake's functional state is reflected in the document.

This arose in a discussion of a PR extending this functionality with a ball joint: https://reviewable.io/reviews/robotlocomotion/drake/6489#-KoNVLpgYWG4FywxzM6q:-KoNcONwt2sybgUsB0bo:b-d2fwnl

**Comment by EricCousineau-TRI** [comment]
This has cropped up in #11589. Should we upgrade priority, as the file seems to be more of a distraction than anything?

**Comment by SeanCurtis-TRI** [comment]
Do we actually validate against it? Do we plan on validating against it? What's the cost of maintaining it vs the value of having it up to date?

**Comment by EricCousineau-TRI** [comment]
I don't think so. I'm OK with "delete this file" as being *part* of the solution; that's better than it being a lie.

However, at some point, we *should* introduce something that defines what modifications we have on top of URDF / SDFormat that are actively being used, and should validate against it. However, that can be split off as a separate issue.

Does that sound good to you? If so, I'll create the issue for it.

**Comment by SeanCurtis-TRI** [comment]
A year later, I'm coming back to this.

1. I think #11589 was the wrong link.
2. Between deleting the lie and keeping the lie, deleting is definitely preferred.
3. Between deleting the lie and stoppping the lie, stopping is definitely preferred.

**Comment by EricCousineau-TRI** [comment]
> I think #11589 was the wrong link.

I mean, MOSEK relates to everything, no? :P (sorry about that!)

And yeah, ideal is stopping the lie. However, I'm up for deleting the lie for short term!

**Comment by SeanCurtis-TRI** [comment]
1-2-3 NOT IT!  :finger_on_nose:

**Comment by EricCousineau-TRI** [comment]
As far as the "split off on separate issue", I think that is now covered by https://github.com/RobotLocomotion/drake/issues/13103 - it's already on me, so I'm good there.

Would you be able to take on deleting the file? (I know this is against the rules... but I play dirty!)

**Comment by SeanCurtis-TRI** [comment]
Yeah. I think I'm just about up to the task.
