### ISSUE TITLE
Issue Building Drake with ROS

### ISSUE THREAD

**Issue by cirpote** [RobotLocomotion/drake#6575]
Ciao,

I am trying to build drake with ROS Kinetic on my laptop (with Ubuntu 16.04) following your guide, [Building Drake as a Catkin Package in ROS](http://drake.mit.edu/from_source_ros_kinetic.html) but i get this error:

![drake_error](https://user-images.githubusercontent.com/7804435/28202291-f1fa7848-6874-11e7-99b2-39916e9605e7.png)

This error happens after the first tentative of building since there is no VTK5 installed on my laptop and i need to build it directly from source. Following your guide i to set -DUSE_SYSTEM_VTK=OFF -DWITH_VTK=ON, but actually both flags do not exist and are not settable.

Recompiling i get again the above error.

**Comment by liangfok** [comment]
Hi @cirpote, which commit SHA are you using? I just want to confirm you're using the latest version of Drake. You can view the SHA by executing:

```
git log -1 --format="%H"
```

**Comment by cirpote** [comment]
I am using this version:

80b0dfeff71e3681d26e48a97da6f762fece00c9

**Comment by liangfok** [comment]
I'll try to replicate the error later this morning. I suspect #6476 may be related.

**Comment by jamiesnape** [comment]
You would need to switch `WITH_DIRECTOR=OFF`.

**Comment by cirpote** [comment]
Now it's working! thanks a lot
