### ISSUE TITLE
kcov is not working in Ubuntu

### ISSUE THREAD

**Issue by soonho-tri** [RobotLocomotion/drake#6603]
Recently @hongkai-dai and I found that `bazel test --config=kcov` is not working in Ubuntu. Here is a screenshot showing its symptom.

<img width="880" alt="68747470733a2f2f66696c65732e72657669657761626c6575736572636f6e74656e742e696f2f696d616765732f72657669657761626c652f32303737393736372f4d6a5573795a4370507647504c6174536d733446786a4e542f53637265656e25323053686f74253230323031372d30372d3137253230" src="https://user-images.githubusercontent.com/20779767/28380656-1440265e-6c86-11e7-8743-e369cf50dd15.png">

We've tried different versions of `kcov` including `v32`, `v33`, `v34`, and the `master` of https://github.com/SimonKagstrom/kcov. None of them is working in Ubuntu, which makes us suspect that it's the new version of `bazel` which causes this problem. 

Interestingly, in OSX, bazel kcov is working as expected (for example, `bazel-0.5.2-homebrew` + `kcov v32-6-g045d4`).

**Comment by rpoyner-tri** [comment]
The symptom is a result of changes in bazel itself, between release versions 0.4.5 (works) and 0.5.0 (kcov broken). Specifically, commit f396da66ac2421373172e88538066051a22f0309 in the bazel source repo is where things stop working.

Don't know why yet, but at least we know when and where.

**Comment by rpoyner-tri** [comment]
Roughly speaking, `kcov` cannot find the project source code under the new bazel execution environment. Without the source code, it can't build its coverage report.

There is some wiggle room to finesse the file finding; haven't quite found the right solution yet.

**Comment by rpoyner-tri** [comment]
Closing; fixed by https://github.com/RobotLocomotion/drake/pull/6880 .
