### ISSUE TITLE
MeshPoints geometry type is now unused

### ISSUE THREAD

**Issue by avalenzu** [RobotLocomotion/drake#6644]
This poorly named class represents the convex hull of a set of points. Back in the mists of time, it was used when creating a C++ RBT from a MATLAB one. Now that MATLAB RBT is gone, there is nothing in Drake or Spartan that constructs `MeshPoints` instances. I propose removing this class.

@sammy-tri, @siyuanfeng-tri, @SeanCurtis-TRI (or anyone else) any objections?

**Comment by SeanCurtis-TRI** [comment]
No complaints from me.

**Comment by siyuanfeng-tri** [comment]
I haven't run into this, so no complaints from me either.

**Comment by tri-ltyyu** [comment]
Please use MBP instead. If it's still an issue, please open new issue.
