### ISSUE TITLE
LCMGL doesn't render inertial ellipsoids in drake-visualizer

### ISSUE THREAD

**Issue by zamzami** [RobotLocomotion/drake#6666]
I'm trying to visualize the inertial ellipsoids and would also like to send ellipsoids that I calculate during the motion to perform some sort of trajectory analysis. 
 
A quick hack in #603 is a good place to start however upon executing the following commands I can see Atlas but not the ellipsoids. 
```
urdf = [getDrakePath,'/examples/Atlas/urdf/atlas_minimal_contact.urdf'];
robot = RigidBodyManipulator(urdf,options);
v=robot.constructVisualizer
v=v.enableLCMGLInertiaEllipsoids();
nomdata = load([getDrakePath,'/examples/Atlas/data/atlas_fp.mat']);
nq = robot.getNumPositions();
qstar = nomdata.xstar(1:nq);
v.draw(0,qstar)
```
I checked  `LCM Spy` and found the the LCMGL channel is well established and data is being sent over, but i'm not sure if that seems correct. Here is a screenshot. 

<img width="1009" alt="screen shot 2017-07-26 at 01 45 43" src="https://user-images.githubusercontent.com/9399029/28598682-86e44acc-71a5-11e7-8f89-1c94b76ce326.png">

/CC @patmarion

**Comment by RussTedrake** [comment]
@zamzami -- i'm thrilled to see you using drake, but we need to get you over to the new workflow.  I don't have the cycles to support the deprecated APIs.
