### ISSUE TITLE
Retrieve documentation for IK constraints that was lost in the MATLAB purge

### ISSUE THREAD

**Issue by avalenzu** [RobotLocomotion/drake#6667]
#6420 removed the MATLAB implementations of the constraint classes used in IK. For most of those classes, the documentation resided in the MATLAB implementation, as that was the user visible portion of the original design. That documentation should be retrieved and added to the C++ code where appropriate.

**Comment by hongkai-dai** [comment]
in `multibody/inverse_kinematics` folder, all the constraints have nice documentation.
