### ISSUE TITLE
fastQP lcp solve reports success for a case where it is clearly failing

### ISSUE THREAD

**Issue by RussTedrake** [RobotLocomotion/drake#668]
it's for a case with position constraints, where lb = -Big.  it could be that the numerics of Big are throwing it off?  or that the lb is not handled everywhere.  @kuindersma - can you take a look?

to reproduce, you can run the tension.m example in my pull request #666 , but revert the change that I made to the initial guess for M_active in solveLCP.

**Comment by RussTedrake** [comment]
Thanks Scott.  Two things:  I propose that we change
```
min ||z||

subject to:
M*z + w >= 0
z>=lb
```
to
```
min z

subject to:
M*z + w >= 0
z>=lb
```
When `lb==0`, they should behave similarly, but it should also do better when `lb<<0`.  

But even if the code remains as before, the code should realize that it failed to solve the mcp and fall over to pathlcp.  Right?

**Comment by kuindersma** [comment]
How about something like: ``` min ||z-lb|| ``` (the above objective is non-scalar)? 

And yes, I can add a more comprehensive check there to be safe. The problem was that we were not passing in a consistent LCP active set on the first time step, so the assumption that the QP was taking care of certain checks was false.

**Comment by RussTedrake** [comment]
i mean the l1 norm of z.  that seems better to me because I was worried about putting inf into the objective.

**Comment by kuindersma** [comment]
Ah ok. Do you expect this will improve active-set performance in some way? It seems to be working well with ||z||. Without modifying the fastQP algorithm, I think we'll still need a (small) l2 regularization term in there (we require H to be positive definite).

**Comment by RussTedrake** [comment]
I think the objective is wrong if lb neq 0?  And i just think min sum z is better than min ||z - inf||_2

- Russ

**Comment by RussTedrake** [comment]
in fact, might it also make sense to include the l1 norm of M*z + w in the objective, too?  (encouraging sparsity in the hopes of the optimal solution also being a solution to the lcp?)

**Comment by kuindersma** [comment]
I agree the objective isn't quite as meaningful if lb is not zero, but I don't think it is having a significant practical impact on the simulation of position constrained systems (unless I missed something). Unfortunately, fastQP doesn't like when H is small (where obj = z'Hz + f'z), so we'd have modify the solver (fastLP? :) to implement this.

**Comment by RussTedrake** [comment]
got it. thanks.

did we resolve the fact that the solution not being a solution to the mcp was not caught?

**Comment by kuindersma** [comment]
I'll send a pull request for that part shortly
