### ISSUE TITLE
Testing call_matlab_client

### ISSUE THREAD

**Issue by RussTedrake** [RobotLocomotion/drake#6707]
The newer version of CallMatlab writes to a file (via protobuf) during execution of the c++ program; then you can run matlab at any time on that file to visualize the results.  I would like to put test coverage not only on the call_matlab_client implementation, but also the matlab code inside the c++.  What's the right way to do this in our current testing framework?

I think i'd basically like to do a (cmake) add_matlab_test that calls the c++ target first, then calls the matlab client and makes sure it terminates without errors.  I also want to plan ahead for the near future when the c++ is only available via bazel, even though the matlab client is only available/testable via cmake.

**Comment by jamiesnape** [comment]
Can you share a MATLAB script that would (roughly) implement the test?

**Comment by jamiesnape** [comment]
Aside: This TODO needs to be implemented for CI: https://github.com/RobotLocomotion/drake/blob/master/drake/matlab/util/call_matlab_client.cc#L33-L34
We cannot guarantee that a location in `/tmp` will be writeable and if it is, whether it will be cleaned up between successive builds.

**Comment by RussTedrake** [comment]
understood that we need to implement the file name option.  Then call_matlab_client would be the (only) command that matlab runs; if it completes without errors then the test passes.

**Comment by jwnimmer-tri** [comment]
I haven't entirely studied where all the pieces come from, but if for some reason running both programs (client and server) in the same build is difficult, then we could also commit the intermediate file, and one one side test that the C++ program emits exactly those bytes, and that those bytes fed into MATLAB pass the test.  And if the bytes ever need to change (unlikely), we just commit whatever the C++ is emitting at the time.

**Comment by RussTedrake** [comment]
fyi -- i have a WIP for this now.  and I've confirmed that an updated version of the symlink instructions in #960 are still mandatory for matlab 2017a on ubuntu.  @pangtao22 -- perhaps something similar is happening to you on mac?

**Comment by EricCousineau-TRI** [comment]
No longer relevant given resolution in #11753. Closing.
