### ISSUE TITLE
We have both drake::SpatialForce and drake::multibody::SpatialForce defined

### ISSUE THREAD

**Issue by sherm1** [RobotLocomotion/drake#6731]
drake::SpatialForce is defined in common/eigen_types.h basically as a typedef for a Vector6, and is only lightly used within RigidBodyPlant and Valkyrie. OTOH, drake::multibody::SpatialForce is a force-space SpatialVector providing essential functionality in the new MultibodyTree code. 

The names conflict in typical programs that include namespace drake and drake::multibody (discovered by @mitiguy while making multibody tests). We should get rid of the typedef asap. Since the code it is in will soon be deprecated, it would be fine to give it a somewhat awkward name like RBSpatialForce. Many other solutions are possible.

**Comment by amcastro-tri** [comment]
Thank you for filing this issue, I had forgotten about this typedef.

**Comment by amcastro-tri** [comment]
This is the typedef in `eigen_types.h`:
`template <typename Scalar> using SpatialForce = Eigen::Matrix<Scalar, 6, 1>;`

Within the same file we have a more appropriate typedef for this, `Vector6<T>`, in consistency with all other typedefs in the same file. If you all agree I will go ahead and replace `drake::SpatialForce<T>` with `drake::Vector6<T>` to avoid any possible collisions for now until this code is deprecated. RBP and Valkyrie code could actually be easily update to use `drake::multibody::SpatialForce<T>`.

**Comment by sherm1** [comment]
Per f2f we need to look more closely at @mitiguy's test to see why he's seeing a conflict but @amcastro-tri doesn't.

**Comment by sherm1** [comment]
Recently rediscovered. Relevant [Slack discussion](https://drakedevelopers.slack.com/archives/C2ETTRXT7/p1555512929000900).

**Comment by amcastro-tri** [comment]
12 uses of `SpatialForce<double>` in the attic. We could replace with `Vector6<double>` and remove `drake::SpatialForce` from `eigen_types.h`?
