### ISSUE TITLE
AMIs for Xenial CI are missing /usr/bin/clang-format-3.9

### ISSUE THREAD

**Issue by jwnimmer-tri** [RobotLocomotion/drake#6742]
The build failures in #6741 are consistent with our Xenial CI images having `/usr/bin/clang-format` installed but `/usr/bin/clang-format-3.9` missing.  Per the `install_prereqs.sh` script change at 44691518196c66c074f7cabf1c65222eeb923b13, it should be the other way around.

**Comment by jamiesnape** [comment]
AMI had been updated.

**Comment by jwnimmer-tri** [comment]
This is great!  But it looks like it also ate the Bazel 0.5.3 upgrade, so install-related tests are failing now.

**Comment by jamiesnape** [comment]
Reverted. Not sure how that happened. New AMI will be up shortly.

**Comment by jamiesnape** [comment]
New AMI is enabled. It will take a while to cycle through as there are a lot of Xenial nodes up at the moment.
