### ISSUE TITLE
Installed SDFormat library missing dependencies

### ISSUE THREAD

**Issue by stonier** [RobotLocomotion/drake#6746]
```
$ ldd /opt/drake/lib/libsdformat.so
linux-vdso.so.1 =>  (0x00007fff73158000)
libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f136ba5d000)
libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f136b754000)
libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f136b53d000)
libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f136b173000)
/lib64/ld-linux-x86-64.so.2 (0x000055e3e620d000)
```

Seems to be missing both `libignition_math.so` and `libtinyxml.so`.

These problems are turning up when trying to link the example in https://github.com/RobotLocomotion/drake-shambhala/pull/22 -> undefined references to `TiXml***`. Since the example does not use these directly, they should be transitively picked up by a dependency on `sdformat`.

It looks like tinyxml is missed in [sdformat-create-cps.py](https://github.com/RobotLocomotion/drake/blob/master/tools/sdformat-create-cps.py) and both tinyxml and ignition math missed in the component dependencies. This does not explain why the installed `libsdformat.so` doesn't get linked against these libraries though.

**Comment by jamiesnape** [comment]
The linking issue is a long-standing Bazel problem. We can certain update the CPS to ameliorate it, though.

**Comment by jamiesnape** [comment]
https://github.com/bazelbuild/bazel/issues/492
