### ISSUE TITLE
Update MATLAB FAQs and simplify JVM warning in addpath_drake.m

### ISSUE THREAD

**Issue by jamiesnape** [RobotLocomotion/drake#6761]
From https://github.com/RobotLocomotion/drake/pull/6725#issuecomment-319947025:

> I think we should create a section in the docs and just say here in one line: WARNING: Your JVM may crash if you do not set it to prefer IPv4 over IPv6, see <link to section in docs>. The docs should include a link to https://www.mathworks.com/help/matlab/matlab_env/java-opts-file.html. On that note, I think most of matlab_faq.rst can be removed. We do not use the MEX compiler wrapper, the versions of Xcode referenced are very old, and we already support newer Java.

**Comment by RussTedrake** [comment]
Won't fix. (at least for now)
