### ISSUE TITLE
Modernize cpplint_wrapper.py

### ISSUE THREAD

**Issue by jwnimmer-tri** [RobotLocomotion/drake#6770]
Right now, `cpplint_wrapper.py` calls out to the `git submodule` flavor of `google_styleguide`.  We want to stop using submodules, so at a minimum it needs to switch over Bazel's download of the tool.  Possibly the script should disappear entirely, now that "lint all the files" is part of the build system.  If so, we'll need to update `drake/doc/clion.rst` with the new recipe.

**Comment by SeanCurtis-TRI** [comment]
Just to echo a point previously discussed in a slack conversation.  The "lint all the files" of the current state of affairs produces feedback of the form `[relative file name]:[line number]`. In its infinite wisdom, CLion can only turn *absolute* paths into clickable links. So, if/when we pull the trigger on this, we either need to make paths absolute (at least configurable to such) or update the clion documentation to eliminate the external tool that recommends this tool.

**Comment by jwnimmer-tri** [comment]
See also #6767 re: paths.
