### ISSUE TITLE
CI Failure - "Could not get lock /var/lib/dpkg/lock"

### ISSUE THREAD

**Issue by liangfok** [RobotLocomotion/drake#6821]
The following is an example error:

```
10:52:22 E: Could not get lock /var/lib/dpkg/lock - open (11: Resource temporarily unavailable)
10:52:22 E: Unable to lock the administration directory (/var/lib/dpkg/), is another process using it?
```

It is happening to various [nightly-production configurations](
https://drake-jenkins.csail.mit.edu/view/Nightly%20Production/) involving `linux-xenial-unprovisioned`.

![screenshot from 2017-08-11 10-58-25](https://user-images.githubusercontent.com/1388098/29218811-071621f8-7e84-11e7-9355-8244c646c9f8.png)

**Comment by jwnimmer-tri** [comment]
Transient problem, not relevant anymore.
