### ISSUE TITLE
Insufficient test coverage for LcmDrivenLoop

### ISSUE THREAD

**Issue by siyuanfeng-tri** [RobotLocomotion/drake#6828]
There are no stress tests for LcmDrivenLoop to catch any threading related bugs. 
A way to do so is keeping a reasonably long log in master, and write tests against it. 
Any comments on how to proceed would be very welcome here.

**Comment by jwnimmer-tri** [comment]
For stress testing, just generating synthetic data on the fly seems like it should be good enough.

**Comment by EricCousineau-TRI** [comment]
@siyuanfeng-tri Have we felt any pain from this? I don't think we have, so I'd say we could prolly close this issue?

**Comment by jwnimmer-tri** [comment]
Resolved via #11281.
