### ISSUE TITLE
AddLinearConstraint(Formula) cannot accept limits at infinity

### ISSUE THREAD

**Issue by RussTedrake** [RobotLocomotion/drake#6836]
If a user passes in `inf` or `-inf` into as part of a symbolic formula, the resulting constraints will have `lb` or `ub = NaN`.  This happens in 
https://github.com/RobotLocomotion/drake/blob/master/drake/automotive/test/trajectory_optimization_test.cc#L52
and happens because of the logic here:
https://github.com/RobotLocomotion/drake/blob/master/drake/solvers/create_constraint.cc#L127
(which ultimately results in `-inf + inf = nan` or `inf - inf = nan`).

fyi @jadecastro -- this is very possibly the reason why ipopt was performing so badly on the trajectory optimization example with simple cars.  it's probably worth trying ipopt again once this is resolved.

**Comment by RussTedrake** [comment]
my mistake.  it doesn't happen on master (i had local mods).  but it can be reproduced in the automotive example by inserting at the location above
```
prog.AddLinearConstraint(lower_limit.get_value() <= prog.input(0));
prog.AddLinearConstraint(prog.input(0) <= upper_limit.get_value());
```

**Comment by soonho-tri** [comment]
@RussTedrake , I'm working on the fix. Thanks for the report.

**Comment by soonho-tri** [comment]
> fyi @jadecastro -- this is very possibly the reason why ipopt was performing so badly on the trajectory optimization example with simple cars. it's probably worth trying ipopt again once this is resolved.

@jadecastro , this is issue is fixed in `master`. Could you test it with `ipopt`? Thank you.

**Comment by jwnimmer-tri** [comment]
@soonho-tri When running unit tests (such as automotive trajectory optimization) in debug mode, if we are computing with `NaN`s then we should have been failing-fast, not taking a stupid-long time.  If indeed that's what was happening, please open an issue to add `DRAKE_ASSERT(!std::isnan(stuff))` to enough places that we would have caught this earlier.

**Comment by soonho-tri** [comment]
I see. 

I've added `DRAKE_DEMAND(!std::isnan(...))` in #6849. I will check the other files and add more.

**Comment by RussTedrake** [comment]
My apologies.  The nan issue was not in master before (see my clarification above).  But indeed, it was not failing fast on my branch... it took some digging to discover it.

**Comment by soonho-tri** [comment]
Not a problem. I believe that the bomb was there and it was just a matter of time to trigger it. I believe that the symbolic code under `common` directory is good, but maybe the code under `solvers` is not as good. As @jwnimmer-tri suggested, I'll inspect them asap.

**Comment by jadecastro** [comment]
I compared pre- and post-PR commits the test using IPOPT and there's absolutely no change to resulting trajectory, which I think is expected.
(I did not try to recreate the result when replacing `AddInputBounds()` with `AddLinearConstraint()`, however.)

**Comment by soonho-tri** [comment]
Good to know. Thanks for the check, @jadecastro !
