### ISSUE TITLE
IK Traj: MultipleTimeKinematicConstraints are not being evaluated

### ISSUE THREAD

**Issue by avalenzu** [RobotLocomotion/drake#6893]
This is related to #6892. The only place that `MultipleTimeKinematicConstraints` would be evaluated is inside `IKInbetweenConstraint`. Since that's not being added to the mathematical program as described in #6892, these constraints are never evaluated.

**Comment by hongkai-dai** [comment]
We don't support iktraj any more. I will close this issue.
