### ISSUE TITLE
UBSan Failure in run_quadrotor_dynamics_test

### ISSUE THREAD

**Issue by m-chaturvedi** [RobotLocomotion/drake#6908]
`bazel test  -c  dbg --copt -O0 --config=ubsan --test_output=all //drake/examples/quadrotor:run_quadrotor_dynamics_test`

The errors seems to be due to run-time overflow when converting double to float, [here](https://github.com/RobotLocomotion/drake/blob/master/drake/multibody/rigid_body_plant/viewer_draw_translator.cc#L69).  The LCM structure has floats which are trying to store doubles.

**Comment by stonier** [comment]
@naveenoid *bump* this is the last one to close out the sanitiser jobs we are setting up, do you have an ETA for us? ;)

**Comment by naveenoid** [comment]
OK working on it right now. ETA today

**Comment by naveenoid** [comment]
WIP!

**Comment by m-chaturvedi** [comment]
Hi @naveenoid!  Did you get a chance to look at the problem?

**Comment by naveenoid** [comment]
Sadly still working on it since I didnt get much coding time. This afternoon I will spend time exclusively on this. Sorry again.

**Comment by m-chaturvedi** [comment]
That's alright.  Thanks!

**Comment by stonier** [comment]
@naveenoid need to get this resolved soon. If we let it slide too long, then there is a good chance we will have to repeat the cycle of bringing the quickly evolving codebase again up to the point where we can consider adding the sanitisers to the buildcop purview.

**Comment by jwnimmer-tri** [comment]
Did #7212 not resolve the problem?

**Comment by m-chaturvedi** [comment]
It did, we forgot to close the issue.   Closed via #7212 .

**Comment by stonier** [comment]
:+1:
