### ISSUE TITLE
Multiple shooting should use time as a decision variable instead of timesteps

### ISSUE THREAD

**Issue by RussTedrake** [RobotLocomotion/drake#6924]
It appears often in costs/constraints, and it seems overall better for maintaining sparsity (you can always get timestep out of two sample times, but it might take N timesteps to go the other direction).  It should be a pretty seamless change underneath the current api.

**Comment by hongkai-dai** [comment]
I think Andres is working on this? Reassign the issue to Andres.

**Comment by jwnimmer-tri** [comment]
@RussTedrake should we keep this open?  I'm inclined to say the work is "not planned" and close it.

**Comment by RussTedrake** [comment]
closing at "not planned"
