### ISSUE TITLE
Support RigidBodyManipulator collision filters via C++ construction

### ISSUE THREAD

**Issue by patmarion** [RobotLocomotion/drake#694]
Do you think there should be support for constructing a RBM from URDF in C++?  The drake-designer application does this, but some features are missing, such as parsing and initializing collision masks/filters.  In my project last semester I hacked a c++ version to support Atlas, but did not implement general purpose code.

**Comment by RussTedrake** [comment]
Yes, absolutely.  Twan's pending changes are the biggest upcoming changes to the c++ code, otherwise i don't see any obstructions to pushing this in.

- Russ

**Comment by RussTedrake** [comment]
c++ parser is now pretty far along.
