### ISSUE TITLE
Compute taylor expansion for symbolic expression

### ISSUE THREAD

**Issue by hongkai-dai** [RobotLocomotion/drake#6960]
When verifying stability using Sum of Squares, we need to approximate the dynamics as polynomials, using taylor expansion. We should consider that for a given symbolic expression, take the taylor expansion up to `N`th order. (Most likely N <= 3).

@soonho-tri @RussTedrake

**Comment by RussTedrake** [comment]
The obvious alternative is to use recursive autodiff.  Do we think that we'll ever want to do autodiff for systems that we can't support with symbolic?

**Comment by soonho-tri** [comment]
@hongkai-dai , FYI, implementing it shouldn't be difficult thanks to what we already have -- symbolic polynomial and `Differentiate` method.

**Comment by hongkai-dai** [comment]
@soonho-tri added the feature already.
