### ISSUE TITLE
Rework github.bzl to avoid git tgz checksums changing out from under us

### ISSUE THREAD

**Issue by jwnimmer-tri** [RobotLocomotion/drake#7003]
Our `master` was broken for a while, due to a GitHub OS upgrade.  We fixed it in #7002, but now bisecting is broken (modulo manual content-addressable-cache pre-seeding work-arounds), and we are still at risk of GitHub changing their implementation and disturbing the checksum again.

Note that this also broke protobuf archives as used by a wide community google/protobuf#3619.  The "Releases" page of protobuf advertises the https://github.com/google/protobuf/releases page, which has the download URLs with the time-varying-checksum bug.  Many others were affected too, e.g., kubernetes/kubernetes#52307.

GitHub's staff's summary of the intended semantics and hazards is posted at https://github.com/libgit2/libgit2/issues/4343#issuecomment-328631745.

We should update our "grab a certain commit from a github.com repository" implementation to avoid this pitfall.

**Comment by jwnimmer-tri** [comment]
(1) One method would be to fall back to our own mirrors if the github.com checksum failed (with some kind of telemetry to remind us to bump the checksum and re-mirror the source archive).  Our own mirrors should stay intact even if github's download morphs.  (Possibly we'd have to add the checksum to our mirror filename, since we'll now have multiple concurrently-hosted artifacts with the same commit or tag.)

(2) Another related option would be to stop pulling from github.com entirely, and only ever refer to our self-hosted mirrored releases (or possibly first-party hosting, if the project offers permanent source archives, rather than on-demand generated tarballs).

(3) Another method would be to avoid `new_http_archive` and instead roll our own in skylark, where we verify the integrity of the download with our own checksum that inspects the unpacked contents, instead of the source tarball.

Other proposals?

**Comment by jwnimmer-tri** [comment]
To +@stonier for delegation.

**Comment by jamiesnape** [comment]
(1) would be easiest.

> (Possibly we'd have to add the checksum to our mirror filename, since we'll now have multiple concurrently-hosted artifacts with the same commit or tag.)

Probably not. We only need one. If it matches the GitHub SHA then great, and we only use it if the GitHub HTTP download fails, otherwise we know the SHA so we download and compare as before. If we notice the mirror getting a lot of hits, we can update the archive either manually, or my hope is that it would be eventually be automatic.

Putting the CloudFront URL first would not be such as bad idea. Downloads of newly changed references should fall through to the GitHub archive.

**Comment by jwnimmer-tri** [comment]
@jamiesnape I think you have the best understanding of what (if anything) we should still improve, suggestions for next steps, and to help inform what the priority should be.

**Comment by jwnimmer-tri** [comment]
Hearing nothing, seems ok to close.
