### ISSUE TITLE
RigidBodyTree to MultibodyTree Feature Migration

### ISSUE THREAD

**Issue by avalenzu** [RobotLocomotion/drake#7025]
The purpose of this issue is to try to make sure that no existing functionality of RigidBodyTree/RigidBodyPlant is unintentionally lost in the transition to MultibodyTree/GeometryWorld. Each comment on this issue should name a feature of RigidBodyTree/RigidBodyPlant. If a feature you use has already been listed, please +1 the corresponding comment.

**Comment by avalenzu** [comment]
URDF/SDF parsing

**Comment by avalenzu** [comment]
Simulating multi-body systems without contact

**Comment by avalenzu** [comment]
Simulating multi-body systems with contact

**Comment by avalenzu** [comment]
Collision checking

**Comment by avalenzu** [comment]
Ray-casting

**Comment by avalenzu** [comment]
Computing separation/penetration distance

**Comment by sherm1** [comment]
Obtaining Jacobians (which ones?)

**Comment by EricCousineau-TRI** [comment]
For collision checking: signed distance functions

**Comment by manuelli** [comment]
Rigid body dynamics, H,C,B matrices.

**Comment by avalenzu** [comment]
Centroidal momentum matrix

**Comment by siyuanfeng-tri** [comment]
I'd like to have a first order system.

**Comment by sammy-tri** [comment]
Model-Instance-Centric Port Accessors (RigidBodyPlant)

**Comment by EricCousineau-TRI** [comment]
In conjunction with Sammy's comment, if we're going to use `MultibodyTree` as a world-representation, it'd be nice to have instance-centric properties directly available (not just ports, but getting variables / indices / whatever for a subset of an instance's joints within the tree, bodies for a given instance, etc.).

**Comment by manuelli** [comment]
Following up on Eric and Sammy's comments. I will mostly be using MultiBodyTree with a single robot, so just having the same easy to use functionality from RBT would be appreciated.

**Comment by EricCousineau-TRI** [comment]
As a nice-to-have, being able to copy portions of an already-constructed tree into a construction-in-progress tree.
(Example: From the monolithic pick-and-place, instantiating a KUKA arm within the world, adding a WSG gripper, and, when building the controller model, have the option to use the same model, but fixing / welding the gripper joints.)

**Comment by EricCousineau-TRI** [comment]
Per [comment](https://github.com/RobotLocomotion/drake/issues/7185#issuecomment-336192337) in #7185:

* Python bindings
* Support a dynamically changing scene (objects being added or removed), with support in Python, for collision-free IK trajectory planning. Either:
    * Interacting with `GeometryWorld` to add / remove entities
    * Adding / removing tree components (bodies, collisions) and being able to recompile the tree efficiently

**Comment by amcastro-tri** [comment]
Thank you @EricCousineau-TRI. 
1. Python bindings do not happen to fall on my lap, I wonder if this should be cited on a more "python bindings" issue? so it doesn't get lost here.
2. Support a dynamically changing scene. The policy with MBT was decided; if you want to add more bodies (for dynamics at least), you need to create a new tree. That makes sense if you think that everything MBT needs to solve for is fully coupled. Of course, additional sugar around it can mimic this functionality you describe, but it'd code living outside of MBT.
3. Dynamically adding/removing collision geometries is another issue, but as far as I understand @SeanCurtis-TRI took this into account in `GeometrySystem`.

**Comment by mpetersen94** [comment]
Torsional springs and distance constraints between two points.

**Comment by sherm1** [comment]
cc @tri-ltyyu

**Comment by EricCousineau-TRI** [comment]
Uh, is this still alive?

**Comment by amcastro-tri** [comment]
I believe many of the features mentioned here are actually in Drake master today.
Some might be missing but were not given high enough priority yet. I vote that we close for this issue and if there is some feature we currently don't have and you want it added, please open a specific issue for it. Thanks @EricCousineau-TRI

**Comment by EricCousineau-TRI** [comment]
Seconded! Closing for now, we can re-open later.
