### ISSUE TITLE
Investigate why articulated_icp_test's PostiveReturnsZeroCost test needs a large tolerance

### ISSUE THREAD

**Issue by EricCousineau-TRI** [RobotLocomotion/drake#7035]
Ideally, this test should not require any tolerance, as it's simply a cost computation.

Per f2f with @amcastro-tri, the original high tolerance for this test (`1e-4`) may arise due to Bullet's precision settings.

**Comment by hongkai-dai** [comment]
@EricCousineau-TRI , could you update the status of this issue? Thanks!

**Comment by EricCousineau-TRI** [comment]
This has the double-whammy of being both `attic/` *and* `dev/`. Not worth investigating.
