### ISSUE TITLE
Generated BasicVector subclasses should automatically generate SystemConstraints

### ISSUE THREAD

**Issue by jwnimmer-tri** [RobotLocomotion/drake#7037]
Generated BasicVector subclasses such as [PendulumParams](https://github.com/RobotLocomotion/drake/blob/master/drake/examples/pendulum/gen/pendulum_params.h) should automatically generate [SystemConstraint](http://drake.mit.edu/doxygen_cxx/classdrake_1_1systems_1_1_system_constraint.html) instances when they are declared as State, Params, etc. of a System.

This should happen automatically (the DeclareFoo methods should inspect the type to see if constraints are available), but perhaps should offer an opt-out in case someone doesn't want the magic behavior.

**Comment by jwnimmer-tri** [comment]
WIP will be at https://github.com/jwnimmer-tri/drake/tree/vectorgen-constraint

**Comment by jwnimmer-tri** [comment]
Since we want to have this on by default, it looks like we'll need constraint expression as a new virtual method on `VectorBase`.  I have a draft of that in the WIP branch.

I was hoping to use compile-time interrogation to see if the model vector had constraints, but it seems too likely to silently not work, and will be hard to, e.g., delegate declarations with constraints and preserve compile-time interrogation.  Instead, at runtime we'll ask if there are any constraints when the model vector is declared into a LeafSystem, and if so then we'll add the SystemConstraint.  I have a draft of that in the WIP branch.

**Comment by sherm1** [comment]
FWIW this seems like a good idea to me and the WIP implementation looks reasonable.

**Comment by jwnimmer-tri** [comment]
Per discussion in #7057, we should also declare constraints when the Output is typed.  I will re-open this to track that addition.
