### ISSUE TITLE
running SNOPT more than once crashes MATLAB on my windows machines

### ISSUE THREAD

**Issue by taylorott** [RobotLocomotion/drake#708]
Hi Everyone,

I make use of SNOPT through the Nonlinear program interface. Everything runs smoothly on my mac machines. However, when I try to run the same exact program on one of my windows64 machines, MATLAB generally crashes after SNOPT is called a second time. Here is an example of a program that I can run multiple times on my mac, but has a 60% chance of crashing MATLAB on my windows machine (It generally crashes the 2nd or 3rd time I run it):

function res=snopt_test01()
nlp1 = NonlinearProgram(3);
nlp1 = nlp1.setCheckGrad(true);
nlp1 = nlp1.setSolver('snopt');

%%%%%%%%%%%
% x1^2+4*x2^2<=4
% (x1-2)^2+x2^2<=5
% x1 >= 0
cnstr1 = FunctionHandleConstraint([-inf(2,1);0],[4;5;inf],2,@cnstr1_userfun);
xind1 = [2;3];
nlp1 = nlp1.addConstraint(cnstr1,xind1);
x1 = [1;2;1];

x=nlp1.solve(x1)

cnstr1_userfun(x(xind1'))

end

function [c,dc] = cnstr1_userfun(x)
c = [x(1)^2+4*x(2)^2;(x(1)-2)^2+x(2)^2;x(1)];
dc = [2*x(1) 8*x(2);2*(x(1)-2) 2*x(2);1 0];
end

Is there something wrong in the way that I'm calling SNOPT through the nonlinear program interface? Or is there just something bonked somewhere? I'm not sure what's going on.

Occasionally (but not always), I'll get a crash dump like this (I have no clue what to make of it):

MATLAB crash file:C:\Users\TAYLOR~1\AppData\Local\Temp\matlab_crash_dump.8264-1:

------------------------------------------------------------------------
          std::terminate() detected at Fri Jan 23 13:35:41 2015
------------------------------------------------------------------------

Configuration:
  Crash Decoding     : Disabled
  Default Encoding   : windows-1252
  Graphics card 1    : NVIDIA ( 0x10de ) NVIDIA Quadro K2100M  Version 9.18.13.1269
  Graphics card 2    : Intel Corporation ( 0x8086 ) Intel(R) HD Graphics Family Version 10.18.10.3412
  MATLAB Architecture: win64
  MATLAB Root        : C:\Program Files\MATLAB\R2014b
  MATLAB Version     : 8.4.0.150421 (R2014b)
  Operating System   : Microsoft Windows 7 Professional 
  Processor ID       : x86 Family 6 Model 60 Stepping 3, GenuineIntel
  Software OpenGL    : 0
  Virtual Machine    : Java 1.7.0_11-b21 with Oracle Corporation Java HotSpot(TM) 64-Bit Server VM mixed mode
  Window System      : Version 6.1 (Build 7601: Service Pack 1)

Fault Count: 1

Abnormal termination:
std::terminate()

Register State (captured):
  RAX = 00000000043eea01  RBX = 000000000401b420
  RCX = 000000000401ade0  RDX = 0000000000000000
  RSP = 000000000401a950  RBP = 000000000401bbd0
  RSI = 00000000043dea60  RDI = 00000000043eeab0
 
   R8 = 000007fffffde000   R9 = 000007feeabf0000
  R10 = 00000000043deab0  R11 = 00000000043deab0
  R12 = 00000000fd7f3f01  R13 = 000000000401b9e8
  R14 = 0000000000000000  R15 = 0000000000000000
 
  RIP = 000000000421432a  EFL = 00000206
 
   CS = 0033   FS = 0053   GS = 002b

Stack Trace (captured):
[  0] 0x000000000421432a C:\Program Files\MATLAB\R2014b\bin\win64\libmwfl.dll+00082730 fl::diag::windows::context_base::capture_data+00000010
[  1] 0x0000000004210bb4 C:\Program Files\MATLAB\R2014b\bin\win64\libmwfl.dll+00068532 fl::diag::thread_context::unspecified_bool+00006628
[  2] 0x00000000042130f6 C:\Program Files\MATLAB\R2014b\bin\win64\libmwfl.dll+00078070 fl::test::terminate_handler::~terminate_handler+00003510
[  3] 0x00000000fd0f2e45   C:\Program Files\MATLAB\R2014b\bin\win64\mcr.dll+00470597 mnShutdownMCR+00026709
[  4] 0x00000000fd0f25c1   C:\Program Files\MATLAB\R2014b\bin\win64\mcr.dll+00468417 mnShutdownMCR+00024529
[  5] 0x00000000fd0f26aa   C:\Program Files\MATLAB\R2014b\bin\win64\mcr.dll+00468650 mnShutdownMCR+00024762
[  6] 0x00000000fd0ef0ca   C:\Program Files\MATLAB\R2014b\bin\win64\mcr.dll+00454858 mnShutdownMCR+00010970
[  7] 0x00000000fd0f3938   C:\Program Files\MATLAB\R2014b\bin\win64\mcr.dll+00473400 mnSetSegvServiceUrl+00000168
[  8] 0x000007feeac5d56c C:\Program Files\MATLAB\R2014b\bin\win64\MSVCR110.dll+00447852 purecall+00000024
[  9] 0x00000000ec75c827 C:\Program Files\MATLAB\R2014b\bin\win64\libmwconfig.dll+00378919 QueryMLFcnTable_libmwconfig+00371383
[ 10] 0x00000000ec7646fb C:\Program Files\MATLAB\R2014b\bin\win64\libmwconfig.dll+00411387 QueryMLFcnTable_libmwconfig+00403851
[ 11] 0x00000000ec767cb3 C:\Program Files\MATLAB\R2014b\bin\win64\libmwconfig.dll+00425139 QueryMLFcnTable_libmwconfig+00417603
[ 12] 0x0000000004ce1e90 C:\Program Files\MATLAB\R2014b\bin\win64\m_dispatcher.dll+00007824 Mlm_MATLAB_fn::reset_license+00000512
[ 13] 0x0000000004cf4ad3 C:\Program Files\MATLAB\R2014b\bin\win64\m_dispatcher.dll+00084691 Mdispatcher::cleanupAllFcns+00000147
[ 14] 0x0000000004dc9c90 C:\Program Files\MATLAB\R2014b\bin\win64\m_interpreter.dll+00040080 inEvalCmd+00008208
[ 15] 0x0000000004dc3905 C:\Program Files\MATLAB\R2014b\bin\win64\m_interpreter.dll+00014597 MathWorks::interpreter::releaseCurrentMcrContext+00001061
[ 16] 0x00000000fd7411e8 C:\Program Files\MATLAB\R2014b\bin\win64\mlutil.dll+01249768 mlutil::contextmgr::ContextRegistry::getInstance+00011528
[ 17] 0x00000000fd73a315 C:\Program Files\MATLAB\R2014b\bin\win64\mlutil.dll+01221397 mlutil::contextmgr::NullResourceException::rethrow+00024917
[ 18] 0x00000000fd7911c6 C:\Program Files\MATLAB\R2014b\bin\win64\mlutil.dll+01577414 mlutil::ScopedFactoryRegistration::Impl::unregister+00000070
[ 19] 0x00000000fd790eab C:\Program Files\MATLAB\R2014b\bin\win64\mlutil.dll+01576619 mlutil::ScopedFactoryRegistration::Impl::~Impl+00000027
[ 20] 0x00000000fd73bdb8 C:\Program Files\MATLAB\R2014b\bin\win64\mlutil.dll+01228216 mlutil::contextmgr::NullResourceException::rethrow+00031736
[ 21] 0x00000000fd6aeaf3 C:\Program Files\MATLAB\R2014b\bin\win64\mlutil.dll+00649971 mlutil::ScopedFactoryRegistration::~ScopedFactoryRegistration+00000035
[ 22] 0x0000000004efa620 C:\Program Files\MATLAB\R2014b\bin\win64\m_interpreter.dll+01287712 init_cleaner+00003184
[ 23] 0x0000000004efa5f0 C:\Program Files\MATLAB\R2014b\bin\win64\m_interpreter.dll+01287664 init_cleaner+00003136
[ 24] 0x0000000004efa5d2 C:\Program Files\MATLAB\R2014b\bin\win64\m_interpreter.dll+01287634 init_cleaner+00003106
[ 25] 0x0000000004f01038 C:\Program Files\MATLAB\R2014b\bin\win64\m_interpreter.dll+01314872 QueryMLFcnTable_m_interpreter+00019832
[ 26] 0x0000000004f012ba C:\Program Files\MATLAB\R2014b\bin\win64\m_interpreter.dll+01315514 QueryMLFcnTable_m_interpreter+00020474
[ 27] 0x00000000777143a1                      C:\Windows\SYSTEM32\ntdll.dll+00148385 LdrShutdownProcess+00000465
[ 28] 0x00000000777141b0                      C:\Windows\SYSTEM32\ntdll.dll+00147888 RtlExitUserProcess+00000144
[ 29] 0x0000000061150ccd C:\Program Files\MATLAB\R2014b\bin\win64\MSVCR100.dll+00134349 get_pgmptr+00000585
[ 30] 0x00000000611a61d3 C:\Program Files\MATLAB\R2014b\bin\win64\MSVCR100.dll+00483795 abort+00000063
[ 31] 0x000007fee38e530d C:\Users\taylorott\Documents\MATLAB\drake-precompiled-0.9.7-3ade858-win64\drake\solvers\NonlinearProgramSnoptmex.mexw64+00480013 mexFunction+00475629
[ 32] 0x000007fee38e1f77 C:\Users\taylorott\Documents\MATLAB\drake-precompiled-0.9.7-3ade858-win64\drake\solvers\NonlinearProgramSnoptmex.mexw64+00466807 mexFunction+00462423
[ 33] 0x000007fee3872a8f C:\Users\taylorott\Documents\MATLAB\drake-precompiled-0.9.7-3ade858-win64\drake\solvers\NonlinearProgramSnoptmex.mexw64+00010895 mexFunction+00006511
[ 34] 0x000007fee38729eb C:\Users\taylorott\Documents\MATLAB\drake-precompiled-0.9.7-3ade858-win64\drake\solvers\NonlinearProgramSnoptmex.mexw64+00010731 mexFunction+00006347
[ 35] 0x00000000fc5f3701 C:\Program Files\MATLAB\R2014b\bin\win64\libmex.dll+00079617 mexRunMexFile+00000129
[ 36] 0x00000000fc5f2762 C:\Program Files\MATLAB\R2014b\bin\win64\libmex.dll+00075618 inSwapMexfileReader+00000690
[ 37] 0x00000000fc5f2248 C:\Program Files\MATLAB\R2014b\bin\win64\libmex.dll+00074312 mexUnlock+00006008
[ 38] 0x0000000004cf05e3 C:\Program Files\MATLAB\R2014b\bin\win64\m_dispatcher.dll+00067043 Mfh_file::dispatch_fh+00000659
[ 39] 0x0000000004cf0aee C:\Program Files\MATLAB\R2014b\bin\win64\m_dispatcher.dll+00068334 Mfunction_handle::dispatch+00000766
[ 40] 0x0000000004e02b2f C:\Program Files\MATLAB\R2014b\bin\win64\m_interpreter.dll+00273199 inGetNameInSymbolTable+00017071
[ 41] 0x0000000004e040c0 C:\Program Files\MATLAB\R2014b\bin\win64\m_interpreter.dll+00278720 inGetNameInSymbolTable+00022592
[ 42] 0x0000000004e01b4f C:\Program Files\MATLAB\R2014b\bin\win64\m_interpreter.dll+00269135 inGetNameInSymbolTable+00013007
[ 43] 0x0000000004e01ab1 C:\Program Files\MATLAB\R2014b\bin\win64\m_interpreter.dll+00268977 inGetNameInSymbolTable+00012849
[ 44] 0x0000000004e2406f C:\Program Files\MATLAB\R2014b\bin\win64\m_interpreter.dll+00409711 inPathNotification::function_delete_notification+00098591
[ 45] 0x0000000004e227af C:\Program Files\MATLAB\R2014b\bin\win64\m_interpreter.dll+00403375 inPathNotification::function_delete_notification+00092255
[ 46] 0x0000000004e21359 C:\Program Files\MATLAB\R2014b\bin\win64\m_interpreter.dll+00398169 inPathNotification::function_delete_notification+00087049
[ 47] 0x0000000004cf05e3 C:\Program Files\MATLAB\R2014b\bin\win64\m_dispatcher.dll+00067043 Mfh_file::dispatch_fh+00000659
[ 48] 0x0000000004cf0aee C:\Program Files\MATLAB\R2014b\bin\win64\m_dispatcher.dll+00068334 Mfunction_handle::dispatch+00000766
[ 49] 0x00000000058ec728  C:\Program Files\MATLAB\R2014b\bin\win64\mcos.dll+00182056 mcos::COSDataType::checkValue+00002824
[ 50] 0x0000000004cf0d54 C:\Program Files\MATLAB\R2014b\bin\win64\m_dispatcher.dll+00068948 Mfh_MATLAB_fn::dispatch_fh+00000452
[ 51] 0x000000000591116d  C:\Program Files\MATLAB\R2014b\bin\win64\mcos.dll+00332141 omUnmarkArrayForAssignment+00000525
[ 52] 0x0000000004cf0aee C:\Program Files\MATLAB\R2014b\bin\win64\m_dispatcher.dll+00068334 Mfunction_handle::dispatch+00000766
[ 53] 0x0000000004e02b2f C:\Program Files\MATLAB\R2014b\bin\win64\m_interpreter.dll+00273199 inGetNameInSymbolTable+00017071
[ 54] 0x0000000004e040c0 C:\Program Files\MATLAB\R2014b\bin\win64\m_interpreter.dll+00278720 inGetNameInSymbolTable+00022592
[ 55] 0x0000000004e01b4f C:\Program Files\MATLAB\R2014b\bin\win64\m_interpreter.dll+00269135 inGetNameInSymbolTable+00013007
[ 56] 0x0000000004e01ab1 C:\Program Files\MATLAB\R2014b\bin\win64\m_interpreter.dll+00268977 inGetNameInSymbolTable+00012849
[ 57] 0x0000000004e2406f C:\Program Files\MATLAB\R2014b\bin\win64\m_interpreter.dll+00409711 inPathNotification::function_delete_notification+00098591
[ 58] 0x0000000004e227af C:\Program Files\MATLAB\R2014b\bin\win64\m_interpreter.dll+00403375 inPathNotification::function_delete_notification+00092255
[ 59] 0x0000000004e21359 C:\Program Files\MATLAB\R2014b\bin\win64\m_interpreter.dll+00398169 inPathNotification::function_delete_notification+00087049
[ 60] 0x0000000004cf05e3 C:\Program Files\MATLAB\R2014b\bin\win64\m_dispatcher.dll+00067043 Mfh_file::dispatch_fh+00000659
[ 61] 0x0000000004cf0aee C:\Program Files\MATLAB\R2014b\bin\win64\m_dispatcher.dll+00068334 Mfunction_handle::dispatch+00000766
[ 62] 0x00000000058ec728  C:\Program Files\MATLAB\R2014b\bin\win64\mcos.dll+00182056 mcos::COSDataType::checkValue+00002824
[ 63] 0x0000000004cf0d54 C:\Program Files\MATLAB\R2014b\bin\win64\m_dispatcher.dll+00068948 Mfh_MATLAB_fn::dispatch_fh+00000452
[ 64] 0x000000000591116d  C:\Program Files\MATLAB\R2014b\bin\win64\mcos.dll+00332141 omUnmarkArrayForAssignment+00000525
[ 65] 0x0000000004cf0aee C:\Program Files\MATLAB\R2014b\bin\win64\m_dispatcher.dll+00068334 Mfunction_handle::dispatch+00000766
[ 66] 0x0000000004e006b9 C:\Program Files\MATLAB\R2014b\bin\win64\m_interpreter.dll+00263865 inGetNameInSymbolTable+00007737
[ 67] 0x0000000004e01332 C:\Program Files\MATLAB\R2014b\bin\win64\m_interpreter.dll+00267058 inGetNameInSymbolTable+00010930
[ 68] 0x0000000004e01c5f C:\Program Files\MATLAB\R2014b\bin\win64\m_interpreter.dll+00269407 inGetNameInSymbolTable+00013279
[ 69] 0x0000000004e0244f C:\Program Files\MATLAB\R2014b\bin\win64\m_interpreter.dll+00271439 inGetNameInSymbolTable+00015311
[ 70] 0x0000000004e033eb C:\Program Files\MATLAB\R2014b\bin\win64\m_interpreter.dll+00275435 inGetNameInSymbolTable+00019307
[ 71] 0x0000000004e03fac C:\Program Files\MATLAB\R2014b\bin\win64\m_interpreter.dll+00278444 inGetNameInSymbolTable+00022316
[ 72] 0x0000000004e01b4f C:\Program Files\MATLAB\R2014b\bin\win64\m_interpreter.dll+00269135 inGetNameInSymbolTable+00013007
[ 73] 0x0000000004e01ab1 C:\Program Files\MATLAB\R2014b\bin\win64\m_interpreter.dll+00268977 inGetNameInSymbolTable+00012849
[ 74] 0x0000000004e2406f C:\Program Files\MATLAB\R2014b\bin\win64\m_interpreter.dll+00409711 inPathNotification::function_delete_notification+00098591
[ 75] 0x0000000004e227af C:\Program Files\MATLAB\R2014b\bin\win64\m_interpreter.dll+00403375 inPathNotification::function_delete_notification+00092255
[ 76] 0x0000000004e21359 C:\Program Files\MATLAB\R2014b\bin\win64\m_interpreter.dll+00398169 inPathNotification::function_delete_notification+00087049
[ 77] 0x0000000004cf05e3 C:\Program Files\MATLAB\R2014b\bin\win64\m_dispatcher.dll+00067043 Mfh_file::dispatch_fh+00000659
[ 78] 0x0000000004cf0aee C:\Program Files\MATLAB\R2014b\bin\win64\m_dispatcher.dll+00068334 Mfunction_handle::dispatch+00000766
[ 79] 0x0000000004e02b2f C:\Program Files\MATLAB\R2014b\bin\win64\m_interpreter.dll+00273199 inGetNameInSymbolTable+00017071
[ 80] 0x0000000004eeb6f7 C:\Program Files\MATLAB\R2014b\bin\win64\m_interpreter.dll+01226487 inFullEvalFcn+00011159
[ 81] 0x0000000004e05592 C:\Program Files\MATLAB\R2014b\bin\win64\m_interpreter.dll+00284050 inGetNameInSymbolTable+00027922
[ 82] 0x0000000004e01b4f C:\Program Files\MATLAB\R2014b\bin\win64\m_interpreter.dll+00269135 inGetNameInSymbolTable+00013007
[ 83] 0x0000000004e01ab1 C:\Program Files\MATLAB\R2014b\bin\win64\m_interpreter.dll+00268977 inGetNameInSymbolTable+00012849
[ 84] 0x0000000004e2406f C:\Program Files\MATLAB\R2014b\bin\win64\m_interpreter.dll+00409711 inPathNotification::function_delete_notification+00098591
[ 85] 0x0000000004e227af C:\Program Files\MATLAB\R2014b\bin\win64\m_interpreter.dll+00403375 inPathNotification::function_delete_notification+00092255
[ 86] 0x0000000004e21359 C:\Program Files\MATLAB\R2014b\bin\win64\m_interpreter.dll+00398169 inPathNotification::function_delete_notification+00087049
[ 87] 0x0000000004cf07a4 C:\Program Files\MATLAB\R2014b\bin\win64\m_dispatcher.dll+00067492 Mfh_file::dispatch_fh+00001108
[ 88] 0x0000000004cf0aee C:\Program Files\MATLAB\R2014b\bin\win64\m_dispatcher.dll+00068334 Mfunction_handle::dispatch+00000766
[ 89] 0x0000000004e54a88 C:\Program Files\MATLAB\R2014b\bin\win64\m_interpreter.dll+00608904 inPathNotification::function_delete_notification+00297784
[ 90] 0x0000000004e54a04 C:\Program Files\MATLAB\R2014b\bin\win64\m_interpreter.dll+00608772 inPathNotification::function_delete_notification+00297652
[ 91] 0x0000000004e549c5 C:\Program Files\MATLAB\R2014b\bin\win64\m_interpreter.dll+00608709 inPathNotification::function_delete_notification+00297589
[ 92] 0x0000000004e54992 C:\Program Files\MATLAB\R2014b\bin\win64\m_interpreter.dll+00608658 inPathNotification::function_delete_notification+00297538
[ 93] 0x0000000004e54947 C:\Program Files\MATLAB\R2014b\bin\win64\m_interpreter.dll+00608583 inPathNotification::function_delete_notification+00297463
[ 94] 0x0000000004dcd69d C:\Program Files\MATLAB\R2014b\bin\win64\m_interpreter.dll+00054941 inEvalExp+00001309
[ 95] 0x0000000004ef525d C:\Program Files\MATLAB\R2014b\bin\win64\m_interpreter.dll+01266269 inEvalCmdWithLocalReturn+00000285
[ 96] 0x0000000004ef5181 C:\Program Files\MATLAB\R2014b\bin\win64\m_interpreter.dll+01266049 inEvalCmdWithLocalReturn+00000065
[ 97] 0x000000000636e31d C:\Program Files\MATLAB\R2014b\bin\win64\libmwbridge.dll+00058141 mnGetPrompt+00001517
[ 98] 0x000000000636ed09 C:\Program Files\MATLAB\R2014b\bin\win64\libmwbridge.dll+00060681 mnParser+00000745
[ 99] 0x00000000fd0dd834   C:\Program Files\MATLAB\R2014b\bin\win64\mcr.dll+00383028 mcrInstance::mnParser_on_interpreter_thread+00000036
[100] 0x00000000fd0a68e7   C:\Program Files\MATLAB\R2014b\bin\win64\mcr.dll+00157927 mcr::runtime::setInterpreterThreadToCurrent+00019751
[101] 0x00000000fd0a6923   C:\Program Files\MATLAB\R2014b\bin\win64\mcr.dll+00157987 mcr::runtime::setInterpreterThreadToCurrent+00019811
[102] 0x00000000fd0a7121   C:\Program Files\MATLAB\R2014b\bin\win64\mcr.dll+00160033 mcr::runtime::setInterpreterThreadToCurrent+00021857
[103] 0x00000000fab5d3a6   C:\Program Files\MATLAB\R2014b\bin\win64\uiw.dll+00512934 UIW_AttachThreadInput+00001270
[104] 0x00000000fab5cc35   C:\Program Files\MATLAB\R2014b\bin\win64\uiw.dll+00511029 wsd_to_MSW+00004373
[105] 0x00000000fab5ccb9   C:\Program Files\MATLAB\R2014b\bin\win64\uiw.dll+00511161 wsd_to_MSW+00004505
[106] 0x00000000774f87fe                     C:\Windows\system32\USER32.dll+00165886 GetMenuBarInfo+00000638
[107] 0x00000000774df5fb                     C:\Windows\system32\USER32.dll+00062971 SystemParametersInfoW+00000235
[108] 0x00000000774e4895                     C:\Windows\system32\USER32.dll+00084117 IsProcessDPIAware+00000465
[109] 0x00000000777411f5                      C:\Windows\SYSTEM32\ntdll.dll+00332277 KiUserCallbackDispatcher+00000031
[110] 0x00000000774eef0a                     C:\Windows\system32\USER32.dll+00126730 GetClipboardData+00001686
[111] 0x00000000774d5466                     C:\Windows\system32\USER32.dll+00021606 LockWindowStation+00000262
[112] 0x00000000774d797c                     C:\Windows\system32\USER32.dll+00031100 GetKeyboardLayoutList+00000412
[113] 0x00000000774df5fb                     C:\Windows\system32\USER32.dll+00062971 SystemParametersInfoW+00000235
[114] 0x00000000774e4895                     C:\Windows\system32\USER32.dll+00084117 IsProcessDPIAware+00000465
[115] 0x00000000777411f5                      C:\Windows\SYSTEM32\ntdll.dll+00332277 KiUserCallbackDispatcher+00000031
[116] 0x00000000774e908a                     C:\Windows\system32\USER32.dll+00102538 PeekMessageW+00000186
[117] 0x00000000774e50fe                     C:\Windows\system32\USER32.dll+00086270 GetKeyState+00000238
[118] 0x00000000774e3a6f                     C:\Windows\system32\USER32.dll+00080495 PeekMessageA+00000087
[119] 0x00000000fab0a26b   C:\Program Files\MATLAB\R2014b\bin\win64\uiw.dll+00172651 UIW_ShowMenuItem+00003995
[120] 0x00000000fab5dce2   C:\Program Files\MATLAB\R2014b\bin\win64\uiw.dll+00515298 UIW_SuspendAttachThreadInput+00000466
[121] 0x0000000100118223 C:\Program Files\MATLAB\R2014b\bin\win64\libmwservices.dll+01212963 services::system_events::PpeDispatchHook::dispatchOne+00032291
[122] 0x0000000100123c95 C:\Program Files\MATLAB\R2014b\bin\win64\libmwservices.dll+01260693 sysq::addProcessPendingEventsUnitTestHook+00005813
[123] 0x0000000100123d50 C:\Program Files\MATLAB\R2014b\bin\win64\libmwservices.dll+01260880 sysq::addProcessPendingEventsUnitTestHook+00006000
[124] 0x0000000100125b75 C:\Program Files\MATLAB\R2014b\bin\win64\libmwservices.dll+01268597 sysq::getCondition+00004629
[125] 0x00000001001274ba C:\Program Files\MATLAB\R2014b\bin\win64\libmwservices.dll+01275066 svWS_ProcessPendingEvents+00000138
[126] 0x00000000fd0a783d   C:\Program Files\MATLAB\R2014b\bin\win64\mcr.dll+00161853 mcr::runtime::setInterpreterThreadToCurrent+00023677
[127] 0x00000000fd0a84aa   C:\Program Files\MATLAB\R2014b\bin\win64\mcr.dll+00165034 mcr::runtime::setInterpreterThreadToCurrent+00026858

This error was detected while a MEX-file was running. If the MEX-file
is not an official MathWorks function, please examine its source code
for errors. Please consult the External Interfaces Guide for information
on debugging MEX-files.

If this problem is reproducible, please submit a Service Request via:
    http://www.mathworks.com/support/contact_us/

A technical support engineer might contact you with further information.

Thank you for your help.

**Comment by taylorott** [comment]
The new drake that was posted 3 days ago fixes this problem. I don't know how it did it, but it does. Thanks!

**Comment by RussTedrake** [comment]
Excellent!  Thanks for letting me know.

- Russ
