### ISSUE TITLE
Function Miscall in examples/IRB140/runPlanning

### ISSUE THREAD

**Issue by Nima-Fazeli** [RobotLocomotion/drake#711]
In IRB140 example line 30, command "findLinkId" does not work but if replaced with "findLinkInd" (note the letter "n" between "I" and "d", then it does. Consider checking it out

**Comment by RussTedrake** [comment]
findLinkInd has been replaced (relatively recently) with findLinkId.  not sure how you might have gotten a mixed version.  is there a chance you pulled the IRB140 example in on top of an older version of drake?

**Comment by Nima-Fazeli** [comment]
I just checked, you are right, sorry about that. My installation of drake did not have IRB140, so I pulled it and ran it on an older version of drake (it is from last year). Thank you for the clarification.
