### ISSUE TITLE
Profile and speed up LCM image publishing

### ISSUE THREAD

**Issue by EricCousineau-TRI** [RobotLocomotion/drake#7117]
While producing a few demos, we found that now the bottlenecks in the RGB-D camera simulation pipeline is most likely publishing LCM images. This is most likely due to compression, but we'll look into this and confirm.

\cc @kunimatsu-tri

**Comment by EricCousineau-TRI** [comment]
Seems like it was really just an issue due to #5629 - I was testing in `monolithic_pick_and_place_demo`, which did not have `simulator.set_publish_every_time_step(false)`.

Will check and see if there is any other low-hanging fruit.

**Comment by hongkai-dai** [comment]
@EricCousineau-TRI could you update the status of this issue? Thanks!

**Comment by EricCousineau-TRI** [comment]
I think this one is more-or-less resolved (in that it hasn't been identified as a major pain point).

Can either re-open or open a new issue if it does become an issue.
