### ISSUE TITLE
Frames mistakenly registered with the same "name" do not show up in visualizer

### ISSUE THREAD

**Issue by amcastro-tri** [RobotLocomotion/drake#7122]
A `GeometrySystem` problem. In my case I register a single frame per single geometry. I do frame registration by calling:
```c++
FrameId link_frame_id = geometry_system->RegisterFrame(
          source_id_, GeometryFrame(
              "MistakelyAlwaysTheSameName", Isometry3<double>::Identity()));
```
Then, after calling the `geometry::DispatchLoadMessage(*geometry_system);`, I run the simulation. 
With that setup, only my first two geometries are shown and the rest are invisible.

If I now make the `GeometryName` different for each frame, life is good. Should that registration throw for frames with the same name?

**Comment by amcastro-tri** [comment]
To be more specific with an example soon-to-be in master, `SolarSystem`. If I change the name "Luna" to "Earth", "Luna" is no longer rendered (I have no idea if it actually did make it to my geometry model though). I think the safest thing to do would be to require (throw if not) unique names.

**Comment by SeanCurtis-TRI** [comment]
Thanks -- I'll get this fixed.
