### ISSUE TITLE
LeafSystem::DeclareDiscreteState does not support model_vector types

### ISSUE THREAD

**Issue by RussTedrake** [RobotLocomotion/drake#7147]
and even the existing interface (taking just the vector size) is misleading.  I would have thought that if I called `DeclareDiscreteState` twice, I would have gotten two distinct discrete state groups.  In fact, I would just get one, with the size of the last call do `DeclareDiscreteState`.  Yikes!

**Comment by jwnimmer-tri** [comment]
The model_value request is tracked under #7058 already.
