### ISSUE TITLE
`region_of_attraction_test` on Sierra

### ISSUE THREAD

**Issue by m-chaturvedi** [RobotLocomotion/drake#7189]
[`mac-sierra-clang-bazel-nightly-everything-release`](https://drake-jenkins.csail.mit.edu/view/Mac%20Sierra/job/mac-sierra-clang-bazel-nightly-everything-release/68/consoleText) fails to build due to `region_of_attraction_test`, it is a MOSEK related test. @EricCousineau-TRI reported that:

The test 'passes' when run with `bazel test` as well as with `bazel run`  in `dbg` mode.  
```
$ bazel run -c dbg --config everything //drake/examples/cubic_polynomial:region_of_attraction_test
...
INFO: Running command line: bazel-bin/drake/examples/cubic_polynomial/region_of_attraction_test
Verified that 1*x(0)^2 < 1 is in the region of attraction.

$ bazel test -c dbg --config everything //drake/examples/cubic_polynomial:region_of_attraction_test
...
Executed 0 out of 1 test: 1 test passes.
```

The test doesn't report an error with `bazel run` in `opt` (default) mode, i.e.
```
$ bazel run --config everything //drake/examples/cubic_polynomial:region_of_attraction_test
...
INFO: Running command line: bazel-bin/drake/examples/cubic_polynomial/region_of_attraction_test
```
but that's most likely because it crashes before then.  It fails with `bazel test` in `opt` mode, i.e.
```
$ bazel test --config everything //drake/examples/cubic_polynomial:region_of_attraction_test
...
==================== Test output for //drake/examples/cubic_polynomial:region_of_attraction_test:
Segmentation fault: 11
================================================================================
```

When run on Linux, it prints the "Verified that..." statement in both `dbg` and `opt` configurations.

Additionally, this is the debug build, which is successful, [`mac-sierra-clang-bazel-nightly-everything-debug`](https://drake-jenkins.csail.mit.edu/view/Mac%20Sierra/job/mac-sierra-clang-bazel-nightly-everything-debug/68/)

**Comment by soonho-tri** [comment]
I think I've fixed the problem in #7188 .

**Comment by soonho-tri** [comment]
Now, it's merged. I forgot to run `mac-sierra-clang-bazel-nightly-everything-release`. Could you test it by triggering the build?

**Comment by m-chaturvedi** [comment]
Scheduled:
https://drake-jenkins.csail.mit.edu/view/Mac%20Sierra/job/mac-sierra-clang-bazel-experimental-everything/

**Comment by soonho-tri** [comment]
It’s blue.
