### ISSUE TITLE
//tools/lint/util_test may fail if there is a .DS_Store file in third_party

### ISSUE THREAD

**Issue by jamiesnape** [RobotLocomotion/drake#7201]
Presumably these files need to be excluded from `util.find_all_sources()`.

**Comment by jwnimmer-tri** [comment]
In Drake's `.gitignore`, I don't see an entry for `.DS_Store` files.  Does OSX have some kind of system-wide default to ignore those?  Or are they showing up as `?`s in `git status`?

**Comment by jamiesnape** [comment]
Most people have it in a global `.gitignore`, I imagine.
