### ISSUE TITLE
[maliput] Missing input checks on `HBounds` and `RBounds`

### ISSUE THREAD

**Issue by maddog-tri** [RobotLocomotion/drake#7231]
Regarding both `maliput::api::RBounds` and `maliput::api::HBounds`:
  * The constructors of both have input-checks to ensure that the invariant `min <= 0 <= max` is fulfilled.
  * The `set_min()` and `set_max()` setters lack these checks, allowing the invariant to later be violated.

Given that this invariant is part of the contracts of these classes, the checks should be changed from `DRAKE_DEMAND` to `DRAKE_THROW_UNLESS`, and unit-tests should be added to make sure the checks are enforced by both constructors and setters.

**Comment by agalbachicar** [comment]
Closed via #7239 and #7249
