### ISSUE TITLE
Add to Python RigidBodyTree API to enable collision-free path planning in dynamically changing scenes

### ISSUE THREAD

**Issue by EricCousineau-TRI** [RobotLocomotion/drake#7251]
Per [this request](https://github.com/RobotLocomotion/drake/issues/7185#issuecomment-336192337) in #7185:
Before the features in #7025 / #5013 are completed for `MultibodyTree` (after which `RigidBodyTree` will be deprecated), this could be achieved by updating the existing Python bindings (adding `addCollisionElement`, `removeCollisionElement`, `removeCollisionGroupsIf`, `updateCollisionElements`, and the upstream classes for that API).

Per f2f with @avalenzu, this could be achieved by adding the "scene" collision elements to the world body with a unique group name, and when the scene is updated (either with new objects, or updating the poses of the existing elements), either update the element position or remove the existing group and the updated elements anew.
Note that `RigidBodyTree` does not support removing elements; hence you could just modify the collision elements as needed.

\cc @dmsj

**Comment by jwnimmer-tri** [comment]
@EricCousineau-TRI I'm assuming that we don't care about new RBT features anymore?  Can this be closed?

**Comment by EricCousineau-TRI** [comment]
Yup. We have other issues tracking this equivalent for MBP.
