### ISSUE TITLE
Justify the get_I and get_J constant values in free_body benchmark

### ISSUE THREAD

**Issue by amcastro-tri** [RobotLocomotion/drake#7252]
A number of `using` directives in header for benchmark `free_body` should be removed.
See [comment here](https://reviewable.io/reviews/robotlocomotion/drake/7218#-KwGLEph4LDAXEu3oLab).

**Comment by amcastro-tri** [comment]
I'll transcribe @soonho-tri's question from [comment here](https://reviewable.io/reviews/robotlocomotion/drake/7218#-Kw0c1xKWbFGSkZPCUBV) so that it doesn't get lost:
> Can you provide a comment why we have this particular constant here? (and also for get_J below) For example, are they from the book cited above?

**Comment by jwnimmer-tri** [comment]
> A number of using directives in header for benchmark free_body should be removed.

This is already done.  I've re-titled this issue to focus on the second post, instead.

**Comment by mitiguy** [comment]
@jwnimmer-tri   
Jeremy - can we close issue #7252 
(Justify the get_i and get_j constant values in free_body_benchmark) ?

**Comment by jwnimmer-tri** [comment]
The fix I made was only to repair the using statements.
To my knowledge, no change has been made to fix the documentation of the constants.

**Comment by jwnimmer-tri** [comment]
Well, the free_body docs still don't explain where `I` and `J` came from.  The next time someone decides they need to know about it, they can work to dig up the answer and add it to the docs.
