### ISSUE TITLE
Need CI coverage of `bazel run :install` correctness

### ISSUE THREAD

**Issue by jwnimmer-tri** [RobotLocomotion/drake#7260]
Drake's CI should have coverage that `bazel run :install` behaves correctly, in terms of a CMake project being able to consume the results.  (I'm leaning toward pre-merge checks, though possibly `Continuous Production` that we could opt-in to for `Experimental` would be good enough.)

The fix in #7257 for a bug that I introduced in #7241 is a good example of what we would like to catch, since it broke ~everything.  Other more subtle or rare failure modes perhaps don't need to be covered, at least in the first iteration.

Possibly #7293 will get us most of what we want.

**Comment by EricCousineau-TRI** [comment]
@jamiesnape Would you mind if I assigned this to you?

For CMake project consumption within Drake's CI, should we make a simple non-cached test which is simply a *very* small subset of `drake-shambhala/drake_cmake_installed`, consuming from `bazel run //:install`, setting the appropriate compilers per Bazel's setup?

Or do we want want this to run entirely through the CMake install process? (in which case, would we just want to defer this entirely to `drake-shambhala`?)

**Comment by jamiesnape** [comment]
> @jamiesnape Would you mind if I assigned this to you?

Sure. Not decided on how we do it, but I don't think it will be deferring to shambhala.

**Comment by jwnimmer-tri** [comment]
The drake-shambala CI is good enough as a first pass.  If we discover that it's not catching certain kinds of errors, we can open separate issues for those problems.
