### ISSUE TITLE
Update CI images for new protobuf2 dependencies

### ISSUE THREAD

**Issue by jwnimmer-tri** [RobotLocomotion/drake#7306]
PR #7303 added some new OS dependencies.  Please update CI's default Xenial and Apple images to provide the new packages by default.  Thanks!

**Comment by jamiesnape** [comment]
Do we have any other system dependency updates in the pipeline?

**Comment by jwnimmer-tri** [comment]
I was wondering the same thing.  I didn't immediately think of any, but I'll do another survey to be sure.

**Comment by jwnimmer-tri** [comment]
I guess #7293 has some, though perhaps they are all already present in CI.

**Comment by jamiesnape** [comment]
Yes, they are. They are really refactoring from the manual instructions to the script.

**Comment by jwnimmer-tri** [comment]
On Xenial, it looks like `libyaml-cpp-dev` will be coming down the pipeline eventually too.  I suspect that `brew install yaml-cpp` might also apply in that case, though I'm less sure there.

**Comment by jamiesnape** [comment]
Version numbers of the Homebrew and Xenial packages are pretty similar, so I imagine so.

**Comment by jamiesnape** [comment]
Mind if we PR the yaml-cpp updates to `install_prereqs.sh` now? Keeps (practically) everything that is installed on CI transparent.

**Comment by jwnimmer-tri** [comment]
SGTM.

**Comment by BetsyMcPhail** [comment]
CI images have been updated to match latest install_prereqs scripts.

**Comment by jwnimmer-tri** [comment]
@clalancette Can you verify and then we can close this issue?  Maybe rebase and push #7278?

**Comment by clalancette** [comment]
Will do.

**Comment by clalancette** [comment]
I'll note, though, that I'm sure MacOS is going to fail with that branch.  I still haven't figured out how to make it work properly.  That being said, it will still be a good test for Linux.

**Comment by clalancette** [comment]
So, despite the fact that one of the builds in #7278 failed, I think we can call this done.  That failure was a segmentation fault in two of the tests.  While that is obviously a problem for that PR, it doesn't seem to be a problem with the setup/build portion of it.

**Comment by jwnimmer-tri** [comment]
Great.  Thanks @BetsyMcPhail!
