### ISSUE TITLE
c++ doKinematics, HandC, etc should take VectorXd's (properly templated) instead of double*

### ISSUE THREAD

**Issue by RussTedrake** [RobotLocomotion/drake#731]
in the RigidBodyManipulator class.

@avalenzu , @hongkai-dai , @tkoolen - can you think of any reason to avoid this?  I think it's just vestigial (those were the first methods we implemented).

**Comment by tkoolen** [comment]
No, no real reason I think.

**Comment by hongkai-dai** [comment]
No, I don't think we need VectorXd

**Comment by RussTedrake** [comment]
i'm proposing that DO use VectorXd so that everything is consistent.

**Comment by hongkai-dai** [comment]
I see, I think that should work. And we can also add the size check to make
sure size(q) is consistent with the robot num_dof;

**Comment by avalenzu** [comment]
I'm definitely in favor of using VectorXd.

**Comment by psiorx** [comment]
I'm also in favor of this.

@RussTedrake Can you please assign this to me?

**Comment by RussTedrake** [comment]
will do!  but you might wait until my next pull request comes through (i'm restructuring the mex interface to RBM).

**Comment by psiorx** [comment]
@RussTedrake Ok.  I already have getCMM and HandC done.  I'll wait before finishing up doKinematics*().
