### ISSUE TITLE
remove directorPython usage from iiwa arm example

### ISSUE THREAD

**Issue by RussTedrake** [RobotLocomotion/drake#7321]
As discussed in https://reviewable.io/reviews/RobotLocomotion/drake/7313#-Kx99MsvVKtz09Qu5tIr

Nominal plan: convert the state translator to C++ (and cover it with unit tests), and to convert the director ik interface to a drake-visualizer app if necessary.

Related: #7024

**Comment by sammy-tri** [comment]
Also the kuka example's README.md should be updated to include the steps which it's currently missing which depend on this issue (making sure to also add the dual-arm examples).

**Comment by sammy-tri** [comment]
Also the kuka example's README.md should be updated to include the steps which it's currently missing which depend on this issue (making sure to also add the dual-arm examples).

**Comment by sammy-tri** [comment]
I've got a C++ version of the state translator basically ready (I think I might wait on #7439 before opening a PR).  As we've discussed in other places (#7314 and #7024) converting the director IK interface to a drake-visualizer app requires a more complex resolution.  Do we want to leave this issue open pending that change?  Or close this and just track the lack of graphical IK in #7314?
