### ISSUE TITLE
Problem in install drake on Ubuntu

### ISSUE THREAD

**Issue by peterchen0206** [RobotLocomotion/drake#7328]
Hello guys, I'm a new beginner using drake to model underactuated system.
I have been using drake on window 10 and MATLAB ,but i doesn't work.
And it seems drake doesn't support window now.
So I change to Ubunto 16.04 and follow the install guide from here:
http://drake.mit.edu/from_source.html
I use bazel and follow guied from here:
http://drake.mit.edu/bazel.html#using-bazel
```
cd /path/to/drake-distro
bazel build //...                     # Build the entire project.
bazel test //...                      # Build and test the entire project.
bazel build --compiler=gcc-5 //...    # Build using gcc 5.x on Xenial.
```
After key in all code above and build successfully.
I use MATLAB and  key in 
```
cd drake-distro/drake/matlab
addpath_drake
cd solvers/test
testMathematicalProgram
```
But my matlab just show "can't find addpath_drake variable".
and I also can't set path manually in MATLAB.
What should I do to run drake on linux MATLAB?

**Comment by jamiesnape** [comment]
MATLAB is not current supported by the Bazel build. If you only need the MATLAB support, use the legacy CMake build, otherwise wait for #7293.
