### ISSUE TITLE
Refactor install.py.in

### ISSUE THREAD

**Issue by fbudin69500** [RobotLocomotion/drake#7331]
`install.py.in` is not tested. It is getting complex and it is complicated for reviewers to verify that modifications do not break anything.

Fixup methods should be refactored and have unit tests as well as pycodestyle checking. Those function need to turn into *.py code that is imported by the generated :install program(s).

See comments on PR #7301

**Comment by jamiesnape** [comment]
Relates #6117.

**Comment by jwnimmer-tri** [comment]
(Yes; see 6117 for a possible nit to look into as part of this.)

**Comment by EricCousineau-TRI** [comment]
#10103 might be able to address simplified testing.

**Comment by rpoyner-tri** [comment]
Unless someone else has work-in-progress on this, I will take a look.

**Comment by jwnimmer-tri** [comment]
In #16252, I moved the `install.py.in` code into an `installer.py` binary, which automatically enabled our default linting checks for it.

What remains here is to refactor `installer.py` for maintainability and test coverage.

**Comment by jwnimmer-tri** [comment]
As much as I still don't enjoy the status quo of `installer.py` code, I think refactoring for testability and maintainability is best done _in situ_ as we fix bugs our add new features, not as a standalone task.
