### ISSUE TITLE
A problem about protobuf CMakeLists.txt

### ISSUE THREAD

**Issue by TheOnlyTree** [RobotLocomotion/drake#7341]
Thank for your reading.
I want to install the drake in my computer .(use Ubuntu 16.04)
I follow the "Source installation (OS X, Ubuntu)" website and  when I used the "make" at "/build" folder ,it print an error about this:

> [ 33%] Performing configure step for 'protobuf'
> CMake Error: The source directory "/home/tree/drake/drake-distro/build/externals/protobuf-src" does not appear to contain CMakeLists.txt.
> Specify --help for usage, or press the help button on the CMake GUI.
> make[2]: *** [CMakeFiles/protobuf.dir/build.make:109: protobuf-prefix/src/protobuf-stamp/protobuf-configure] Error 1
> make[1]: *** [CMakeFiles/Makefile2:544: CMakeFiles/protobuf.dir/all] Error 2
> make: *** [Makefile:95: all] Error 2

It seems that miss the file "CMakeLists.txt" .Did I miss some installation steps or other else?
I have to apologize about my English ability and thanks for reading again.

**Comment by jamiesnape** [comment]
There is an issue with the legacy CMake build that will be fixed by #7293. If you need MATLAB, please wait for that, otherwise, please use the Bazel build.
