### ISSUE TITLE
Building without Matlab

### ISSUE THREAD

**Issue by joaospinto** [RobotLocomotion/drake#7351]
After cloning and installing the pre-requisites, I create a `build folder` inside `~/github.com/RobotLocomotion/drake`, and run `cmake .. && make -j$(nproc)` from within that folder. I also tried to run `cmake -DDISABLE_MATLAB=ON ..` instead of `cmake ..`. My build always fails with the following error:
`CMake Error at /home/joao/github/RobotLocomotion/drake/cmake/matlab.cmake:66 (matlab_add_unit_test):
  Unknown CMake command "matlab_add_unit_test".`
What's the problem here? Is it possible to build your project without having Matlab installed? Thanks.

**Comment by Capri2014** [comment]
@joaospinto  what system are you using ?

**Comment by Capri2014** [comment]
@joaospinto Did you try build with bazel ? http://drake.mit.edu/bazel.html?highlight=bazel%20build

**Comment by joaospinto** [comment]
@Capri2014 The fact that bazel does not work well inside docker makes it slightly inconvenient to me. There seem to be ways available workarounds for that, so I will look into those. Did you have the same problem when building with CMake? Or you just uesd Bazel by default?
