### ISSUE TITLE
Documentation incomplete on PiecewisePolynomial: why is the coefficient matrix a matrix and not a vector?

### ISSUE THREAD

**Issue by edrumwri** [RobotLocomotion/drake#7399]
A reasonable examination of both the doxygen and the source code for piecewise polynomial did not reveal what the rows and columns in the coefficient matrix correspond to. An example that I am using indeed uses only row vectors. Is using a matrix only sugar, as appears to be the case?

**Comment by edrumwri** [comment]
Siyuan, please feel free to reassign, as appropriate. You appear to be original author of this file?

**Comment by siyuanfeng-tri** [comment]
This legacy code from drc era. I just happened to be the one slightly updating it. I didn't find it odd, it's rather convenient if you want to have a spline for each element of a N by M thing.

**Comment by edrumwri** [comment]
Ah, then it is sugar. It's fine as a design decision, but I spent a good fifteen minutes trying to figure out what needed to go in the rows (in other words, some documentation would have been very much appreciated!)

**Comment by jwnimmer-tri** [comment]
@edrumwri Maybe you can PR some suggested documentation that would have preempted your confusion?
