### ISSUE TITLE
Support Gurobi 7.5.2

### ISSUE THREAD

**Issue by hongkai-dai** [RobotLocomotion/drake#7484]
Our CI uses gurobi 7.0.2, but gurobi has a new version 7.5.2 that is faster. Our bazel build code hardcodes gurobi 7.0.2 in https://github.com/RobotLocomotion/drake/blob/master/tools/workspace/gurobi/gurobi.bzl#L15

**Comment by hongkai-dai** [comment]
It would be better if we could support both gurobi 7.0.2 and 7.5.2 in the bazel build

**Comment by jwnimmer-tri** [comment]
@hongkai-dai Would there be a problem if we upgraded CI to use 7.5.2 and made that version required?  (In other words, why should we support 7.0.2 at all?)

**Comment by hongkai-dai** [comment]
Your are right, it is better to support gurobi 7.5.2 only. I know there are some students in Russ's group using gurobi, I do not know which version do they use.

@gizatt will it be OK if we upgrade to gurobi 7.5.2 for your use case?

**Comment by jamiesnape** [comment]
Looks like the same license is good for both 7.0.2 and 7.5.2 and the 7.5.2 packages are already downloaded to the Xenial images. We would just need to install 7.5.2 onto the Mac images and work out the logistics of the switchover.

**Comment by gizatt** [comment]
Yup, fine with me!

**Comment by jamiesnape** [comment]
@BetsyMcPhail we will need to install 7.5.2 onto the Mac images, but not entirely sure the two versions can coexist. Can you check whether they will and, if so, run the installer on each of the images? You can grab it from the `drake-provisioning` bucket on S3.

**Comment by jamiesnape** [comment]
Do they actively conflict, though? Looks like Gurobi 7.0.2 is in a versioned folder in `/Library`.

**Comment by BetsyMcPhail** [comment]
Sorry, I misunderstood the question.

Multiple versions of Gurobi can happily coexist. Gurobi 7.5.2 has been installed (/Library/gurobi752) on both the Sierra and High Sierra images and Jenkins has been updated.
