### ISSUE TITLE
Add support for a `call_matlab`-like interface for Python

### ISSUE THREAD

**Issue by EricCousineau-TRI** [RobotLocomotion/drake#7487]
Per @RussTedrake's request, also enabling road warriors who may not have Internet access for MATLAB (@avalenzu).

I have a prototype here: [branch](https://github.com/EricCousineau-TRI/drake/blob/feature/call_python-wip/drake/common/proto/test/call_python_test.cc) | [commit](https://github.com/EricCousineau-TRI/drake/blob/be6d14a/drake/common/proto/test/call_python_test.cc)

This enables basic CLI workflows, and is geared towards enabling interactive notebook workflows as well (IPython / Jupyter), for prototyping plotting after having captured data.

Proposed PR train:

- [x] Add initial Python functionality on top of `call_matlab` code (#7496).
- [x] Add multi-threading code setup.
- [ ] Add instructions on how to run `call_python_client`
- [x] Reshuffle code to have the core RPC stuff be non-MATLAB specific.
- [x] Ensure `call_python_client` is part of `//:install`

**Comment by RussTedrake** [comment]
love it, love it, love it.  (especially the "print", "Howdy").  
the initial python functionality is all i need for now.  the second two proposed PRs are great, but definitely should not block the first.  
Thank you!

**Comment by EricCousineau-TRI** [comment]
Per @jamiesnape's [comment](https://github.com/RobotLocomotion/drake/pull/7496#issuecomment-347209543), I've added the 4th bullet point.
My inclination is that installation would be a little more scoped if this client were to be part of `pydrake` for now. If, for whatever reason, someone wants to use this code outside of Drake, we can split it out at that point.

**Comment by EricCousineau-TRI** [comment]
Per @hongkai-dai's question, I've inserted the new 3rd bullet point (for documenting it).
