### ISSUE TITLE
TSan Issue with monolithic_pick_and_place_demo_test

### ISSUE THREAD

**Issue by m-chaturvedi** [RobotLocomotion/drake#7524]
`bazel test -c dbg --config=tsan --runs_per_test=3 //drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place:monolithic_pick_and_place_demo_test`
[Failing Build](https://drake-jenkins.csail.mit.edu/view/Continuous%20Production/job/linux-xenial-clang-bazel-continuous-memcheck-tsan/559/consoleText)
[Output](https://gist.github.com/m-chaturvedi/4dd54a4e354c053f320ffdb8bab1f7ed)
Seems like it's the same as #6634

**Comment by jwnimmer-tri** [comment]
FYI #9810 fixed one threading problem, but when I tried re-enabling this test even after that PR, the test still failed.

**Comment by jwnimmer-tri** [comment]
This example no longer exists on master.
