### ISSUE TITLE
Algebraic loop error message is unhelpful

### ISSUE THREAD

**Issue by ggould-tri** [RobotLocomotion/drake#7557]
I allegedly have an algebraic loop.  However the error message is unhelpful:
```
*** 1 failure is detected in the test module "Master Test Suite"
Running 5 test cases...
unknown location(0): fatal error: in "TrajectoryTesterSmokeTest": std::logic_error: Algebraic loop detected in DiagramBuilder.
program/controller_analyzer/test/run_one_trajectory.cc(45): last checkpoint: "TrajectoryTesterSmokeTest" fixture ctor
ERROR: Non-zero return code '201' from command: Process exited with status 201
```
The error message should say (1) what systems constitute the loop, and (2) Direct the user toward `DoHasDirectFeedthrough` or the appropriate transmogrification boilerplate to make symbolic analysis work.

**Comment by jwnimmer-tri** [comment]
The "resolves" in #7564 message was in a comment, not the description, so the issue didn't auto-close.
