### ISSUE TITLE
Re-enable RGBD tests in CI

### ISSUE THREAD

**Issue by jwnimmer-tri** [RobotLocomotion/drake#7573]
In #7572, I turned off some tests, because they interrupt developer workflow with flashy and focus-stealing things.  We should find a way for them to pass in CI but also not annoy developers.

**Comment by SeanCurtis-TRI** [comment]
Ultimately, we should be able to generate a GL context and render to buffers without ever actually drawing to the screen. This *might* get resolved when the rendering gets moved to GeometryWorld.

**Comment by kunimatsu-tri** [comment]
You can close this issue now. Please let me know if anything would go wrong for you.
