### ISSUE TITLE
MacOS setup missing brew link ipopt step

### ISSUE THREAD

**Issue by ahundt** [RobotLocomotion/drake#7609]
I think ipopt is keg only so this might need to be added to the setup script:

```brew link ipopt```

**Comment by soonho-tri** [comment]
> I think ipopt is keg only

I don't think `ipopt` is keg-only. Could you check https://github.com/Homebrew/homebrew-science/blob/master/ipopt.rb ?

**Comment by jamiesnape** [comment]
If it were keg only, we definitely should not do this; things are keg only for reason. However, ipopt is not keg only.

**Comment by soonho-tri** [comment]
I think we can close this issue. @ahundt , please feel free to add a comment or re-open it if you need.

**Comment by ahundt** [comment]
ok no worries, probably just got unlinked on my machine for some reason or another. Sorry for the flurry of issues this is my first time installing + building.
