### ISSUE TITLE
Support clang-4.0 in CMake (+ MATLAB) builds

### ISSUE THREAD

**Issue by jwnimmer-tri** [RobotLocomotion/drake#7618]
In #7459, on Ubuntu we switched the Bazel default Clang version to 4.0, but the CMake default version remains 3.9.  That means we have to install both in our setup script (and that we risk 3.9 vs 4.0 incompatibilities since 3.9 now has less coverage).

We should figure out how to make 4.0 work, and then drop support for 3.9

Relates to bazelbuild/bazel#3977.

**Comment by jwnimmer-tri** [comment]
Very happy to see progress here!  I'm kicking over to @jamiesnape to help shepherd since I'm not actively working it at all right now.

**Comment by jwnimmer-tri** [comment]
@jamiesnape I think this one is done?

**Comment by jamiesnape** [comment]
Yes.
