### ISSUE TITLE
FCL Integration Status

### ISSUE THREAD

**Issue by avalenzu** [RobotLocomotion/drake#7656]
This issue serves to track the status of our efforts to use FCL as the primary (only?) collision engine in Drake. The checklist below should be updated as tasks are completed.
## Upstream fixes for working with boxes
([Drake branch](https://github.com/avalenzu/drake/tree/fcl-capsule))
- [ ] There are multiple issues in the FCL `Box`-`Box`- collision:
  - [X] Signed values are reported as negative instead of as positive. (Addressed by [fcl PR 259](https://github.com/flexible-collision-library/fcl/pull/259).)
  - [X] The reported "contact position" lies on the surface of one of the boxes instead of midway between the two deepest penetrating points (it is not clear that which box it lies on is always the first or second; it may depend on configuration). (Addressed by [fcl PR 259](https://github.com/flexible-collision-library/fcl/pull/259).)
  - [ ] Collision between Box and quadratic surfaces (e.g., Sphere and Cylinder) produces highly imprecise solutions. See [proximity_engine_test.cc](https://github.com/RobotLocomotion/drake/blob/master/geometry/test/proximity_engine_test.cc) -- under the `BoxPenetrationTest` tests for concrete examples.

## Upstream fixes for working with capsules 
([FCL branch](https://github.com/avalenzu/fcl/tree/capsule-capsule-intersect) | [Drake branch](https://github.com/avalenzu/drake/tree/fcl-capsule))
- [X] Submit FCL PR to fix inconsistent interpretation of capsule parameters (flexible-collision-library/fcl#225) Addressed by [PR 436](https://github.com/flexible-collision-library/fcl/pull/436)
- [ ] Submit FCL PR to use special-case algorithm for Capsule-Capsule intersection (as it currently does for separation distance).

## Upstream fixes for working with convex polyhedra
([libccd branch](https://github.com/avalenzu/libccd/tree/mpr-penetration-fix) | [FCL branch](https://github.com/avalenzu/fcl/tree/fix-convex-constructor) | [Drake branch](https://github.com/avalenzu/drake/tree/fcl-convex-mesh))
- [X] Submit FCL PR to fix initialization of pointer members in `fcl::Convex` constructor. (Done in https://github.com/flexible-collision-library/fcl/pull/338.)
- [ ] MPR collision point computation appears to be broken. [This branch](https://github.com/avalenzu/libccd/tree/mpr-penetration-fix) has what I (@avalenzu) believe is a fix.

## Issues with cylinders
- [x] See #8049 

There may be additional issues that we should consider in the discussion on ipab-slmc/exotica#184.

**Comment by amcastro-tri** [comment]
@avalenzu. I was thinking about spiking an MBP/GS demo while at HQ in two weeks. Is the mesh (convex, just convex) penetration depth query working with FCL? would you have any unit test/example that shows failure modes?

**Comment by sherm1** [comment]
@SeanCurtis-TRI is this worth keeping around?

**Comment by SeanCurtis-TRI** [comment]
Yeah. We can close it. Of the remaining open issues, only the putative error in MRP collision point computation is of interest to me. The fix doesn't come with a test so it'll have to be investigated from scratch.
