### ISSUE TITLE
Clion refactor does not work after we move from drake-distro/drake to drake-distro

### ISSUE THREAD

**Issue by hongkai-dai** [RobotLocomotion/drake#7685]
Now when we try to refactor a function in Clion, it tries to modify a function in the .cache/bazel directory, instead of the actual code in drake-distro folder. Here is a screenshot when I try to rename a function in `mathematical_program.h`, it says I am trying to modify a non-project file.

![screenshot from 2018-01-02 14-46-17](https://user-images.githubusercontent.com/6314000/34503146-c4928e16-efcb-11e7-97bb-df03e47a28ae.png)
![screenshot from 2018-01-02 14-46-37](https://user-images.githubusercontent.com/6314000/34503150-c7c1a39c-efcb-11e7-8f0d-8234861f36ee.png)

cc @jwnimmer-tri

**Comment by jwnimmer-tri** [comment]
Is this with or without the work-around in #7586 applied first?

**Comment by hongkai-dai** [comment]
I didn't realize there is a work-around, let me try that.
