### ISSUE TITLE
Simulation speed

### ISSUE THREAD

**Issue by JavadHasaneini** [RobotLocomotion/drake#77]
Russ,

I have tried a few simple examples and compared the results with MuJoCo. I have to say that I am very impressed by the accuracy of the results produced by Drake.

The only issue (within the capabilities of Drake) is the simulation time, especially when there are (potential) collisions. Is there any way to increase the speed without writing your dynamics in C?
- Javad

**Comment by sherm1** [comment]
Sorry, please ignore this notification test.
