### ISSUE TITLE
Support 'floating' joints

### ISSUE THREAD

**Issue by christian-rauch** [RobotLocomotion/drake#7701]
I added a `floating` type joint to my URDF:
```
<joint name="camera_pose" type="floating">
  <parent link="base"/>
  <child link="camera_frame"/>
</joint>
```
with the intention to optimise the full 6D pose / transformation between frames `base` and `camera_frame`.

It seems that Drake is not supporting `floating` joints at the moment since it is merging frames `base` and `camera_frame` when loading the URDF: `Welding joint camera_pose`. (In my opinion only `fixed` joints should be welded and Drake should raise a warning for unsupported joints otherwise.)

Can the `floating` joint be supported similar to `FloatingBaseType::kQuaternion`, by adding for example joints `camera_pose_{x,y,z,qw,qx,qy,qz}` between frames `base` and `camera_frame`?

**Comment by RussTedrake** [comment]
sorry you didn't get an answer on this.  It should be a simple enough feature to add to the parser.  we haven't touched it because we're focused on the replacement parsers coming into multibodytree (instead of the rigidbodytree parsers).
