### ISSUE TITLE
install_prereqs.sh should fail more loudly

### ISSUE THREAD

**Issue by jwnimmer-tri** [RobotLocomotion/drake#7724]
https://github.com/RobotLocomotion/drake/blob/master/setup/ubuntu/16.04/install_prereqs.sh has `set -e` so it halts on error.  That's good, but users may not always recognize that the lack of `echo "install_prereqs: success"` indicates a problem, e.g., when the llvm server is slow to return its apt signing key.  We should probably add an exit handler trap to print an error ala https://unix.stackexchange.com/questions/39623/trap-err-and-echoing-the-error-line or related.

**Comment by amcastro-tri** [comment]
Thank you for addressing this @jwnimmer-tri!
