### ISSUE TITLE
kuka_plan_runner crashes with binary install, can't find URDF

### ISSUE THREAD

**Issue by 5yler** [RobotLocomotion/drake#7734]
Installed drake from `drake-latest-xenial.tar.gz` binary release (accessed Jan 11th 2018) into `/opt/drake`. Trying to run `plan_runner` fails because the URDF is not found:

```
09:37 t2box /opt/drake/share/drake/examples/kuka_iiwa_arm ./kuka_plan_runner 
terminate called after throwing an instance of 'std::runtime_error'
  what():  could not find resource: drake/manipulation/models/iiwa_description/urdf/iiwa14_primitive_collision.urdf
Aborted (core dumped)
```

**Comment by hongkai-dai** [comment]
@fbudin69500 could you update the status on this issue? Thanks a lot!

**Comment by EricCousineau-TRI** [comment]
Running locally on machine @ 4c6246197 seems to indicate that this is no longer an issue (due to relevant `find_resource` fixes). Closing.
