### ISSUE TITLE
Create unittests for usage in Jupyter notebooks

### ISSUE THREAD

**Issue by EricCousineau-TRI** [RobotLocomotion/drake#7751]
Specifically, for testing `pydrake` REPL-friendliness,  `call_python_client`, etc.

These may belong in something like `drake-shambhala`; however, if this is widely used feature of Drake, it'd probably be good to have it closer to home.

\cc @rdeits @peteflorence @gizatt

**Comment by rdeits** [comment]
BTW, you can use `jupyter nbconvert` with the `--execute` flag to run a notebook from the command line (and exit with an error if any of the cells throws an error).

**Comment by EricCousineau-TRI** [comment]
Awesome, thanks!

**Comment by EricCousineau-TRI** [comment]
Ended up needing this for some PyTorch stuff, and posted a quick hack here: https://github.com/bazelbuild/rules_python/issues/63

> 
> I quickly put together a simple, kinda hacky, rendition of semi-generalized rules:
> https://github.com/EricCousineau-TRI/repro/tree/52e484e3d68e29bfb8a8e66362c60838161f0dfa/bazel/jupyter_integration
> 
> This allows interactively editing the notebook, using some .runfiles hackery (which I guess may break in upcoming Bazel version) via the ./run script (which perhaps could be replaced via bazel run --direct?).
> You can also run the notebook via bazel run and bazel test.
> 
> Granted, this uses the system jupyter; it focuses on the content of notebooks, not necessarily using a Bazel version of IPython, but I'm sure that could be easy to patch in.

**Comment by EricCousineau-TRI** [comment]
Closing in favor of tracking via #9650
