### ISSUE TITLE
Installed version of drake-lcm-spy no longer works

### ISSUE THREAD

**Issue by sammy-tri** [RobotLocomotion/drake#7752]
As of 6eca6e7 (libbot removal), the installed version of drake-lcm-spy now prints
```
Error: Could not find or load main class lcm.spy.Spy
```
and does not run.  It still runs from within the tree as `bazel-bin/lcmtypes/drake-lcm-spy`.

**Comment by sammy-tri** [comment]
#7750 is reported to fix this issue

**Comment by fbudin69500** [comment]
#7760 should address the issue in a cleaner way than #7750.

**Comment by jwnimmer-tri** [comment]
Merged #7760.
