### ISSUE TITLE
pydrake: Add `RgbdRenderer` for use with `RigidBodyTree` and general shading

### ISSUE THREAD

**Issue by EricCousineau-TRI** [RobotLocomotion/drake#7753]
For simplicity, it'd be nice to move some of the `RigidBodyTree` mechanisms (e.g. `UpdateModelPoses`, visual registration, etc.) to another utility file to minimize the number of components needed to expose to `pybind` for the time being.

Steps:
- [ ] Expose `RgbdRenderer` / `RigidBodyTreeRenderer`
- [ ] Add an unstable /  unsupported API for shaders.

\cc @kunimatsu-tri @gizatt and Chris Sweeny (do you have a GitHub acct?)

**Comment by gizatt** [comment]
@ChristopherSweeney

**Comment by EricCousineau-TRI** [comment]
Question: Would using `RigidBodyTree` work for y'all?
Or would you want to work with raw (Drake) shapes?

C++ `RgbdRenderer` class:
https://github.com/RobotLocomotion/drake/blob/master/systems/sensors/rgbd_renderer.h#L88

(Just using `RigidBodyTree` would simplify what all I need to expose for the time being.)

**Comment by kunimatsu-tri** [comment]
My original thought of making `RgbdRenderer` apart from `RgbdCamera` was that being Drake's system and `RigidBodyTree` independent just so that it could be used anywhere as a library. 

So, I'm ok with @EricCousineau-TRI 's proposal as long as the original idea would be preserved.

**Comment by jwnimmer-tri** [comment]
@EricCousineau-TRI I'm assuming that we don't care about new RBT features anymore?  Can this be closed?

**Comment by EricCousineau-TRI** [comment]
Yup.

FTR, the new abstractions for rendering will be `RenderEngine` for interfacing `SceneGraph` / `GeometryState`.
