### ISSUE TITLE
Mac install_prereqs.sh upgrades everything

### ISSUE THREAD

**Issue by rdeits** [RobotLocomotion/drake#7786]
I was surprised to see just how long `install_prereqs.sh` takes on mac until I noticed that it runs `brew upgrade`, which upgrades every single homebrew package on the system, including those not used by Drake. This seems like a somewhat unfriendly thing to do without warning, as it could be the source of lots of other subtle versioning issues for packages entirely outside the Drake ecosystem.

**Comment by rdeits** [comment]
This also means that *any* failure in the upgrade of any package will cause `install_prereqs.sh` to error out, which has happened several times in a row now for packages completely unrelated to Drake.

**Comment by jamiesnape** [comment]
Yes, it is deliberate. Homebrew itself basically relies on having the latest versions of all packages. Invariably Homebrew packages break because you haven't upgraded everything rather than being selective.
