### ISSUE TITLE
Some built filenames are too long for ecryptfs users

### ISSUE THREAD

**Issue by ggould-tri** [RobotLocomotion/drake#7791]
ecryptfs (used for homedir encryption on linux systems, required for all TRI computers) limits filenames to 143 characters.

Drake's documentation build results in filenames like "classdrake_1_1examples_1_1kuka__iiwa__arm_1_1box__rotation_1_1_iiwa_and_box_plant_with_state_estimator_a8a9de6aad54e3098b0144c7dd2040317_cgraph.md5" (148 characters).

Not to say that "143 characters ought to be enough for anyone" but...  143 characters ought to be enough for anyone.

**Comment by jwnimmer-tri** [comment]
https://www.stack.nl/~dimitri/doxygen/manual/config.html#cfg_short_names

**Comment by jwnimmer-tri** [comment]
The question would be if we turn it on always and then our website may have less readable URL slugs, or whether our doxygen.py wrapper should query whether long files are trouble and then enable the option only if so.

**Comment by jwnimmer-tri** [comment]
Possibly worth solving in concert with #7920.

**Comment by jwnimmer-tri** [comment]
@jamiesnape I'll assign this to you in case the shortname setting helps with #7920; if you end up not touching this issue, you can assign it back to me.

**Comment by jwnimmer-tri** [comment]
TRI no longer uses ecryptfs.  I think it would be OK to close this issue?

**Comment by ggould-tri** [comment]
TRI still supports ecryptfs homedir encryption -- in fact this is still the case on my desktop machine.

**Comment by jwnimmer-tri** [comment]
@ggould-tri Can you check locally wheather generating the built documentation into `/tmp/something` instead of the source tree is a suitable work-around?

**Comment by jwnimmer-tri** [comment]
Closing out as "backlog unlikely to reach an actionable state within a reasonable timeframe".  In any case, it's likely that #14834 and alike have resolved this in any case (they build into and serve from a tmpfs).
