### ISSUE TITLE
Rename @lcm to avoid directory name collisions

### ISSUE THREAD

**Issue by jwnimmer-tri** [RobotLocomotion/drake#7799]
In `WORKSPACE`, we use `@lcm` as the name for the LCM external.  When combined with pythonpath module lookup semantics and native `*.so` loading, this ultimately leads to confusing breaks like #7788.  (See also source code comments nearby there for more details.)

We should explore whether simple using a new name allows us to remove the work-arounds.

**Comment by EricCousineau-TRI** [comment]
Potentially related: https://github.com/bazelbuild/bazel/issues/3998
(Had run into this when prototyping `external_data` stuff.)

Should we consider using `--noexperimental_python_import_all_repositories` to avoid this in the future?

**Comment by jwnimmer-tri** [comment]
I started a WIP a while ago at https://github.com/jwnimmer-tri/drake/commits/rename-lcm.  I seem to recall it was getting hairy when I paused.

**Comment by jwnimmer-tri** [comment]
We can do this if / when we need.  Doesn't seem to be actively causing pain right now.
