### ISSUE TITLE
vector_gen: error: cannot use -i when reading from stdin.

### ISSUE THREAD

**Issue by jamiesnape** [RobotLocomotion/drake#7803]
On Mac locally. Did not notice it earlier, so maybe post #7798?
```
INFO: From SkylarkAction tools/vector_gen/test/lcmt_sample_t.lcm:
error: cannot use -i when reading from stdin.
```
Despite the protestation, does not actually seem to be an error in that the build completes successfully.

**Comment by jwnimmer-tri** [comment]
Yeah, probably related to #7798.  I will see if I can tease out what's happening.
