### ISSUE TITLE
DeclarePublishPeriodSec still lingers in the doxygen

### ISSUE THREAD

**Issue by RussTedrake** [RobotLocomotion/drake#7834]
e.g. 
http://drake.mit.edu/doxygen_cxx/classdrake_1_1systems_1_1lcm_1_1_lcm_publisher_system.html#ae1f56c09e30e20d5b5789eec13c1e1e3

(but please search in case there is more).  i seems that the correct name is now
DeclarePeriodicPublish
http://drake.mit.edu/doxygen_cxx/classdrake_1_1systems_1_1_leaf_system.html#a1adf7020dee795fd1b34b023c447eb6f

**Comment by edrumwri** [comment]
Note that this comment is now present only in attic files (drake_visualizer.h and frame_visualizer.h)

**Comment by edrumwri** [comment]
All traces have magically been removed from the code (good things come to those who wait).
