### ISSUE TITLE
Add a launcher name parameter to `drake_java_binary()`

### ISSUE THREAD

**Issue by fbudin69500** [RobotLocomotion/drake#7842]
[`drake_java_binary()` bazel function](https://github.com/RobotLocomotion/drake/blob/master/tools/skylark/drake_java.bzl#L30) declares a new target named ${name}-launcher without letting the user choose the name or whether this new target is created. It would be better to have a new argument such as launcher_name =lcm-spy-launcher` where the caller would have to specify the launcher explicitly. In general BUILD rules should be immediately obvious, so creating targets that the user has to know about, but didn't explicitly name, tends to be a surprise. (Issue raised in PR#7802)

**Comment by EricCousineau-TRI** [comment]
Closing this for now, doesn't seem to be a pain point.
