### ISSUE TITLE
Update Ubuntu AMIs to Bazel 0.9

### ISSUE THREAD

**Issue by jwnimmer-tri** [RobotLocomotion/drake#7854]
The Ubuntu setup changed in #7846.  Please re-spin new Ubuntu AMIs.

If we have other changes pending (@soonho-tri?), I'm okay to wait a bit to get them.

**Comment by soonho-tri** [comment]
The new `.deb`s for `dReal` and `libibex-dev` are ready but we need an update on `pkg_config.bzl` which I'm working on now. I'll ask for another AMIs update.

**Comment by BetsyMcPhail** [comment]
The Xenial AMI has been updated. As always, it could take awhile for Jenkins to cycle through the old images.
