### ISSUE TITLE
Add a version (or timestamp or commit SHA) file to the install

### ISSUE THREAD

**Issue by jamiesnape** [RobotLocomotion/drake#7903]
Per discussion with @RussTedrake and @stonier, we need a file that is embedded in the install, so that we can identify the version of an arbitrary installed version of Drake. At its simplest, this could be a file `share/doc/drake/VERSION` with a nightly timestamp or commit SHA. More sophisticated would be a nice header and Python variable than could also be queried programmatically. Once we have `major.minor.patch.tweak` versioning (which we could do now with `0.x.x.yyyymmdd` if we really wanted), CMake would also want to know this information.

**Comment by jamiesnape** [comment]
(Note if we do this within this repo using Bazel we have to be careful not to break caching of the rest of the build. Not difficult, but something to remember.)

**Comment by jamiesnape** [comment]
@EricCousineau-TRI To answer the question in #7906, if you have time today, please take this issue, otherwise I will work on it tomorrow morning.

**Comment by jwnimmer-tri** [comment]
Maybe somewhere around https://github.com/RobotLocomotion/drake-ci/blob/master/driver/configurations/bazel/step-build.cmake#L108 we could output the date (and also `git rev-parse HEAD`) to an installed file such as `share/drake/version.txt`?

**Comment by jamiesnape** [comment]
That is the quick version, yes.

**Comment by jamiesnape** [comment]
RobotLocomotion/drake-ci@3d3bb24f9a6f6162c7e48d5fdc9bacea89eab524. I will leave this open at least until I have checked the nightly builds tomorrow morning.

**Comment by jamiesnape** [comment]
Nightlies are all good and contain `/opt/drake/share/doc/drake/VERSION.txt` with `<date> <commit>` as the contents.

**Comment by EricCousineau-TRI** [comment]
Quick follow-up question: Is it easy to programmatically query this information? Is it easily discoverable via `FindResource`?

e.g. in Python, it'd be nice to have something like `dump_debug_info()`, which would print version, platform, etc., when students have issues.

**Comment by jamiesnape** [comment]
> Quick follow-up question: Is it easy to programmatically query this information? Is it easily discoverable via FindResource?

Not at all. It is human readable information for now.

**Comment by jamiesnape** [comment]
(Create a follow up issue if necessary.)

**Comment by EricCousineau-TRI** [comment]
Yup, shall do.
