### ISSUE TITLE
Add versioning for Drake Releases

### ISSUE THREAD

**Issue by EricCousineau-TRI** [RobotLocomotion/drake#7906]
Given that Russ's class is starting soon, we should provide a mechanism to tag a release so that we can trace that back to a source tree / release build.

Perhaps start by providing a Python-only Git SHA, provided upon install (and stubbed during development in Bazel)?

@jamiesnape Should you or I take this?

\cc @RussTedrake @stonier

**Comment by jamiesnape** [comment]
Duplicate of #7903?

**Comment by EricCousineau-TRI** [comment]
Oops, yup!
