### ISSUE TITLE
pydrake: Make a function to dump debug (support) information

### ISSUE THREAD

**Issue by EricCousineau-TRI** [RobotLocomotion/drake#7916]
Follow-up from #7903:

It'd be useful to have a one-stop function, first in pydrake, later in C++, that can dump things like Drake version, platform, etc.

As a first step, this method should be able to query `VERSION.txt` (if it exists) using `FindResource` to trace version information.

\cc @jamiesnape

**Comment by jamiesnape** [comment]
`VERSION.TXT` is not actually below the resource root (and I do not think it should be), so you may prefer to skip the first step. `VERSION.TXT` is really just an interim fix since the class is starting so soon.

**Comment by EricCousineau-TRI** [comment]
What would a better step be? Have Drake generate something in source on `install`?
This seems like it'd be easy to have a "devel" version for Python, but not so for C++ - but I'd like to focus on Python first.

**Comment by jwnimmer-tri** [comment]
The release engineering for compiled-in version badging can be tricky.  For now, a small human-only use python method that opened `/opt/drake/share/doc/drake/VERSION.TXT` and returned its contents (or some "unknown" text) would probably go a long way?

**Comment by jamiesnape** [comment]
I agree. We do not need to overthink this for now.

**Comment by EricCousineau-TRI** [comment]
Effectively resolved via #7903.
