### ISSUE TITLE
Add Python bindings for AutomotiveSimulator and/or upstream components

### ISSUE THREAD

**Issue by EricCousineau-TRI** [RobotLocomotion/drake#7918]
- [x] Subset of Maliput API
- [ ] `AutomotiveSimulator`
- [x] `SimpleCar` Cars, Controllers, Planners
- [ ] `AutomotiveSimulator`?

Needs from #7660:
- `PoseVector`, `PoseBundle`
- `AbstractValue`, creating them for `FixInputPort`

\cc @clalancette @mikaelarguedas @stonier

**Comment by jadecastro** [comment]
Complete, with the exception of `AutomotiveSimulator`, which we don't need bindings for.
