### ISSUE TITLE
Size of RobotLocomotion.github.io repo has exploded again

### ISSUE THREAD

**Issue by jamiesnape** [RobotLocomotion/drake#7920]
1.67 GB currently, documentation jobs may start timing out at some point soon.

FYI @stonier.

**Comment by jamiesnape** [comment]
To me, looks like we could still tweak some more Doxygen settings. Small code changes are still inducing large numbers of changed generated documentation files.

**Comment by RussTedrake** [comment]
is it the size of the doxygen content or the compilation time of doxygen that is the issue?

**Comment by jamiesnape** [comment]
Cumulative size of the lots of surprisingly large diffs. Makes the clone of the repo slow. Generation time is fine. Strictly a byproduct of using a git repo.

**Comment by sherm1** [comment]
Is it possible to nuke that repo altogether when it gets big and start fresh? (Assuming it just contains machine-generated content.)

**Comment by jamiesnape** [comment]
Yes, we keep doing that every few months already. This is as much a reminder for me to do that soon, but equally it would be nice to fix the root cause.

**Comment by jwnimmer-tri** [comment]
Possibly worth solving root cause in concert with #7791.

**Comment by EricCousineau-TRI** [comment]
Given that this is not a huge pain point and not actively working on this, will close for now.
