### ISSUE TITLE
Have `RgbdCamera::RgbdCamera(..., show_window = {true,false})` be changeable in one location.

### ISSUE THREAD

**Issue by rpoyner-tri** [RobotLocomotion/drake#7935]
https://github.com/RobotLocomotion/drake/issues/7908#issuecomment-362605359
splitting out as new issue.

Goal is to have bazel test //... work out-of-box (no manual config, no read-the-FAQ), or failing that, only have one place to make some change so it works.

**Comment by EricCousineau-TRI** [comment]
Howdy! I've updated title to emphasize that this issue is for having one place to make it work, and leave #7908 for VTK issues - per f2f with @jamiesnape, that was the original intent.
I think that having `bazel test //...` would be addressed by #7908 itself as well.
