### ISSUE TITLE
Promote `geometry/test_utils/expect_error_message.h` to `drake/common`

### ISSUE THREAD

**Issue by amcastro-tri** [RobotLocomotion/drake#8003]
There are some really useful testing utilities there that are worth promoting so everyone can benefit from them.
Now in use by:
 - `drake/geometry/` code.
 - `drake/multibody/multibody_tree` code, #7995.
 - `drake/systems/framework/test/diagram_builder_test.cc`

**Comment by amcastro-tri** [comment]
I just found out that `diagram_builder_test.cc` has the same macro. Rule of three satisfied now! List updated.

**Comment by amcastro-tri** [comment]
BTW. @soonho-tri proposes ([see comment](https://reviewable.io/reviews/robotlocomotion/drake/7995#-L4qfFOJYbzSN0vlFPVq)) to append these macros with `DRAKE_`

**Comment by soonho-tri** [comment]
FYI, this should be a complete list of the files using the macro:
```
$ ag "EXPECT_ERROR_MESSAGE" -l
common/test/copyable_unique_ptr_test.cc
common/test/type_safe_index_test.cc
geometry/test_utilities/expect_error_message.h
geometry/test/frame_id_vector_test.cc
geometry/test/query_object_test.cc
geometry/test/geometry_state_test.cc
geometry/test/geometry_system_test.cc
systems/framework/test/diagram_builder_test.cc
```

**Comment by SeanCurtis-TRI** [comment]
Those files are like my breadcrumbs -- that paint a clear picture of which code I've been walking through.

Thanks, @soonho-tri for the thorough accounting. And I also support the `DRAKE_` prefix.
