### ISSUE TITLE
`drake.lcmtypes` does not have an `__init__.py`, thus cannot always be imported

### ISSUE THREAD

**Issue by EricCousineau-TRI** [RobotLocomotion/drake#8012]
Not sure when exactly this passes or fails, but `lcmtypes_py` does not have an `__init__.py`, so importing things breaks.

Trying to use `show_contacts.py` with `//tools:drake_visualizer`:
```
...
    messageClass=lcmdrakemsg.lcmt_contact_results_for_viz,
AttributeError: 'module' object has no attribute 'lcmt_contact_results_for_viz'
```

A solution is to place an `__init__.py` in `lcmtypes_py`.

\cc @kunimatsu-tri @amcastro-tri

**Comment by jwnimmer-tri** [comment]
The codegen by default makes one.  Maybe its a drake-the-workspace vs drake-the-module confusion?

**Comment by EricCousineau-TRI** [comment]
I don't think so - it's reading your `//:module_py` code to check the `_needs_lcmtypes_pathing` logic. When I inspected `.runfiles`, `.../drake_visualizer.runfiles/drake/lcmtypes` had no `__init__.py`.

If the codegen does generate an `__init__.py`, I think that's going in under `drake/lcmtypes/drake`.

**Comment by jwnimmer-tri** [comment]
Yeah, I'd misunderstood which `__init__.py` you'd meant was missing.  I see what the PR is trying to do now; I'll give it some mental energy later on to see if it seems robust.
