### ISSUE TITLE
Master doesn't compile on my machine

### ISSUE THREAD

**Issue by tkoolen** [RobotLocomotion/drake#803]
This is when compiling under OSX with Matlab 2014a. Here's the error I'm getting:

```
/Users/twan/code/MIT/drake-distro/drake/systems/plants/contactConstraintsmex.cpp:224:37: error: non-constant-expression cannot be narrowed from type 'int' to 'mwSize' (aka 'unsigned long') in initializer list [-Wc++11-narrowing]
      const mwSize cellDims[] = {1, 2*nk};
                                    ^~~~
/Users/twan/code/MIT/drake-distro/drake/systems/plants/contactConstraintsmex.cpp:224:37: note: override this message by inserting an explicit cast
      const mwSize cellDims[] = {1, 2*nk};
                                    ^~~~
                                    static_cast<mwSize>( )
```

@psiorx Looks like you last touched these lines.
Why didn't the build servers catch this?

**Comment by tkoolen** [comment]
My clang --version:
```
Apple LLVM version 6.0 (clang-600.0.56) (based on LLVM 3.5svn)
Target: x86_64-apple-darwin14.0.0
Thread model: posix
```

**Comment by RussTedrake** [comment]
the mac build server is way underpowered and is way behind.  (drake001).  the macpro is the intended solution, which I will bring up soon.

**Comment by psiorx** [comment]
@tkoolen Looks like clang doesn't like the implicit cast.  I'll fix this in my latest pull request.

**Comment by tkoolen** [comment]
I'm a little held up until the fix is in, so if the pull request doesn't get accepted quickly, could you submit a new one fixing just that line?

**Comment by psiorx** [comment]
Yes. Sorry didn't see this. https://github.com/RobotLocomotion/drake/pull/806

**Comment by tkoolen** [comment]
Thanks!
