### ISSUE TITLE
Add Maliput RBounds, HBounds helpers.

### ISSUE THREAD

**Issue by jadecastro** [RobotLocomotion/drake#8032]
There are some places in the `automotive` codebase where we have code like:
```
  if (lane_position.r() < r_bounds.min() ||
      lane_position.r() > r_bounds.max()) { ... }
```
This exists, for instance, in several places within `pose_selector.cc`.

It would be nice to simplify with the aid of helpers such as 
`RBounds::contains(lane_position, tol)` or `RBounds::contains(lane_position)` and 
`HBounds::contains(lane_position, tol)` or `HBounds::contains(lane_position)`.

/cc @maddog-tri

**Comment by jwnimmer-tri** [comment]
Per #11603, the automotive folder is deprecated, so I'll close this issue as "won't fix"; @jadecastro if this issue is still important to you, please re-open it in a different issue tracker.

\CC @liangfok FYI
