### ISSUE TITLE
Port automotive tests and examples to multilane

### ISSUE THREAD

**Issue by jadecastro** [RobotLocomotion/drake#8033]
Per a discussion in #8028, various examples and unit tests depend on the monolane backend, but these eventually will need to be replaced with multilane.  Places identified that need to be ported:
- [x] `pose_selector_test.cc`
- [x] `monolane_onramp_merge.h`
- [x] `maliput_railcar_test.cc`

Relates #4934.

**Comment by agalbachicar** [comment]
After #9484, this issue is complete.
