### ISSUE TITLE
Add autopep8 to automate fixing Python lint errors

### ISSUE THREAD

**Issue by EricCousineau-TRI** [RobotLocomotion/drake#8070]
\cc @jwnimmer-tri

**Comment by EricCousineau-TRI** [comment]
@jamiesnape may have found a better tool than `autopep8` for automating this.

**Comment by EricCousineau-TRI** [comment]
Per f2f: https://github.com/google/yapf

**Comment by jwnimmer-tri** [comment]
FYI -- Many TRI people now like `black` https://github.com/psf/black the best.

**Comment by jwnimmer-tri** [comment]
Closing out as "backlog unlikely to reach an actionable state within a reasonable timeframe".

If we find some tool that we like (black) and get it up to 100% usage in Anzu, then we should upstream it to Drake as the next step.
