### ISSUE TITLE
pydrake: AddValueInstantiation doesn't place the class in the correct module

### ISSUE THREAD

**Issue by jadecastro** [RobotLocomotion/drake#8074]

**Comment by EricCousineau-TRI** [comment]
Reproduction commit (from virtual f2f (v2v?)):
https://github.com/jadecastro/drake/blob/416123ad47f53556ac36e378e83c9b43de15b750/bindings/pydrake/automotive_py.cc#L39

**Comment by EricCousineau-TRI** [comment]
It actually wasn't an issue with the wrong module being used (the template instantiation was being registered correctly, just the wrong *name* was being printed) - rather, the input is somehow getting converted to a `BasicVector<double>`? (at least, that's how RTTI sees it)
https://github.com/EricCousineau-TRI/drake/commit/4edc923221c3f3948fc28813aaf0e13d9306c3dc

The output:
```Yar:  <pydrake.systems.framework.AbstractValue object at 0x7f212bd668f0>
[ 0.  0.  0.  0.]
 OutputSteeringCommand: data type: 1
 stuff: drake::systems::Value<drake::systems::BasicVector<double>>
```

So it sees it correctly in the Diagram context, but once it gets funneled to the system, something goes awry?

**Comment by EricCousineau-TRI** [comment]
Error was due to some mishaps I introduced in our pybind fork; luckily, the fix was relatively easy:
https://github.com/RobotLocomotion/pybind11/pull/10
