### ISSUE TITLE
forwardKin Jacobians don't match between mex and MATLAB for RBMs with multiple floating quat joints

### ISSUE THREAD

**Issue by avalenzu** [RobotLocomotion/drake#808]
Adding the following line after line 16 in `testForwardKin` causes it to fail the `valuecheck` on line 115:

```matlab
robot = robot.addRobotFromURDF('FallingBrick.urdf', [], [], options); 
```

**Comment by avalenzu** [comment]
Meant to tag @tkoolen on this one.

**Comment by tkoolen** [comment]
I'll take a look.
@RussTedrake could you assign this to me?
