### ISSUE TITLE
RigidBodyTree: Automatically add frames for each body

### ISSUE THREAD

**Issue by EricCousineau-TRI** [RobotLocomotion/drake#8089]
In the interim, it'd be nice if RigidBodyTree automatically generated frames for bodies, such that you can refer to a body purely using a frame, rather than a workaround like #8085.

**Comment by jwnimmer-tri** [comment]
@EricCousineau-TRI I'm assuming that we don't care about new RBT features anymore?  Can this be closed?

**Comment by EricCousineau-TRI** [comment]
Yup. (Actually, I should've closed this, as I had submitted this PR at some point...)
