### ISSUE TITLE
Make Doxygen High Level Documentation Consistent - Python Bindings, Stochastic Systems

### ISSUE THREAD

**Issue by EricCousineau-TRI** [RobotLocomotion/drake#8093]
Presently, there are two top-level pages which are high-level overviews, `Python Bindings` (which has an awkward `aliases` Module) and `Stochastic Systems`, while there are multiple Modules.

![image](https://user-images.githubusercontent.com/26719449/36330754-06969ef2-1339-11e8-9067-7405c24057d3.png)

For consistency, these should be placed under `Modules` with the other high-level documentation.

@RussTedrake Would you be OK with me moving the `Stochastic Systems` page under `Modules`?

\cc @jwnimmer-tri

**Comment by RussTedrake** [comment]
Definitely.  Slip it in wherever it fits.  Please note that there are link to some of these pages from sphinx, which may need to be repaired if you make these moves.

**Comment by EricCousineau-TRI** [comment]
Resolved via #9494.
