### ISSUE TITLE
python bindings for symbolic Monomial, MonomialBasis, and Polynomial

### ISSUE THREAD

**Issue by RussTedrake** [RobotLocomotion/drake#8098]
I took a slapdash pass at this trying to enable one particular optimization problem in python:
https://github.com/RussTedrake/drake/commit/1cef69a8df30324e2b2b9f2faa9847ce7e0ac06e

but it really needs to be done correctly and more carefully.  There are not that many operators to bind, really, but doing it properly matters.  @soonho-tri -- might you be willing?

**Comment by soonho-tri** [comment]
I'll work on this issue today. Please find me in Slack if you need.

**Comment by RussTedrake** [comment]
hoorah!
