### ISSUE TITLE
Override `--test_summary` option in CI

### ISSUE THREAD

**Issue by soonho-tri** [RobotLocomotion/drake#8127]
Reference: https://docs.bazel.build/versions/master/command-line-reference.html#flag--test_summary

For now, `tools/bazel.rc` has `--test_summary=terse` and as a result the logs in Jenkins do not include information about test running time. This is available in CDash but it would be nice to have the information in the Jenkin log as well.

/cc @m-chaturvedi

**Comment by jamiesnape** [comment]
Fixed in https://github.com/RobotLocomotion/drake-ci/commit/dff67e49ebdfc5e7d8883029f47cb63bebf50e84.
