### ISSUE TITLE
Generated mesh files are put in source tree

### ISSUE THREAD

**Issue by tkoolen** [RobotLocomotion/drake#813]
When I run e.g. examples/PR2/runSaggitalPassive, a bunch of .wrl files are generated and simply stored in the same directory as the obj meshes they were generated from. The wrl files are not in .gitignore, so they show up in my untracked files list.

Should we: 1) add the files to .gitignore, or 2) store the files somewhere else? For 2), one option is to store them in a subfolder of the folder returned by `tempdir` (and maybe fall back to storing it in the source tree and giving a warning if it doesn't exist).

What do you think?

**Comment by RussTedrake** [comment]
I've been slowly adding them to gitignore

- Russ
