### ISSUE TITLE
python bindings for trig in symbolic expressions

### ISSUE THREAD

**Issue by gizatt** [RobotLocomotion/drake#8144]
Would be nice to have support for more powerful functions with the symbolic stuff in Python! In particular, having trig is enough to do coordinate transformations.

**Comment by EricCousineau-TRI** [comment]
@soonho-tri Do you have bandwidth for this, or would you like me to take it?

**Comment by soonho-tri** [comment]
I can start working on it tomorrow. If you want to do it before then, please feel free to assign it to yourself.

**Comment by soonho-tri** [comment]
FYI @EricCousineau-TRI , I've assigned myself.
