### ISSUE TITLE
lcm generated files include system headers

### ISSUE THREAD

**Issue by soonho-tri** [RobotLocomotion/drake#8155]
We're making a transition to use quoted includes to avoid conflicts with system libraries. #8151 is an effort to handle lcm and external lcm types. While testing #8151 and #8153, I've found that there is still an issue to handle.

```
ERROR: /Users/soonhok/work/drake/multibody/rigid_body_plant/BUILD.bazel:90:1: C++ compilation of rule '//multibody/rigid_body_plant:contact_results_to_lcm' failed (Exit 1)
In file included from multibody/rigid_body_plant/contact_results_to_lcm.cc:1:
In file included from bazel-out/darwin-dbg/bin/multibody/rigid_body_plant/_virtual_includes/contact_results_to_lcm/drake/multibody/rigid_body_plant/contact_results_to_lcm.h:6:
bazel-out/darwin-dbg/bin/lcmtypes/_virtual_includes/contact_results_for_viz/drake/lcmt_contact_results_for_viz.hpp:177:36: error: cannot initialize a member subobject of type 'void *' with an lvalue of type 'int64_t ()' (aka 'long long ()')
    const __lcm_hash_ptr cp = { p, lcmt_contact_results_for_viz::getHash };
                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

Here, when lcm processes [https://github.com/RobotLocomotion/drake/blob/master/lcmtypes/lcmt_contact_results_for_viz.lcm](lcmtypes/lcmt_contact_results_for_viz.lcm) file, it generates `lcmt_contact_results_for_viz.hpp` file which includes:

```c++
#include <lcm/lcm_coretypes.h>
```

We need to replace the line with `#include "lcm/lcm_coretypes.h"` (and similarly all bracketed include headers to quoted ones).

**Comment by jamiesnape** [comment]
Yes.
