### ISSUE TITLE
Re-enable QuaternionFloatingMobilizer.Simulation test case

### ISSUE THREAD

**Issue by jwnimmer-tri** [RobotLocomotion/drake#8177]
In #8176 (assuming it merges) we disabled a test case that fails under valgrind -- `QuaternionFloatingMobilizer.Simulation` in `multibody/multibody_tree/test/floating_body_test.cc`.  This issue tracks re-enabling that test case.

**Comment by amcastro-tri** [comment]
Submitted fix in #8192.
