### ISSUE TITLE
Use py::implicitly_convertible and clean up `symbolic_py.cc`

### ISSUE THREAD

**Issue by soonho-tri** [RobotLocomotion/drake#8187]
https://github.com/RobotLocomotion/drake/pull/8179#issuecomment-368638516

**Comment by EricCousineau-TRI** [comment]
BTW I realize my comment had extra info in it; whether or not `A` was a custom type would not have affects its usage in this case, since both `Expression` and `Variable` are custom; it would affect cases where a class is implicitly convertible from a by-value converted type, like `int` or `str`.
