### ISSUE TITLE
constructModelmex skips actuators and position constraints

### ISSUE THREAD

**Issue by psiorx** [RobotLocomotion/drake#820]
Currently, when a manipulator with lots of loop constraints (like the robotiq hand) is compiled, the RigidBodyLoop elements are not present in the mex model.  The same is true for actuated joints and their respective constraint functions.

constructModelmex should replicate these elements in the c++ version of the RBM at compile time.  Another option would be to have these elements created by the c++ urdf parser.  Ideally, both would work.

**Comment by RussTedrake** [comment]
need to also make sure we populate the B ma
