### ISSUE TITLE
Eigen's normalize() does not work as expected with symbolic matrix

### ISSUE THREAD

**Issue by soonho-tri** [RobotLocomotion/drake#8207]
https://github.com/RLovelett/eigen/blob/master/Eigen/src/Core/Dot.h#L133-L148

```c++
/** Normalizes the vector, i.e. divides it by its own norm.
  *
  * \only_for_vectors
  *
  * \warning If the input vector is too small (i.e., this->norm()==0), then \c *this is left unchanged.
  *
  * \sa norm(), normalized()
  */
template<typename Derived>
EIGEN_DEVICE_FUNC inline void MatrixBase<Derived>::normalize()
{
  RealScalar z = squaredNorm();
  // NOTE: after extensive benchmarking, this conditional does not impact performance, at least on recent x86 CPU
  if(z>RealScalar(0))
    derived() /= numext::sqrt(z);
}
```

It has a line to check if the squared norm of an input is positive. I'll check if we can provide an `symbolic` specialization for it. `stableNormalize` also fails due to the same cause.

**Comment by jwnimmer-tri** [comment]
The OP doesn't explain the situation that led to this request.  Browsing through all of Drake, I'm unable to find any places where we're manually working around this in a way where we'd like sugar to fix it.  The only few places I see (e.g., rotation_matrix) already want to add fail-fast guards against too-small norms, which means the Eigen function isn't sufficient on its own anyway.

Closing as "won't fix" for now.  We can re-open in the future if we find some need for this sugar.
