### ISSUE TITLE
c++ urdf parser treats floating base / fixed joints as dof

### ISSUE THREAD

**Issue by psiorx** [RobotLocomotion/drake#826]
The resulting RBM has more of degrees of freedom when parsed in c++ versus MATLAB.  This makes interoperability between the c++ and MATLAB objects more difficult (position constraint matrices are different sizes, etc).

There's a workaround for this in testURDFmex.  Ultimately, the c++ urdf parser should produce output that is consistent with what gets built by constructModelmex.  This is related to, but distinct from, #820 .

**Comment by RussTedrake** [comment]
resolved.
