### ISSUE TITLE
testMixedIntegerConvexDemo can fail to meet tolerance

### ISSUE THREAD

**Issue by RussTedrake** [RobotLocomotion/drake#827]
Site: drake002
Build Name: master-RobotLocomotion-master
Build Server Directory: /tmp/drake-master-2313/drake
CDash: http://kobol.csail.mit.edu/cd/index.php?project=Drake&date=20150304

Most recent commits to drake included in this build:

```
b6a0f07 Merge pull request #821 from hongkai-dai/rotate_ABB_base
5deae73 rotate the ABB base by 90 degrees, fix a bug in ATI sensor urdf
b1fd26c Merge pull request #799 from RussTedrake/no_boost
962e53c Merge branch 'master' into no_boost
9f3031d fix compile error on win32.  quiet a bunch of warnings, too
```

364 tests run:
344 passed
0 cancelled (with missing dependencies )
6 timed out
14 failed
 4 <a href="https://github.com/RobotLocomotion/drake/issues/18">known
issue #18</a>: Singularities in the euler-angle floating base joint cause
infrequent errors on unit tests with random initial conditions
 2 <a href="https://github.com/RobotLocomotion/drake/issues/310">known
issue #310</a>: testLCMPlant fails on parallel build because it can't keep
up with realtime
 1 <a href="https://github.com/RobotLocomotion/drake/issues/311">known
issue #311</a>: testFloatingBase test can fail to match tolerance
 4 <a href="https://github.com/RobotLocomotion/drake/issues/374">known
issue #374</a>: failing imu unit tests
 1 <a href="https://github.com/RobotLocomotion/drake/issues/466">known
issue #466</a>: implement Jdot*v for drakeFunction.kinematic methods
 1 <a href="https://github.com/RobotLocomotion/drake/issues/822">known
issue #822</a>: testURDF fails now that it is parsing every urdf in drake
 1 unknown

RigidBodyManipulatorMemoryTest (timed out)

solvers/test/testMixedIntegerConvexDemo (unknown issue)

```
error_id = Drake:ValueCheck
error_message = Values don't match.  Expected 
[0.299380471012598;0.798296858067338]
but got 
[0.299380547462255;0.798296582957981]
is_segfault = 0
```

``` Matlab

                           < M A T L A B (R) >
                 Copyright 1984-2014 The MathWorks, Inc.
                   R2014a (8.3.0.532) 64-bit (glnxa64)
                            February 11, 2014


To get started, type one of these: helpwin, helpdesk, or demo.
For product information, visit www.mathworks.com.

To reproduce this test use rng(575029040,'twister')

[Warning: Disabling autosave for simulink blocks (to avoid generating a
lot of
*.mdl.autosave files in your directory.  If you aren't a regular Simulink
user
and don't want this disabled, comment out this section in addpath_drake.
To disable this warning in the future, add
  warning('off','Drake:DisablingSimulinkAutosave')
to your matlab startup.m] 
[> In addpath_drake at 74
 In addpath_drake at 4] 
Calling addpath_yalmip
Calling addpath_gurobi
symbolic problem overhead: 4.188667s

xstar =

   0.2994
   0.7983

non-symbolic problem overhead: 0.031347s

xstar_non_symb =

   0.2994
   0.7983

Error using valuecheck (line 78)
Values don't match.  Expected 
[0.299380471012598;0.798296858067338]
but got 
[0.299380547462255;0.798296582957981]

Error in testMixedIntegerConvexDemo (line 100)
valuecheck(xstar_non_symb, xstar);

Error in fevalPackageSafe (line 21)
 feval(f);


<test_name>solvers/test/testMixedIntegerConvexDemo</test_name>
<error_id>Drake:ValueCheck</error_id> <error_message>Values don't match. 
Expected 
[0.299380471012598;0.798296858067338]
but got 
[0.299380547462255;0.798296582957981]</error_message> 


```

<matlab_test>strcmp(test_name,'solvers/test/testMixedIntegerConvexDemo') && strcmp(error_id,'Drake:ValueCheck')</matlab_test>

**Comment by jwnimmer-tri** [comment]
Closing as won't-fix, because #6369 will be removing the relevant software.

If I'm confused and this should in fact stay open, please re-open an clarify the remaining unsolved problem(s) in a new comment here.
