### ISSUE TITLE
kcov-34 missing copyright file

### ISSUE THREAD

**Issue by jwnimmer-tri** [RobotLocomotion/drake#8326]
Drake's `kcov-34_34-1_amd64.deb` has only these files:
```
 -rwxr-xr-x    root/root    1388432 ./opt/kcov/34/bin/kcov
 -rwxr-xr-x    root/root     191792 ./opt/kcov/34/bin/kcov-system-daemon
 -rw-r--r--    root/root       7232 ./opt/kcov/34/share/man/man1/kcov.1
```
I think at least we need `doc/copyright` in some form to meet upstream's license obligations.

**Comment by jamiesnape** [comment]
Technically upstream’s defect since they provided the packaging recipe, but I will patch it next week.
