### ISSUE TITLE
windows build servers print " mp" instead of "tmp" for some reason

### ISSUE THREAD

**Issue by rdeits** [RobotLocomotion/drake#835]
If you look at the folder name given by the windows build servers, they always replace the `t` in `tmp` with a space. For example: 

```
Build Server Directory: C:\cygwin\ mp\drake-precompiled-25558
```

which can be seen in this comment: https://github.com/RobotLocomotion/drake/pull/829#issuecomment-77742166

**Comment by RussTedrake** [comment]
that's known, but i didn't consider it a high priority.  :)

**Comment by rdeits** [comment]
Haha, alright.

**Comment by RussTedrake** [comment]
btw - fixed it anyways.
