### ISSUE TITLE
c++ QP controller should use eigen sparse matrices

### ISSUE THREAD

**Issue by rdeits** [RobotLocomotion/drake#836]
See: https://github.com/RobotLocomotion/drake/pull/829#discussion-diff-26008724

**Comment by rdeits** [comment]
@RussTedrake you can assign this to me, but I think it's low-priority

**Comment by RussTedrake** [comment]
assigned. (the github issue viewer app i'm trying has this marked as "unanswered by me" :)

**Comment by RussTedrake** [comment]
related to #6381.  with that link established, I will close this one.
