### ISSUE TITLE
cps file for dreal

### ISSUE THREAD

**Issue by soonho-tri** [RobotLocomotion/drake#8393]
from slack discussion with @jamiesnape

**Comment by jwnimmer-tri** [comment]
@soonho-tri Is this still important?  If so, can you please elaborate on the specifics of the feature request, and why it matters?

**Comment by jamiesnape** [comment]
Do we still use dreal in public headers? If so, it is important, since people using the CMake build will have failures if they include such headers, if not it can be closed.

**Comment by jwnimmer-tri** [comment]
As of #11940 we no longer include `<dreal/dreal.h>` publicly.
