### ISSUE TITLE
Ensure testing utilities have negative tests where applicable

### ISSUE THREAD

**Issue by EricCousineau-TRI** [RobotLocomotion/drake#8403]
As a followup from [this comment](https://github.com/robotlocomotion/drake/pull/8396#issuecomment-374305915) in #8396, it'd be useful to have negative tests for testing utilities that do not yet have them.

This link provides some information on how to test these:
https://github.com/google/googletest/blob/master/googletest/docs/AdvancedGuide.md#catching-failures

\cc @sherm1

**Comment by jwnimmer-tri** [comment]
I'll propose that we close this under the umbrella of "fix it only when it hurts".  If we find a bug in a test_utilities, we can add a regression test for it then.  I'm not sure we need to go hunt down and test the tests now, nevermind have a reminder issue for it.

**Comment by EricCousineau-TRI** [comment]
Agreed, closing.
