### ISSUE TITLE
Remove explicit bool conversion from symbolic::Formula

### ISSUE THREAD

**Issue by soonho-tri** [RobotLocomotion/drake#8417]
https://github.com/RobotLocomotion/drake/issues/8362#issuecomment-374965944

https://github.com/RobotLocomotion/drake/blob/a692ae5a05cc00d865502c326ffa5b2dc27927a9/common/symbolic_formula.h#L189-L190

It was introduced as a workaround to make Drake code compatible with Eigen. I'll check if we still need this and remove it if it's not necessary.

**Comment by jwnimmer-tri** [comment]
Actually, I think we should _keep_ that conversion intact?  The new boolish stuff from the past month or two requires it?

**Comment by soonho-tri** [comment]
@jwnimmer-tri , not sure we need this conversion because of the drake bool. But I found cases where we need it because of Eigen. One example that I get when I remove this conversion:

```
external/eigen/Eigen/src/Core/GeneralProduct.h:250:55: error: invalid operands to binary expression ('bool' and 'drake::symbolic::Formula')
      const bool alphaIsCompatible = (!ComplexByReal) || (numext::imag(actualAlpha)==RealScalar(0));
                                     ~~~~~~~~~~~~~~~~ ^  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by soonho-tri** [comment]
@jwnimmer-tri , I think we agree that we can close this one. What do you think?
