### ISSUE TITLE
Install on Arch linux

### ISSUE THREAD

**Issue by CatchMeFastFat** [RobotLocomotion/drake#8467]
Should I switch to ubuntu or use docker to get drake?
I have tried to build it, but bazel gives :
{could not determine Linux distribution: unsupported distribution 'Arch Linux' and referenced by '//tools/workspace:install_external_packages'} 

"I think that would be duplicate, but search doesn't help me"
Thanks

**Comment by jwnimmer-tri** [comment]
The supported configurations are shown at http://drake.mit.edu/developers.html#supported-configurations.  Also http://drake.mit.edu/docker.html is option.
