### ISSUE TITLE
eval() and fasteval() treat t as 0 if it's a Matlab `single`

### ISSUE THREAD

**Issue by rdeits** [RobotLocomotion/drake#848]
try it:

```
K>> traj = PPTrajectory(foh([0, 1], [0, 1]));

K>> traj.eval(0.5)        

ans =

    0.5000

K>> traj.eval(single(0.5))

ans =

  5.2221e-315

K>> traj.eval(double(single(0.5)))

ans =

    0.5000
```

This is made much worse by the fact that `single` + `double` = `single` for some crazy reason, so having one `single` around will break all sorts of things in silent and scary ways. We end up with `single`s when we load LCM types with `float`s.

**Comment by rdeits** [comment]
I think the reason this happens is that PPTmex does the following:

```
double *t = mxGetPr(prhs[2]);
```

but if prhs[2] isn't a Matlab `double`, then all sorts of stupid bad stuff can happen (like your `single` becoming a `double` which is very very close to 0). Replacing that with:

```
double t = mxGetScalar(prhs[2]);
```

seems to fix the problem. Is that the right solution?

**Comment by RussTedrake** [comment]
Wow.  Yikes.  Good catch!

- Russ

**Comment by RussTedrake** [comment]
Yes, looks like that will do the conversion as necessary.  http://www.mathworks.com/help/matlab/apiref/mxgetscalar.html

Arrays will be harder.  Is there a good way to watch/check for this happening in other places?

- Russ

**Comment by rdeits** [comment]
We could write a `myGetPr` which checks `mxIsDouble` before assigning the pointer and throws an error otherwise

**Comment by RussTedrake** [comment]
It’s a good idea.  I might call it mxGetPrSafe (or getPrSafe) and would put it in drakeUtil.cpp

**Comment by rdeits** [comment]
Ah, I was trying to keep the analogy we have in controlUtil with `myGetField` (which is a safer version of `mxGetField`) and `myGetProperty` vs. `mxGetProperty`. Should we try to keep a consistent scheme for these utils:

**Comment by RussTedrake** [comment]
Definitely yes to being consistent.  I know controlutil was different and would love to make everything agree.  I'm not wed to either naming convention.

- Russ
