### ISSUE TITLE
Use_new_kinsol fails with cables

### ISSUE THREAD

**Issue by psiorx** [RobotLocomotion/drake#851]
Any manipulator containing cables will fail to resolve constraints in the initial state if it is set to use_new_kinsol.

Reproduce using:
RigidBodyManipulator('examples/SimplePulleys/simple_pulley.urdf', struct('use_new_kinsol', true)).getInitialState

The urdf above can be replaced with any such urdf that has cables(soft_hand.urdf, tension.urdf, robotiq_tendons.urdf, etc) with the same result.

**Comment by tkoolen** [comment]
I can no longer reproduce this using the code above. Can you verify that this is fixed?
BTW, please @mention me in anything related to kinematics/dynamics :-)

**Comment by psiorx** [comment]
I can confirm this is fixed, now.  Will do.
