### ISSUE TITLE
pydrake.symbolic.Formula and returns unexpected results

### ISSUE THREAD

**Issue by RussTedrake** [RobotLocomotion/drake#8536]
From underactuated piazza

``
mp = MathematicalProgram()
x = mp.NewContinuousVariables(1, 'x')
mp.AddLinearCost(x[0])
mp.AddLinearConstraint(-1 <= x[0] <= 1)
mp.Solve()
print mp.GetSolution(x)
```

This prints -6.17673396e+14 instead of printing -1 or throwing an exception. I understand that python doesn't allow you to override and, so AddLinearConstraint can only see one of the subexpressions (rhs if lhs is truthy, lhs if it isn't). But is there any reason why `pydrake._symbolic_py.Formula.__nonzero__` doesn't throw an exception?

**Comment by soonho-tri** [comment]
I think #8500 resolves this issue as well. I'll check and add this as a test.

/cc @EricCousineau-TRI

**Comment by EricCousineau-TRI** [comment]
Went ahead and added it in as a two-liner to #8500. Thanks!
