### ISSUE TITLE
Remove `@numpy` repository

### ISSUE THREAD

**Issue by EricCousineau-TRI** [RobotLocomotion/drake#8544]
From what I understand, `pybind11` does not need `numpy` headers as it a separate ABI (not through `ld.so`), which effectively "links" the functions via dictionaries in Python that store the relevant pointers in capsules, and locks constants by an API guarantee in the documentation.

Because of this, we don't really need `@numpy` as a C++ dependency; it's existence is effectively guaranteed by `install_prereqs.sh`.

@rdeits Can I ask if there was any reason in particular for keeping these headers around? Since @m-chaturvedi submitted an updated patch which uses the above ABI style, it shouldn't be needed for `dtype=object` stuff.

**Comment by rdeits** [comment]
Nope, no reason I'm aware of.

**Comment by jamiesnape** [comment]
> Because of this, we don't really need @numpy as a C++ dependency; it's existence is effectively guaranteed by install_prereqs.sh.

We should not be using `install_prereqs.sh` to guarantee anything. Presumably we will have failing tests in Drake, which is the guarantee.
