### ISSUE TITLE
Add lock and retry logic to license acquisition in GurobiSolver

### ISSUE THREAD

**Issue by jamiesnape** [RobotLocomotion/drake#8563]
Since it is common for the license to be obtained from a license server over a network, it is perfectly possible that license acquisition will fail on occasion.

**Comment by jamiesnape** [comment]
Interim solution to license server flakiness is to add the flag `--flaky_test_attempts=3` build option on CI for "everything" builds.

**Comment by mpetersen94** [comment]
Additionally, every time the GurobiSolver is used to solve a mathematical program, a message is printed if using a Gurobi academic license.  If the GRBenv (or whatever is causing the re-printing) could be saved to limit the number of messages to 1 that would be very helpful (something similar to `MosekSolver::AcquireLicense`).
