### ISSUE TITLE
sphinx docs talk about clang-format-4.0, but install_prereqs on a fresh mac gave me clang-format (7.0)

### ISSUE THREAD

**Issue by RussTedrake** [RobotLocomotion/drake#8571]
```
mbp:lib RT$ clang-format --version
clang-format version 7.0.0 (tags/google/stable/2018-01-11)
```

this includes (starts from) the clion setup instructions.

**Comment by jamiesnape** [comment]
Half the docs we have are written from an (almost) exclusively Ubuntu perspective. We definitely need a cleanup. It is not just this.

**Comment by jwnimmer-tri** [comment]
Since I've recently introduced linter rules for clang-format idempotence (in bindings), I'll at least get the instructions related to clang-format up to snuff again.
