### ISSUE TITLE
Warning spew from RigidBodyManipulator.cpp

### ISSUE THREAD

**Issue by avalenzu** [RobotLocomotion/drake#858]
Constructing an RBM in C++ for a model with joint dynamics now results in a long stream of:

```
Warning: joint dynamics xml tag not (re-)implemented yet; they will be ignored.
```

This makes the user far more likely to ignore the printouts and could cause more serious warnings to be ignored. I'd suggest adding "warn once" logic like we used to have for meshes that used the "package://" syntax.

**Comment by RussTedrake** [comment]
sounds good.  can you knock that out?

**Comment by avalenzu** [comment]
Will do.
