### ISSUE TITLE
contactConstraintsBV.m assumes mu=1, while the c++ version does not

### ISSUE THREAD

**Issue by rdeits** [RobotLocomotion/drake#860]
This means that we can't do `use_mex=2` tests of the controllers without assuming mu=1.

**Comment by RussTedrake** [comment]
in addition to improving the support for friction (eg #57) and making sure we can pass it through these interfaces, it seems like we should be close to zapping the matlab version of the controller.  agree?

**Comment by RussTedrake** [comment]
just found #1317, so clearly you agree about zapping the matlab version.  resolving this as "won't fix"
