### ISSUE TITLE
Documentation for how to write a leaf system

### ISSUE THREAD

**Issue by jwnimmer-tri** [RobotLocomotion/drake#8616]
We should add documentation for how to write a leaf system, for example including a decision tree about the system model you are choosing, whether / how to do symbolic and autodiff, abstract vs numeric state, whether to use LeafSystem or VectorSystem etc.  We have various examples of varying quality, but no tutorial that stitches them together.

Relates #7560.

**Comment by ManuelAhumada-TRI** [comment]
Sure thing! I'd be in to test it (i.e. guinea pig).

**Comment by edrumwri** [comment]
One piece of information to be attached to this issue: we need documentation for declaring events and writing event handlers for LeafSystem authors.

**Comment by jwnimmer-tri** [comment]
Fixed as of the `authoring_leaf_systems.ipynb` tutorial.
