### ISSUE TITLE
contactConstraintsmex fails with use_new_kinsol = true

### ISSUE THREAD

**Issue by psiorx** [RobotLocomotion/drake#863]
This breaks because the current implementation calls RigidBodyManipulator::forwardJac to compute dphi/dq.  The best solution is probably to route calls to forwardJac and forwarddJac through forwardKinNew with the appropriate gradient_order if called with use_new_kinsol

I'm planning to push the fix for this on my setupLCPmex branch.

**Comment by tkoolen** [comment]
This was fixed in #891, correct?

**Comment by psiorx** [comment]
Yes.
