### ISSUE TITLE
Add range-limited separation distance query to GeometrySystem

### ISSUE THREAD

**Issue by avalenzu** [RobotLocomotion/drake#8631]
It would be great to be able to get the signed distance for all pairs of geometries which are closer than some (positive) threshold, but the full N^2 results would be an acceptable start (that's what we have now from `BulletModel`.

**Comment by SeanCurtis-TRI** [comment]
Signed distance queries were added in #8896. These are the O(N²) queries.

Title of issue updated to reflect the range-limited variation of the query.
