### ISSUE TITLE
Performance impact on Systems framework, possibly from #8420

### ISSUE THREAD

**Issue by EricCousineau-TRI** [RobotLocomotion/drake#8636]
Possibly triggered by #8420

Slack transcript from 2018-04-18:

> eric.cousineau [11:43 AM]
> ![image](https://user-images.githubusercontent.com/26719449/39005384-17d47340-43ce-11e8-94a5-560aa5b67fa4.png)
> 
> alejandro sherm1 It seems that `spring_mass_system_test` had an almost double in test time within the past week:
> 
> sherm1 [11:43 AM]
> joined #buildcop by invitation from eric.cousineau.
> 
> eric.cousineau [11:44 AM]
> Can I ask if y'all might now what the source of this slowdown?
> (Andres is submitting a temp fix to bump the test timeout.)
> 
> Source of the graph: https://drake-cdash.csail.mit.edu/testDetails.php?test=19135208&build=986422 (edited)
> 
> sherm1 [12:28 PM]
> I'm not seeing any recent changes to that test case. It's also not obvious what other changes might have affected it. Does it slow down only in Debug builds? I'm wondering if we might have added some expensive Debug validity checks somewhere.
> 
> sherm1 [12:38 PM]
> BTW I ran this test in Debug on my laptop and the total run time was 11s. Is it plausible that valgrind bumps that to 600s?
> 
> jamiesnape [12:42 PM]
> We had a test with 1000x slowdown earlier.
> 
> rpoyner-tri [12:43 PM]
> valgrind can interact badly with things like Eigen -- not sure why. perhaps the emulations for certain operations are particularly slow? (edited)
> 
> eric.cousineau [1:30 PM]
> Valgrind definitely slows down a ton; at least my takeaway from the above graph is that it is consistently slower post-April 12, which seems to indicate that either (a) the load on the CI machines has been consistently higher (hard to confirm, and doubtful) or (b) there has been code introduced recently that slows down at least valgrind.
> 
> Will briefly check the other non-valgrind builds to see if there is a similar slowdown that can be observed.
> 
> jamiesnape [1:34 PM]
> Load on the CI machines is always the same on Linux. There are no shared resources.
> 
> eric.cousineau [1:43 PM]
> ![image](https://user-images.githubusercontent.com/26719449/39005366-050e7882-43ce-11e8-8ae5-44dba93866b9.png)
> Confirmed that non-`valgrind` builds have a similar relative trend:
> https://drake-cdash.csail.mit.edu/testDetails.php?test=18718982&build=986351
> 
> eric.cousineau [1:44 PM]
> The above is `debug` only, no valgrind. TEst time went from ~5s on Apr 10 to ~7-8s.
> 
> I don't think there's anything actionable for now, but just a heads up
> sherm1 alejandro
> 
> jwnimmer-tri [1:44 PM]
> Such a bright-line difference should be *trivial* to automatically bisect locally.
> 
> eric.cousineau [3:05 PM]
> True; was able to find what I believe to be the offending commit, `0fc114b`, part of merge commit `2b275fc6d`, which was introduced via sherm1's #8420. (Process will be posted as a comment in this thread.)
> 
> Sherm, do you want me to open an issue to track this? (edited)
> sherm1 [12:30 PM]
> Oh, neat -- thanks for tracking that down. That PR certainly did add some extra work cloning
> contexts, but should only affect overhead and not simulation run times. Possibly spring-mass
> is largely overhead because it is so small, but it would be good to verify that. If you wouldn't
> mind filing an issue containing your discovery and instructions and assigning to me, that 
> would be great. Thanks, @eric.cousineau!
> 
> Test script is:
> `bazel test --nocache_test_results //systems/plants/spring_mass_system:spring_mass_system_test --test_summary=short`
> 
> On my system, before Apr. 10, the runtime was 0.5s; on master, the runtime was 0.7-0.8s (about the same ratios as before).
> 
> Process for bisecting (`HEAD = master = 7f57930`)
> ```
> git bisect start
> git bisect bad HEAD
> git bisect good a4f42385
> # Run the above script; could have made a script before `git bisect run`, but was too lazy.
> ```

**Comment by sherm1** [comment]
This isn't actionable now. We're profiling and fixing things as they come up.
