### ISSUE TITLE
Add tests for openness of framework scalar types

### ISSUE THREAD

**Issue by jwnimmer-tri** [RobotLocomotion/drake#8640]
Right now, the `//systems/framework` notionally supports user-defined scalar types, because we (try to) place all of the code in header files templated on `T`.  However, in practice possibly we have made mistakes and do not in fact support user-defined scalars.  We should add unit test(s) that prove the framework works with non-default scalars.

(Alternatively, we could give up and just lock down the scalars to those we care about, but that would be a separate discussion.)

Relates #6691 and #3741 as this also touches on code organization and compile times and etc.

\CC @sherm1

**Comment by sherm1** [comment]
A few thoughts: 
- This seems reasonable and gets less painful as we move more functionality up into the type-agnostic SystemBase and ContextBase classes.
- In numerical code, supporting `float` correctly requires a lot more than just changing the scalar type. In practice, it is also very difficult to get `float` code to run faster than `double`. IIRC, we agreed long ago that we only support double precision in Drake. Using `float` to check for user-scalar health is fine, but we should be careful to avoid leaving the impression that anything good will happen using `float` as the scalar type.
- A really nice additional scalar type we _could_ support is `adouble` from the [ADOL-C project](https://projects.coin-or.org/ADOL-C). This is a _much_ more sophisticated autodifferentiation approach than Eigen's AutoDiff, and is compatible with Eigen (it's an [Eigen example](https://eigen.tuxfamily.org/dox/TopicCustomizing_CustomScalar.html) of custom scalar types here). adouble has more in common with our Expression type than with AutoDiffScalar, with similar limitations.
