### ISSUE TITLE
DRAKE_EXPECT_THROWS_MESSAGE() should continue if wrong exception type thrown

### ISSUE THREAD

**Issue by sherm1** [RobotLocomotion/drake#8657]
This macro would be more useful if it would behave like EXPECT_THROW(), which continues on if the wrong exception gets thrown, with a message like:
```
Expected: system.AllocateContext() throws an exception of type std::runtime_error.
  Actual: it throws a different type.
```
Currently DRAKE_EXPECT_THROWS_MESSAGE() kills the executing test if the wrong exception is thrown.

DRAKE_ASSERT_THROWS_MESSAGE(), OTOH, should still treat this as a test-ending fatality.

(From PR #8649 comment thread [here](https://beta.reviewable.io/reviews/robotlocomotion/drake/8649#-LAZcbAr8N5eMx1SUUMM))

Also, this and related macros need unit tests, see #8403.

**Comment by SeanCurtis-TRI** [comment]
I came across this myself -- put a small solution together. I'll PR it.

Note for the future: when we get C++17 we can take it a step further and in case where the wrong exception type is thrown, we can say *what* the wrong exception was. Doing that under C++14 is technically possible but a real pain in the tuckus.
