### ISSUE TITLE
bad mercurial dependency in install_prereqs.sh 

### ISSUE THREAD

**Issue by RussTedrake** [RobotLocomotion/drake#8672]
This morning I saw this:
```
+ source /Users/russt/drake/setup/mac/binary_distribution/install_prereqs.sh
++ set -euxo pipefail
++ [[ 501 -eq 0 ]]
++ command -v brew
++ brew update
Already up-to-date.
++ brew bundle --file=/Users/russt/drake/setup/mac/binary_distribution/Brewfile
Using caskroom/versions
Using dreal/dreal
Using robotlocomotion/director
Error: No such file or directory - /usr/local/opt/mercurial/bin/hg
```

mercurial was already installed, but `brew upgrade mercurial` resolved it.  Not sure if that's our issue or homebrew's, but wanted to report it.

**Comment by RussTedrake** [comment]
nope.  a macbook pro that I hadn't used in a few weeks.

**Comment by jamiesnape** [comment]
It is certainly a Homebrew problem since we do not require `mercurial`, I just have not isolated the particular commit. They had a similar problem once before, https://github.com/Homebrew/brew/issues/1372, so may be related somehow to how bottles are installed.

**Comment by RussTedrake** [comment]
ok.  I'm happy to have the record here, but consider it "not our problem".
