### ISSUE TITLE
Update QuadrotorPlant with new rotation matrix tools.  

### ISSUE THREAD

**Issue by RussTedrake** [RobotLocomotion/drake#8681]
The rotation/frame-related operations in the current quadrotor example could use a serious cleanup:
https://github.com/RobotLocomotion/drake/blob/master/examples/quadrotor/quadrotor_plant.cc#L95

Would be great to see them use the new rotation library.

**Comment by mitiguy** [comment]
This has been cleaned up through a series of PRs, namely:
8778, 8818, 8822, 8829, 8875.
