### ISSUE TITLE
Consider removing CROSSTOOL, pass required flags via `bazel.rc` if possible?

### ISSUE THREAD

**Issue by EricCousineau-TRI** [RobotLocomotion/drake#8684]
(Per conversations with @jamiesnape - just transcribing what I remember, but will definitely accept corrections to my understanding!)

Jamie has mentioned that our usage of `CROSSTOOL` could possibly be replaced by updating our `bazel.rc` flags. This could possibly help to better address issues like #7835, cache invalidation, etc. Additionally, the `CROSSTOOL` format seems like a moving target, frequently changes with Bazel releases, and the only documentation for this feature appears to be some `bazelbuild/bazel` Wiki entries.

Given that we're not doing any insane cross-compilation, we could possibly do away with it?

@jamiesnape Can I ask if this accurately describes what we have discussed? (And sorry for the delay in posting this!)

\cc @jwnimmer-tri

**Comment by jamiesnape** [comment]
> Additionally, the CROSSTOOL format seems like a moving target, frequently changes with Bazel releases, and the only documentation for this feature appears to be some bazelbuild/bazel Wiki entries

They are in process of completely changing the process, so they is actually no documentation at all currently. I spent a fun few weeks reading source code and have a pretty good understanding, but it is a lot of code to maintain and verify against each Bazel release (the current Ubuntu CROSSTOOL that we use is legacy, so will stop working eventually).

> @jamiesnape Can I ask if this accurately describes what we have discussed? (And sorry for the delay in posting this!)

Basically, yes.

**Comment by jamiesnape** [comment]
Bazel 0.14.0 has a set of constraints for compiler family, which will solve any issues with warning flags if they were actually implemented (correctly).
