### ISSUE TITLE
Atlas's feet slide when in contact if enable_fastqp is true

### ISSUE THREAD

**Issue by rdeits** [RobotLocomotion/drake#869]
When walking in sim, I've noticed Atlas's feet frequently sliding, especially at the beginning of a walking plan. This seems to go away if enable_fastqp is set to false in the TSRBM constructor. 

@kuindersma says he's going to look into this.

**Comment by kuindersma** [comment]
If you run atlasWalking in master with enable_fastqp = false in TSRBM, the foot sliding persists. It definitely seems like a solveLCP bug has crept in. @psiorx are you still hacking on this function? If so, do you want to look at this?

**Comment by psiorx** [comment]
I'll take a look.
