### ISSUE TITLE
sphinx docs need a more visible pointer to drake-external-examples

### ISSUE THREAD

**Issue by RussTedrake** [RobotLocomotion/drake#8711]
I think it's time to incorporate ~shambhala~ drake-external-examples more fully into the drake documentation.   Probably also a visible pointer to http://underactuated.mit.edu as a source of many more examples in the same location?

Perhaps right on the installation and distribution page?

Motivated by answering a lot of questions like this:
https://stackoverflow.com/questions/50060927/how-to-use-robotlocomotion-drake-codes-in-my-project-for-example-qp-inverse/50075307#50075307

**Comment by jwnimmer-tri** [comment]
SGTM.

Possibly in concert with a Shambhala top-level README.md addition that says something like:

_This repository shows you how to use Drake from your own project.  Choose one of the three subdirectories named `drake_*` as your guide, depending on which mechanism is most suitable for you._

as a first-paragraph introduction, relegating the metaphysics to a "Where does the name Shamhala  come from?" footnote instead of the first thing a user sees.

**Comment by jamiesnape** [comment]
> as a first-paragraph introduction, relegating the metaphysics to a "Where does the name Shamhala come from?" footnote instead of the first thing a user sees.

I would be more controversial and say that we should give the repo a more descriptive (and less exciting name) than "drake-shambhala". Same for the ROS examples repo beginning with "k" (whose full name that I cannot remember offhand) should it ever graduate to RobotLocomotion.

**Comment by RussTedrake** [comment]
Want to re-assert the importance of this.  

Proposal:
drake-shambhala => drake-as-external ?  drake-external-project ?  drake-as-a-library ?  drake-in-your-project ? 

https://github.com/naveenoid/kumonoito => RobotLocomotion/drake-ros ?

**Comment by EricCousineau-TRI** [comment]
@jamiesnape Given that you've merged this in, how hard would it be to resolve this?

Perhaps we can consolidate these references to just point to them on the front page?

**Comment by jamiesnape** [comment]
Merged what? Resolve what? To what this issue is pertaining seems to be different in almost every comment.

**Comment by EricCousineau-TRI** [comment]
Sorry, meant the rename. Updated comment.

**Comment by RussTedrake** [comment]
Ping on this.  Can we resolve it?

**Comment by EricCousineau-TRI** [comment]
This can be done in or after #10963.
