### ISSUE TITLE
AddSystem template overloading ambiguity

### ISSUE THREAD

**Issue by stonier** [RobotLocomotion/drake#8714]
Wondering if 

```
template<template<typename Scalar> class S, typename... Args>
S<T>* AddSystem(Args&&... args)
```
should be redefined as:
```
template<typename Scalar, template<typename Scalar> class S, typename... Args>
S<T>* AddSystem(Args&&... args)
```
to avoid ambiguity with 
```
template<class S, typename... Args>
S* AddSystem(Args&&... args)
```
when called with template arguments for which `Scalar` is the same as `T`. e.g. 
```
drake::systems::DiagramBuilder<double>* builder;
// ...
// ambiguity...
drake::automotive::MobilPlanner<double>* planner =
  builder->template AddSystem<drake::automotive::MobilPlanner<double>>(....)
```

**Comment by EricCousineau-TRI** [comment]
Seems like an odd case of ambiguity, as `MobilPlanner<double>` is a class (which should bind to the former) while `MobilePlanner` is a `template <typename Scalar> class` (which should bind to the latter).

Which compiler are you using? Does this happen for both `gcc` and `clang`? (if it's for one, not the other, seems like a compiler bug?)

**Comment by jwnimmer-tri** [comment]
Absent any additional info, we will close for now.  If it comes up again with more info, we can repair it then.
