### ISSUE TITLE
Block network connections for unit tests by default?

### ISSUE THREAD

**Issue by jamiesnape** [RobotLocomotion/drake#8717]
Obviously we would need to open up connections to license servers, but feels like we should make use of the Bazel functionality and declare when we need a network connection, which would also help identify possible sources of flakiness.

**Comment by jwnimmer-tri** [comment]
I tried this briefly in Anzu and gave up.  My recollection is that the `block-network` tag makes the `socket()` syscall fail, even if the use was spurious, or even if the only subsequent use was going to be to listen on loopback for a connection that never comes, etc.  My appraisal was that we'd need to whitelist a lot of tests, to the point where it wasn't going to add net value.  The tag doesn't block network _connections_, it blocks _ever calling any networking-related APIs_.

**Comment by jamiesnape** [comment]
Let's close then.
