### ISSUE TITLE
Investigate a failure on mac machine with rotation constraint

### ISSUE THREAD

**Issue by hongkai-dai** [RobotLocomotion/drake#8719]
In https://github.com/robotlocomotion/drake/blob/cc8ca9df00e49dd79616e4d7d1be052863732a18/solvers/rotation_constraint.cc#L459 I tried to add a "polishing" step on the Mosek optimization result, as
```C++
  // The optimization problem might not be solved to super high precision. To
  // guarantee that the constraints d <= nᵀ * pts.col(i), nᵀ * n = 1 are
  // satisfied, we "polish" the optimization solution below.
  n->normalize();
  *d = std::numeric_limits<double>::infinity();
  for (const auto& pt : pts) {
    *d = std::min(*d, n->dot(pt));
  }
```
But then using this polished result, Gurobi 7.5 fails to find a solution on Mac machine. I should have investigated why Gurobi fails.

**Comment by jwnimmer-tri** [comment]
Given 5+ years passed, and a few Gurobi upgrades, perhaps this is no longer worth tracking?  We could close as "won't fix".

**Comment by hongkai-dai** [comment]
We can close this issue.
