### ISSUE TITLE
URDFRigidBodyManipulator.h missing?

### ISSUE THREAD

**Issue by steinachim** [RobotLocomotion/drake#872]
Hi,

I noticed there were some nice C++ additions to the code base and tried to compile and run the test-cases (e.g. built from `systems/plants/test/testIKtraj.cpp`). But when I try to compile them, I get a bunch of "file missing" errors:
```drake-distro/drake/systems/plants/test/testIK.cpp:4:38: fatal error: URDFRigidBodyManipulator.h: No such file or directory?```

I checked and didn't find the file in the repos either. Is this some oversight or is there another reason that the file was removed?

Best,
Achim

**Comment by avalenzu** [comment]
URDFRigidBodyManipulator was removed because the functionality it provided
has been incorporated into the main RigidBodyManipulator C++ class. You've
found some tests we forgot to update. Thanks!
