### ISSUE TITLE
Unsmooth lane transitions due to PurePursuit myopia

### ISSUE THREAD

**Issue by jadecastro** [RobotLocomotion/drake#8735]
This is a known issue that arises because PurePursuit's look-ahead point is constrained to the current lane only. Now that interesting multi-segment roads are coming to life, we need to revisit this issue.

**Comment by jwnimmer-tri** [comment]
Per #11603, the automotive folder is deprecated, so I'll close this issue as "won't fix"; @jadecastro if this issue is still important to you, please re-open it in a different issue tracker.

\CC @liangfok FYI
