### ISSUE TITLE
MBP Supports scalar conversion for systems that inherit from it

### ISSUE THREAD

**Issue by amcastro-tri** [RobotLocomotion/drake#8739]
MBP is not marked final. However, in order to support scalar conversion, it should provide a `protected: ` constructor as [documented here](http://drake.mit.edu/doxygen_cxx/group__system__scalar__conversion.html)

**Comment by jwnimmer-tri** [comment]
Per #10310, we agree that MBP should be final.  This issue is WONTFIX.
