### ISSUE TITLE
Support type-erased pixel type in `Image<>`

### ISSUE THREAD

**Issue by EricCousineau-TRI** [RobotLocomotion/drake#8750]
It'd be convenient for writing API's if there were a type-erased version of `Image<>` (akin to `cv::Mat` and what not), which could simply support a closed set (or open set, if we're feeling up to it) of image types, perhaps defining a flag type `PixelType { ... kDynamic }`, use either virtual dispatch or some C++14 variant of `std::any`, and do some API trickery to make it appear similar.

\cc @siyuanfeng-tri @kunimatsu-tri 

EDIT: Another simpler option is just to make all image types extend from some `ImageBase`, and do whatever type-erasing from the base to enable templated accessors. (Slight cost with virtual dispatch, but I don't think that'd be too much of an issue.)

**Comment by hongkai-dai** [comment]
@EricCousineau-TRI is this feature still needed?

**Comment by EricCousineau-TRI** [comment]
I would like to keep it open, yes.

**Comment by jwnimmer-tri** [comment]
Would adding this typedef to Drake be sufficient to close the issue?

```c++
using ImageVariant = std::variant<ImageBgr8U, ImageBgra8U, ImageDepth16U,
                                  ImageDepth32F, ImageExpr, ImageGrey8U,
                                  ImageLabel16I, ImageRgb8U, ImageRgba8U>;
```

**Comment by jwnimmer-tri** [comment]
We have `using ImageAny = std::variant<...>` now.  That might solve the problem.

Since we lack a clearly-articulated use case for something more complicated, we'll close this as "not planned".
