### ISSUE TITLE
Compiler warning regarding literal operator suffixes not preceded by '_' being reserved

### ISSUE THREAD

**Issue by liangfok** [RobotLocomotion/drake#8751]
Post 864bcd125e6b5374d9170d687c5be59c243072dd, I'm seeing the following compiler warning:

```
external/drake/systems/framework/system_base.cc: In member function 'virtual std::__cxx11::string drake::systems::SystemBase::GetSystemPathname() const':
external/drake/systems/framework/system_base.cc:20:39: warning: literal operator suffixes not preceded by '_' are reserved for future standardization
   using std::string_literals::operator""s;
```
Can this warning be addressed or suppressed?

**Comment by sherm1** [comment]
Oh, that's absurd -- that operator is from the C++ standard and provided in the library! I guess they expect us to include the whole namespace `std::string_literals` (not permitted by our standards guide) and never tried mentioning one of the built-in operators by name :(. I'll fix it.
