### ISSUE TITLE
`//bindings/pydrake:py/math_test` fails as a timeout frequently CI

### ISSUE THREAD

**Issue by EricCousineau-TRI** [RobotLocomotion/drake#8752]
@hongkai-dai noted that `:math_test` has been failing frequently in CI (for the past week or so).
Looking at the timing for the test, the trend seems rather sporadic: https://drake-cdash.csail.mit.edu/testDetails.php?test=20303158&build=999659
From https://drake-jenkins.csail.mit.edu/job/linux-xenial-clang-bazel-experimental-cache/773/

Since it's been failing more frequently, there may be another contributing factor, but the first easy fix is to disable `matplotlib` on CI to avoid it needing to rebuild its font cache.

**Comment by jwnimmer-tri** [comment]
Also note that #8659 changed test-timeout configurations ~13 days ago, so could be related.
