### ISSUE TITLE
WorldSimTreeBuilder::AddModelInstanceToFrame fails unhelpfully when incorrect model name is given

### ISSUE THREAD

**Issue by avalenzu** [RobotLocomotion/drake#8791]
[Line 99]( https://github.com/RobotLocomotion/drake/blob/485879c9a334ca43509b40e84f305887a19fa01b/manipulation/util/world_sim_tree_builder.cc#L99) reads

```c++
  spruce::path p(model_map_[model_name]);
```
If `model_name` is not present in the map, this silently adds the pair (`model_name`, `""`) to the map, leading to a failure when the extension of the filename is checked. We should check if `model_name` is in the map and give a useful error message.

**Comment by hongkai-dai** [comment]
@avalenzu could you update the status of this issue? Feel free to close or reassign it.

**Comment by avalenzu** [comment]
This is `attic` code. Closing.
