### ISSUE TITLE
RgbdRenderer, RgbdCamera: Expose setting intrinsics matrix; ensure that rendering is accurate to arbitrary intrinsics

### ISSUE THREAD

**Issue by EricCousineau-TRI** [RobotLocomotion/drake#8850]
Per f2f

Steps:
- [x] Expose setting image width and height in `RgbdCamera` (C++ and Python)
- [x] Resolve #8123
- [ ] Set camera intrinsics

\cc @naveenoid @siyuanfeng-tri @kunimatsu-tri

**Comment by kunimatsu-tri** [comment]
The current `RgbdCamera` and/or `RgbdRenderer` APIs are coming from those of VTK where what we can set is `fov_y`, `width` and `height`. There is no way to set `fov_x` and that means we don't have full control for setting both `fx` and `fy` intrinsic parameters independently.

Here is the code where `fov_y` is set:
https://github.com/RobotLocomotion/drake/blob/master/systems/sensors/rgbd_renderer_vtk.cc#L383

@jamiesnape Can you confirm this comment and point out if there is any way to enable us to set all the camera intrinsic parameters using VTK?

**Comment by SeanCurtis-TRI** [comment]
We might consider constructing our own projection matrix and setting the matrix rather than using the syntactic sugar that VTK provides.

**Comment by jamiesnape** [comment]
You beat me to it. I think the method is something like `SetExplicitProjectionTransformMatrix(vtkMatrix4x4)`

**Comment by kunimatsu-tri** [comment]
Great! Then, can we just ignore `SetViewAngle` or do we need some tricks to make it work?

**Comment by jamiesnape** [comment]
You can ignore it, `ComputeProjectionTransform()` is short-circuited before it uses it:

https://github.com/Kitware/VTK/blob/4656844ec61ff83c1438f03c7941126ddc53d8c3/Rendering/Core/vtkCamera.cxx#L1046-L1052

**Comment by kunimatsu-tri** [comment]
Cool. Thanks for the pointer!

**Comment by EricCousineau-TRI** [comment]
Sorry, I'm a little slow on the uptake; just want to confirm some deets / ask some slightly redundant questions about the  coordinates / units:

The documentation for [`GetProjectionTransformMatrix`](https://www.vtk.org/doc/nightly/html/classvtkCamera.html#a4d9a509bf60f1555a70ecdee758c2753) states:

> Return the projection transform matrix, which converts from camera coordinates to viewport coordinates. [...] The viewport coordinates of a point located inside the frustum are in the range ([-1,+1],[-1,+1],[nearz,farz]).

(1)(a) Let's call the camera coordinates `[x, y, z]` and the viewport coordinates `[U, V, W]`, and the projection+transform matrix `PT`; are the relations per the docs simply this?
`[U, V, W; 1] = PT * [x; y; z; 1]`
Or is the an additional scaling term on the left side?

(1)(b) If (1)(a) holds, then the normalized pixel coordinates are simply `u = U / W`, `v = V / W`, right?

(2)(a) It seems that the documentation seems like it *may* be a tad ambiguous, in that it could imply that the frustrum is defined by the above range, but instead should state that the frustrum is a subset of the defined range (e.g. `[-1, 1, farz]` is in the frustrum, but `[-1, 1, nearz]` is not).
Is this the case?

(2)(b) Does this mean that `U, V` are scaled such that, at `farz`, `[-1, 1]` defines the extent of the image? (From looking at `vtkPerspectiveTransform`, seems so?)

**Comment by EricCousineau-TRI** [comment]
Reassigning to @SeanCurtis-TRI per Slack discussion.

**Comment by hongkai-dai** [comment]
@SeanCurtis-TRI could you update the status of this issue? Can we close it?

**Comment by EricCousineau-TRI** [comment]
> Can we close it?

I'd like to keep it open!

**Comment by SeanCurtis-TRI** [comment]
Still an open feature request.

**Comment by EricCousineau-TRI** [comment]
I'd move to close this in lieu of #11880. That cool with you?

**Comment by SeanCurtis-TRI** [comment]
Missed the question. I agree with closing this.
