### ISSUE TITLE
Add "--config everything" to the list of things to check during bazel/CLion updates.

### ISSUE THREAD

**Issue by avalenzu** [RobotLocomotion/drake#8882]

**Comment by jamiesnape** [comment]
Do you have more context/detail?

**Comment by jwnimmer-tri** [comment]
Before I bump Drake's documented/supported version of Bazel, CLion, and the IJWB plug-in on Ubuntu, I have a manual test procedure to confirm that all of the GUI pieces function correctly.  We realized last week that I wasn't testing `--config everything` as part of that, but I should be.

**Comment by jwnimmer-tri** [comment]
I don't do these tests anymore (the CLion users on Drake do).  Over to @DamrongGuoy in case you want to have any kind of testing checklist, when you bless upgrades.  If not, you are more than welcome to close it.
