### ISSUE TITLE
Multilane Technical debt - Documentation / renaming

### ISSUE THREAD

**Issue by agalbachicar** [RobotLocomotion/drake#8898]
The following TODOs in multilane are related to documentation and renaming:

- [x] [loader.h:39](https://github.com/RobotLocomotion/drake/blob/master/automotive/maliput/multilane/loader.h#L39) --> Almost done in GDoc.
- [x] [road_curve.h:168](https://github.com/RobotLocomotion/drake/blob/master/automotive/maliput/multilane/road_curve.h#L168) --> Trivial.

**Comment by hidmic** [comment]
And PR #9332 addresses the second bullet.
