### ISSUE TITLE
Multilane Technical debt - Missing tests

### ISSUE THREAD

**Issue by agalbachicar** [RobotLocomotion/drake#8899]
The following TODOs in code are there to remember addressing tests / modifying tests:

- [ ] [multilane_builder_test.cc:23](https://github.com/RobotLocomotion/drake/blob/master/automotive/maliput/multilane/test/multilane_builder_test.cc#L23) --> Trivial.
- [x] [multilane_loader_test.cc:42](https://github.com/RobotLocomotion/drake/blob/master/automotive/maliput/multilane/test/multilane_loader_test.cc#L42) and [multilane_loader_test.cc:45](https://github.com/RobotLocomotion/drake/blob/master/automotive/maliput/multilane/test/multilane_loader_test.cc#L45) --> Trivial.
- [x] [multilane_loader_test.cc:549](https://github.com/RobotLocomotion/drake/blob/master/automotive/maliput/multilane/test/multilane_loader_test.cc#L538) --> implies creating a Group interface and then refactoring that test.
- [ ] [multilane_types_compare.h](https://github.com/RobotLocomotion/drake/blob/master/automotive/maliput/multilane/test_utilities/multilane_types_compare.h#L31) --> here and there are functions that compare different coordinates with the same tolerance, e.g. EndpointXy. A general review of tolerances for linear, angular and derivative values needs to be done. (#9239)

**Comment by hidmic** [comment]
Taking this one.

**Comment by agalbachicar** [comment]
Taking the third bullet.

**Comment by agalbachicar** [comment]
Closing this issue as it has already been migrated to downstream repository.
