### ISSUE TITLE
Multilane Technical debt - Miscellaneous

### ISSUE THREAD

**Issue by agalbachicar** [RobotLocomotion/drake#8901]
The following list has miscellaneous TODOs in multilane:

- [ ] [builder.cc:176](https://github.com/RobotLocomotion/drake/blob/master/automotive/maliput/multilane/builder.cc#L121)
- [ ] Verify when `explicit_end` is used that not only `EnpointZ` but also `(x, y, theta)` match between the input point and the end `Endpoint` from the new `Connection`.

**Comment by jwnimmer-tri** [comment]
Per #11603, the automotive folder is deprecated, so I'll close this issue as "won't fix"; @agalbachicar if this issue is still important to you, please re-open it in a different issue tracker.

\CC @liangfok FYI
