### ISSUE TITLE
car_sim_lcm has inverted steering and throttle control

### ISSUE THREAD

**Issue by sammy-tri** [RobotLocomotion/drake#8922]
When running `car_sim_lcm` according to the instructions from https://github.com/RobotLocomotion/drake/blob/master/automotive/README.md#running-the-dynamics the steering angle control seems to control the vehicle's velocity, and the throttle/brake controls seem to affect the wheel angle.

**Comment by sammy-tri** [comment]
Assigning to @liangfok based on git history.  Apologies if you're not the right person for this.

**Comment by jwnimmer-tri** [comment]
Resolved as of #9474.
