### ISSUE TITLE
pydrake: Make unittest tolerance semantics for `np.array`s related to `CompareMatrices`

### ISSUE THREAD

**Issue by EricCousineau-TRI** [RobotLocomotion/drake#8958]
Per comment here:
https://github.com/robotlocomotion/drake/pull/8956#issuecomment-395849867

`np.allclose` has two tolerances with default values, `rtol=1e-05` and `atol=1e-08`, which are combined in the [following fashion](https://docs.scipy.org/doc/numpy-1.11.0/reference/generated/numpy.allclose.html):
> `absolute(a - b) <= (atol + rtol * absolute(b))`

Test case authors should be wary of these semantics.

My ideal realization of this is to make some mixins for `unittest.TestCase` that handle `np.array`s in a more elegant fashion, and provide a closeness test whose semantics are closer to those of `drake::CompareMatrices`.

\cc @SeanCurtis-TRI

**Comment by SeanCurtis-TRI** [comment]
It doesn't seem the link to the comment is as target as you'd like -- when I click on it, it takes me to the block of comments, but not the comment specifically.

[This link](https://reviewable.io/reviews/robotlocomotion/drake/8956#-LEVdQLI8Uvrw3zTJIXx:-LEVdOEa9vIqgf9peMKD:bh1wnhh) might be better.

**Comment by EricCousineau-TRI** [comment]
Did most of this with the introduction of `numpy_compare` (#11386). Still need to address the semantics issue.
