### ISSUE TITLE
SceneGraph `GS_THROW_IF_CONTEXT_ALLOCATED` should have terminal parentheses

### ISSUE THREAD

**Issue by SeanCurtis-TRI** [RobotLocomotion/drake#8959]
SceneGraph.cc has a malformed macro leading to callsites that look like:

`GS_THROW_IF_CONTEXT_ALLOCATED`

it needs to become

`GS_THROW_IF_CONTEXT_ALLOCATED()`

**Comment by jwnimmer-tri** [comment]
To be precise, we want `GS_THROW_IF_CONTEXT_ALLOCATED();` (with the semicolon placed at each call site).

**Comment by SeanCurtis-TRI** [comment]
This will be a race condition -- these particular semantics are going away. So, I'll see which is more immediately convenient: adding the semi-colon or just nuking the macro entirely (vis a vis semantics overhaul).
