### ISSUE TITLE
drake_visualizer import error: no module named vtkRenderingOSPRayPython

### ISSUE THREAD

**Issue by RobotXiaoFeng** [RobotLocomotion/drake#8964]
## Description

Hi, I am new to drake and am trying to run the kuka_iiwa example here: https://github.com/RobotLocomotion/drake/tree/master/examples/kuka_iiwa_arm.
I build drake using bazel then follow the instructions in the example. However, when I try to launch drake_visualizer, there is an 

> Traceback (most recent call last):
  File "\<string>\", line 1, in \<module>\
  File "/home/shawn/.cache/bazel/_bazel_shawn/d9ec32c4c5898474a9a58c9aa25df3a4/external/drake_visualizer/lib/python2.7/site-packages/director/drakevisualizerapp.py", line 3, in \<module>\
    from director import mainwindowapp
  File "/home/shawn/.cache/bazel/_bazel_shawn/d9ec32c4c5898474a9a58c9aa25df3a4/external/drake_visualizer/lib/python2.7/site-packages/director/mainwindowapp.py", line 2, in \<module>\
    from director.componentgraph import ComponentFactory
  File "/home/shawn/.cache/bazel/_bazel_shawn/d9ec32c4c5898474a9a58c9aa25df3a4/external/drake_visualizer/lib/python2.7/site-packages/director/componentgraph.py", line 2, in \<module>\
    from director.fieldcontainer import FieldContainer
  File "/home/shawn/.cache/bazel/_bazel_shawn/d9ec32c4c5898474a9a58c9aa25df3a4/external/drake_visualizer/lib/python2.7/site-packages/director/fieldcontainer.py", line 1, in \<module>\
    import vtk
  File "/home/shawn/.cache/bazel/_bazel_shawn/d9ec32c4c5898474a9a58c9aa25df3a4/execroot/drake/bazel-out/k8-opt/bin/tools/drake_visualizer.runfiles/drake/external/vtk/lib/python2.7/site-packages/vtk/__init__.py", line 97, in \<module>\
    from .vtkRenderingOSPRay import *
  File "/home/shawn/.cache/bazel/_bazel_shawn/d9ec32c4c5898474a9a58c9aa25df3a4/execroot/drake/bazel-out/k8-opt/bin/tools/drake_visualizer.runfiles/drake/external/vtk/lib/python2.7/site-packages/vtk/vtkRenderingOSPRay.py", line 9, in \<module>\
    from vtkRenderingOSPRayPython import *
ImportError: No module named vtkRenderingOSPRayPython

It seems that a vtkRenderingOSPRayPython.py is missing? I found a vtkRenderingOSPRayPython.so in that path.

And it seem that the pre-compiled package has the same problem. 

## Reproduction

I build the drake_visualizer with
> cd drake
> bazel build //tools:drake_visualizer

And I build the python bindings

then set PYTHONPATH using 
> cd drake-build
> export PYTHONPATH=${PWD}/install/lib/python2.7/site-packages:${PYTHONPATH}

then run the drake_visualizer with
> cd drake
> bazel-bin/tools/drake_visualizer

## Debug Information

* What operating system are you running Drake on?
(e.g. Ubuntu 16.04, macOS 10.13)

    > Ubuntu 16.04

* Is this an issue with (a) C++, (b) Python, or (c) the distributed tools
(e.g. `drake-visualizer`)?

    > drake-visualizer

* Are you (a) building `drake` from source, or (b) from a binary release?

    > I am building drake from source.

* What version of `python` are you using?

    > Python 2.7.12

my PYTHONPATH

    > '/home/shawn/open-source/drake-build/install/lib/python2.7/site-packages', '/home/shawn/open-   source/drake', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-x86_64-linux-gnu', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages/gtk-2.0'

* If you are building from source or using the `drake` C++ library as an
external:

    * What version of Bazel and CMake are you using?

        > bazel 0.12.0
        >cmake 3.5.1

    * If you are using Bazel, please provide the host settings in your present
    project workspace:

        > clang version 4.0.0-1ubuntu1~16.04.2 (tags/RELEASE_400/rc1)
        >Target: x86_64-pc-linux-gnu
        >Thread model: posix
        >InstalledDir: /usr/bin

* If you are building `drake`
[from source](http://drake.mit.edu/from_source.html):

    * What git commit of `drake` are you using?

        > a1c5fde

    * Are you building `drake` with Bazel or CMake?

        > Bazel

    * Are you using `drake` directly, or consuming it as an external?

        > directly, through python binding?

**Comment by jwnimmer-tri** [comment]
Possibly related to #8789.

However, 
```console
$ bazel build //tools:drake_visualizer
$ bazel-bin/tools/drake_visualizer
```
works just fine for me on Ubuntu 16.04, using latest master.

Please fill out the full bug report template that was provided when you opened the issue.  If we can't reproduce the problem (what commands did you run? what OS? what revision of Drake? what is your PYTHONPATH?), we can't help fix it.

**Comment by RobotXiaoFeng** [comment]
I've fill the bug report template.

**Comment by EricCousineau-TRI** [comment]
Thanks for using the template!
Just out of curiosity, can I ask if you can post the full stack trace to that import error? I'm curious which module in VTK Python is requesting OSPRay at this point.

Also, I see that you may be mixing up the Python bindings build; at present, you won't be able to import `pydrake` from the Bazel-ran version of `drake_visualizer`; since you are using the binary package from 2018-02-05 but a commit from the past few days, there may be some weird stuff going on with version mixing.

Can you try doing `bazel run //tools:drake_visualizer` in a fresh terminal, with no extra `PYTHONPATH` set?

If that still does not work, can you try running the command with a completely fresh environment?
```
$ alias bash-isolate='env -i HOME=$HOME DISPLAY=$DISPLAY SHELL=$SHELL TERM=$TERM USER=$USER PATH=/usr/local/bin:/usr/bin:/bin bash --norc'
$ bash-isolate
bash-4.3$ cd drake
bash-4.3$ bazel run //tools:drake_visualizer
```

**Comment by RobotXiaoFeng** [comment]
Hi Eric,
I've post the full stack trace~

`bazel run //tools:drake_visualizer` in a fresh terminal without any extra set also fails. 

And 
> $ alias bash-isolate='env -i HOME=$HOME DISPLAY=$DISPLAY SHELL=$SHELL TERM=$TERM USER=$USER PATH=/usr/local/bin:/usr/bin:/bin bash --norc'
$ bash-isolate
bash-4.3$ cd drake
bash-4.3$ bazel run //tools:drake_visualizer
gives the same error as well.

I moved from windows to ubuntu only recently, maybe this problem is due to some inappropriate settings? 

Also, the binary is downloaded and try after I get this error with the build using bazel, so I think maybe it is not due to a mix use of different versions?

**Comment by mws262** [comment]
Another coworker and I are having this issue too. I found a stupid hack to get around it. I imagine altering things in the bazel-bin folder is evil, but maybe this will help you diagnose the true root of the issue.

The error happens .../drake/bazel-bin/tools/drake_visualizer.runfiles/drake/external/vtk/lib/python2.7/site-packages/vtk/vtkRenderingOSPRay.py:

```
from __future__ import absolute_import
try:
    # use relative import for installed modules
    from .vtkRenderingOSPRayPython import *
except ImportError:
    # during build and testing, the modules will be elsewhere,
    # e.g. in lib directory or Release/Debug config directories
    from vtkRenderingOSPRayPython import *
```

Replace with something like:

```
from __future__ import absolute_import
try:
    # use relative import for installed modules
    from .vtkRenderingOSPRayPython import *
except ImportError:
    print "Oh no, vtkRenderingOSPRayPython cannot load. Oh well."
```

**Comment by RobotXiaoFeng** [comment]
@mws262 LOL

**Comment by mws262** [comment]
This issue and several others resolved for me when I downgraded CLion from a 2018 version to 2017.3.
The Bazel plugin for CLion has not yet been updated for 2018.

**Comment by RobotXiaoFeng** [comment]
This issue resolved for me after I reinstalled lightdm, however I have not figured out why.

**Comment by EricCousineau-TRI** [comment]
If y'all are able to, can y'all post the output of the following commands?
```
cd drake
bazel build //tools:drake_visualizer
( cd bazel-bin/tools/drake_visualizer.runfiles/drake/external/vtk/lib && LD_LIBRARY_PATH=${PWD} ldd python2.7/site-packages/vtk/vtkRenderingOSPRayPython.so | sort | sed 's#/home/.*\.runfiles/#{runfiles}/#g' )
```
An example from my system:
https://gist.github.com/EricCousineau-TRI/a9517021eba7f51a30d0fa8c1d3c9f11#file-drake_8964_output-txt

@jamiesnape Can I ask if you know what may be happening here?

As an aside, you can automate the @mws262's hack if you apply the following patch:
https://gist.github.com/EricCousineau-TRI/a9517021eba7f51a30d0fa8c1d3c9f11#file-drake_8964_workaround-patch

**Comment by RobotXiaoFeng** [comment]
Mine here: 
https://gist.github.com/RobotXiaoFeng/cbcd499ebe5d233e69dc49d1e9c15710#file-drake_8964_output-txt

**Comment by kuindersma** [comment]
https://gist.github.com/kuindersma/e04fa74fbe26ddbcf70816b6389a2747#file-drake-viz-output-txt

**Comment by jamiesnape** [comment]
@kuindersma `sudo apt install libtbb2`

**Comment by kuindersma** [comment]
@jamiesnape that fixed it. Thx!
