### ISSUE TITLE
New constructor for Monomial class

### ISSUE THREAD

**Issue by frankpermenter** [RobotLocomotion/drake#8977]
Take VectorX\<Variable\> and Eigen::VectorXi as input and construct a Monomial object.

Ex: 
```
Monomial( vars , exponent)

where vars = ("x", "y", "z") and exponent = (1,3,4).
```
The reverse operation (converting a Monomial to Eigen::VectorXi) would also be useful 
```
Ex:
x^2yz converts to (2,1,1)
```
as would the reverse operation that converts a Polynomial to a MatrixXi:
```
Ex:
xy^2z^3 + xz converts to    

(1, 2, 3
 1, 0, 1)
```

**Comment by jwnimmer-tri** [comment]
Since `Variables` is unsorted, I think we instead need `VectorX<Variable>` and `VectorXi` as the two arguments.

**Comment by soonho-tri** [comment]
@jwnimmer-tri, I agree. The only caveat is that `Variables` is actually ordered by `Variable::Id`. But I agree that this ordering is highly likely not the one that users expect.

@frankpermenter , could you update the issue? Also, please add the reverse operation on the `symbolic::Polynomial` to the first comment.

**Comment by frankpermenter** [comment]
The "reverse" operation that takes a Monomial (or Polynomial) to a VectorXi (or MatrixXi) of exponents would also be useful.

> Ex: convert the Monomial x^2 y to [2,1]  and the polynomial x y^2 z^3 + z^2 to 
[1,2,3
 0,0,2]

**Comment by soonho-tri** [comment]
@frankpermenter , can you either post your working branch here or send the link to me?

**Comment by frankpermenter** [comment]
@soonho-tri 
See https://github.com/frankpermenter/drake/blob/monomialbasis/solvers/sos_utils.cc

The function "ExponentsToMonomials" implements the requested Monomial constructor and the function "GetPolynomialExponents" implements the reverse operation.
