### ISSUE TITLE
`rgbd_renderer_vtk_test` fails on some configurations if `show_window=true` and multi-sampling is enabled

### ISSUE THREAD

**Issue by fbudin69500** [RobotLocomotion/drake#8996]
## Description

`rgbd_renderer_vtk_test` fails on some configurations if `show_window=true` and multi-sampling is enabled because of a bug in the NVidia drivers. This bug has been reported to NVidia but their bug tracker is private, so I cannot link the bug report in this issue.

The background color bleeds through opaque foreground with OPENGL multisampling ON. This happens only for the center pixel, but this makes `rgbd_renderer_vtk_test` fail.

## Reproduction

To reproduce this this bug, you need to revert #8668 and set [`show_window=true`](https://github.com/RobotLocomotion/drake/blob/master/systems/sensors/rgbd_renderer.h#L45) .

* What operating system are you running Drake on?
Ubuntu 16.04 with NVidia graphics card.

**Comment by EricCousineau-TRI** [comment]
Closing, as this is resolved by #8668, and the core issue is due to NVidia drivers.
