### ISSUE TITLE
Migrate time-varying LQR from matlab sha

### ISSUE THREAD

**Issue by joycezyu** [RobotLocomotion/drake#9013]
## Description

> Per slack discussion under #dynamics with @hongkai-dai, @RussTedrake, @sherm1, I would like to request the implementation of the time-varying Linear Quadratic Regulator functionality in the C++ version of drake. tvlqr is available in the matlab version of drake, so I guess transferring to c++ shouldn't be too bad.

**Comment by RussTedrake** [comment]
n.b. original version is here:
https://github.com/RobotLocomotion/drake/blob/last_sha_with_original_matlab/drake/matlab/systems/%40DrakeSystem/tvlqr.m

i can try to do this sometime in the next few days.

**Comment by junhyeokahn** [comment]
It would be also nice to see ```runTrajectorySwingUpAndBalance.m``` in the previous tag in the c++ version of drake.

**Comment by mpetersen94** [comment]
Any updates on this?

**Comment by joycezyu** [comment]
We have a hacky-ish version of `tvlqr` implemented locally. Hope to PR in the near future!

**Comment by joycezyu** [comment]
@junhyeokahn The local version of `tvlqr` lives in TRI for now due to the legal issues... I will post here if things change

**Comment by akshitj1** [comment]
Have implemented a draft version for TimeVaryingLQR tested with perching glider [here](https://github.com/akshitj1/drake_plants/blob/master/src/glider/tvlqr.h). Will raise a PR in near future. Linking as it might be helpful for someone to refer meanwhile.
