### ISSUE TITLE
Question on API : CalcArticulatedBodyInertiaCache

### ISSUE THREAD

**Issue by junhyeokahn** [RobotLocomotion/drake#9015]
Hello, I have a question on ```CalcArticulatedBodyInertiaCache```.
The argument of the function is ```context```, ```PositionKinematicsCache``` and ```ArticulatedBodyInertiaCache```.
If ```PositionKinematicsCache``` has to be synced with ```context```, why the API requires ```PositionKinematicsCache``` as an argument?
I think inertia matrix could be computed only with ```State``` in the ```context```

Also, what is the API to get generalized inertia? (Inertia matrix in joint space)

**Comment by sherm1** [comment]
Hi, @junhyeokahn. The cache object isn't yet stored in the Context and automatically synced. It will be there once PR #7668 is fully merged into master.

One way to get the generalized inertia (we usually call it the "mass matrix") is with the method [MultibodyTree::CalcMassMatrixViaInverseDynamics()](http://drake.mit.edu/doxygen_cxx/classdrake_1_1multibody_1_1_multibody_tree.html#a33fc1c4cfefa9f3e1bc7d702ec20869e).
