### ISSUE TITLE
drake-jenkins-bot comments 36 times with "Can one of the admins verify this patch?"

### ISSUE THREAD

**Issue by hazelnusse** [RobotLocomotion/drake#9019]
Perhaps I did something outside the correct workflow, but it seems like this shouldn't happen.

Example here:
https://github.com/RobotLocomotion/drake/pull/9018

**Comment by sherm1** [comment]
Sorry, Luke. Known bug, see  #3537. I believe I have whitelisted you now.

**Comment by hazelnusse** [comment]
No problem, I'll verify that whitelisting solves the problem on my next pull request.
