### ISSUE TITLE
RgbdCamera: `RegisterVisual` does not record when a visual is not registered; fails when capsules are added

### ISSUE THREAD

**Issue by EricCousineau-TRI** [RobotLocomotion/drake#9032]
Ran into a case where `RgbdCamera` was trying to render an URDF with a `capsule` geometry.

Since it is not yet registered, it caused `shape_matched` to be `false`, and return `nullopt` from `RgbdRendererVtk::RegisterVisual`.
However, `RgbdCamera` does not check the return value:
https://github.com/RobotLocomotion/drake/blob/55f68a6/systems/sensors/rgbd_camera.cc#L129
and just assumes that the body is already registered:
https://github.com/RobotLocomotion/drake/blob/55f68a6/systems/sensors/rgbd_camera.cc#L211

This causes the following call to fail upon calling `CalcOutput`:
https://github.com/RobotLocomotion/drake/blob/55f68a6/systems/sensors/rgbd_renderer_vtk.cc#L266

\cc @kunimatsu-tri

**Comment by kunimatsu-tri** [comment]
Oops, sorry about that and thanks for the fix!
