### ISSUE TITLE
Feature request: Sugar function to evaluate a matrix of symbolic expressions with an Environment

### ISSUE THREAD

**Issue by mitiguy** [RobotLocomotion/drake#9049]
In the symbolic::Expression class, It would be helpful to have a "sugar function (static method) -- possibly called Evaluate -- whose first argument is a matrix of symbolic expressions and whose second argument is a symbolic::Environment (maps symbolic variables to values).

Ideally, this "sugar" function would evaluate each of its elements and return an appropriately sized matrix of type double.  

If the symbolic expression fails to evaluate to a number, it should throw an exception (at least for this sugar function).

**Comment by soonho-tri** [comment]
FYI, the sugar function should look like the following:

```c++
// Evaluates a symbolic matrix `m` using the `env` by evaluating each element.
auto Evaluate(const MatrixX<Expression>& m, const Environment& env) {
  return m.unaryExpr([&env](const Expression& e) { return e.Evaluate(env); });
}
```
