### ISSUE TITLE
`hermitian_continuous_extension` tests fail on mac

### ISSUE THREAD

**Issue by ggould-tri** [RobotLocomotion/drake#9060]
Tests introduced in #8950 failed on mac CI.  A representative failure example is:

https://drake-jenkins.csail.mit.edu/view/Continuous%20Production/job/mac-highsierra-clang-bazel-continuous-everything-release/795/

**Comment by hidmic** [comment]
I think this might be related to a similar issue I faced some time ago (https://github.com/RobotLocomotion/drake/issues/8316). Let me open a PR with the relevant lines shortened.

**Comment by jwnimmer-tri** [comment]
Ah, indeed!  We submitted a fix to cpplint (google/styleguide#342) for this, and its been accepted.  However, RobotLocomotion/styleguide#10 is stalled, which means that we haven't merged the newer cpplint into Drake yet, so we are still prone to this bug.

**Comment by jamiesnape** [comment]
> Ah, indeed! We submitted a fix to cpplint (google/styleguide#342) for this, and its been accepted. However, RobotLocomotion/styleguide#10 is stalled, which means that we haven't merged the newer cpplint into Drake yet, so we are still prone to this bug.

Do we know what is delaying that? It has been more than two months now.

**Comment by jwnimmer-tri** [comment]
That seems like a discussion for RobotLocomotion/styleguide#10's thread.

**Comment by jamiesnape** [comment]
True, my apologies.
