### ISSUE TITLE
Implement DoEvalGeneric for constraints and costs to factor out duplicates

### ISSUE THREAD

**Issue by soonho-tri** [RobotLocomotion/drake#9068]
From https://github.com/RobotLocomotion/drake/pull/9056#issuecomment-400732835

**Comment by soonho-tri** [comment]
@hongkai-dai , could you handle this one?

**Comment by hongkai-dai** [comment]
Will handle this issue on top of your PR #9074

**Comment by soonho-tri** [comment]
Thank you, Hongkai!
