### ISSUE TITLE
Eigen version static assertion fail in binary version

### ISSUE THREAD

**Issue by junhyeokahn** [RobotLocomotion/drake#9075]
Hi, I installed drake binary in my ubuntu 16.04 xenial by
```
curl -o drake.tar.gz https://drake-packages.csail.mit.edu/drake/continuous/drake-latest-xenial.tar.gz
sudo tar -xvzf drake.tar.gz -C /opt
```
And I ```find_package(drake)``` in my cmake and try to do optimization.
But I got the following error
```
/opt/drake/include/drake/common/autodiff.h:15:1: error: static assertion failed: Drake requires Eigen >= v3.3.3.
 static_assert(EIGEN_VERSION_AT_LEAST(3, 3, 3),
/opt/drake/include/drake/common/autodiffxd.h:232:69: error: ‘MakeAutoDiffScalar’ was not declared in this scope                                                                                            
     return MakeAutoDiffScalar(m_value * other, m_derivatives * other);
```
I think I am including right ```Eigen``` which is located in ```/opt/drake/include/eigen3```

How could I fix it?
By the way in the Mac, it works well with the same code.

**Comment by jwnimmer-tri** [comment]
Please see http://drake.mit.edu/getting_help.html; this is likely to be a user assistance help question, not a bug in Drake.
