### ISSUE TITLE
AddLinearConstraint being slow

### ISSUE THREAD

**Issue by hongkai-dai** [RobotLocomotion/drake#9081]
MathematicalProgram::AddLinearConstraint takes a lot longer time with symbolic form than the matrix form.

**Comment by hongkai-dai** [comment]
cc @mpetersen94

**Comment by soonho-tri** [comment]
@hongkai-dai and @mpetersen94 , do you have some examples indicating the problem? (should be good test cases as well after a fix)

**Comment by hongkai-dai** [comment]
I remember after the commit https://github.com/RobotLocomotion/drake/commit/e4ad4ebdf72f89db9589c2e3819e6998d9237457, AddLinearConstraint gets about twice slower.

One case is in `GlobalInverseKinematics`, where it parses a lot of linear constraint. You may try https://github.com/RobotLocomotion/drake/blob/master/multibody/dev/test/global_inverse_kinematics_reachable_test.cc.

**Comment by jwnimmer-tri** [comment]
Unless we can point to a concrete benchmark that is slow, we should close this issue.  Do we have anything recent to point to?

**Comment by hongkai-dai** [comment]
Not really, we can close this issue
