### ISSUE TITLE
Compile the Fortran version of SNOPT

### ISSUE THREAD

**Issue by jwnimmer-tri** [RobotLocomotion/drake#9099]
As it turns out, to make progress on #7984, we first need to know how to teach Bazel to compile the Fortran version of SNOPT.  In the SNOPT archive, see `src/Submakefile` target named `src_snopt`.  That is doing `libtool --mode=compile --tag=FC  gfortran` on approx 40 fortran source files, and then `interfaces/Submakefile` has a `snopt_c` target that adds in one more fortran file and the cwrap C file.  We will need to teach Bazel how to run the analogous commands.

I propose that we do that in a first build-system-only PR(s), prior to attacking the API in porting in #7984.  We could add new labels that we compile in CI, but aren't used by MathematicalProgram yet.

**Comment by jwnimmer-tri** [comment]
\CC @jamiesnape FYI.  I am not going to work on this immediately.  (Still TBD on prioritization within the Drake project plan.)

A quick google search doesn't show much in the way of fortran support.  I doesn't like like `.f` files can appear in `cc_library` sources, either.

One solution might be to genrule-copy `somecode.f` to `somecode_f.c` and then use `copts = ["--lang", "f90"]` or however it's spelled.

Another solution might be to precompile snopt and have Bazel download it.

Another solution would be to set CC to a compiler wrapper (like now nvcc support works).

**Comment by jamiesnape** [comment]
I looked at Fortran compiling sometime ago when we used to compile IPOPT. Using the same ideas as `rules_go` seemed to most viable the last time I looked, but it was going to be a fair amount of work.

**Comment by jamiesnape** [comment]
It works as really one or two files Fortran files in `snopt-interface`, really, though, I thought. We can use SNOPT provided binaries for the core library. Not sure compiling from source gains a great deal, but if it is needed, we should definitely precompile.

**Comment by jwnimmer-tri** [comment]
I didn't think the SNOPT releases contained any binaries, though (where are they in the archive)?  Only the student version has binaries IIRC.

My read was that yes we need to compile the 1 Fortran files in `snopt-interface`, but that we also need to compile most of `snopt/src/*.f` from the SNOPT sources.

**Comment by jamiesnape** [comment]
> I didn't think the SNOPT releases contained any binaries, though (where are they in the archive)? Only the student version has binaries IIRC.

Unless something has changed, they were a separate download from the same page as the source archive, `http://ccom.ucsd.edu/~optimizers/downloads/software/licensed?id=<id>`

**Comment by jamiesnape** [comment]
Regardless, I am sure all they do is run their own build scripts, so it seems like just uploading and using a precompiled version is exponentially easier. Their binaries are probably shared libraries, so we may even have to do that anyway since we need a static library for the redistributable packages.

**Comment by jwnimmer-tri** [comment]
@hongkai-dai I have a very questionable first draft of this work pushed to https://github.com/jwnimmer-tri/drake/commits/snopt_cwrap now.  The toyA example from SNOPT folks compiles and runs okay for me, tested on Ubuntu with both Clang and GCC.  This might be enough to unblock your own experimentation for the API porting.

I am going to see if that branch's approach is workable enough to push to master, with enough rework.  One challenge is that the snopt_cwrap build is actually relatively difference bewteen 7.5 and 7.6 release, much moreso than the f2c build is, so I am going to have to be careful about how I deal with version skew.

**Comment by jwnimmer-tri** [comment]
It turns out that the `-x f95` trick will not work on macOS.  On Ubuntu, both /usr/bin/gcc and /usr/bin/clang-4.0 understand it and do the right thing (with clang just delegating to gcc under the hood).  On macOS, clang knows that f95 is a real language (the error message for misspelled -x foo is different), but doesn't know that handling f95 means calling homebrew gcc or gfortran or f951.

**Comment by jwnimmer-tri** [comment]
In #9101, I have a proposal where we just shell out to `gfortran` in `genrule`, which is [apparently what google does itself](https://groups.google.com/forum/#!topic/bazel-discuss/x81efJSmBMk) anyway?  That link has the info about what if we needed to use the same CFLAGS for gfortran as the rest of the C++ code in Drake, but I actually think we _don't_ want to do that?  Anyway, I hope this would be enough to bootstrap us.

**Comment by jamiesnape** [comment]
Yes, I think #9101 should be sufficient for our needs.
