### ISSUE TITLE
QP controller fails when setting use_new_kinsol = true

### ISSUE THREAD

**Issue by hongkai-dai** [RobotLocomotion/drake#910]
The new kinsol is needed when we want to use geometric Jacobian  to track body orientation. I will make sure the current QP controller works with the new kinsol first, before adding geometric Jacobian to QP controller.

**Comment by tkoolen** [comment]
Can this be closed?

**Comment by rdeits** [comment]
Yup, we're using the new kinsol in sim and hardware now
