### ISSUE TITLE
Upload detached signature files for binary releases and add links to documentation

### ISSUE THREAD

**Issue by jamiesnape** [RobotLocomotion/drake#9139]
e.g., `drake-latest-xenial.tar.gz.sha256` and `drake-latest-xenial.tar.gz.sig` for SHA-256 checksum and detached GPG signature of file.

**Comment by EricCousineau-TRI** [comment]
Per f2f, this will be worked on shortly.

**Comment by jamiesnape** [comment]
Checksum upload was added in https://github.com/RobotLocomotion/drake-ci/commit/66139dd14212318753cba3eb4bd0f1f95d6fcfb5. Need to update the drake documentation, which I will do when the detached signature files are added.

**Comment by jwnimmer-tri** [comment]
FYI Whatever ends up here, I would end up reusing for the monthly tagged releases.  Might be worth backlog => low?

**Comment by jamiesnape** [comment]
Sure, maybe medium even (low pretty much equals backlog for me at the moment).

**Comment by EricCousineau-TRI** [comment]
Setting to "low", with a target date of mid-November. That work?

**Comment by jwnimmer-tri** [comment]
Sure, I am in no hurry to sign the releases.  Checksums are OK for now.

**Comment by jamiesnape** [comment]
Note, the monthly S3 packages do get signed since I manually upload those (add `.asc` to a given filename and verify with the key at https://drake-packages.csail.mit.edu/drake/release/drake.asc, which is the same key as the apt packages). Basically, to me, this ticket is an appendix to an automated release process. Once that happens, it is additional infrastructure and security.

**Comment by jwnimmer-tri** [comment]
All of the binaries on https://github.com/RobotLocomotion/drake/releases/ pages now have sha256 and sha512 files (checksums).

We don't have actualy signatures, but for now I'm ok with the chain of trust going through `https://github`.
