### ISSUE TITLE
Fix sweeping suppressions with `rgbd_renderer_ospray_test`

### ISSUE THREAD

**Issue by m-chaturvedi** [RobotLocomotion/drake#9179]
This is with regards to @sammy-tri's [ comment](https://github.com/RobotLocomotion/drake/pull/9174#pullrequestreview-140104904).

`bazel test --runs_per_test=10 --config=tsan -c dbg --test_output=all //systems/sensors:rgbd_renderer_ospray_test`

**Comment by SeanCurtis-TRI** [comment]
As part of my platform review duties, I'm assigning this to the author. If you feel there's a better assignee, feel free to change it.

**Comment by SeanCurtis-TRI** [comment]
Closed as being an attic artifact.
