### ISSUE TITLE
Replace Drake Skylark functions with ones from Skylib where possible

### ISSUE THREAD

**Issue by jamiesnape** [RobotLocomotion/drake#9199]
Path manipulation functions are one example.

See https://github.com/bazelbuild/bazel-skylib.

**Comment by jamiesnape** [comment]
Turns out your current method of factoring out calls that would normally be in the WORKSPACE into `//tools/workspace:default.bzl` means that Skylib cannot be used in other repository rules, so that needs to be worked out first.

**Comment by jwnimmer-tri** [comment]
We can do this incrementally as we revisit or rewrite any particular logic.  We won't bother cleaning up old code just for the sake of it.
