### ISSUE TITLE
Create test workspace inside of `drake` tree to immediately test external workspaces

### ISSUE THREAD

**Issue by EricCousineau-TRI** [RobotLocomotion/drake#9210]
Per f2f with @jamiesnape during meeting.

Modalities to test:
- [ ] Bazel - perhaps just touch analysis phase, `bazel analyze-profile`, or lint `libdrake.so` 
- [ ] CMake - just run off of install

Relates https://github.com/RobotLocomotion/drake/pull/9207

**Comment by jwnimmer-tri** [comment]
Some of the `install_test` do this, to some extent.  When we find new regressions that they have missed, then we can add more of them.
