### ISSUE TITLE
Python bindings with multiple inheritance can cause segfaults

### ISSUE THREAD

**Issue by pvarin** [RobotLocomotion/drake#9243]
Follow up from a Slack conversation with @EricCousineau-TRI 

## Description

Adding bindings for classes with multiple inheritance can cause segfaults.

## Reproduction
 
This issue came up while I was adding python bindings for the InverseDynamicsController: https://github.com/RobotLocomotion/drake/commit/88c3dd03154af479b4d641749943a187fb558666.

Changing the order of inheritance in the InverseDynamicsController C++ class causes a test to fail with a segfault: https://github.com/pvarin/drake/commit/95d20d3c6a734f7ddc8884e7ecf7f39e0bce410b

Adding the `py::multiple_inheritance()` tag fixed the issue with the one test https://github.com/pvarin/drake/commit/c88165c09ef138c3d84ee93ed301714af0ade01d. But created another issue where segfaults occurred when adding trivial and seemingly unrelated systems to a diagram https://github.com/pvarin/drake/commit/265a673ed4b77784cce4c1f4691c3df90ff5aabc.

## Debug Information

I'm running this on Ubuntu 16.04, with Python version 2.7.12.

EDIT(eric):

## Mitigation

If Python does not yet need information about a secondary interface (e.g. `StateFeedbackControllerInterface`), then we can get around this by simply ensuring that `LeafSystem` is first in the inheritance list.

However, once we want to leverage this casting, we'll need to fix this issue.

**Comment by EricCousineau-TRI** [comment]
Relates inheritance re-ordering in #9236.
