### ISSUE TITLE
Need to verify that cache implementation matches cache documentation

### ISSUE THREAD

**Issue by sherm1** [RobotLocomotion/drake#9251]
PR #9113 alleges to complete the cache implementation, but leaves caching disabled by default. Per [discussion there](https://github.com/robotlocomotion/drake/pull/9113#pullrequestreview-145001635), the code that manages dependencies within Diagrams is tricky enough that the intended behavior needs to be spelled out in precise detail in the design document (PR #9136), then used to verify that the code matches.

After we're sure the code & design intent match, we'll enable caching by default.

**Comment by tri-ltyyu** [comment]
Waiting for PR to enable caching by default.

**Comment by sherm1** [comment]
Status: PR #10979 in review to address this issue.
