### ISSUE TITLE
MBP's API to retrieve force element.

### ISSUE THREAD

**Issue by amcastro-tri** [RobotLocomotion/drake#9253]
Implement `MultibodyPlant::gravity_element()` so that users have access to the plant's gravity. Also useful since it'll allow access to `UniformGravityFieldElement::CalcGravityGeneralizedForces()` which allow us to compute `tau_g(q)`.

Related #9131 for gravity compensation.

**Comment by sherm1** [comment]
`MBP::gravity_field()` exists and resolves this issue.
