### ISSUE TITLE
Refresh Ubuntu AMIs for Ubuntu 16.04 / Bazel 0.16.1

### ISSUE THREAD

**Issue by jwnimmer-tri** [RobotLocomotion/drake#9275]
In #9212 we changed the setup script to update the Bazel version to 0.16.1.  Please update the AMIs to reflect this change.

**Comment by BetsyMcPhail** [comment]
CI and Jenkins have been updated. As always with Linux AMIs, it's going to take Jenkins awhile to switch over to the new images.
