### ISSUE TITLE
multibodyplant documentation should mention parsing

### ISSUE THREAD

**Issue by RussTedrake** [RobotLocomotion/drake#9286]
The documentation here: https://drake.mit.edu/doxygen_cxx/classdrake_1_1multibody_1_1multibody__plant_1_1_multibody_plant.html#details 
is great, but is not the way 99.5% of users will interact with the code.  Please add the use case of loading from a urdf/sdf here?

**Comment by amcastro-tri** [comment]
I wonder if we'd like something more in the form of a tutorial for this. In that case, would it be part of the Doxygen or should we somehow reference a pdf? ideas or preferences?

**Comment by RussTedrake** [comment]
I think a lot of projects write their tutorials in sphinx, too.  It’s worth considering.

Even a short note in the doxygen could go a long way, too.

**Comment by jwnimmer-tri** [comment]
With the instructions merged in #9312 and my amendments pending in #10058, is there anything remaining to do here?

**Comment by RussTedrake** [comment]
Lgtm
