### ISSUE TITLE
Atlas walking fails with pelvis height below 0.82m

### ISSUE THREAD

**Issue by rdeits** [RobotLocomotion/drake#931]
If the `pelvis_height_above_foot_sole` is set below 0.82m, flat ground walking (as in `runAtlasWalkingSplit`) results in a fall. This is probably because we're hard-coding the LIP model height. 

@kuindersma can we take a look at this when you get back? For now, I'll just make sure that we set that default to a safe number.

**Comment by kuindersma** [comment]
Yes, assign to me

**Comment by kuindersma** [comment]
This appears to have been resolved with the reduction of the foot tracking weights. I was able to run walking tests with 80cm pelvis height using both controller implementations.

**Comment by kuindersma** [comment]
This can be closed
