### ISSUE TITLE
Implement MultiBodyConstraint (MBT equivalent to RigidBodyConstraint) for IK, etc.

### ISSUE THREAD

**Issue by RussTedrake** [RobotLocomotion/drake#9341]
This is a first step to moving IK / planning support from RBT to MBT.

- [x] simple kinematic constraints
  - [x] +python bindings
- [ ] multi-time kinematic constraints
  - [ ] +python bindings
- [x] collision-based constraints
  - [x] +python bindings

**Comment by hongkai-dai** [comment]
I believe we can close this, as `multibody/inverse_kinematics` folder already contain these constraints.
