### ISSUE TITLE
CLion on macOS no longer works

### ISSUE THREAD

**Issue by jwnimmer-tri** [RobotLocomotion/drake#9347]
Discussed at length in slack; https://drakedevelopers.slack.com/messages/C36L0D7D4/convo/C36L0D7D4-1535410503.000100/.  Exploratory testing looks like #8881 is what broke it.  The default macOS toolchain is thought to not be a C toolchain in the IDE.

**Comment by jwnimmer-tri** [comment]
See also bazelbuild/intellij#109 and bazelbuild/intellij#397.

**Comment by jwnimmer-tri** [comment]
\CC @RussTedrake

**Comment by jwnimmer-tri** [comment]
The commit on https://github.com/jwnimmer-tri/drake/commits/macos-clion-workaround appears to work around the problem for now.  Users have to merge it into their local copy, but not commit it to master.

**Comment by RussTedrake** [comment]
Here's the one-liner 
```
git fetch https://github.com/jwnimmer-tri/drake macos-clion-workaround && git cherry-pick daca23091e40bde66bd89f8f206894513fdc7ed6
```

**Comment by jwnimmer-tri** [comment]
It is possible that, instead of the above patch, setting `BAZEL_USE_CPP_ONLY_TOOLCHAIN=1` in the environment (before launching CLion) would also get things working on macOS.

**Comment by RussTedrake** [comment]
Tested the environment variable patch, and confirmed that it works!  Woohoo!
