### ISSUE TITLE
documentation for get_generalized_contact_forces_output_port gives no indication of what the format/type of the output is

### ISSUE THREAD

**Issue by RussTedrake** [RobotLocomotion/drake#9393]
http://drake.mit.edu/doxygen_cxx/classdrake_1_1multibody_1_1multibody__plant_1_1_multibody_plant.html#a1d355c7fc6c5c09a52e9fd8daf026ddf

The only way I know how to infer it is by digging into the source code.

**Comment by RussTedrake** [comment]
(and it looks like a BasicVector of size num_velocities, which puzzles me)

**Comment by jwnimmer-tri** [comment]
Duplicate of #13146.
