### ISSUE TITLE
Add symbolic formula for isinf / isfinite

### ISSUE THREAD

**Issue by jwnimmer-tri** [RobotLocomotion/drake#9404]
In general, we should support most common functions from https://en.cppreference.com/w/cpp/numeric/math in our Expression overloads.  Mostly we add only when needed, beyond a nice starter pack that we already have on master.

Recently I needed `isinf` in work that ended up not making it to master.  I should add `isinf` anyway, since its could easily be needed in Drake for, e.g., simulation.

**Comment by jwnimmer-tri** [comment]
\CC @soonho-tri FYI

**Comment by soonho-tri** [comment]
@jwnimmer-tri, please feel free to assign this to me if you haven't started implementing the feature.

**Comment by jwnimmer-tri** [comment]
Sure, thanks.

While we could make this its own formula term, I just thinking of just reusing Eq / Lt / Gt formulas comparing the argument with `ExpressionConstant{numeric_limits<double>::infinity()}`, or -inf, etc.

**Comment by soonho-tri** [comment]
I like the idea. I'll implement that.
