### ISSUE TITLE
A list of must-have bindings in MBT

### ISSUE THREAD

**Issue by amcastro-tri** [RobotLocomotion/drake#9423]
This is a simple list of bindings we could implement right now given the C++ APIs are already in place:
- SetFreeBodyPoseOrThrow()
- SetFreeBodySpatialVelocityOrThrow()
- CalcAllBodyPosesInWorld()
- CalcAllBodySpatialVelocitiesInWorld()
- EvalBodyPoseInWorld()
- EvalBodySpatialVelocityInWorld()

For methods like `CalcAllBodyPosesInWorld()` and `CalcAllBodySpatialVelocitiesInWorld()` we'll most likely want to **return** a vector with the results rather than passing a mutable argument.
Options for doing this are:
1. Writing that API in C++ and bind that.
2. Write a lambda wrapping the current C++ API as for instance done [here.](https://github.com/RobotLocomotion/drake/blob/master/bindings/pydrake/multibody/multibody_tree_py.cc#L188)

**Comment by EricCousineau-TRI** [comment]
Relates #9311.

Is it possible to just merge this issue into that one?

**Comment by amcastro-tri** [comment]
I actually made this one separately since it is very specific low hanging fruit compared to #9311.
