### ISSUE TITLE
MultibodyTree::GetModelInstanceName missing unit tests

### ISSUE THREAD

**Issue by jwnimmer-tri** [RobotLocomotion/drake#9430]
From #9406, the new method `MultibodyTree::GetModelInstanceName` lacks a unit test that bad-instance is detected and that the artisinally-crafted error string is correct.  According to the review discussion `multibody_tree.h:964`, other methods also suffer from the same lack.

High priority because new PRs are cargo-culting defects.  Maybe an interesting starter issue for @DamrongGuoy.

**Comment by amcastro-tri** [comment]
cc'ing @sammy-tri

**Comment by tri-ltyyu** [comment]
Per scrubbing session, tech debt item...will put in "ready for work".
