### ISSUE TITLE
Mex controllers incorrectly assume that the map pointer is a double

### ISSUE THREAD

**Issue by rdeits** [RobotLocomotion/drake#944]
`constructQPDataPointerMex` and `QPControllermex` both call  

```
memcpy(&pdata->map_ptr,mxGetPr(prhs[6]),sizeof(pdata->map_ptr));
```

Changing `mxGetPr` to `mxGetPrSafe` reveals that the map ptr is actually a uint64, not a double, and we've just been getting lucky that they're the same size. Ick. 

I assume we want pointers to be stored as uint64 (or uint32 as appropriate) not doubles, right?

**Comment by RussTedrake** [comment]
Check out drakeUtil for the (slightly platform dep) logic for how we store pointers.

- Russ

**Comment by rdeits** [comment]
Yup, that's done in #945
