### ISSUE TITLE
Doxygen modules tied to RBT in attic -- disposition them

### ISSUE THREAD

**Issue by SeanCurtis-TRI** [RobotLocomotion/drake#9467]
## Description

There are two (possibly more) modules: `collision_filter_doxygen.h` and `contact_model_doxygen.h`. Both of these discuss details that are both general and *very* specific to the RBT/RBP ecosystem. We've moved RBT/RBP into the attic but the modules are still prominently featured in the main modules section (see [Collision Filter Concepts](http://drake.mit.edu/doxygen_cxx/group__collision__filter__concepts.html) and [Compliant Contact in Drake](http://drake.mit.edu/doxygen_cxx/group__drake__contacts.html)).

Several things need to be done:
  - [ ] Those details/discussions that are deeply tied to RBT/RBP and are not going to be applied to SG/MBP should be likewise attic'd in the doxygen. Possibly, create a `@group` for containing that: soon to be deprecated or some such thing.
  - [ ] The files need to be curated, dividing what should be kept moving forward and what should be moved. The simplest approach now, is to attic the whole thing and only pull the useful bits out when the new version is authored.

/cc @jwnimmer-tri @sherm1

**Comment by sherm1** [comment]
In PR #9136 I changed the Module title to "Collision Concepts (RigidBodyPlant only)" and referenced this issue in a TODO.
