### ISSUE TITLE
Inconsistent use of the doxygen @bug tag calls out a few obscure TODO items

### ISSUE THREAD

**Issue by RussTedrake** [RobotLocomotion/drake#9493]
and places them right at the top of our doxygen table of contents.
http://drake.mit.edu/doxygen_cxx/bug.html

Looks like they are mostly (exclusively?) from @sherm1 .  Please consider changing these to TODOs.

**Comment by sherm1** [comment]
I didn't realize `@bug` had that ugly side effect. I'll fix.
