### ISSUE TITLE
Typo in Doxygen comments

### ISSUE THREAD

**Issue by carismoses** [RobotLocomotion/drake#9525]
In drake/multibody/inverse_kinematics/inverse_kinematics.h line 37, the description for p_BQ says "The position of the point Q, rigidly attached to frame B, measured and expressed in frame A." Based on the variable naming I am assuming this should end with "...measured and expressed in frame B."

**Comment by sherm1** [comment]
Thanks, Caris. Yes, that is wrong as written. The point is actually p_BQ and should read "... measured and expressed in frame B." I will fix it along with some other multibody things in PR #9489.
