### ISSUE TITLE
Provide symbolic substitution (Expr -> Expr)

### ISSUE THREAD

**Issue by soonho-tri** [RobotLocomotion/drake#9555]
For now, we only allow "Var -> Expr" case.

/cc @shensquared , @hongkai-dai

**Comment by jwnimmer-tri** [comment]
Note that #16014 (pydrake only) is related to this.

**Comment by jwnimmer-tri** [comment]
In pydrake, we have `Unapply` now (see above).

For C++ users, we have `VisitExpression` which the user can call using their own visitor that _could_ be used to implement structural expression pattern matching and substitution, as one example.  Possibly that basic architecture is sufficient for the need?

@shensquared or @hongkai-dai is there some use case you have in mind that is not yet supported, or is overly difficult?  Please let me know what's still missing, if anything.

**Comment by hongkai-dai** [comment]
Thanks Jeremy, I think this looks good. Personally I haven't done symbolic substitution using Expr -> Expr yet, but this feature looks nice (especially in pydrake).

**Comment by shensquared** [comment]
Hey, Jeremy! IIRC, this issue was created out of a discussion very similar to Alexandre's request on [Stackoverflow](https://stackoverflow.com/questions/69774737/xreplace-in-drake-symbolic); essentially a change of (external) variable to comply with the SOS `form'.  So your PR and unittest example addressed that; thanks!

**Comment by jwnimmer-tri** [comment]
Okay, thanks!  I will close this for now, since it seems most active interest is from the pydrake side.

If a C++ Drake user finds the issue in the future and would like to have `Unapply` sugar built-in to C++ (instead of needing to roll your own visitor), please speak up and we can re-open.
