### ISSUE TITLE
Add regression test to prevent unplanned removal of public API

### ISSUE THREAD

**Issue by EricCousineau-TRI** [RobotLocomotion/drake#9564]
It'd be nice to have a record of (a subset of) the public symbols that Drake offers, and have a small regression test that will fail if a public symbol is removed / renamed without a plan.

For C++, it'd be easy to leverage the stuff in `mkdoc.py` to generate that list; it could also be used to track publicly available headers (though I'm not sure how we'd handle forwarding of symbols).
For Python, it may take a bit more time to figure out the minimal set of symbols (e.g. not requiring that `pydrake.__init__` have `sys` imported).

It wouldn't be perfect, in that it would require manual update, as we do with `build_components`, but we could at least roll it into the same script.

Example case:
#9489 removed `MultibodyTree::AllocateDefaultContext`, which broke downstream code usage in Anzu. It'd have been nice to put a test that would automatically complain about the loss of this public API member.

**Comment by jwnimmer-tri** [comment]
I'm not sure the problem with #9489 was that the author and reviewers were unaware that an API was being removed.  I'm not sure that this acute proposal will add much value.

**Comment by sherm1** [comment]
Right. At least for me I didn't realize this was already in use outside of Drake. Even so I would have left it there deprecated but couldn't figure out a way to make it work since an MBTree shouldn't be able to allocate System resources without a System present. @EricCousineau-TRI's workaround still requires a change to existing code -- it keeps the API but changes the circumstances in which it may be called.

I think Drake API wranglers like me should start building Anzu. In that case I would have prepared a PR to upgrade Anzu to the new API.

**Comment by jamiesnape** [comment]
> At least for me I didn't realize this was already in use outside of Drake.

Could we ever know? The best we can probably do here is offer a fixed deprecation period for any change, I think.

**Comment by jamiesnape** [comment]
Or maybe a slightly less friendly, but useful error message or comment with migration instructions when that is not possible, given the major refactoring that happens any given day here.

**Comment by EricCousineau-TRI** [comment]
I'm going to close this for now. We have some brief docs about testing with `drake-external-examples`:
https://drake.mit.edu/downstream_testing.html

**Comment by jamiesnape** [comment]
I guess I will fix this during #12783 anyway, but it is anything but solved. `drake-external-examples` tests the mechanics of the build, not the API.

**Comment by EricCousineau-TRI** [comment]
Aye, will re-open for now. (And sorry Jeremy - I didn't look at the issue ownership :( )

**Comment by jamiesnape** [comment]
FTR https://manpages.debian.org/testing/dpkg-dev/dpkg-gensymbols.1.en.html would diff the API from month-to-month (or however often we build packages).

**Comment by jwnimmer-tri** [comment]
I am a bit interested in running symbol linters as part of the release process, but moreso about leaking private symbols accidentally, than trying to carefully guard what public ABI symbols we export.  Code reviews seem to working OK for that purpose for now.
