### ISSUE TITLE
Purge old dynamics methods

### ISSUE THREAD

**Issue by RussTedrake** [RobotLocomotion/drake#957]
I think that we want to keep the old kinsol methods for now (since IK and planners use them), but at this point i think we can safely zap the old dynamics methods, which accounts for the gross featherstone structure and a lot of the cruft in the rigidbodymanipulator c++ class.

**Comment by tkoolen** [comment]
OK, I think that's a good approach. The new dynamics methods do rely on kinematics cache from the new doKinematics method, so both the new doKinematics and the old one would need to be called during this transition period. A little nasty, but I think it should work fine.
