### ISSUE TITLE
lcm systems are a mess

### ISSUE THREAD

**Issue by RussTedrake** [RobotLocomotion/drake#9604]
Just lost a few hours trying to muck through what should have been a simple addition to our lcm systems toolchain.  The contents of that directory are terrifying.

We have many way to "serialize" between lcm message types and data types (e.g. vectors).  `Serializer`, `TranslatorBase`, `LcmAndVectorBaseTranslator` (which is not a `TranslatorBase`, by the way).  It's very hard to figure out what's recommended, because there are almost no examples of most of them outside of their immediate test cases.   

I think we need to pick and stick with one type of Serialization approach, move all of the tools/examples over to that, and purge the rest.

**Comment by jwnimmer-tri** [comment]
Resolved via #10514.
