### ISSUE TITLE
pydrake: Tests timeout due to `matplotlib` font cache

### ISSUE THREAD

**Issue by EricCousineau-TRI** [RobotLocomotion/drake#9607]
Certain tests timeout due to the `matplotlib` font cache being built, such as:
```
//bindings/pydrake:py/all_test
//bindings/pydrake/systems:drawing_graphviz_example_test
```

Some potential solutions:
* Disable the tests.
* Pre-build font cache on CI, and:
   * Add `local` test tags.
   * Find another solution to permit `bazel test` to leverage pre-built font-cache.

@jamiesnape Any other thoughts?

Relates #8752

**Comment by jamiesnape** [comment]
> Pre-build font cache on CI

Note it was pre-built on provisioned CI, but it does not help unprovisioned CI even if you do add the necessary flags to allow bazel to leverage it.

Just increase the test size, I would say. If the test sizes are borderline enough for the font cache to be an issue, they are probably too small.
