### ISSUE TITLE
Wiring an input of the wrong size to robot_plan_interpolator does not produce an error

### ISSUE THREAD

**Issue by RussTedrake** [RobotLocomotion/drake#9626]
I observed this in PR #9625  in `lcm_plan_interpolator.cc`.  The `status_receiver` `measured_position` output port was providing a vector of size `kNumJoints*3` into the  input of `robot_plan_interpolator` that was expecting an input of size `kNumJoints*2`.  It was silently working (by taking the top `kNumJoints*2` elements). 

I assume we would agree that this is not the correct behavior?

I looked quickly, but I think that perhaps the violation in not really in the `robot_plan_interpolator`, but perhaps in a failure at `System<T>::EvalVectorInput`. I don't want to go down this rabbit-hole now, but also did not want to forget. 

cc @avalenzu  (who I think did the initial wiring?)

**Comment by jwnimmer-tri** [comment]
We have a framework unit test that connecting mismatched port sizes throws:

https://github.com/RobotLocomotion/drake/blob/c7f246998a4eeafc48feab4bc108d955bfd04b91/systems/framework/test/diagram_builder_test.cc#L294-L318

It was merged in #9875, a few weeks after this bug report.  I think we can safely close this.
