### ISSUE TITLE
Consider breaking up `documentation_pybind.h`

### ISSUE THREAD

**Issue by EricCousineau-TRI** [RobotLocomotion/drake#9644]
At present, we dump all documentation bits into `documentation_pybind.h`.
It hurts CLion usage, as the current file is huge.

It shouldn't be too hard to have `mkdoc.py` generate different headers based on the directory (or namespace); it should also be easy to specify what target directories / namespaces we want to generate (to quell `genfiles`s requirement for outputs).

Proposed example:
From:
```
#include "drake/bindings/pydrake/documentation_pybind.h"
pydrake_doc.drake.math.RigidTransform.ctor.doc_4
```
Directory-based (w/ redundancy):
```
#include "drake/bindings/pydrake/doc/drake/math.h"
pydoc_drake_math.drake.math.RigidTransform.ctor.doc_4
```
Namespace-based (no redundancy):
```
#include "drake/bindings/pydrake/doc/drake/math.h"
pydoc_drake_math.RigidTransform.ctor.doc_4
```

Namespace stuff would be non-nested (if we use naiive specification); alternatively, we take the explicit approach and specify exactly which namespaces go in each file.

\cc @jwnimmer-tri @jamiesnape @amcastro-tri

**Comment by jamiesnape** [comment]
I think that was the original plan, to be honest. Probably says more about CLion, than `documentation_pybind.h`, however.

**Comment by jwnimmer-tri** [comment]
My vote would be for one header per top-level directory (attic, common, manipulation, systems, multibody, etc) to keep it simple for now (that set changes rarely -- the second-tier folders change more often).  And to be clear, still only run mkdoc once for all of libdrake, but have it emit a dozen'ish doc files.  That should mitigate IDE complaints and rebuild times -- bazel will not recompile uses of the header that is regenerated, as long as its contents stay the same.  If we find that the string tables are still too large, we can add in the second layer later on.

**Comment by jamiesnape** [comment]
> My vote would be for one header per top-level directory [...]

Agreed.

**Comment by EricCousineau-TRI** [comment]
I believe that #11131 may have slowed down `mkdoc` generation from ~50s to ~80s (on my beastly Puget); not a huge pain point, but given that all modules currently depend on this, it's a bit of a bottleneck that could be better alleviated by addressing this issue in the near-term.

Assigned `medium` priority for now.

**Comment by EricCousineau-TRI** [comment]
Hm... On my laptop (8 cores), this is taking >5min to complete...

**Comment by jamiesnape** [comment]
> 8 cores

It only uses one, if I am not mistaken.

**Comment by EricCousineau-TRI** [comment]
That is correct; sorry, had posted number of cores to indicate possible resource starvation (not just intrinsic timing issues).

**Comment by jwnimmer-tri** [comment]
My laptop is did not show that kind of slowdown.  I knew in #11131 I did some O(N) things that should be O(1) dicts; if it's a pain point I could amend that PR a little bit, before we fracture the header?

**Comment by jamiesnape** [comment]
I'm not seeing it either, but it would be quicker to try rather than to split the file at this stage, I think.

**Comment by EricCousineau-TRI** [comment]
Copying @RussTedrake's comment from Slack (not bumping priority yet, but noting the pain point):

> russtedrake Yesterday at 6:04 PM
> I happened to just catch a snapshot of how long it actually takes to compile the bindings on my mac  Action bindings/pydrake/documentation_pybind.h; 594s remote-cache, darwin-sandbox .  It's not my main workflow; I'm not complaining.  Just thought 10 min was impressive.  Especially since this was testing a change to a single variable name that amounted to < 20 characters.  :wink: 

[link](https://drakedevelopers.slack.com/archives/C0JNAGTNW/p1579561448000600)

**Comment by EricCousineau-TRI** [comment]
That being said, @jwnimmer-tri, if you have time, could you point out which spot would need the modifications to be O(1)?

**Comment by jwnimmer-tri** [comment]
I believe the slowdown introduced by #11131 was `extract_comment`'s search of `deprecations` for the `MACRO_INSTANTIATION` associated with the current comment.  But at this point I'd really just profile the python and see what the actual hot spot is.

**Comment by ToffeeAlbina-TRI** [comment]
This should be worked on in combination with the bindings work
RobotLocomotion/drake#7889

**Comment by EricCousineau-TRI** [comment]
Lower priority, as `attic` has been separated out.

**Comment by jamiesnape** [comment]
Honestly, I would close this. It ends up being inseparable from #7889 and highly coupled to whatever the issue is for splitting libdrake.so (which I can't find at the moment).

**Comment by EricCousineau-TRI** [comment]
SGTM. Will re-open if duration / lack of granularity pains us more in the future before #7889 lands.
