### ISSUE TITLE
python sphinx is missing LeafSystem._DeclareAbstractOutputPort and related methods 

### ISSUE THREAD

**Issue by RussTedrake** [RobotLocomotion/drake#9651]
The documentation here:
http://drake.mit.edu/pydrake/pydrake.math.html?highlight=rigidtransform#pydrake.math.RigidTransform

does not capture the constructor bindings I see here:
https://github.com/RobotLocomotion/drake/blob/master/bindings/pydrake/math_py.cc#L69

Not sure how wide spread the issue is.  Just wanted to capture the instance I observed.

**Comment by RussTedrake** [comment]
A few others I've observed to be missing:
- Isometry3 constructors.
- LeafSystem._DeclareAbstractOutputPort

**Comment by jamiesnape** [comment]
There is a Sphinx configuration option. By default constructors are not documented separately. I will look into changing the option.

**Comment by RussTedrake** [comment]
Thanks.  I don’t see how that could have address the leafsystem bindings, though.

**Comment by jamiesnape** [comment]
So this issue is not just about constructors? Can you update the title/description?

**Comment by EricCousineau-TRI** [comment]
Because we decided to use private names for overloaded methods, `_MethodName`, we run into issues like this.

My preference is that we only allow certain methods in; we may be able to work this into our current `sphinx_pydrake` plugin.

**Comment by jamiesnape** [comment]
There is a Sphinx setting for private members to be documented. Either we set that, change our naming convention, or accept that these methods are not going to appear in the online docs. Adding the plugin should be a last resort. We should not overcomplicate this.

**Comment by EricCousineau-TRI** [comment]
I don't want private members documented unless they're intended to be used by users.

I would like to know what other projects do when they have private / protected methods to be overridden; if they do not prefix with `_`, then we shouldn't.
If they do, then we should target specific members.

**Comment by sherm1** [comment]
I just re-discovered this problem in #10136 when I added some new LeafSystem method (DeclareDiscreteState). Most of LeafSystem's useful content is protected.

**Comment by jamiesnape** [comment]
@sherm1, therefore the useful content in LeafSystem was not documented online, or it affected you in #10136 in some other way?

**Comment by sherm1** [comment]
Right, there was no documentation online for the new methods I added, even though they had elaborate doxygen in C++. I'm not blocked by it, but it seems like a major gap in the Python docs. Those protected methods are really necessary for Python users to make Drake Systems.
