### ISSUE TITLE
fix inconsistent use of `timestep` and `time_step` throughout the codebase

### ISSUE THREAD

**Issue by RussTedrake** [RobotLocomotion/drake#9661]
I think different authors have used different variants.  I don't have a strong opinion, but would like things to be consistent.

**Comment by jamiesnape** [comment]
Almost raised this in https://github.com/RobotLocomotion/drake/pull/9200. `timestep` is not in the dictionary, of course.

**Comment by jwnimmer-tri** [comment]
The two-word is used approx 900 times, the one-word approx 300 times.  The 900-times is mostly dynamics code (multibody, simulator), the 300-times is mostly Russ code (traj opt).

Shall we settle on the two-word version for new code?

Is it worth fixing the one-word version in old code (possibly only non-API-changing locations, to avoid churn)?

**Comment by RussTedrake** [comment]
I'm happy to go with the two-word version, and even with changing the API at some point if we decide that's best.  I agree that there is significant value in consistency.

**Comment by sherm1** [comment]
Grammarhow favors "time step": https://grammarhow.com/timestep-time-step-or-time-step/
