### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by rahulvigneswaran** [RobotLocomotion/drake#9711]
While trying to install Drake on Ubuntu 16.04, I followed the documentation available in [official site](http://drake.mit.edu/python_bindings.html#using-python-bindings) but am stuck with an error in the `cmake -DWITH_GUROBI=ON -DWITH_MOSEK=ON ../drake`  step. 
![Screen Grab](https://user-images.githubusercontent.com/37276766/47211082-42040800-d3b2-11e8-9fcf-4b8336f3ab50.png)

**Comment by hongkai-dai** [comment]
Which version of Mosek and Gurobi do you have on your machine?

**Comment by EricCousineau-TRI** [comment]
Howdy @rahulvigneswaran! I'm not sure if you've yet had a chance to revisit this issue. If you want, you can see the logic for how CMake will try to find the location of Gurobi in known locations:
https://github.com/RobotLocomotion/drake/blob/94bb5e4d1626dc3d5d983a7835b7047b50dcd1c6/cmake/modules/FindGurobi.cmake#L4-L11

I'm going to close this for now.
Please do let us know if you still need help, in which case we can re-open the issue.
