### ISSUE TITLE
WSGSender and Reciever classes

### ISSUE THREAD

**Issue by RussTedrake** [RobotLocomotion/drake#9731]
As seen in iiwa_lcm.h.  Currently the send/receive logic is a bit buried in the controllers.

**Comment by sammy-tri** [comment]
Did you just want the command receive logic decoupled from the trajectory generation part of the controller (which seems sufficient to simulate a gripper with different controllers)?  Or are you also looking to add a `CommandSender` and a `StatusReceiver` to control/monitor a gripper?

Opened #9760 which disentangles the current code a bit.  If we want to add the other classes I'll either open a followup or amend that PR.
