### ISSUE TITLE
Eigen as a required dependency?

### ISSUE THREAD

**Issue by tkoolen** [RobotLocomotion/drake#974]
I'd like to propose making Eigen a required dependency. My arguments:
* As we're moving more stuff to C++, a larger percentage of our codebase will be unusable without Eigen.
* It's a hassle to remember to use if (eigen3_FOUND) everywhere.
* Why would any system we care about not have Eigen?

What do you think?

**Comment by psiorx** [comment]
I agree.

**Comment by avalenzu** [comment]
I'd be in favor of Eigen as a required dependency too.

**Comment by RussTedrake** [comment]
I agree, too.  I will have to update the distros, but that's easy enough.

in fact, i think we should make matlab optional.  There are definitely systems where we want to be able to compile the c++ tools which don't have matlab.

**Comment by andybarry** [comment]
> matlab optional

exciting!
