### ISSUE TITLE
Update documentation style guide: Doxygen style, Python docstrings

### ISSUE THREAD

**Issue by EricCousineau-TRI** [RobotLocomotion/drake#9745]
Things discussed with @jamiesnape:
- [ ] Conventions for Doxygen docstrings; add this to `doc/doxygen_instructions.rst`
  - e.g. spacing on `@code` blocks, where to place `TODO`s, Math styles, etc.
- [ ] Clarify that we use [Napoleon-style docstrings](https://sphinxcontrib-napoleon.readthedocs.io/en/latest/) for Python

**Comment by EricCousineau-TRI** [comment]
Re: #9735
@jamiesnape I would agree with @sherm1 on the aesthetics, in that we should permit (or even enforce) indentation in `@code` blocks.
After writing the script to automatically change the indentations, and seeing that Doxygen renders properly with indentations, it should be rather easy to make `mkdoc` behave properly with this behavior, and automatically set the indentations on existing code once we decide on something.

If Doxygen doesn't handle it properly at some point, we can address it then.

**Comment by jamiesnape** [comment]
> I would agree with @sherm1 on the aesthetics, in that we should permit (or even enforce) indentation in @code blocks.

We are writing multi-modal documentation and I would not even agree that how documentation looks in source is even the most important modality. But I guess I would be outvoted.

**Comment by jamiesnape** [comment]
> Clarify that we use Napoleon-style docstrings for Python

With whom? Our style guide is non-specific, and it is what our tools accept.

**Comment by jwnimmer-tri** [comment]
One thing we should do sooner rather than later is to forbid doing this:
```
/// A nice log Doxygen comment.
// An implementation comment.
double CalcSomething(...) { ...; }
```

Our mkdoc tooling loses track of the Doxygen comment when it doesn't directly abut the method.

**Comment by SeanCurtis-TRI** [comment]
@mitiguy I don't know if you saw this comment -- but it applies to your style.

**Comment by mitiguy** [comment]
@SeanCurtis-TRI  Thanks - message received.  I'll talk with you about best practice, e.g., how to handle comments I formerly labeled with   
// @internal

**Comment by jwnimmer-tri** [comment]
@mitiguy For one idea, you can look at what I did at https://github.com/RobotLocomotion/drake/pull/10289/files#diff-1cf56ab04d535b7e08ba6aca2d0c2d31 for `rigid_transform` and `matrix`.  IMO there are probably many fine ways to do it.  Even doing `/// @internal Stuff` is probably fine (adding the third slash).

**Comment by mitiguy** [comment]
@jwnimmer-tri -- Thanks for the ideas.  I like the way you did it.

**Comment by EricCousineau-TRI** [comment]
Per f2f, should have a first rough-cut PR with just style-guide suggestions (probably no linter to start).

**Comment by jwnimmer-tri** [comment]
We have some documentation advice captured in https://drake.mit.edu/styleguide/pyguide.html already now.  What (if anything) still needs to be done to resolve this issue?  What is the victory condition?
