### ISSUE TITLE
Enable pre-finalize collision filtering.

### ISSUE THREAD

**Issue by EricCousineau-TRI** [RobotLocomotion/drake#9754]
At present, certain workflows like collision filtering require finalization. While some portions of this workflow (such as getting geometry IDs) are currently marked as needing finalization, but may not actually need it, there are other bits that need topology queries that can realistically only be achieved via finalization.

More specifically, we want to be able to request: `GetBodiesWeldedTo()` (in #9740).

Potential solutions:
- [ ] Remove finalization requirements from methods that don't really need it (possibly `GetBodyFrameIdIfExists()`, `GetBodyFrameIdOrThrow()`, etc.)
- [ ] ~~Add some sort of queuing mechanism when it's necessary, either transparently or explicitly (e.g. `std::function<>`).~~
   - ~~Easiest starting point is explicit queuing.~~
- [ ] ~~Geometry port querying (#9787)~~

\cc @sammy-tri @SeanCurtis-TRI

**Comment by EricCousineau-TRI** [comment]
Could be done via filter groups; filter groups can be mutated pre-finalize (as they are only SceneGraph). Should create checkbox or another issue for sdf parsing.

**Comment by amcastro-tri** [comment]
Even to be **more** specific. We want to get rid of **DRAKE_MBP_THROW_IF_NOT_FINALIZED**:
https://github.com/RobotLocomotion/drake/blob/1b09de88b89a40300ccf047a6af29091c0bd7836/multibody/plant/multibody_plant.cc#L405
