### ISSUE TITLE
Documentation requiring deprecation: output_port_value.h

### ISSUE THREAD

**Issue by SeanCurtis-TRI** [RobotLocomotion/drake#9775]
The [`output_port_value.h`](https://github.com/RobotLocomotion/drake/blob/master/systems/framework/output_port_value.h) file has a TODO indicating that it should have been removed 10/1/2018.

(There may be other such TODOs...worthing scrubbing through.)

**Comment by jwnimmer-tri** [comment]
Fixed in #10051.
