### ISSUE TITLE
Determine if multibody/parsing is dead code

### ISSUE THREAD

**Issue by amcastro-tri** [RobotLocomotion/drake#9781]
The code in `multibody/parsing` was initially written to get the ball rolling for the interaction with OSRC to help us with the SDF parser. The decision was to migrate features from that code directly into `sdformat` and it slowly decayed into disuse.

If nothing from this directory is useful (for instance the `frame_cache.h` code used to specify the pose of a frame in any other frame defined int the file), this code should be eliminated from Drake master.

@sammy-tri, @jwnimmer-tri, anything useful there you'd like to keep?

**Comment by jwnimmer-tri** [comment]
We can always go back and resurrect (in a new home) anything we end up wanting.  I'm okay to remove it.

**Comment by jwnimmer-tri** [comment]
I opened a PR.  Sam can bless the idea there.
