### ISSUE TITLE
Upload SNOPT 7.4 sources into git for use by CI

### ISSUE THREAD

**Issue by jwnimmer-tri** [RobotLocomotion/drake#9803]
As it turns out, every version of SNOPT has various deficiencies, with no single version being monotonically superior to all others.  In order to support ongoing development of MathematicalProgram, we're going to want Drake CI to have access to several revisions of SNOPT, as we explore exactly how to mitigate the deficiencies.

To that end, we'd like to ask that MIT (i.e., @RussTedrake) obtain SNOPT version 7.4 source for use by Drake CI, and that the CI maintainers (i.e., @jamiesnape) uploaded that source to [RobotLocomotion/snopt](https://github.com/RobotLocomotion/snopt/) using some tag like we did with SNOPT 7.6.

(For the record, the SNOPT 7.6 source upload was tracked in #8060.)

Marked as high priority because it relates to #4893 (running SNOPT in parallel), which is a current TRI priority.

**Comment by jwnimmer-tri** [comment]
@RussTedrake I forwarded you emails of TRI's SNOPT 7.4 discussions with SBSI, to kick this off.

**Comment by jwnimmer-tri** [comment]
\CC @EricCousineau-TRI @hongkai-dai @avalenzu @calderpg-tri @sammy-tri

**Comment by EricCousineau-TRI** [comment]
@RussTedrake Can I ask if you've had a chance to reach out to SBSI for the sources? Is there anything I can help with?

**Comment by tri-ltyyu** [comment]
Sent follow-up to SBSI sales

**Comment by RussTedrake** [comment]
sorry that this conversation moved offline.  i forwarded the source code from the snopt developers to @jamiesnape about a month ago.

**Comment by jamiesnape** [comment]
I am not seeing that email. Can you forward it again?

**Comment by jwnimmer-tri** [comment]
The source release for SNOPT 7.4-1.1 is now available at `RobotLocomotion/snopt` branch `2015-02-26` commit `0254e961cb8c60193b0862a0428fd6a42bfb5243`.
