### ISSUE TITLE
Port double_pendulum example to MultibodyPlant

### ISSUE THREAD

**Issue by sherm1** [RobotLocomotion/drake#9811]
~PR #9800 removes dead parsing code. That requires removing examples/double_pendulum which is the only example that was using that dead code. That is actually one of the nicer "hello world" Drake examples, with a beautiful README and short, readable implementation.~

_Edit: The `examples/double_pendulum` demo uses custom SDF parsing; instead, it should use the typical MultibodyPlant parsing routines._

Luke Peterson (@hazelnusse) volunteered to try reworking the example to use MultibodyPlant while retaining its character. I'll mark this as high priority since we don't want to lose the example, though we do want to nuke the dead code.

**Comment by sherm1** [comment]
Luke, after #9800 merges the double_pendulum example will still be functional, but using outdated custom parsing and soon-to-be-deprecated RigidBodyPlant rather than the current MultibodyPlant. Your mission, should you choose to accept it, would be to modernize this and delete the custom parsing files.

**Comment by sherm1** [comment]
@hazelnusse -- Luke, are you going to be able to get to this or would it be better if we reassign it?

**Comment by sherm1** [comment]
@mitiguy, please resurrect this example in modernized form when you have a chance.

**Comment by sherm1** [comment]
Is this issue still active, @mitiguy ?

**Comment by jwnimmer-tri** [comment]
I'm going to remove the example for now -- git remembers, so we can always resurrect a rewrite later.  I'll let you decide whether to close the issue or not.

**Comment by jwnimmer-tri** [comment]
This code no longer exists on the main branch.
