### ISSUE TITLE
cpplint issues an erroneous warning with dealing with single-argument unnamed bool

### ISSUE THREAD

**Issue by mitiguy** [RobotLocomotion/drake#9815]
## Description
In the file rotation_matrix.h, in the private section of the RotationMatrix class,
there appears a RotationMatrix constructor that has a single unnamed bool argument.
cpplint flags this line as an error, saying:
math/rotation_matrix.h:595:  Using C-style cast.  Use static_cast<bool>(...) instead  [readability/casting] [4]

Herein is the code near the time of the commit that discovered it (with PR 9812)
  // TODO(Mitiguy) Remove NOLINTNEXTLINE(readability/casting) when cpplint bug
  // is fixed.  cpplint interprets the unnamed bool in RotationMatrix(bool) as a 
  // C-style cast.  Similarly if bool is changed to int. Strangely, things like:
  // RotationMatrix(const bool) don't trigger the lint error. That suggests
  // naive string matching in cpplint: See issue #XXXX
  // NOLINTNEXTLINE(readability/casting)
  explicit RotationMatrix(bool) : R_AB_() {}

## Reproduction
To reproduce triggering the erroneous warning, remove the following comment
(which appears directly below the constructor).
  // NOLINTNEXTLINE(readability/casting)

> Please provide a minimal snippet of code or shell commands (<10 lines)
that reproduces the issue. 

cd drake/math
bazel build ... -c dbg
bazel test ... -c dbg

## Debug Information
* What operating system are you running Drake on?
Ubuntu 16.04

* Is this an issue with (a) C++, (b) Python, or (c) the distributed tools?
cpplint

* Are you (a) building `drake` from source, or (b) from a binary release?
Source.

* What version of `python` are you using?
Not relevant.

* If you are building from source or using the `drake` C++ library as an
external:

    * What version of Bazel and CMake are you using?
Build label: 0.16.1
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Mon Aug 13 13:43:36 2018 (1534167816)
Build timestamp: 1534167816
Build timestamp as int: 1534167816

    * If you are using Bazel, please provide the host settings in your present
    project workspace:

        > In your workspace, please copy the output of:
        `bazel run @drake//common:print_host_settings`

+ capture_cc_env=external/drake/tools/cc_toolchain/capture_cc.env
+ source external/drake/tools/cc_toolchain/capture_cc.env
++ BAZEL_CC=/usr/bin/gcc
+ /usr/bin/gcc --version
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

* If you are building `drake`
[from source](https://drake.mit.edu/from_source.html):

    * What git commit of `drake` are you using?

        > Replace this with the output of `git rev-parse --short HEAD`.
17e4dab

    * Are you building `drake` with Bazel or CMake?
bazel

    * Are you using `drake` directly, or consuming it as an external?
directly

**Comment by jwnimmer-tri** [comment]
We're not going to fix this.

First, even just looking at for time spent, it is trivial to work around the problem that happens only once every few months, and its hours and hours of time to fix the false positive in the tool.

Second, this code is bad and you shouldn't be writing it that way anyway.  If you want a tag to disable initialization, use an enum class or something that's actually readable to a developer, and not so brittle (many, many things implicitly covert to bool).
