### ISSUE TITLE
The drake/lcmtypes headers are installed twice

### ISSUE THREAD

**Issue by EricCousineau-TRI** [RobotLocomotion/drake#9837]
From https://github.com/robotlocomotion/drake/pull/9830#issuecomment-433653589

> [eric]
> this pr: 7e6e88a
> master (HEAD~): 114ba73
> ```
> $ diff -r build-7e6e88a/ build-114ba73/ | grep 'Only in'
> Only in build-7e6e88a/include/drake/automotive/maliput: simple_phase_provider
> Only in build-7e6e88a/include/drake/geometry: dev
> Only in build-7e6e88a/include/drake/lcmtypes/drake: lcmt_viewer2_comms.hpp
> Only in build-7e6e88a/include/drake/manipulation: dev
> Only in build-7e6e88a/include/drake/systems/sensors: dev
> ```
> Dunno why lcmt_viewer2_comms.hpp only appears in this PR, but that's fine by me.
> 
> [jeremy]
> It's probably because the //manipulation/dev:remote_tree_viewer_wrapper depends on it. However, the //lcmtypes:install_cc_headers rule should have already been installing it, so something weird is going on that we don't understand yet. Can probably defer to a future PR to resolve.
> 
> [eric]
> Ah, it is duplicated:
> ```
> $ find build-* -name '*lcmt_viewer2_comms*'
> build-114ba73/include/drake_lcmtypes/drake/lcmt_viewer2_comms.hpp
> build-114ba73/lib/python2.7/site-packages/drake/lcmt_viewer2_comms.py
> build-7e6e88a/include/drake_lcmtypes/drake/lcmt_viewer2_comms.hpp
> build-7e6e88a/include/drake/lcmtypes/drake/lcmt_viewer2_comms.hpp
> build-7e6e88a/lib/python2.7/site-packages/drake/lcmt_viewer2_comms.py
> ```

**Comment by jwnimmer-tri** [comment]
Actually, _most_ of our lcmtypes are being installed twice, already on master.
