### ISSUE TITLE
Need python bindings for LeafSystem::DeclareInitializationEvent.

### ISSUE THREAD

**Issue by RussTedrake** [RobotLocomotion/drake#9842]
My immediate goal is to accomplish the equivalent of https://github.com/RobotLocomotion/drake/blob/master/systems/lcm/lcm_publisher_system.cc#L92
in a LeafSystem authored in python.

That particular method is templated.  I only actually need to declare the PublishEvent type right now.  But perhaps it's best to add the overloads for the various event types?

I spent a bit of time messing with it, but I think @EricCousineau-TRI can knock it out much faster/better than me.

**Comment by EricCousineau-TRI** [comment]
Will take a whack at it and see...
