### ISSUE TITLE
styleguide, lint: Handle Skylark / Bazel gotchas

### ISSUE THREAD

**Issue by EricCousineau-TRI** [RobotLocomotion/drake#9848]
Per discussion in #9845, we should have a styleguide for advice on writing Starlark / Bazel rules, and we should have linting that automatically enforces this.

\cc @jamiesnape

**Comment by jwnimmer-tri** [comment]
Closing out as "backlog unlikely to reach an actionable state within a reasonable timeframe".  We've survived this long by cargo-culting the existing BUILD files.  It seems like that can continue indefinitely, unless we find new evidence to the contrary.
