### ISSUE TITLE
ubuntu: Upgrade to Bazel >=0.18 - `~/.bazelrc` now ignored by Drake on Bazel 0.16.1

### ISSUE THREAD

**Issue by EricCousineau-TRI** [RobotLocomotion/drake#9863]
I believe this has been discussed on Slack already; long and short of it is, we have a newer version of Bazel on Mac (0.19 is what Homebrew will install), and due to that upgrade, had to put in a compatibility shim (#9849) that has now disconnected Bazel from reading `~/.bazelrc` (which to me is important, as it contains repository cache, remote cache, and possibly some usability options).

The fix should be to upgrade Xenial to Bazel >=0.18.

**Comment by jamiesnape** [comment]
Most Mac users will have 0.19. The shim is for that version.
