### ISSUE TITLE
testURDFcollisionmex Fails for atlas v5 model_convex_hull

### ISSUE THREAD

**Issue by psiorx** [RobotLocomotion/drake#989]
@avalenzu thinks this might be an issue related to collision filter groups in the c++ urdf parser.

He asked me to create an issue so we can resolve this later.

**Comment by RussTedrake** [comment]
we should understand this to make sure that it's not a bug in the c++ parser (but not invest time in updating the matlab implementation, per #2228).

**Comment by amcastro-tri** [comment]
Thanks, on my radar now.

**Comment by tri-ltyyu** [comment]
This is likely specific to RigidBodyPlant. If this is applicable to MultBodyPlant/SceneGraph, please file new issue. Closing for now.
