### ISSUE TITLE
mbp sdf: Consider supporting `//joint/parent` and `//joint/child` to use frames

### ISSUE THREAD

**Issue by EricCousineau-TRI** [RobotLocomotion/drake#9910]
Upstream issue:
https://bitbucket.org/osrf/sdformat/issues/204

**Comment by sherm1** [comment]
@EricCousineau-TRI should this still be open?

**Comment by EricCousineau-TRI** [comment]
I think this is well-enough captured in upstream issues that it doesn't need to be captured here. Closing - thanks!
