### ISSUE TITLE
Mac: Ensure `numpy` and `nlopt` do not conflict

### ISSUE THREAD

**Issue by EricCousineau-TRI** [RobotLocomotion/drake#9916]
Tracking a known an issue for Mac, shown in TravisCI in `drake-external-examples`.

Example failure: [link](https://travis-ci.org/RobotLocomotion/drake-shambhala/jobs/449540487#L970-L972), snippet:
```
Installing nlopt
Error: numpy 1.15.3 already installed
Installing numpy has failed!
```

I believe @jamiesnape's possible solution is to provide an alternative formula for `nlopt` that does not include Python bindings.

**Comment by jamiesnape** [comment]
It is a little more subtle than that, but nevertheless the alternative formula would be https://github.com/RobotLocomotion/homebrew-director/blob/master/Formula/nlopt%402.4.rb.

**Comment by jamiesnape** [comment]
Closed by https://github.com/Homebrew/homebrew-core/pull/39620.
