### ISSUE TITLE
support DSDP as the open-source SDP solver

### ISSUE THREAD

**Issue by hongkai-dai** [RobotLocomotion/drake#9923]
[DSDP](https://www.mcs.anl.gov/hs/software/DSDP/) is an open-source SDP solver in C. It uses University of Chicago [license](https://www.mcs.anl.gov/hs/software/DSDP/Copyright.txt). @jamiesnape and @jwnimmer-tri is this license supported? In #4045 I saw we supported this license before, but then we deleted the software?

**Comment by hongkai-dai** [comment]
related to #3773

**Comment by jamiesnape** [comment]
This line is problematic:
```
Any publication resulting from research that made use of this software 
should cite this document.
```
“Should” is never a good word to find in a license as it is ambiguous as to whether it obligates the user.

**Comment by hongkai-dai** [comment]
Thanks @jamiesnape . This solver is a lower priority. I will work with CSDP solver #9922 first.

**Comment by hongkai-dai** [comment]
Will reopen this issue if we find we need DSDP
