### ISSUE TITLE
Support SDPA as the open-source SDP solver

### ISSUE THREAD

**Issue by hongkai-dai** [RobotLocomotion/drake#9924]
SDPA can be obtained from http://sdpa.sourceforge.net/index.html. It uses GPL-2.0 license.

**Comment by hongkai-dai** [comment]
related to #3773

**Comment by hongkai-dai** [comment]
Thanks @jwnimmer-tri . This is not important yet. I think I will add CSDP to drake before working with SDPA. As mentioned in https://github.com/RobotLocomotion/drake/issues/3773#issuecomment-435644223, CSDP averagely performs better than SDPA, and CSDP is using EPL-2.0 license, compatible with Drake.

**Comment by jwnimmer-tri** [comment]
Maybe just close this issue, in that case?  We can re-open (and start talking to legal) iff we find it to be a hard requirement.
