### ISSUE TITLE
ImageWriter test depends on user permissions

### ISSUE THREAD

**Issue by SeanCurtis-TRI** [RobotLocomotion/drake#9960]
## Description
The test for `ImageWriter` includes a test for validating against a directory against which the program does not have write permissions. Currently, the test is executed with [fingers crossed](https://github.com/RobotLocomotion/drake/blob/master/systems/sensors/test/image_writer_test.cc#L461): a directory has been selected that shouldn't be writable for the user under whose permissions the test is running. This is obviously brittle.

## Reproduction

Run `sudo bazel test systems/sensors:image_writer_test`. 

## Resolution

The test should not rely on these permission. Instead it should:

1. Create sub-directory in temp directory.
2. Change permissions to be unwritable.
3. Run the test against *this* directory.
4. Upon cleanup, restore permissions on directory and delete it.

**Comment by jwnimmer-tri** [comment]
FYI Step (4) is done for you by Bazel, as part of its test runner.  You'd only need to actively clean up if your test logic required it (e.g., if it would affect other cases within the same image_writer_test.cc file).
