### ISSUE TITLE
EPIC: Jacobians with respect to q for MBP

### ISSUE THREAD

**Issue by amcastro-tri** [RobotLocomotion/drake#9971]
We need the capability to compute Jacobians with respect to q (formerly, and incorrectly, called "analytical Jacobians"). Most importantly, for the implementation of our inverse kinematics.

**Comment by mitiguy** [comment]
@EricCousineau-TRI 
I am in the process of changing Jacobian names.
I noticed CalcFrameGeometricJacobianExpressedInWorld is used in several python files, e.g.,
multibody_tree_test.py
multibody_tree_py.cc

I would like to know if there is any reason not to immediately change all of these names to
CalcFrameJacobianWrtQDotExpressedInWorld ?

**Comment by mitiguy** [comment]
I meant CalcFrameJacobianWrtVExpressedInWorld() not QDot.

**Comment by EricCousineau-TRI** [comment]
If it's not too much additional effort, it would be best to deprecate them in lieu of changing them outright.
Per the deadlines in #9366, I intend to deprecate most of MBT, aiming to have the PR submitted tomorrow, hopefully merged by Friday.
If you'd like, I can deprecate the old spellings and add the new (to only `MultibodyPlant`) in that sweep?

I also have a question about needing to have additional work for adding new overloads, but will ask that in #10194 to keep the issues separate.
