### ISSUE TITLE
Port //multibody/benchmarks/free_body:rigid_body_plant_free_body_test to MBP

### ISSUE THREAD

**Issue by jwnimmer-tri** [RobotLocomotion/drake#9974]
The `//multibody/benchmarks/free_body:rigid_body_plant_free_body_test ` is the only thing left under `//multibody/...` that uses or mentions RigidBodyTree.

I assume that the right answer is to port it to MultibodyPlant, is that correct?  (As opposed, say, to deleting it.)

If you want _both_ RBT and MBP copies of this test case, let me know and I can help get that moving, also.

Relates #9783.

**Comment by sherm1** [comment]
This definitely needs converting. No need to retain RBPlant.

**Comment by sherm1** [comment]
attn @mitiguy -- relatively high priority since it is the last RBPlant straggler here.

**Comment by mitiguy** [comment]
Starting it now.
